/*
 Generated from thomas_vs_openclaw_subcommands.json
 Snapshot: 2026-03-01
*/

export type CLIComparisonRow = {
  feature: string;
  thomasPresent: boolean;
  openclawPresent: boolean;
  thomasChildren: string[];
  openclawChildren: string[];
  thomasDepth: number;
  openclawDepth: number;
};

export const CLI_COMPARISON_ROWS: CLIComparisonRow[] = [
  {
    feature: "acp",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["bridge", "client"],
    openclawChildren: ["bridge", "client"],
    thomasDepth: 2,
    openclawDepth: 2,
  },
  {
    feature: "agent",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "agents",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["list", "start", "status", "stop"],
    openclawChildren: ["add", "delete", "list", "set-identity"],
    thomasDepth: 4,
    openclawDepth: 4,
  },
  {
    feature: "and",
    thomasPresent: false,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: ["acp", "agent", "agents", "and", "approvals", "browser", "channels", "clawbot", "completion", "config", "configure", "cron", "daemon", "dashboard", "devices", "directory", "dns", "docs", "doctor", "gateway", "health", "help", "hooks", "logs", "memory", "message", "models", "node", "nodes", "onboard", "pairing", "plugins", "qr", "reset", "sandbox", "security", "sessions", "setup", "skills", "skills", "starts", "status", "supported", "system", "tui", "uninstall", "update", "webhooks"],
    thomasDepth: 0,
    openclawDepth: 48,
  },
  {
    feature: "approvals",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["approve", "list", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "reject", "status"],
    openclawChildren: ["allowlist", "get", "help", "set"],
    thomasDepth: 10,
    openclawDepth: 4,
  },
  {
    feature: "browser",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["action-click", "action-evaluate-script", "action-hover-and-focus", "action-navigate-and-open", "action-scroll-and-scroll-into-view", "action-type-and-press", "action-wait-conditions", "artifact-accessibility-snapshot", "artifact-dom-snapshot", "artifact-har-export", "artifact-pdf-export", "artifact-screenshot", "command-registry-scaffold", "context-set-geolocation", "context-set-user-agent", "context-set-viewport", "data-cookies-export-and-import", "data-storage-snapshot", "download-tracking", "error-normalization", "integration-into-top-level-cli", "json-output-contract", "lifecycle-start-stop-restart", "network-emulate-conditions", "network-set-offline", "open", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "permissions-grant", "permissions-revoke", "profile-create-delete-list", "smoke", "status", "tab-management", "telemetry-console-stream", "telemetry-network-requests", "telemetry-response-body-fetch", "trace-start-stop-export", "upload-helper", "workflow-cases", "workflows"],
    openclawChildren: ["accessibility", "click", "close", "conditions", "console", "cookies", "create-profile", "delete-profile", "dialog", "download", "drag", "errors", "evaluate", "extension", "fill", "focus", "highlight", "hover", "navigate", "open", "pdf", "press", "profiles", "requests", "reset-profile", "resize", "responsebody", "screenshot", "scrollintoview", "select", "set", "snapshot", "start", "status", "stop", "storage", "tab", "tabs", "trace", "type", "upload", "wait", "waitfordownload"],
    thomasDepth: 45,
    openclawDepth: 43,
  },
  {
    feature: "channels",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["add", "auth-validation-helper", "capabilities", "configure", "delivery-acknowledgement-mapping", "docs-generator", "failure-taxonomy", "integration-into-existing-channels-module", "list", "list-enriched-output", "login", "logout", "logs", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "provider-config-schema", "provider-contract-tests", "provider-interface-contract", "registry-loader", "remove", "resolve", "retry-and-backoff-strategy", "secret-resolution-precedence", "status", "test", "throttling-policy", "webhook-bridge-adapter"],
    openclawChildren: ["add", "capabilities", "help", "list", "login", "logout", "logs", "remove", "resolve", "status"],
    thomasDepth: 31,
    openclawDepth: 10,
  },
  {
    feature: "chat",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "clawbot",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["chat", "qr"],
    openclawChildren: ["help", "qr"],
    thomasDepth: 2,
    openclawDepth: 2,
  },
  {
    feature: "codex",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: ["login", "logout", "models", "status"],
    openclawChildren: [],
    thomasDepth: 4,
    openclawDepth: 0,
  },
  {
    feature: "companion",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: ["apply-bundle", "init", "module-disable", "module-enable", "module-list", "status", "verify-bundle", "write-template"],
    openclawChildren: [],
    thomasDepth: 8,
    openclawDepth: 0,
  },
  {
    feature: "completion",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "config",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["get", "set", "show", "unset"],
    openclawChildren: ["get", "set", "unset"],
    thomasDepth: 4,
    openclawDepth: 3,
  },
  {
    feature: "configure",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "cron",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["add", "doctor", "list", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "pause", "preview", "remove", "resume", "run", "status", "update"],
    openclawChildren: ["add", "disable", "edit", "enable", "help", "list", "rm", "run", "runs", "status"],
    thomasDepth: 16,
    openclawDepth: 10,
  },
  {
    feature: "daemon",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["install", "logs", "restart", "start", "status", "stop", "uninstall"],
    openclawChildren: ["help", "install", "restart", "start", "status", "stop", "uninstall"],
    thomasDepth: 7,
    openclawDepth: 7,
  },
  {
    feature: "dashboard",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "devices",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["list", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "pair", "revoke", "status", "verify"],
    openclawChildren: ["approve", "clear", "help", "list", "reject", "remove", "revoke", "rotate"],
    thomasDepth: 11,
    openclawDepth: 8,
  },
  {
    feature: "directory",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["add", "list", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "remove"],
    openclawChildren: ["groups", "peers", "self"],
    thomasDepth: 9,
    openclawDepth: 3,
  },
  {
    feature: "dns",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["setup", "status"],
    openclawChildren: ["(Wide-Area", "help", "setup"],
    thomasDepth: 2,
    openclawDepth: 3,
  },
  {
    feature: "docs",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "doctor",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "doppelganger",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: ["promote", "rollback", "serve-green", "status", "sync", "test"],
    openclawChildren: [],
    thomasDepth: 6,
    openclawDepth: 0,
  },
  {
    feature: "gateway",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["auth-policy-enforcement", "compat-auth-and-rate-limit-middleware", "compat-model-capability-resolver", "compat-request-validation-layer", "configured", "discover", "health-detailed-payload", "install", "logs", "logs-filter", "metrics-snapshot", "openai-chat-completions-non-stream", "openai-chat-completions-stream", "openai-compat-route-scaffold", "openai-tool-call-passthrough-mapping", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-route-package-scaffold", "ops-verify", "probe", "responses-compat-route-scaffold", "responses-create-non-stream", "responses-create-stream-events", "responses-tool-result-mapping", "restart", "run", "start", "state-persistence-model", "status", "stop", "uninstall", "url", "usage-cost"],
    openclawChildren: ["(launchd/systemd/schtasks)", "(launchd/systemd/schtasks)", "(launchd/systemd/schtasks)", "(launchd/systemd/schtasks)", "call", "configured)", "discover", "health", "install", "probe", "restart", "run", "start", "status", "status", "stop", "uninstall", "usage-cost"],
    thomasDepth: 36,
    openclawDepth: 18,
  },
  {
    feature: "health",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "hooks",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["check", "disable", "enable", "info", "install", "list", "update"],
    openclawChildren: ["check", "disable", "enable", "info", "install", "list", "update"],
    thomasDepth: 7,
    openclawDepth: 7,
  },
  {
    feature: "library",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: ["add", "curate", "list", "reindex", "show", "where"],
    openclawChildren: [],
    thomasDepth: 6,
    openclawDepth: 0,
  },
  {
    feature: "live-browser-smoke",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "logs",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "memory",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["compact", "list", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "search", "status"],
    openclawChildren: ["help", "index", "search", "status"],
    thomasDepth: 10,
    openclawDepth: 4,
  },
  {
    feature: "message",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["channel-specific-route-resolver", "delete", "edit", "event-history", "integration-into-cli-group", "list", "mark-sent", "member-kick-and-ban", "member-timeout", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "permissions-view", "pin", "poll-create", "poll-vote-and-close", "reactions-add-remove-list", "retry", "role-assign-and-remove", "schema-and-persistence-refactor", "search", "send", "thread-list", "thread-reply", "unpin", "voice-metadata-stub"],
    openclawChildren: ["ban", "broadcast", "channel", "delete", "edit", "emoji", "event", "kick", "member", "permissions", "pin", "pins", "poll", "react", "reactions", "read", "role", "search", "send", "sticker", "thread", "timeout", "unpin", "voice"],
    thomasDepth: 29,
    openclawDepth: 24,
  },
  {
    feature: "models",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["aliases", "auth", "discover", "fallbacks", "image-fallbacks", "list", "pull", "scan", "set", "set-image", "status", "validate"],
    openclawChildren: ["aliases", "auth", "fallbacks", "image-fallbacks", "list", "scan", "set", "set-image", "status"],
    thomasDepth: 12,
    openclawDepth: 9,
  },
  {
    feature: "node",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["cli-group-scaffold", "command-install", "command-restart", "command-run", "command-status", "command-stop", "command-uninstall", "host-config-model", "host-lifecycle-service", "host-state-store", "install", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify"],
    openclawChildren: ["help", "install", "restart", "run", "status", "stop", "uninstall"],
    thomasDepth: 17,
    openclawDepth: 7,
  },
  {
    feature: "nodes",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["api-routes-and-auth", "approve-action", "camera-action", "canvas-action", "cli-integration-and-parity-tests", "invoke-action", "list-and-status", "location", "location-action", "notify-action", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "pairing-handshake", "pending-approvals", "pending-approvals-p046", "push-payload", "registry-model", "reject-action", "screen-capture-action", "token-rotate-and-revoke"],
    openclawChildren: ["approve", "camera", "canvas", "describe", "help", "invoke", "list", "location", "notify", "pending", "push", "reject", "rename", "run", "screen", "status"],
    thomasDepth: 24,
    openclawDepth: 16,
  },
  {
    feature: "onboard",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "pairing",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "reset", "start", "status"],
    openclawChildren: ["approve", "help", "list"],
    thomasDepth: 9,
    openclawDepth: 3,
  },
  {
    feature: "plugins",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["command-registry-bridge", "config-schema-validator", "diagnostics-collector", "disable", "discovery-scanner", "doctor", "enable", "enable-and-disable-state-store", "extension-catalog", "gateway-handler-registry", "hook-after-response", "hook-after-tool", "hook-before-model", "hook-before-tool", "hook-runner-core", "hook-types-contract", "http-route-registry", "info", "install", "install-from-local-path", "lifecycle-commands-runtime-backed", "list", "list-command-runtime-backed", "manifest-schema", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "package-bootstrap", "registry-core-model", "sample-plugin-skeleton-extension", "service-lifecycle-manager", "show", "tool-provider-injection", "uninstall", "uninstall-cleanup", "update-planner"],
    openclawChildren: ["disable", "doctor", "enable", "help", "info", "install", "list", "uninstall", "update"],
    thomasDepth: 39,
    openclawDepth: 9,
  },
  {
    feature: "qr",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "repl",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "reset",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "sandbox",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["run", "status", "test"],
    openclawChildren: ["explain", "list", "recreate"],
    thomasDepth: 3,
    openclawDepth: 3,
  },
  {
    feature: "security",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "scan", "status"],
    openclawChildren: ["audit", "help"],
    thomasDepth: 8,
    openclawDepth: 2,
  },
  {
    feature: "serve",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "sessions",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "setup",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "skills",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["list", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "show", "sync"],
    openclawChildren: ["check", "info", "list"],
    thomasDepth: 9,
    openclawDepth: 3,
  },
  {
    feature: "starts",
    thomasPresent: false,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: ["acp", "agent", "agents", "and", "approvals", "browser", "channels", "clawbot", "completion", "config", "configure", "cron", "daemon", "dashboard", "devices", "directory", "dns", "docs", "doctor", "gateway", "health", "help", "hooks", "logs", "memory", "message", "models", "node", "nodes", "onboard", "pairing", "plugins", "qr", "reset", "sandbox", "security", "sessions", "setup", "skills", "skills", "starts", "status", "supported", "system", "tui", "uninstall", "update", "webhooks"],
    thomasDepth: 0,
    openclawDepth: 48,
  },
  {
    feature: "status",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "supported",
    thomasPresent: false,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: ["acp", "agent", "agents", "and", "approvals", "browser", "channels", "clawbot", "completion", "config", "configure", "cron", "daemon", "dashboard", "devices", "directory", "dns", "docs", "doctor", "gateway", "health", "help", "hooks", "logs", "memory", "message", "models", "node", "nodes", "onboard", "pairing", "plugins", "qr", "reset", "sandbox", "security", "sessions", "setup", "skills", "skills", "starts", "status", "supported", "system", "tui", "uninstall", "update", "webhooks"],
    thomasDepth: 0,
    openclawDepth: 48,
  },
  {
    feature: "system",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["doctor", "env", "health", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "status"],
    openclawChildren: ["event", "heartbeat", "help", "presence"],
    thomasDepth: 10,
    openclawDepth: 4,
  },
  {
    feature: "telegram",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: ["run"],
    openclawChildren: [],
    thomasDepth: 1,
    openclawDepth: 0,
  },
  {
    feature: "tools",
    thomasPresent: true,
    openclawPresent: false,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "tui",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "uninstall",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: [],
    openclawChildren: [],
    thomasDepth: 0,
    openclawDepth: 0,
  },
  {
    feature: "update",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["apply", "check", "ops-benchmark", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify"],
    openclawChildren: ["status", "wizard"],
    thomasDepth: 8,
    openclawDepth: 2,
  },
  {
    feature: "webhooks",
    thomasPresent: true,
    openclawPresent: true,
    thomasChildren: ["delete", "inbox", "list", "ops-doctor", "ops-export", "ops-inspect", "ops-metrics", "ops-verify", "register", "show", "stats"],
    openclawChildren: ["gmail", "help"],
    thomasDepth: 11,
    openclawDepth: 2,
  },
];

export const COMPARISON_META = {
  suiteDateUtc: '2026-03-01T21:23:54Z',
  source: 'thomas_vs_openclaw_subcommands.json',
  openclawRepo: 'https://github.com/openclaw/openclaw',
  openclawCommit: 'c1428e8df9a497d45b3ed3d35f70419d736fdd4b',
};
