"""Tool capability catalog and immutable runtime policy model."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ToolRuntimePolicy:
    allow_shell: bool
    allow_file_write: bool
    allow_network: bool
    allow_browser: bool
    allow_channels: bool
    allow_git: bool
    require_command_approval: bool
    tool_timeout_s: int
    max_parallel_tools: int
    allowed_paths: tuple[str, ...]
    blocked_commands: tuple[str, ...]


_TOOL_PREFIXES = ("functions.", "function.", "tool.", "tools.", "mcp.", "mcp__")
_WRITE_PREFIXES = (
    "fs.write",
    "fs.delete",
    "fs.remove",
    "fs.move",
    "fs.copy",
    "deploy.",
)
_WRITE_TOOLS = {
    "api.import",
    "api.reload_imported",
    "api.remove",
    "channel_auth",
    "channel_management",
    "create_skill",
    "companion_log_audit_event",
    "config_mgmt.create_snapshot",
    "db.command",
    "db.save_connection",
    "diff.apply_patch",
    "diff.create",
    "eng.format_code",
    "eng.lint",
    "flow_design",
    "flow_execute",
    "git.commit",
    "git.push",
    "intake_set_clipboard",
    "intake_start_watcher",
    "library_add_entry",
    "library_add_research_note",
    "marketplace.create_listing",
    "marketplace.create_order",
    "marketplace.create_review",
    "marketplace.publish_listing",
    "marketplace.register_vendor",
    "messages_create",
    "messages_delete",
    "nodes_create_node",
    "nodes_execute_node",
    "notifications_clear",
    "notifications_create",
    "notifications_mark_read",
    "notify_send",
    "notify_subscribe",
    "paper_trading.propose",
    "paper_trading.recall",
    "paper_trading.review",
    "paper_trading.submit",
    "policy_create_config",
    "preferences_reset",
    "preferences_set",
    "task_management",
    "template_extensions",
    "tray_agent_show_notification",
    "tray_agent_start",
    "tray_agent_stop",
    "upgrade_create_backup",
    "upgrade_ensure_green_venv",
    "upgrade_promote_green_to_blue",
    "upgrade_rollback",
    "upgrade_run_green_tests",
    "upgrade_sync_blue_to_green",
    "upgrade_sync_green_to_blue",
    "workflow_execution",
}
_SHELL_TOOLS = {
    "eng.dead_code",
    "eng.format_code",
    "eng.git_analysis",
    "eng.lint",
    "eng.security_scan",
    "flow_execute",
    "intake_start_watcher",
    "nodes_execute_node",
    "shell.exec",
    "ssh.exec",
    "tray_agent_start",
    "tray_agent_stop",
    "upgrade_create_backup",
    "upgrade_ensure_green_venv",
    "upgrade_promote_green_to_blue",
    "upgrade_rollback",
    "upgrade_run_green_tests",
    "upgrade_sync_blue_to_green",
    "upgrade_sync_green_to_blue",
    "workflow_execution",
}
_EXTERNAL_TOOLS = {
    "companion_get_devices",
    "companion_log_audit_event",
    "db.query",
    "db.save_connection",
    "db.schema",
    "eng.web_extract",
    "flow_execute",
    "git.push",
    "nodes_execute_node",
    "notify_send",
    "notify_subscribe",
    "upgrade_ensure_green_venv",
    "workflow_execution",
}
_EXTERNAL_PREFIXES = (
    "api.",
    "browser.",
    "email.",
    "web.",
    "http.",
    "network.",
    "paper_trading.",
    "gmail.",
    "drive.",
    "calendar.",
    "slack.",
    "ssh.",
    "teams.",
    "discord.",
)
_CHANNEL_PREFIXES = ("email.", "gmail.", "drive.", "calendar.", "slack.", "teams.", "discord.")
_CHANNEL_TOOLS = {
    "channel_auth",
    "channel_capabilities",
    "channel_management",
    "companion_get_devices",
    "companion_log_audit_event",
    "intake_get_clipboard",
    "intake_set_clipboard",
    "intake_start_watcher",
    "notify_get_subscriptions",
    "notify_send",
    "notify_subscribe",
    "tray_agent_show_notification",
}
_SAFE_READ_PREFIXES = ("code.", "investigate.")
_SAFE_READ_TOOLS = {
    "api.list_imported",
    "config_mgmt.check_compliance",
    "config_mgmt.get_statistics",
    "config_mgmt.list_resources",
    "data_format_info",
    "data_load",
    "db.connections",
    "demo_metrics",
    "demo_agent_comparison",
    "demo_benchmark",
    "demo_campaign",
    "demo_task_pack",
    "diff.preview",
    "eng.code_complexity",
    "eng.dependency_tree",
    "eng.detect_encoding",
    "eng.file_type",
    "eng.parse_document",
    "eng.project_stats",
    "eng.system_info",
    "fs.list_dir",
    "fs.read_file",
    "fs.search",
    "library_build_context",
    "library_get_entry",
    "library_list_entries",
    "library_scan_entries",
    "marketplace.get_listing",
    "marketplace.get_order",
    "marketplace.get_vendor",
    "marketplace.search_listings",
    "messages_list",
    "nodes_get_node_status",
    "notifications_get_store",
    "notifications_get_unread_count",
    "notifications_list",
    "policy_evaluate",
    "policy_load_config",
    "preferences_get",
    "preferences_list",
    "rag.search",
    "template_filters",
    "template_rendering",
    "tray_agent_get_status",
    "upgrade_get_paths",
    "upgrade_latest_backup",
}
# Only arguments that the concrete tool interprets as local filesystem paths
# belong here. Generic names such as ``source``, ``target``, ``folder``, and
# ``file_id`` are intentionally absent: several tools use those names for flow
# node IDs, inline data, mailbox folders, or connector object IDs.
_LOCAL_PATH_ARGUMENTS: dict[str, tuple[str, ...]] = {
    "browser.screenshot": ("path",),
    "code.find_definition": ("path",),
    "code.find_references": ("path",),
    "code.project_structure": ("path",),
    "code.search": ("path",),
    "demo_task_pack": ("task_pack_path",),
    "diff.create": ("file",),
    "diff.preview": ("file",),
    "eng.code_complexity": ("path",),
    "eng.dead_code": ("path",),
    "eng.dependency_tree": ("path",),
    "eng.detect_encoding": ("path",),
    "eng.file_type": ("path",),
    "eng.format_code": ("path",),
    "eng.git_analysis": ("repo_path",),
    "eng.lint": ("path",),
    "eng.parse_document": ("path",),
    "eng.project_stats": ("path",),
    "eng.security_scan": ("path",),
    "fs.list_dir": ("path",),
    "fs.read_file": ("path",),
    "fs.search": ("path",),
    "fs.write_file": ("path",),
    "fs.write_protected_file": ("path",),
    "git.blame": ("file",),
    "git.commit": ("files",),
    "git.diff": ("path",),
    "git.log": ("path",),
    "library_add_entry": ("library_root",),
    "library_add_research_note": ("library_root",),
    "library_build_context": ("library_root",),
    "library_get_entry": ("library_root",),
    "library_list_entries": ("library_root",),
    "library_scan_entries": ("library_root",),
    "notifications_clear": ("store_path",),
    "notifications_create": ("store_path",),
    "notifications_get_store": ("store_path",),
    "notifications_get_unread_count": ("store_path",),
    "notifications_list": ("store_path",),
    "notifications_mark_read": ("store_path",),
    "policy_create_config": ("runtime_root",),
    "policy_evaluate": ("runtime_root", "cwd", "sandbox_root"),
    "policy_load_config": ("runtime_root",),
    "upgrade_create_backup": ("project_root",),
    "upgrade_ensure_green_venv": ("project_root",),
    "upgrade_get_paths": ("project_root",),
    "upgrade_latest_backup": ("project_root",),
    "upgrade_promote_green_to_blue": ("project_root",),
    "upgrade_rollback": ("project_root", "backup_dir"),
    "upgrade_run_green_tests": ("project_root",),
    "upgrade_sync_blue_to_green": ("project_root",),
    "upgrade_sync_green_to_blue": ("project_root",),
}
