Option Explicit
' Thomas — desktop app launcher (generated by scripts/thomas_app.py).
' Opens the Thomas desktop shell: a real browser engine around the Thomas
' chrome, so a web tab can load a site that refuses to be framed.
Dim shell, fso, electronExe, desktopDir, runDesktopPs1, appUrl, profileDir, args, answer

Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
desktopDir = "C:\Users\corbe\Thomas\desktop"
electronExe = "C:\Users\corbe\Thomas\desktop\node_modules\electron\dist\electron.exe"
runDesktopPs1 = "C:\Users\corbe\Thomas\scripts\run-desktop.ps1"
appUrl = "http://127.0.0.1:8899/"

If fso.FileExists(electronExe) Then
    ' The shell attaches to a running engine or spawns one itself, and only
    ' stops the engine it started. Nothing to wait for here.
    shell.CurrentDirectory = desktopDir
    shell.Run Chr(34) & electronExe & Chr(34) & " " & Chr(34) & desktopDir & Chr(34), 1, False
    WScript.Quit 0
End If

' The shell is not built yet - a fresh checkout, or setup was never run.
' run-desktop.ps1 installs the dependencies on first run and then launches, so
' offer that rather than dead-ending in a dialog. Visible window on purpose:
' the install takes a minute and silence reads as nothing happening.
If fso.FileExists(runDesktopPs1) Then
    answer = MsgBox("Thomas needs to finish installing its desktop shell before websites will load in web tabs." & vbCrLf & vbCrLf & _
        "This downloads the browser engine and takes about a minute. It only happens once." & vbCrLf & vbCrLf & _
        "Install it now?", 36, "Thomas")
    If answer = 6 Then
        shell.Run "powershell -NoProfile -ExecutionPolicy Bypass -File " & Chr(34) & runDesktopPs1 & Chr(34), 1, False
        WScript.Quit 0
    End If
End If

' Declined, or the installer script is missing. Thomas still opens, but web
' tabs fall back to iframes and sites that refuse framing will show blank.
profileDir = shell.ExpandEnvironmentStrings("%LOCALAPPDATA%") & "\Thomas\AppWindow"
If Not fso.FolderExists(shell.ExpandEnvironmentStrings("%LOCALAPPDATA%") & "\Thomas") Then
    fso.CreateFolder shell.ExpandEnvironmentStrings("%LOCALAPPDATA%") & "\Thomas"
End If
args = " --app=" & appUrl & _
       " --user-data-dir=" & Chr(34) & profileDir & Chr(34) & _
       " --window-size=1440,960 --no-first-run --no-default-browser-check"

On Error Resume Next
shell.Run "msedge" & args, 1, False
If Err.Number <> 0 Then
    Err.Clear
    shell.Run "chrome" & args, 1, False
End If
If Err.Number <> 0 Then
    Err.Clear
    shell.Run appUrl, 1, False
End If
