/* app.js lines 29001-30000 */
export default [
    "                }))",
    "                .filter((line) => Boolean(line.message))",
    "            : [],",
    "        tasks: Array.isArray(officeState.tasks)",
    "            ? officeState.tasks.map((task) => ({",
    "                id: safeString(task?.id),",
    "                title: safeString(task?.title),",
    "                rawText: safeString(task?.rawText),",
    "                source: safeString(task?.source),",
    "                roomId: safeString(task?.roomId),",
    "                roomLabel: safeString(task?.roomLabel),",
    "                status: safeString(task?.status).toLowerCase(),",
    "                assignedAgentId: safeString(task?.assignedAgentId),",
    "                createdAt: Number(task?.createdAt) || 0,",
    "                startedAt: Number(task?.startedAt) || 0,",
    "                completedAt: Number(task?.completedAt) || 0,",
    "            })).filter((task) => Boolean(task.id))",
    "            : [],",
    "        agents: Array.isArray(officeState.agents)",
    "            ? officeState.agents.map((agent) => {",
    "                const timers = {};",
    "                OFFICE_RUNTIME_TIMER_FIELDS.forEach((field) => {",
    "                    timers[field] = officeRuntimeTimerRemaining(timerNow, agent?.[field]);",
    "                });",
    "                return {",
    "                    id: safeString(agent?.id),",
    "                    name: safeString(agent?.name).slice(0, 24),",
    "                    color: safeString(agent?.color),",
    "                    costume: safeString(agent?.costume || 'none').toLowerCase(),",
    "                    tint: safeString(agent?.tint || officeAgentTintFromColor(agent?.color)).toLowerCase(),",
    "                    x: Number(agent?.x) || 0,",
    "                    y: Number(agent?.y) || 0,",
    "                    targetX: Number(agent?.targetX) || 0,",
    "                    targetY: Number(agent?.targetY) || 0,",
    "                    speed: Number(agent?.speed) || 0,",
    "                    facing: Number(agent?.facing) || 1,",
    "                    laneBias: Number(agent?.laneBias) || 0,",
    "                    state: safeString(agent?.state).toLowerCase(),",
    "                    intent: safeString(agent?.intent).toLowerCase(),",
    "                    taskId: safeString(agent?.taskId),",
    "                    workStreak: Number(agent?.workStreak) || 0,",
    "                    yieldResumeIntent: safeString(agent?.yieldResumeIntent),",
    "                    runawayPhase: safeString(agent?.runawayPhase),",
    "                    runawayExitX: Number(agent?.runawayExitX) || 0,",
    "                    runawayExitY: Number(agent?.runawayExitY) || 0,",
    "                    currentNodeId: safeString(agent?.currentNodeId),",
    "                    routeWaypoints: Array.isArray(agent?.routeWaypoints)",
    "                        ? agent.routeWaypoints.slice(0, 24).map((point) => ({",
    "                            x: Number(point?.x) || 0,",
    "                            y: Number(point?.y) || 0,",
    "                            nodeId: safeString(point?.nodeId),",
    "                        }))",
    "                        : [],",
    "                    routeDestinationNodeId: safeString(agent?.routeDestinationNodeId),",
    "                    reservedLaneEdgeKey: safeString(agent?.reservedLaneEdgeKey),",
    "                    timers,",
    "                };",
    "            }).filter((agent) => Boolean(agent.id))",
    "            : [],",
    "    };",
    "}",
    "",
    "function officeApplyRuntimeSnapshot(snapshotRaw, now = performance.now()) {",
    "    if (!officeState || !snapshotRaw || typeof snapshotRaw !== 'object') return false;",
    "    if (Number(snapshotRaw.version) !== OFFICE_RUNTIME_SCHEMA_VERSION) return false;",
    "    const timerNow = Number(now) || performance.now();",
    "    let changed = false;",
    "",
    "    const taskList = [];",
    "    const rawTasks = Array.isArray(snapshotRaw.tasks) ? snapshotRaw.tasks : [];",
    "    rawTasks.slice(0, OFFICE_MAX_TASKS).forEach((taskRaw) => {",
    "        const id = safeString(taskRaw?.id);",
    "        if (!id) return;",
    "        const room = officeRoomById(safeString(taskRaw?.roomId)) || officeRoomById('room-lobby');",
    "        const statusRaw = safeString(taskRaw?.status).toLowerCase();",
    "        const status = new Set(['queued', 'active', 'done']).has(statusRaw) ? statusRaw : 'queued';",
    "        taskList.push({",
    "            id,",
    "            title: officeTaskTitle(safeString(taskRaw?.title || taskRaw?.rawText || id)),",
    "            rawText: safeString(taskRaw?.rawText || taskRaw?.title || id),",
    "            source: safeString(taskRaw?.source) || 'runtime-restore',",
    "            roomId: room?.id || 'room-lobby',",
    "            roomLabel: room?.label || 'Main Lobby',",
    "            status,",
    "            assignedAgentId: safeString(taskRaw?.assignedAgentId),",
    "            createdAt: Number(taskRaw?.createdAt) || Date.now(),",
    "            startedAt: Number(taskRaw?.startedAt) || 0,",
    "            completedAt: Number(taskRaw?.completedAt) || 0,",
    "        });",
    "    });",
    "    if (taskList.length) {",
    "        officeState.tasks = taskList;",
    "        officeState.tasksDirty = true;",
    "        changed = true;",
    "    }",
    "",
    "    const knownTaskIds = new Set(officeState.tasks.map((task) => task.id));",
    "    const allowedStates = new Set(['idle', 'walking', 'working', 'break', 'yield', 'runaway']);",
    "    const agentById = new Map(officeState.agents.map((agent) => [agent.id, agent]));",
    "    const rawAgents = Array.isArray(snapshotRaw.agents) ? snapshotRaw.agents : [];",
    "    rawAgents.forEach((saved) => {",
    "        const id = safeString(saved?.id);",
    "        if (!id) return;",
    "        const agent = agentById.get(id);",
    "        if (!agent) return;",
    "        const x = officeClamp(Number(saved?.x) || agent.x, 1, 99);",
    "        const y = officeClamp(Number(saved?.y) || agent.y, 1, 99);",
    "        const safePosition = officeNearestWalkablePoint(x, y, agent.x, agent.y);",
    "        agent.x = safePosition.x;",
    "        agent.y = safePosition.y;",
    "        const targetX = officeClamp(Number(saved?.targetX) || agent.x, 1, 99);",
    "        const targetY = officeClamp(Number(saved?.targetY) || agent.y, 1, 99);",
    "        const safeTarget = officeNearestWalkablePoint(targetX, targetY, agent.x, agent.y);",
    "        agent.targetX = safeTarget.x;",
    "        agent.targetY = safeTarget.y;",
    "        agent.name = safeString(saved?.name).slice(0, 24) || agent.name;",
    "        const color = safeString(saved?.color);",
    "        if (/^#[0-9a-f]{6}$/i.test(color)) {",
    "            agent.color = color;",
    "        }",
    "        const costume = safeString(saved?.costume).toLowerCase();",
    "        if (new Set(OFFICE_AGENT_COSTUME_POOL).has(costume)) {",
    "            agent.costume = costume;",
    "        }",
    "        agent.tint = safeString(saved?.tint).toLowerCase() || officeAgentTintFromColor(agent.color);",
    "        agent.speed = officeClamp(Number(saved?.speed) || agent.speed, 1.3, 5.2);",
    "        agent.facing = Number(saved?.facing) >= 0 ? 1 : -1;",
    "        agent.laneBias = officeClamp(Number(saved?.laneBias) || 0, -1, 1);",
    "        const state = safeString(saved?.state).toLowerCase();",
    "        agent.state = allowedStates.has(state) ? state : 'idle';",
    "        agent.intent = safeString(saved?.intent).toLowerCase() || (agent.state === 'working' ? 'task' : 'wander');",
    "        const taskId = safeString(saved?.taskId);",
    "        agent.taskId = knownTaskIds.has(taskId) ? taskId : '';",
    "        agent.workStreak = Math.max(0, Number(saved?.workStreak) || 0);",
    "        agent.yieldResumeIntent = safeString(saved?.yieldResumeIntent) || '';",
    "        agent.runawayPhase = safeString(saved?.runawayPhase) || '';",
    "        agent.runawayExitX = officeClamp(Number(saved?.runawayExitX) || 0, OFFICE_RUNAWAY_EXIT_MARGIN, 100 - OFFICE_RUNAWAY_EXIT_MARGIN);",
    "        agent.runawayExitY = officeClamp(Number(saved?.runawayExitY) || 0, OFFICE_RUNAWAY_EXIT_MARGIN, 100 - OFFICE_RUNAWAY_EXIT_MARGIN);",
    "        agent.currentNodeId = officeState.navMap.has(safeString(saved?.currentNodeId))",
    "            ? safeString(saved?.currentNodeId)",
    "            : officeFindNearestNode(officeState.navMap, agent.x, agent.y);",
    "        agent.routeWaypoints = Array.isArray(saved?.routeWaypoints)",
    "            ? saved.routeWaypoints.slice(0, 24).map((point) => ({",
    "                x: officeClamp(Number(point?.x) || agent.x, 0, 100),",
    "                y: officeClamp(Number(point?.y) || agent.y, 0, 100),",
    "                nodeId: safeString(point?.nodeId),",
    "            }))",
    "            : [];",
    "        const destination = safeString(saved?.routeDestinationNodeId);",
    "        agent.routeDestinationNodeId = officeState.navMap.has(destination) ? destination : '';",
    "        agent.reservedLaneEdgeKey = safeString(saved?.reservedLaneEdgeKey);",
    "        agent.speech = null;",
    "        const timers = saved?.timers && typeof saved.timers === 'object' ? saved.timers : {};",
    "        OFFICE_RUNTIME_TIMER_FIELDS.forEach((field) => {",
    "            agent[field] = officeRuntimeTimerRestore(timerNow, timers[field]);",
    "        });",
    "        agent.lastMoveX = agent.x;",
    "        agent.lastMoveY = agent.y;",
    "        changed = true;",
    "    });",
    "",
    "    const selectedAgentId = safeString(snapshotRaw.selectedAgentId);",
    "    if (selectedAgentId && officeState.agents.some((agent) => agent.id === selectedAgentId)) {",
    "        officeState.selectedAgentId = selectedAgentId;",
    "        changed = true;",
    "    }",
    "    const followAgentId = safeString(snapshotRaw.followAgentId);",
    "    if (followAgentId && officeState.agents.some((agent) => agent.id === followAgentId)) {",
    "        officeState.followAgentId = followAgentId;",
    "        changed = true;",
    "    }",
    "    if (Array.isArray(snapshotRaw.chatLines) && snapshotRaw.chatLines.length) {",
    "        officeState.chatLines = snapshotRaw.chatLines",
    "            .map((line) => ({",
    "                message: safeString(line?.message),",
    "                tone: safeString(line?.tone) || 'system',",
    "                at: Number(line?.at) || Date.now(),",
    "            }))",
    "            .filter((line) => Boolean(line.message))",
    "            .slice(-OFFICE_MAX_CHAT_LINES);",
    "        changed = true;",
    "    }",
    "    officeState.taskCounter = Math.max(",
    "        Number(officeState.taskCounter) || 0,",
    "        Number(snapshotRaw.taskCounter) || 0,",
    "        officeState.tasks.length,",
    "    );",
    "    officeState.lastWallClockTickAt = Date.now();",
    "    return changed;",
    "}",
    "",
    "function officePersistRuntimeState(now = performance.now(), { force = false } = {}) {",
    "    if (!officeState) return;",
    "    const snapshotNow = Number(now) || performance.now();",
    "    const elapsed = snapshotNow - (officeState.lastRuntimePersistAt || 0);",
    "    if (!force && elapsed < OFFICE_RUNTIME_PERSIST_INTERVAL_MS) return;",
    "    const snapshot = officeCollectRuntimeSnapshot(snapshotNow);",
    "    if (!snapshot) return;",
    "    saveStoredOfficeRuntimeState(snapshot);",
    "    officeState.lastRuntimePersistAt = snapshotNow;",
    "}",
    "",
    "function officeSanitizeDynamicRoomSnapshot(roomRaw, index = 0) {",
    "    const room = roomRaw && typeof roomRaw === 'object' ? roomRaw : {};",
    "    const roomId = safeString(room.id) || `room-dynamic-${index + 1}`;",
    "    const x = officeClamp(Number(room.x) || 58, 1, 93);",
    "    const y = officeClamp(Number(room.y) || 58, 1, 95);",
    "    const w = officeClamp(Number(room.w) || 8, 4.8, 18);",
    "    const h = officeClamp(Number(room.h) || 8, 4.8, 18);",
    "    const doorX = officeClamp(Number(room.doorX) || (x + (w / 2)), x, x + w);",
    "    const doorY = officeClamp(Number(room.doorY) || (y + h), y, y + h + 2.2);",
    "    const hallId = safeString(room.hallId) || officeNearestHallId(doorX, doorY);",
    "    return {",
    "        id: roomId,",
    "        label: safeString(room.label) || `Task Pod ${index + 1}`,",
    "        meta: safeString(room.meta) || 'Auto-generated feature room',",
    "        x,",
    "        y,",
    "        w,",
    "        h,",
    "        kind: safeString(room.kind) || 'work',",
    "        theme: safeString(room.theme) || 'dynamic',",
    "        doorX,",
    "        doorY,",
    "        hallId,",
    "        dynamic: true,",
    "    };",
    "}",
    "",
    "function officeCollectLayoutSnapshot() {",
    "    if (!officeState) return { dynamicRooms: [], dynamicRoomBySlug: {} };",
    "    const dynamicRooms = officeState.rooms",
    "        .filter((room) => room?.dynamic)",
    "        .map((room) => ({",
    "            id: room.id,",
    "            label: room.label,",
    "            meta: room.meta,",
    "            x: Number(room.x) || 0,",
    "            y: Number(room.y) || 0,",
    "            w: Number(room.w) || 0,",
    "            h: Number(room.h) || 0,",
    "            kind: room.kind || 'work',",
    "            theme: room.theme || 'dynamic',",
    "            doorX: Number(room.doorX) || 0,",
    "            doorY: Number(room.doorY) || 0,",
    "            hallId: room.hallId || '',",
    "        }));",
    "    const dynamicRoomBySlug = {};",
    "    officeState.dynamicRoomBySlug.forEach((roomId, slug) => {",
    "        if (!slug || !roomId) return;",
    "        dynamicRoomBySlug[slug] = roomId;",
    "    });",
    "    return { dynamicRooms, dynamicRoomBySlug };",
    "}",
    "",
    "function officePersistLayoutState() {",
    "    if (!officeState) return;",
    "    saveStoredOfficeLayoutState(officeCollectLayoutSnapshot());",
    "}",
    "",
    "function officeApplyStoredAgentPrefs(agents, prefsRaw) {",
    "    if (!Array.isArray(agents) || !agents.length) return;",
    "    const prefs = prefsRaw && typeof prefsRaw === 'object' ? prefsRaw : null;",
    "    if (!prefs) return;",
    "    const usedNames = new Set();",
    "    agents.forEach((agent) => {",
    "        const saved = prefs[safeString(agent.id)];",
    "        if (!saved || typeof saved !== 'object') return;",
    "        const proposedName = safeString(saved.name).slice(0, 24);",
    "        const lowered = proposedName.toLowerCase();",
    "        if (proposedName && !usedNames.has(lowered)) {",
    "            agent.name = proposedName;",
    "            usedNames.add(lowered);",
    "        } else {",
    "            usedNames.add(safeString(agent.name).toLowerCase());",
    "        }",
    "        const color = safeString(saved.color);",
    "        if (/^#[0-9a-f]{6}$/i.test(color)) {",
    "            agent.color = color;",
    "        }",
    "        const costume = safeString(saved.costume).toLowerCase();",
    "        if (new Set(['none', 'cap', 'visor', 'headset', 'bowtie']).has(costume)) {",
    "            agent.costume = costume;",
    "        }",
    "        const tint = safeString(saved.tint).toLowerCase();",
    "        if (tint) {",
    "            agent.tint = tint;",
    "        } else {",
    "            agent.tint = officeAgentTintFromColor(agent.color);",
    "        }",
    "    });",
    "}",
    "",
    "function officeCollectAgentPrefsSnapshot() {",
    "    if (!officeState) return {};",
    "    const snapshot = {};",
    "    officeState.agents.forEach((agent) => {",
    "        if (!agent) return;",
    "        snapshot[agent.id] = {",
    "            name: safeString(agent.name).slice(0, 24),",
    "            color: /^#[0-9a-f]{6}$/i.test(safeString(agent.color)) ? safeString(agent.color) : '#9ad8ff',",
    "            costume: safeString(agent.costume || 'none'),",
    "            tint: safeString(agent.tint || 'blue'),",
    "        };",
    "    });",
    "    return snapshot;",
    "}",
    "",
    "function officePersistAgentPrefs() {",
    "    if (!officeState) return;",
    "    saveStoredOfficeAgentPrefs(officeCollectAgentPrefsSnapshot());",
    "}",
    "",
    "function setChatListExpanded(expanded, { persist = true } = {}) {",
    "    chatListExpanded = Boolean(expanded);",
    "    if (navChatBtn) navChatBtn.classList.toggle('chat-list-collapsed', !chatListExpanded);",
    "    if (sidebarChatPanel) {",
    "        sidebarChatPanel.classList.toggle('chat-list-collapsed', !chatListExpanded);",
    "        sidebarChatPanel.classList.toggle('hidden', !(sidebarNavMode === 'chat' || sidebarNavMode === 'search'));",
    "    }",
    "    if (persist) saveStoredChatListExpanded(chatListExpanded);",
    "}",
    "",
    "function initContentWorkspace() {",
    "    const state = contentEnsureState();",
    "    if (!state) return;",
    "    if (!state.controlsBound) {",
    "        state.controlsBound = true;",
    "        if (contentRefreshBtn) {",
    "            contentRefreshBtn.addEventListener('click', async () => {",
    "                const ok = await contentRefresh({ silent: true });",
    "                if (ok) {",
    "                    notifyUser('Content Hub refreshed from live mission data.', {",
    "                        tone: 'success',",
    "                        debugKind: 'success',",
    "                        durationMs: 1700,",
    "                    });",
    "                } else {",
    "                    notifyUser('Content Hub refresh failed.', {",
    "                        tone: 'warning',",
    "                        debugKind: 'warning',",
    "                        durationMs: 2600,",
    "                    });",
    "                }",
    "            });",
    "        }",
    "    }",
    "    if (!state.payload) {",
    "        state.payload = contentEmptyPayload();",
    "    }",
    "    contentRender();",
    "    if (sidebarNavMode === 'content') {",
    "        void contentRefresh({ silent: true });",
    "    }",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  SIDEBAR & NAVIGATION                                                   ║",
    "// ║  Nav mode switching, chat list, office/content workspace init           ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function setSidebarNavMode(mode = 'chat', { persist = true } = {}) {",
    "    sidebarNavMode = normalizeNavMode(mode);",
    "    const isSearch = sidebarNavMode === 'search';",
    "    const isChat = sidebarNavMode === 'chat' || isSearch;",
    "    const isOffice = sidebarNavMode === 'office';",
    "    const isMission = sidebarNavMode === 'mission';",
    "    const isContent = sidebarNavMode === 'content';",
    "    const isModule = MODULE_NAV_MODE_SET.has(sidebarNavMode);",
    "",
    "    if (navChatBtn) navChatBtn.classList.toggle('active', isChat);",
    "    if (navOfficeBtn) navOfficeBtn.classList.toggle('active', isOffice);",
    "    if (navMissionBtn) navMissionBtn.classList.toggle('active', isMission);",
    "    if (navContentBtn) navContentBtn.classList.toggle('active', isContent);",
    "    sidebarModeButtons.forEach((button) => {",
    "        const buttonMode = normalizeNavMode(button.dataset.navMode);",
    "        button.classList.toggle('active', buttonMode === sidebarNavMode);",
    "    });",
    "    if (searchOverlayBar) searchOverlayBar.classList.remove('hidden');",
    "    if (sidebarChatPanel) {",
    "        sidebarChatPanel.classList.toggle('hidden', !isChat);",
    "        sidebarChatPanel.classList.toggle('chat-list-collapsed', !chatListExpanded);",
    "    }",
    "    if (officeWorkspace) officeWorkspace.classList.toggle('hidden', !isOffice);",
    "    if (missionWorkspace) missionWorkspace.classList.toggle('hidden', !isMission);",
    "    if (contentWorkspace) contentWorkspace.classList.toggle('hidden', !isContent);",
    "    if (moduleWorkspace) moduleWorkspace.classList.toggle('hidden', !isModule);",
    "    if (appRoot) {",
    "        appRoot.classList.toggle('office-active', isOffice);",
    "        appRoot.classList.toggle('mission-active', isMission);",
    "        appRoot.classList.toggle('content-active', isContent);",
    "        appRoot.classList.toggle('module-active', isModule);",
    "    }",
    "",
    "    if (sidebar) {",
    "        sidebar.classList.toggle('mode-search', isSearch);",
    "        sidebar.classList.toggle('mode-chat', isChat);",
    "        sidebar.classList.toggle('mode-office', isOffice);",
    "        sidebar.classList.toggle('mode-mission', isMission);",
    "        sidebar.classList.toggle('mode-content', isContent);",
    "        sidebar.classList.toggle('mode-module', isModule);",
    "    }",
    "",
    "    if (isOffice && officeEnsureState()) {",
    "        officeState.active = true;",
    "        officeResetViewport();",
    "        void officeStartMissionStream();",
    "        if (officeChatInput) {",
    "            window.setTimeout(() => {",
    "                officeChatInput.focus();",
    "            }, 0);",
    "        }",
    "    } else if (officeState) {",
    "        officeState.active = false;",
    "        officeSetEditorOpen(false);",
    "        officeStopMissionStream();",
    "        officePersistRuntimeState(performance.now(), { force: true });",
    "    }",
    "",
    "    if (isMission) {",
    "        missionEnterMode();",
    "    } else {",
    "        missionLeaveMode();",
    "    }",
    "",
    "    if (isContent) {",
    "        contentEnterMode();",
    "    } else {",
    "        contentLeaveMode();",
    "    }",
    "",
    "    if (isModule) {",
    "        moduleEnterMode(sidebarNavMode);",
    "        if (sidebarNavMode === 'finance') void spendRefresh();",
    "        if (sidebarNavMode === 'operations' || sidebarNavMode === 'dashboard') void goalsRefresh();",
    "    } else {",
    "        moduleLeaveMode();",
    "    }",
    "",
    "    if (!isChat) {",
    "        chatGameClose({ clearMode: false });",
    "        if (safeString(composerModeSelection?.kind) === 'game') {",
    "            composerClearMode({ closeGame: false });",
    "        }",
    "    }",
    "",
    "    setSidebarSearchScope(isModule ? 'general' : sidebarNavMode);",
    "",
    "    if (persist && !isSearch) {",
    "        saveStoredNavMode(sidebarNavMode);",
    "    }",
    "    normalizeMainContentScroll();",
    "    updateTaskContinuityVisibility({ refresh: isChat });",
    "    updateDebugDockSnapshot();",
    "}",
    "",
    "function setSidebarSearchScope(scope = 'chat') {",
    "    const normalizedScope = safeString(scope).toLowerCase();",
    "    if (normalizedScope === 'office' || normalizedScope === 'mission' || normalizedScope === 'content' || normalizedScope === 'general') {",
    "        sidebarSearchScope = normalizedScope;",
    "    } else if (normalizedScope === 'search' || MODULE_NAV_MODE_SET.has(normalizedScope)) {",
    "        sidebarSearchScope = 'general';",
    "    } else {",
    "        sidebarSearchScope = 'chat';",
    "    }",
    "",
    "    let label = 'Search chats';",
    "    if (sidebarSearchScope === 'office') label = 'Search office';",
    "    if (sidebarSearchScope === 'mission') label = 'Search mission control';",
    "    if (sidebarSearchScope === 'content') label = 'Search content hub';",
    "    if (sidebarSearchScope === 'general') label = withAgentName('Search {{agent}}');",
    "",
    "    if (globalSearchInput) globalSearchInput.placeholder = label;",
    "    if (sidebarSearchModeLabel) sidebarSearchModeLabel.textContent = label;",
    "    if (sidebarChatHeaderLabel) sidebarChatHeaderLabel.textContent = 'Recent Chats';",
    "    renderSidebarChatList();",
    "    updateDebugDockSnapshot();",
    "}",
    "",
    "function renderSidebarChatList() {",
    "    if (!sidebarChatList) return;",
    "    const chatSearchEnabled = sidebarSearchScope === 'chat' || sidebarSearchScope === 'general';",
    "    const queryLower = chatSearchEnabled ? safeString(globalSearchInput?.value).toLowerCase() : '';",
    "    const activeId = safeString(activeChatId) || safeString(sessionId);",
    "    sidebarChatList.innerHTML = '';",
    "",
    "    const filteredSessions = sidebarSessions.filter((session) => {",
    "        if (!queryLower) return true;",
    "        const haystack = `${safeString(session?.title)} ${safeString(session?.preview)} ${safeString(session?.model)} ${safeString(session?.id)}`.toLowerCase();",
    "        return haystack.includes(queryLower);",
    "    });",
    "",
    "    filteredSessions.forEach((session) => {",
    "        const row = document.createElement('button');",
    "        row.type = 'button';",
    "        row.className = 'sidebar-chat-row';",
    "        if (safeString(session?.id) === activeId) {",
    "            row.classList.add('active');",
    "        }",
    "        row.innerHTML = `",
    "            <span class=\"sidebar-chat-row-title\">${escapeHtml(formatSidebarSessionTitle(session))}</span>",
    "            <span class=\"sidebar-chat-row-meta\">${escapeHtml(formatSidebarSessionMeta(session))}</span>",
    "        `;",
    "        row.addEventListener('click', () => {",
    "            const sid = safeString(session?.id);",
    "            if (!sid) return;",
    "            void loadSessionFromHistory(sid);",
    "        });",
    "        sidebarChatList.appendChild(row);",
    "    });",
    "",
    "    if (!sidebarChatList.children.length) {",
    "        const empty = document.createElement('div');",
    "        empty.className = 'sidebar-chat-empty';",
    "        if (queryLower) {",
    "            empty.textContent = 'No matches yet. Try another search term.';",
    "        } else if (sidebarSearchScope === 'general') {",
    "            empty.textContent = withAgentName('Search {{agent}} to find chats and relevant items.');",
    "        } else {",
    "            empty.textContent = 'No chats yet. Start one from New Chat.';",
    "        }",
    "        sidebarChatList.appendChild(empty);",
    "    }",
    "}",
    "",
    "function slugifySettingsLabel(label) {",
    "    return safeString(label)",
    "        .toLowerCase()",
    "        .replace(/[^a-z0-9]+/g, '-')",
    "        .replace(/^-+|-+$/g, '');",
    "}",
    "",
    "function isSettingsSectionVisible(section) {",
    "    return Boolean(section && section.getClientRects().length > 0);",
    "}",
    "",
    "function setActiveSettingsSectionNav(sectionId) {",
    "    settingsSectionEntries.forEach((entry) => {",
    "        const isActive = Boolean(sectionId) && entry.section.id === sectionId && !entry.link.classList.contains('hidden');",
    "        entry.link.classList.toggle('active', isActive);",
    "        entry.link.setAttribute('aria-current', isActive ? 'true' : 'false');",
    "    });",
    "}",
    "",
    "function getVisibleSettingsSectionEntries() {",
    "    return settingsSectionEntries.filter((entry) => !entry.link.classList.contains('hidden') && isSettingsSectionVisible(entry.section));",
    "}",
    "",
    "function updateSettingsNavEmptyState() {",
    "    if (!settingsNavEmpty) return;",
    "    const hasVisibleEntries = settingsSectionEntries.some((entry) => !entry.link.classList.contains('hidden'));",
    "    settingsNavEmpty.classList.toggle('hidden', hasVisibleEntries);",
    "}",
    "",
    "function updateSettingsSectionNavActive() {",
    "    if (!settingsSections) return;",
    "    const visibleEntries = getVisibleSettingsSectionEntries();",
    "    if (visibleEntries.length === 0) {",
    "        setActiveSettingsSectionNav('');",
    "        return;",
    "    }",
    "",
    "    const activeOffset = settingsSections.scrollTop + 56;",
    "    let activeEntry = visibleEntries[0];",
    "    visibleEntries.forEach((entry) => {",
    "        if (entry.section.offsetTop <= activeOffset) {",
    "            activeEntry = entry;",
    "        }",
    "    });",
    "    setActiveSettingsSectionNav(activeEntry.section.id);",
    "}",
    "",
    "function queueSettingsSectionNavActiveUpdate() {",
    "    if (settingsNavTicking) return;",
    "    settingsNavTicking = true;",
    "    requestAnimationFrame(() => {",
    "        settingsNavTicking = false;",
    "        updateSettingsSectionNavActive();",
    "    });",
    "}",
    "",
    "function updateSettingsSectionNavVisibility() {",
    "    const query = safeString(settingsSectionSearch?.value).toLowerCase();",
    "    const advancedModeEnabled = Boolean(settingsSuite?.classList.contains('advanced-mode'));",
    "",
    "    settingsSectionEntries.forEach((entry) => {",
    "        const advancedOnly = entry.section.classList.contains('settings-advanced-only');",
    "        const inMode = advancedModeEnabled || !advancedOnly;",
    "        const matches = !query || entry.labelLower.includes(query);",
    "        entry.link.classList.toggle('hidden', !(inMode && matches));",
    "    });",
    "",
    "    updateSettingsNavEmptyState();",
    "    queueSettingsSectionNavActiveUpdate();",
    "}",
    "",
    "function scrollToSettingsSection(sectionId) {",
    "    if (!settingsSections || !sectionId) return;",
    "    const section = document.getElementById(sectionId);",
    "    if (!isSettingsSectionVisible(section)) return;",
    "    const top = Math.max(0, section.offsetTop - 8);",
    "    settingsSections.scrollTo({ top, behavior: 'smooth' });",
    "    setActiveSettingsSectionNav(sectionId);",
    "}",
    "",
    "function buildSettingsSectionNav() {",
    "    if (!settingsSectionNav || !settingsSections) return;",
    "    settingsSectionNav.innerHTML = '';",
    "    settingsSectionEntries = [];",
    "",
    "    const seenIds = new Set();",
    "    const sections = Array.from(settingsSections.querySelectorAll('.settings-section'));",
    "    sections.forEach((section, index) => {",
    "        const heading = section.querySelector('.settings-section-head h3');",
    "        const label = safeString(heading?.textContent) || `Section ${index + 1}`;",
    "        const baseId = safeString(section.id) || `settings-${slugifySettingsLabel(label) || `section-${index + 1}`}`;",
    "        let sectionId = baseId;",
    "        let suffix = 2;",
    "        while (seenIds.has(sectionId)) {",
    "            sectionId = `${baseId}-${suffix}`;",
    "            suffix += 1;",
    "        }",
    "        seenIds.add(sectionId);",
    "        section.id = sectionId;",
    "",
    "        const link = document.createElement('button');",
    "        link.type = 'button';",
    "        link.className = 'settings-nav-link';",
    "        link.textContent = label;",
    "        link.dataset.sectionId = sectionId;",
    "        link.setAttribute('aria-current', 'false');",
    "        link.addEventListener('click', () => scrollToSettingsSection(sectionId));",
    "        settingsSectionNav.appendChild(link);",
    "",
    "        settingsSectionEntries.push({",
    "            section,",
    "            link,",
    "            labelLower: label.toLowerCase(),",
    "        });",
    "    });",
    "",
    "    updateSettingsSectionNavVisibility();",
    "}",
    "",
    "function initSettingsSectionNavigation() {",
    "    if (settingsNavBound || !settingsSectionNav || !settingsSections) return;",
    "    settingsNavBound = true;",
    "    buildSettingsSectionNav();",
    "",
    "    if (settingsSectionSearch) {",
    "        settingsSectionSearch.addEventListener('input', updateSettingsSectionNavVisibility);",
    "    }",
    "",
    "    settingsSections.addEventListener('scroll', queueSettingsSectionNavActiveUpdate, { passive: true });",
    "    window.addEventListener('resize', queueSettingsSectionNavActiveUpdate);",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  INITIAL STATE & BOOT                                                   ║",
    "// ║  loadInitialState(), session creation, profile loading, preference sync ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "async function loadInitialState() {",
    "    let loadedFromHistory = false;",
    "    try {",
    "        await refreshIdentityState();",
    "        await fetchModels();",
    "        await fetchChatHistory();",
    "",
    "        const storedActiveChatId = loadStoredActiveChatId();",
    "        const hasStoredSession = Boolean(storedActiveChatId)",
    "            && sidebarSessions.some((row) => safeString(row?.id) === safeString(storedActiveChatId));",
    "        if (hasStoredSession) {",
    "            await loadSessionFromHistory(storedActiveChatId);",
    "            loadedFromHistory = true;",
    "        } else if (storedActiveChatId) {",
    "            saveStoredActiveChatId('');",
    "        }",
    "",
    "        if (!loadedFromHistory && sidebarSessions.length > 0) {",
    "            const latestSessionId = safeString(sidebarSessions[0]?.id);",
    "            if (latestSessionId) {",
    "                await loadSessionFromHistory(latestSessionId);",
    "                loadedFromHistory = true;",
    "            }",
    "        }",
    "",
    "        if (!loadedFromHistory) {",
    "            await createNewSessionAndRefresh();",
    "        }",
    "    } catch (e) {",
    "        console.error(\"Failed to boot session:\", e);",
    "        await createNewSessionAndRefresh();",
    "    } finally {",
    "        _positionRobotDock();",
    "        if (!document.querySelector('.chat-robot-landed')) {",
    "            _landRobotAtComposerDock();",
    "        }",
    "        await maybeAutoOpenEasySetup();",
    "    }",
    "}",
    "",
    "async function fetchChatHistory() {",
    "    try {",
    "        const res = await fetchJsonSafe('/api/chats');",
    "        if (res.ok) {",
    "            const data = res.data || {};",
    "            const chatRows = Array.isArray(data?.chats) ? data.chats : [];",
    "            if (chatRows.length > 0) {",
    "                sidebarSessions = chatRows",
    "                    .map((row) => mapPersistedChatToSidebarSession(row))",
    "                    .filter(Boolean);",
    "            } else {",
    "                const legacySessions = Array.isArray(data?.sessions) ? data.sessions : [];",
    "                sidebarSessions = legacySessions",
    "                    .map((row) => mapLegacySidebarSession(row))",
    "                    .filter(Boolean);",
    "            }",
    "            sidebarSessions.sort((a, b) => Number(b?.updatedAt || 0) - Number(a?.updatedAt || 0));",
    "            rebuildChatHistorySelector();",
    "            renderSidebarChatList();",
    "            updateDebugDockSnapshot();",
    "        }",
    "    } catch (e) {",
    "        console.error(\"Failed to fetch chat history:\", e);",
    "    }",
    "}",
    "",
    "async function createNewSessionAndRefresh() {",
    "    try {",
    "        const res = await fetchJsonSafe('/api/session/new', { method: 'POST' });",
    "        const data = res.data || {};",
    "        if (res.ok && data.session_id) {",
    "            sessionId = data.session_id;",
    "            activeChatId = data.session_id;",
    "            saveStoredActiveChatId(activeChatId);",
    "            pushDebugEvent('chat', `Created session ${sessionId}`);",
    "            // Clear current UI chat",
    "            chatHistory = [];",
    "            chatMessagesInner.innerHTML = '';",
    "            welcomeScreen.classList.remove('hidden');",
    "            chatScrollArea.classList.add('hidden');",
    "            maybeRenderSessionIntro();",
    "            showStarterSuggestionRail({ force: true });",
    "            await fetchChatHistory();",
    "            await refreshTaskContinuity({ sessionOverride: sessionId, force: true });",
    "        }",
    "    } catch (e) { console.error(\"Error creating new session:\", e); }",
    "}",
    "",
    "async function saveAgentIdentityName(nameRaw, { source = 'rename' } = {}) {",
    "    const nextName = sanitizeAgentNameInput(nameRaw);",
    "    if (!nextName) {",
    "        notifyUser('Agent name cannot be empty.', {",
    "            tone: 'warning',",
    "            durationMs: 2400,",
    "            debugKind: 'settings',",
    "        });",
    "        return false;",
    "    }",
    "",
    "    const currentName = getAgentName();",
    "    if (nextName === currentName) return true;",
].join("\n");
