/* app.js lines 25001-26000 */
export default [
    "        wrap: true,",
    "    });",
    "    editor.session.setUseWorker(false);",
    "    editor.setOption('tabSize', 4);",
    "    editor.setOption('useSoftTabs', true);",
    "    editor.setValue(wb.code, -1);",
    "    wb.aceEditor = editor;",
    "",
    "    const getCode = () => safeString(editor.getValue());",
    "    const setCode = (text) => editor.setValue(safeString(text), -1);",
    "    const log = (message, tone = 'ok') => moduleWorkbenchPushLog(wb.logs, message, tone, 120, 'dev-log');",
    "    const renderLogs = () => {",
    "        logsEl.innerHTML = wb.logs.length",
    "            ? wb.logs.slice(0, 16).map((entry) => `<article class=\"module-wb-log-item ${moduleToneClass(entry.tone) || 'ok'}\"><span>${escapeHtml(safeString(entry.time))}</span><p>${escapeHtml(safeString(entry.message))}</p></article>`).join('')",
    "            : '<div class=\"module-wb-ghost\">No execution logs yet.</div>';",
    "    };",
    "    const renderIssues = () => {",
    "        issuesEl.innerHTML = wb.issues.length",
    "            ? wb.issues.map((issue) => `<article class=\"module-wb-issue ${moduleToneClass(issue.tone) || 'ok'}\">${escapeHtml(safeString(issue.text))}</article>`).join('')",
    "            : '<div class=\"module-wb-ghost\">No checks run yet.</div>';",
    "        const errors = wb.issues.filter((issue) => moduleToneClass(issue.tone) === 'error').length;",
    "        status.textContent = `${errors ? `${errors} error` : 'No critical errors'} | ${getCode().length} chars`;",
    "    };",
    "    const applyAnnotations = () => {",
    "        const annotations = wb.issues",
    "            .filter((issue) => moduleToneClass(issue.tone) !== 'ok')",
    "            .map((issue) => ({",
    "                row: Math.max(0, (Number(issue.line) || 1) - 1),",
    "                column: 0,",
    "                text: safeString(issue.text),",
    "                type: moduleToneClass(issue.tone) === 'error' ? 'error' : 'warning',",
    "            }));",
    "        editor.session.setAnnotations(annotations);",
    "    };",
    "    const analyze = () => {",
    "        wb.code = getCode();",
    "        wb.issues = moduleDevStudioScanIssues(wb.code);",
    "        applyAnnotations();",
    "        renderIssues();",
    "    };",
    "",
    "    analyze();",
    "    renderLogs();",
    "",
    "    editor.session.on('change', () => {",
    "        wb.code = getCode();",
    "        renderIssues();",
    "    });",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const target = event.target instanceof Element ? event.target.closest('[data-dev-action]') : null;",
    "        if (!target) return;",
    "        const action = safeString(target.dataset.devAction).toLowerCase();",
    "        wb.code = getCode();",
    "        if (action === 'analyze') {",
    "            analyze();",
    "            log('Static analysis completed.', wb.issues.some((issue) => moduleToneClass(issue.tone) === 'error') ? 'warn' : 'ok');",
    "        }",
    "        if (action === 'tests') {",
    "            const hasTests = /\\b(test|describe|it)\\s*\\(/.test(wb.code);",
    "            if (!hasTests) {",
    "                setCode(`${wb.code.trimEnd()}\\n\\n// test('smoke', () => expect(true).toBe(true));\\n`);",
    "                wb.code = getCode();",
    "            }",
    "            analyze();",
    "            log(hasTests ? 'Tests passed in simulation.' : 'No tests found. Added smoke test stub.', hasTests ? 'ok' : 'warn');",
    "        }",
    "        if (action === 'build') {",
    "            analyze();",
    "            const failed = wb.issues.some((issue) => moduleToneClass(issue.tone) === 'error');",
    "            log(failed ? 'Build failed.' : 'Build succeeded.', failed ? 'error' : 'ok');",
    "        }",
    "        if (action === 'format') {",
    "            try {",
    "                editor.execCommand('beautify');",
    "                log('Format command executed.', 'ok');",
    "            } catch (_error) {",
    "                log('Format command unavailable in this runtime.', 'warn');",
    "            }",
    "        }",
    "        if (action === 'snippet') {",
    "            const snippet = `\\nexport async function rollout(ctx) {\\n    const records = await ctx.fetch();\\n    return { ok: true, count: Array.isArray(records) ? records.length : 0 };\\n}\\n`;",
    "            setCode(`${getCode().trimEnd()}\\n${snippet}`);",
    "            wb.code = getCode();",
    "            analyze();",
    "            log('Inserted rollout snippet.', 'ok');",
    "        }",
    "        if (action === 'dockerfile') {",
    "            moduleWorkbenchCopyText(moduleWorkbenchDevDockerfileSnippet(), 'Dockerfile Snippet');",
    "            log('Copied Dockerfile starter.', 'ok');",
    "        }",
    "        if (action === 'export') {",
    "            moduleWorkbenchCopyJson({ code: wb.code, issues: wb.issues, logs: wb.logs.slice(0, 24) }, 'Dev Studio Snapshot');",
    "        }",
    "        renderIssues();",
    "        renderLogs();",
    "    });",
    "",
    "    return true;",
    "}",
    "",
    "function moduleRenderWorkbenchDevStudio(container, wb) {",
    "    if (moduleRenderWorkbenchDevStudioOss(container, wb)) return;",
    "    if (!container || !wb) return;",
    "    wb.code = safeString(wb.code);",
    "    if (!Array.isArray(wb.issues)) wb.issues = [];",
    "    if (!Array.isArray(wb.logs)) wb.logs = [];",
    "",
    "    moduleWorkbenchHeader(container, 'Dev Studio', 'Dispatch engineering tasks to Thomas, inspect issues/checks, and review implementation outputs.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-dev';",
    "    shell.innerHTML = `",
    "        <section class=\"module-wb-stage-card\"><div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Editor</span><span class=\"module-wb-stage-meta\" data-dev-status></span></div><div class=\"module-wb-inspector-actions\"><button type=\"button\" class=\"module-item-btn\" data-dev-action=\"analyze\">Analyze</button><button type=\"button\" class=\"module-item-btn\" data-dev-action=\"tests\">Run Tests</button><button type=\"button\" class=\"module-item-btn\" data-dev-action=\"build\">Build</button><button type=\"button\" class=\"module-item-btn\" data-dev-action=\"snippet\">Snippet</button><button type=\"button\" class=\"module-item-btn\" data-dev-action=\"dockerfile\">Dockerfile</button><button type=\"button\" class=\"module-item-btn\" data-dev-action=\"export\">Export</button></div><textarea class=\"module-wb-code-editor\" data-dev-code placeholder=\"Write code here...\">${escapeHtml(wb.code)}</textarea></section>",
    "        <aside class=\"module-wb-inspector-card\"><h4>Issues</h4><div class=\"module-wb-issues\" data-dev-issues></div><h4>Logs</h4><div class=\"module-wb-log-list\" data-dev-logs></div></aside>",
    "        ${moduleWorkbenchRenderOssStack('dev_studio')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const status = shell.querySelector('[data-dev-status]');",
    "    const codeEl = shell.querySelector('[data-dev-code]');",
    "    const issuesEl = shell.querySelector('[data-dev-issues]');",
    "    const logsEl = shell.querySelector('[data-dev-logs]');",
    "    const analyze = () => {",
    "        const code = safeString(wb.code);",
    "        const issues = [];",
    "        if (!code.trim()) issues.push({ tone: 'warn', text: 'Editor is empty.' });",
    "        const opens = (code.match(/{/g) || []).length;",
    "        const closes = (code.match(/}/g) || []).length;",
    "        if (opens !== closes) issues.push({ tone: 'error', text: `Brace mismatch: ${opens} vs ${closes}.` });",
    "        if (/TODO/.test(code)) issues.push({ tone: 'warn', text: 'TODO markers still present.' });",
    "        if (/console\\.log\\(/.test(code)) issues.push({ tone: 'warn', text: 'Debug logs detected.' });",
    "        if (!/\\b(test|describe|it)\\s*\\(/.test(code)) issues.push({ tone: 'warn', text: 'No tests found.' });",
    "        if (!issues.length) issues.push({ tone: 'ok', text: 'No obvious static issues.' });",
    "        wb.issues = issues;",
    "    };",
    "    const log = (message, tone = 'ok') => moduleWorkbenchPushLog(wb.logs, message, tone, 120, 'dev-log');",
    "    const render = () => {",
    "        issuesEl.innerHTML = wb.issues.length ? wb.issues.map((issue) => `<article class=\"module-wb-issue ${moduleToneClass(issue.tone) || 'ok'}\">${escapeHtml(safeString(issue.text))}</article>`).join('') : '<div class=\"module-wb-ghost\">No checks run yet.</div>';",
    "        logsEl.innerHTML = wb.logs.length ? wb.logs.slice(0, 16).map((entry) => `<article class=\"module-wb-log-item ${moduleToneClass(entry.tone) || 'ok'}\"><span>${escapeHtml(safeString(entry.time))}</span><p>${escapeHtml(safeString(entry.message))}</p></article>`).join('') : '<div class=\"module-wb-ghost\">No execution logs yet.</div>';",
    "        const errors = wb.issues.filter((issue) => moduleToneClass(issue.tone) === 'error').length;",
    "        status.textContent = `${errors ? `${errors} error` : 'No critical errors'} | ${safeString(wb.code).length} chars`;",
    "    };",
    "    render();",
    "    if (codeEl) codeEl.addEventListener('input', () => { wb.code = safeString(codeEl.value); render(); });",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const target = event.target instanceof Element ? event.target.closest('[data-dev-action]') : null;",
    "        if (!target) return;",
    "        const action = safeString(target.dataset.devAction).toLowerCase();",
    "        wb.code = safeString(codeEl?.value);",
    "        if (action === 'analyze') { analyze(); log('Static analysis completed.', wb.issues.some((issue) => moduleToneClass(issue.tone) === 'error') ? 'warn' : 'ok'); }",
    "        if (action === 'tests') { const hasTests = /\\b(test|describe|it)\\s*\\(/.test(wb.code); log(hasTests ? 'Tests passed in simulation.' : 'No tests found. Added smoke test stub.', hasTests ? 'ok' : 'warn'); if (!hasTests) { wb.code += `${wb.code.endsWith('\\n') ? '' : '\\n'}\\n// test('smoke', () => expect(true).toBe(true));`; if (codeEl) codeEl.value = wb.code; } analyze(); }",
    "        if (action === 'build') { analyze(); log(wb.issues.some((issue) => moduleToneClass(issue.tone) === 'error') ? 'Build failed.' : 'Build succeeded.', wb.issues.some((issue) => moduleToneClass(issue.tone) === 'error') ? 'error' : 'ok'); }",
    "        if (action === 'snippet') { wb.code += `${wb.code.endsWith('\\n') ? '' : '\\n'}\\nexport async function handler(ctx){\\n    const data = await ctx.fetch();\\n    return { ok: true, size: Array.isArray(data) ? data.length : 0 };\\n}\\n`; if (codeEl) codeEl.value = wb.code; analyze(); log('Inserted reusable handler snippet.', 'ok'); }",
    "        if (action === 'dockerfile') { moduleWorkbenchCopyText(moduleWorkbenchDevDockerfileSnippet(), 'Dockerfile Snippet'); log('Copied Dockerfile starter.', 'ok'); }",
    "        if (action === 'export') moduleWorkbenchCopyJson({ code: wb.code, issues: wb.issues, logs: wb.logs.slice(0, 20) }, 'Dev Studio Snapshot');",
    "        render();",
    "    });",
    "}",
    "",
    "function moduleGameStudioEnsureGrid(wb) {",
    "    wb.gridWidth = moduleWorkbenchClamp(Number(wb.gridWidth) || 20, 8, 64);",
    "    wb.gridHeight = moduleWorkbenchClamp(Number(wb.gridHeight) || 12, 6, 40);",
    "    wb.brush = moduleWorkbenchClamp(Number(wb.brush) || 1, 0, 4);",
    "    if (!Array.isArray(wb.tiles) || wb.tiles.length !== wb.gridHeight || !Array.isArray(wb.tiles[0]) || wb.tiles[0].length !== wb.gridWidth) {",
    "        wb.tiles = Array.from({ length: wb.gridHeight }, () => Array.from({ length: wb.gridWidth }, () => 0));",
    "    }",
    "    if (!Array.isArray(wb.logs)) wb.logs = [];",
    "}",
    "",
    "function moduleGameStudioResizeGrid(wb, widthRaw, heightRaw) {",
    "    const nextWidth = moduleWorkbenchClamp(Number(widthRaw) || wb.gridWidth || 20, 8, 64);",
    "    const nextHeight = moduleWorkbenchClamp(Number(heightRaw) || wb.gridHeight || 12, 6, 40);",
    "    const prev = Array.isArray(wb.tiles) ? wb.tiles : [];",
    "    const next = Array.from({ length: nextHeight }, (_row, y) => (",
    "        Array.from({ length: nextWidth }, (_col, x) => moduleWorkbenchClamp(Number(prev?.[y]?.[x]) || 0, 0, 4))",
    "    ));",
    "    wb.gridWidth = nextWidth;",
    "    wb.gridHeight = nextHeight;",
    "    wb.tiles = next;",
    "}",
    "",
    "function moduleGameStudioCounts(wb) {",
    "    const counts = { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0 };",
    "    wb.tiles.forEach((row) => row.forEach((tile) => {",
    "        const key = String(moduleWorkbenchClamp(Number(tile) || 0, 0, 4));",
    "        counts[key] += 1;",
    "    }));",
    "    return counts;",
    "}",
    "",
    "function moduleGameStudioPlayable(wb) {",
    "    let start = null;",
    "    const goals = new Set();",
    "    for (let y = 0; y < wb.gridHeight; y += 1) {",
    "        for (let x = 0; x < wb.gridWidth; x += 1) {",
    "            const tile = Number(wb.tiles[y][x]) || 0;",
    "            if (tile === 3) start = { x, y };",
    "            if (tile === 4) goals.add(`${x},${y}`);",
    "        }",
    "    }",
    "    if (!start || !goals.size) return false;",
    "    const queue = [start];",
    "    const seen = new Set([`${start.x},${start.y}`]);",
    "    while (queue.length) {",
    "        const current = queue.shift();",
    "        if (!current) continue;",
    "        if (goals.has(`${current.x},${current.y}`)) return true;",
    "        [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([dx, dy]) => {",
    "            const nx = current.x + dx;",
    "            const ny = current.y + dy;",
    "            if (nx < 0 || ny < 0 || nx >= wb.gridWidth || ny >= wb.gridHeight) return;",
    "            const tile = Number(wb.tiles[ny][nx]) || 0;",
    "            if (tile === 0 || tile === 2) return;",
    "            const key = `${nx},${ny}`;",
    "            if (seen.has(key)) return;",
    "            seen.add(key);",
    "            queue.push({ x: nx, y: ny });",
    "        });",
    "    }",
    "    return false;",
    "}",
    "",
    "function moduleGameStudioFindFirstTile(wb, valueRaw) {",
    "    const value = Number(valueRaw) || 0;",
    "    for (let y = 0; y < wb.gridHeight; y += 1) {",
    "        for (let x = 0; x < wb.gridWidth; x += 1) {",
    "            if ((Number(wb.tiles[y][x]) || 0) === value) return { x, y };",
    "        }",
    "    }",
    "    return null;",
    "}",
    "",
    "function moduleGameStudioPlayTarget(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    if (mode === 'auto' || mode === 'phaser' || mode === 'unreal') return mode;",
    "    return 'auto';",
    "}",
    "",
    "function moduleGameStudioViewMode(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    if (mode === 'edit' || mode === 'playtest' || mode === 'unreal' || mode === 'split') return mode;",
    "    return 'split';",
    "}",
    "",
    "function moduleGameStudioActorTypeFromTile(tileRaw) {",
    "    const tile = Number(tileRaw) || 0;",
    "    if (tile === 1) return 'platform';",
    "    if (tile === 2) return 'hazard';",
    "    if (tile === 3) return 'spawn';",
    "    if (tile === 4) return 'goal';",
    "    return '';",
    "}",
    "",
    "function moduleGameStudioTileFromActorType(typeRaw) {",
    "    const type = safeString(typeRaw).toLowerCase();",
    "    if (type === 'platform') return 1;",
    "    if (type === 'hazard') return 2;",
    "    if (type === 'spawn') return 3;",
    "    if (type === 'goal') return 4;",
    "    return 0;",
    "}",
    "",
    "function moduleGameStudioActorTileBacked(typeRaw) {",
    "    return moduleGameStudioTileFromActorType(typeRaw) > 0;",
    "}",
    "",
    "function moduleGameStudioActorName(typeRaw, indexRaw = 1) {",
    "    const type = safeString(typeRaw).toLowerCase();",
    "    const index = Math.max(1, Number(indexRaw) || 1);",
    "    if (type === 'spawn') return 'Player Spawn';",
    "    if (type === 'goal') return 'Goal Marker';",
    "    if (type === 'hazard') return `Hazard ${index}`;",
    "    if (type === 'platform') return `Platform ${index}`;",
    "    if (type === 'npc') return `NPC ${index}`;",
    "    if (type === 'pickup') return `Pickup ${index}`;",
    "    if (type === 'light') return `Light ${index}`;",
    "    if (type === 'camera') return `Camera ${index}`;",
    "    if (type === 'trigger') return `Trigger ${index}`;",
    "    return `Actor ${index}`;",
    "}",
    "",
    "function moduleGameStudioActorId(wb) {",
    "    wb.nextActorId = Math.max(1, Number(wb.nextActorId) || 1);",
    "    const id = `actor-${wb.nextActorId}`;",
    "    wb.nextActorId += 1;",
    "    return id;",
    "}",
    "",
    "function moduleGameStudioActorById(wb, actorIdRaw) {",
    "    const actorId = safeString(actorIdRaw);",
    "    if (!Array.isArray(wb?.sceneActors) || !actorId) return null;",
    "    return wb.sceneActors.find((actor) => safeString(actor?.id) === actorId) || null;",
    "}",
    "",
    "function moduleGameStudioActorKey(actorTypeRaw, xRaw, yRaw) {",
    "    const actorType = safeString(actorTypeRaw).toLowerCase();",
    "    const x = Number(xRaw);",
    "    const y = Number(yRaw);",
    "    if (!actorType || !Number.isFinite(x) || !Number.isFinite(y)) return '';",
    "    return `${actorType}:${Math.round(x)}:${Math.round(y)}`;",
    "}",
    "",
    "function moduleGameStudioNormalizeActor(actorRaw, fallbackId) {",
    "    const actor = actorRaw && typeof actorRaw === 'object' ? actorRaw : {};",
    "    const className = safeString(actor.className || actor.type || 'actor').toLowerCase() || 'actor';",
    "    const id = safeString(actor.id) || safeString(fallbackId) || `actor-${Date.now()}`;",
    "    return {",
    "        id,",
    "        name: safeString(actor.name) || moduleGameStudioActorName(className, 1),",
    "        className,",
    "        assetId: safeString(actor.assetId),",
    "        x: Number(actor.x) || 0,",
    "        y: Number(actor.y) || 0,",
    "        z: Number(actor.z) || 0,",
    "        rx: Number(actor.rx) || 0,",
    "        ry: Number(actor.ry) || 0,",
    "        rz: Number(actor.rz) || 0,",
    "        sx: Number(actor.sx) || 1,",
    "        sy: Number(actor.sy) || 1,",
    "        sz: Number(actor.sz) || 1,",
    "        tileBacked: moduleGameStudioActorTileBacked(className),",
    "    };",
    "}",
    "",
    "function moduleGameStudioSyncSceneActorsFromTiles(wb) {",
    "    if (!wb || !Array.isArray(wb.tiles)) return;",
    "    if (!Array.isArray(wb.sceneActors)) wb.sceneActors = [];",
    "    wb.nextActorId = Math.max(1, Number(wb.nextActorId) || 1);",
    "",
    "    const previousSelected = safeString(wb.selectedActorId);",
    "    const existingTileActors = new Map();",
    "    const customActors = [];",
    "",
    "    wb.sceneActors.forEach((actorRaw) => {",
    "        const actor = moduleGameStudioNormalizeActor(actorRaw);",
    "        if (!moduleGameStudioActorTileBacked(actor.className)) {",
    "            customActors.push({",
    "                ...actor,",
    "                tileBacked: false,",
    "            });",
    "            return;",
    "        }",
    "        const key = moduleGameStudioActorKey(actor.className, actor.x, actor.y);",
    "        if (!key || existingTileActors.has(key)) return;",
    "        existingTileActors.set(key, actor);",
    "    });",
    "",
    "    const counters = Object.create(null);",
    "    const tileActors = [];",
    "    for (let y = 0; y < wb.gridHeight; y += 1) {",
    "        for (let x = 0; x < wb.gridWidth; x += 1) {",
    "            const className = moduleGameStudioActorTypeFromTile(wb.tiles?.[y]?.[x]);",
    "            if (!className) continue;",
    "            const key = moduleGameStudioActorKey(className, x, y);",
    "            counters[className] = (Number(counters[className]) || 0) + 1;",
    "            const existing = existingTileActors.get(key);",
    "            const normalized = moduleGameStudioNormalizeActor(existing || {",
    "                id: moduleGameStudioActorId(wb),",
    "                name: moduleGameStudioActorName(className, counters[className]),",
    "                className,",
    "                x,",
    "                y,",
    "                z: 0,",
    "                rx: 0,",
    "                ry: 0,",
    "                rz: 0,",
    "                sx: 1,",
    "                sy: 1,",
    "                sz: 1,",
    "            });",
    "            normalized.className = className;",
    "            normalized.x = x;",
    "            normalized.y = y;",
    "            normalized.z = 0;",
    "            normalized.tileBacked = true;",
    "            tileActors.push(normalized);",
    "        }",
    "    }",
    "",
    "    wb.sceneActors = [...tileActors, ...customActors];",
    "    const selectedStillExists = wb.sceneActors.some((actor) => safeString(actor.id) === previousSelected);",
    "    wb.selectedActorId = selectedStillExists ? previousSelected : safeString(wb.sceneActors[0]?.id);",
    "}",
    "",
    "function moduleGameStudioRebuildTilesFromActors(wb) {",
    "    if (!wb) return;",
    "    const nextTiles = Array.from({ length: wb.gridHeight }, () => Array.from({ length: wb.gridWidth }, () => 0));",
    "    const uniqueTileOwner = new Map();",
    "    const actors = Array.isArray(wb.sceneActors) ? wb.sceneActors : [];",
    "",
    "    actors.forEach((actorRaw) => {",
    "        const actor = moduleGameStudioNormalizeActor(actorRaw);",
    "        const tileType = moduleGameStudioTileFromActorType(actor.className);",
    "        if (!tileType) return;",
    "        const x = moduleWorkbenchClamp(Math.round(Number(actor.x) || 0), 0, wb.gridWidth - 1);",
    "        const y = moduleWorkbenchClamp(Math.round(Number(actor.y) || 0), 0, wb.gridHeight - 1);",
    "        if (tileType === 3 || tileType === 4) {",
    "            uniqueTileOwner.set(tileType, { x, y });",
    "            return;",
    "        }",
    "        nextTiles[y][x] = tileType;",
    "    });",
    "",
    "    if (uniqueTileOwner.has(3)) {",
    "        const position = uniqueTileOwner.get(3);",
    "        if (position) nextTiles[position.y][position.x] = 3;",
    "    }",
    "    if (uniqueTileOwner.has(4)) {",
    "        const position = uniqueTileOwner.get(4);",
    "        if (position) nextTiles[position.y][position.x] = 4;",
    "    }",
    "",
    "    wb.tiles = nextTiles;",
    "}",
    "",
    "const MODULE_GAME_ASSET_TYPES = [",
    "    { id: 'all', label: 'All' },",
    "    { id: 'mesh', label: 'Mesh' },",
    "    { id: 'material', label: 'Material' },",
    "    { id: 'blueprint', label: 'Blueprint' },",
    "    { id: 'audio', label: 'Audio' },",
    "    { id: 'vfx', label: 'VFX' },",
    "    { id: 'ui', label: 'UI' },",
    "];",
    "",
    "function moduleGameStudioDefaultAssets() {",
    "    return [",
    "        { id: 'asset-floor-grid', name: 'SM_FloorGrid', type: 'mesh', source: '/Game/Environment/Meshes', tags: ['level', 'base'] },",
    "        { id: 'asset-platform-a', name: 'SM_PlatformA', type: 'mesh', source: '/Game/Environment/Meshes', tags: ['platform'] },",
    "        { id: 'asset-hazard-01', name: 'BP_HazardLaser', type: 'blueprint', source: '/Game/Gameplay/Blueprints', tags: ['hazard'] },",
    "        { id: 'asset-goal-beacon', name: 'BP_GoalBeacon', type: 'blueprint', source: '/Game/Gameplay/Blueprints', tags: ['goal'] },",
    "        { id: 'asset-robot-npc', name: 'BP_RobotGuard', type: 'blueprint', source: '/Game/Characters/Blueprints', tags: ['npc'] },",
    "        { id: 'asset-hud-main', name: 'WBP_MainHUD', type: 'ui', source: '/Game/UI/Widgets', tags: ['ui'] },",
    "    ];",
    "}",
    "",
    "function moduleGameStudioNormalizeAsset(assetRaw, fallbackId) {",
    "    const asset = assetRaw && typeof assetRaw === 'object' ? assetRaw : {};",
    "    const id = safeString(asset.id) || safeString(fallbackId) || `asset-${Date.now()}`;",
    "    const typeRaw = safeString(asset.type).toLowerCase();",
    "    const type = MODULE_GAME_ASSET_TYPES.some((row) => safeString(row.id) === typeRaw)",
    "        ? typeRaw",
    "        : 'mesh';",
    "    return {",
    "        id,",
    "        name: safeString(asset.name) || `Asset ${id}`,",
    "        type,",
    "        source: safeString(asset.source) || '/Game',",
    "        tags: Array.isArray(asset.tags)",
    "            ? asset.tags.map((tag) => safeString(tag)).filter(Boolean).slice(0, 12)",
    "            : [],",
    "    };",
    "}",
    "",
    "function moduleGameStudioEnsureAssets(wb) {",
    "    if (!wb) return;",
    "    const defaults = moduleGameStudioDefaultAssets();",
    "    const incoming = Array.isArray(wb.assets) && wb.assets.length ? wb.assets : defaults;",
    "    const seen = new Set();",
    "    wb.assets = incoming.map((asset, index) => moduleGameStudioNormalizeAsset(asset, `asset-${index + 1}`))",
    "        .filter((asset) => {",
    "            if (seen.has(asset.id)) return false;",
    "            seen.add(asset.id);",
    "            return true;",
    "        })",
    "        .slice(0, 180);",
    "    wb.selectedAssetId = safeString(wb.selectedAssetId);",
    "    if (!wb.assets.some((asset) => safeString(asset.id) === wb.selectedAssetId)) {",
    "        wb.selectedAssetId = safeString(wb.assets[0]?.id);",
    "    }",
    "    wb.assetFilterType = MODULE_GAME_ASSET_TYPES.some((row) => safeString(row.id) === safeString(wb.assetFilterType).toLowerCase())",
    "        ? safeString(wb.assetFilterType).toLowerCase()",
    "        : 'all';",
    "    wb.assetSearch = safeString(wb.assetSearch);",
    "}",
    "",
    "function moduleGameStudioFilteredAssets(wb) {",
    "    const rows = Array.isArray(wb?.assets) ? wb.assets : [];",
    "    const type = safeString(wb?.assetFilterType).toLowerCase() || 'all';",
    "    const query = safeString(wb?.assetSearch).trim().toLowerCase();",
    "    return rows.filter((asset) => {",
    "        const assetType = safeString(asset?.type).toLowerCase();",
    "        if (type !== 'all' && assetType !== type) return false;",
    "        if (!query) return true;",
    "        const haystack = `${safeString(asset?.name)} ${safeString(asset?.source)} ${(Array.isArray(asset?.tags) ? asset.tags.join(' ') : '')}`.toLowerCase();",
    "        return haystack.includes(query);",
    "    });",
    "}",
    "",
    "function moduleGameStudioAssetById(wb, assetIdRaw) {",
    "    const assetId = safeString(assetIdRaw);",
    "    const rows = Array.isArray(wb?.assets) ? wb.assets : [];",
    "    return rows.find((asset) => safeString(asset?.id) === assetId) || null;",
    "}",
    "",
    "function moduleGameStudioBridgeState(wb) {",
    "    if (!wb) return {};",
    "    if (!wb.bridge || typeof wb.bridge !== 'object') {",
    "        wb.bridge = {};",
    "    }",
    "    const bridge = wb.bridge;",
    "    bridge.status = safeString(bridge.status).toLowerCase() || 'idle';",
    "    bridge.lastPingMs = Number(bridge.lastPingMs) || 0;",
    "    bridge.lastSeenAt = Number(bridge.lastSeenAt) || 0;",
    "    bridge.lastError = safeString(bridge.lastError);",
    "    bridge.routes = Array.isArray(bridge.routes) ? bridge.routes.slice(0, 120) : [];",
    "    bridge.pullCount = Number(bridge.pullCount) || 0;",
    "    bridge.pushCount = Number(bridge.pushCount) || 0;",
    "    bridge.actorSyncPath = safeString(bridge.actorSyncPath) || '/Game/Blueprints/BP_LevelBridge.BP_LevelBridge_C';",
    "    return bridge;",
    "}",
    "",
    "async function moduleGameStudioBridgeFetch(wb, endpointRaw, { method = 'GET', body = null, timeoutMs = 4800 } = {}) {",
    "    const url = moduleGameStudioRemoteUrl(wb.unrealRcUrl, endpointRaw);",
    "    if (!url) throw new Error('Set Unreal RC URL first.');",
    "    const started = Date.now();",
    "    const controller = typeof AbortController !== 'undefined' ? new AbortController() : null;",
    "    let timerId = 0;",
    "    if (controller && Number(timeoutMs) > 0) {",
    "        timerId = window.setTimeout(() => controller.abort(), Number(timeoutMs));",
    "    }",
    "    try {",
    "        const response = await fetch(url, {",
    "            method,",
    "            headers: body ? { 'Content-Type': 'application/json' } : undefined,",
    "            body: body ? JSON.stringify(body) : undefined,",
    "            signal: controller ? controller.signal : undefined,",
    "        });",
    "        const text = await response.text();",
    "        let payload = text;",
    "        try {",
    "            payload = text ? JSON.parse(text) : null;",
    "        } catch (_error) {}",
    "        return {",
    "            ok: response.ok,",
    "            status: response.status,",
    "            statusText: safeString(response.statusText),",
    "            elapsedMs: Date.now() - started,",
    "            url,",
    "            body: payload,",
    "        };",
    "    } finally {",
    "        if (timerId > 0) window.clearTimeout(timerId);",
    "    }",
    "}",
    "",
    "async function moduleGameStudioBridgePing(wb, { silent = false } = {}) {",
    "    const bridge = moduleGameStudioBridgeState(wb);",
    "    try {",
    "        const response = await moduleGameStudioBridgeFetch(wb, '/remote/info', { method: 'GET', timeoutMs: 4200 });",
    "        bridge.status = response.ok ? 'online' : 'degraded';",
    "        bridge.lastPingMs = Number(response.elapsedMs) || 0;",
    "        bridge.lastSeenAt = Date.now();",
    "        bridge.lastError = response.ok ? '' : `HTTP ${response.status}`;",
    "        const routeSource = response?.body && typeof response.body === 'object'",
    "            ? (Array.isArray(response.body.routes)",
    "                ? response.body.routes",
    "                : Array.isArray(response.body.pathes)",
    "                    ? response.body.pathes",
    "                    : [])",
    "            : [];",
    "        bridge.routes = routeSource",
    "            .map((row) => safeString(typeof row === 'string' ? row : row?.path || row?.route || row?.name))",
    "            .filter(Boolean)",
    "            .slice(0, 120);",
    "        if (!silent) {",
    "            moduleWorkbenchPushLog(",
    "                wb.logs,",
    "                response.ok",
    "                    ? `Bridge ping ok (${response.elapsedMs} ms).`",
    "                    : `Bridge ping degraded (${response.status}).`,",
    "                response.ok ? 'ok' : 'warn',",
    "                80,",
    "                'game-log',",
    "            );",
    "        }",
    "        return response;",
    "    } catch (error) {",
    "        bridge.status = 'offline';",
    "        bridge.lastPingMs = 0;",
    "        bridge.lastError = safeString(error?.message) || 'Ping failed.';",
    "        if (!silent) {",
    "            moduleWorkbenchPushLog(wb.logs, bridge.lastError, 'error', 80, 'game-log');",
    "        }",
    "        return {",
    "            ok: false,",
    "            status: 0,",
    "            statusText: 'error',",
    "            elapsedMs: 0,",
    "            url: moduleGameStudioRemoteUrl(wb.unrealRcUrl, '/remote/info'),",
    "            body: { error: bridge.lastError },",
    "        };",
    "    }",
    "}",
    "",
    "async function moduleGameStudioBridgePushSelectedActor(wb) {",
    "    const actor = moduleGameStudioActorById(wb, wb.selectedActorId);",
    "    if (!actor) throw new Error('Select an actor to push.');",
    "    const bridge = moduleGameStudioBridgeState(wb);",
    "    const payload = {",
    "        objectPath: bridge.actorSyncPath,",
    "        functionName: 'ApplyActorPatch',",
    "        parameters: {",
    "            id: safeString(actor.id),",
    "            name: safeString(actor.name),",
    "            className: safeString(actor.className),",
    "            assetId: safeString(actor.assetId),",
    "            transform: {",
    "                x: Number(actor.x) || 0,",
    "                y: Number(actor.y) || 0,",
    "                z: Number(actor.z) || 0,",
    "                rx: Number(actor.rx) || 0,",
    "                ry: Number(actor.ry) || 0,",
    "                rz: Number(actor.rz) || 0,",
    "                sx: Number(actor.sx) || 1,",
    "                sy: Number(actor.sy) || 1,",
    "                sz: Number(actor.sz) || 1,",
    "            },",
    "        },",
    "    };",
    "    const result = await moduleGameStudioRemoteSend(wb, payload);",
    "    if (result.ok) bridge.pushCount = (Number(bridge.pushCount) || 0) + 1;",
    "    return result;",
    "}",
    "",
    "async function moduleGameStudioBridgePushScene(wb) {",
    "    const bridge = moduleGameStudioBridgeState(wb);",
    "    const payload = {",
    "        objectPath: bridge.actorSyncPath,",
    "        functionName: 'ApplySceneSnapshot',",
    "        parameters: {",
    "            sceneActors: Array.isArray(wb.sceneActors) ? wb.sceneActors.slice(0, 320) : [],",
    "            assets: Array.isArray(wb.assets) ? wb.assets.slice(0, 320) : [],",
    "            tiles: wb.tiles,",
    "            gridWidth: wb.gridWidth,",
    "            gridHeight: wb.gridHeight,",
    "        },",
    "    };",
    "    const result = await moduleGameStudioRemoteSend(wb, payload);",
    "    if (result.ok) bridge.pushCount = (Number(bridge.pushCount) || 0) + 1;",
    "    return result;",
    "}",
    "",
    "async function moduleGameStudioBridgePullState(wb) {",
    "    const bridge = moduleGameStudioBridgeState(wb);",
    "    const payload = {",
    "        objectPath: bridge.actorSyncPath,",
    "        functionName: 'RequestSceneSnapshot',",
    "        parameters: {},",
    "    };",
    "    const result = await moduleGameStudioRemoteSend(wb, payload);",
    "    if (result.ok) {",
    "        bridge.pullCount = (Number(bridge.pullCount) || 0) + 1;",
    "    }",
    "    const body = result?.body && typeof result.body === 'object' ? result.body : {};",
    "    const params = body?.ReturnValue && typeof body.ReturnValue === 'object'",
    "        ? body.ReturnValue",
    "        : body?.returnValue && typeof body.returnValue === 'object'",
    "            ? body.returnValue",
    "            : body;",
    "    if (params && typeof params === 'object') {",
    "        const remoteWidth = Number(params.gridWidth);",
    "        const remoteHeight = Number(params.gridHeight);",
    "        if (Number.isFinite(remoteWidth) || Number.isFinite(remoteHeight)) {",
    "            moduleGameStudioResizeGrid(",
    "                wb,",
    "                Number.isFinite(remoteWidth) ? remoteWidth : wb.gridWidth,",
    "                Number.isFinite(remoteHeight) ? remoteHeight : wb.gridHeight,",
    "            );",
    "        }",
    "        if (Array.isArray(params.tiles)) {",
    "            const incomingTiles = params.tiles;",
    "            wb.tiles = Array.from({ length: wb.gridHeight }, (_row, y) => (",
    "                Array.from({ length: wb.gridWidth }, (_col, x) => moduleWorkbenchClamp(Number(incomingTiles?.[y]?.[x]) || 0, 0, 4))",
    "            ));",
    "        }",
    "        if (Array.isArray(params.sceneActors)) {",
    "            wb.sceneActors = params.sceneActors.map((actor, index) => moduleGameStudioNormalizeActor(actor, `pull-actor-${index + 1}`));",
    "        }",
    "        if (Array.isArray(params.assets)) {",
    "            wb.assets = params.assets.map((asset, index) => moduleGameStudioNormalizeAsset(asset, `pull-asset-${index + 1}`));",
    "        }",
    "        wb.selectedActorId = safeString(params.selectedActorId) || wb.selectedActorId;",
    "        wb.selectedAssetId = safeString(params.selectedAssetId) || wb.selectedAssetId;",
    "    }",
    "    moduleGameStudioSyncSceneActorsFromTiles(wb);",
    "    moduleGameStudioEnsureAssets(wb);",
    "    return result;",
    "}",
    "",
    "function moduleGameStudioRemoteUrl(baseRaw, endpointRaw) {",
    "    const base = safeString(baseRaw).trim();",
    "    const endpoint = safeString(endpointRaw).trim();",
    "    if (!base) return '';",
    "    try {",
    "        return new URL(endpoint || '/', base).toString();",
    "    } catch (_error) {",
    "        const normalizedBase = base.replace(/\\/+$/, '');",
    "        if (!endpoint) return normalizedBase;",
    "        const normalizedEndpoint = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;",
    "        return `${normalizedBase}${normalizedEndpoint}`;",
    "    }",
    "}",
    "",
    "async function moduleGameStudioRemoteSend(wb, payloadOverride = null, endpointOverride = '') {",
    "    const url = moduleGameStudioRemoteUrl(wb.unrealRcUrl, endpointOverride || wb.unrealRcEndpoint);",
    "    if (!url) throw new Error('Set Unreal RC URL first.');",
    "    let payload = {};",
    "    if (payloadOverride && typeof payloadOverride === 'object') {",
    "        payload = payloadOverride;",
    "    } else {",
    "        const payloadRaw = safeString(wb.unrealRcPayload).trim();",
    "        if (payloadRaw) {",
    "            try {",
    "                payload = JSON.parse(payloadRaw);",
    "            } catch (_error) {",
    "                throw new Error('Unreal RC payload must be valid JSON.');",
    "            }",
    "        }",
    "    }",
    "    const started = Date.now();",
    "    const response = await fetch(url, {",
    "        method: 'POST',",
    "        headers: { 'Content-Type': 'application/json' },",
    "        body: JSON.stringify(payload),",
    "    });",
    "    const text = await response.text();",
    "    let body = text;",
    "    try {",
    "        body = text ? JSON.parse(text) : null;",
    "    } catch (_error) {}",
    "    return {",
    "        ok: response.ok,",
    "        status: response.status,",
    "        statusText: safeString(response.statusText),",
    "        elapsedMs: Date.now() - started,",
    "        url,",
    "        body,",
    "    };",
    "}",
    "",
    "function moduleGameStudioCommands(wb) {",
    "    const godotPath = safeString(wb.godotProjectPath) || 'C:/games/MyGodotProject';",
    "    const unrealPath = safeString(wb.unrealProjectPath) || 'C:/games/MyUnrealProject/MyGame.uproject';",
    "    return {",
    "        godotOpen: `godot4 --path \"${godotPath}\"`,",
    "        godotBuild: `godot4 --headless --path \"${godotPath}\" --export-release \"Windows Desktop\"`,",
    "        unrealOpen: `UnrealEditor.exe \"${unrealPath}\"`,",
    "        unrealBuild: `RunUAT.bat BuildCookRun -project=\"${unrealPath}\" -platform=Win64 -build -cook -stage -pak`,",
    "    };",
    "}",
    "",
    "const MODULE_GAME_ENGINE_CATALOG = [",
    "    {",
    "        id: 'unreal',",
    "        label: 'Unreal Engine',",
    "        tag: 'AAA',",
    "        summary: 'High-fidelity runtime and cinematic pipeline.',",
    "        pathHint: 'C:/games/MyUnrealProject/MyGame.uproject',",
    "        launchLabel: 'Launch Unreal',",
    "    },",
    "    {",
    "        id: 'godot',",
    "        label: 'Godot',",
    "        tag: 'MIT',",
    "        summary: 'Fast open-source workflow and lightweight exports.',",
    "        pathHint: 'C:/games/MyGodotProject',",
    "        launchLabel: 'Launch Godot',",
    "    },",
    "    {",
    "        id: 'o3de',",
    "        label: 'O3DE',",
    "        tag: 'Open 3D',",
    "        summary: 'Large-scale simulation and advanced rendering stack.',",
    "        pathHint: 'C:/games/O3DE/Project',",
    "        launchLabel: 'Launch O3DE',",
    "    },",
    "    {",
    "        id: 'bevy',",
    "        label: 'Bevy',",
    "        tag: 'Rust',",
    "        summary: 'Data-driven ECS workflows for rapid prototypes.',",
    "        pathHint: 'C:/games/bevy-project',",
    "        launchLabel: 'Launch Bevy',",
    "    },",
    "    {",
    "        id: 'unity',",
    "        label: 'Unity',",
    "        tag: 'Connector',",
    "        summary: 'Connected through external editor bridge and CLI.',",
    "        pathHint: 'C:/games/UnityProject',",
    "        launchLabel: 'Launch Unity',",
    "    },",
    "    {",
    "        id: 'custom',",
    "        label: 'Custom Engine',",
    "        tag: 'SDK',",
    "        summary: 'Use Thomas plugin hooks for in-house runtimes.',",
    "        pathHint: 'C:/games/custom-engine',",
    "        launchLabel: 'Open Connector',",
    "    },",
    "];",
    "",
    "function moduleGameStudioEngineById(engineIdRaw) {",
    "    const engineId = safeString(engineIdRaw).toLowerCase();",
    "    return MODULE_GAME_ENGINE_CATALOG.find((engine) => safeString(engine.id) === engineId) || MODULE_GAME_ENGINE_CATALOG[0];",
    "}",
    "",
    "function moduleGameStudioProjectNormalize(projectRaw, fallbackId, engineIdRaw) {",
    "    const project = projectRaw && typeof projectRaw === 'object' ? projectRaw : {};",
    "    const engine = moduleGameStudioEngineById(engineIdRaw);",
    "    const id = safeString(project.id) || safeString(fallbackId) || `project-${Date.now()}`;",
    "    const pathValue = safeString(project.path) || safeString(engine.pathHint);",
    "    const tasks = Array.isArray(project.tasks)",
    "        ? project.tasks.map((item) => safeString(item)).filter(Boolean).slice(0, 8)",
    "        : [];",
    "    return {",
    "        id,",
    "        name: safeString(project.name) || 'Untitled Project',",
    "        path: pathValue,",
    "        status: safeString(project.status).toLowerCase() || 'planning',",
    "        focus: safeString(project.focus) || 'Define loop, player verbs, and build milestone.',",
    "        learning: safeString(project.learning) || 'Capture unknowns and test assumptions each run.',",
    "        tasks,",
    "        updatedAt: Number(project.updatedAt) || Date.now(),",
    "    };",
    "}",
    "",
    "function moduleGameStudioEnsureDirectorState(wb) {",
    "    if (!wb || typeof wb !== 'object') return;",
    "    wb.selectedEngine = safeString(wb.selectedEngine).toLowerCase() || 'unreal';",
    "    if (!MODULE_GAME_ENGINE_CATALOG.some((engine) => safeString(engine.id) === wb.selectedEngine)) {",
    "        wb.selectedEngine = 'unreal';",
    "    }",
    "    if (!wb.engineProjects || typeof wb.engineProjects !== 'object') wb.engineProjects = {};",
    "    if (!wb.activeProjectByEngine || typeof wb.activeProjectByEngine !== 'object') wb.activeProjectByEngine = {};",
    "    MODULE_GAME_ENGINE_CATALOG.forEach((engine, index) => {",
    "        const key = safeString(engine.id);",
    "        const seed = index === 0",
    "            ? [{",
    "                id: `${key}-project-1`,",
    "                name: key === 'unreal' ? 'Probe Arena' : `${engine.label} Prototype`,",
    "                path: safeString(engine.pathHint),",
    "                status: 'planning',",
    "                focus: 'Ship first playable slice with one clear objective.',",
    "                learning: 'Validate control feel and production velocity in week one.',",
    "                tasks: ['Define gameplay loop', 'Create graybox level', 'Run first playtest'],",
    "                updatedAt: Date.now(),",
    "            }]",
    "            : [];",
    "        const rowsRaw = Array.isArray(wb.engineProjects[key]) ? wb.engineProjects[key] : seed;",
    "        const seen = new Set();",
    "        wb.engineProjects[key] = rowsRaw",
    "            .map((row, rowIndex) => moduleGameStudioProjectNormalize(row, `${key}-project-${rowIndex + 1}`, key))",
    "            .filter((row) => {",
    "                if (seen.has(row.id)) return false;",
    "                seen.add(row.id);",
    "                return true;",
    "            })",
    "            .slice(0, 120);",
    "        const activeId = safeString(wb.activeProjectByEngine[key]);",
    "        if (!wb.engineProjects[key].some((row) => safeString(row.id) === activeId)) {",
    "            wb.activeProjectByEngine[key] = safeString(wb.engineProjects[key][0]?.id);",
    "        }",
    "    });",
    "    if (!Array.isArray(wb.studioChat)) wb.studioChat = [];",
    "    wb.studioChat = wb.studioChat",
    "        .map((msgRaw, index) => {",
    "            const msg = msgRaw && typeof msgRaw === 'object' ? msgRaw : {};",
    "            return {",
    "                id: safeString(msg.id) || `chat-${index + 1}`,",
    "                role: safeString(msg.role).toLowerCase() === 'assistant' ? 'assistant' : 'user',",
    "                text: safeString(msg.text).slice(0, 2200),",
    "                time: safeString(msg.time) || moduleWorkbenchTimeStamp(),",
    "            };",
    "        })",
    "        .slice(-40);",
    "    if (!wb.studioChat.length) {",
    "        wb.studioChat.push({",
    "            id: `chat-seed-${Date.now()}`,",
    "            role: 'assistant',",
    "            text: 'Game Studio ready. Pick an engine tile, pick a project, then tell Thomas what to build.',",
    "            time: moduleWorkbenchTimeStamp(),",
    "        });",
    "    }",
    "    wb.chatDraft = safeString(wb.chatDraft);",
    "    wb.projectDraftName = safeString(wb.projectDraftName);",
    "    wb.projectDraftPath = safeString(wb.projectDraftPath);",
    "    moduleGameStudioBridgeState(wb);",
    "}",
    "",
    "function moduleGameStudioCurrentProject(wb) {",
    "    const engineId = safeString(wb?.selectedEngine).toLowerCase();",
    "    const rows = Array.isArray(wb?.engineProjects?.[engineId]) ? wb.engineProjects[engineId] : [];",
    "    const activeId = safeString(wb?.activeProjectByEngine?.[engineId]);",
    "    return rows.find((row) => safeString(row.id) === activeId) || rows[0] || null;",
    "}",
    "",
    "function moduleGameStudioSetCurrentProject(wb, projectIdRaw) {",
    "    if (!wb || typeof wb !== 'object') return;",
    "    const engineId = safeString(wb.selectedEngine).toLowerCase();",
    "    const rows = Array.isArray(wb.engineProjects?.[engineId]) ? wb.engineProjects[engineId] : [];",
    "    const projectId = safeString(projectIdRaw);",
    "    if (!rows.some((row) => safeString(row.id) === projectId)) return;",
    "    wb.activeProjectByEngine[engineId] = projectId;",
    "}",
    "",
    "function moduleGameStudioAssistantReply(wb, promptRaw) {",
    "    const prompt = safeString(promptRaw).trim();",
    "    const engine = moduleGameStudioEngineById(wb?.selectedEngine);",
    "    const project = moduleGameStudioCurrentProject(wb);",
    "    const lower = prompt.toLowerCase();",
    "    const projectName = safeString(project?.name) || 'current project';",
    "    if (lower.includes('plan') || lower.includes('roadmap')) {",
    "        return [",
    "            `Plan locked for ${projectName} (${engine.label}).`,",
    "            '1) graybox core loop',",
    "            '2) playable objective',",
    "            '3) test pass + tuning',",
    "            '4) content expansion',",
    "        ].join('\\n');",
    "    }",
    "    if (lower.includes('launch') || lower.includes('open')) {",
    "        return `Ready to launch ${projectName}. Use Launch in the project card, then I can iterate from logs and playtest feedback.`;",
    "    }",
    "    if (lower.includes('build') || lower.includes('ship')) {",
    "        return `Build path for ${projectName}: run automated checks, package the build, then produce patch notes. Use Build in project actions to trigger command handoff.`;",
    "    }",
    "    if (lower.includes('learn') || lower.includes('research')) {",
    "        return `Learning track for ${projectName}: capture 3 references, define one mechanic benchmark, then run a proof scene by end of day.`;",
    "    }",
    "    return `Working in ${engine.label} on ${projectName}. I can plan features, generate tasks, launch tooling, and run build/playtest loops from this tab.`;",
    "}",
    "",
    "function moduleGameStudioOpenCommand(engineIdRaw, projectPathRaw, wb) {",
    "    const engine = moduleGameStudioEngineById(engineIdRaw);",
    "    const projectPath = safeString(projectPathRaw) || safeString(engine.pathHint);",
    "    if (safeString(engine.id) === 'unreal') {",
    "        wb.unrealProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).unrealOpen;",
    "    }",
    "    if (safeString(engine.id) === 'godot') {",
    "        wb.godotProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).godotOpen;",
    "    }",
    "    if (safeString(engine.id) === 'o3de') return `o3de.exe --project-path \"${projectPath}\"`;",
    "    if (safeString(engine.id) === 'bevy') return `cargo run --manifest-path \"${projectPath}/Cargo.toml\"`;",
    "    if (safeString(engine.id) === 'unity') return `Unity.exe -projectPath \"${projectPath}\"`;",
    "    return `thomas engine connect --engine custom --project \"${projectPath}\"`;",
    "}",
    "",
    "function moduleGameStudioBuildCommand(engineIdRaw, projectPathRaw, wb) {",
    "    const engine = moduleGameStudioEngineById(engineIdRaw);",
    "    const projectPath = safeString(projectPathRaw) || safeString(engine.pathHint);",
    "    if (safeString(engine.id) === 'unreal') {",
    "        wb.unrealProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).unrealBuild;",
    "    }",
    "    if (safeString(engine.id) === 'godot') {",
    "        wb.godotProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).godotBuild;",
    "    }",
    "    if (safeString(engine.id) === 'o3de') return `cmake --build \"${projectPath}/build\" --config profile`;",
    "    if (safeString(engine.id) === 'bevy') return `cargo build --manifest-path \"${projectPath}/Cargo.toml\" --release`;",
    "    if (safeString(engine.id) === 'unity') return `Unity.exe -batchmode -quit -projectPath \"${projectPath}\" -buildWindows64Player \"${projectPath}/Builds/Game.exe\"`;",
    "    return `thomas engine build --engine custom --project \"${projectPath}\"`;",
    "}",
    "",
    "function moduleGameStudioGodotTscn(wb) {",
    "    const lines = [",
    "        '[gd_scene load_steps=2 format=3]',",
    "        '',",
    "        '[node name=\"ThomasLevel\" type=\"Node2D\"]',",
    "        '[node name=\"Platforms\" type=\"Node2D\" parent=\".\"]',",
    "        '[node name=\"Hazards\" type=\"Node2D\" parent=\".\"]',",
    "        '',",
    "    ];",
    "    const tile = 32;",
    "    for (let y = 0; y < wb.gridHeight; y += 1) {",
    "        for (let x = 0; x < wb.gridWidth; x += 1) {",
    "            const type = Number(wb.tiles?.[y]?.[x]) || 0;",
    "            const px = x * tile;",
    "            const py = y * tile;",
    "            if (type === 1) lines.push(`[node name=\"Platform_${x}_${y}\" type=\"StaticBody2D\" parent=\"Platforms\"]`, `position = Vector2(${px}, ${py})`, '');",
    "            if (type === 2) lines.push(`[node name=\"Hazard_${x}_${y}\" type=\"Area2D\" parent=\"Hazards\"]`, `position = Vector2(${px}, ${py})`, '');",
    "            if (type === 3) lines.push('[node name=\"Spawn\" type=\"Marker2D\" parent=\".\"]', `position = Vector2(${px}, ${py})`, '');",
    "            if (type === 4) lines.push('[node name=\"Goal\" type=\"Marker2D\" parent=\".\"]', `position = Vector2(${px}, ${py})`, '');",
    "        }",
    "    }",
    "    return lines.join('\\n');",
    "}",
    "",
    "function moduleGameStudioUnrealCsv(wb) {",
    "    const rows = ['x,y,type'];",
    "    for (let y = 0; y < wb.gridHeight; y += 1) {",
    "        for (let x = 0; x < wb.gridWidth; x += 1) {",
    "            const type = Number(wb.tiles?.[y]?.[x]) || 0;",
    "            if (!type) continue;"
].join("\n");
