/* app.js lines 27001-28000 */
export default [
    "        wb.viewMode = moduleGameStudioViewMode(payload.viewMode || wb.viewMode);",
    "        wb.playTarget = moduleGameStudioPlayTarget(payload.playTarget || wb.playTarget);",
    "        wb.unrealViewportUrl = safeString(payload.unrealViewportUrl) || wb.unrealViewportUrl;",
    "        wb.unrealRcUrl = safeString(payload.unrealRcUrl) || wb.unrealRcUrl;",
    "        wb.unrealRcEndpoint = safeString(payload.unrealRcEndpoint) || wb.unrealRcEndpoint;",
    "        wb.unrealRcPayload = safeString(payload.unrealRcPayload) || wb.unrealRcPayload;",
    "        wb.aiPrompt = safeString(payload.aiPrompt) || wb.aiPrompt;",
    "        const rawSceneActors = Array.isArray(payload.sceneActors) ? payload.sceneActors : [];",
    "        wb.sceneActors = rawSceneActors.map((actor, index) => moduleGameStudioNormalizeActor(actor, `actor-load-${index + 1}`));",
    "        wb.selectedActorId = safeString(payload.selectedActorId) || wb.selectedActorId;",
    "        wb.nextActorId = Math.max(",
    "            Number(payload.nextActorId) || 1,",
    "            wb.sceneActors.length + 1,",
    "            Number(wb.nextActorId) || 1,",
    "        );",
    "        moduleGameStudioSyncSceneActorsFromTiles(wb);",
    "        const rawAssets = Array.isArray(payload.assets) ? payload.assets : [];",
    "        wb.assets = rawAssets.map((asset, index) => moduleGameStudioNormalizeAsset(asset, `asset-load-${index + 1}`));",
    "        wb.selectedAssetId = safeString(payload.selectedAssetId) || wb.selectedAssetId;",
    "        wb.assetFilterType = safeString(payload.assetFilterType).toLowerCase() || wb.assetFilterType;",
    "        wb.assetSearch = safeString(payload.assetSearch) || wb.assetSearch;",
    "        moduleGameStudioEnsureAssets(wb);",
    "        const bridge = moduleGameStudioBridgeState(wb);",
    "        bridge.actorSyncPath = safeString(payload.bridgeActorSyncPath) || bridge.actorSyncPath;",
    "        wb.viewportConnected = false;",
    "        wb.viewportLoadState = 'idle';",
    "        wb.viewportBlockedHint = false;",
    "    };",
    "    const setViewMode = (modeRaw, { silent = false } = {}) => {",
    "        const nextMode = moduleGameStudioViewMode(modeRaw);",
    "        const changed = wb.viewMode !== nextMode;",
    "        wb.viewMode = nextMode;",
    "        layout.dataset.gameView = wb.viewMode;",
    "        if (changed && !silent) {",
    "            moduleWorkbenchPushLog(wb.logs, `Viewport mode set to ${viewModeLabel().toLowerCase()}.`, 'ok', 80, 'game-log');",
    "        }",
    "    };",
    "    const renderViewportStatus = () => {",
    "        if (!safeString(wb.unrealViewportUrl)) {",
    "            wb.viewportConnected = false;",
    "            wb.viewportLoadState = 'idle';",
    "            wb.viewportBlockedHint = false;",
    "            viewportStatus.textContent = 'No URL';",
    "            blockedHint.classList.add('hidden');",
    "            return;",
    "        }",
    "        if (wb.viewportLoadState === 'pending') {",
    "            viewportStatus.textContent = 'Connecting';",
    "        } else if (wb.viewportLoadState === 'blocked') {",
    "            viewportStatus.textContent = 'Blocked';",
    "        } else {",
    "            viewportStatus.textContent = wb.viewportConnected ? 'Live' : 'Disconnected';",
    "        }",
    "        blockedHint.classList.toggle('hidden', !wb.viewportBlockedHint);",
    "    };",
    "    const mountUnrealViewport = (forceReload = false, { silent = false } = {}) => {",
    "        const url = safeString(wb.unrealViewportUrl).trim();",
    "        if (!url) {",
    "            wb.viewportConnected = false;",
    "            wb.viewportLoadState = 'idle';",
    "            wb.viewportBlockedHint = false;",
    "            viewportFrame.removeAttribute('src');",
    "            viewportFrame.dataset.viewportUrl = '';",
    "            if (Number(wb.viewportProbeTimer) > 0) {",
    "                window.clearTimeout(Number(wb.viewportProbeTimer));",
    "                wb.viewportProbeTimer = 0;",
    "            }",
    "            if (!silent) {",
    "                moduleWorkbenchPushLog(wb.logs, 'Set Unreal viewport URL before connecting.', 'warn', 80, 'game-log');",
    "            }",
    "            renderViewportStatus();",
    "            return false;",
    "        }",
    "        const cached = safeString(viewportFrame.dataset.viewportUrl);",
    "        if (!forceReload && cached === url && safeString(viewportFrame.getAttribute('src')) && wb.viewportLoadState !== 'blocked') {",
    "            renderViewportStatus();",
    "            return true;",
    "        }",
    "        if (Number(wb.viewportProbeTimer) > 0) {",
    "            window.clearTimeout(Number(wb.viewportProbeTimer));",
    "            wb.viewportProbeTimer = 0;",
    "        }",
    "        wb.viewportConnected = false;",
    "        wb.viewportLoadState = 'pending';",
    "        wb.viewportBlockedHint = false;",
    "        const finalUrl = forceReload",
    "            ? `${url}${url.includes('?') ? '&' : '?'}thomasReload=${Date.now()}`",
    "            : url;",
    "        viewportFrame.src = finalUrl;",
    "        viewportFrame.dataset.viewportUrl = url;",
    "        wb.viewportProbeTimer = window.setTimeout(() => {",
    "            wb.viewportProbeTimer = 0;",
    "            if (wb.viewportLoadState !== 'pending') return;",
    "            wb.viewportLoadState = 'blocked';",
    "            wb.viewportBlockedHint = true;",
    "            wb.viewportConnected = false;",
    "            moduleWorkbenchPushLog(",
    "                wb.logs,",
    "                'Unreal stream did not load in-frame. Host may block embedding (CSP/X-Frame-Options).',",
    "                'warn',",
    "                80,",
    "                'game-log',",
    "            );",
    "            render();",
    "        }, 2800);",
    "        if (!silent) {",
    "            moduleWorkbenchPushLog(wb.logs, `${forceReload ? 'Reloading' : 'Connecting'} Unreal viewport...`, 'ok', 80, 'game-log');",
    "        }",
    "        renderViewportStatus();",
    "        return true;",
    "    };",
    "    const playTargetLabel = () => {",
    "        if (wb.playTarget === 'unreal') return 'Unreal';",
    "        if (wb.playTarget === 'phaser') return 'Phaser';",
    "        return 'Auto';",
    "    };",
    "    const selectedActor = () => moduleGameStudioActorById(wb, wb.selectedActorId);",
    "    const selectedAsset = () => moduleGameStudioAssetById(wb, wb.selectedAssetId);",
    "    const updateBridgeFromResult = (resultRaw) => {",
    "        const result = resultRaw && typeof resultRaw === 'object' ? resultRaw : {};",
    "        const bridge = moduleGameStudioBridgeState(wb);",
    "        bridge.lastSeenAt = Date.now();",
    "        bridge.lastPingMs = Number(result.elapsedMs) || 0;",
    "        if (result.ok) {",
    "            bridge.status = 'online';",
    "            bridge.lastError = '';",
    "            return;",
    "        }",
    "        const statusCode = Number(result.status) || 0;",
    "        bridge.status = statusCode > 0 ? 'degraded' : 'offline';",
    "        bridge.lastError = safeString(result.statusText) || (statusCode > 0 ? `HTTP ${statusCode}` : 'Request failed.');",
    "    };",
    "    const runBridgeAction = (requestFactory, { successMessage = 'Bridge request completed.', failureMessage = 'Bridge request failed.' } = {}) => {",
    "        void requestFactory().then((result) => {",
    "            updateBridgeFromResult(result);",
    "            wb.unrealRcResponse = JSON.stringify(result, null, 2);",
    "            moduleWorkbenchPushLog(",
    "                wb.logs,",
    "                result?.ok ? successMessage : `${failureMessage} (${Number(result?.status) || 0}).`,",
    "                result?.ok ? 'ok' : 'warn',",
    "                80,",
    "                'game-log',",
    "            );",
    "            render();",
    "        }).catch((error) => {",
    "            const bridge = moduleGameStudioBridgeState(wb);",
    "            bridge.status = 'offline';",
    "            bridge.lastSeenAt = Date.now();",
    "            bridge.lastPingMs = 0;",
    "            bridge.lastError = safeString(error?.message) || failureMessage;",
    "            wb.unrealRcResponse = JSON.stringify({",
    "                ok: false,",
    "                error: bridge.lastError,",
    "            }, null, 2);",
    "            moduleWorkbenchPushLog(wb.logs, bridge.lastError, 'error', 80, 'game-log');",
    "            render();",
    "        });",
    "    };",
    "    const updateSelectedActorFields = () => {",
    "        const actor = selectedActor();",
    "        if (!actor) {",
    "            actorNameInput.value = '';",
    "            actorClassInput.value = 'marker';",
    "            actorXInput.value = '0';",
    "            actorYInput.value = '0';",
    "            actorZInput.value = '0';",
    "            actorRxInput.value = '0';",
    "            actorRyInput.value = '0';",
    "            actorRzInput.value = '0';",
    "            actorSxInput.value = '1';",
    "            actorSyInput.value = '1';",
    "            actorSzInput.value = '1';",
    "            actorMeta.textContent = 'No actor selected.';",
    "            return;",
    "        }",
    "        const asset = moduleGameStudioAssetById(wb, actor.assetId);",
    "        if (asset) wb.selectedAssetId = safeString(asset.id);",
    "        actorNameInput.value = safeString(actor.name);",
    "        actorClassInput.value = safeString(actor.className) || 'marker';",
    "        actorXInput.value = String(Number(actor.x) || 0);",
    "        actorYInput.value = String(Number(actor.y) || 0);",
    "        actorZInput.value = String(Number(actor.z) || 0);",
    "        actorRxInput.value = String(Number(actor.rx) || 0);",
    "        actorRyInput.value = String(Number(actor.ry) || 0);",
    "        actorRzInput.value = String(Number(actor.rz) || 0);",
    "        actorSxInput.value = String(Number(actor.sx) || 1);",
    "        actorSyInput.value = String(Number(actor.sy) || 1);",
    "        actorSzInput.value = String(Number(actor.sz) || 1);",
    "        const assetLabel = asset ? ` | ${safeString(asset.name)}` : '';",
    "        actorMeta.textContent = `${safeString(actor.className).toUpperCase()} // (${Number(actor.x) || 0}, ${Number(actor.y) || 0}, ${Number(actor.z) || 0})${assetLabel}`;",
    "    };",
    "    const applySelectedActorEdits = () => {",
    "        const actor = selectedActor();",
    "        if (!actor) {",
    "            moduleWorkbenchPushLog(wb.logs, 'Select an actor first.', 'warn', 80, 'game-log');",
    "            return false;",
    "        }",
    "        const nextClass = safeString(actorClassInput.value).toLowerCase() || safeString(actor.className);",
    "        const nextActor = moduleGameStudioNormalizeActor({",
    "            ...actor,",
    "            name: safeString(actorNameInput.value) || actor.name,",
    "            className: nextClass,",
    "            assetId: safeString(actor.assetId) || safeString(wb.selectedAssetId),",
    "            x: Number(actorXInput.value),",
    "            y: Number(actorYInput.value),",
    "            z: Number(actorZInput.value),",
    "            rx: Number(actorRxInput.value),",
    "            ry: Number(actorRyInput.value),",
    "            rz: Number(actorRzInput.value),",
    "            sx: Number(actorSxInput.value),",
    "            sy: Number(actorSyInput.value),",
    "            sz: Number(actorSzInput.value),",
    "        }, actor.id);",
    "        const rows = Array.isArray(wb.sceneActors) ? wb.sceneActors.map((row) => moduleGameStudioNormalizeActor(row)) : [];",
    "        const index = rows.findIndex((row) => safeString(row.id) === safeString(actor.id));",
    "        if (index < 0) return false;",
    "        rows[index] = nextActor;",
    "        wb.sceneActors = rows;",
    "        moduleGameStudioRebuildTilesFromActors(wb);",
    "        moduleGameStudioSyncSceneActorsFromTiles(wb);",
    "        wb.selectedActorId = safeString(nextActor.id);",
    "        moduleWorkbenchPushLog(wb.logs, `Updated actor ${safeString(nextActor.name)}.`, 'ok', 80, 'game-log');",
    "        return true;",
    "    };",
    "    const addActor = () => {",
    "        const index = (Array.isArray(wb.sceneActors) ? wb.sceneActors.length : 0) + 1;",
    "        const actor = moduleGameStudioNormalizeActor({",
    "            id: moduleGameStudioActorId(wb),",
    "            name: moduleGameStudioActorName('npc', index),",
    "            className: 'npc',",
    "            assetId: safeString(wb.selectedAssetId),",
    "            x: 1,",
    "            y: 1,",
    "            z: 0,",
    "            rx: 0,",
    "            ry: 0,",
    "            rz: 0,",
    "            sx: 1,",
    "            sy: 1,",
    "            sz: 1,",
    "        });",
    "        actor.tileBacked = false;",
    "        wb.sceneActors = [...(Array.isArray(wb.sceneActors) ? wb.sceneActors : []), actor];",
    "        wb.selectedActorId = safeString(actor.id);",
    "        moduleWorkbenchPushLog(wb.logs, `Added actor ${safeString(actor.name)}.`, 'ok', 80, 'game-log');",
    "        return actor;",
    "    };",
    "    const addAsset = () => {",
    "        const filterType = safeString(wb.assetFilterType).toLowerCase();",
    "        const type = filterType && filterType !== 'all' ? filterType : 'mesh';",
    "        const rawName = safeString(wb.assetSearch).replace(/[^\\w\\s.-]/g, '').trim();",
    "        const stamp = `${Date.now().toString(36)}${Math.floor(Math.random() * 46656).toString(36)}`;",
    "        const asset = moduleGameStudioNormalizeAsset({",
    "            id: `asset-${stamp}`,",
    "            name: rawName || `New ${type.toUpperCase()}`,",
    "            type,",
    "            source: '/Game/Generated',",
    "            tags: rawName ? ['custom', type] : [type],",
    "        });",
    "        wb.assets = [asset, ...(Array.isArray(wb.assets) ? wb.assets : [])].slice(0, 180);",
    "        wb.selectedAssetId = safeString(asset.id);",
    "        moduleGameStudioEnsureAssets(wb);",
    "        moduleWorkbenchPushLog(wb.logs, `Added asset ${safeString(asset.name)}.`, 'ok', 80, 'game-log');",
    "        return asset;",
    "    };",
    "    const placeSelectedAsset = () => {",
    "        const asset = selectedAsset();",
    "        if (!asset) {",
    "            moduleWorkbenchPushLog(wb.logs, 'Select an asset first.', 'warn', 80, 'game-log');",
    "            return false;",
    "        }",
    "        let actor = selectedActor();",
    "        let createdActor = false;",
    "        if (!actor) {",
    "            actor = addActor();",
    "            createdActor = true;",
    "        }",
    "        if (!actor) return false;",
    "        const rows = Array.isArray(wb.sceneActors) ? wb.sceneActors.map((row) => moduleGameStudioNormalizeActor(row)) : [];",
    "        const index = rows.findIndex((row) => safeString(row.id) === safeString(actor.id));",
    "        if (index < 0) return false;",
    "        const fallbackClass = asset.type === 'mesh' ? 'platform' : asset.type === 'blueprint' ? 'npc' : 'marker';",
    "        const rowActor = rows[index];",
    "        const className = createdActor ? fallbackClass : safeString(rowActor.className) || fallbackClass;",
    "        rows[index] = moduleGameStudioNormalizeActor({",
    "            ...rowActor,",
    "            className,",
    "            assetId: safeString(asset.id),",
    "            name: createdActor ? `${safeString(asset.name)} Actor` : rowActor.name,",
    "        }, rowActor.id);",
    "        wb.sceneActors = rows;",
    "        moduleGameStudioRebuildTilesFromActors(wb);",
    "        moduleGameStudioSyncSceneActorsFromTiles(wb);",
    "        wb.selectedActorId = safeString(rows[index].id);",
    "        moduleWorkbenchPushLog(",
    "            wb.logs,",
    "            `Placed ${safeString(asset.name)} on ${safeString(rows[index].name)}.`,",
    "            'ok',",
    "            80,",
    "            'game-log',",
    "        );",
    "        return true;",
    "    };",
    "    const removeSelectedAsset = () => {",
    "        const asset = selectedAsset();",
    "        if (!asset) {",
    "            moduleWorkbenchPushLog(wb.logs, 'No selected asset to remove.', 'warn', 80, 'game-log');",
    "            return false;",
    "        }",
    "        const previousId = safeString(asset.id);",
    "        let detachedCount = 0;",
    "        wb.sceneActors = (Array.isArray(wb.sceneActors) ? wb.sceneActors : []).map((row) => {",
    "            const actor = moduleGameStudioNormalizeActor(row);",
    "            if (safeString(actor.assetId) !== previousId) return actor;",
    "            detachedCount += 1;",
    "            return moduleGameStudioNormalizeActor({",
    "                ...actor,",
    "                assetId: '',",
    "            }, actor.id);",
    "        });",
    "        wb.assets = (Array.isArray(wb.assets) ? wb.assets : []).filter((row) => safeString(row?.id) !== previousId);",
    "        if (!wb.assets.length) {",
    "            wb.assets = [moduleGameStudioNormalizeAsset({",
    "                id: 'asset-prototype-cube',",
    "                name: 'SM_PrototypeCube',",
    "                type: 'mesh',",
    "                source: '/Game/Generated',",
    "                tags: ['fallback'],",
    "            })];",
    "        }",
    "        moduleGameStudioEnsureAssets(wb);",
    "        moduleGameStudioSyncSceneActorsFromTiles(wb);",
    "        moduleWorkbenchPushLog(",
    "            wb.logs,",
    "            `Removed asset ${safeString(asset.name)}${detachedCount > 0 ? ` and detached ${detachedCount} actor(s)` : ''}.`,",
    "            'warn',",
    "            80,",
    "            'game-log',",
    "        );",
    "        return true;",
    "    };",
    "    const deleteSelectedActor = () => {",
    "        const actor = selectedActor();",
    "        if (!actor) {",
    "            moduleWorkbenchPushLog(wb.logs, 'No actor selected to delete.', 'warn', 80, 'game-log');",
    "            return false;",
    "        }",
    "        const tileType = moduleGameStudioTileFromActorType(actor.className);",
    "        if (tileType > 0) {",
    "            const x = moduleWorkbenchClamp(Math.round(Number(actor.x) || 0), 0, wb.gridWidth - 1);",
    "            const y = moduleWorkbenchClamp(Math.round(Number(actor.y) || 0), 0, wb.gridHeight - 1);",
    "            if ((Number(wb.tiles?.[y]?.[x]) || 0) === tileType) {",
    "                wb.tiles[y][x] = 0;",
    "            }",
    "        }",
    "        wb.sceneActors = (Array.isArray(wb.sceneActors) ? wb.sceneActors : [])",
    "            .filter((row) => safeString(row?.id) !== safeString(actor.id));",
    "        moduleGameStudioRebuildTilesFromActors(wb);",
    "        moduleGameStudioSyncSceneActorsFromTiles(wb);",
    "        moduleWorkbenchPushLog(wb.logs, `Deleted actor ${safeString(actor.name)}.`, 'warn', 80, 'game-log');",
    "        return true;",
    "    };",
    "    const render = () => {",
    "        moduleGameStudioSyncSceneActorsFromTiles(wb);",
    "        layout.dataset.gameView = wb.viewMode;",
    "        viewModeBar.innerHTML = viewModes",
    "            .map((entry) => `<button type=\"button\" class=\"module-wb-tool-btn${entry.id === wb.viewMode ? ' active' : ''}\" data-game-view-mode=\"${entry.id}\"><span>${entry.label}</span></button>`)",
    "            .join('');",
    "        brushBar.innerHTML = brushes.map((brush) => `<button type=\"button\" class=\"module-wb-tool-btn${Number(wb.brush) === brush.id ? ' active' : ''}\" data-game-brush=\"${brush.id}\"><span>${brush.label}</span></button>`).join('');",
    "        const playTargetBtn = shell.querySelector('[data-game-action=\"play_target\"]');",
    "        if (playTargetBtn instanceof HTMLElement) {",
    "            playTargetBtn.textContent = `Target: ${playTargetLabel()}`;",
    "        }",
    "        grid.style.gridTemplateColumns = `repeat(${wb.gridWidth}, minmax(0, 1fr))`;",
    "        const cells = [];",
    "        for (let y = 0; y < wb.gridHeight; y += 1) {",
    "            for (let x = 0; x < wb.gridWidth; x += 1) {",
    "                cells.push(`<button type=\"button\" class=\"module-wb-game-cell tile-${moduleWorkbenchClamp(Number(wb.tiles[y][x]) || 0, 0, 4)}\" data-game-x=\"${x}\" data-game-y=\"${y}\"></button>`);",
    "            }",
    "        }",
    "        grid.innerHTML = cells.join('');",
    "        const counts = moduleGameStudioCounts(wb);",
    "        const actorRows = Array.isArray(wb.sceneActors) ? wb.sceneActors.slice(0, 140) : [];",
    "        outliner.innerHTML = actorRows.length",
    "            ? actorRows.map((actor) => {",
    "                const selected = safeString(actor.id) === safeString(wb.selectedActorId);",
    "                const className = safeString(actor.className).toLowerCase();",
    "                const asset = moduleGameStudioAssetById(wb, actor.assetId);",
    "                const assetLabel = asset ? ` | ${safeString(asset.name)}` : '';",
    "                return `",
    "                    <button type=\"button\" class=\"module-wb-outliner-row${selected ? ' active' : ''}\" data-game-outline-action=\"select_actor\" data-game-actor-id=\"${escapeHtml(safeString(actor.id))}\">",
    "                        <strong>${escapeHtml(safeString(actor.name) || 'Actor')}</strong>",
    "                        <span>${escapeHtml(`${className || 'actor'} | (${Number(actor.x) || 0}, ${Number(actor.y) || 0}, ${Number(actor.z) || 0})${assetLabel}`)}</span>",
    "                    </button>",
    "                `;",
    "            }).join('')",
    "            : '<div class=\"module-wb-ghost\">No actors in level.</div>';",
    "        const filteredAssets = moduleGameStudioFilteredAssets(wb).slice(0, 120);",
    "        assetsList.innerHTML = filteredAssets.length",
    "            ? filteredAssets.map((asset) => {",
    "                const selected = safeString(asset.id) === safeString(wb.selectedAssetId) ? ' selected' : '';",
    "                const usedBy = actorRows.filter((row) => safeString(row.assetId) === safeString(asset.id)).length;",
    "                return `",
    "                    <article class=\"module-wb-asset-row${selected}\" data-game-asset-id=\"${escapeHtml(safeString(asset.id))}\">",
    "                        <div>",
    "                            <strong>${escapeHtml(safeString(asset.name) || 'Asset')}</strong>",
    "                            <span>${escapeHtml(`${safeString(asset.type).toUpperCase()} | ${safeString(asset.source)}`)}</span>",
    "                        </div>",
    "                        <span>${usedBy}x</span>",
    "                    </article>",
    "                `;",
    "            }).join('')",
    "            : '<div class=\"module-wb-ghost\">No assets match filter.</div>';",
    "        const viewportLabel = wb.viewportLoadState === 'pending'",
    "            ? 'Connecting'",
    "            : wb.viewportLoadState === 'blocked'",
    "                ? 'Blocked'",
    "                : wb.viewportConnected",
    "                    ? 'Live'",
    "                    : 'Idle';",
    "        metrics.innerHTML = `",
    "            <div><span>Platforms</span><strong>${counts[1]}</strong></div>",
    "            <div><span>Hazards</span><strong>${counts[2]}</strong></div>",
    "            <div><span>Spawn</span><strong>${counts[3]}</strong></div>",
    "            <div><span>Goal</span><strong>${counts[4]}</strong></div>",
    "            <div><span>Actors</span><strong>${actorRows.length}</strong></div>",
    "            <div><span>Mode</span><strong>${escapeHtml(viewModeLabel())}</strong></div>",
    "            <div><span>Unreal</span><strong>${viewportLabel}</strong></div>",
    "        `;",
    "        status.textContent = `${wb.gridWidth}x${wb.gridHeight} | ${moduleGameStudioPlayable(wb) ? 'Playable path found' : 'No valid path'} | ${viewModeLabel()} | High ${Number(wb.highScore) || 0}`;",
    "        if (sizeWidthInput instanceof HTMLInputElement) sizeWidthInput.value = String(wb.gridWidth);",
    "        if (sizeHeightInput instanceof HTMLInputElement) sizeHeightInput.value = String(wb.gridHeight);",
    "        unrealUrlInput.value = safeString(wb.unrealViewportUrl);",
    "        rcUrlInput.value = safeString(wb.unrealRcUrl);",
    "        rcEndpointInput.value = safeString(wb.unrealRcEndpoint);",
    "        rcPayloadInput.value = safeString(wb.unrealRcPayload);",
    "        rcResponseInput.value = safeString(wb.unrealRcResponse);",
    "        aiPromptInput.value = safeString(wb.aiPrompt);",
    "        assetSearchInput.value = safeString(wb.assetSearch);",
    "        assetTypeSelect.value = safeString(wb.assetFilterType) || 'all';",
    "        const bridge = moduleGameStudioBridgeState(wb);",
    "        const lastSeen = Number(bridge.lastSeenAt) > 0",
    "            ? new Date(Number(bridge.lastSeenAt)).toLocaleTimeString()",
    "            : '--';",
    "        const bridgeStatusLabel = bridge.status === 'online'",
    "            ? 'Online'",
    "            : bridge.status === 'degraded'",
    "                ? 'Degraded'",
    "                : bridge.status === 'offline'",
    "                    ? 'Offline'",
    "                    : 'Idle';",
    "        bridgeMetrics.innerHTML = `",
    "            <div><span>Status</span><strong>${escapeHtml(bridgeStatusLabel)}</strong></div>",
    "            <div><span>Ping</span><strong>${Number(bridge.lastPingMs) > 0 ? `${Number(bridge.lastPingMs)} ms` : '--'}</strong></div>",
    "            <div><span>Routes</span><strong>${Array.isArray(bridge.routes) ? bridge.routes.length : 0}</strong></div>",
    "            <div><span>Pulls</span><strong>${Number(bridge.pullCount) || 0}</strong></div>",
    "            <div><span>Pushes</span><strong>${Number(bridge.pushCount) || 0}</strong></div>",
    "            <div><span>Last Seen</span><strong>${escapeHtml(lastSeen)}</strong></div>",
    "        `;",
    "        bridgeStatus.textContent = bridge.lastError",
    "            ? `Last error: ${safeString(bridge.lastError)}`",
    "            : `${bridgeStatusLabel}${Number(bridge.lastPingMs) > 0 ? ` (${Number(bridge.lastPingMs)} ms)` : ''}`;",
    "        updateSelectedActorFields();",
    "        renderProjectSelect();",
    "        renderViewportStatus();",
    "        logs.innerHTML = wb.logs.length",
    "            ? wb.logs.slice(0, 14).map((entry) => `<article class=\"module-wb-log-item ${moduleToneClass(entry.tone) || 'ok'}\"><span>${escapeHtml(safeString(entry.time))}</span><p>${escapeHtml(safeString(entry.message))}</p></article>`).join('')",
    "            : '<div class=\"module-wb-ghost\">No playtest logs yet.</div>';",
    "    };",
    "    const startPreview = ({ silent = false } = {}) => {",
    "        if (wb.phaserGame?.destroy && preview.querySelector('canvas')) return;",
    "        moduleGameStudioStartPhaserPreview(wb, preview, {",
    "            onGoal: () => {",
    "                moduleWorkbenchPushLog(wb.logs, 'Reached goal tile in playtest.', 'ok', 80, 'game-log');",
    "                render();",
    "            },",
    "            onHazard: () => {",
    "                moduleWorkbenchPushLog(wb.logs, 'Hit hazard tile in playtest.', 'warn', 80, 'game-log');",
    "                render();",
    "            },",
    "        });",
    "        if (!silent) moduleWorkbenchPushLog(wb.logs, 'Playtest started in Phaser runtime.', 'ok', 80, 'game-log');",
    "        render();",
    "    };",
    "    const stopPreview = ({ silent = false } = {}) => {",
    "        if (wb.phaserGame?.destroy) {",
    "            try {",
    "                wb.phaserGame.destroy(true);",
    "            } catch (_error) {}",
    "            wb.phaserGame = null;",
    "        }",
    "        preview.innerHTML = '';",
    "        if (!silent) moduleWorkbenchPushLog(wb.logs, 'Playtest stopped.', 'warn', 80, 'game-log');",
    "        render();",
    "    };",
    "    const exportLevel = () => ({",
    "        width: wb.gridWidth,",
    "        height: wb.gridHeight,",
    "        tiles: wb.tiles,",
    "        spawn: moduleGameStudioFindFirstTile(wb, 3),",
    "        goal: moduleGameStudioFindFirstTile(wb, 4),",
    "    });",
    "",
    "    if (wb.viewMode !== 'playtest' && wb.viewMode !== 'split' && wb.phaserGame?.destroy) {",
    "        try {",
    "            wb.phaserGame.destroy(true);",
    "        } catch (_error) {}",
    "        wb.phaserGame = null;",
    "    }",
    "    if (Number(wb.bridgePollTimer) > 0) {",
    "        window.clearInterval(Number(wb.bridgePollTimer));",
    "        wb.bridgePollTimer = 0;",
    "    }",
    "    wb.bridgePollTimer = window.setInterval(() => {",
    "        if (!document.body.contains(shell)) return;",
    "        void moduleGameStudioBridgePing(wb, { silent: true }).then(() => {",
    "            if (!document.body.contains(shell)) return;",
    "            render();",
    "        });",
    "    }, 12000);",
    "    void moduleGameStudioBridgePing(wb, { silent: true }).then(() => {",
    "        if (!document.body.contains(shell)) return;",
    "        render();",
    "    });",
    "    if (wb.viewMode === 'playtest' || wb.viewMode === 'split') startPreview({ silent: true });",
    "    if (wb.viewMode === 'unreal' || wb.viewMode === 'split') mountUnrealViewport(false, { silent: true });",
    "    render();",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const projectActionEl = event.target instanceof Element",
    "            ? event.target.closest('[data-wb-project-action][data-wb-project-mode=\"game_studio\"]')",
    "            : null;",
    "        if (projectActionEl) {",
    "            const action = safeString(projectActionEl.dataset.wbProjectAction).toLowerCase();",
    "            const select = shell.querySelector('select[data-wb-project-select=\"game_studio\"]');",
    "            const input = shell.querySelector('input[data-wb-project-name=\"game_studio\"]');",
    "            const selectedId = safeString(select instanceof HTMLSelectElement ? select.value : wb.selectedProjectId);",
    "            if (action === 'save') {",
    "                const savedId = moduleWorkbenchProjectSave('game_studio', projectPayload(), safeString(input instanceof HTMLInputElement ? input.value : ''));",
    "                wb.selectedProjectId = savedId;",
    "                if (input instanceof HTMLInputElement) input.value = '';",
    "                renderProjectSelect();",
    "                notifyUser('Game project saved.', { tone: 'success', durationMs: 1600, debugKind: 'game-studio' });",
    "                return;",
    "            }",
    "            if (action === 'load') {",
    "                if (!selectedId) return;",
    "                const project = moduleWorkbenchProjectGet('game_studio', selectedId);",
    "                if (!project?.payload) return;",
    "                stopPreview({ silent: true });",
    "                applyProjectPayload(project.payload);",
    "                wb.selectedProjectId = selectedId;",
    "                if (wb.viewMode === 'playtest' || wb.viewMode === 'split') startPreview({ silent: true });",
    "                if (wb.viewMode === 'unreal' || wb.viewMode === 'split') mountUnrealViewport(false, { silent: true });",
    "                render();",
    "                notifyUser(`Loaded game project: ${safeString(project.name)}.`, { tone: 'success', durationMs: 1800, debugKind: 'game-studio' });",
    "                return;",
    "            }",
    "            if (action === 'delete') {",
    "                if (!selectedId) return;",
    "                if (moduleWorkbenchProjectDelete('game_studio', selectedId)) {",
    "                    wb.selectedProjectId = '';",
    "                    renderProjectSelect();",
    "                    notifyUser('Deleted game project.', { tone: 'warn', durationMs: 1700, debugKind: 'game-studio' });",
    "                }",
    "                return;",
    "            }",
    "        }",
    "        const target = event.target instanceof Element ? event.target.closest('[data-game-brush], [data-game-view-mode], [data-game-action], [data-game-outline-action], [data-game-asset-id], [data-game-x][data-game-y]') : null;",
    "        if (!target) return;",
    "        const brush = safeString(target.dataset.gameBrush);",
    "        const viewMode = safeString(target.dataset.gameViewMode);",
    "        const action = safeString(target.dataset.gameAction).toLowerCase();",
    "        const outlineAction = safeString(target.dataset.gameOutlineAction).toLowerCase();",
    "        const assetId = safeString(target.dataset.gameAssetId);",
    "        if (assetId && !action) {",
    "            wb.selectedAssetId = assetId;",
    "            render();",
    "            return;",
    "        }",
    "        if (outlineAction === 'select_actor') {",
    "            wb.selectedActorId = safeString(target.dataset.gameActorId);",
    "            render();",
    "            return;",
    "        }",
    "        if (outlineAction === 'path_check') {",
    "            const pass = moduleGameStudioPlayable(wb);",
    "            moduleWorkbenchPushLog(wb.logs, pass ? 'Path check passed.' : 'Path check failed.', pass ? 'ok' : 'warn', 80, 'game-log');",
    "            render();",
    "            return;",
    "        }",
    "        if (viewMode) {",
    "            const previousMode = wb.viewMode;",
    "            setViewMode(viewMode);",
    "            if (wb.viewMode === 'playtest' || wb.viewMode === 'split') {",
    "                startPreview({ silent: true });",
    "            } else if (previousMode === 'playtest' || previousMode === 'split') {",
    "                stopPreview({ silent: true });",
    "            }",
    "            if (wb.viewMode === 'unreal' || wb.viewMode === 'split') mountUnrealViewport(false, { silent: true });",
    "            render();",
    "            return;",
    "        }",
    "        if (brush) {",
    "            wb.brush = moduleWorkbenchClamp(Number(brush) || 0, 0, 4);",
    "            render();",
    "            return;",
    "        }",
    "        const x = Number(target.dataset.gameX);",
    "        const y = Number(target.dataset.gameY);",
    "        if (Number.isFinite(x) && Number.isFinite(y)) {",
    "            paint(x, y);",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'playtest') {",
    "            const wantsUnreal = wb.playTarget === 'unreal'",
    "                || (wb.playTarget === 'auto' && (wb.viewMode === 'unreal' || wb.viewMode === 'split'));",
    "            if (wantsUnreal) {",
    "                const mounted = mountUnrealViewport(false, { silent: true });",
    "                if (mounted) {",
    "                    void moduleGameStudioRemoteSend(wb).then((result) => {",
    "                        updateBridgeFromResult(result);",
    "                        wb.unrealRcResponse = JSON.stringify(result, null, 2);",
    "                        moduleWorkbenchPushLog(",
    "                            wb.logs,",
    "                            `Engine play ${result.ok ? 'started' : 'request failed'} (${result.status}).`,",
    "                            result.ok ? 'ok' : 'warn',",
    "                            80,",
    "                            'game-log',",
    "                        );",
    "                        render();",
    "                    }).catch((error) => {",
    "                        moduleWorkbenchPushLog(",
    "                            wb.logs,",
    "                            safeString(error?.message) || 'Engine play request failed, using local simulation.',",
    "                            'warn',",
    "                            80,",
    "                            'game-log',",
    "                        );",
    "                        const bridge = moduleGameStudioBridgeState(wb);",
    "                        bridge.status = 'offline';",
    "                        bridge.lastSeenAt = Date.now();",
    "                        bridge.lastPingMs = 0;",
    "                        bridge.lastError = safeString(error?.message) || 'Engine play failed.';",
    "                        if (wb.playTarget === 'auto') {",
    "                            setViewMode('playtest', { silent: true });",
    "                            startPreview({ silent: true });",
    "                        }",
    "                        render();",
    "                    });",
    "                } else if (wb.playTarget === 'auto') {",
    "                    setViewMode('playtest', { silent: true });",
    "                    startPreview({ silent: true });",
    "                }",
    "                render();",
    "                return;",
    "            }",
    "            setViewMode('playtest', { silent: true });",
    "            startPreview();",
    "            return;",
    "        }",
    "        if (action === 'stop') {",
    "            stopPreview();",
    "            return;",
    "        }",
    "        if (action === 'play_target') {",
    "            const sequence = ['auto', 'phaser', 'unreal'];",
    "            const current = sequence.indexOf(wb.playTarget);",
    "            wb.playTarget = sequence[(current + 1) % sequence.length];",
    "            moduleWorkbenchPushLog(wb.logs, `Play target switched to ${playTargetLabel().toLowerCase()}.`, 'ok', 80, 'game-log');",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'add_actor') {",
    "            addActor();",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'asset_add') {",
    "            addAsset();",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'asset_place') {",
    "            placeSelectedAsset();",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'asset_remove') {",
    "            removeSelectedAsset();",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'apply_actor') {",
    "            applySelectedActorEdits();",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'delete_actor') {",
    "            deleteSelectedActor();",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'check') {",
    "            const pass = moduleGameStudioPlayable(wb);",
    "            moduleWorkbenchPushLog(wb.logs, pass ? 'Path check passed.' : 'Path check failed.', pass ? 'ok' : 'warn', 80, 'game-log');",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'clear') {",
    "            wb.tiles = Array.from({ length: wb.gridHeight }, () => Array.from({ length: wb.gridWidth }, () => 0));",
    "            moduleWorkbenchPushLog(wb.logs, 'Cleared level grid.', 'warn', 80, 'game-log');",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'resize') {",
    "            moduleGameStudioResizeGrid(",
    "                wb,",
    "                Number(sizeWidthInput instanceof HTMLInputElement ? sizeWidthInput.value : wb.gridWidth),",
    "                Number(sizeHeightInput instanceof HTMLInputElement ? sizeHeightInput.value : wb.gridHeight),",
    "            );",
    "            moduleWorkbenchPushLog(wb.logs, `Resized grid to ${wb.gridWidth}x${wb.gridHeight}.`, 'ok', 80, 'game-log');",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'export') {",
    "            moduleWorkbenchCopyJson(exportLevel(), 'Game Studio Level JSON');",
    "            return;",
    "        }",
    "        if (action === 'connect_unreal') {",
    "            mountUnrealViewport(false);",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'reload_unreal') {",
    "            mountUnrealViewport(true);",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'open_unreal') {",
    "            const url = safeString(wb.unrealViewportUrl).trim();",
    "            if (!url) return;",
    "            window.open(url, '_blank', 'noopener');",
    "            return;",
    "        }",
    "        if (action === 'bridge_ping') {",
    "            runBridgeAction(",
    "                () => moduleGameStudioBridgePing(wb, { silent: true }),",
    "                {",
    "                    successMessage: 'Bridge ping ok.',",
    "                    failureMessage: 'Bridge ping degraded',",
    "                },",
    "            );",
    "            return;",
    "        }",
    "        if (action === 'bridge_pull') {",
    "            runBridgeAction(",
    "                () => moduleGameStudioBridgePullState(wb),",
].join("\n");
