/* app.js lines 13001-14000 */
export default [
    "            Math.max(2, wall * 0.22),",
    "            'rgba(243, 249, 255, 0.28)',",
    "        );",
    "        officeCanvasBox(",
    "            ctx,",
    "            rect.x + wall,",
    "            rect.y + rect.h - wall - 2,",
    "            Math.max(3, rect.w - (wall * 2)),",
    "            Math.max(2, wall * 0.14),",
    "            'rgba(34, 47, 67, 0.2)',",
    "        );",
    "",
    "        const pillar = Math.max(3, Math.round(wall * 0.38));",
    "        officeCanvasRoundedBox(ctx, rect.x + 1, rect.y + 1, pillar, pillar, 2, 'rgba(212, 225, 246, 0.62)');",
    "        officeCanvasRoundedBox(ctx, rect.x + rect.w - pillar - 1, rect.y + 1, pillar, pillar, 2, 'rgba(212, 225, 246, 0.62)');",
    "        officeCanvasRoundedBox(ctx, rect.x + 1, rect.y + rect.h - pillar - 1, pillar, pillar, 2, 'rgba(76, 96, 126, 0.38)');",
    "        officeCanvasRoundedBox(ctx, rect.x + rect.w - pillar - 1, rect.y + rect.h - pillar - 1, pillar, pillar, 2, 'rgba(76, 96, 126, 0.38)');",
    "",
    "        // Subtle interior lines for a Gather-style tile feel.",
    "        ctx.strokeStyle = 'rgba(69, 87, 121, 0.3)';",
    "        ctx.lineWidth = 1;",
    "        for (let x = rect.x + wall + tile; x < rect.x + rect.w - wall; x += tile) {",
    "            ctx.beginPath();",
    "            ctx.moveTo(x + 0.5, rect.y + wall);",
    "            ctx.lineTo(x + 0.5, rect.y + rect.h - wall);",
    "            ctx.stroke();",
    "        }",
    "        for (let y = rect.y + wall + tile; y < rect.y + rect.h - wall; y += tile) {",
    "            ctx.beginPath();",
    "            ctx.moveTo(rect.x + wall, y + 0.5);",
    "            ctx.lineTo(rect.x + rect.w - wall, y + 0.5);",
    "            ctx.stroke();",
    "        }",
    "",
    "        const doorWidth = Math.max(24, Math.min(56, Math.min(rect.w, rect.h) * 0.24));",
    "        const doorDistances = {",
    "            top: Math.abs(rect.doorY - rect.y),",
    "            bottom: Math.abs(rect.doorY - (rect.y + rect.h)),",
    "            left: Math.abs(rect.doorX - rect.x),",
    "            right: Math.abs(rect.doorX - (rect.x + rect.w)),",
    "        };",
    "        const edge = Object.entries(doorDistances).sort((a, b) => a[1] - b[1])[0]?.[0] || 'bottom';",
    "        const doorAnchor = { x: rect.doorX, y: rect.doorY };",
    "        if (edge === 'top') doorAnchor.y = rect.y;",
    "        if (edge === 'bottom') doorAnchor.y = rect.y + rect.h;",
    "        if (edge === 'left') doorAnchor.x = rect.x;",
    "        if (edge === 'right') doorAnchor.x = rect.x + rect.w;",
    "        const doorDepth = Math.max(7, wall * 1.06);",
    "        const doorRadius = Math.max(3, Math.min(doorWidth, doorDepth) * 0.2);",
    "        const doorTrim = 'rgba(83, 106, 142, 0.78)';",
    "        const doorSill = 'rgba(119, 144, 180, 0.72)';",
    "",
    "        if (edge === 'top') {",
    "            officeCanvasRoundedBox(ctx, doorAnchor.x - (doorWidth / 2), rect.y - doorDepth + 1, doorWidth, doorDepth + 2, doorRadius, corridorFill, doorTrim, 1);",
    "            officeCanvasRoundedBox(ctx, doorAnchor.x - (doorWidth * 0.42), rect.y - doorDepth + 2, doorWidth * 0.84, Math.max(3, wall * 0.22), Math.max(2, doorRadius * 0.6), doorSill);",
    "            officeCanvasRoundedBox(ctx, doorAnchor.x - (doorWidth * 0.46), rect.y + wall - 4, doorWidth * 0.92, Math.max(2, wall * 0.16), Math.max(1.5, doorRadius * 0.52), 'rgba(54, 72, 102, 0.3)');",
    "        } else if (edge === 'bottom') {",
    "            officeCanvasRoundedBox(ctx, doorAnchor.x - (doorWidth / 2), rect.y + rect.h - 1, doorWidth, doorDepth + 1, doorRadius, corridorFill, doorTrim, 1);",
    "            officeCanvasRoundedBox(ctx, doorAnchor.x - (doorWidth * 0.42), rect.y + rect.h + 1, doorWidth * 0.84, Math.max(3, wall * 0.22), Math.max(2, doorRadius * 0.6), doorSill);",
    "            officeCanvasRoundedBox(ctx, doorAnchor.x - (doorWidth * 0.46), rect.y + rect.h - wall - 4, doorWidth * 0.92, Math.max(2, wall * 0.16), Math.max(1.5, doorRadius * 0.52), 'rgba(54, 72, 102, 0.3)');",
    "        } else if (edge === 'left') {",
    "            officeCanvasRoundedBox(ctx, rect.x - doorDepth + 1, doorAnchor.y - (doorWidth / 2), doorDepth + 2, doorWidth, doorRadius, corridorFill, doorTrim, 1);",
    "            officeCanvasRoundedBox(ctx, rect.x - doorDepth + 2, doorAnchor.y - (doorWidth * 0.42), Math.max(3, wall * 0.22), doorWidth * 0.84, Math.max(2, doorRadius * 0.6), doorSill);",
    "            officeCanvasRoundedBox(ctx, rect.x + wall - 4, doorAnchor.y - (doorWidth * 0.46), Math.max(2, wall * 0.16), doorWidth * 0.92, Math.max(1.5, doorRadius * 0.52), 'rgba(54, 72, 102, 0.3)');",
    "        } else {",
    "            officeCanvasRoundedBox(ctx, rect.x + rect.w - 1, doorAnchor.y - (doorWidth / 2), doorDepth + 1, doorWidth, doorRadius, corridorFill, doorTrim, 1);",
    "            officeCanvasRoundedBox(ctx, rect.x + rect.w + 1, doorAnchor.y - (doorWidth * 0.42), Math.max(3, wall * 0.22), doorWidth * 0.84, Math.max(2, doorRadius * 0.6), doorSill);",
    "            officeCanvasRoundedBox(ctx, rect.x + rect.w - wall - 4, doorAnchor.y - (doorWidth * 0.46), Math.max(2, wall * 0.16), doorWidth * 0.92, Math.max(1.5, doorRadius * 0.52), 'rgba(54, 72, 102, 0.3)');",
    "        }",
    "",
    "        // Draw a connector from each doorway to its hall node so corridors visually align with rooms.",
    "        const hallPx = hallNodePxById.get(safeString(room.hallId));",
    "        if (hallPx) {",
    "            const connectorHalf = Math.max(5, Math.min(12, doorWidth * 0.24));",
    "            const connectorStroke = 'rgba(128, 149, 183, 0.7)';",
    "            const connectorRadius = Math.max(3, connectorHalf * 0.9);",
    "            const drawConnector = (x1, y1, x2, y2) => {",
    "                const dx = x2 - x1;",
    "                const dy = y2 - y1;",
    "                if (Math.hypot(dx, dy) < 0.9) return;",
    "                if (Math.abs(dx) >= Math.abs(dy)) {",
    "                    const minX = Math.min(x1, x2);",
    "                    officeCanvasRoundedBox(",
    "                        ctx,",
    "                        minX,",
    "                        y1 - connectorHalf,",
    "                        Math.max(1.2, Math.abs(dx)),",
    "                        connectorHalf * 2,",
    "                        connectorRadius,",
    "                        corridorFill,",
    "                        connectorStroke,",
    "                        1,",
    "                    );",
    "                } else {",
    "                    const minY = Math.min(y1, y2);",
    "                    officeCanvasRoundedBox(",
    "                        ctx,",
    "                        x1 - connectorHalf,",
    "                        minY,",
    "                        connectorHalf * 2,",
    "                        Math.max(1.2, Math.abs(dy)),",
    "                        connectorRadius,",
    "                        corridorFill,",
    "                        connectorStroke,",
    "                        1,",
    "                    );",
    "                }",
    "            };",
    "",
    "            if (edge === 'top' || edge === 'bottom') {",
    "                drawConnector(doorAnchor.x, doorAnchor.y, doorAnchor.x, hallPx.y);",
    "                drawConnector(doorAnchor.x, hallPx.y, hallPx.x, hallPx.y);",
    "            } else {",
    "                drawConnector(doorAnchor.x, doorAnchor.y, hallPx.x, doorAnchor.y);",
    "                drawConnector(hallPx.x, doorAnchor.y, hallPx.x, hallPx.y);",
    "            }",
    "",
    "            officeCanvasCircle(",
    "                ctx,",
    "                doorAnchor.x,",
    "                doorAnchor.y,",
    "                Math.max(2.8, connectorHalf * 0.46),",
    "                'rgba(234, 241, 249, 0.98)',",
    "                'rgba(120, 142, 176, 0.72)',",
    "                1,",
    "            );",
    "        }",
    "",
    "        officeDrawRoomFurnitureCanvas(ctx, room, {",
    "            x: rect.x + wall + 6,",
    "            y: rect.y + wall + 6,",
    "            w: Math.max(4, rect.w - ((wall + 6) * 2)),",
    "            h: Math.max(4, rect.h - ((wall + 6) * 2)),",
    "        }, palette);",
    "    });",
    "",
    "    ctx.restore();",
    "}",
    "",
    "function officeRenderScene() {",
    "    if (!officeState || !officeScene) return;",
    "    officeScene.innerHTML = '';",
    "    const floorLayer = document.createElement('div');",
    "    floorLayer.className = 'office-floor-layer';",
    "    const tileCanvas = document.createElement('canvas');",
    "    tileCanvas.className = 'office-tilemap-canvas';",
    "    tileCanvas.width = officeState.mapWidth;",
    "    tileCanvas.height = officeState.mapHeight;",
    "    officeDrawTilemap(tileCanvas, officeState.rooms, officeState.corridors);",
    "",
    "    const roomLayer = document.createElement('div');",
    "    roomLayer.className = 'office-room-layer';",
    "",
    "    officeState.rooms.forEach((room) => {",
    "        const roomEl = document.createElement('section');",
    "        roomEl.className = `office-room overlay kind-${room.kind || 'work'} theme-${room.theme || 'work'}${room.dynamic ? ' dynamic' : ''}`;",
    "        roomEl.dataset.roomId = room.id;",
    "        roomEl.dataset.roomTheme = room.theme || room.kind || 'work';",
    "        roomEl.style.left = `${room.x}%`;",
    "        roomEl.style.top = `${room.y}%`;",
    "        roomEl.style.width = `${room.w}%`;",
    "        roomEl.style.height = `${room.h}%`;",
    "        roomEl.innerHTML = `",
    "            <div class=\"office-room-title\">${escapeHtml(room.label)}</div>",
    "            <div class=\"office-room-meta\">${escapeHtml(room.meta)}</div>",
    "        `;",
    "        roomLayer.appendChild(roomEl);",
    "    });",
    "",
    "    const agentLayer = document.createElement('div');",
    "    agentLayer.className = 'office-agent-layer';",
    "    officeScene.appendChild(floorLayer);",
    "    officeScene.appendChild(tileCanvas);",
    "    officeScene.appendChild(roomLayer);",
    "    officeScene.appendChild(agentLayer);",
    "",
    "    officeState.roomLayerEl = roomLayer;",
    "    officeState.agentLayerEl = agentLayer;",
    "    officeState.agentElements = new Map();",
    "    officeRenderAgents();",
    "    officeUpdateRoomMeta();",
    "}",
    "",
    "function officeSetEditorOpen(open) {",
    "    if (!officeEditorModal) return;",
    "    const isOpen = Boolean(open);",
    "    officeEditorModal.classList.toggle('hidden', !isOpen);",
    "    officeEditorModal.setAttribute('aria-hidden', isOpen ? 'false' : 'true');",
    "    if (officeWorkspace) {",
    "        officeWorkspace.classList.toggle('editor-open', isOpen);",
    "    }",
    "    if (officeEditorToggleBtn) {",
    "        officeEditorToggleBtn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');",
    "    }",
    "    if (isOpen) {",
    "        officeSyncCustomizerFields();",
    "        officeBusEmit('editor.opened', { selectedAgentId: officeState?.selectedAgentId || '' });",
    "        if (officeAgentSelect) {",
    "            window.setTimeout(() => {",
    "                officeAgentSelect.focus();",
    "            }, 0);",
    "        }",
    "    } else {",
    "        officeBusEmit('editor.closed', {});",
    "    }",
    "}",
    "",
    "function officeSyncCustomizerFields() {",
    "    if (!officeState) return;",
    "    const agent = officeGetAgentById(officeState.selectedAgentId) || officeState.agents[0];",
    "    if (!agent) return;",
    "    officeState.selectedAgentId = agent.id;",
    "    if (officeAgentSelect) officeAgentSelect.value = agent.id;",
    "    if (officeAgentNameInput) officeAgentNameInput.value = agent.name;",
    "    if (officeAgentColorInput) officeAgentColorInput.value = agent.color;",
    "    if (officeAgentCostumeSelect) officeAgentCostumeSelect.value = agent.costume || 'none';",
    "}",
    "",
    "function officeRenderAgentSelector(selectedId = '') {",
    "    if (!officeState || !officeAgentSelect) return;",
    "    const fallbackId = selectedId || officeState.selectedAgentId || officeState.agents[0]?.id || '';",
    "    officeAgentSelect.innerHTML = '';",
    "    officeState.agents.forEach((agent) => {",
    "        const option = document.createElement('option');",
    "        option.value = agent.id;",
    "        option.textContent = agent.name;",
    "        officeAgentSelect.appendChild(option);",
    "    });",
    "    if (officeState.agents.some((agent) => agent.id === fallbackId)) {",
    "        officeState.selectedAgentId = fallbackId;",
    "    } else {",
    "        officeState.selectedAgentId = officeState.agents[0]?.id || '';",
    "    }",
    "    officeAgentSelect.value = officeState.selectedAgentId;",
    "    officeSyncCustomizerFields();",
    "}",
    "",
    "function officeSetAgentTarget(agent, x, y, { intent = 'wander', speed = 0, preserveRoute = false } = {}) {",
    "    if (!agent) return;",
    "    if (agent.state === 'yield') {",
    "        agent.state = 'walking';",
    "        agent.yieldUntil = 0;",
    "        agent.yieldResumeIntent = '';",
    "    }",
    "    agent.targetX = officeClamp(x, 3, 97);",
    "    agent.targetY = officeClamp(y, 7, 92);",
    "    if (safeString(intent) !== 'runaway' && agent.state !== 'runaway') {",
    "        const walkableTarget = officeNearestWalkablePoint(agent.targetX, agent.targetY, agent.x, agent.y);",
    "        agent.targetX = officeClamp(walkableTarget.x, 3, 97);",
    "        agent.targetY = officeClamp(walkableTarget.y, 7, 92);",
    "    }",
    "    agent.intent = intent;",
    "    agent.state = 'walking';",
    "    if (!preserveRoute) {",
    "        agent.routeWaypoints = [];",
    "        agent.routeDestinationNodeId = '';",
    "    }",
    "    if (speed > 0) {",
    "        agent.speed = speed;",
    "    }",
    "    agent.stuckSince = 0;",
    "}",
    "",
    "function officeComputeAgentAvoidance(agent) {",
    "    if (!officeState || !agent) {",
    "        return { x: 0, y: 0 };",
    "    }",
    "    let forceX = 0;",
    "    let forceY = 0;",
    "",
    "    officeState.agents.forEach((other) => {",
    "        if (!other || other.id === agent.id || other.state === 'runaway') return;",
    "        const dx = agent.x - other.x;",
    "        const dy = agent.y - other.y;",
    "        const distance = Math.hypot(dx, dy);",
    "        if (!Number.isFinite(distance) || distance <= 0.001 || distance >= OFFICE_AGENT_AVOID_RADIUS) return;",
    "",
    "        const ratio = (OFFICE_AGENT_AVOID_RADIUS - distance) / OFFICE_AGENT_AVOID_RADIUS;",
    "        const weight = ratio * ratio;",
    "        forceX += (dx / distance) * weight;",
    "        forceY += (dy / distance) * weight;",
    "    });",
    "",
    "    const magnitude = Math.hypot(forceX, forceY);",
    "    if (!Number.isFinite(magnitude) || magnitude <= 0.0001) {",
    "        return { x: 0, y: 0 };",
    "    }",
    "    const capped = Math.min(1.4, magnitude);",
    "    return {",
    "        x: (forceX / magnitude) * capped,",
    "        y: (forceY / magnitude) * capped,",
    "    };",
    "}",
    "",
    "function officeMoveAgent(agent, dt) {",
    "    const dx = agent.targetX - agent.x;",
    "    const dy = agent.targetY - agent.y;",
    "    const distance = Math.hypot(dx, dy);",
    "    if (agent.state === 'yield') {",
    "        return distance <= 0.26;",
    "    }",
    "",
    "    const avoidance = officeComputeAgentAvoidance(agent);",
    "    const desiredX = distance > 0.001 ? (dx / distance) : 0;",
    "    const desiredY = distance > 0.001 ? (dy / distance) : 0;",
    "    const avoidanceForwardDot = (avoidance.x * desiredX) + (avoidance.y * desiredY);",
    "    const lateralAvoidX = avoidance.x - (desiredX * avoidanceForwardDot);",
    "    const lateralAvoidY = avoidance.y - (desiredY * avoidanceForwardDot);",
    "    const steerX = dx + (lateralAvoidX * 2.05) - (desiredX * Math.max(0, -avoidanceForwardDot) * 0.64);",
    "    const steerY = dy + (lateralAvoidY * 2.05) - (desiredY * Math.max(0, -avoidanceForwardDot) * 0.64);",
    "    const steerDistance = Math.hypot(steerX, steerY);",
    "    const moveX = steerDistance > 0.001 ? steerX : dx;",
    "    const moveY = steerDistance > 0.001 ? steerY : dy;",
    "    const moveDistance = Math.hypot(moveX, moveY);",
    "",
    "    if (Math.abs(moveX) > 0.1) {",
    "        agent.facing = moveX >= 0 ? 1 : -1;",
    "    }",
    "    if (distance <= 0.22) {",
    "        agent.x = agent.targetX;",
    "        agent.y = agent.targetY;",
    "        if (Array.isArray(agent.routeWaypoints) && agent.routeWaypoints.length) {",
    "            const nextStop = agent.routeWaypoints.shift();",
    "            if (nextStop) {",
    "                agent.targetX = nextStop.x;",
    "                agent.targetY = nextStop.y;",
    "                if (safeString(nextStop.nodeId)) {",
    "                    agent.currentNodeId = nextStop.nodeId;",
    "                }",
    "                return false;",
    "            }",
    "        }",
    "        if (safeString(agent.routeDestinationNodeId)) {",
    "            agent.currentNodeId = agent.routeDestinationNodeId;",
    "            agent.routeDestinationNodeId = '';",
    "        }",
    "        return true;",
    "    }",
    "    const crowdBrake = 1 - Math.min(0.34, Math.max(0, -avoidanceForwardDot) * 0.22);",
    "    const step = Math.min(distance, Math.max(1.05, agent.speed) * dt * crowdBrake);",
    "    const dirX = moveDistance > 0.001 ? (moveX / moveDistance) : (dx / Math.max(0.001, distance));",
    "    const dirY = moveDistance > 0.001 ? (moveY / moveDistance) : (dy / Math.max(0.001, distance));",
    "    const fromX = agent.x;",
    "    const fromY = agent.y;",
    "    const nextX = officeClamp(agent.x + (dirX * step), 2, 98);",
    "    const nextY = officeClamp(agent.y + (dirY * step), 6, 93);",
    "    const constrained = officeConstrainWalkableMove(agent, fromX, fromY, nextX, nextY);",
    "    agent.x = officeClamp(constrained.x, 2, 98);",
    "    agent.y = officeClamp(constrained.y, 6, 93);",
    "    return false;",
    "}",
    "",
    "function officeSafeguardAgentPosition(agent, now = performance.now(), { reroute = true } = {}) {",
    "    if (!officeState || !agent) return false;",
    "    if (agent.state === 'runaway') {",
    "        agent.x = officeClamp(agent.x, 0, 100);",
    "        agent.y = officeClamp(agent.y, 0, 100);",
    "        return false;",
    "    }",
    "",
    "    let x = officeClamp(Number(agent.x) || 0, 1, 99);",
    "    let y = officeClamp(Number(agent.y) || 0, 1, 99);",
    "    let targetX = officeClamp(Number(agent.targetX) || x, 1, 99);",
    "    let targetY = officeClamp(Number(agent.targetY) || y, 1, 99);",
    "    let snapped = false;",
    "",
    "    if (!officeIsWalkablePoint(x, y)) {",
    "        const fallbackX = Number(agent.lastMoveX) || x;",
    "        const fallbackY = Number(agent.lastMoveY) || y;",
    "        const safe = officeNearestWalkablePoint(x, y, fallbackX, fallbackY);",
    "        x = officeClamp(safe.x, 1, 99);",
    "        y = officeClamp(safe.y, 1, 99);",
    "        snapped = true;",
    "    }",
    "    if (!officeIsWalkablePoint(targetX, targetY)) {",
    "        const safeTarget = officeNearestWalkablePoint(targetX, targetY, x, y);",
    "        targetX = officeClamp(safeTarget.x, 1, 99);",
    "        targetY = officeClamp(safeTarget.y, 1, 99);",
    "        snapped = true;",
    "    }",
    "",
    "    agent.x = x;",
    "    agent.y = y;",
    "    agent.targetX = targetX;",
    "    agent.targetY = targetY;",
    "",
    "    if (!snapped) return false;",
    "",
    "    agent.currentNodeId = officeFindNearestNode(officeState.navMap, agent.x, agent.y);",
    "    if (!reroute || agent.state !== 'walking') {",
    "        return true;",
    "    }",
    "",
    "    const destinationNodeId = safeString(agent.routeDestinationNodeId);",
    "    if (destinationNodeId && officeState.navMap.has(destinationNodeId)) {",
    "        officeRouteAgentToNode(agent, destinationNodeId, {",
    "            intent: agent.intent || 'wander',",
    "            speed: Math.max(2.5, Number(agent.speed) || 0),",
    "        });",
    "        agent.collisionCooldownUntil = now + officeRandomRange(260, 620);",
    "    }",
    "    return true;",
    "}",
    "",
    "function officeHandleAgentStuck(agent, now) {",
    "    if (!officeState || !agent || agent.state !== 'walking') return;",
    "    const deltaX = Number(agent.x) - Number(agent.lastMoveX || agent.x);",
    "    const deltaY = Number(agent.y) - Number(agent.lastMoveY || agent.y);",
    "    const moved = Math.hypot(deltaX, deltaY);",
    "    const toTarget = Math.hypot((agent.targetX || agent.x) - agent.x, (agent.targetY || agent.y) - agent.y);",
    "    agent.lastMoveX = agent.x;",
    "    agent.lastMoveY = agent.y;",
    "",
    "    if (moved > 0.055 || toTarget < 0.48) {",
    "        agent.stuckSince = 0;",
    "        return;",
    "    }",
    "    if (!agent.stuckSince) {",
    "        agent.stuckSince = now;",
    "        return;",
    "    }",
    "    if ((now - agent.stuckSince) < 2100) return;",
    "",
    "    agent.stuckSince = now;",
    "    const destinationNodeId = safeString(agent.routeDestinationNodeId);",
    "    if (destinationNodeId && destinationNodeId !== safeString(agent.currentNodeId)) {",
    "        officeRouteAgentToNode(agent, destinationNodeId, {",
    "            intent: agent.intent || 'wander',",
    "            speed: Math.max(3.2, Number(agent.speed) || 0),",
    "        });",
    "        return;",
    "    }",
    "",
    "    const fallbackRoomId = agent.intent === 'break' ? 'room-break' : 'room-lobby';",
    "    officeRouteAgentToRoom(agent, fallbackRoomId, {",
    "        intent: agent.intent || 'wander',",
    "        speed: Math.max(3.2, Number(agent.speed) || 0),",
    "    });",
    "}",
    "",
    "function officeSnapAgentToNavigation(agent, { reroute = false } = {}) {",
    "    if (!officeState?.navMap || !agent || agent.state === 'runaway') return false;",
    "    const nearestNodeId = officeFindNearestNode(officeState.navMap, agent.x, agent.y);",
    "    const nearestNode = officeState.navMap.get(nearestNodeId);",
    "    if (!nearestNode) return false;",
    "",
    "    agent.x = nearestNode.x;",
    "    agent.y = nearestNode.y;",
    "    agent.targetX = nearestNode.x;",
    "    agent.targetY = nearestNode.y;",
    "    agent.currentNodeId = nearestNodeId;",
    "",
    "    if (!reroute) return true;",
    "",
    "    const destinationNodeId = safeString(agent.routeDestinationNodeId);",
    "    if (destinationNodeId && destinationNodeId !== nearestNodeId) {",
    "        officeRouteAgentToNode(agent, destinationNodeId, {",
    "            intent: agent.intent || 'wander',",
    "            speed: Math.max(2.8, Number(agent.speed) || 0),",
    "        });",
    "        return true;",
    "    }",
    "",
    "    if (agent.intent === 'task' && agent.taskId) {",
    "        const task = officeState.tasks.find((entry) => entry.id === agent.taskId);",
    "        if (task) {",
    "            officeRouteAgentToRoom(agent, task.roomId, {",
    "                intent: 'task',",
    "                speed: Math.max(3.2, Number(agent.speed) || 0),",
    "            });",
    "        }",
    "    }",
    "    return true;",
    "}",
    "",
    "function officeTaskPriorityScore(task) {",
    "    if (!task) return 0;",
    "    const now = Date.now();",
    "    const ageMs = Math.max(0, now - (Number(task.createdAt) || now));",
    "    const ageScore = Math.min(3.6, ageMs / 22_000);",
    "    const urgencyFromWords = /\\b(urgent|asap|priority|critical|now)\\b/i.test(safeString(task.rawText))",
    "        ? 2.2",
    "        : 0;",
    "    const roomBoost = safeString(task.roomId) === 'room-support' ? 0.5 : 0;",
    "    return ageScore + urgencyFromWords + roomBoost;",
    "}",
    "",
    "function officeAgentTaskFitScore(agent, task) {",
    "    if (!agent || !task) return 0;",
    "    const roomId = safeString(task.roomId);",
    "    const tint = officePersonaBucket(agent);",
    "    const tintRoomAffinity = {",
    "        blue: new Set(['room-engineering', 'room-ops', 'room-lobby']),",
    "        green: new Set(['room-research', 'room-support']),",
    "        orange: new Set(['room-content', 'room-engineering']),",
    "        pink: new Set(['room-design', 'room-content']),",
    "        purple: new Set(['room-planning', 'room-pods', 'room-research']),",
    "        yellow: new Set(['room-support', 'room-lobby']),",
    "    };",
    "    const affinityBoost = tintRoomAffinity[tint]?.has(roomId) ? 1.8 : 0;",
    "    const distancePenalty = Math.min(3.2, Math.hypot((agent.x || 50) - 50, (agent.y || 50) - 50) / 22);",
    "    const routeBoost = Array.isArray(agent.routeWaypoints) && agent.routeWaypoints.length ? -0.6 : 0;",
    "    const idleBoost = agent.state === 'idle' ? 0.8 : 0;",
    "    return affinityBoost + idleBoost + routeBoost - distancePenalty;",
    "}",
    "",
    "function officeAssignTaskToAgent(task, agent, now) {",
    "    if (!task || !agent || task.status !== 'queued') return false;",
    "    task.status = 'active';",
    "    task.assignedAgentId = agent.id;",
    "    task.startedAt = Date.now();",
    "    agent.taskId = task.id;",
    "    const routed = officeRouteAgentToRoom(agent, task.roomId, {",
    "        intent: 'task',",
    "        speed: officeRandomRange(3.2, 4.3),",
    "    });",
    "    if (!routed) return false;",
    "    const roomTheme = officeRoomById(task.roomId)?.theme || '';",
    "    const pickupLine = officeBanterForAgent(agent, 'task_pickup', {",
    "        roomTheme,",
    "        taskTitle: task.title,",
    "    }) || officePick(OFFICE_DIALOGUE.pickup).replace('{room}', task.roomLabel);",
    "    officeSpeak(agent, pickupLine, { priority: true, durationMs: 1400 });",
    "    officeBusEmit('task.assigned', {",
    "        taskId: task.id,",
    "        roomId: task.roomId,",
    "        roomLabel: task.roomLabel,",
    "        agentId: agent.id,",
    "        agentName: agent.name,",
    "        score: Number((officeTaskPriorityScore(task) + officeAgentTaskFitScore(agent, task)).toFixed(3)),",
    "    }, now);",
    "    officeState.tasksDirty = true;",
    "    return true;",
    "}",
    "",
    "function officeAssignQueuedTasks(now = performance.now()) {",
    "    if (!officeState) return;",
    "    const queued = officeState.tasks",
    "        .filter((task) => task.status === 'queued')",
    "        .sort((a, b) => officeTaskPriorityScore(b) - officeTaskPriorityScore(a));",
    "    if (!queued.length) return;",
    "",
    "    const availableAgents = officeState.agents.filter((agent) => (",
    "        !agent.taskId",
    "        && (agent.state === 'idle' || (agent.state === 'walking' && agent.intent === 'wander'))",
    "    ));",
    "    if (!availableAgents.length) return;",
    "",
    "    const openTasks = [...queued];",
    "    availableAgents.forEach((agent) => {",
    "        let bestIndex = -1;",
    "        let bestScore = Number.NEGATIVE_INFINITY;",
    "        openTasks.forEach((task, index) => {",
    "            const score = officeTaskPriorityScore(task) + officeAgentTaskFitScore(agent, task);",
    "            if (score > bestScore) {",
    "                bestScore = score;",
    "                bestIndex = index;",
    "            }",
    "        });",
    "        if (bestIndex < 0) return;",
    "        const [nextTask] = openTasks.splice(bestIndex, 1);",
    "        if (!nextTask) return;",
    "        officeAssignTaskToAgent(nextTask, agent, now);",
    "    });",
    "}",
    "",
    "function officeFinishTask(agent, now) {",
    "    if (!officeState || !agent?.taskId) return;",
    "    const task = officeState.tasks.find((entry) => entry.id === agent.taskId);",
    "    if (task) {",
    "        task.status = 'done';",
    "        task.completedAt = Date.now();",
    "        officeState.tasksDirty = true;",
    "    }",
    "    agent.taskId = '';",
    "    agent.workUntil = 0;",
    "    if (officeChance(0.38)) {",
    "        const targetRoom = officeChance(0.5) ? 'room-coffee' : 'room-break';",
    "        officeRouteAgentToRoom(agent, targetRoom, {",
    "            intent: 'break',",
    "            speed: officeRandomRange(2.8, 3.8),",
    "        });",
    "        officeSpeak(agent, officeBanterForAgent(agent, 'break', { roomTheme: targetRoom }), { durationMs: 1700 });",
    "        agent.nextBreakAt = now + officeRandomRange(26_000, 62_000);",
    "    } else {",
    "        agent.state = 'idle';",
    "        agent.intent = 'wander';",
    "        agent.idleUntil = now + officeRandomRange(800, 1900);",
    "        officeSpeak(agent, officeBanterForAgent(agent, 'task_done', { taskTitle: task?.title || '' }), { durationMs: 1500 });",
    "    }",
    "    officeBusEmit('task.completed', {",
    "        taskId: task?.id || '',",
    "        roomId: task?.roomId || '',",
    "        roomLabel: task?.roomLabel || '',",
    "        agentId: agent.id,",
    "        agentName: agent.name,",
    "    }, now);",
    "}",
    "",
    "function officeTrimTasks() {",
    "    if (!officeState) return;",
    "    let changed = false;",
    "    const completionCutoff = Date.now() - (3 * 60 * 1000);",
    "    const before = officeState.tasks.length;",
    "    officeState.tasks = officeState.tasks.filter((task) => (",
    "        task.status !== 'done' || task.completedAt >= completionCutoff",
    "    ));",
    "    if (officeState.tasks.length !== before) {",
    "        changed = true;",
    "    }",
    "    while (officeState.tasks.length > OFFICE_MAX_TASKS) {",
    "        const doneIndex = officeState.tasks.findIndex((task) => task.status === 'done');",
    "        if (doneIndex >= 0) {",
    "            officeState.tasks.splice(doneIndex, 1);",
    "        } else {",
    "            officeState.tasks.shift();",
    "        }",
    "        changed = true;",
    "    }",
    "    if (changed) {",
    "        officeState.tasksDirty = true;",
    "    }",
    "}",
    "",
    "function officeTickBreakSchedules(now) {",
    "    if (!officeState) return;",
    "    officeState.agents.forEach((agent) => {",
    "        if (!agent || agent.state === 'runaway') return;",
    "        if (agent.taskId) return;",
    "        const nextBreakAt = Number(agent.nextBreakAt) || 0;",
    "        if (nextBreakAt <= 0 || now < nextBreakAt) return;",
    "        if (!(agent.state === 'idle' || (agent.state === 'walking' && agent.intent === 'wander'))) return;",
    "        const breakRoomId = officeChance(0.56) ? 'room-coffee' : 'room-break';",
    "        const routed = officeRouteAgentToRoom(agent, breakRoomId, {",
    "            intent: 'break',",
    "            speed: officeRandomRange(2.8, 3.8),",
    "        });",
    "        agent.nextBreakAt = now + officeRandomRange(42_000, 94_000);",
    "        if (!routed) return;",
    "        const line = officeBanterForAgent(agent, 'break', {",
    "            roomTheme: officeRoomById(breakRoomId)?.theme || '',",
    "        });",
    "        officeSpeak(agent, line, { priority: true, durationMs: 1320 });",
    "        officeBusEmit('agent.break_cycle', {",
    "            agentId: agent.id,",
    "            agentName: agent.name,",
    "            roomId: breakRoomId,",
    "        }, now);",
    "    });",
    "}",
    "",
    "function officeTickSocialIdle(now) {",
    "    if (!officeState) return;",
    "    if ((now - (officeState.lastSocialTickAt || 0)) < 360) return;",
    "    officeState.lastSocialTickAt = now;",
    "    if (now < (officeState.nextSocialWindowAt || 0)) return;",
    "",
    "    const candidates = officeState.agents.filter((agent) => (",
    "        agent",
    "        && !agent.taskId",
    "        && !agent.speech",
    "        && (agent.state === 'idle' || (agent.state === 'walking' && agent.intent === 'wander'))",
    "        && now >= (Number(agent.nextSocialAt) || 0)",
    "    ));",
    "    if (candidates.length < 2) return;",
    "",
    "    let bestPair = null;",
    "    let bestDistance = Number.POSITIVE_INFINITY;",
    "    for (let i = 0; i < candidates.length; i += 1) {",
    "        const a = candidates[i];",
    "        const roomA = officeCurrentRoomForAgent(a);",
    "        if (!roomA) continue;",
    "        for (let j = i + 1; j < candidates.length; j += 1) {",
    "            const b = candidates[j];",
    "            const roomB = officeCurrentRoomForAgent(b);",
    "            if (!roomB || roomA.id !== roomB.id) continue;",
    "            const distance = Math.hypot(a.x - b.x, a.y - b.y);",
    "            if (distance > 12.2) continue;",
    "            if (distance < bestDistance) {",
    "                bestDistance = distance;",
    "                bestPair = { a, b, room: roomA };",
    "            }",
    "        }",
    "    }",
    "    if (!bestPair) return;",
    "",
    "    const lead = officeChance(0.5) ? bestPair.a : bestPair.b;",
    "    const reply = lead.id === bestPair.a.id ? bestPair.b : bestPair.a;",
    "    const leadLine = officeBanterForAgent(lead, 'social_lead', { roomTheme: bestPair.room.theme });",
    "    const replyLine = officeBanterForAgent(reply, 'social_reply', { roomTheme: bestPair.room.theme });",
    "",
    "    let spoke = false;",
    "    if (officeSpeak(lead, leadLine, { priority: true, durationMs: 1320 })) {",
    "        spoke = true;",
    "    }",
    "    if (officeChance(0.86)) {",
    "        window.setTimeout(() => {",
    "            if (!officeState) return;",
    "            officeSpeak(reply, replyLine, { priority: true, durationMs: 1180 });",
    "        }, officeRandomRange(320, 620));",
    "    }",
    "",
    "    [lead, reply].forEach((agent) => {",
    "        agent.nextSocialAt = now + officeRandomRange(15_000, 32_000);",
    "    });",
    "    officeState.nextSocialWindowAt = now + officeRandomRange(5_000, 12_000);",
    "",
    "    if (spoke) {",
    "        officeBusEmit('agent.social', {",
    "            roomId: bestPair.room.id,",
    "            roomTheme: bestPair.room.theme,",
    "            speakerId: lead.id,",
    "            responderId: reply.id,",
    "        }, now);",
    "    }",
    "}",
    "",
    "function officeRenderDebugOverlay(now = performance.now()) {",
    "    if (!officeState || !officeDebugOverlay) return;",
    "    if (!officeState.debugOverlayOpen) {",
    "        officeDebugOverlay.classList.add('hidden');",
    "        return;",
    "    }",
    "    if ((now - (officeState.lastDebugRenderAt || 0)) < OFFICE_DEBUG_REFRESH_MS) return;",
    "    officeState.lastDebugRenderAt = now;",
    "    officeDebugOverlay.classList.remove('hidden');",
    "",
    "    const activeTasks = officeState.tasks.filter((task) => task.status === 'active').length;",
    "    const queuedTasks = officeState.tasks.filter((task) => task.status === 'queued').length;",
    "    const walking = officeState.agents.filter((agent) => agent.state === 'walking').length;",
    "    const working = officeState.agents.filter((agent) => agent.state === 'working').length;",
    "    const collisions = officeState.agents.filter((agent) => now < (agent.bumpUntil || 0)).length;",
    "    const fps = Number(officeState.debugFrameRate || 0).toFixed(1);",
    "    const stream = officeState.stream || {};",
    "    const streamStatus = stream.connected ? 'live' : (stream.connecting ? 'connecting' : 'retry');",
    "    const streamSeq = Number(stream.lastSeq) || 0;",
    "    const events = officeState.officeEvents.slice(-3).reverse();",
    "    const eventLines = events.map((event) => {",
    "        const stamp = new Date(event.ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });",
    "        return `<li>[${stamp}] ${escapeHtml(event.type)}</li>`;",
    "    }).join('');",
    "",
    "    officeDebugOverlay.innerHTML = `",
    "        <div class=\"office-debug-head\">Office Debug</div>",
    "        <div class=\"office-debug-grid\">",
    "            <span>FPS <strong>${fps}</strong></span>",
    "            <span>Agents <strong>${officeState.agents.length}</strong></span>",
    "            <span>Walking <strong>${walking}</strong></span>",
    "            <span>Working <strong>${working}</strong></span>",
    "            <span>Queued <strong>${queuedTasks}</strong></span>",
    "            <span>Active <strong>${activeTasks}</strong></span>",
    "            <span>Lane Claims <strong>${officeState.laneReservations.size}</strong></span>",
    "            <span>Bumps <strong>${collisions}</strong></span>",
    "            <span>Stream <strong>${streamStatus}</strong></span>",
    "            <span>Seq <strong>${streamSeq}</strong></span>",
    "        </div>",
    "        <ul class=\"office-debug-events\">${eventLines || '<li>No recent events</li>'}</ul>",
    "    `;",
    "}",
    "",
    "function officeMissionStatusToOfficeState(statusRaw) {",
    "    const status = safeString(statusRaw).toLowerCase();",
    "    if (status === 'active' || status === 'running' || status === 'in_progress') return 'working';",
    "    if (status === 'idle' || status === 'waiting') return 'idle';",
    "    if (status === 'blocked' || status === 'paused') return 'yield';",
    "    if (status === 'break') return 'break';",
    "    return '';",
    "}",
    "",
    "function officeReconcileFromMissionPayload(payload, now = performance.now()) {",
    "    if (!officeState || !payload || typeof payload !== 'object') return false;",
    "    let changed = false;",
    "",
    "    const rooms = Array.isArray(payload.rooms) ? payload.rooms : [];",
    "    rooms.forEach((entry) => {",
    "        const id = safeString(entry?.id);",
    "        if (!id) return;",
    "        const room = officeRoomById(id);",
    "        if (!room) return;",
    "        const nextLabel = safeString(entry?.label);",
    "        if (nextLabel && room.label !== nextLabel) {",
    "            room.label = nextLabel;",
    "            changed = true;",
    "        }",
    "    });",
    "",
    "    const tasks = Array.isArray(payload.tasks) ? payload.tasks : [];",
    "    tasks.forEach((entry) => {",
    "        const id = safeString(entry?.id);",
    "        if (!id) return;",
    "        const existing = officeState.tasks.find((task) => task.id === id);",
    "        if (existing) {",
    "            const nextStatus = safeString(entry?.status).toLowerCase();",
    "            if (nextStatus && nextStatus !== existing.status) {",
    "                existing.status = nextStatus;",
    "                changed = true;",
    "            }",
    "            const assignedAgentId = safeString(entry?.assigned_agent_id || entry?.assignedAgentId);",
    "            if (assignedAgentId && existing.assignedAgentId !== assignedAgentId) {",
    "                existing.assignedAgentId = assignedAgentId;",
    "                changed = true;",
    "            }",
    "            return;",
    "        }",
    "        const label = safeString(entry?.title || entry?.name || id);",
    "        const roomId = safeString(entry?.room || entry?.room_id || 'room-lobby');",
    "        const room = officeRoomById(roomId) || officeRoomById('room-lobby');",
    "        officeState.tasks.push({",
    "            id,",
    "            title: officeTaskTitle(label),",
    "            rawText: label,",
    "            source: 'mission-stream',",
    "            roomId: room?.id || 'room-lobby',",
    "            roomLabel: room?.label || 'Main Lobby',",
    "            status: safeString(entry?.status).toLowerCase() || 'queued',",
    "            assignedAgentId: safeString(entry?.assigned_agent_id || entry?.assignedAgentId),",
    "            createdAt: Date.now(),",
    "            startedAt: 0,",
    "            completedAt: 0,",
    "        });",
    "        changed = true;",
    "    });",
    "",
    "    const agents = Array.isArray(payload.agents) ? payload.agents : [];",
    "    agents.forEach((entry) => {",
    "        const remoteId = safeString(entry?.id);",
    "        const remoteName = safeString(entry?.name);",
    "        const local = officeState.agents.find((agent) => (",
    "            (remoteId && agent.id === remoteId)",
    "            || (remoteName && officeAgentHandle(agent.name) === officeAgentHandle(remoteName))",
    "        ));",
    "        if (!local) return;",
    "        const mappedState = officeMissionStatusToOfficeState(entry?.status);",
    "        if (!mappedState) return;",
    "        local.remoteStatus = mappedState;",
    "        if (local.taskId) return;",
    "        if (mappedState === 'working' && local.state === 'idle') {",
    "            local.state = 'working';",
    "            local.workUntil = now + officeRandomRange(2800, 6400);",
    "            local.nextWorkLineAt = now + officeRandomRange(1400, 2600);",
    "            changed = true;",
    "        } else if (mappedState === 'break' && local.state === 'idle') {",
    "            local.state = 'break';",
    "            local.breakUntil = now + officeRandomRange(1900, 4600);",
    "            local.nextWorkLineAt = now + officeRandomRange(900, 1800);",
    "            changed = true;",
    "        } else if (mappedState === 'yield' && local.state === 'walking') {",
    "            officeSetYieldState(local, now, officeRandomRange(-0.8, 0.8), officeRandomRange(-0.8, 0.8));",
    "            changed = true;",
    "        }",
    "    });",
    "",
    "    if (changed) {",
    "        officeTrimTasks();",
    "        officeState.tasksDirty = true;",
    "    }",
    "    return changed;",
    "}",
    "",
    "function officeHandleMissionStreamLine(lineRaw) {",
    "    if (!officeState) return;",
    "    const line = safeString(lineRaw);",
    "    if (!line) return;",
    "    let parsed = null;",
    "    try {",
    "        parsed = JSON.parse(line);",
    "    } catch {",
    "        return;",
    "    }",
    "    if (!parsed || typeof parsed !== 'object') return;",
    "    const type = safeString(parsed.type).toLowerCase() || 'snapshot';",
    "    const seq = Number(parsed.seq) || 0;",
    "    if (type === 'snapshot' && parsed.payload && typeof parsed.payload === 'object') {",
    "        const changed = officeReconcileFromMissionPayload(parsed.payload);",
    "        officeState.stream.lastSeq = seq || officeState.stream.lastSeq;",
    "        officeBusEmit('stream.snapshot', {",
    "            seq,",
    "            changed,",
    "        });",
    "        return;",
    "    }",
    "    officeBusEmit('stream.event', {",
    "        type,",
    "        seq,",
    "    });",
    "}",
    "",
    "function officeScheduleMissionStreamReconnect(delayMs = 0) {",
    "    if (!officeState?.stream || !officeState.active) return;",
    "    const stream = officeState.stream;",
    "    if (stream.reconnectTimer) return;",
    "    const retryMs = delayMs > 0",
    "        ? delayMs",
    "        : officeClamp(Number(stream.retryMs) || OFFICE_STREAM_RETRY_MIN_MS, OFFICE_STREAM_RETRY_MIN_MS, OFFICE_STREAM_RETRY_MAX_MS);",
    "    stream.retryMs = Math.min(OFFICE_STREAM_RETRY_MAX_MS, Math.round(retryMs * 1.75));",
    "    stream.reconnectTimer = window.setTimeout(() => {",
    "        if (!officeState?.stream) return;",
    "        officeState.stream.reconnectTimer = 0;",
    "        void officeStartMissionStream();",
    "    }, retryMs);",
    "}",
    "",
    "function officeStopMissionStream() {",
    "    if (!officeState?.stream) return;",
    "    const stream = officeState.stream;",
    "    if (stream.reconnectTimer) {",
    "        window.clearTimeout(stream.reconnectTimer);",
    "        stream.reconnectTimer = 0;",
    "    }",
    "    if (stream.controller) {",
    "        try {",
    "            stream.controller.abort();",
    "        } catch {",
    "            // Ignore abort failures.",
    "        }",
    "    }",
    "    stream.connected = false;",
    "    stream.connecting = false;",
    "    stream.controller = null;",
    "}",
    "",
    "async function officeStartMissionStream() {",
    "    if (!officeState?.stream || !officeState.active) return;",
    "    const stream = officeState.stream;",
    "    if (stream.connecting || stream.connected) return;",
    "    if (typeof fetch !== 'function' || typeof TextDecoder === 'undefined') return;",
    "",
    "    stream.connecting = true;",
    "    const controller = new AbortController();",
    "    stream.controller = controller;",
    "    const url = '/api/mission/stream?interval=1.8';",
    "",
    "    try {",
    "        const response = await fetch(url, {",
    "            method: 'GET',",
    "            headers: {",
    "                Accept: 'application/x-ndjson',",
    "            },",
    "            signal: controller.signal,",
    "            cache: 'no-store',",
    "        });",
    "        if (!response.ok || !response.body) {",
    "            throw new Error(`mission_stream_http_${response.status}`);",
    "        }",
    "",
    "        stream.connected = true;",
    "        stream.connecting = false;",
    "        stream.retryMs = OFFICE_STREAM_RETRY_MIN_MS;",
    "        stream.lastMessageAt = Date.now();",
    "        officeBusEmit('stream.connected', { url });",
    "",
    "        const reader = response.body.getReader();",
    "        const decoder = new TextDecoder();",
    "        let buffer = '';",
    "",
    "        while (officeState && officeState.active && !controller.signal.aborted) {",
    "            const { done, value } = await reader.read();",
    "            if (done) break;",
    "            stream.lastMessageAt = Date.now();",
    "            buffer += decoder.decode(value, { stream: true });",
    "            let newlineIndex = buffer.indexOf('\\n');",
    "            while (newlineIndex >= 0) {",
    "                const line = buffer.slice(0, newlineIndex).trim();",
    "                buffer = buffer.slice(newlineIndex + 1);",
    "                if (line) {",
    "                    officeHandleMissionStreamLine(line);",
    "                }",
    "                newlineIndex = buffer.indexOf('\\n');",
    "            }",
    "        }",
    "    } catch (error) {",
    "        if (!controller.signal.aborted) {",
    "            officeBusEmit('stream.error', {",
    "                reason: safeString(error?.message || error),",
    "            });",
    "        }",
    "    } finally {",
    "        if (!officeState?.stream) return;",
    "        stream.connected = false;",
    "        stream.connecting = false;",
    "        stream.controller = null;",
    "        if (officeState.active) {",
    "            officeScheduleMissionStreamReconnect();",
    "        }",
    "    }",
    "}",
    "",
    "function officeTickAgent(agent, now, dt) {",
    "    if (!agent) return;",
    "    if (agent.state !== 'runaway') {",
    "        officeSafeguardAgentPosition(agent, now, { reroute: false });",
    "    }",
    "    if (agent.state === 'runaway') {",
    "        const arrived = officeMoveAgent(agent, dt);",
    "        if (arrived && safeString(agent.runawayPhase) === 'to-hall') {",
    "            agent.runawayPhase = 'exiting';",
    "            officeSetAgentTarget(agent, agent.runawayExitX, agent.runawayExitY, {",
    "                intent: 'runaway',",
    "                speed: officeRandomRange(5.8, 7.2),",
    "            });"
].join("\n");
