/* split from part-011.js */
export default [
    "    let vertical = 'above';",
    "    if ((screen.y - 96) <= margin) {",
    "        vertical = 'below';",
    "    } else if ((screen.y + 96) >= (screen.height - margin)) {",
    "        vertical = 'above';",
    "    } else {",
    "        vertical = officeBubbleVerticalForY(agent?.y || 50);",
    "    }",
    "",
    "    return { horizontal, vertical };",
    "}",
    "",
    "function officeVisibleSpeech(agent, now) {",
    "    if (!agent?.speech) return '';",
    "    if (now >= agent.speech.endAt) {",
    "        agent.speech = null;",
    "        return '';",
    "    }",
    "    const text = safeString(agent.speech.text);",
    "    if (!text) return '';",
    "    const elapsed = now - agent.speech.startAt;",
    "    const revealMs = Math.max(1, Number(agent.speech.revealMs) || 1);",
    "    const ratio = officeClamp(elapsed / revealMs, 0, 1);",
    "    const chars = Math.max(1, Math.round(text.length * ratio));",
    "    return text.slice(0, chars);",
    "}",
    "",
    "function officeSpeak(agent, text, { priority = false, durationMs = 0 } = {}) {",
    "    if (!officeState || !agent) return false;",
    "    const clean = safeString(text);",
    "    if (!clean) return false;",
    "    const now = performance.now();",
    "    if (!priority && now < officeState.nextGlobalSpeechAt) {",
    "        return false;",
    "    }",
    "",
    "    const revealMs = officeSpeechRevealMsForText(clean);",
    "    const holdMs = durationMs > 0",
    "        ? officeClamp(durationMs, 700, 4800)",
    "        : officeClamp(clean.length * 46, 1100, 3600);",
    "",
    "    agent.speech = {",
    "        text: clean,",
    "        startAt: now,",
    "        revealMs,",
    "        endAt: now + revealMs + holdMs,",
    "    };",
    "    agent.nextAmbientAt = now + officeRandomRange(6800, 13000);",
    "    officeState.nextGlobalSpeechAt = now + officeRandomRange(850, 1800);",
    "    officeBusEmit('agent.speak', {",
    "        agentId: agent.id,",
    "        state: agent.state,",
    "        intent: agent.intent,",
    "        text: clean.slice(0, 120),",
    "    }, now);",
    "    return true;",
    "}",
    "",
    "function officePushChatLine(text, tone = 'system') {",
    "    if (!officeState || !officeChatLog) return;",
    "    const message = safeString(text);",
    "    if (!message) return;",
    "    officeState.chatLines.push({",
    "        message,",
    "        tone: safeString(tone) || 'system',",
    "        at: Date.now(),",
    "    });",
    "    if (officeState.chatLines.length > OFFICE_MAX_CHAT_LINES) {",
    "        officeState.chatLines = officeState.chatLines.slice(officeState.chatLines.length - OFFICE_MAX_CHAT_LINES);",
    "    }",
    "",
    "    officeChatLog.innerHTML = '';",
    "    const frag = document.createDocumentFragment();",
    "    officeState.chatLines.forEach((line) => {",
    "        const row = document.createElement('div');",
    "        const epoch = Number(line?.at);",
    "        const stamp = Number.isFinite(epoch) && epoch > 0",
    "            ? new Date(epoch).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })",
    "            : '--:--';",
    "        row.textContent = `[${stamp}] ${safeString(line?.message)}`;",
    "        row.dataset.tone = line.tone;",
    "        frag.appendChild(row);",
    "    });",
    "    officeChatLog.appendChild(frag);",
    "    officeChatLog.scrollTop = officeChatLog.scrollHeight;",
    "}",
    "",
    "function officeBusEmit(typeRaw, payload = {}, now = performance.now()) {",
    "    if (!officeState) return null;",
    "    const type = safeString(typeRaw).toLowerCase();",
    "    if (!type) return null;",
    "    const event = {",
    "        id: `oe-${Math.round(now)}-${Math.floor(officeRandomRange(100, 999))}`,",
    "        schema: OFFICE_EVENT_SCHEMA_VERSION,",
    "        type,",
    "        ts: Date.now(),",
    "        now,",
    "        payload: payload && typeof payload === 'object' ? payload : {},",
    "    };",
    "    officeState.officeEvents.push(event);",
    "    if (officeState.officeEvents.length > OFFICE_EVENT_LOG_LIMIT) {",
    "        officeState.officeEvents = officeState.officeEvents.slice(",
    "            officeState.officeEvents.length - OFFICE_EVENT_LOG_LIMIT,",
    "        );",
    "    }",
    "    officeState.officeBusListeners.forEach((listener) => {",
    "        try {",
    "            listener(event);",
    "        } catch {",
    "            // Listener failures should not break simulation loop.",
    "        }",
    "    });",
    "    return event;",
    "}",
    "",
    "function officeBusSubscribe(listener) {",
    "    if (!officeState || typeof listener !== 'function') {",
    "        return () => {};",
    "    }",
    "    officeState.officeBusListeners.add(listener);",
    "    return () => {",
    "        if (!officeState) return;",
    "        officeState.officeBusListeners.delete(listener);",
    "    };",
    "}",
    "",
    "function officeViewportMetrics() {",
    "    if (!officeSceneWrap || !officeScenePanzoom) return null;",
    "    const wrapRect = officeSceneWrap.getBoundingClientRect();",
    "    return {",
    "        wrapRect,",
    "        wrapWidth: Math.max(1, wrapRect.width),",
    "        wrapHeight: Math.max(1, wrapRect.height),",
    "        mapWidth: Math.max(1, officeState?.mapWidth || officeScenePanzoom.offsetWidth || OFFICE_MAP_WIDTH),",
    "        mapHeight: Math.max(1, officeState?.mapHeight || officeScenePanzoom.offsetHeight || OFFICE_MAP_HEIGHT),",
    "    };",
    "}",
    "",
    "function officeClampPan(panX, panY, zoom, metrics = null) {",
    "    const view = metrics || officeViewportMetrics();",
    "    if (!view) return { panX, panY };",
    "",
    "    const renderZoom = officeEffectiveZoom(zoom);",
    "    const scaledW = view.mapWidth * renderZoom;",
    "    const scaledH = view.mapHeight * renderZoom;",
    "",
    "    let minX;",
    "    let maxX;",
    "    if (scaledW <= view.wrapWidth) {",
    "        minX = (view.wrapWidth - scaledW) / 2;",
    "        maxX = minX;",
    "    } else {",
    "        minX = view.wrapWidth - scaledW - OFFICE_VIEWPORT_MARGIN;",
    "        maxX = OFFICE_VIEWPORT_MARGIN;",
    "    }",
    "",
    "    let minY;",
    "    let maxY;",
    "    if (scaledH <= view.wrapHeight) {",
    "        minY = (view.wrapHeight - scaledH) / 2;",
    "        maxY = minY;",
    "    } else {",
    "        minY = view.wrapHeight - scaledH - OFFICE_VIEWPORT_MARGIN;",
    "        maxY = OFFICE_VIEWPORT_MARGIN;",
    "    }",
    "",
    "    return {",
    "        panX: officeClamp(panX, minX, maxX),",
    "        panY: officeClamp(panY, minY, maxY),",
    "    };",
    "}",
    "",
    "function officeDynamicMinZoom(metrics = null) {",
    "    return OFFICE_ZOOM_MIN;",
    "}",
    "",
    "function officeEffectiveZoom(rawZoom) {",
    "    const numeric = officeClamp(",
    "        Number.isFinite(rawZoom) ? rawZoom : 1,",
    "        OFFICE_ZOOM_MIN,",
    "        OFFICE_ZOOM_MAX,",
    "    );",
    "    if (numeric <= OFFICE_ZOOM_RENDER_FLOOR) {",
    "        return OFFICE_ZOOM_RENDER_FLOOR;",
    "    }",
    "    if (numeric < 0.3) {",
    "        const t = officeClamp(",
    "            (numeric - OFFICE_ZOOM_RENDER_FLOOR) / (0.3 - OFFICE_ZOOM_RENDER_FLOOR),",
    "            0,",
    "            1,",
    "        );",
    "        return OFFICE_ZOOM_RENDER_FLOOR + (t * t * (0.3 - OFFICE_ZOOM_RENDER_FLOOR));",
    "    }",
    "    return numeric;",
    "}",
    "",
    "function officeApplyZoom() {",
    "    if (!officeState || !officeScenePanzoom) return;",
    "    officeScenePanzoom.style.width = `${officeState.mapWidth}px`;",
    "    officeScenePanzoom.style.height = `${officeState.mapHeight}px`;",
    "    const metrics = officeViewportMetrics();",
    "    const minZoom = officeDynamicMinZoom(metrics);",
    "    officeState.zoomLevel = officeClamp(officeState.zoomLevel, minZoom, OFFICE_ZOOM_MAX);",
    "    const clampedPan = officeClampPan(officeState.panX, officeState.panY, officeState.zoomLevel);",
    "    officeState.panX = clampedPan.panX;",
    "    officeState.panY = clampedPan.panY;",
    "    const renderZoom = officeEffectiveZoom(officeState.zoomLevel);",
    "    officeScenePanzoom.style.setProperty('--office-zoom', String(renderZoom));",
    "    officeScenePanzoom.style.setProperty('--office-pan-x', `${officeState.panX.toFixed(2)}px`);",
    "    officeScenePanzoom.style.setProperty('--office-pan-y', `${officeState.panY.toFixed(2)}px`);",
    "    if (officeSceneWrap) {",
    "        officeSceneWrap.style.setProperty('--office-pan-x', `${officeState.panX.toFixed(2)}px`);",
    "        officeSceneWrap.style.setProperty('--office-pan-y', `${officeState.panY.toFixed(2)}px`);",
    "    }",
    "    if (officeZoomResetBtn) {",
    "        officeZoomResetBtn.textContent = `${Math.round(Math.max(0, officeState.zoomLevel) * 100)}%`;",
    "    }",
    "    officeRenderMinimap();",
    "}",
    "",
    "function officePersistCameraState(now = performance.now()) {",
    "    if (!officeState) return;",
    "    if ((now - (officeState.lastCameraPersistAt || 0)) < 260) return;",
    "    const snapshot = {",
    "        zoom: Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel,",
    "        panX: Number.isFinite(officeState.targetPanX) ? officeState.targetPanX : officeState.panX,",
    "        panY: Number.isFinite(officeState.targetPanY) ? officeState.targetPanY : officeState.panY,",
    "        followAgentId: safeString(officeState.followAgentId),",
    "    };",
    "    const signature = [",
    "        Number(snapshot.zoom || 0).toFixed(4),",
    "        Number(snapshot.panX || 0).toFixed(2),",
    "        Number(snapshot.panY || 0).toFixed(2),",
    "        safeString(snapshot.followAgentId),",
    "    ].join('|');",
    "    if (signature === safeString(officeState.lastCameraPersistSignature)) {",
    "        return;",
    "    }",
    "    officeState.lastCameraPersistAt = now;",
    "    officeState.lastCameraPersistSignature = signature;"
].join("\n");
