/* app.js lines 30001-31000 */
export default [
    "            void refreshTaskContinuity({ force: true });",
    "        });",
    "    }",
    "    updateTaskContinuityVisibility({ refresh: true });",
    "    initDebugDockTabs();",
    "    renderDebugEventLog();",
    "    renderDebugConsoleLog();",
    "    renderDebugNetworkLog();",
    "    renderDebugLivePanels();",
    "    updateDebugNetworkSummary();",
    "    startDebugConsoleCapture();",
    "    startDebugNetworkCapture();",
    "    syncLayoutOffsets();",
    "    if (mainContent) {",
    "        mainContent.addEventListener('scroll', normalizeMainContentScroll, { passive: true });",
    "    }",
    "    normalizeMainContentScroll();",
    "    window.addEventListener('resize', syncLayoutOffsets);",
    "",
    "    const toggleSidebarCollapsed = () => {",
    "        if (!sidebar || isSidebarAnimating()) return;",
    "        startSidebarAnimationLock();",
    "        sidebar.classList.toggle('collapsed');",
    "        saveStoredSidebarCollapsed(Boolean(sidebar.classList.contains('collapsed')));",
    "        syncLayoutOffsets();",
    "        pushDebugEvent('layout', sidebar.classList.contains('collapsed') ? 'Collapsed sidebar' : 'Expanded sidebar');",
    "    };",
    "",
    "    if (sidebarToggleBtn) {",
    "        sidebarToggleBtn.addEventListener('click', toggleSidebarCollapsed);",
    "    }",
    "    if (sidebarCollapseBtn) {",
    "        sidebarCollapseBtn.addEventListener('click', toggleSidebarCollapsed);",
    "    }",
    "",
    "    if (newChatSidebar) {",
    "        newChatSidebar.addEventListener('click', (event) => {",
    "            const wantsNewChat = Boolean(event && (event.shiftKey || event.metaKey || event.ctrlKey));",
    "            if (wantsNewChat) {",
    "                ensureSettingsUiClosed();",
    "                createNewSessionAndRefresh();",
    "                if (globalSearchInput) globalSearchInput.value = '';",
    "                setSidebarNavMode('chat');",
    "                setSidebarSearchScope('chat');",
    "                return;",
    "            }",
    "            void promptRenameAgentIdentity();",
    "        });",
    "    }",
    "",
    "    if (navChatBtn) {",
    "        navChatBtn.addEventListener('click', (event) => {",
    "            const isCaretClick = Boolean(event.target instanceof Element && event.target.closest('.nav-chat-caret'));",
    "            if (isCaretClick) {",
    "                event.preventDefault();",
    "                event.stopPropagation();",
    "                if (sidebarNavMode !== 'chat') {",
    "                    ensureSettingsUiClosed();",
    "                    setSidebarNavMode('chat');",
    "                    setSidebarSearchScope('chat');",
    "                }",
    "                setChatListExpanded(!chatListExpanded);",
    "                return;",
    "            }",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('chat');",
    "            setSidebarSearchScope('chat');",
    "            if (globalSearchInput) globalSearchInput.focus();",
    "        });",
    "    }",
    "",
    "    if (navOfficeBtn) {",
    "        navOfficeBtn.addEventListener('click', () => {",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('office');",
    "        });",
    "    }",
    "",
    "    if (navMissionBtn) {",
    "        navMissionBtn.addEventListener('click', () => {",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('mission');",
    "        });",
    "    }",
    "",
    "    if (navContentBtn) {",
    "        navContentBtn.addEventListener('click', () => {",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('content');",
    "        });",
    "    }",
    "",
    "    if (navInfiniteBtn) {",
    "        navInfiniteBtn.addEventListener('click', () => {",
    "            ensureSettingsUiClosed();",
    "            window.open('/companion', '_blank', 'noopener');",
    "        });",
    "    }",
    "",
    "    if (sidebarModeButtons.length) {",
    "        sidebarModeButtons.forEach((button) => {",
    "            button.addEventListener('click', () => {",
    "                const mode = normalizeNavMode(button.dataset.navMode);",
    "                if (!MODULE_NAV_MODE_SET.has(mode)) return;",
    "                ensureSettingsUiClosed();",
    "                setSidebarNavMode(mode);",
    "            });",
    "        });",
    "    }",
    "",
    "    if (globalSearchInput) {",
    "        globalSearchInput.addEventListener('input', () => {",
    "            renderSidebarChatList();",
    "        });",
    "    }",
    "",
    "    if (debugDockToggleBtn) {",
    "        debugDockToggleBtn.addEventListener('click', () => {",
    "            if (isDebugDockAnimating()) return;",
    "            const open = Boolean(appRoot?.classList.contains('debug-dock-open'));",
    "            setDebugDockOpen(!open);",
    "        });",
    "    }",
    "",
    "    if (debugDockCloseBtn) {",
    "        debugDockCloseBtn.addEventListener('click', () => {",
    "            if (isDebugDockAnimating()) return;",
    "            setDebugDockOpen(false);",
    "        });",
    "    }",
    "",
    "    if (debugDockRefreshBtn) {",
    "        debugDockRefreshBtn.addEventListener('click', () => {",
    "            void refreshDebugLiveData({ force: true, reason: 'manual' });",
    "        });",
    "    }",
    "",
    "    if (debugCopySnapshotBtn) {",
    "        debugCopySnapshotBtn.addEventListener('click', () => {",
    "            void copyDebugSnapshotToClipboard();",
    "        });",
    "    }",
    "",
    "    if (debugOnboardingRepairBtn) {",
    "        debugOnboardingRepairBtn.addEventListener('click', () => {",
    "            void runDebugOnboardingRepairNow();",
    "        });",
    "    }",
    "",
    "    if (debugClearEventsBtn) {",
    "        debugClearEventsBtn.addEventListener('click', () => {",
    "            debugEvents = [];",
    "            renderDebugEventLog();",
    "            pushDebugEvent('tools', 'Cleared debug events');",
    "        });",
    "    }",
    "",
    "    if (debugClearConsoleBtn) {",
    "        debugClearConsoleBtn.addEventListener('click', () => {",
    "            debugConsoleEntries = [];",
    "            renderDebugConsoleLog();",
    "            updateDebugDockSnapshot();",
    "            pushDebugEvent('tools', 'Cleared console diagnostics');",
    "        });",
    "    }",
    "",
    "    if (debugClearNetworkBtn) {",
    "        debugClearNetworkBtn.addEventListener('click', () => {",
    "            debugNetworkEntries = [];",
    "            renderDebugNetworkLog();",
    "            updateDebugNetworkSummary();",
    "            updateDebugDockSnapshot();",
    "            pushDebugEvent('tools', 'Cleared network diagnostics');",
    "        });",
    "    }",
    "",
    "    window.addEventListener('resize', syncLayoutOffsets);",
    "",
    "    if (chatHistorySelector) {",
    "        chatHistorySelector.addEventListener('change', () => {",
    "            const selectedSession = chatHistorySelector.value;",
    "            if (selectedSession === 'new') {",
    "                createNewSessionAndRefresh();",
    "            } else {",
    "                loadSessionFromHistory(selectedSession);",
    "            }",
    "        });",
    "    }",
    "",
    "    if (settingsAdvancedToggle && settingsSuite) {",
    "        settingsAdvancedToggle.addEventListener('change', () => {",
    "            settingsSuite.classList.toggle('advanced-mode', settingsAdvancedToggle.checked);",
    "            updateSettingsSectionNavVisibility();",
    "        });",
    "    }",
    "    initSettingsSectionNavigation();",
    "",
    "    bindRangeValue(settingFontSize, settingFontSizeValue, (v) => `${Math.round(v)}px`);",
    "    bindRangeValue(settingVoiceSpeed, settingVoiceSpeedValue, (v) => `${v.toFixed(2)}x`);",
    "    bindRangeValue(settingAdvTemperature, settingAdvTemperatureValue, (v) => v.toFixed(2));",
    "    bindRangeValue(settingAdvTopP, settingAdvTopPValue, (v) => v.toFixed(2));",
    "    bindRangeValue(settingAdvFrequencyPenalty, settingAdvFrequencyPenaltyValue, (v) => v.toFixed(1));",
    "    bindRangeValue(settingAdvPresencePenalty, settingAdvPresencePenaltyValue, (v) => v.toFixed(1));",
    "    bindRangeValue(settingAdvAutoToolThreshold, settingAdvAutoToolThresholdValue, (v) => v.toFixed(2));",
    "",
    "    if (changeAvatarBtn && settingsAvatarInput) {",
    "        changeAvatarBtn.addEventListener('click', () => {",
    "            settingsAvatarInput.click();",
    "        });",
    "    }",
    "",
    "    if (settingsAvatarInput) {",
    "        settingsAvatarInput.addEventListener('change', () => {",
    "            const file = settingsAvatarInput.files && settingsAvatarInput.files[0];",
    "            if (!file) return;",
    "            if (!file.type.startsWith('image/')) {",
    "                notifyUser('Please choose an image file for your profile photo.', {",
    "                    tone: 'warning',",
    "                    debugKind: 'warning',",
    "                    durationMs: 2800,",
    "                });",
    "                settingsAvatarInput.value = '';",
    "                return;",
    "            }",
    "            const reader = new FileReader();",
    "            reader.onload = (event) => {",
    "                pendingAvatarOverride = safeString(event.target?.result);",
    "                refreshSettingsAvatarPreview();",
    "            };",
    "            reader.readAsDataURL(file);",
    "            settingsAvatarInput.value = '';",
    "        });",
    "    }",
    "",
    "    if (removeAvatarBtn) {",
    "        removeAvatarBtn.addEventListener('click', () => {",
    "            pendingAvatarOverride = '';",
    "            refreshSettingsAvatarPreview();",
    "        });",
    "    }",
    "",
    "    if (settingsDisplayName) {",
    "        settingsDisplayName.addEventListener('input', refreshSettingsAvatarPreview);",
    "    }",
    "",
    "    if (settingsBtn && settingsModal) {",
    "        settingsBtn.addEventListener('click', () => {",
    "            openSettingsModal();",
    "        });",
    "    }",
    "",
    "    if (closeSettingsBtn && settingsModal) {",
    "        closeSettingsBtn.addEventListener('click', closeSettingsModal);",
    "    }",
    "",
    "    if (saveSettingsBtn) {",
    "        saveSettingsBtn.addEventListener('click', saveSettings);",
    "    }",
    "",
    "    initModelSetup();",
    "    startRuntimeGuardMonitor();",
    "    pushDebugEvent('runtime', 'UI initialized');",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  MODEL SETUP & SETTINGS                                                 ║",
    "// ║  Model selector, profile switching, settings form, save/load prefs      ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function initModelSetup() {",
    "    const openModelSetupModal = () => {",
    "        modelSetupModal.classList.add('active');",
    "        modelSetupModal.style.display = 'flex';",
    "",
    "        // Seed from saved preferences or current active profile",
    "        const savedProfile = safeString(currentPreferences?.advanced?.model?.active_profile)",
    "            || modelSelector.value;",
    "        setupProviderSelector.value = savedProfile;",
    "",
    "        // Restore segmented controls from preferences",
    "        const savedAutonomy = safeString(currentPreferences?.autonomy?.default_level).replace('L', '');",
    "        if (savedAutonomy) {",
    "            activeAutonomyLevel = parseInt(savedAutonomy, 10) || 3;",
    "            setSegmentedControlSelection('setupAutonomyGroup', String(activeAutonomyLevel));",
    "        }",
    "        const prefsEconomy = safeString(currentPreferences?.advanced?.runtime?.default_token_economy);",
    "        const econRevMap = { cheap: 'cheap', optimal: 'balanced', max: 'max' };",
    "        if (prefsEconomy && econRevMap[prefsEconomy]) {",
    "            activeTokenEconomy = econRevMap[prefsEconomy];",
    "            setSegmentedControlSelection('setupEconomyGroup', activeTokenEconomy);",
    "        }",
    "",
    "        if (typeof _syncProviderUI === 'function') _syncProviderUI(savedProfile);",
    "        if (setupProviderSelector) setupProviderSelector.focus();",
    "    };",
    "",
    "    // Open Trigger",
    "    modelSetupBtn.addEventListener('click', () => {",
    "        openModelSetupModal();",
    "    });",
    "    modelSetupBtn.addEventListener('keydown', (event) => {",
    "        if (event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') {",
    "            event.preventDefault();",
    "            openModelSetupModal();",
    "        }",
    "    });",
    "",
    "    // Close Triggers",
    "    closeModelSetupBtn.addEventListener('click', () => {",
    "        modelSetupModal.style.display = 'none';",
    "    });",
    "",
    "    document.getElementById('modelSetupBackdrop').addEventListener('click', () => {",
    "        modelSetupModal.style.display = 'none';",
    "    });",
    "",
    "    // Personality Dropdown Logic (Show/Hide Custom Textarea)",
    "    setupPersonalitySelector.addEventListener('change', (e) => {",
    "        if (e.target.value === 'custom') {",
    "            customPersonalityGroup.classList.remove('hidden');",
    "        } else {",
    "            customPersonalityGroup.classList.add('hidden');",
    "        }",
    "    });",
    "",
    "    // Segmented Controls (Autonomy & Economy)",
    "    const bindSegmentedControl = (groupId, updateCallback) => {",
    "        const group = document.getElementById(groupId);",
    "        group.querySelectorAll('.segment').forEach(btn => {",
    "            btn.addEventListener('click', (e) => {",
    "                // Clear active",
    "                group.querySelectorAll('.segment').forEach(b => b.classList.remove('active'));",
    "                // Set active",
    "                const target = e.currentTarget;",
    "                target.classList.add('active');",
    "                updateCallback(target.dataset.level);",
    "            });",
    "        });",
    "    };",
    "",
    "    bindSegmentedControl('setupAutonomyGroup', val => activeAutonomyLevel = parseInt(val, 10));",
    "    bindSegmentedControl('setupEconomyGroup', val => activeTokenEconomy = val);",
    "    bindSegmentedControl('setupReasoningEffortGroup', val => { activeReasoningEffort = val; });",
    "",
    "    // Provider change: sync model select, reasoning effort, and meta",
    "    const _syncProviderUI = (profileName) => {",
    "        const p = availableModelProfiles.find(m => m.name === profileName);",
    "        const reasoningGroup = document.getElementById('setupReasoningGroup');",
    "        const metaEl = document.getElementById('setupProfileMeta');",
    "",
    "        // --- Model <select> ---",
    "        if (p && setupModelSelector) {",
    "            const defaultModel = safeString(p.model).split('/').pop() || '';",
    "            _populateModelSelect([defaultModel, ...(KNOWN_MODEL_SUGGESTIONS[p.provider] || [])]);",
    "            setupModelSelector.value = defaultModel;",
    "            activeModelOverride = defaultModel;",
    "            _discoverProfileModels(profileName, defaultModel);",
    "        }",
    "",
    "        // --- Reasoning effort ---",
    "        if (p && (p.provider === 'codex' || p.reasoning_effort)) {",
    "            if (reasoningGroup) reasoningGroup.style.display = '';",
    "            const cur = p.reasoning_effort || 'medium';",
    "            activeReasoningEffort = cur;",
    "            setSegmentedControlSelection('setupReasoningEffortGroup', cur);",
    "        } else {",
    "            if (reasoningGroup) reasoningGroup.style.display = 'none';",
    "            activeReasoningEffort = '';",
    "        }",
    "",
    "        // --- Profile meta (provider + url) ---",
    "        if (metaEl && p) {",
    "            const url = safeString(p.base_url);",
    "            metaEl.textContent = p.provider + (url ? '  \\u2022  ' + url : '');",
    "        } else if (metaEl) {",
    "            metaEl.textContent = '';",
    "        }",
    "    };",
    "",
    "    // Populate model <select> with deduped options",
    "    function _populateModelSelect(modelIds) {",
    "        if (!setupModelSelector) return;",
    "        const currentVal = setupModelSelector.value;",
    "        setupModelSelector.innerHTML = '';",
    "        const seen = new Set();",
    "        for (const id of modelIds) {",
    "            const clean = safeString(id);",
    "            if (!clean || seen.has(clean)) continue;",
    "            seen.add(clean);",
    "            const opt = document.createElement('option');",
    "            opt.value = clean;",
    "            opt.textContent = clean;",
    "            setupModelSelector.appendChild(opt);",
    "        }",
    "        if (currentVal && seen.has(currentVal)) setupModelSelector.value = currentVal;",
    "    }",
    "",
    "    // Async model discovery from server",
    "    async function _discoverProfileModels(profileName, defaultModel) {",
    "        try {",
    "            const inFlightSelection = safeString(setupModelSelector?.value);",
    "            const res = await fetch(`/api/models/${encodeURIComponent(profileName)}/ids`);",
    "            if (!res.ok) return;",
    "            const data = await res.json();",
    "            const discovered = Array.isArray(data.models) ? data.models : [];",
    "            const provider = (availableModelProfiles.find(m => m.name === profileName) || {}).provider || '';",
    "            const staticFallbacks = KNOWN_MODEL_SUGGESTIONS[provider] || [];",
    "            const merged = [defaultModel, ...discovered, ...staticFallbacks];",
    "            _populateModelSelect(merged);",
    "            // Preserve the in-flight user selection; otherwise prefer saved profile model.",
    "            if (inFlightSelection && setupModelSelector.querySelector(`option[value=\"${CSS.escape(inFlightSelection)}\"]`)) {",
    "                setupModelSelector.value = inFlightSelection;",
    "                activeModelOverride = inFlightSelection;",
    "                return;",
    "            }",
    "            const savedModelId = safeString(currentPreferences?.advanced?.model?.model_id);",
    "            const savedProfile = safeString(currentPreferences?.advanced?.model?.active_profile);",
    "            if (savedModelId && savedProfile === profileName && setupModelSelector.querySelector(`option[value=\"${CSS.escape(savedModelId)}\"]`)) {",
    "                setupModelSelector.value = savedModelId;",
    "                activeModelOverride = savedModelId;",
    "            }",
    "        } catch (e) {",
    "            console.warn('Model discovery failed for', profileName, e);",
    "        }",
    "    }",
    "",
    "    setupProviderSelector.addEventListener('change', (e) => _syncProviderUI(e.target.value));",
    "",
    "    // Model selector change tracking",
    "    if (setupModelSelector) {",
    "        setupModelSelector.addEventListener('change', (e) => {",
    "            activeModelOverride = safeString(e.target.value);",
    "        });",
    "    }",
    "",
    "    // Apply Button — persist ALL settings",
    "    applyModelSetupBtn.addEventListener('click', async () => {",
    "        // 1. Capture current UI state",
    "        const selectedProfile = setupProviderSelector.value;",
    "        const selectedModel = setupModelSelector ? safeString(setupModelSelector.value) : '';",
    "        activeModelOverride = selectedModel;",
    "        modelSelector.value = selectedProfile;",
    "",
    "        // 2. Update header label + localStorage backup",
    "        modelSetupCurrentLabel.textContent = _profileHeaderLabel(selectedProfile);",
    "        try { window.localStorage.setItem('thomas_active_profile', selectedProfile); } catch (_) {}",
    "        try { window.localStorage.setItem('thomas_active_model_id', selectedModel); } catch (_) {}",
    "",
    "        // 3. Build preferences patch (map UI values to preferences schema)",
    "        const economyMap = { cheap: 'cheap', balanced: 'optimal', max: 'max' };",
    "        const patch = {",
    "            memory: { enabled_global: Boolean(setupMemoryToggle && setupMemoryToggle.checked) },",
    "            autonomy: { default_level: 'L' + activeAutonomyLevel },",
    "            advanced: {",
    "                model: {",
    "                    active_profile: selectedProfile,",
    "                    model_id: selectedModel,",
    "                    reasoning_effort: activeReasoningEffort || 'medium',",
    "                },",
    "                runtime: {",
    "                    default_token_economy: economyMap[activeTokenEconomy] || 'optimal',",
    "                },",
    "            },",
    "        };",
    "",
    "        // 4. PATCH to server",
    "        try {",
    "            const res = await fetch('/api/preferences', {",
    "                method: 'PATCH',",
    "                headers: { 'Content-Type': 'application/json' },",
    "                body: JSON.stringify(patch),",
    "            });",
    "            if (res.ok) {",
    "                currentPreferences = await res.json();",
    "                updateSidebarIdentity();",
    "            }",
    "        } catch (e) {",
    "            console.error('Failed to persist model setup:', e);",
    "        }",
    "",
    "        // 5. Close Modal",
    "        modelSetupModal.style.display = 'none';",
    "    });",
    "",
    "    // Restart Server button",
    "    if (restartServerBtn) {",
    "        restartServerBtn.addEventListener('click', async () => {",
    "            if (!confirm('Restart the Thomas server? Active requests will be interrupted.')) return;",
    "            try {",
    "                const restartReq = await fetchJsonSafe('/api/server/restart', { method: 'POST', timeoutMs: 5000 });",
    "                if (!restartReq.ok) {",
    "                    const reason = safeString(restartReq?.text) || `HTTP ${restartReq.status || 0}`;",
    "                    throw new Error(reason || 'Restart request failed');",
    "                }",
    "",
    "                modelSetupModal.style.display = 'none';",
    "                if (restartOverlay) restartOverlay.classList.remove('hidden');",
    "",
    "                // Poll /api/health until server comes back (max 30s, poll every 500ms)",
    "                const restartStatus = document.getElementById('restartStatus');",
    "                for (let i = 0; i < 60; i++) {",
    "                    if (restartStatus) restartStatus.textContent = `Waiting\\u2026 ${Math.floor(i * 0.5)}s`;",
    "                    await new Promise(r => setTimeout(r, 500));",
    "                    const probe = await fetchJsonSafe('/api/health', { timeoutMs: 1500 });",
    "                    if (probe.ok) {",
    "                        if (restartStatus) restartStatus.textContent = 'Reconnecting\\u2026';",
    "                        if (restartOverlay) restartOverlay.classList.add('hidden');",
    "                        await fetchModels();",
    "                        // Re-import conversation into a fresh server session",
    "                        if (chatHistory.length > 0) {",
    "                            try {",
    "                                const importPayload = {",
    "                                    profile: (setupProviderSelector && setupProviderSelector.value) || 'local',",
    "                                    conversation: chatHistory.map(m => ({",
    "                                        role: safeString(m.role),",
    "                                        content: safeString(m.content),",
    "                                    })),",
    "                                };",
    "                                const importRes = await fetchJsonSafe('/api/session/import', {",
    "                                    method: 'POST',",
    "                                    headers: { 'Content-Type': 'application/json' },",
    "                                    body: JSON.stringify(importPayload),",
    "                                    timeoutMs: 5000,",
    "                                });",
    "                                if (importRes.ok) {",
    "                                    const imported = importRes.data && typeof importRes.data === 'object' ? importRes.data : {};",
    "                                    if (safeString(imported.session_id)) {",
    "                                        sessionId = safeString(imported.session_id);",
    "                                    }",
    "                                }",
    "                            } catch (_e) { console.warn('Session re-import after restart failed:', _e); }",
    "                        }",
    "                        return;",
    "                    }",
    "                }",
    "",
    "                if (restartOverlay) restartOverlay.classList.add('hidden');",
    "                alert('Server did not come back within 30 seconds. Check manually.');",
    "            } catch (e) {",
    "                if (restartOverlay) restartOverlay.classList.add('hidden');",
    "                const reason = safeString(e?.message) || 'Restart request failed.';",
    "                alert(`Restart failed: ${reason}`);",
    "                console.error('Restart request failed:', e);",
    "            }",
    "        });",
    "    }",
    "}",
    "",
    "async function persistMemorySetting(isEnabled) {",
    "    try {",
    "        const res = await fetch('/api/preferences', {",
    "            method: 'PATCH',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({",
    "                memory: { enabled_global: isEnabled }",
    "            })",
    "        });",
    "        if (res.ok) {",
    "            currentPreferences = await res.json();",
    "            updateSidebarIdentity();",
    "        }",
    "    } catch (e) {",
    "        console.error(\"Failed to save memory preference:\", e);",
    "    }",
    "}",
    "",
    "function openSettingsModal() {",
    "    if (!settingsModal) return;",
    "    setDebugDockOpen(false, { recordEvent: false });",
    "    settingsModal.classList.remove('hidden');",
    "    if (appRoot) appRoot.classList.add('settings-active');",
    "    settingsReturnNavMode = normalizeNavMode(sidebarNavMode);",
    "    setSidebarNavMode('chat', { persist: false });",
    "    if (settingsBtn) settingsBtn.classList.add('active');",
    "    loadSettings();",
    "}",
    "",
    "function isSettingsScreenOpen() {",
    "    return Boolean(settingsModal && !settingsModal.classList.contains('hidden'));",
    "}",
    "",
    "function ensureSettingsUiClosed() {",
    "    if (!settingsModal) return;",
    "    if (isSettingsScreenOpen()) {",
    "        closeSettingsModal();",
    "        return;",
    "    }",
    "    settingsModal.classList.add('hidden');",
    "    if (appRoot) appRoot.classList.remove('settings-active');",
    "    if (settingsBtn) settingsBtn.classList.remove('active');",
    "}",
    "",
    "function closeSettingsModal() {",
    "    if (!settingsModal) return;",
    "    settingsModal.classList.add('hidden');",
    "    if (appRoot) appRoot.classList.remove('settings-active');",
    "    if (settingsBtn) settingsBtn.classList.remove('active');",
    "    setSidebarNavMode(settingsReturnNavMode || loadStoredNavMode(), { persist: false });",
    "",
    "    const hasMessages = Boolean(chatMessagesInner && chatMessagesInner.children.length > 0);",
    "    if (welcomeScreen) welcomeScreen.classList.toggle('hidden', hasMessages);",
    "    if (chatScrollArea) chatScrollArea.classList.toggle('hidden', !hasMessages);",
    "}",
    "",
    "function toInt(value, fallback, min, max) {",
    "    const n = Number.parseInt(String(value), 10);",
    "    if (!Number.isFinite(n)) return fallback;",
    "    return Math.max(min, Math.min(max, n));",
    "}",
    "",
    "function toFloat(value, fallback, min, max) {",
    "    const n = Number.parseFloat(String(value));",
    "    if (!Number.isFinite(n)) return fallback;",
    "    return Math.max(min, Math.min(max, n));",
    "}",
    "",
    "function bindRangeValue(inputEl, valueEl, formatter) {",
    "    if (!inputEl || !valueEl) return;",
    "    const update = () => {",
    "        valueEl.textContent = formatter(Number(inputEl.value));",
    "    };",
    "    inputEl.addEventListener('input', update);",
    "    update();",
    "}",
    "",
    "function applyApiKeyPlaceholders(apiKeys = {}) {",
    "    const mapping = {",
    "        openai: settingApiKeyOpenai,",
    "        anthropic: settingApiKeyAnthropic,",
    "        google: settingApiKeyGoogle,",
    "        elevenlabs: settingApiKeyElevenlabs,",
    "        azure_openai: settingApiKeyAzureOpenai,",
    "        custom: settingApiKeyCustom,",
    "    };",
    "    Object.entries(mapping).forEach(([provider, input]) => {",
    "        if (!input) return;",
    "        input.value = '';",
    "        input.placeholder = safeString(apiKeys[provider]) || 'Not set';",
    "    });",
    "}",
    "",
    "function renderPowerPcRecommendationBadge(localPlan) {",
    "    if (!settingAdvPowerPcBadge) return;",
    "    const tier = safeString(localPlan?.device_tier).toLowerCase();",
    "    const mode = safeString(localPlan?.recommended_mode).toLowerCase();",
    "    if (!(tier === 'power' && mode === 'local_preferred')) {",
    "        settingAdvPowerPcBadge.classList.add('hidden');",
    "        settingAdvPowerPcBadge.textContent = '';",
    "        return;",
    "    }",
    "    const modelIds = (Array.isArray(localPlan?.recommended_models) ? localPlan.recommended_models : [])",
    "        .map((row) => safeString(row?.id))",
    "        .filter(Boolean)",
    "        .slice(0, 3);",
    "    const modelText = modelIds.length > 0 ? ` Suggested local models: ${modelIds.join(', ')}.` : '';",
    "    settingAdvPowerPcBadge.textContent = `Power PC mode recommended. This machine is suited for local-preferred runtime.${modelText}`;",
    "    settingAdvPowerPcBadge.classList.remove('hidden');",
    "}",
    "",
    "async function refreshPowerPcRecommendationBadge() {",
    "    if (!settingAdvPowerPcBadge) return;",
    "    settingAdvPowerPcBadge.classList.add('hidden');",
    "    settingAdvPowerPcBadge.textContent = '';",
    "    try {",
    "        const res = await fetchJsonSafe('/api/local/recommendations');",
    "        if (!res.ok || !res.data) return;",
    "        renderPowerPcRecommendationBadge(res.data?.local_plan);",
    "    } catch {",
    "        // Non-blocking UI hint only.",
    "    }",
    "}",
    "",
    "function normalizeChatMode(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    return new Set(['auto', 'fast', 'thinking']).has(mode) ? mode : '';",
    "}",
    "",
    "function _profileHeaderLabel(profileName) {",
    "    const p = availableModelProfiles.find(m => m.name === profileName);",
    "    if (!p) return profileName;",
    "    // Prefer active overrides over profile defaults",
    "    const model = activeModelOverride",
    "        || safeString(p.model).split('/').pop()",
    "        || profileName;",
    "    const effort = activeReasoningEffort || safeString(p.reasoning_effort);",
    "    return effort ? `${model} (${effort})` : model;",
    "}",
    "",
    "function applyProfileSelection(profileRaw) {",
    "    const profile = safeString(profileRaw);",
    "    if (!profile) return;",
    "    if (setupProviderSelector) setupProviderSelector.value = profile;",
    "    if (modelSelector) modelSelector.value = profile;",
    "    if (modelSetupCurrentLabel) modelSetupCurrentLabel.textContent = _profileHeaderLabel(profile);",
    "}",
    "",
    "function setSegmentedControlSelection(groupId, levelRaw) {",
    "    const group = document.getElementById(groupId);",
    "    if (!group) return;",
    "    const level = safeString(levelRaw);",
    "    group.querySelectorAll('.segment').forEach((segmentBtn) => {",
    "        const isActive = safeString(segmentBtn.dataset.level) === level;",
    "        segmentBtn.classList.toggle('active', isActive);",
    "    });",
    "}",
    "",
    "function applyUiStatePatchEvent(evt) {",
    "    if (!evt || typeof evt !== 'object') return;",
    "    const rawPatch = evt.applied_patch && typeof evt.applied_patch === 'object'",
    "        ? evt.applied_patch",
    "        : (evt.patch && typeof evt.patch === 'object' ? evt.patch : null);",
    "    if (!rawPatch) return;",
    "",
    "    applyProfileSelection(rawPatch.activeProfile);",
    "",
    "    const mode = normalizeChatMode(rawPatch.mode);",
    "    if (mode) {",
    "        activeChatMode = mode;",
    "        if (settingAdvDefaultMode) settingAdvDefaultMode.value = mode;",
    "    }",
    "",
    "    const settings = rawPatch.settings;",
    "    if (!settings || typeof settings !== 'object') return;",
    "",
    "    const autonomyLevel = Number.parseInt(String(settings.autonomyLevel ?? ''), 10);",
    "    if (Number.isFinite(autonomyLevel)) {",
    "        const nextLevel = Math.max(1, Math.min(4, autonomyLevel));",
    "        activeAutonomyLevel = nextLevel;",
    "        setSegmentedControlSelection('setupAutonomyGroup', String(nextLevel));",
    "        if (settingAutonomy) settingAutonomy.value = `L${nextLevel}`;",
    "    }",
    "",
    "    const themeRaw = safeString(settings.theme).toLowerCase();",
    "    if (themeRaw) {",
    "        const themeValue = themeRaw === 'system' ? 'auto' : themeRaw;",
    "        if (settingTheme && new Set(['auto', 'light', 'dark']).has(themeValue)) {",
    "            settingTheme.value = themeValue;",
    "        }",
    "    }",
    "}",
    "",
    "function refreshSettingsAvatarPreview() {",
    "    const name = safeString(settingsDisplayName?.value) || resolveAgentName(currentPreferences);",
    "    const avatarBase = pendingAvatarOverride !== null",
    "        ? pendingAvatarOverride",
    "        : safeString(currentPreferences?.profile?.avatar_url);",
    "    const avatarUrl = safeString(avatarBase) || safeString(currentCodexStatus?.avatar_url);",
    "    setAvatarVisual(settingsProfileAvatar, {",
    "        text: initialsFromName(name),",
    "        imageUrl: avatarUrl,",
    "    });",
    "}",
    "",
    "async function refreshIdentityState() {",
    "    try {",
    "        const [prefsRes, codexRes] = await Promise.all([",
    "            fetch('/api/preferences'),",
    "            fetchJsonSafe('/api/codex/status'),",
    "        ]);",
    "        if (prefsRes.ok) {",
    "            currentPreferences = await prefsRes.json();",
    "            if (!currentPreferences || typeof currentPreferences !== 'object') currentPreferences = {};",
    "            const prefAutonomyRaw = safeString(currentPreferences?.autonomy?.default_level).replace(/^l/i, '');",
    "            const prefAutonomy = Number.parseInt(prefAutonomyRaw, 10);",
    "            if (Number.isFinite(prefAutonomy)) {",
    "                activeAutonomyLevel = Math.max(1, Math.min(4, prefAutonomy));",
    "                setSegmentedControlSelection('setupAutonomyGroup', String(activeAutonomyLevel));",
    "                if (settingAutonomy) settingAutonomy.value = `L${activeAutonomyLevel}`;",
    "            }",
    "        }",
    "        if (codexRes.ok) {",
    "            currentCodexStatus = codexRes.data || null;",
    "        } else if (!codexRes.ok && codexRes.status) {",
    "            currentCodexStatus = null;",
    "        }",
    "    } catch (e) {",
    "        console.error('Failed to load identity state', e);",
    "    } finally {",
    "        applyInterfaceMotionPreference();",
    "        updateSidebarIdentity();",
    "        setDebugDockOpen(false, { recordEvent: false });",
    "        updateDebugDockSnapshot();",
    "    }",
    "}",
    "",
    "async function loadSettings() {",
    "    try {",
    "        const [prefsRes, codexRes] = await Promise.all([",
    "            fetchJsonSafe('/api/preferences'),",
    "            fetchJsonSafe('/api/codex/status'),",
    "        ]);",
    "        if (!prefsRes.ok) {",
    "            throw new Error(`Failed to load preferences (${prefsRes.status})`);",
    "        }",
    "",
].join("\n");
