/* app.js lines 1001-2000 */
export default [
    "            'My bad, rerouting smooth.',",
    "        ],",
    "    },",
    "    orange: {",
    "        working: [",
    "            'Build lane hot. Let me cook.',",
    "            'I am on turbo and still readable.',",
    "            'Banana pro energy but disciplined.',",
    "        ],",
    "        break: [",
    "            'Snack break speedrun.',",
    "            'Lunch loop in and out.',",
    "        ],",
    "        socialLead: [",
    "            'Brandon, Trey, status ping?',",
    "            'Team, quick roast then back to work?',",
    "        ],",
    "        socialReply: [",
    "            'Respectfully hilarious, now focus.',",
    "            'Noted. Shipping anyway.',",
    "        ],",
    "        collision: [",
    "            'Watch out, speed goblin incoming.',",
    "            'Sorry, hallway drift.',",
    "        ],",
    "    },",
    "    pink: {",
    "        working: [",
    "            'Polish pass in progress.',",
    "            'Making this look expensive.',",
    "            'Aligning details so it feels pro.',",
    "        ],",
    "        break: [",
    "            'Resetting eyes for pixel-perfect pass.',",
    "            'Quick tea and aesthetic recalibration.',",
    "        ],",
    "        socialLead: [",
    "            'Can we align visual language real quick?',",
    "            'Need one clean second opinion.',",
    "        ],",
    "        socialReply: [",
    "            'Yep, that composition is better.',",
    "            'Agreed. Keep it purposeful.',",
    "        ],",
    "        collision: [",
    "            'Oops, sorry, wardrobe malfunction.',",
    "            'Tiny crash, no drama.',",
    "        ],",
    "    },",
    "    purple: {",
    "        working: [",
    "            'Deep work pod mode active.',",
    "            'Threading context with zero panic.',",
    "            'Strategic pass underway.',",
    "        ],",
    "        break: [",
    "            'Micro-break for macro clarity.',",
    "            'Lunch room strategy huddle.',",
    "        ],",
    "        socialLead: [",
    "            'Can we map priorities in 20 seconds?',",
    "            'Need a fast alignment check.',",
    "        ],",
    "        socialReply: [",
    "            'Priority order looks strong.',",
    "            'Yep, sequence is correct.',",
    "        ],",
    "        collision: [",
    "            'Excuse me, merging left.',",
    "            'Sorry, traffic math failed me.',",
    "        ],",
    "    },",
    "    yellow: {",
    "        working: [",
    "            'Support lane warm and responsive.',",
    "            'Handling tickets with empathy and speed.',",
    "            'Status updates queued and clear.',",
    "        ],",
    "        break: [",
    "            'Coffee with customer context.',",
    "            'Quick reset, then support sweep.',",
    "        ],",
    "        socialLead: [",
    "            'Need help triaging this queue?',",
    "            'Anyone free for a fast handoff?',",
    "        ],",
    "        socialReply: [",
    "            'Yep, I can cover that.',",
    "            'Good handoff, thanks.',",
    "        ],",
    "        collision: [",
    "            'Whoops, pardon me.',",
    "            'Sorry, crowding there.',",
    "        ],",
    "    },",
    "    default: {",
    "        working: OFFICE_DIALOGUE.working,",
    "        break: OFFICE_DIALOGUE.break,",
    "        socialLead: ['Quick sync?', 'Any updates?'],",
    "        socialReply: ['Sounds good.', 'Copy that.'],",
    "        collision: OFFICE_DIALOGUE.collision,",
    "    },",
    "};",
    "",
    "// ── Chat Robot Status Sayings ──",
    "const CHAT_ROBOT_SAYINGS = {",
    "    thinking: [",
    "        'Spinning up robots...',",
    "        'Beep boop beep...',",
    "        'Consulting the hive mind...',",
    "        'Warming up neurons...',",
    "        'Loading clever thoughts...',",
    "        'Connecting synapses...',",
    "        'Brewing fresh ideas...',",
    "        'Calibrating brain waves...',",
    "        'Pondering possibilities...',",
    "        'Initializing thought engine...',",
    "    ],",
    "    working: [",
    "        'Building something cool...',",
    "        'Robots are on it...',",
    "        'Turbo mode engaged...',",
    "        'Compiling awesomeness...',",
    "        'Making magic happen...',",
    "        'Crunching the numbers...',",
    "        'Assembling the pieces...',",
    "        'Putting it all together...',",
    "        'Almost there, hang tight...',",
    "        'Cooking up a response...',",
    "    ],",
    "};",
    "",
    "// Tool name → human-friendly description",
    "const CHAT_TOOL_DESCRIPTIONS = {",
    "    'fs.read_file':           'Reading files...',",
    "    'fs.write_file':          'Writing code...',",
    "    'fs.list_dir':            'Browsing directories...',",
    "    'fs.search':              'Searching files...',",
    "    'code.search':            'Searching codebase...',",
    "    'code.find_definition':   'Finding definitions...',",
    "    'code.find_references':   'Finding references...',",
    "    'code.project_structure': 'Mapping project structure...',",
    "    'shell.exec':             'Running a command...',",
    "    'git.status':             'Checking git status...',",
    "    'git.log':                'Reading git history...',",
    "    'git.diff':               'Reviewing changes...',",
    "    'git.commit':             'Committing changes...',",
    "    'git.blame':              'Checking git blame...',",
    "    'browser.open':           'Opening a page...',",
    "    'browser.click':          'Clicking around...',",
    "    'browser.type':           'Typing in browser...',",
    "    'browser.screenshot':     'Taking a screenshot...',",
    "    'browser.extract':        'Extracting page data...',",
    "    'browser.close':          'Closing browser...',",
    "    'diff.create':            'Preparing a diff...',",
    "    'diff.preview':           'Previewing changes...',",
    "    'diff.apply_patch':       'Applying changes...',",
    "    'email.send':             'Sending email...',",
    "    'email.reply':            'Replying to email...',",
    "    'email.read':             'Reading email...',",
    "    'email.get':              'Fetching email...',",
    "    'calendar.today':         'Checking calendar...',",
    "    'calendar.week':          'Checking schedule...',",
    "    'calendar.create_event':  'Creating event...',",
    "    'calendar.suggest_times': 'Finding free times...',",
    "    'db.query':               'Querying database...',",
    "    'db.schema':              'Reading schema...',",
    "    'db.connections':         'Checking connections...',",
    "    'rag.search':             'Searching knowledge base...',",
    "};",
    "// Prefix fallbacks for tool families",
    "const CHAT_TOOL_PREFIX_MAP = {",
    "    'fs.':       'Working with files...',",
    "    'code.':     'Analyzing code...',",
    "    'git.':      'Checking git...',",
    "    'browser.':  'Browsing the web...',",
    "    'diff.':     'Preparing changes...',",
    "    'email.':    'Handling email...',",
    "    'calendar.': 'Checking calendar...',",
    "    'db.':       'Querying database...',",
    "};",
    "function describeToolName(toolName) {",
    "    const name = (toolName || '').trim();",
    "    if (CHAT_TOOL_DESCRIPTIONS[name]) return CHAT_TOOL_DESCRIPTIONS[name];",
    "    for (const prefix in CHAT_TOOL_PREFIX_MAP) {",
    "        if (name.startsWith(prefix)) return CHAT_TOOL_PREFIX_MAP[prefix];",
    "    }",
    "    return null; // no match — caller falls back to generic",
    "}",
    "",
    "/**",
    " * Create a collapsible tool call card DOM element.",
    " * @param {string} toolName - The tool's identifier",
    " * @returns {{ card: HTMLElement, setArgs: (args: any) => void, setResult: (result: any, ok?: boolean) => void }}",
    " */",
    "function createToolCallCard(toolName) {",
    "    const desc = describeToolName(toolName) || toolName || 'Tool';",
    "    const card = document.createElement('div');",
    "    card.className = 'tool-call-card';",
    "    card.innerHTML = `",
    "        <div class=\"tool-call-header\">",
    "            <span class=\"tool-call-icon\"><i class=\"ph ph-wrench\"></i></span>",
    "            <span class=\"tool-call-name\">${escapeHtml(desc)}</span>",
    "            <span class=\"tool-call-status\"><span class=\"tool-call-spinner\"></span></span>",
    "            <span class=\"tool-call-chevron\"><i class=\"ph ph-caret-down\"></i></span>",
    "        </div>",
    "        <div class=\"tool-call-body\">",
    "            <pre class=\"tool-call-args\"></pre>",
    "            <pre class=\"tool-call-result\" style=\"display:none\"></pre>",
    "        </div>",
    "    `;",
    "    const header = card.querySelector('.tool-call-header');",
    "    header.addEventListener('click', () => card.classList.toggle('expanded'));",
    "",
    "    function setArgs(args) {",
    "        const el = card.querySelector('.tool-call-args');",
    "        if (!el) return;",
    "        try {",
    "            el.textContent = typeof args === 'string' ? args : JSON.stringify(args, null, 2);",
    "        } catch { el.textContent = String(args); }",
    "    }",
    "",
    "    function setResult(result, ok = true) {",
    "        const statusEl = card.querySelector('.tool-call-status');",
    "        if (statusEl) statusEl.innerHTML = ok ? '<i class=\"ph ph-check-circle\" style=\"color: #3fb950\"></i>' : '<i class=\"ph ph-x-circle\" style=\"color: #f85149\"></i>';",
    "        const el = card.querySelector('.tool-call-result');",
    "        if (!el) return;",
    "        try {",
    "            el.textContent = typeof result === 'string' ? result : JSON.stringify(result, null, 2);",
    "        } catch { el.textContent = String(result); }",
    "        if (el.textContent.trim()) el.style.display = '';",
    "    }",
    "",
    "    return { card, setArgs, setResult };",
    "}",
    "",
    "let _lastSayingIndex = {};",
    "function pickChatSaying(category) {",
    "    const arr = CHAT_ROBOT_SAYINGS[category];",
    "    if (!arr || arr.length === 0) return 'Working...';",
    "    let idx;",
    "    do {",
    "        idx = Math.floor(Math.random() * arr.length);",
    "    } while (idx === _lastSayingIndex[category] && arr.length > 1);",
    "    _lastSayingIndex[category] = idx;",
    "    return arr[idx];",
    "}",
    "",
    "const CHAT_ROBOT_ANIMATIONS = ['fishing', 'bouncing', 'looking', 'napping', 'waving'];",
    "const CHAT_ROBOT_DOCK_ID = 'chatRobotDock';",
    "const CHAT_ROBOT_DOCK_WIDTH = 16;",
    "const CHAT_ROBOT_DOCK_HEIGHT = 14;",
    "const CHAT_ROBOT_DOCK_OUTSIDE_GAP = 14;",
    "const CHAT_ROBOT_EXIT_FALL_MS = 1550;",
    "const CHAT_ROBOT_ENTRY_PORTAL_LEAD_MS = 210;",
    "const CHAT_ROBOT_ENTRY_STEP_MS = 340;",
    "let _lastRobotAnim = '';",
    "function _pickRobotAnimation() {",
    "    let pick;",
    "    do {",
    "        pick = CHAT_ROBOT_ANIMATIONS[Math.floor(Math.random() * CHAT_ROBOT_ANIMATIONS.length)];",
    "    } while (pick === _lastRobotAnim && CHAT_ROBOT_ANIMATIONS.length > 1);",
    "    _lastRobotAnim = pick;",
    "    return pick;",
    "}",
    "",
    "function _createLandedRobotElement() {",
    "    const landed = document.createElement('div');",
    "    landed.className = 'chat-robot-landed';",
    "    landed.innerHTML = `",
    "        <span class=\"office-agent-head\">",
    "            <span class=\"office-agent-eye office-agent-eye-left\"></span>",
    "            <span class=\"office-agent-eye office-agent-eye-right\"></span>",
    "        </span>",
    "        <span class=\"office-agent-body\"></span>",
    "        <span class=\"office-agent-leg office-agent-leg-left\"></span>",
    "        <span class=\"office-agent-leg office-agent-leg-right\"></span>",
    "    `;",
    "    return landed;",
    "}",
    "",
    "function _ensureRobotDock() {",
    "    let dock = document.getElementById(CHAT_ROBOT_DOCK_ID);",
    "    if (!(dock instanceof HTMLElement)) {",
    "        dock = document.createElement('div');",
    "        dock.id = CHAT_ROBOT_DOCK_ID;",
    "        dock.className = 'chat-robot-dock is-hidden';",
    "        document.body.appendChild(dock);",
    "    }",
    "    return dock;",
    "}",
    "",
    "function _positionRobotDock() {",
    "    const dock = _ensureRobotDock();",
    "    const anchorRect = attachBtn instanceof HTMLElement ? attachBtn.getBoundingClientRect() : null;",
    "    if (!anchorRect || anchorRect.width < 2 || anchorRect.height < 2) {",
    "        dock.classList.add('is-hidden');",
    "        return dock;",
    "    }",
    "    const leftRaw = Math.round(anchorRect.left - CHAT_ROBOT_DOCK_WIDTH - CHAT_ROBOT_DOCK_OUTSIDE_GAP);",
    "    const topRaw = Math.round(anchorRect.top + ((anchorRect.height - CHAT_ROBOT_DOCK_HEIGHT) * 0.5));",
    "    const viewportWidth = Math.max(0, Number(window.innerWidth) || 0);",
    "    const maxLeft = Math.max(4, viewportWidth - CHAT_ROBOT_DOCK_WIDTH - 4);",
    "    const left = Math.max(4, Math.min(maxLeft, leftRaw));",
    "    const top = Math.max(4, topRaw);",
    "    dock.style.left = `${left}px`;",
    "    dock.style.top = `${top}px`;",
    "    dock.classList.remove('is-hidden');",
    "    return dock;",
    "}",
    "",
    "function _asLandedRobotElement(sourceNode = null) {",
    "    const landed = sourceNode instanceof HTMLElement ? sourceNode : _createLandedRobotElement();",
    "    landed.classList.remove('chat-robot-agent', 'chat-robot-enter', 'robot-exit-run');",
    "    CHAT_ROBOT_ANIMATIONS.forEach((anim) => landed.classList.remove('chat-robot-anim-' + anim));",
    "    landed.classList.add('chat-robot-landed');",
    "    landed.removeAttribute('data-idle-anim');",
    "    landed.style.position = '';",
    "    landed.style.top = '';",
    "    landed.style.left = '';",
    "    landed.style.zIndex = '';",
    "    landed.style.filter = '';",
    "    landed.style.animation = '';",
    "    landed.style.transform = '';",
    "    landed.style.opacity = '';",
    "    landed.style.pointerEvents = '';",
    "    return landed;",
    "}",
    "",
    "function _landRobotAtComposerDock(sourceNode = null) {",
    "    document.querySelectorAll('.chat-robot-landed').forEach((node) => {",
    "        if (node !== sourceNode) node.remove();",
    "    });",
    "    const dock = _positionRobotDock();",
    "    dock.innerHTML = '';",
    "    const landed = _asLandedRobotElement(sourceNode);",
    "    landed.classList.add('chat-robot-landed-entry');",
    "",
    "    const entryWrap = document.createElement('div');",
    "    entryWrap.className = 'chat-robot-landed-entry-wrap';",
    "    entryWrap.innerHTML = `",
    "        <span class=\"chat-robot-portal portal-opening\">",
    "            <span class=\"chat-game-portal-ring\"></span>",
    "            <span class=\"chat-game-portal-ring ring-inner\"></span>",
    "            <span class=\"chat-game-portal-core\"></span>",
    "        </span>",
    "    `;",
    "    entryWrap.appendChild(landed);",
    "    dock.appendChild(entryWrap);",
    "",
    "    const entryPortal = entryWrap.querySelector('.chat-robot-portal');",
    "    const revealRobot = () => landed.classList.add('is-visible');",
    "    setTimeout(revealRobot, CHAT_ROBOT_ENTRY_PORTAL_LEAD_MS);",
    "",
    "    if (entryPortal) {",
    "        entryPortal.addEventListener('animationend', function onOpen(e) {",
    "            if (e.animationName !== 'chatPortalOpen') return;",
    "            entryPortal.classList.remove('portal-opening');",
    "            entryPortal.classList.add('portal-closing');",
    "            entryPortal.removeEventListener('animationend', onOpen);",
    "            entryPortal.addEventListener('animationend', () => entryPortal.remove(), { once: true });",
    "        });",
    "    }",
    "",
    "    setTimeout(() => {",
    "        if (!(entryWrap.parentNode instanceof HTMLElement)) return;",
    "        const staticRobot = _asLandedRobotElement(landed);",
    "        staticRobot.classList.add('chat-robot-landed-steady');",
    "        staticRobot.classList.remove('chat-robot-landed-entry', 'is-visible');",
    "        entryWrap.replaceWith(staticRobot);",
    "    }, CHAT_ROBOT_ENTRY_PORTAL_LEAD_MS + CHAT_ROBOT_ENTRY_STEP_MS + 420);",
    "}",
    "",
    "function _portalOutLandedRobot() {",
    "    return new Promise((resolve) => {",
    "        const existingLanded = document.querySelector('.chat-robot-landed');",
    "        if (!existingLanded || !(existingLanded.parentNode instanceof HTMLElement)) {",
    "            resolve();",
    "            return;",
    "        }",
    "        const parent = existingLanded.parentNode;",
    "        const exitWrap = document.createElement('div');",
    "        exitWrap.className = 'chat-robot-landed-exit';",
    "        exitWrap.innerHTML = `",
    "            <span class=\"chat-robot-portal portal-opening\">",
    "                <span class=\"chat-game-portal-ring\"></span>",
    "                <span class=\"chat-game-portal-ring ring-inner\"></span>",
    "                <span class=\"chat-game-portal-core\"></span>",
    "            </span>",
    "        `;",
    "        parent.insertBefore(exitWrap, existingLanded);",
    "        exitWrap.appendChild(existingLanded);",
    "        let settled = false;",
    "        const done = () => {",
    "            if (settled) return;",
    "            settled = true;",
    "            resolve();",
    "        };",
    "        const exitPortal = exitWrap.querySelector('.chat-robot-portal');",
    "        if (exitPortal) {",
    "            exitPortal.addEventListener('animationend', function onOpen(e) {",
    "                if (e.animationName !== 'chatPortalOpen') return;",
    "                exitPortal.classList.remove('portal-opening');",
    "                exitPortal.classList.add('portal-closing');",
    "                exitPortal.removeEventListener('animationend', onOpen);",
    "                exitPortal.addEventListener('animationend', () => {",
    "                    exitWrap.remove();",
    "                    done();",
    "                }, { once: true });",
    "            });",
    "        }",
    "        setTimeout(() => {",
    "            if (exitWrap.parentNode) exitWrap.remove();",
    "            done();",
    "        }, 1700);",
    "    });",
    "}",
    "",
    "window.addEventListener('resize', () => _positionRobotDock());",
    "window.addEventListener('scroll', () => _positionRobotDock(), { passive: true });",
    "if (window.visualViewport) {",
    "    window.visualViewport.addEventListener('resize', () => _positionRobotDock());",
    "    window.visualViewport.addEventListener('scroll', () => _positionRobotDock());",
    "}",
    "",
    "function _createRobotStatus(category) {",
    "    const anim = _pickRobotAnimation();",
    "    const wrapper = document.createElement('div');",
    "    wrapper.className = 'chat-robot-status';",
    "    wrapper.innerHTML = `",
    "        <span class=\"chat-robot-portal-wrap\">",
    "            <span class=\"chat-robot-portal portal-opening\">",
    "                <span class=\"chat-game-portal-ring\"></span>",
    "                <span class=\"chat-game-portal-ring ring-inner\"></span>",
    "                <span class=\"chat-game-portal-core\"></span>",
    "            </span>",
    "            <span class=\"chat-robot-agent-step chat-robot-enter-step\">",
    "                <span class=\"chat-robot-agent chat-robot-enter\" data-idle-anim=\"${anim}\">",
    "                    <span class=\"office-agent-head\">",
    "                        <span class=\"office-agent-eye office-agent-eye-left\"></span>",
    "                        <span class=\"office-agent-eye office-agent-eye-right\"></span>",
    "                    </span>",
    "                    <span class=\"office-agent-body\"></span>",
    "                    <span class=\"office-agent-leg office-agent-leg-left\"></span>",
    "                    <span class=\"office-agent-leg office-agent-leg-right\"></span>",
    "                </span>",
    "            </span>",
    "        </span>",
    "        <span class=\"chat-robot-text-wrap\">",
    "            <span class=\"chat-robot-saying-row\">",
    "                <span class=\"chat-robot-saying\">${pickChatSaying(category)}</span>",
    "                <button type=\"button\" class=\"chat-robot-thinking-toggle\" title=\"Show thinking details\" aria-expanded=\"false\">",
    "                    <svg width=\"10\" height=\"10\" viewBox=\"0 0 10 10\"><path d=\"M2 3.5L5 6.5L8 3.5\" stroke=\"currentColor\" stroke-width=\"1.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>",
    "                </button>",
    "            </span>",
    "            <span class=\"chat-robot-timer\">0.0s</span>",
    "        </span>",
    "        <div class=\"chat-robot-thinking-details\">",
    "            <div class=\"thinking-text-content\"></div>",
    "            <div class=\"thinking-tool-cards\"></div>",
    "        </div>",
    "    `;",
    "",
    "    // Wire toggle button",
    "    const toggleBtn = wrapper.querySelector('.chat-robot-thinking-toggle');",
    "    const detailsEl = wrapper.querySelector('.chat-robot-thinking-details');",
    "    if (toggleBtn && detailsEl) {",
    "        toggleBtn.addEventListener('click', (e) => {",
    "            e.stopPropagation();",
    "            const expanding = !detailsEl.classList.contains('expanded');",
    "            detailsEl.classList.toggle('expanded', expanding);",
    "            toggleBtn.classList.toggle('expanded', expanding);",
    "            toggleBtn.setAttribute('aria-expanded', String(expanding));",
    "            // Auto-scroll to bottom when expanding",
    "            if (expanding) detailsEl.scrollTop = detailsEl.scrollHeight;",
    "        });",
    "    }",
    "",
    "    // Stagger: entrance first, THEN idle animation after materialize finishes",
    "    const agentEl = wrapper.querySelector('.chat-robot-agent');",
    "    const portalEl = wrapper.querySelector('.chat-robot-portal');",
    "    if (agentEl) {",
    "        agentEl.addEventListener('animationend', function onMaterialize(e) {",
    "            if (e.animationName === 'chatRobotMaterialize') {",
    "                agentEl.classList.remove('chat-robot-enter');",
    "                agentEl.classList.add('chat-robot-anim-' + (agentEl.dataset.idleAnim || 'bouncing'));",
    "                agentEl.removeEventListener('animationend', onMaterialize);",
    "            }",
    "        });",
    "    }",
    "    // Close portal after it opens",
    "    if (portalEl) {",
    "        portalEl.addEventListener('animationend', function onPortalOpen(e) {",
    "            if (e.animationName === 'chatPortalOpen') {",
    "                setTimeout(() => {",
    "                    portalEl.classList.remove('portal-opening');",
    "                    portalEl.classList.add('portal-closing');",
    "                    portalEl.addEventListener('animationend', () => portalEl.remove(), { once: true });",
    "                }, 140);",
    "                portalEl.removeEventListener('animationend', onPortalOpen);",
    "            }",
    "        });",
    "    }",
    "    return wrapper;",
    "}",
    "",
    "/**",
    " * Update the inline thinking text display with accumulated thinking content.",
    " * Called whenever new thinking tokens arrive during streaming.",
    " */",
    "function _updateThinkingDisplay(container, text) {",
    "    if (!container) return;",
    "    const contentEl = container.querySelector('.thinking-text-content');",
    "    if (!contentEl) return;",
    "    contentEl.textContent = text;",
    "    // Auto-scroll if the details panel is expanded",
    "    if (container.classList.contains('expanded')) {",
    "        container.scrollTop = container.scrollHeight;",
    "    }",
    "}",
    "",
    "/**",
    " * Create a post-stream \"Thought for X.Xs\" collapsed summary that replaces the robot status.",
    " * Shows accumulated thinking/reasoning text like Claude and ChatGPT.",
    " * Returns the summary element or null if no thinking data was available.",
    " */",
    "function _createThinkingSummary(elapsedMs, capturedThinkingText, capturedToolCards) {",
    "    const seconds = (elapsedMs / 1000).toFixed(1);",
    "    const text = (capturedThinkingText || '').trim();",
    "    const hasToolCards = capturedToolCards && capturedToolCards.length > 0;",
    "    if (!text && !hasToolCards) return null;",
    "",
    "    const summary = document.createElement('div');",
    "    summary.className = 'thinking-summary';",
    "",
    "    summary.innerHTML = `",
    "        <button type=\"button\" class=\"thinking-summary-toggle\" aria-expanded=\"false\">",
    "            <span class=\"thinking-summary-label\">Thought for ${seconds}s</span>",
    "            <svg class=\"thinking-summary-arrow\" width=\"10\" height=\"10\" viewBox=\"0 0 10 10\"><path d=\"M2 3.5L5 6.5L8 3.5\" stroke=\"currentColor\" stroke-width=\"1.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>",
    "        </button>",
    "        <div class=\"thinking-summary-details\">",
    "            <div class=\"thinking-text-content\"></div>",
    "            <div class=\"thinking-tool-cards\"></div>",
    "        </div>",
    "    `;",
    "",
    "    // Set text content via DOM (safe, no innerHTML injection)",
    "    if (text) {",
    "        const contentEl = summary.querySelector('.thinking-text-content');",
    "        if (contentEl) contentEl.textContent = text;",
    "    }",
    "",
    "    // Move captured tool card elements into the summary",
    "    if (hasToolCards) {",
    "        const toolContainer = summary.querySelector('.thinking-tool-cards');",
    "        if (toolContainer) {",
    "            for (const tc of capturedToolCards) {",
    "                toolContainer.appendChild(tc.card);",
    "            }",
    "        }",
    "    }",
    "",
    "    const toggleBtn = summary.querySelector('.thinking-summary-toggle');",
    "    const detailsEl = summary.querySelector('.thinking-summary-details');",
    "    toggleBtn.addEventListener('click', (e) => {",
    "        e.stopPropagation();",
    "        const expanding = !detailsEl.classList.contains('expanded');",
    "        detailsEl.classList.toggle('expanded', expanding);",
    "        toggleBtn.classList.toggle('expanded', expanding);",
    "        toggleBtn.setAttribute('aria-expanded', String(expanding));",
    "    });",
    "",
    "    return summary;",
    "}",
    "",
    "let suggestionRailVersion = 0;",
    "let suggestionContext = '';",
    "let suggestionDismissible = true;",
    "const introShownSessionIds = new Set();",
    "",
    "const ONBOARDING_VERSION = 3;",
    "const easySetupState = {",
    "    step: 1,",
    "    source: 'auto',",
    "    required: true,",
    "    onboardingSessionId: '',",
    "    telemetryStartedAtMs: 0,",
    "    selectedPath: '',",
    "    bootstrap: null,",
    "    verified: false,",
    "    verifiedProfile: '',",
    "    codexModels: [],",
    "    dependencyPlan: [],",
    "    dependenciesAction: 'pending',",
    "    interviewStarted: false,",
    "    interviewStage: 'idle',",
    "    interviewIndex: -1,",
    "    interviewAnswers: {},",
    "    interviewSkipChosen: false,",
    "};",
    "",
    "const onboardingInterviewQuestions = [",
    "    {",
    "        id: 'experience',",
    "        prompt: 'What best matches your current experience level?',",
    "        options: [",
    "            { value: 'new', label: 'New' },",
    "            { value: 'builder', label: 'Builder' },",
    "            { value: 'expert', label: 'Expert' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'personality',",
    "        prompt: 'How should {{agent}} sound by default?',",
    "        options: [",
    "            { value: 'calm_guide', label: 'Calm guide' },",
    "            { value: 'balanced', label: 'Balanced' },",
    "            { value: 'direct_technical', label: 'Direct technical' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'autonomy',",
    "        prompt: 'How autonomous should {{agent}} be?',",
    "        options: [",
    "            { value: 'guided', label: 'Guided' },",
    "            { value: 'balanced', label: 'Balanced' },",
    "            { value: 'aggressive', label: 'Aggressive' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'cost_quality',",
    "        prompt: 'Cost vs quality preference?',",
    "        options: [",
    "            { value: 'low_cost', label: 'Low cost' },",
    "            { value: 'balanced', label: 'Balanced' },",
    "            { value: 'max_quality', label: 'Max quality' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'memory',",
    "        prompt: 'How should memory behave?',",
    "        options: [",
    "            { value: 'remember', label: 'Remember across sessions' },",
    "            { value: 'session_only', label: 'Only current session' },",
    "            { value: 'disabled', label: 'Disable memory' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'workflow',",
    "        prompt: 'What is your primary workflow?',",
    "        options: [",
    "            { value: 'build_features', label: 'Build features' },",
    "            { value: 'research', label: 'Research' },",
    "            { value: 'ops_reliability', label: 'Ops + reliability' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'default_toggles',",
    "        prompt: 'Pick a default toggle bundle.',",
    "        options: [",
    "            { value: 'safe_defaults', label: 'Safe defaults' },",
    "            { value: 'power_mode', label: 'Power mode' },",
    "            { value: 'quiet_mode', label: 'Quiet mode' },",
    "        ],",
    "    },",
    "];",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  EASY SETUP / ONBOARDING                                               ║",
    "// ║  Setup wizard, path cards, dependency checks, telemetry, choice bubbles ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function onboardingNowIso() {",
    "    return new Date().toISOString();",
    "}",
    "",
    "function createOnboardingTelemetrySessionId() {",
    "    try {",
    "        if (window.crypto && typeof window.crypto.randomUUID === 'function') {",
    "            return window.crypto.randomUUID();",
    "        }",
    "    } catch {",
    "        // Fallback below.",
    "    }",
    "    return `session_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;",
    "}",
    "",
    "function ensureOnboardingTelemetryClock() {",
    "    const now = Date.now();",
    "    if (!safeString(easySetupState.onboardingSessionId)) {",
    "        easySetupState.onboardingSessionId = createOnboardingTelemetrySessionId();",
    "    }",
    "    if (!Number.isFinite(Number(easySetupState.telemetryStartedAtMs)) || Number(easySetupState.telemetryStartedAtMs) <= 0) {",
    "        easySetupState.telemetryStartedAtMs = now;",
    "    }",
    "    const elapsed = Math.max(0, now - Number(easySetupState.telemetryStartedAtMs));",
    "    return {",
    "        onboarding_session_id: safeString(easySetupState.onboardingSessionId),",
    "        elapsed_ms: elapsed,",
    "    };",
    "}",
    "",
    "function isOnboardingSlashCommand(text) {",
    "    const normalized = safeString(text).toLowerCase();",
    "    return normalized === '/onboarding' || normalized === '/setup' || normalized === '/easy-setup';",
    "}",
    "",
    "function ensureChatVisible() {",
    "    if (isSettingsScreenOpen()) {",
    "        closeSettingsModal();",
    "    }",
    "    if (welcomeScreen) welcomeScreen.classList.add('hidden');",
    "    if (chatScrollArea) chatScrollArea.classList.remove('hidden');",
    "    setSidebarNavMode('chat');",
    "}",
    "",
    "async function fetchJsonSafe(url, options = {}) {",
    "    const response = await fetch(url, options);",
    "    let data = null;",
    "    let text = '';",
    "    try {",
    "        data = await response.json();",
    "    } catch {",
    "        try {",
    "            text = await response.text();",
    "        } catch {",
    "            text = '';",
    "        }",
    "    }",
    "    return { ok: response.ok, status: response.status, data, text };",
    "}",
    "",
    "function taskContinuityStatusLabel(statusRaw) {",
    "    const status = safeString(statusRaw).toLowerCase();",
    "    if (status === 'complete') return 'complete';",
    "    if (status === 'blocked') return 'blocked';",
    "    return 'in_progress';",
    "}",
    "",
    "function taskContinuityShouldBeVisible() {",
    "    if (!taskContinuityPanel) return false;",
    "    if (isSettingsScreenOpen()) return false;",
    "    return sidebarNavMode === 'chat' || sidebarNavMode === 'search';",
    "}",
    "",
    "function stopTaskContinuityAutoRefresh() {",
    "    if (taskContinuityAutoRefreshTimer) {",
    "        window.clearInterval(taskContinuityAutoRefreshTimer);",
    "        taskContinuityAutoRefreshTimer = 0;",
    "    }",
    "}",
    "",
    "function startTaskContinuityAutoRefresh() {",
    "    if (taskContinuityAutoRefreshTimer) return;",
    "    taskContinuityAutoRefreshTimer = window.setInterval(() => {",
    "        if (!taskContinuityShouldBeVisible()) return;",
    "        void refreshTaskContinuity();",
    "    }, TASK_CONTINUITY_REFRESH_INTERVAL_MS);",
    "}",
    "",
    "function renderTaskContinuity(state, events, sessionToken, { error = '' } = {}) {",
    "    if (!taskContinuityPanel) return;",
    "",
    "    const hasState = Boolean(state && typeof state === 'object');",
    "    const normalizedEvents = Array.isArray(events) ? events.slice(0, 6) : [];",
    "    const status = taskContinuityStatusLabel(hasState ? state.status : (error ? 'blocked' : 'in_progress'));",
    "    const activeGoal = hasState ? safeString(state.active_goal) : '';",
    "    const progress = hasState ? safeString(state.last_progress) : '';",
    "    const missingInputs = hasState && Array.isArray(state.missing_inputs) ? state.missing_inputs.filter(Boolean) : [];",
    "    const updatedAtRaw = hasState ? safeString(state.updated_at) : '';",
    "    const sessionLabelRaw = safeString(sessionToken);",
    "    const sessionLabel = sessionLabelRaw.length > 16 ? `${sessionLabelRaw.slice(0, 16)}…` : (sessionLabelRaw || '--');",
    "",
    "    if (hasState) {",
    "        taskContinuityLatestState = state;",
    "    }",
    "    if (normalizedEvents.length) {",
    "        taskContinuityLatestEvents = normalizedEvents;",
    "    }",
    "    if (sessionLabelRaw) {",
    "        taskContinuityLatestSessionId = sessionLabelRaw;",
    "    }",
    "",
    "    if (taskContinuityStatusPill) {",
    "        taskContinuityStatusPill.textContent = status;",
    "        taskContinuityStatusPill.classList.remove('is-complete', 'is-blocked');",
    "        if (status === 'complete') taskContinuityStatusPill.classList.add('is-complete');",
    "        if (status === 'blocked') taskContinuityStatusPill.classList.add('is-blocked');",
    "    }",
    "",
    "    if (taskContinuityGoal) {",
    "        if (activeGoal) {",
    "            taskContinuityGoal.textContent = activeGoal;",
    "        } else if (error) {",
    "            taskContinuityGoal.textContent = 'Task continuity is temporarily unavailable.';",
    "        } else {",
    "            taskContinuityGoal.textContent = 'No active task tracked yet.';",
    "        }",
    "    }",
    "",
    "    if (taskContinuityProgress) {",
    "        if (progress) {",
    "            taskContinuityProgress.textContent = progress;",
    "        } else if (error) {",
    "            taskContinuityProgress.textContent = error;",
    "        } else {",
    "            taskContinuityProgress.textContent = 'Waiting for first update.';",
    "        }",
    "    }",
    "",
    "    if (taskContinuityBlockersWrap && taskContinuityBlockersList) {",
    "        taskContinuityBlockersWrap.classList.toggle('hidden', missingInputs.length === 0);",
    "        taskContinuityBlockersList.innerHTML = missingInputs",
    "            .map((item) => `<li>${escapeHtml(safeString(item))}</li>`)",
    "            .join('');",
    "    }",
    "",
    "    if (taskContinuityEventsList) {",
    "        if (normalizedEvents.length > 0) {",
    "            taskContinuityEventsList.classList.remove('hidden');",
    "            taskContinuityEventsList.innerHTML = normalizedEvents.map((entry) => {",
    "                const source = safeString(entry?.source).replace(/^chat\\./, '');",
    "                const line = safeString(entry?.last_progress);",
    "                const when = missionRelativeTime(entry?.created_at);",
    "                const text = [source || 'event', line].filter(Boolean).join(' | ');",
    "                const suffix = when && when !== '--' ? ` (${when})` : '';",
    "                return `<li title=\"${escapeHtml(text)}\">${escapeHtml(text)}${escapeHtml(suffix)}</li>`;",
    "            }).join('');",
    "        } else {",
    "            taskContinuityEventsList.classList.add('hidden');",
    "            taskContinuityEventsList.innerHTML = '';",
    "        }",
    "    }",
    "",
    "    if (taskContinuityUpdatedAt) {",
    "        taskContinuityUpdatedAt.textContent = updatedAtRaw ? `Updated ${missionRelativeTime(updatedAtRaw)}` : 'Not synced';",
    "    }",
    "    if (taskContinuitySession) {",
    "        taskContinuitySession.textContent = `Session: ${sessionLabel}`;",
    "    }",
    "}",
    "",
    "async function refreshTaskContinuity({ sessionOverride = '', force = false } = {}) {",
    "    if (taskContinuityInFlight && !force) return;",
    "",
    "    const sid = safeString(sessionOverride || sessionId || activeChatId || taskContinuityLatestSessionId);",
    "    const currentUrl = sid",
    "        ? `/api/task-ledger/current?session_id=${encodeURIComponent(sid)}`",
    "        : '/api/task-ledger/current';",
    "    const historyUrl = sid",
    "        ? `/api/task-ledger/history?session_id=${encodeURIComponent(sid)}&limit=6`",
    "        : '/api/task-ledger/history?limit=6';",
    "",
    "    taskContinuityInFlight = true;",
    "    if (taskContinuityRefreshBtn) taskContinuityRefreshBtn.disabled = true;",
    "    try {",
    "        const [currentResp, historyResp] = await Promise.all([",
    "            fetchJsonSafe(currentUrl),",
    "            fetchJsonSafe(historyUrl),",
    "        ]);",
    "        if (!currentResp.ok || !historyResp.ok) {",
    "            throw new Error('Unable to refresh task continuity right now.');",
    "        }",
    "        const currentPayload = currentResp.data && typeof currentResp.data === 'object' ? currentResp.data : {};",
    "        const historyPayload = historyResp.data && typeof historyResp.data === 'object' ? historyResp.data : {};",
    "        const state = currentPayload.state && typeof currentPayload.state === 'object' ? currentPayload.state : null;",
    "        const events = Array.isArray(historyPayload.events) ? historyPayload.events : [];",
    "        const resolvedSid = safeString(currentPayload.session_id || historyPayload.session_id || sid);",
    "        renderTaskContinuity(state, events, resolvedSid);",
    "    } catch (error) {",
    "        const fallbackState = taskContinuityLatestState;",
    "        const fallbackEvents = taskContinuityLatestEvents;",
    "        const fallbackSid = safeString(taskContinuityLatestSessionId || sid);",
    "        renderTaskContinuity(fallbackState, fallbackEvents, fallbackSid, {",
    "            error: safeString(error?.message) || 'Sync failed.',",
    "        });",
    "    } finally {",
    "        taskContinuityInFlight = false;",
    "        if (taskContinuityRefreshBtn) taskContinuityRefreshBtn.disabled = false;",
    "        taskContinuityPanel.classList.toggle('hidden', !taskContinuityShouldBeVisible());",
    "    }",
    "}",
    "",
    "function updateTaskContinuityVisibility({ refresh = false } = {}) {",
    "    if (!taskContinuityPanel) return;",
    "    const visible = taskContinuityShouldBeVisible();",
    "    taskContinuityPanel.classList.toggle('hidden', !visible);",
    "    if (!visible) {",
    "        stopTaskContinuityAutoRefresh();",
    "        return;",
    "    }",
    "    startTaskContinuityAutoRefresh();",
    "    if (refresh) {",
    "        void refreshTaskContinuity({ force: true });",
    "    }",
    "}",
    "",
    "async function emitOnboardingTelemetry(eventName, payload = {}) {",
    "    const normalized = safeString(eventName);",
    "    if (!normalized) return;",
    "    const basePayload = payload && typeof payload === 'object' ? { ...payload } : {};",
    "    const telemetryTiming = ensureOnboardingTelemetryClock();",
    "    if (!safeString(basePayload.onboarding_session_id)) {",
    "        basePayload.onboarding_session_id = telemetryTiming.onboarding_session_id;",
    "    }",
    "    if (!Number.isFinite(Number(basePayload.elapsed_ms))) {",
    "        basePayload.elapsed_ms = telemetryTiming.elapsed_ms;",
    "    }",
    "    try {",
    "        await fetch('/api/onboarding/telemetry', {",
    "            method: 'POST',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({",
    "                event: normalized,",
    "                payload: basePayload,",
    "            }),",
    "        });",
    "    } catch {",
    "        // Best-effort telemetry only.",
    "    }",
    "}",
    "",
    "function getOnboardingFromPrefs() {",
    "    return currentPreferences?.onboarding || {};",
    "}",
    "",
    "function isOnboardingComplete() {",
    "    return Boolean(getOnboardingFromPrefs()?.setup_completed);",
    "}",
    "",
    "function mapRecommendedPath(bootstrap) {",
    "    const recommended = safeString(bootstrap?.quick_start?.recommended_path).toLowerCase();",
    "    if (recommended === 'codex') return 'codex';",
    "    if (recommended === 'local') return 'local';",
    "    if (recommended === 'cloud') return 'manual';",
    "    return '';",
    "}",
    "",
    "function easySetupStepName(step) {",
    "    if (step <= 1) return 'choose_path';",
    "    if (step === 2) return 'connect';",
    "    if (step === 3) return 'downloads';",
    "    if (step === 4) return 'brain_ready';",
    "    return 'choose_path';",
    "}",
    "",
    "function stepFromOnboardingName(nameRaw) {",
    "    const name = safeString(nameRaw).toLowerCase();",
    "    if (name === 'connect') return 2;",
    "    if (name === 'downloads') return 3;",
    "    if (name === 'brain_ready') return 4;",
    "    if (name === 'interview' || name === 'completed') return 4;",
    "    return 1;",
    "}",
    "",
    "function setEasySetupStatus(targetEl, text, tone = '') {",
    "    if (!targetEl) return;",
    "    targetEl.textContent = safeString(text);",
    "    targetEl.classList.remove('ok', 'error');",
    "    if (tone === 'ok') targetEl.classList.add('ok');",
    "    if (tone === 'error') targetEl.classList.add('error');",
    "    if (tone === 'error') {",
    "        notifyUser(targetEl.textContent, {",
    "            tone: 'error',",
    "            durationMs: 3400,",
    "        });",
    "    }",
    "}",
    "",
    "function hideAssistantSuggestions({ force = false } = {}) {",
    "    if (!assistantSuggestionRail || !assistantSuggestionBubbles) return;",
    "    if (!force && !suggestionDismissible) return;",
    "    _stopSuggestionAutoScroll();",
    "    suggestionRailVersion += 1;",
    "    suggestionContext = '';",
    "    suggestionDismissible = true;",
    "    assistantSuggestionBubbles.innerHTML = '';",
    "    assistantSuggestionRail.classList.add('hidden');",
    "    assistantSuggestionRail.removeAttribute('data-context');",
    "    if (assistantSuggestionTitle) assistantSuggestionTitle.textContent = 'Suggestions';",
    "    if (assistantSuggestionDismissBtn) assistantSuggestionDismissBtn.classList.add('hidden');",
    "}",
    "",
    "// CSS marquee handles the scrolling animation via .assistant-suggestion-track",
    "// These are kept as no-ops for any callers that reference them",
    "function _startSuggestionAutoScroll() {}",
    "function _stopSuggestionAutoScroll() {}",
    "",
    "function setAssistantSuggestions({ title = 'Suggestions', options = [], context = 'general', dismissible = true } = {}) {",
    "    if (!assistantSuggestionRail || !assistantSuggestionBubbles) return;",
    "    // Don't show suggestions while the model is generating",
    "    if (isGenerating) return;",
    "",
    "    const validOptions = (Array.isArray(options) ? options : []).filter((option) => {",
    "        return Boolean(safeString(option?.label) || safeString(option?.value));",
    "    });",
    "    if (validOptions.length === 0) {",
    "        hideAssistantSuggestions({ force: true });",
    "        return;",
    "    }"
].join("\n");
