/* split from part-022.js */
export default [
    "                    ['inc', 'Increment'],",
    "                    ['append_tag', 'Append tag'],",
    "                    ['delete', 'Delete'],",
    "                ].map(([value, label]) => `<option value=\"${value}\"${safeString(node.properties?.operation) === value ? ' selected' : ''}>${label}</option>`).join('')}</select></label>",
    "                <label class=\"module-wb-field\">Channel<input type=\"text\" data-flow-prop=\"channel\" value=\"${escapeHtml(safeString(node.properties?.channel) || 'inbox')}\" /></label>",
    "                <label class=\"module-wb-field module-wb-field-check\"><input type=\"checkbox\" data-flow-prop=\"autoApprove\" ${node.properties?.autoApprove ? 'checked' : ''} />Auto-approve gate</label>",
    "                <label class=\"module-wb-field module-wb-field-wide\">Notes<textarea rows=\"5\" data-flow-prop=\"notes\">${escapeHtml(safeString(node.properties?.notes))}</textarea></label>",
    "                <label class=\"module-wb-field module-wb-field-wide\">Message Template<textarea rows=\"3\" data-flow-prop=\"template\">${escapeHtml(safeString(node.properties?.template) || 'Workflow alert: {{subject}}')}</textarea></label>",
    "            </div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"duplicate\">Duplicate</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"delete\">Delete</button>",
    "            </div>",
    "        `;",
    "    };",
    "",
    "    palette.innerHTML = blockDefs.map((block) => `<button type=\"button\" class=\"module-wb-palette-btn\" data-flow-node-type=\"${block.id}\"><strong>${block.label}</strong><span>${block.kind}</span></button>`).join('');",
    "",
    "    if (wb.graphData?.nodes?.length) {",
    "        try {",
    "            graph.configure(wb.graphData);",
    "        } catch (_error) {",
    "            wb.graphData = null;",
    "        }",
    "    }",
    "    if (!graphNodes().length) {",
    "        const trigger = createNode(blockDefs[0], [80, 140]);",
    "        const action = createNode(blockDefs[4], [420, 140]);",
    "        if (trigger) graph.add(trigger);",
    "        if (action) graph.add(action);",
    "        if (trigger && action) trigger.connect(0, action, 0);",
    "    }",
    "    remember();",
    "    renderLogs();",
    "    renderReport();",
    "    renderProjectSelect();",
    "    renderStatus();",
    "    renderInspector();",
    "",
    "    graph.onAfterChange = () => {",
    "        remember();",
    "        renderStatus();",
    "        renderInspector();",
    "        renderProjectSelect();",
    "    };",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const projectActionEl = event.target instanceof Element",
    "            ? event.target.closest('[data-wb-project-action][data-wb-project-mode=\"automations\"]')",
    "            : null;",
    "        if (projectActionEl) {",
    "            const action = safeString(projectActionEl.dataset.wbProjectAction).toLowerCase();",
    "            const select = shell.querySelector('select[data-wb-project-select=\"automations\"]');",
    "            const input = shell.querySelector('input[data-wb-project-name=\"automations\"]');",
    "            const selectedId = safeString(select instanceof HTMLSelectElement ? select.value : wb.selectedProjectId);",
    "            if (action === 'save') {",
    "                remember();",
    "                const savedId = moduleWorkbenchProjectSave('automations', {",
    "                    graphData: wb.graphData || graph.serialize(),",
    "                    runInput: wb.runInput,",
    "                }, safeString(input instanceof HTMLInputElement ? input.value : ''));",
    "                wb.selectedProjectId = savedId;",
    "                if (input instanceof HTMLInputElement) input.value = '';",
    "                moduleWorkbenchPushLog(wb.logs, 'Saved flow project.', 'ok', 80, 'flow-log');",
    "                renderLogs();",
    "                renderProjectSelect();",
    "                return;",
    "            }",
    "            if (action === 'load') {",
    "                if (!selectedId) return;",
    "                const project = moduleWorkbenchProjectGet('automations', selectedId);",
    "                if (!project?.payload) return;",
    "                const payload = project.payload;",
    "                graph.clear();",
    "                wb.graphData = payload.graphData && typeof payload.graphData === 'object' ? payload.graphData : null;",
    "                if (wb.graphData?.nodes?.length) {",
    "                    try {",
    "                        graph.configure(wb.graphData);",
    "                    } catch (_error) {",
    "                        wb.graphData = null;",
    "                    }",
    "                }",
    "                wb.runInput = safeString(payload.runInput) || wb.runInput;",
    "                if (runInputEl instanceof HTMLTextAreaElement) runInputEl.value = wb.runInput;",
    "                wb.selectedProjectId = selectedId;",
    "                remember();",
    "                moduleWorkbenchPushLog(wb.logs, `Loaded project: ${safeString(project.name)}.`, 'ok', 80, 'flow-log');",
    "                renderLogs();",
    "                renderStatus();",
    "                renderInspector();",
    "                renderProjectSelect();",
    "                return;",
    "            }",
    "            if (action === 'delete') {",
    "                if (!selectedId) return;",
    "                if (moduleWorkbenchProjectDelete('automations', selectedId)) {",
    "                    wb.selectedProjectId = '';",
    "                    moduleWorkbenchPushLog(wb.logs, 'Deleted flow project.', 'warn', 80, 'flow-log');",
    "                    renderLogs();",
    "                    renderProjectSelect();",
    "                }",
    "                return;",
    "            }",
    "        }",
    "        const target = event.target instanceof Element ? event.target.closest('[data-flow-node-type], [data-flow-action]') : null;",
    "        if (!target) return;",
    "        const nodeType = safeString(target.dataset.flowNodeType);",
    "        const action = safeString(target.dataset.flowAction).toLowerCase();",
    "        if (nodeType) {",
    "            const def = blockDefs.find((block) => block.id === nodeType) || blockDefs[0];",
    "            const offset = graphNodes().length;",
    "            const node = createNode(def, [80 + (offset * 30), 100 + (offset * 20)]);",
    "            if (!node) return;",
    "            graph.add(node);",
    "            wb.selectedNodeId = safeString(node.id);",
    "            moduleWorkbenchPushLog(wb.logs, `Added ${def.label}.`, 'ok', 80, 'flow-log');",
    "            remember();",
    "            renderLogs();",
    "            renderStatus();",
    "            renderInspector();",
    "            return;",
    "        }",
    "        const node = selectedNode();",
    "        if (action === 'run') {",
    "            remember();",
    "            const run = moduleAutomationRunGraphData(wb.graphData || graph.serialize(), parseRunInput());",
    "            wb.runReport = run;",
    "            moduleWorkbenchPushLog(wb.logs, `Run completed: ${run.steps.length} step(s), ${run.outputs.length} output(s).`, 'ok', 80, 'flow-log');",
    "            renderLogs();",
    "            renderReport();",
    "            return;",
    "        }",
    "        if (action === 'run_dry') {",
    "            remember();",
    "            const run = moduleAutomationRunGraphData(wb.graphData || graph.serialize(), parseRunInput());",
    "            wb.runReport = {",
    "                ...run,",
    "                outputs: [],",
    "                steps: run.steps.map((step) => ({ ...step, note: `${safeString(step.note)} (dry run)` })),",
    "            };",
    "            moduleWorkbenchPushLog(wb.logs, `Dry run completed: ${run.steps.length} step(s).`, 'warn', 80, 'flow-log');",
    "            renderLogs();",
    "            renderReport();",
    "            return;",
    "        }",
    "        if (action === 'export') {",
    "            remember();",
    "            moduleWorkbenchCopyJson(wb.graphData || graph.serialize(), 'Automation Flow JSON');",
    "            return;",
    "        }",
    "        if (action === 'export_n8n') {",
    "            remember();",
    "            moduleWorkbenchCopyJson(moduleWorkbenchFlowToN8n(wb.graphData || graph.serialize()), 'n8n Workflow JSON');",
    "            return;",
    "        }",
    "        if (action === 'export_nodered') {",
    "            remember();",
    "            moduleWorkbenchCopyJson(moduleWorkbenchFlowToNodeRed(wb.graphData || graph.serialize()), 'Node-RED Flow JSON');",
    "            return;",
    "        }",
    "        if (action === 'reset') {",
    "            graph.clear();",
    "            wb.graphData = null;",
    "            wb.selectedNodeId = '';",
    "            wb.logs = [];",
    "            wb.runReport = null;",
    "            renderLogs();",
    "            renderReport();",
    "            renderStatus();",
    "            renderInspector();",
    "            return;",
    "        }",
    "        if (action === 'duplicate' && node) {",
    "            const clone = createNode({",
    "                id: safeString(node.properties?.blockType) || 'custom',",
    "                kind: safeString(node.properties?.kind) || 'action',",
    "                label: `${safeString(node.title) || 'Block'} Copy`,",
    "            }, [Number(node.pos?.[0] || 80) + 42, Number(node.pos?.[1] || 80) + 32]);",
    "            if (!clone) return;",
    "            clone.properties.notes = safeString(node.properties?.notes);",
    "            clone.properties.approval = Boolean(node.properties?.approval);",
    "            clone.properties.field = safeString(node.properties?.field);",
    "            clone.properties.op = safeString(node.properties?.op) || 'equals';",
    "            clone.properties.value = safeString(node.properties?.value);",
    "            clone.properties.template = safeString(node.properties?.template);",
    "            clone.properties.operation = safeString(node.properties?.operation) || 'set';",
    "            clone.properties.channel = safeString(node.properties?.channel) || 'inbox';",
    "            clone.properties.autoApprove = Boolean(node.properties?.autoApprove);",
    "            graph.add(clone);",
    "            wb.selectedNodeId = safeString(clone.id);",
    "            remember();",
    "            renderStatus();",
    "            renderInspector();",
    "            return;",
    "        }",
    "        if (action === 'delete' && node) {",
    "            graph.remove(node);",
    "            wb.selectedNodeId = '';",
    "            remember();",
    "            renderStatus();",
    "            renderInspector();",
    "        }",
    "    });",
    "",
    "    inspector.addEventListener('input', (event) => {",
    "        const target = event.target;",
    "        if (!(target instanceof HTMLInputElement || target instanceof HTMLSelectElement || target instanceof HTMLTextAreaElement)) return;",
    "        const node = selectedNode();",
    "        if (!node) return;",
    "        const prop = safeString(target.dataset.flowProp);",
    "        if (!prop) return;",
    "        if (prop === 'title') node.title = safeString(target.value).slice(0, 90);",
    "        if (prop === 'kind') node.properties.kind = safeString(target.value);",
    "        if (prop === 'notes') node.properties.notes = safeString(target.value).slice(0, 2200);",
    "        if (prop === 'field') node.properties.field = safeString(target.value).slice(0, 140);",
    "        if (prop === 'op') node.properties.op = safeString(target.value);",
    "        if (prop === 'value') node.properties.value = safeString(target.value).slice(0, 400);",
    "        if (prop === 'template') node.properties.template = safeString(target.value).slice(0, 1800);",
    "        if (prop === 'operation') node.properties.operation = safeString(target.value);",
    "        if (prop === 'channel') node.properties.channel = safeString(target.value).slice(0, 80);",
    "        if (prop === 'approval' && target instanceof HTMLInputElement) node.properties.approval = target.checked;",
    "        if (prop === 'autoApprove' && target instanceof HTMLInputElement) node.properties.autoApprove = target.checked;",
    "        node.setDirtyCanvas(true, true);",
    "        remember();",
    "        renderStatus();",
    "        renderReport();",
    "    });",
    "",
    "    if (runInputEl instanceof HTMLTextAreaElement) {",
    "        runInputEl.addEventListener('input', () => {",
    "            wb.runInput = safeString(runInputEl.value);",
    "        });",
    "    }",
    "    const projectSelect = shell.querySelector('select[data-wb-project-select=\"automations\"]');",
    "    if (projectSelect instanceof HTMLSelectElement) {",
    "        projectSelect.addEventListener('change', () => {",
    "            wb.selectedProjectId = safeString(projectSelect.value);",
    "        });",
    "    }"
].join("\n");
