/* split from part-026.js */
export default [
    "        pathHint: 'C:/games/MyUnrealProject/MyGame.uproject',",
    "        launchLabel: 'Launch Unreal',",
    "    },",
    "    {",
    "        id: 'godot',",
    "        label: 'Godot',",
    "        tag: 'MIT',",
    "        summary: 'Fast open-source workflow and lightweight exports.',",
    "        pathHint: 'C:/games/MyGodotProject',",
    "        launchLabel: 'Launch Godot',",
    "    },",
    "    {",
    "        id: 'o3de',",
    "        label: 'O3DE',",
    "        tag: 'Open 3D',",
    "        summary: 'Large-scale simulation and advanced rendering stack.',",
    "        pathHint: 'C:/games/O3DE/Project',",
    "        launchLabel: 'Launch O3DE',",
    "    },",
    "    {",
    "        id: 'bevy',",
    "        label: 'Bevy',",
    "        tag: 'Rust',",
    "        summary: 'Data-driven ECS workflows for rapid prototypes.',",
    "        pathHint: 'C:/games/bevy-project',",
    "        launchLabel: 'Launch Bevy',",
    "    },",
    "    {",
    "        id: 'unity',",
    "        label: 'Unity',",
    "        tag: 'Connector',",
    "        summary: 'Connected through external editor bridge and CLI.',",
    "        pathHint: 'C:/games/UnityProject',",
    "        launchLabel: 'Launch Unity',",
    "    },",
    "    {",
    "        id: 'custom',",
    "        label: 'Custom Engine',",
    "        tag: 'SDK',",
    "        summary: 'Use Thomas plugin hooks for in-house runtimes.',",
    "        pathHint: 'C:/games/custom-engine',",
    "        launchLabel: 'Open Connector',",
    "    },",
    "];",
    "",
    "function moduleGameStudioEngineById(engineIdRaw) {",
    "    const engineId = safeString(engineIdRaw).toLowerCase();",
    "    return MODULE_GAME_ENGINE_CATALOG.find((engine) => safeString(engine.id) === engineId) || MODULE_GAME_ENGINE_CATALOG[0];",
    "}",
    "",
    "function moduleGameStudioProjectNormalize(projectRaw, fallbackId, engineIdRaw) {",
    "    const project = projectRaw && typeof projectRaw === 'object' ? projectRaw : {};",
    "    const engine = moduleGameStudioEngineById(engineIdRaw);",
    "    const id = safeString(project.id) || safeString(fallbackId) || `project-${Date.now()}`;",
    "    const pathValue = safeString(project.path) || safeString(engine.pathHint);",
    "    const tasks = Array.isArray(project.tasks)",
    "        ? project.tasks.map((item) => safeString(item)).filter(Boolean).slice(0, 8)",
    "        : [];",
    "    return {",
    "        id,",
    "        name: safeString(project.name) || 'Untitled Project',",
    "        path: pathValue,",
    "        status: safeString(project.status).toLowerCase() || 'planning',",
    "        focus: safeString(project.focus) || 'Define loop, player verbs, and build milestone.',",
    "        learning: safeString(project.learning) || 'Capture unknowns and test assumptions each run.',",
    "        tasks,",
    "        updatedAt: Number(project.updatedAt) || Date.now(),",
    "    };",
    "}",
    "",
    "function moduleGameStudioEnsureDirectorState(wb) {",
    "    if (!wb || typeof wb !== 'object') return;",
    "    wb.selectedEngine = safeString(wb.selectedEngine).toLowerCase() || 'unreal';",
    "    if (!MODULE_GAME_ENGINE_CATALOG.some((engine) => safeString(engine.id) === wb.selectedEngine)) {",
    "        wb.selectedEngine = 'unreal';",
    "    }",
    "    if (!wb.engineProjects || typeof wb.engineProjects !== 'object') wb.engineProjects = {};",
    "    if (!wb.activeProjectByEngine || typeof wb.activeProjectByEngine !== 'object') wb.activeProjectByEngine = {};",
    "    MODULE_GAME_ENGINE_CATALOG.forEach((engine, index) => {",
    "        const key = safeString(engine.id);",
    "        const seed = index === 0",
    "            ? [{",
    "                id: `${key}-project-1`,",
    "                name: key === 'unreal' ? 'Probe Arena' : `${engine.label} Prototype`,",
    "                path: safeString(engine.pathHint),",
    "                status: 'planning',",
    "                focus: 'Ship first playable slice with one clear objective.',",
    "                learning: 'Validate control feel and production velocity in week one.',",
    "                tasks: ['Define gameplay loop', 'Create graybox level', 'Run first playtest'],",
    "                updatedAt: Date.now(),",
    "            }]",
    "            : [];",
    "        const rowsRaw = Array.isArray(wb.engineProjects[key]) ? wb.engineProjects[key] : seed;",
    "        const seen = new Set();",
    "        wb.engineProjects[key] = rowsRaw",
    "            .map((row, rowIndex) => moduleGameStudioProjectNormalize(row, `${key}-project-${rowIndex + 1}`, key))",
    "            .filter((row) => {",
    "                if (seen.has(row.id)) return false;",
    "                seen.add(row.id);",
    "                return true;",
    "            })",
    "            .slice(0, 120);",
    "        const activeId = safeString(wb.activeProjectByEngine[key]);",
    "        if (!wb.engineProjects[key].some((row) => safeString(row.id) === activeId)) {",
    "            wb.activeProjectByEngine[key] = safeString(wb.engineProjects[key][0]?.id);",
    "        }",
    "    });",
    "    if (!Array.isArray(wb.studioChat)) wb.studioChat = [];",
    "    wb.studioChat = wb.studioChat",
    "        .map((msgRaw, index) => {",
    "            const msg = msgRaw && typeof msgRaw === 'object' ? msgRaw : {};",
    "            return {",
    "                id: safeString(msg.id) || `chat-${index + 1}`,",
    "                role: safeString(msg.role).toLowerCase() === 'assistant' ? 'assistant' : 'user',",
    "                text: safeString(msg.text).slice(0, 2200),",
    "                time: safeString(msg.time) || moduleWorkbenchTimeStamp(),",
    "            };",
    "        })",
    "        .slice(-40);",
    "    if (!wb.studioChat.length) {",
    "        wb.studioChat.push({",
    "            id: `chat-seed-${Date.now()}`,",
    "            role: 'assistant',",
    "            text: 'Game Studio ready. Pick an engine tile, pick a project, then tell Thomas what to build.',",
    "            time: moduleWorkbenchTimeStamp(),",
    "        });",
    "    }",
    "    wb.chatDraft = safeString(wb.chatDraft);",
    "    wb.projectDraftName = safeString(wb.projectDraftName);",
    "    wb.projectDraftPath = safeString(wb.projectDraftPath);",
    "    moduleGameStudioBridgeState(wb);",
    "}",
    "",
    "function moduleGameStudioCurrentProject(wb) {",
    "    const engineId = safeString(wb?.selectedEngine).toLowerCase();",
    "    const rows = Array.isArray(wb?.engineProjects?.[engineId]) ? wb.engineProjects[engineId] : [];",
    "    const activeId = safeString(wb?.activeProjectByEngine?.[engineId]);",
    "    return rows.find((row) => safeString(row.id) === activeId) || rows[0] || null;",
    "}",
    "",
    "function moduleGameStudioSetCurrentProject(wb, projectIdRaw) {",
    "    if (!wb || typeof wb !== 'object') return;",
    "    const engineId = safeString(wb.selectedEngine).toLowerCase();",
    "    const rows = Array.isArray(wb.engineProjects?.[engineId]) ? wb.engineProjects[engineId] : [];",
    "    const projectId = safeString(projectIdRaw);",
    "    if (!rows.some((row) => safeString(row.id) === projectId)) return;",
    "    wb.activeProjectByEngine[engineId] = projectId;",
    "}",
    "",
    "function moduleGameStudioAssistantReply(wb, promptRaw) {",
    "    const prompt = safeString(promptRaw).trim();",
    "    const engine = moduleGameStudioEngineById(wb?.selectedEngine);",
    "    const project = moduleGameStudioCurrentProject(wb);",
    "    const lower = prompt.toLowerCase();",
    "    const projectName = safeString(project?.name) || 'current project';",
    "    if (lower.includes('plan') || lower.includes('roadmap')) {",
    "        return [",
    "            `Plan locked for ${projectName} (${engine.label}).`,",
    "            '1) graybox core loop',",
    "            '2) playable objective',",
    "            '3) test pass + tuning',",
    "            '4) content expansion',",
    "        ].join('\\n');",
    "    }",
    "    if (lower.includes('launch') || lower.includes('open')) {",
    "        return `Ready to launch ${projectName}. Use Launch in the project card, then I can iterate from logs and playtest feedback.`;",
    "    }",
    "    if (lower.includes('build') || lower.includes('ship')) {",
    "        return `Build path for ${projectName}: run automated checks, package the build, then produce patch notes. Use Build in project actions to trigger command handoff.`;",
    "    }",
    "    if (lower.includes('learn') || lower.includes('research')) {",
    "        return `Learning track for ${projectName}: capture 3 references, define one mechanic benchmark, then run a proof scene by end of day.`;",
    "    }",
    "    return `Working in ${engine.label} on ${projectName}. I can plan features, generate tasks, launch tooling, and run build/playtest loops from this tab.`;",
    "}",
    "",
    "function moduleGameStudioOpenCommand(engineIdRaw, projectPathRaw, wb) {",
    "    const engine = moduleGameStudioEngineById(engineIdRaw);",
    "    const projectPath = safeString(projectPathRaw) || safeString(engine.pathHint);",
    "    if (safeString(engine.id) === 'unreal') {",
    "        wb.unrealProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).unrealOpen;",
    "    }",
    "    if (safeString(engine.id) === 'godot') {",
    "        wb.godotProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).godotOpen;",
    "    }",
    "    if (safeString(engine.id) === 'o3de') return `o3de.exe --project-path \"${projectPath}\"`;",
    "    if (safeString(engine.id) === 'bevy') return `cargo run --manifest-path \"${projectPath}/Cargo.toml\"`;",
    "    if (safeString(engine.id) === 'unity') return `Unity.exe -projectPath \"${projectPath}\"`;",
    "    return `thomas engine connect --engine custom --project \"${projectPath}\"`;",
    "}",
    "",
    "function moduleGameStudioBuildCommand(engineIdRaw, projectPathRaw, wb) {",
    "    const engine = moduleGameStudioEngineById(engineIdRaw);",
    "    const projectPath = safeString(projectPathRaw) || safeString(engine.pathHint);",
    "    if (safeString(engine.id) === 'unreal') {",
    "        wb.unrealProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).unrealBuild;",
    "    }",
    "    if (safeString(engine.id) === 'godot') {",
    "        wb.godotProjectPath = projectPath;",
    "        return moduleGameStudioCommands(wb).godotBuild;",
    "    }",
    "    if (safeString(engine.id) === 'o3de') return `cmake --build \"${projectPath}/build\" --config profile`;",
    "    if (safeString(engine.id) === 'bevy') return `cargo build --manifest-path \"${projectPath}/Cargo.toml\" --release`;",
    "    if (safeString(engine.id) === 'unity') return `Unity.exe -batchmode -quit -projectPath \"${projectPath}\" -buildWindows64Player \"${projectPath}/Builds/Game.exe\"`;",
    "    return `thomas engine build --engine custom --project \"${projectPath}\"`;",
    "}",
    "",
    "function moduleGameStudioGodotTscn(wb) {",
    "    const lines = [",
    "        '[gd_scene load_steps=2 format=3]',",
    "        '',",
    "        '[node name=\"ThomasLevel\" type=\"Node2D\"]',",
    "        '[node name=\"Platforms\" type=\"Node2D\" parent=\".\"]',",
    "        '[node name=\"Hazards\" type=\"Node2D\" parent=\".\"]',",
    "        '',",
    "    ];",
    "    const tile = 32;",
    "    for (let y = 0; y < wb.gridHeight; y += 1) {",
    "        for (let x = 0; x < wb.gridWidth; x += 1) {",
    "            const type = Number(wb.tiles?.[y]?.[x]) || 0;",
    "            const px = x * tile;",
    "            const py = y * tile;",
    "            if (type === 1) lines.push(`[node name=\"Platform_${x}_${y}\" type=\"StaticBody2D\" parent=\"Platforms\"]`, `position = Vector2(${px}, ${py})`, '');",
    "            if (type === 2) lines.push(`[node name=\"Hazard_${x}_${y}\" type=\"Area2D\" parent=\"Hazards\"]`, `position = Vector2(${px}, ${py})`, '');",
    "            if (type === 3) lines.push('[node name=\"Spawn\" type=\"Marker2D\" parent=\".\"]', `position = Vector2(${px}, ${py})`, '');",
    "            if (type === 4) lines.push('[node name=\"Goal\" type=\"Marker2D\" parent=\".\"]', `position = Vector2(${px}, ${py})`, '');",
    "        }",
    "    }",
    "    return lines.join('\\n');",
    "}",
    "",
    "function moduleGameStudioUnrealCsv(wb) {",
    "    const rows = ['x,y,type'];",
    "    for (let y = 0; y < wb.gridHeight; y += 1) {",
    "        for (let x = 0; x < wb.gridWidth; x += 1) {",
    "            const type = Number(wb.tiles?.[y]?.[x]) || 0;",
    "            if (!type) continue;"
].join("\n");
