/* app.js lines 8001-9000 */
export default [
    "    attachmentsPreview.querySelectorAll('.remove-btn').forEach(btn => {",
    "        btn.addEventListener('click', (e) => {",
    "            const type = e.target.getAttribute('data-type');",
    "            const idx = parseInt(e.target.getAttribute('data-index'), 10);",
    "            if (type === 'img') {",
    "                pendingImages.splice(idx - pendingDocs.length, 1);",
    "            } else {",
    "                pendingDocs.splice(idx, 1);",
    "            }",
    "            renderAttachmentsPreview();",
    "            composerTextarea.dispatchEvent(new Event('input')); // update button state",
    "        });",
    "    });",
    "    syncChatComposerOffset();",
    "}",
    "",
    "/* ── Toast helper ── */",
    "function showToast(msg, durationMs = 2000) {",
    "    if (!toastContainer) return;",
    "    const t = document.createElement('div');",
    "    t.className = 'toast';",
    "    t.textContent = msg;",
    "    toastContainer.appendChild(t);",
    "    setTimeout(() => t.remove(), durationMs + 300);",
    "}",
    "",
    "/* ── Code-block header injection (DOM walk, avoids sanitizer) ── */",
    "function addCodeBlockControls(container) {",
    "    container.querySelectorAll('pre > code').forEach(codeEl => {",
    "        const pre = codeEl.parentElement;",
    "        if (pre.parentElement && pre.parentElement.classList.contains('code-block-wrapper')) return;",
    "        // Detect language from class: could be \"language-python\", \"python\", or just \"hljs\"",
    "        const classes = [...codeEl.classList].filter(c => c !== 'hljs');",
    "        let lang = 'text';",
    "        for (const c of classes) {",
    "            if (c.startsWith('language-')) { lang = c.replace('language-', ''); break; }",
    "            if (c && c !== 'undefined' && c !== 'null') { lang = c; break; }",
    "        }",
    "        const wrapper = document.createElement('div');",
    "        wrapper.className = 'code-block-wrapper';",
    "        const header = document.createElement('div');",
    "        header.className = 'code-block-header';",
    "        header.innerHTML = `<span class=\"code-block-lang\">${escapeHtml(lang)}</span><button class=\"code-block-copy\" title=\"Copy code\"><i class=\"ph ph-copy\"></i> Copy</button>`;",
    "        pre.parentNode.insertBefore(wrapper, pre);",
    "        wrapper.appendChild(header);",
    "        wrapper.appendChild(pre);",
    "    });",
    "}",
    "",
    "/**",
    " * Render a message bubble into the stream",
    " */",
    "function renderMessage(msg) {",
    "    const isUser = msg.role === 'user';",
    "    const row = document.createElement('div');",
    "    row.className = 'message-row';",
    "    if (msg.id) {",
    "        row.id = String(msg.id);",
    "    }",
    "",
    "    const avatar = document.createElement('div');",
    "    avatar.className = `avatar ${isUser ? 'user' : 'assistant'}`;",
    "    if (isUser) {",
    "        avatar.textContent = 'U';",
    "    } else {",
    "        const icon = document.createElement('i');",
    "        icon.className = 'ph ph-sparkle';",
    "        avatar.appendChild(icon);",
    "    }",
    "",
    "    const content = document.createElement('div');",
    "    content.className = 'message-content';",
    "    content.innerHTML = formatMarkdown(msg.content);",
    "",
    "    row.appendChild(avatar);",
    "    row.appendChild(content);",
    "",
    "    // Message action buttons (hover-visible)",
    "    const actions = document.createElement('div');",
    "    actions.className = 'message-actions';",
    "    if (isUser) {",
    "        actions.innerHTML = [",
    "            '<button class=\"msg-action-btn\" data-action=\"edit\" title=\"Edit message\"><i class=\"ph ph-pencil-simple\"></i></button>',",
    "            '<button class=\"msg-action-btn\" data-action=\"copy\" title=\"Copy message\"><i class=\"ph ph-copy\"></i></button>',",
    "            '<button class=\"msg-action-btn\" data-action=\"pin\" title=\"Pin message\"><i class=\"ph ph-push-pin\"></i></button>',",
    "        ].join('');",
    "    } else {",
    "        actions.innerHTML = [",
    "            '<button class=\"msg-action-btn\" data-action=\"copy\" title=\"Copy message\"><i class=\"ph ph-copy\"></i></button>',",
    "            '<button class=\"msg-action-btn\" data-action=\"regenerate\" title=\"Regenerate response\"><i class=\"ph ph-arrows-clockwise\"></i></button>',",
    "            '<button class=\"msg-action-btn\" data-action=\"pin\" title=\"Pin message\"><i class=\"ph ph-push-pin\"></i></button>',",
    "        ].join('');",
    "    }",
    "    row.appendChild(actions);",
    "",
    "    chatMessagesInner.appendChild(row);",
    "",
    "    // Scroll to bottom",
    "    chatScrollArea.scrollTo({ top: chatScrollArea.scrollHeight, behavior: 'smooth' });",
    "",
    "    // Apply highlighting to new code blocks, then add header controls",
    "    chatMessagesInner.lastElementChild.querySelectorAll('pre code').forEach((el) => {",
    "        hljs.highlightElement(el);",
    "    });",
    "    addCodeBlockControls(content);",
    "    updateDebugDockSnapshot();",
    "}",
    "",
    "function updateMessage(id, newContent, isStreaming = true) {",
    "    const row = document.getElementById(id);",
    "    if (!row) return;",
    "    const contentDiv = row.querySelector('.message-content');",
    "    if (contentDiv) {",
    "        // Preserve thinking summary if present (lives above markdown, includes tool cards)",
    "        const thinkingSummary = contentDiv.querySelector('.thinking-summary');",
    "        if (thinkingSummary) thinkingSummary.remove(); // detach temporarily",
    "",
    "        contentDiv.innerHTML = formatMarkdown(newContent);",
    "        contentDiv.querySelectorAll('pre code').forEach((el) => {",
    "            hljs.highlightElement(el);",
    "        });",
    "        addCodeBlockControls(contentDiv);",
    "",
    "        // Re-attach thinking summary at top",
    "        if (thinkingSummary) contentDiv.insertBefore(thinkingSummary, contentDiv.firstChild);",
    "",
    "        contentDiv.classList.remove('streaming-cursor');",
    "        chatScrollArea.scrollTo({ top: chatScrollArea.scrollHeight, behavior: 'smooth' });",
    "        updateDebugDockSnapshot();",
    "    }",
    "}",
    "",
    "/**",
    " * Configure Marked.js to wrap code blocks in our Custom \"Mac Style\" window",
    " */",
    "function formatMarkdown(text) {",
    "    const renderer = new marked.Renderer();",
    "    renderer.code = function (code, language) {",
    "        const validLang = !!(language && hljs.getLanguage(language));",
    "        const highlighted = validLang ? hljs.highlight(code, { language }).value : escapeHtml(code);",
    "        const langClass = validLang ? language : '';",
    "        return `<pre><code class=\"hljs${langClass ? ' ' + langClass : ''}\">${highlighted}</code></pre>`;",
    "    };",
    "    renderer.html = function (rawHtml) {",
    "        // Raw HTML in user/assistant messages is treated as text to block XSS.",
    "        return escapeHtml(rawHtml || '');",
    "    };",
    "",
    "    marked.setOptions({ renderer });",
    "    const rendered = marked.parse(String(text || ''));",
    "    return sanitizeRenderedHtml(rendered);",
    "}",
    "",
    "function sanitizeRenderedHtml(html) {",
    "    const template = document.createElement('template');",
    "    template.innerHTML = String(html || '');",
    "",
    "    const blockedTags = new Set([",
    "        'SCRIPT', 'STYLE', 'IFRAME', 'OBJECT', 'EMBED', 'LINK', 'META', 'BASE',",
    "        'FORM', 'INPUT', 'BUTTON', 'TEXTAREA', 'SELECT', 'OPTION'",
    "    ]);",
    "    const urlAttrs = new Set(['href', 'src', 'xlink:href']);",
    "    const allowDataImage = new Set(['IMG']);",
    "    const elements = template.content.querySelectorAll('*');",
    "    for (const el of elements) {",
    "        const tag = String(el.tagName || '').toUpperCase();",
    "        if (blockedTags.has(tag)) {",
    "            el.remove();",
    "            continue;",
    "        }",
    "        for (const attr of [...el.attributes]) {",
    "            const name = String(attr.name || '').toLowerCase();",
    "            const value = String(attr.value || '');",
    "            if (name.startsWith('on') || name === 'style' || name === 'srcdoc') {",
    "                el.removeAttribute(attr.name);",
    "                continue;",
    "            }",
    "            if (urlAttrs.has(name)) {",
    "                const safe = sanitizeUrl(value, allowDataImage.has(tag));",
    "                if (safe === null) {",
    "                    el.removeAttribute(attr.name);",
    "                } else {",
    "                    el.setAttribute(attr.name, safe);",
    "                }",
    "            }",
    "        }",
    "        if (tag === 'A') {",
    "            el.setAttribute('rel', 'noopener noreferrer nofollow');",
    "            if (!el.getAttribute('target')) {",
    "                el.setAttribute('target', '_blank');",
    "            }",
    "        }",
    "    }",
    "    return template.innerHTML;",
    "}",
    "",
    "function sanitizeUrl(raw, allowDataImage = false) {",
    "    const value = String(raw || '').trim();",
    "    if (!value) return null;",
    "    if (value.startsWith('#') || value.startsWith('/')) return value;",
    "    try {",
    "        const parsed = new URL(value, window.location.origin);",
    "        const protocol = String(parsed.protocol || '').toLowerCase();",
    "        if (protocol === 'http:' || protocol === 'https:' || protocol === 'mailto:' || protocol === 'tel:') {",
    "            return parsed.href;",
    "        }",
    "        if (allowDataImage && protocol === 'data:' && /^data:image\\//i.test(value)) {",
    "            return value;",
    "        }",
    "    } catch (e) {",
    "        return null;",
    "    }",
    "    return null;",
    "}",
    "",
    "function escapeHtml(unsafe) {",
    "    return String(unsafe || '')",
    "        .replace(/&/g, \"&amp;\")",
    "        .replace(/</g, \"&lt;\")",
    "        .replace(/>/g, \"&gt;\")",
    "        .replace(/\"/g, \"&quot;\")",
    "        .replace(/'/g, \"&#039;\");",
    "}",
    "",
    "function safeString(value) {",
    "    return String(value || '').trim();",
    "}",
    "",
    "function sleepMs(ms) {",
    "    return new Promise((resolve) => {",
    "        window.setTimeout(resolve, Math.max(0, Number(ms) || 0));",
    "    });",
    "}",
    "",
    "function normalizeNotificationMessage(message) {",
    "    return safeString(message).replace(/\\s+/g, ' ');",
    "}",
    "",
    "function robotAlertVariantFromTone(tone = 'info') {",
    "    const normalized = safeString(tone).toLowerCase();",
    "    if (normalized === 'success' || normalized === 'ok') return 'variant-mint';",
    "    if (normalized === 'error' || normalized === 'danger') return 'variant-pink';",
    "    if (normalized === 'warning' || normalized === 'warn') return 'variant-orange';",
    "    return 'variant-blue';",
    "}",
    "",
    "function queueRobotAlert(message, { tone = 'info', durationMs = 0, dedupeMs = 3500 } = {}) {",
    "    if (!robotAlertStage || !robotAlertBot || !robotAlertBubble) return false;",
    "    const normalized = normalizeNotificationMessage(message);",
    "    if (!normalized) return false;",
    "",
    "    const now = Date.now();",
    "    if (normalized === robotAlertLastMessage && now - robotAlertLastAt < dedupeMs) {",
    "        return false;",
    "    }",
    "",
    "    robotAlertLastMessage = normalized;",
    "    robotAlertLastAt = now;",
    "    robotAlertQueue.push({",
    "        message: normalized,",
    "        tone: safeString(tone).toLowerCase() || 'info',",
    "        durationMs: Number(durationMs) || 0,",
    "    });",
    "    if (robotAlertQueue.length > 8) {",
    "        robotAlertQueue = robotAlertQueue.slice(robotAlertQueue.length - 8);",
    "    }",
    "",
    "    if (!robotAlertShowing) {",
    "        void processRobotAlertQueue();",
    "    }",
    "    return true;",
    "}",
    "",
    "async function processRobotAlertQueue() {",
    "    if (robotAlertShowing) return;",
    "    if (!robotAlertStage || !robotAlertBot || !robotAlertBubble) return;",
    "    robotAlertShowing = true;",
    "",
    "    const variantClasses = ['variant-blue', 'variant-mint', 'variant-pink', 'variant-orange'];",
    "",
    "    try {",
    "        while (robotAlertQueue.length) {",
    "            const next = robotAlertQueue.shift();",
    "            if (!next) continue;",
    "",
    "            const tone = safeString(next.tone).toLowerCase() || 'info';",
    "            const variant = robotAlertVariantFromTone(tone);",
    "            robotAlertBot.classList.remove(...variantClasses);",
    "            robotAlertBot.classList.add(variant);",
    "",
    "            robotAlertBubble.textContent = next.message;",
    "",
    "            robotAlertStage.classList.remove('exit', 'talking');",
    "            robotAlertStage.classList.add('active');",
    "            robotAlertBot.classList.add('walking');",
    "",
    "            await sleepMs(500);",
    "            robotAlertBot.classList.remove('walking');",
    "            robotAlertStage.classList.add('talking');",
    "",
    "            const readingMs = Math.max(1900, Math.min(5600, 900 + (next.message.length * 28)));",
    "            const holdMs = next.durationMs > 0 ? Math.max(900, next.durationMs) : readingMs;",
    "            await sleepMs(holdMs);",
    "",
    "            robotAlertStage.classList.remove('talking');",
    "            robotAlertStage.classList.add('exit');",
    "            robotAlertBot.classList.add('walking');",
    "",
    "            await sleepMs(520);",
    "            robotAlertBot.classList.remove('walking');",
    "            robotAlertStage.classList.remove('active', 'exit', 'talking');",
    "",
    "            await sleepMs(120);",
    "        }",
    "    } finally {",
    "        robotAlertShowing = false;",
    "    }",
    "}",
    "",
    "function notifyUser(message, { tone = 'info', durationMs = 0, dedupeMs = 3500, debugKind = '' } = {}) {",
    "    const normalized = normalizeNotificationMessage(message);",
    "    if (!normalized) return;",
    "    queueRobotAlert(normalized, { tone, durationMs, dedupeMs });",
    "    if (safeString(debugKind)) {",
    "        pushDebugEvent(debugKind, normalized);",
    "    }",
    "}",
    "",
    "function initialsFromName(nameOrEmail) {",
    "    const text = safeString(nameOrEmail);",
    "    if (!text) return 'U';",
    "    const words = text.replace(/@.*/, '').split(/[.\\s_-]+/).filter(Boolean);",
    "    if (words.length === 0) return 'U';",
    "    const first = words[0][0] || '';",
    "    const second = words.length > 1 ? words[1][0] : '';",
    "    return (first + second).toUpperCase() || 'U';",
    "}",
    "",
    "function setAvatarVisual(el, { text = 'U', imageUrl = '' } = {}) {",
    "    if (!el) return;",
    "    if (safeString(imageUrl)) {",
    "        el.style.backgroundImage = `url(\"${imageUrl}\")`;",
    "        el.textContent = '';",
    "    } else {",
    "        el.style.backgroundImage = '';",
    "        el.textContent = text;",
    "    }",
    "}",
    "",
    "function resolveDisplayName(preferences, codexStatus) {",
    "    const prefName = safeString(preferences?.profile?.display_name);",
    "    if (prefName) return prefName;",
    "    const codexName = safeString(codexStatus?.display_name);",
    "    if (codexName) return codexName;",
    "    const email = safeString(codexStatus?.email);",
    "    return email || 'User';",
    "}",
    "",
    "function sanitizeAgentNameInput(value) {",
    "    return safeString(value).replace(/\\s+/g, ' ').slice(0, 64);",
    "}",
    "",
    "function normalizeAgentName(value) {",
    "    const normalized = sanitizeAgentNameInput(value);",
    "    return normalized || DEFAULT_AGENT_NAME;",
    "}",
    "",
    "function resolveAgentName(preferences) {",
    "    const prefName = safeString(preferences?.profile?.display_name);",
    "    return normalizeAgentName(prefName || activeAgentName);",
    "}",
    "",
    "function getAgentName() {",
    "    return normalizeAgentName(activeAgentName || resolveAgentName(currentPreferences));",
    "}",
    "",
    "function withAgentName(templateRaw) {",
    "    const template = safeString(templateRaw);",
    "    if (!template) return '';",
    "    return template.replace(/\\{\\{\\s*agent\\s*\\}\\}/gi, getAgentName());",
    "}",
    "",
    "function applyAgentIdentityToDom(nameRaw = '') {",
    "    const agentName = normalizeAgentName(nameRaw || resolveAgentName(currentPreferences));",
    "    activeAgentName = agentName;",
    "",
    "    document.querySelectorAll('[data-agent-template]').forEach((el) => {",
    "        const template = safeString(el.getAttribute('data-agent-template'));",
    "        if (!template) return;",
    "        el.textContent = template.replace(/\\{\\{\\s*agent\\s*\\}\\}/gi, agentName);",
    "    });",
    "",
    "    document.querySelectorAll('[data-agent-placeholder-template]').forEach((el) => {",
    "        if (!('placeholder' in el)) return;",
    "        const template = safeString(el.getAttribute('data-agent-placeholder-template'));",
    "        if (!template) return;",
    "        el.placeholder = template.replace(/\\{\\{\\s*agent\\s*\\}\\}/gi, agentName);",
    "    });",
    "",
    "    document.querySelectorAll('[data-agent-aria-label-template]').forEach((el) => {",
    "        const template = safeString(el.getAttribute('data-agent-aria-label-template'));",
    "        if (!template) return;",
    "        el.setAttribute('aria-label', template.replace(/\\{\\{\\s*agent\\s*\\}\\}/gi, agentName));",
    "    });",
    "}",
    "",
    "function resolveAvatarUrl(preferences, codexStatus) {",
    "    const prefAvatar = safeString(preferences?.profile?.avatar_url);",
    "    if (prefAvatar) return prefAvatar;",
    "    return safeString(codexStatus?.avatar_url);",
    "}",
    "",
    "function updateSidebarIdentity() {",
    "    const name = resolveAgentName(currentPreferences);",
    "    const avatarUrl = resolveAvatarUrl(currentPreferences, currentCodexStatus);",
    "    setAvatarVisual(sidebarUserAvatar, {",
    "        text: initialsFromName(name),",
    "        imageUrl: avatarUrl,",
    "    });",
    "    applyAgentIdentityToDom(name);",
    "}",
    "",
    "function applyInterfaceMotionPreference() {",
    "    const animationsEnabled = currentPreferences?.advanced?.interface?.animations_enabled;",
    "    const allowMotion = animationsEnabled === undefined ? true : Boolean(animationsEnabled);",
    "    if (appRoot) appRoot.classList.toggle('no-motion', !allowMotion);",
    "}",
    "",
    "function readThemeName() {",
    "    const value = safeString(getComputedStyle(document.documentElement).getPropertyValue('--theme-name'));",
    "    return value.replace(/^[\"']|[\"']$/g, '') || 'Default';",
    "}",
    "",
    "function formatDebugTime(stamp = Date.now()) {",
    "    try {",
    "        return new Date(stamp).toLocaleTimeString([], { hour12: false });",
    "    } catch {",
    "        return '';",
    "    }",
    "}",
    "",
    "function formatDebugValue(value) {",
    "    if (value instanceof Error) {",
    "        return `${value.name}: ${value.message}`;",
    "    }",
    "    if (typeof value === 'string') return value;",
    "    if (typeof value === 'number' || typeof value === 'boolean' || value === null || value === undefined) {",
    "        return String(value);",
    "    }",
    "    try {",
    "        return JSON.stringify(value);",
    "    } catch {",
    "        try {",
    "            return String(value);",
    "        } catch {",
    "            return '[unserializable]';",
    "        }",
    "    }",
    "}",
    "",
    "function normalizeDebugUrl(input) {",
    "    if (typeof input === 'string') return input;",
    "    if (typeof URL !== 'undefined' && input instanceof URL) return input.toString();",
    "    if (typeof Request !== 'undefined' && input instanceof Request) return safeString(input.url);",
    "    if (input && typeof input === 'object' && 'url' in input) return safeString(input.url);",
    "    return '';",
    "}",
    "",
    "function shortDebugUrl(url) {",
    "    const raw = safeString(url);",
    "    if (!raw) return '-';",
    "    try {",
    "        const parsed = new URL(raw, window.location.origin);",
    "        return `${parsed.pathname}${parsed.search}` || parsed.toString();",
    "    } catch {",
    "        return raw;",
    "    }",
    "}",
    "",
    "function setActiveDebugTab(tabRaw = 'runtime') {",
    "    const normalized = DEBUG_TAB_SEQUENCE.includes(safeString(tabRaw))",
    "        ? safeString(tabRaw)",
    "        : 'runtime';",
    "    activeDebugTab = normalized;",
    "",
    "    const tabButtons = [",
    "        debugTabRuntime,",
    "        debugTabSystem,",
    "        debugTabModels,",
    "        debugTabTools,",
    "        debugTabMemory,",
    "        debugTabRuns,",
    "        debugTabEvents,",
    "        debugTabConsole,",
    "        debugTabNetwork,",
    "    ];",
    "    tabButtons.forEach((button) => {",
    "        if (!button) return;",
    "        const isActive = safeString(button.dataset.debugTab) === normalized;",
    "        button.classList.toggle('active', isActive);",
    "        button.setAttribute('aria-selected', isActive ? 'true' : 'false');",
    "        button.setAttribute('tabindex', isActive ? '0' : '-1');",
    "    });",
    "    const activeButton = tabButtons.find((button) => button && safeString(button.dataset.debugTab) === normalized);",
    "    if (activeButton && typeof activeButton.scrollIntoView === 'function') {",
    "        activeButton.scrollIntoView({ block: 'nearest', inline: 'nearest' });",
    "    }",
    "",
    "    const panels = [",
    "        debugPanelRuntime,",
    "        debugPanelSystem,",
    "        debugPanelModels,",
    "        debugPanelTools,",
    "        debugPanelMemory,",
    "        debugPanelRuns,",
    "        debugPanelEvents,",
    "        debugPanelConsole,",
    "        debugPanelNetwork,",
    "    ];",
    "    panels.forEach((panel) => {",
    "        if (!panel) return;",
    "        const isActive = safeString(panel.dataset.debugPanel) === normalized;",
    "        panel.classList.toggle('active', isActive);",
    "        panel.setAttribute('aria-hidden', isActive ? 'false' : 'true');",
    "    });",
    "",
    "    updateDebugDockSnapshot();",
    "    void refreshDebugLiveData({ reason: `tab:${normalized}` });",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  DEBUG DOCK                                                             ║",
    "// ║  Runtime, system, models, tools, memory, runs, console, network panels  ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function initDebugDockTabs() {",
    "    if (!debugDockTabs) return;",
    "    const tabButtons = [",
    "        debugTabRuntime,",
    "        debugTabSystem,",
    "        debugTabModels,",
    "        debugTabTools,",
    "        debugTabMemory,",
    "        debugTabRuns,",
    "        debugTabEvents,",
    "        debugTabConsole,",
    "        debugTabNetwork,",
    "    ];",
    "    tabButtons.forEach((button) => {",
    "        if (!button) return;",
    "        button.addEventListener('click', () => {",
    "            setActiveDebugTab(button.dataset.debugTab || 'runtime');",
    "        });",
    "        button.addEventListener('keydown', (event) => {",
    "            const current = tabButtons.filter(Boolean).indexOf(button);",
    "            if (current < 0) return;",
    "            if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') {",
    "                event.preventDefault();",
    "                const delta = event.key === 'ArrowRight' ? 1 : -1;",
    "                const next = (current + delta + tabButtons.length) % tabButtons.length;",
    "                const target = tabButtons[next];",
    "                if (target) {",
    "                    target.focus();",
    "                    setActiveDebugTab(target.dataset.debugTab || 'runtime');",
    "                }",
    "            } else if (event.key === 'Home') {",
    "                event.preventDefault();",
    "                const target = tabButtons[0];",
    "                if (target) {",
    "                    target.focus();",
    "                    setActiveDebugTab(target.dataset.debugTab || 'runtime');",
    "                }",
    "            } else if (event.key === 'End') {",
    "                event.preventDefault();",
    "                const target = tabButtons[tabButtons.length - 1];",
    "                if (target) {",
    "                    target.focus();",
    "                    setActiveDebugTab(target.dataset.debugTab || 'runtime');",
    "                }",
    "            }",
    "        });",
    "    });",
    "    setActiveDebugTab(activeDebugTab);",
    "}",
    "",
    "function debugRenderEmpty(target, message) {",
    "    if (!target) return;",
    "    target.innerHTML = '';",
    "    const empty = document.createElement('div');",
    "    empty.className = 'debug-empty';",
    "    empty.textContent = safeString(message) || 'No data available.';",
    "    target.appendChild(empty);",
    "}",
    "",
    "function debugCreateItemCard({ title = '', pill = '', pillTone = '', meta = [] } = {}) {",
    "    const row = document.createElement('article');",
    "    row.className = 'debug-item-card';",
    "",
    "    const head = document.createElement('div');",
    "    head.className = 'debug-item-head';",
    "",
    "    const heading = document.createElement('div');",
    "    heading.className = 'debug-item-title';",
    "    heading.textContent = safeString(title) || 'Item';",
    "    head.appendChild(heading);",
    "",
    "    if (safeString(pill)) {",
    "        const badge = document.createElement('span');",
    "        badge.className = 'debug-item-pill';",
    "        if (pillTone === 'ok' || pillTone === 'warn' || pillTone === 'error') {",
    "            badge.classList.add(pillTone);",
    "        }",
    "        badge.textContent = safeString(pill);",
    "        head.appendChild(badge);",
    "    }",
    "",
    "    row.appendChild(head);",
    "    (Array.isArray(meta) ? meta : []).forEach((line) => {",
    "        const text = safeString(line);",
    "        if (!text) return;",
    "        const body = document.createElement('div');",
    "        body.className = 'debug-item-meta';",
    "        body.textContent = text;",
    "        row.appendChild(body);",
    "    });",
    "    return row;",
    "}",
    "",
    "function debugStatusToneFromBool(value) {",
    "    if (value === true) return 'ok';",
    "    if (value === false) return 'error';",
    "    return 'warn';",
    "}",
    "",
    "function setDebugStatusNode(node, text, tone = '') {",
    "    if (!node) return;",
    "    node.textContent = safeString(text) || 'No status available.';",
    "    node.classList.remove('ok', 'warn', 'error');",
    "    if (tone === 'ok' || tone === 'warn' || tone === 'error') {",
    "        node.classList.add(tone);",
    "    }",
    "}",
    "",
    "function setDebugSystemStatus(text, tone = '') {",
    "    setDebugStatusNode(debugSystemStatus, text, tone);",
    "}",
    "",
    "function setDebugOnboardingRepairButtonState({",
    "    visible = true,",
    "    enabled = true,",
    "    label = 'Repair Now',",
    "} = {}) {",
    "    if (!debugOnboardingRepairBtn) return;",
    "    debugOnboardingRepairBtn.hidden = !visible;",
    "    debugOnboardingRepairBtn.disabled = !enabled;",
    "    debugOnboardingRepairBtn.textContent = safeString(label) || 'Repair Now';",
    "}",
    "",
    "function formatDebugWhen(valueRaw) {",
    "    const value = safeString(valueRaw);",
    "    if (!value) return '-';",
    "    try {",
    "        const dt = new Date(value);",
    "        if (!Number.isFinite(dt.getTime())) return value;",
    "        return `${dt.toLocaleTimeString([], { hour12: false })}`;",
    "    } catch {",
    "        return value;",
    "    }",
    "}",
    "",
    "function summarizeCapabilities(capabilityMap) {",
    "    if (!capabilityMap || typeof capabilityMap !== 'object') return 'Capabilities unavailable';",
    "    const entries = Object.entries(capabilityMap).filter(([, value]) => value === true);",
    "    if (!entries.length) return 'No explicit capabilities';",
    "    const labels = entries.map(([key]) => key.replace(/_/g, ' '));",
    "    return labels.slice(0, 5).join(', ');",
    "}",
    "",
    "function parseEngineRows(enginePayload) {",
    "    const rows = [];",
    "    if (!enginePayload || typeof enginePayload !== 'object') return rows;",
    "    const engines = enginePayload.engines;",
    "    if (!engines || typeof engines !== 'object') return rows;",
    "    Object.entries(engines).forEach(([name, info]) => {",
    "        if (!info || typeof info !== 'object') return;",
    "        const running = Boolean(info.running);",
    "        rows.push({",
    "            name,",
    "            running,",
    "            cycles: Number(info.cycles_completed || 0),",
    "            lastActivity: safeString(info.last_activity || info.started_at),",
    "            error: safeString(info.error),",
    "        });",
    "    });",
    "    return rows;",
    "}",
    "",
    "function renderDebugOnboardingGatePanel(payloadRaw) {",
    "    if (debugOnboardingGateStatusPill) debugOnboardingGateStatusPill.textContent = '-';",
    "    if (debugOnboardingCompletionRate) debugOnboardingCompletionRate.textContent = '-';",
    "    if (debugOnboardingMedianReadySeconds) debugOnboardingMedianReadySeconds.textContent = '-';",
    "",
    "    const payload = payloadRaw && typeof payloadRaw === 'object' ? payloadRaw : null;",
    "    if (!payload) {",
    "        setDebugOnboardingRepairButtonState({",
    "            visible: debugOnboardingRepairInFlight,",
    "            enabled: false,",
    "            label: debugOnboardingRepairInFlight ? 'Repairing...' : 'Repair Now',",
    "        });",
    "        setDebugStatusNode(debugOnboardingGateStatus, 'Use Refresh to fetch onboarding diagnostics.');",
    "        debugRenderEmpty(debugOnboardingGateList, 'No onboarding diagnostics loaded yet.');",
    "        return;",
    "    }",
    "",
    "    const gate = payload?.gate && typeof payload.gate === 'object' ? payload.gate : {};",
    "    const summary = payload?.onboarding_summary && typeof payload.onboarding_summary === 'object'",
    "        ? payload.onboarding_summary",
    "        : (gate?.summary && typeof gate.summary === 'object' ? gate.summary : {});",
    "    const thresholds = gate?.thresholds && typeof gate.thresholds === 'object' ? gate.thresholds : {};",
    "    const errors = Array.isArray(payload?.errors) ? payload.errors : [];",
    "    const warnings = Array.isArray(payload?.warnings) ? payload.warnings : [];",
    "",
    "    const ok = payload?.ok === true;",
    "    const strict = Boolean(payload?.strict);",
    "    const windowDays = Number(payload?.window_days || 0);",
    "    const events = Number(summary?.events || 0);",
    "    const completionRate = Number(summary?.completion_rate || 0);",
    "    const recoveryAttempts = Number(summary?.recovery_attempts || 0);",
    "    const recoverySuccessRate = Number(summary?.recovery_success_rate || 0);",
    "    const completedWithTiming = Number(summary?.completed_journeys_with_timing || 0);",
    "    const medianReadySeconds = Number(summary?.median_time_to_ready_seconds || 0);",
    "",
    "    const minEvents = Number(thresholds?.min_events_for_quality_thresholds || 0);",
    "    const minCompletionRate = Number(thresholds?.min_completion_rate || 0);",
    "    const minRecoverySuccessRate = Number(thresholds?.min_recovery_success_rate || 0);",
    "    const maxMedianReadySeconds = Number(thresholds?.max_median_time_to_ready_seconds || 0);",
    "",
    "    const sampleReady = Number.isFinite(events) && Number.isFinite(minEvents) && events >= minEvents;",
    "    const tone = errors.length > 0 ? 'error' : (warnings.length > 0 ? 'warn' : (ok ? 'ok' : 'warn'));",
    "    const gateLabel = errors.length > 0 ? 'fail' : (warnings.length > 0 ? 'warn' : (ok ? 'pass' : 'check'));",
    "    const needsRepairAction = errors.length > 0 || warnings.length > 0;",
    "    setDebugOnboardingRepairButtonState({",
    "        visible: needsRepairAction || debugOnboardingRepairInFlight,",
    "        enabled: needsRepairAction && !debugOnboardingRepairInFlight,",
    "        label: debugOnboardingRepairInFlight ? 'Repairing...' : 'Repair Now',",
    "    });",
    "",
    "    if (debugOnboardingGateStatusPill) debugOnboardingGateStatusPill.textContent = gateLabel;",
    "    if (debugOnboardingCompletionRate) debugOnboardingCompletionRate.textContent = formatDebugPercent(completionRate, 1);",
    "    if (debugOnboardingMedianReadySeconds) {",
    "        debugOnboardingMedianReadySeconds.textContent = Number.isFinite(medianReadySeconds)",
    "            ? medianReadySeconds.toFixed(1)",
    "            : '-';",
    "    }",
    "",
    "    let statusText = `Window ${windowDays || '-'}d | events ${Number.isFinite(events) ? events : 0}`;",
    "    if (errors.length > 0) {",
    "        statusText = `Gate failed: ${safeString(errors[0]) || 'threshold violations detected.'}`;",
    "    } else if (warnings.length > 0) {",
    "        statusText = `Gate warning: ${safeString(warnings[0]) || 'sample not yet sufficient.'}`;",
].join("\n");
