/* app.js lines 20001-21000 */
export default [
    "                viewportConnected: false,",
    "                viewportLoadState: 'idle',",
    "                viewportBlockedHint: false,",
    "                unrealRcUrl: 'http://127.0.0.1:30010',",
    "                unrealRcEndpoint: '/remote/object/call',",
    "                unrealRcPayload: '{\\n  \"objectPath\": \"/Game/Blueprints/BP_GameMode.BP_GameMode_C\",\\n  \"functionName\": \"RunEditorTick\",\\n  \"parameters\": {}\\n}',",
    "                unrealRcResponse: '',",
    "                sceneActors: [],",
    "                selectedActorId: '',",
    "                nextActorId: 1,",
    "                assets: moduleGameStudioDefaultAssets(),",
    "                selectedAssetId: 'asset-floor-grid',",
    "                assetFilterType: 'all',",
    "                assetSearch: '',",
    "                bridge: {",
    "                    status: 'idle',",
    "                    lastPingMs: 0,",
    "                    lastSeenAt: 0,",
    "                    lastError: '',",
    "                    routes: [],",
    "                    pullCount: 0,",
    "                    pushCount: 0,",
    "                    actorSyncPath: '/Game/Blueprints/BP_LevelBridge.BP_LevelBridge_C',",
    "                },",
    "                bridgePollTimer: 0,",
    "                selectedEngine: 'unreal',",
    "                engineProjects: {},",
    "                activeProjectByEngine: {},",
    "                studioChat: [],",
    "                chatDraft: '',",
    "                projectDraftName: '',",
    "                projectDraftPath: 'C:/games/MyUnrealProject/MyGame.uproject',",
    "                ossReady: false,",
    "                ossLoading: false,",
    "                ossError: '',",
    "            };",
    "        } else if (mode === 'research_lab') {",
    "            state.workbench[mode] = {",
    "                mounted: false,",
    "                lastQuery: '',",
    "                queries: [],",
    "                sources: [],",
    "                notes: '',",
    "                claims: [],",
    "                synthesis: '',",
    "                activeSourceId: '',",
    "            };",
    "        } else {",
    "            state.workbench[mode] = { mounted: false };",
    "        }",
    "    }",
    "    return state.workbench[mode];",
    "}",
    "",
    "function moduleWorkbenchTeardown(mode) {",
    "    const state = moduleEnsureRuntime();",
    "    if (!state) return;",
    "    const wb = state.workbench?.[mode];",
    "    if (!wb || typeof wb !== 'object') return;",
    "    if (mode === 'studio' && Number(wb.timer) > 0) {",
    "        window.clearInterval(wb.timer);",
    "        wb.timer = 0;",
    "        wb.playing = false;",
    "    }",
    "    if (mode === 'lab_3d' && wb.ossEngine?.dispose) {",
    "        try {",
    "            wb.ossEngine.dispose();",
    "        } catch (_error) {}",
    "        wb.ossEngine = null;",
    "    }",
    "    if (mode === 'automations') {",
    "        try {",
    "            wb.ossGraph?.stop?.();",
    "        } catch (_error) {}",
    "        try {",
    "            wb.ossGraphCanvas?.setGraph?.(null, true);",
    "        } catch (_error) {}",
    "        wb.ossGraph = null;",
    "        wb.ossGraphCanvas = null;",
    "    }",
    "    if (mode === 'app_builder' && wb.ossGrid?.destroy) {",
    "        try {",
    "            wb.ossGrid.destroy(false);",
    "        } catch (_error) {}",
    "        wb.ossGrid = null;",
    "    }",
    "    if (mode === 'studio') {",
    "        if (wb.waveSurfer?.destroy) {",
    "            try {",
    "                wb.waveSurfer.destroy();",
    "            } catch (_error) {}",
    "        }",
    "        wb.waveSurfer = null;",
    "        wb.waveContainer = null;",
    "        wb.lastWaveAssetId = '';",
    "    }",
    "    if (mode === 'dev_studio') {",
    "        if (wb.monacoEditor?.dispose) {",
    "            try {",
    "                wb.monacoEditor.dispose();",
    "            } catch (_error) {}",
    "        }",
    "        if (wb.monacoModel?.dispose) {",
    "            try {",
    "                wb.monacoModel.dispose();",
    "            } catch (_error) {}",
    "        }",
    "        wb.monacoEditor = null;",
    "        wb.monacoModel = null;",
    "        if (wb.aceEditor?.destroy) {",
    "            try {",
    "                wb.aceEditor.destroy();",
    "            } catch (_error) {}",
    "        }",
    "        if (wb.aceEditor?.container) {",
    "            wb.aceEditor.container.innerHTML = '';",
    "        }",
    "        wb.aceEditor = null;",
    "    }",
    "    if (mode === 'game_studio' && wb.phaserGame?.destroy) {",
    "        try {",
    "            wb.phaserGame.destroy(true);",
    "        } catch (_error) {}",
    "        wb.phaserGame = null;",
    "    }",
    "    if (mode === 'game_studio' && Number(wb.viewportProbeTimer) > 0) {",
    "        window.clearTimeout(Number(wb.viewportProbeTimer));",
    "        wb.viewportProbeTimer = 0;",
    "    }",
    "    if (mode === 'game_studio' && Number(wb.bridgePollTimer) > 0) {",
    "        window.clearInterval(Number(wb.bridgePollTimer));",
    "        wb.bridgePollTimer = 0;",
    "    }",
    "}",
    "",
    "function moduleWorkbenchHeader(container, title, subtitle) {",
    "    const head = document.createElement('header');",
    "    head.className = 'module-wb-header';",
    "    head.innerHTML = `",
    "        <h3>${escapeHtml(title || 'Workbench')}</h3>",
    "        <p>${escapeHtml(subtitle || 'Interactive workspace')}</p>",
    "    `;",
    "    container.appendChild(head);",
    "}",
    "",
    "const MODULE_WORKBENCH_OPERATOR_COPY = Object.freeze({",
    "    default: 'Thomas executes the work in the background. Use this tab to dispatch tasks, monitor progress, and review outputs.',",
    "    studio: 'Thomas runs connected asset pipelines and tool jobs. Use this tab to queue work, watch status, and review artifacts.',",
    "    dev_studio: 'Thomas runs engineering work and checks. Use this tab to assign coding tasks, monitor results, and review patches.',",
    "    app_builder: 'Thomas builds app structure from your intent. Use this tab to steer requirements, inspect generated UI, and publish safely.',",
    "    game_studio: 'Thomas runs game pipeline jobs across tools. Use this tab to dispatch builds/content generation and review playtest outputs.',",
    "    lab_3d: 'Thomas runs 3D and fabrication pipelines. Use this tab to dispatch modeling/slicing jobs and verify print-ready outputs.',",
    "    research_lab: 'Thomas runs deep research workflows. Use this tab to track source-backed progress and final brief outputs.',",
    "    automations: 'Thomas executes automation flows. Use this tab to define routes, monitor run health, and handle approvals.',",
    "});",
    "",
    "function moduleWorkbenchOperatorNote(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    return MODULE_WORKBENCH_OPERATOR_COPY[mode] || MODULE_WORKBENCH_OPERATOR_COPY.default;",
    "}",
    "",
    "function moduleWorkbenchOperatorPreamble(container, modeRaw) {",
    "    if (!(container instanceof HTMLElement)) return;",
    "    const note = moduleWorkbenchOperatorNote(modeRaw);",
    "    const panel = document.createElement('section');",
    "    panel.className = 'module-wb-operator-note';",
    "    panel.setAttribute('aria-label', 'Thomas operator mode');",
    "    panel.innerHTML = `",
    "        <strong>Operator Mode</strong>",
    "        <p>${escapeHtml(note)}</p>",
    "    `;",
    "    container.appendChild(panel);",
    "}",
    "",
    "function moduleRenderWorkbench(modeRaw, snapshot, signals, definition, { force = false } = {}) {",
    "    if (!moduleWorkbench) return;",
    "    const mode = MODULE_NAV_MODE_SET.has(modeRaw) ? modeRaw : 'dashboard';",
    "    const runtime = moduleEnsureRuntime();",
    "    if (!runtime) return;",
    "    if (!MODULE_WORKBENCH_MODES.has(mode)) {",
    "        if (runtime.workbenchMode && runtime.workbenchMode !== mode) {",
    "            moduleWorkbenchTeardown(runtime.workbenchMode);",
    "        }",
    "        moduleWorkbench.classList.add('hidden');",
    "        moduleWorkbench.dataset.mode = '';",
    "        moduleWorkbench.innerHTML = '';",
    "        runtime.workbenchMode = '';",
    "        return;",
    "    }",
    "",
    "    const wb = moduleWorkbenchState(mode);",
    "    if (!wb) {",
    "        moduleWorkbench.classList.add('hidden');",
    "        return;",
    "    }",
    "",
    "    const modeChanged = runtime.workbenchMode !== mode;",
    "    moduleWorkbench.classList.remove('hidden');",
    "    moduleWorkbench.dataset.mode = mode;",
    "",
    "    if (!force && !modeChanged && wb.mounted) {",
    "        return;",
    "    }",
    "",
    "    if (modeChanged && runtime.workbenchMode) {",
    "        moduleWorkbenchTeardown(runtime.workbenchMode);",
    "    }",
    "",
    "    moduleWorkbench.innerHTML = '';",
    "    moduleWorkbenchOperatorPreamble(moduleWorkbench, mode);",
    "    if (mode === 'lab_3d') {",
    "        moduleRenderWorkbenchLab3d(moduleWorkbench, wb, { signals, snapshot, definition });",
    "    } else if (mode === 'automations') {",
    "        moduleRenderWorkbenchAutomations(moduleWorkbench, wb, { signals, snapshot, definition });",
    "    } else if (mode === 'app_builder') {",
    "        moduleRenderWorkbenchAppBuilder(moduleWorkbench, wb, { signals, snapshot, definition });",
    "    } else if (mode === 'studio') {",
    "        moduleRenderWorkbenchStudio(moduleWorkbench, wb, { signals, snapshot, definition });",
    "    } else if (mode === 'dev_studio') {",
    "        moduleRenderWorkbenchDevStudio(moduleWorkbench, wb, { signals, snapshot, definition });",
    "    } else if (mode === 'game_studio') {",
    "        moduleRenderWorkbenchGameStudio(moduleWorkbench, wb, { signals, snapshot, definition });",
    "    } else if (mode === 'research_lab') {",
    "        moduleRenderWorkbenchResearch(moduleWorkbench, wb, { signals, snapshot, definition });",
    "    } else {",
    "        moduleWorkbench.classList.add('hidden');",
    "    }",
    "",
    "    wb.mounted = true;",
    "    runtime.workbenchMode = mode;",
    "}",
    "",
    "function moduleWorkbenchClamp(value, min, max) {",
    "    const number = Number(value);",
    "    if (!Number.isFinite(number)) return min;",
    "    if (number < min) return min;",
    "    if (number > max) return max;",
    "    return number;",
    "}",
    "",
    "function moduleWorkbenchTimeStamp() {",
    "    return new Date().toISOString().slice(11, 19);",
    "}",
    "",
    "function moduleLab3dDefaultColor(type) {",
    "    if (type === 'circle') return '#79d2b8';",
    "    if (type === 'line') return '#ffd59a';",
    "    return '#83c6ff';",
    "}",
    "",
    "function moduleLab3dShapeById(wb, shapeId) {",
    "    if (!wb || !Array.isArray(wb.shapes)) return null;",
    "    return wb.shapes.find((shape) => safeString(shape?.id) === safeString(shapeId)) || null;",
    "}",
    "",
    "function moduleLab3dMetrics(shapeRaw) {",
    "    const shape = shapeRaw && typeof shapeRaw === 'object' ? shapeRaw : {};",
    "    const type = safeString(shape.type);",
    "    if (type === 'line') {",
    "        const dx = (Number(shape.x2) || 0) - (Number(shape.x) || 0);",
    "        const dy = (Number(shape.y2) || 0) - (Number(shape.y) || 0);",
    "        const length = Math.sqrt((dx * dx) + (dy * dy));",
    "        return { area: 0, perimeter: length, volume: 0 };",
    "    }",
    "    const depth = Math.max(0, Number(shape.depth) || 0);",
    "    if (type === 'circle') {",
    "        const radius = Math.max(1, Math.max(Number(shape.w) || 0, Number(shape.h) || 0) / 2);",
    "        const area = Math.PI * radius * radius;",
    "        const perimeter = 2 * Math.PI * radius;",
    "        return { area, perimeter, volume: area * depth };",
    "    }",
    "    const width = Math.max(0, Number(shape.w) || 0);",
    "    const height = Math.max(0, Number(shape.h) || 0);",
    "    const area = width * height;",
    "    const perimeter = (width * 2) + (height * 2);",
    "    return { area, perimeter, volume: area * depth };",
    "}",
    "",
    "function moduleLab3dHitShape(shapeRaw, pointRaw) {",
    "    const shape = shapeRaw && typeof shapeRaw === 'object' ? shapeRaw : {};",
    "    const point = pointRaw && typeof pointRaw === 'object' ? pointRaw : { x: 0, y: 0 };",
    "    const type = safeString(shape.type);",
    "    if (type === 'line') {",
    "        const x1 = Number(shape.x) || 0;",
    "        const y1 = Number(shape.y) || 0;",
    "        const x2 = Number(shape.x2) || x1;",
    "        const y2 = Number(shape.y2) || y1;",
    "        const px = Number(point.x) || 0;",
    "        const py = Number(point.y) || 0;",
    "        const abx = x2 - x1;",
    "        const aby = y2 - y1;",
    "        const denom = (abx * abx) + (aby * aby);",
    "        if (denom <= 0.001) return Math.hypot(px - x1, py - y1) < 8;",
    "        const t = moduleWorkbenchClamp((((px - x1) * abx) + ((py - y1) * aby)) / denom, 0, 1);",
    "        const cx = x1 + (abx * t);",
    "        const cy = y1 + (aby * t);",
    "        return Math.hypot(px - cx, py - cy) < 8;",
    "    }",
    "    const x = Number(shape.x) || 0;",
    "    const y = Number(shape.y) || 0;",
    "    const w = Number(shape.w) || 0;",
    "    const h = Number(shape.h) || 0;",
    "    if (type === 'circle') {",
    "        const cx = x + (w / 2);",
    "        const cy = y + (h / 2);",
    "        const r = Math.max(1, Math.max(w, h) / 2);",
    "        const dx = (Number(point.x) || 0) - cx;",
    "        const dy = (Number(point.y) || 0) - cy;",
    "        return ((dx * dx) + (dy * dy)) <= (r * r);",
    "    }",
    "    return (Number(point.x) || 0) >= x",
    "        && (Number(point.x) || 0) <= (x + w)",
    "        && (Number(point.y) || 0) >= y",
    "        && (Number(point.y) || 0) <= (y + h);",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  WORKBENCH EDITORS                                                      ║",
    "// ║  Lab 3D, Automations, App Builder, Studio, Dev Studio, Game Studio,     ║",
    "// ║  Research Lab — rich interactive editors for each workbench mode         ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function moduleRenderWorkbenchLab3dOss(container, wb) {",
    "    if (!container || !wb) return false;",
    "    if (wb.ossError) return false;",
    "    if (!wb.ossReady || !wb.ossThree) {",
    "        moduleWorkbenchRenderEngineLoading(",
    "            container,",
    "            '3D Lab CAD Engine',",
    "            'Three.js viewport with transform controls and scene export.',",
    "            'Loading Three.js modules...',",
    "            'Falling back to local sketch mode if loading fails.',",
    "        );",
    "        if (!wb.ossLoading) {",
    "            wb.ossLoading = true;",
    "            void moduleWorkbenchLoadThreeBundle().then((bundle) => {",
    "                wb.ossThree = bundle;",
    "                wb.ossReady = true;",
    "                wb.ossLoading = false;",
    "                wb.ossError = '';",
    "                moduleWorkbenchRefreshMode('lab_3d');",
    "            }).catch((error) => {",
    "                wb.ossLoading = false;",
    "                wb.ossReady = false;",
    "                wb.ossError = safeString(error?.message) || 'Failed to load 3D engine.';",
    "                notifyUser('3D engine failed to load, using fallback canvas.', { tone: 'warn', durationMs: 2400, debugKind: 'lab3d' });",
    "                moduleWorkbenchRefreshMode('lab_3d');",
    "            });",
    "        }",
    "        return true;",
    "    }",
    "",
    "    const { THREE, OrbitControls, TransformControls, GLTFExporter, STLExporter } = wb.ossThree;",
    "    if (!THREE || !OrbitControls || !TransformControls) return false;",
    "    if (!Array.isArray(wb.objects)) wb.objects = [];",
    "    wb.nextId = Math.max(1, Number(wb.nextId) || 1);",
    "    wb.units = safeString(wb.units) || 'mm';",
    "    wb.transformMode = safeString(wb.transformMode) || 'translate';",
    "    wb.transformSpace = safeString(wb.transformSpace) === 'local' ? 'local' : 'world';",
    "    wb.transformSnap = Boolean(wb.transformSnap);",
    "    wb.showGrid = wb.showGrid !== false;",
    "    wb.wireframe = Boolean(wb.wireframe);",
    "    wb.selectedId = safeString(wb.selectedId);",
    "    wb.selectedProjectId = safeString(wb.selectedProjectId);",
    "",
    "    if (!wb.objects.length) {",
    "        wb.objects.push({",
    "            id: `mesh-${wb.nextId++}`,",
    "            name: 'Base Cube',",
    "            type: 'box',",
    "            color: '#7fbfff',",
    "            position: { x: 0, y: 0.5, z: 0 },",
    "            rotation: { x: 0, y: 0, z: 0 },",
    "            scale: { x: 1, y: 1, z: 1 },",
    "        });",
    "    }",
    "",
    "    moduleWorkbenchHeader(container, '3D Lab CAD Engine', 'Thomas runs 3D scene jobs while you monitor geometry, transforms, and export state.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-lab3d-oss';",
    "    shell.innerHTML = `",
    "        <div class=\"module-wb-toolbar\">",
    "            <div class=\"module-wb-tool-group\">",
    "                <button type=\"button\" class=\"module-wb-tool-btn\" data-lab3d-add=\"box\"><i class=\"ph ph-cube\"></i><span>Cube</span></button>",
    "                <button type=\"button\" class=\"module-wb-tool-btn\" data-lab3d-add=\"sphere\"><i class=\"ph ph-circle\"></i><span>Sphere</span></button>",
    "                <button type=\"button\" class=\"module-wb-tool-btn\" data-lab3d-add=\"cylinder\"><i class=\"ph ph-cylinder\"></i><span>Cylinder</span></button>",
    "            </div>",
    "            <div class=\"module-wb-tool-group\">",
    "                <button type=\"button\" class=\"module-wb-tool-btn${wb.transformMode === 'translate' ? ' active' : ''}\" data-lab3d-transform=\"translate\">Move</button>",
    "                <button type=\"button\" class=\"module-wb-tool-btn${wb.transformMode === 'rotate' ? ' active' : ''}\" data-lab3d-transform=\"rotate\">Rotate</button>",
    "                <button type=\"button\" class=\"module-wb-tool-btn${wb.transformMode === 'scale' ? ' active' : ''}\" data-lab3d-transform=\"scale\">Scale</button>",
    "            </div>",
    "            <div class=\"module-wb-toolbar-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"snap\">${wb.transformSnap ? 'Snap On' : 'Snap Off'}</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"space\">${wb.transformSpace === 'local' ? 'Local' : 'World'}</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"wireframe\">${wb.wireframe ? 'Wireframe' : 'Shaded'}</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"grid\">${wb.showGrid ? 'Grid On' : 'Grid Off'}</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"import_json\">Import JSON</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"delete\">Delete</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"export\">Export JSON</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"export_gltf\">Export GLTF</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab3d-action=\"export_stl\">Export STL</button>",
    "            </div>",
    "        </div>",
    "        ${moduleWorkbenchRenderProjectControls('lab_3d', 'Model Projects')}",
    "        <div class=\"module-wb-main-grid module-wb-main-grid-lab3d\">",
    "            <section class=\"module-wb-stage-card\">",
    "                <div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Viewport</span><span class=\"module-wb-stage-meta\" data-lab3d-status></span></div>",
    "                <div class=\"module-wb-3d-stage\" data-lab3d-stage></div>",
    "                <p class=\"module-wb-hint\">Click meshes to select. Drag gizmo handles for precision transforms.</p>",
    "            </section>",
    "            <aside class=\"module-wb-inspector-card\" data-lab3d-inspector></aside>",
    "        </div>",
    "        ${moduleWorkbenchRenderOssStack('lab_3d')}",
    "        <input type=\"file\" class=\"hidden\" data-lab3d-import-json accept=\".json,application/json\" />",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const stage = shell.querySelector('[data-lab3d-stage]');",
    "    const inspector = shell.querySelector('[data-lab3d-inspector]');",
    "    const status = shell.querySelector('[data-lab3d-status]');",
    "    const importInput = shell.querySelector('[data-lab3d-import-json]');",
    "    if (!(stage instanceof HTMLElement) || !(inspector instanceof HTMLElement) || !(status instanceof HTMLElement)) {",
    "        return false;",
    "    }",
    "",
    "    if (wb.ossEngine?.dispose) {",
    "        try {",
    "            wb.ossEngine.dispose();",
    "        } catch (_error) {}",
    "    }",
    "",
    "    const scene = new THREE.Scene();",
    "    scene.background = new THREE.Color(0x0f1928);",
    "    const camera = new THREE.PerspectiveCamera(52, 1, 0.1, 200);",
    "    camera.position.set(4.2, 3.4, 6.1);",
    "    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });",
    "    renderer.setPixelRatio(Math.min(2, window.devicePixelRatio || 1));",
    "    renderer.outputColorSpace = THREE.SRGBColorSpace;",
    "    renderer.shadowMap.enabled = true;",
    "    stage.appendChild(renderer.domElement);",
    "",
    "    const controls = new OrbitControls(camera, renderer.domElement);",
    "    controls.enableDamping = true;",
    "    controls.dampingFactor = 0.08;",
    "    controls.minDistance = 1.5;",
    "    controls.maxDistance = 50;",
    "",
    "    const transform = new TransformControls(camera, renderer.domElement);",
    "    transform.setMode(wb.transformMode);",
    "    transform.setSpace(wb.transformSpace);",
    "    transform.size = 0.78;",
    "    if (wb.transformSnap) {",
    "        transform.setTranslationSnap(0.25);",
    "        transform.setRotationSnap(Math.PI / 12);",
    "        transform.setScaleSnap(0.1);",
    "    } else {",
    "        transform.setTranslationSnap(null);",
    "        transform.setRotationSnap(null);",
    "        transform.setScaleSnap(null);",
    "    }",
    "    transform.addEventListener('dragging-changed', (event) => {",
    "        controls.enabled = !Boolean(event?.value);",
    "    });",
    "    if (typeof transform.getHelper === 'function') {",
    "        scene.add(transform.getHelper());",
    "    } else {",
    "        scene.add(transform);",
    "    }",
    "",
    "    scene.add(new THREE.AmbientLight(0xffffff, 0.42));",
    "    const keyLight = new THREE.DirectionalLight(0xd8ecff, 0.92);",
    "    keyLight.position.set(4, 8, 5);",
    "    keyLight.castShadow = true;",
    "    scene.add(keyLight);",
    "    const gridHelper = new THREE.GridHelper(24, 24, 0x2d5d8f, 0x1a334e);",
    "    gridHelper.visible = wb.showGrid;",
    "    scene.add(gridHelper);",
    "    scene.add(new THREE.AxesHelper(1.25));",
    "",
    "    const raycaster = new THREE.Raycaster();",
    "    const pointer = new THREE.Vector2();",
    "    const meshes = new Map();",
    "",
    "    const cleanColor = (value, fallback = '#7fbfff') => (/^#[0-9a-f]{6}$/i.test(safeString(value)) ? safeString(value) : fallback);",
    "    const ensureVector3 = (raw, fallback) => ({",
    "        x: Number.isFinite(Number(raw?.x)) ? Number(raw.x) : fallback.x,",
    "        y: Number.isFinite(Number(raw?.y)) ? Number(raw.y) : fallback.y,",
    "        z: Number.isFinite(Number(raw?.z)) ? Number(raw.z) : fallback.z,",
    "    });",
    "    const geometryFor = (typeRaw) => {",
    "        const type = safeString(typeRaw);",
    "        if (type === 'sphere') return new THREE.SphereGeometry(0.55, 28, 20);",
    "        if (type === 'cylinder') return new THREE.CylinderGeometry(0.42, 0.42, 1.15, 28);",
    "        return new THREE.BoxGeometry(1, 1, 1);",
    "    };",
    "    const materialFor = (colorRaw) => new THREE.MeshStandardMaterial({",
    "        color: cleanColor(colorRaw, '#7fbfff'),",
    "        metalness: 0.2,",
    "        roughness: 0.52,",
    "        wireframe: wb.wireframe,",
    "    });",
    "    const toMesh = (spec) => {",
    "        const mesh = new THREE.Mesh(geometryFor(spec.type), materialFor(spec.color));",
    "        mesh.castShadow = true;",
    "        mesh.receiveShadow = true;",
    "        mesh.userData.workbenchId = safeString(spec.id);",
    "        const p = ensureVector3(spec.position, { x: 0, y: 0.5, z: 0 });",
    "        const r = ensureVector3(spec.rotation, { x: 0, y: 0, z: 0 });",
    "        const s = ensureVector3(spec.scale, { x: 1, y: 1, z: 1 });",
    "        mesh.position.set(p.x, p.y, p.z);",
    "        mesh.rotation.set(r.x, r.y, r.z);",
    "        mesh.scale.set(Math.max(0.1, s.x), Math.max(0.1, s.y), Math.max(0.1, s.z));",
    "        return mesh;",
    "    };",
    "    const updateSpecFromMesh = (spec, mesh) => {",
    "        spec.position = { x: Number(mesh.position.x.toFixed(3)), y: Number(mesh.position.y.toFixed(3)), z: Number(mesh.position.z.toFixed(3)) };",
    "        spec.rotation = { x: Number(mesh.rotation.x.toFixed(3)), y: Number(mesh.rotation.y.toFixed(3)), z: Number(mesh.rotation.z.toFixed(3)) };",
    "        spec.scale = { x: Number(mesh.scale.x.toFixed(3)), y: Number(mesh.scale.y.toFixed(3)), z: Number(mesh.scale.z.toFixed(3)) };",
    "        if (mesh.material?.color) {",
    "            spec.color = `#${mesh.material.color.getHexString()}`;",
    "        }",
    "    };",
    "    const specById = (id) => wb.objects.find((row) => safeString(row?.id) === safeString(id)) || null;",
    "    const selectedSpec = () => specById(wb.selectedId);",
    "    const selectedMesh = () => meshes.get(safeString(wb.selectedId)) || null;",
    "    const setSelection = (idRaw) => {",
    "        wb.selectedId = safeString(idRaw);",
    "        const mesh = selectedMesh();",
    "        if (mesh) {",
    "            transform.attach(mesh);",
    "        } else {",
    "            transform.detach();",
    "        }",
    "    };",
    "    const rebuildScene = () => {",
    "        meshes.forEach((mesh) => {",
    "            scene.remove(mesh);",
    "            mesh.geometry?.dispose?.();",
    "            if (Array.isArray(mesh.material)) {",
    "                mesh.material.forEach((material) => material?.dispose?.());",
    "            } else {",
    "                mesh.material?.dispose?.();",
    "            }",
    "        });",
    "        meshes.clear();",
    "        wb.objects.forEach((spec) => {",
    "            const mesh = toMesh(spec);",
    "            meshes.set(safeString(spec.id), mesh);",
    "            scene.add(mesh);",
    "        });",
    "        applyMaterialVisuals();",
    "        if (!meshes.has(wb.selectedId) && wb.objects.length) {",
    "            wb.selectedId = safeString(wb.objects[0].id);",
    "        }",
    "        setSelection(wb.selectedId);",
    "    };",
    "    const totalVolume = () => wb.objects.reduce((acc, spec) => {",
    "        const scale = ensureVector3(spec.scale, { x: 1, y: 1, z: 1 });",
    "        let base = 1;",
    "        if (safeString(spec.type) === 'sphere') base = (4 / 3) * Math.PI * 0.55 * 0.55 * 0.55;",
    "        if (safeString(spec.type) === 'cylinder') base = Math.PI * 0.42 * 0.42 * 1.15;",
    "        return acc + (base * Math.max(0.1, scale.x) * Math.max(0.1, scale.y) * Math.max(0.1, scale.z));",
    "    }, 0);",
    "    const renderInspector = () => {",
    "        const spec = selectedSpec();",
    "        if (!spec) {",
    "            inspector.innerHTML = `<h4>Inspector</h4><p class=\"module-wb-mini-note\">Select a mesh to edit transforms.</p><div class=\"module-wb-metrics\"><div><span>Bodies</span><strong>${wb.objects.length}</strong></div><div><span>Volume</span><strong>${totalVolume().toFixed(2)} ${escapeHtml(wb.units)}^3</strong></div><div><span>Mode</span><strong>${escapeHtml(wb.transformMode)}</strong></div></div>`;",
    "            return;",
    "        }",
    "        const p = ensureVector3(spec.position, { x: 0, y: 0.5, z: 0 });",
    "        const s = ensureVector3(spec.scale, { x: 1, y: 1, z: 1 });",
    "        inspector.innerHTML = `",
    "            <h4>${escapeHtml(safeString(spec.name) || 'Mesh')}</h4>",
    "            <div class=\"module-wb-field-grid\">",
    "                <label class=\"module-wb-field\">Name<input type=\"text\" data-lab3d-prop=\"name\" value=\"${escapeHtml(safeString(spec.name))}\" /></label>",
    "                <label class=\"module-wb-field\">Color<input type=\"color\" data-lab3d-prop=\"color\" value=\"${escapeHtml(cleanColor(spec.color))}\" /></label>",
    "                <label class=\"module-wb-field\">X<input type=\"number\" step=\"0.1\" data-lab3d-prop=\"x\" value=\"${p.x}\" /></label>",
    "                <label class=\"module-wb-field\">Y<input type=\"number\" step=\"0.1\" data-lab3d-prop=\"y\" value=\"${p.y}\" /></label>",
    "                <label class=\"module-wb-field\">Z<input type=\"number\" step=\"0.1\" data-lab3d-prop=\"z\" value=\"${p.z}\" /></label>",
    "                <label class=\"module-wb-field\">Scale<input type=\"number\" step=\"0.1\" min=\"0.1\" data-lab3d-prop=\"scale\" value=\"${s.x}\" /></label>",
    "            </div>",
    "            <p class=\"module-wb-mini-note\">Type: ${escapeHtml(safeString(spec.type) || 'box')} | ID: ${escapeHtml(safeString(spec.id))}</p>",
    "        `;",
    "    };",
    "    const renderStatus = () => {",
    "        const selected = selectedSpec() ? safeString(selectedSpec().name) : 'no selection';",
    "        status.textContent = `${wb.objects.length} meshes | ${wb.transformMode}/${wb.transformSpace}${wb.transformSnap ? ' snap' : ''} | ${selected}`;",
    "        const snapBtn = shell.querySelector('[data-lab3d-action=\"snap\"]');",
    "        const spaceBtn = shell.querySelector('[data-lab3d-action=\"space\"]');",
    "        const wireBtn = shell.querySelector('[data-lab3d-action=\"wireframe\"]');",
    "        const gridBtn = shell.querySelector('[data-lab3d-action=\"grid\"]');",
    "        if (snapBtn) snapBtn.textContent = wb.transformSnap ? 'Snap On' : 'Snap Off';",
    "        if (spaceBtn) spaceBtn.textContent = wb.transformSpace === 'local' ? 'Local' : 'World';",
    "        if (wireBtn) wireBtn.textContent = wb.wireframe ? 'Wireframe' : 'Shaded';",
    "        if (gridBtn) gridBtn.textContent = wb.showGrid ? 'Grid On' : 'Grid Off';",
    "    };",
    "    const renderProjectSelect = () => {",
    "        const select = shell.querySelector('select[data-wb-project-select=\"lab_3d\"]');",
    "        if (!(select instanceof HTMLSelectElement)) return;",
    "        const rows = moduleWorkbenchProjectList('lab_3d');",
    "        const current = safeString(wb.selectedProjectId);",
    "        select.innerHTML = `<option value=\"\">Select project</option>${rows.map((row) => `<option value=\"${escapeHtml(safeString(row.id))}\">${escapeHtml(`${safeString(row.name)} (${new Date(Number(row.updatedAt) || Date.now()).toLocaleString()})`)}</option>`).join('')}`;",
    "        select.value = rows.some((row) => safeString(row.id) === current) ? current : '';",
    "    };",
    "    const syncAllSpecs = () => {",
    "        wb.objects.forEach((spec) => {",
    "            const mesh = meshes.get(safeString(spec.id));",
    "            if (mesh) updateSpecFromMesh(spec, mesh);",
    "        });",
    "    };",
    "    const applyMaterialVisuals = () => {",
    "        meshes.forEach((mesh) => {",
    "            if (Array.isArray(mesh.material)) {",
    "                mesh.material.forEach((material) => {",
    "                    if (material && 'wireframe' in material) material.wireframe = wb.wireframe;",
    "                });",
    "            } else if (mesh.material && 'wireframe' in mesh.material) {",
    "                mesh.material.wireframe = wb.wireframe;",
    "            }",
    "        });",
    "    };",
    "    const parseImportedObjects = (payloadRaw) => {",
    "        const payload = payloadRaw && typeof payloadRaw === 'object' ? payloadRaw : {};",
    "        const rows = Array.isArray(payload.objects) ? payload.objects : [];",
    "        return rows",
    "            .map((row, index) => {",
    "                const type = safeString(row?.type);",
    "                if (!['box', 'sphere', 'cylinder'].includes(type)) return null;",
    "                return {",
    "                    id: `mesh-${wb.nextId + index}`,",
    "                    name: safeString(row?.name) || `${type[0]?.toUpperCase() || 'M'}${type.slice(1)} ${wb.nextId + index}`,",
    "                    type,",
    "                    color: cleanColor(row?.color),",
    "                    position: ensureVector3(row?.position, { x: 0, y: 0.5, z: 0 }),",
    "                    rotation: ensureVector3(row?.rotation, { x: 0, y: 0, z: 0 }),",
    "                    scale: ensureVector3(row?.scale, { x: 1, y: 1, z: 1 }),",
    "                };",
    "            })",
    "            .filter(Boolean);",
    "    };",
    "    const addMesh = (typeRaw) => {",
    "        const type = safeString(typeRaw) || 'box';",
    "        const spec = {",
    "            id: `mesh-${wb.nextId++}`,",
    "            name: `${type[0]?.toUpperCase() || 'M'}${type.slice(1)} ${wb.nextId - 1}`,",
    "            type,",
    "            color: cleanColor(type === 'sphere' ? '#7fe2ca' : (type === 'cylinder' ? '#ffcf84' : '#7fbfff')),",
    "            position: { x: 0, y: 0.7, z: 0 },",
    "            rotation: { x: 0, y: 0, z: 0 },",
    "            scale: { x: 1, y: 1, z: 1 },",
    "        };",
    "        wb.objects.push(spec);",
    "        rebuildScene();",
    "        setSelection(spec.id);",
    "        renderInspector();",
    "        renderStatus();",
    "    };",
    "    const resize = () => {",
    "        const width = Math.max(320, stage.clientWidth || 320);",
    "        const height = Math.max(220, stage.clientHeight || 220);",
    "        renderer.setSize(width, height);",
    "        camera.aspect = width / height;",
    "        camera.updateProjectionMatrix();",
    "    };",
    "",
    "    rebuildScene();",
    "    resize();",
    "    renderInspector();",
    "    renderStatus();",
    "    renderProjectSelect();",
    "",
    "    const onPointerDown = (event) => {",
    "        const rect = renderer.domElement.getBoundingClientRect();",
    "        pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;",
    "        pointer.y = -(((event.clientY - rect.top) / rect.height) * 2 - 1);",
    "        raycaster.setFromCamera(pointer, camera);",
    "        const hits = raycaster.intersectObjects(Array.from(meshes.values()), false);",
    "        if (!hits.length) {",
    "            setSelection('');",
    "            renderInspector();",
    "            renderStatus();",
    "            return;",
    "        }",
    "        const id = safeString(hits[0]?.object?.userData?.workbenchId);",
    "        setSelection(id);",
    "        renderInspector();",
    "        renderStatus();",
    "    };",
    "    renderer.domElement.addEventListener('pointerdown', onPointerDown);",
    "    transform.addEventListener('objectChange', () => {",
    "        const spec = selectedSpec();",
    "        const mesh = selectedMesh();",
    "        if (!spec || !mesh) return;",
    "        updateSpecFromMesh(spec, mesh);",
    "        renderInspector();",
    "        renderStatus();",
    "    });",
    "",
    "    const resizeObserver = typeof ResizeObserver !== 'undefined' ? new ResizeObserver(resize) : null;",
    "    if (resizeObserver) resizeObserver.observe(stage);",
    "    const onWindowResize = () => resize();",
    "    window.addEventListener('resize', onWindowResize);",
    "",
    "    let rafId = 0;",
    "    const frame = () => {",
    "        rafId = window.requestAnimationFrame(frame);",
    "        controls.update();",
    "        renderer.render(scene, camera);",
    "    };",
    "    frame();",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const projectActionEl = event.target instanceof Element",
    "            ? event.target.closest('[data-wb-project-action][data-wb-project-mode=\"lab_3d\"]')",
    "            : null;",
    "        if (projectActionEl) {",
    "            const action = safeString(projectActionEl.dataset.wbProjectAction).toLowerCase();",
    "            const select = shell.querySelector('select[data-wb-project-select=\"lab_3d\"]');",
    "            const input = shell.querySelector('input[data-wb-project-name=\"lab_3d\"]');",
    "            const selectedId = safeString(select instanceof HTMLSelectElement ? select.value : wb.selectedProjectId);",
    "            if (action === 'save') {",
    "                syncAllSpecs();",
    "                wb.selectedProjectId = moduleWorkbenchProjectSave('lab_3d', {",
    "                    units: wb.units,",
    "                    objects: wb.objects,",
    "                    transformMode: wb.transformMode,",
    "                    transformSpace: wb.transformSpace,",
    "                    transformSnap: wb.transformSnap,",
    "                    showGrid: wb.showGrid,",
    "                    wireframe: wb.wireframe,",
    "                }, safeString(input instanceof HTMLInputElement ? input.value : ''));",
    "                if (input instanceof HTMLInputElement) input.value = '';",
    "                renderProjectSelect();",
    "                notifyUser('Model project saved.', { tone: 'success', durationMs: 1600, debugKind: 'lab3d' });",
    "                return;",
    "            }",
    "            if (action === 'load') {",
    "                if (!selectedId) return;",
    "                const project = moduleWorkbenchProjectGet('lab_3d', selectedId);",
    "                if (!project?.payload) return;",
    "                const payload = project.payload;",
    "                const nextObjects = parseImportedObjects(payload);",
    "                if (!nextObjects.length) return;",
    "                wb.objects = nextObjects;",
    "                wb.units = safeString(payload.units) || wb.units;",
    "                wb.transformMode = safeString(payload.transformMode) || wb.transformMode;",
    "                wb.transformSpace = safeString(payload.transformSpace) === 'local' ? 'local' : 'world';",
    "                wb.transformSnap = Boolean(payload.transformSnap);",
    "                wb.showGrid = payload.showGrid !== false;",
    "                wb.wireframe = Boolean(payload.wireframe);",
    "                wb.selectedProjectId = selectedId;",
    "                transform.setMode(wb.transformMode);",
    "                transform.setSpace(wb.transformSpace);",
    "                if (wb.transformSnap) {",
    "                    transform.setTranslationSnap(0.25);",
    "                    transform.setRotationSnap(Math.PI / 12);",
    "                    transform.setScaleSnap(0.1);",
    "                } else {",
].join("\n");
