/* app.js lines 18001-19000 */
export default [
    "            triageFilters: {},",
    "            subnavFocus: {},",
    "            workbenchMode: '',",
    "            workbench: {},",
    "            hidden: {},",
    "            activity: {},",
    "            refreshedAt: {},",
"            marketplace: {",
"                apps: [],",
"                modules: [],",
"                loading: false,",
"                error: '',",
"                search: '',",
"                lastRefreshedAt: 0,",
"                refreshPromise: null,",
"            },",
    "        };",
    "    }",
    "    return moduleState;",
    "}",
    "",
    "function moduleEnsureHiddenBucket(mode, section) {",
    "    const state = moduleEnsureRuntime();",
    "    if (!state) return null;",
    "    if (!state.hidden[mode]) {",
    "        state.hidden[mode] = {",
    "            queue: new Set(),",
    "            health: new Set(),",
    "            triage: new Set(),",
    "        };",
    "    }",
    "    if (!state.hidden[mode][section]) {",
    "        state.hidden[mode][section] = new Set();",
    "    }",
    "    return state.hidden[mode][section];",
    "}",
    "",
    "function moduleHideItem(mode, section, itemId) {",
    "    const id = safeString(itemId);",
    "    if (!id) return;",
    "    const bucket = moduleEnsureHiddenBucket(mode, section);",
    "    if (bucket) bucket.add(id);",
    "}",
    "",
    "function moduleIsItemHidden(mode, section, itemId) {",
    "    const id = safeString(itemId);",
    "    if (!id) return false;",
    "    const bucket = moduleEnsureHiddenBucket(mode, section);",
    "    return Boolean(bucket && bucket.has(id));",
    "}",
    "",
    "function moduleVisibleItems(mode, section, rowsRaw) {",
    "    const rows = Array.isArray(rowsRaw) ? rowsRaw : [];",
    "    return rows.filter((row) => !moduleIsItemHidden(mode, section, row?.id));",
    "}",
    "",
    "function moduleToneClass(toneRaw) {",
    "    const tone = safeString(toneRaw).toLowerCase();",
    "    if (tone === 'ok' || tone === 'success' || tone === 'live') return 'ok';",
    "    if (tone === 'warn' || tone === 'warning' || tone === 'watch') return 'warn';",
    "    if (tone === 'error' || tone === 'danger' || tone === 'critical') return 'error';",
    "    if (tone === 'done' || tone === 'complete') return 'done';",
    "    return '';",
    "}",
    "",
    "function moduleTouch(mode) {",
    "    const state = moduleEnsureRuntime();",
    "    if (!state) return;",
    "    state.refreshedAt[mode] = Date.now();",
    "}",
    "",
    "function moduleRecordActivity(mode, title, tone = 'ok') {",
    "    const state = moduleEnsureRuntime();",
    "    if (!state) return;",
    "    if (!Array.isArray(state.activity[mode])) {",
    "        state.activity[mode] = [];",
    "    }",
    "    const badge = tone === 'error' ? 'Alert' : (tone === 'warn' ? 'Update' : 'Action');",
    "    state.activity[mode].unshift({",
    "        id: `act-${Date.now()}-${Math.round(Math.random() * 10_000)}`,",
    "        title: safeString(title) || 'Action completed.',",
    "        meta: 'just now',",
    "        badge,",
    "        tone,",
    "    });",
    "    if (state.activity[mode].length > 14) {",
    "        state.activity[mode] = state.activity[mode].slice(0, 14);",
    "    }",
    "}",
    "",
    "function moduleBuildSnapshot() {",
    "    const missionPayload = missionState?.lastPayload && typeof missionState.lastPayload === 'object'",
    "        ? missionState.lastPayload",
    "        : {};",
    "    const jobsPayload = missionState?.lastJobsPayload && typeof missionState.lastJobsPayload === 'object'",
    "        ? missionState.lastJobsPayload",
    "        : {};",
    "    const contentPayload = contentState?.payload && typeof contentState.payload === 'object'",
    "        ? contentState.payload",
    "        : contentEmptyPayload();",
    "    const summary = contentPayload?.summary && typeof contentPayload.summary === 'object'",
    "        ? contentPayload.summary",
    "        : {};",
    "    const controlSurface = contentPayload?.control_surface && typeof contentPayload.control_surface === 'object'",
    "        ? contentPayload.control_surface",
    "        : {};",
    "    const approvals = missionPayload?.approvals && typeof missionPayload.approvals === 'object'",
    "        ? missionPayload.approvals",
    "        : {};",
    "",
    "    return {",
    "        missionPayload,",
    "        jobs: Array.isArray(jobsPayload?.jobs) ? jobsPayload.jobs : [],",
    "        events: Array.isArray(missionPayload?.events) ? missionPayload.events : [],",
    "        agents: Array.isArray(missionPayload?.agents) ? missionPayload.agents : [],",
    "        platforms: Array.isArray(contentPayload?.platforms) ? contentPayload.platforms : [],",
    "        workflows: Array.isArray(contentPayload?.workflows) ? contentPayload.workflows : [],",
    "        scheduler: Array.isArray(contentPayload?.scheduler) ? contentPayload.scheduler : [],",
    "        tools: Array.isArray(contentPayload?.tools) ? contentPayload.tools : [],",
    "        healthChecks: Array.isArray(controlSurface?.health_checks) ? controlSurface.health_checks : [],",
    "        summary,",
    "        controlSurface,",
    "        totals: missionPayload?.totals && typeof missionPayload.totals === 'object' ? missionPayload.totals : {},",
    "        approvalsAutonomy: Array.isArray(approvals?.autonomy) ? approvals.autonomy : [],",
    "        approvalsGuardrails: Array.isArray(approvals?.guardrails) ? approvals.guardrails : [],",
    "        approvalsPending: contentToCount(",
    "            missionPayload?.totals?.approvals_pending,",
    "            contentToCount(approvals?.pending_total, 0),",
    "        ),",
    "        sessions: Array.isArray(sidebarSessions) ? sidebarSessions : [],",
    "        spend: spendState?.payload && typeof spendState.payload === 'object' ? spendState.payload : {},",
    "        goalStats: goalsState?.payload && typeof goalsState.payload === 'object' ? goalsState.payload : {},",
    "        marketplace: moduleGetMarketplaceState(),",
    "    };",
    "}",

"function moduleGetMarketplaceState() {",
"    const state = moduleEnsureRuntime();",
"    if (!state || !state.marketplace || typeof state.marketplace !== 'object') {",
"        return {",
"            apps: [],",
"            modules: [],",
"            loading: false,",
"            error: '',",
"            lastRefreshedAt: 0,",
"            refreshPromise: null,",
"        };",
"    }",
"    return {",
"        apps: Array.isArray(state.marketplace.apps) ? state.marketplace.apps : [],",
"        modules: Array.isArray(state.marketplace.modules) ? state.marketplace.modules : [],",
"        loading: Boolean(state.marketplace.loading),",
"        error: safeString(state.marketplace.error),",
"        lastRefreshedAt: Number(state.marketplace.lastRefreshedAt) || 0,",
"        refreshPromise: state.marketplace.refreshPromise || null,",
"    };",
"}",
"",
 "",
"function moduleFetchJsonSafe(url, options = {}) {",
"    const normalizedUrl = safeString(url);",
"    if (!normalizedUrl) {",
"        return Promise.reject(new Error('Missing request URL'));",
"    }",
"    return fetch(normalizedUrl, {",
"        headers: {",
"            Accept: 'application/json',",
"            ...(options.headers || {}),",
"        },",
"        ...options,",
"    }).then(async (response) => {",
"        const text = await response.text();",
"        let payload = null;",
"        if (text) {",
"            try {",
"                payload = JSON.parse(text);",
"            } catch {",
"                payload = null;",
"            }",
"        }",
"        if (!response.ok) {",
"            const message = safeString(payload?.error) || safeString(payload?.message) || text || `${response.status} ${response.statusText}`;",
"            const err = new Error(message || 'Request failed');",
"            err.status = response.status;",
"            throw err;",
"        }",
"        return payload;",
"    });",
"}",
 "",
"function moduleParseVersionParts(versionRaw) {",
"    const raw = safeString(versionRaw).replace(/^\\s*v/i, '');",
"    const matches = String(raw || '').match(/\\d+/g) || [];",
"    const parts = matches.slice(0, 3).map((part) => {",
"        const n = Number.parseInt(part, 10);",
"        return Number.isFinite(n) ? n : 0;",
        "});",
"    while (parts.length < 3) {",
"        parts.push(0);",
"    }",
"    return parts;",
"}",
 "",
"function moduleIsVersionNewer(candidateRaw, currentRaw) {",
"    const candidate = moduleParseVersionParts(candidateRaw);",
"    const current = moduleParseVersionParts(currentRaw);",
"    for (let i = 0; i < 3; i += 1) {",
"        const c = Number.isFinite(candidate[i]) ? candidate[i] : 0;",
"        const p = Number.isFinite(current[i]) ? current[i] : 0;",
"        if (c > p) return true;",
"        if (c < p) return false;",
"    }",
"    return false;",
"}",
"",
"function moduleMarketplaceSectionId(value) {",
"    const section = safeString(value).toLowerCase();",
"    if (section === 'templates' || section === 'template') return 'templates';",
"    if (section === 'agents' || section === 'agent') return 'agents';",
"    if (section === 'apps' || section === 'app' || section === 'tools') return 'apps';",
"    return 'featured';",
"}",
"",
"function moduleMarketplaceGuessSection(appRaw = {}, moduleId = '', title = '', description = '') {",
"    const hints = [",
"        safeString(appRaw?.section),",
"        safeString(appRaw?.category),",
"        safeString(appRaw?.kind),",
"        safeString(appRaw?.type),",
"        safeString(appRaw?.module_type),",
"        safeString(moduleId),",
"        safeString(title),",
"        safeString(description),",
"    ];",
"    const blob = hints.join(' ').toLowerCase();",
"    if (/(template|workflow|prompt|playbook|preset)/.test(blob)) return 'templates';",
"    if (/(agent|assistant|operator|crew|bot)/.test(blob)) return 'agents';",
"    if (/(integration|tool|connector|plugin|utility|app)/.test(blob)) return 'apps';",
"    return 'featured';",
"}",
"",
"function moduleMarketplaceSectionLabel(sectionRaw = 'featured') {",
"    const section = safeString(sectionRaw).toLowerCase();",
"    if (section === 'templates') return 'Templates';",
"    if (section === 'agents') return 'Agents';",
"    if (section === 'apps') return 'Apps';",
"    return 'Featured';",
"}",
"",
"function moduleLatestReleaseVersion(appRaw) {",
"    const app = appRaw && typeof appRaw === 'object' ? appRaw : {};",
"    const release = app?.latest_release && typeof app.latest_release === 'object' ? app.latest_release : {};",
"    return safeString(release?.module_version || app?.module_version || app?.version);",
"}",
 "",
"function moduleBuildMarketplaceInstalledMap(modulesRaw = []) {",
"    const modules = Array.isArray(modulesRaw) ? modulesRaw : [];",
"    const out = {};",
"    modules.forEach((row) => {",
"        const moduleId = safeString(row?.module_id);",
"        if (!moduleId) return;",
"        out[moduleId] = {",
"            module_id: moduleId,",
"            display_name: safeString(row?.display_name) || moduleId,",
"            description: safeString(row?.description),",
"            version: safeString(row?.version),",
"            status: safeString(row?.status).toLowerCase(),",
"            installed_at: safeString(row?.installed_at),",
"            updated_at: safeString(row?.updated_at),",
"        };",
"    });",
"    return out;",
"}",
 "",
"function moduleRefreshMarketplace({ force = false } = {}) {",
"    const state = moduleEnsureRuntime();",
"    if (!state) return null;",
"    const now = Date.now();",
"    if (!force && state.marketplace.refreshPromise) {",
"        return state.marketplace.refreshPromise;",
"    }",
"    if (",
"        !force &&",
"        Number(state.marketplace.lastRefreshedAt) > 0 &&",
"        now - Number(state.marketplace.lastRefreshedAt) < MODULE_MARKETPLACE_REFRESH_TTL_MS &&",
"        Array.isArray(state.marketplace.apps) &&",
"        Array.isArray(state.marketplace.modules)",
"    ) {",
"        return null;",
 "    }",
"    state.marketplace.loading = true;",
"    state.marketplace.error = '';",
"    const refreshPromise = (async () => {",
"        try {",
"            const [appStorePayload, modulesPayload] = await Promise.all([",
"                moduleFetchJsonSafe('/api/companion/v1/app-store').catch(() => ({ apps: [] })),",
"                moduleFetchJsonSafe('/api/companion/v1/modules').catch(() => ({ modules: [] })),",
"            ]);",
"            state.marketplace.apps = Array.isArray(appStorePayload?.apps) ? appStorePayload.apps : [];",
"            state.marketplace.modules = Array.isArray(modulesPayload?.modules) ? modulesPayload.modules : [];",
"            state.marketplace.error = '';",
"        } catch (error) {",
"            state.marketplace.error = safeString(error?.message) || 'Unable to refresh marketplace catalog.';",
"            if (!Array.isArray(state.marketplace.apps)) state.marketplace.apps = [];",
"            if (!Array.isArray(state.marketplace.modules)) state.marketplace.modules = [];",
"        } finally {",
"            state.marketplace.loading = false;",
"            state.marketplace.refreshPromise = null;",
"            state.marketplace.lastRefreshedAt = Date.now();",
"        }",
"    })();",
"    state.marketplace.refreshPromise = refreshPromise;",
"    return refreshPromise;",
"}",
 "",
"async function moduleToggleMarketplaceModule(moduleIdRaw, enable = false) {",
"    const moduleId = safeString(moduleIdRaw);",
"    if (!moduleId) {",
"        return { ok: false, error: 'Missing module id.' };",
"    }",
"    const action = safeString(enable ? 'enable' : 'disable');",
    "    const url = `/api/companion/v1/modules/${encodeURIComponent(moduleId)}/${action}`;",
"    try {",
"        const result = await moduleFetchJsonSafe(url, { method: 'POST' });",
"        return {",
"            ok: Boolean(result?.ok) === true || safeString(result?.ok) === 'true' || result?.module != null || result?.modules !== undefined,",
"            data: result,",
"        };",
"    } catch (error) {",
"        return {",
"            ok: false,",
"            error: safeString(error?.message) || 'Unable to update module status.',",
"        };",
"    }",
"}",
 
"function moduleBuildMarketplaceRows(snapshot, { limit = 10, section = 'all', search = '' } = {}) {",
"    const apps = Array.isArray(snapshot?.marketplace?.apps) ? snapshot.marketplace.apps : [];",
"    const modules = Array.isArray(snapshot?.marketplace?.modules) ? snapshot.marketplace.modules : [];",
"    const installedById = moduleBuildMarketplaceInstalledMap(modules);",
"    const seen = new Set();",
"    const rows = [];",
"    const targetSection = moduleMarketplaceSectionId(section);",
"    const searchText = safeString(search).trim().toLowerCase();",
    "    const hasSearch = searchText.length > 0;",
    "    const hasSectionFilter = safeString(targetSection).toLowerCase() !== 'all';",
"    const normalizeList = (raw) => {",
"        const list = Array.isArray(raw) ? raw : [];",
"        const out = [];",
"        list.forEach((item) => {",
"            const value = safeString(item);",
"            if (!value) return;",
        "            const lower = value.toLowerCase();",
"            if (!out.includes(lower)) out.push(lower);",
"        });",
"        return out;",
"    };",
"    const addRow = (row) => {",
"        if (!row?.id) return;",
"        const rowSection = safeString(row?.section || row?.sectionLabel);",
"        if (hasSectionFilter && rowSection.toLowerCase() !== targetSection) return;",
"        if (hasSearch) {",
"            const text = [",
"                row?.id,",
"                row?.title,",
"                row?.description,",
"                row?.sectionLabel,",
"                row?.statusLabel,",
"                row?.source,",
"                row?.meta,",
"                ...(Array.isArray(row?.tags) ? row.tags : []),",
"                ...(Array.isArray(row?.requirements) ? row.requirements : []),",
"                ...(Array.isArray(row?.capabilities) ? row.capabilities : []),",
"            ].filter(Boolean).join(' ').toLowerCase();",
"            if (!text.includes(searchText)) return;",
"        }",
"        rows.push(row);",
"    };",
"    apps.forEach((app, index) => {",
"        const moduleId = safeString(app?.module_id);",
"        if (!moduleId || seen.has(moduleId)) return;",
"        const installed = installedById[moduleId];",
"        const installedVersion = safeString(installed?.version);",
"        const latestVersion = moduleLatestReleaseVersion(app);",
"        const appInstall = app?.install && typeof app.install === 'object' ? app.install : {};",
"        const manifestUrl = safeString(appInstall?.release_manifest_endpoint);",
"        const downloadUrl = safeString(appInstall?.release_download_endpoint);",
"        const compatibility = app?.compatibility && typeof app.compatibility === 'object' ? app.compatibility : {};",
"        const eligibleRaw = compatibility?.eligible;",
"        const eligible = safeString(eligibleRaw).toLowerCase() !== 'false' && eligibleRaw !== false;",
"        const isInstalled = Boolean(installed);",
"        const isEnabled = isInstalled && safeString(installed?.status).toLowerCase() === 'enabled';",
"        const needsUpdate = isInstalled && latestVersion && installedVersion && moduleIsVersionNewer(latestVersion, installedVersion);",
"        const sectionId = moduleMarketplaceGuessSection(app, moduleId, title, description);",
"        const title = safeString(app?.display_name) || safeString(app?.module_id) || safeString(app?.name) || `module-${index + 1}`;",
"        const description = safeString(app?.description) || safeString(app?.summary) || safeString(app?.blurb) || 'No description available.';",
"        const source = safeString(app?.publisher) || safeString(app?.author) || safeString(app?.owner) || safeString(appInstall?.repo_url) || safeString(app?.repo_url);",
"        const tags = normalizeList(app?.tags);",
"        const requirements = normalizeList(app?.requirements);",
"        const capabilities = normalizeList(app?.capabilities);",
"        const statusBits = [];",
"        if (!eligible) statusBits.push('Incompatible with this session');",
"        if (installedVersion) statusBits.push(`Installed ${installedVersion}`);",
"        if (latestVersion) statusBits.push(`Latest ${latestVersion}`);",
"        if (needsUpdate) statusBits.push('Update available');",
"        if (source) statusBits.push(`Source ${source}`);",
"        const tone = needsUpdate ? 'warn' : (isInstalled ? (isEnabled ? 'ok' : 'warn') : (eligible ? 'ok' : 'error'));",
"        const badge = isInstalled ? (isEnabled ? 'installed' : 'disabled') : (eligible ? 'available' : 'blocked');",
"        const statusLabel = isInstalled ? (isEnabled ? 'Enabled' : 'Disabled') : (eligible ? 'Available' : 'Blocked');",
"        const actions = [];",
"        if (isInstalled) {",
"            actions.push({",
"                id: isEnabled ? 'disable' : 'enable',",
"                label: isEnabled ? 'Disable' : 'Enable',",
"            });",
"        } else if (eligible && (manifestUrl || downloadUrl)) {",
"            actions.push({",
"                id: 'install',",
"                label: 'Install',",
"                actionUrl: downloadUrl || manifestUrl || source,",
"            });",
"        }",
"        if (manifestUrl || downloadUrl || source) {",
"        actions.push({",
"            id: needsUpdate ? 'latest' : 'latest',",
"            label: needsUpdate ? 'Update' : 'Details',",
"            actionUrl: manifestUrl || downloadUrl || source,",
"        });",
"        }",
"        addRow({",
"            id: moduleId,",
"            section: sectionId,",
"            sectionLabel: moduleMarketplaceSectionLabel(sectionId),",
"            title,",
"            meta: statusBits.slice(0, 4).join(' | '),",
"            description,",
"            badge,",
"            tone,",
"            statusLabel,",
"            installedVersion,",
"            latestVersion,",
"            needsUpdate,",
"            eligible,",
"            isInstalled,",
"            isEnabled,",
"            source,",
"            tags,",
"            requirements,",
"            capabilities,",
"            actions,",
"        });",
"        seen.add(moduleId);",
"    });",
"    modules.forEach((module) => {",
"        const moduleId = safeString(module?.module_id);",
"        if (!moduleId || seen.has(moduleId)) return;",
"        const status = safeString(module?.status).toLowerCase();",
"        const version = safeString(module?.version);",
"        const title = safeString(module?.display_name) || moduleId;",
"        const enabled = status === 'enabled';",
"        const sectionId = moduleMarketplaceGuessSection(module, moduleId, title, safeString(module?.description));",
"        const description = safeString(module?.description) || safeString(module?.meta) || 'Installed module from local runtime.';",
"        const requirements = normalizeList(module?.requirements);",
"        const capabilities = normalizeList(module?.capabilities);",
"        addRow({",
"            id: moduleId,",
"            section: sectionId,",
"            sectionLabel: moduleMarketplaceSectionLabel(sectionId),",
"            title,",
"            meta: version ? `Installed ${version}` : 'Installed locally',",
"            description,",
"            badge: enabled ? 'installed' : 'disabled',",
"            tone: enabled ? 'ok' : 'warn',",
"            statusLabel: enabled ? 'Enabled' : 'Disabled',",
"            installedVersion: version,",
"            needsUpdate: false,",
"            eligible: true,",
"            isInstalled: true,",
"            isEnabled: enabled,",
"            requirements,",
"            capabilities,",
"            actions: [{",
"                id: enabled ? 'disable' : 'enable',",
"                label: enabled ? 'Disable' : 'Enable',",
"            }],",
"        });",
"        seen.add(moduleId);",
"    });",
"    rows.sort((a, b) => safeString(a?.section).localeCompare(safeString(b?.section)) || safeString(a?.title).localeCompare(safeString(b?.title)));",
"    if (limit <= 0) {",
"        return rows;",
    "    }",
"    const safeLimit = Math.max(1, Number(limit) || 0);",
"    return rows.slice(0, safeLimit);",
"}",
 "",
"function moduleEventSort(eventsRaw = []) {",
"    return [...eventsRaw].sort((a, b) => missionToEpoch(b?.ts) - missionToEpoch(a?.ts));",
"}",
    "",
    "function moduleEventNarrative(event) {",
    "    const text = safeString(event?.text);",
    "    const source = safeString(event?.source).replace(/_/g, ' ');",
    "    if (text) return text;",
    "    if (source) return source;",
    "    return 'No details provided.';",
    "}",
    "",
    "function moduleEventTags(event) {",
    "    const text = `${safeString(event?.type)} ${safeString(event?.source)} ${safeString(event?.text)}`.toLowerCase();",
    "    const tags = new Set();",
    "",
    "    if (/(inbox|email|dm|sms|message|thread|reply|respond|follow[ -]?up)/.test(text)) {",
    "        tags.add('inbox');",
    "        tags.add('needs_reply');",
    "    }",
    "    if (/(urgent|critical|p1|sev1|outage|failed|error|blocked|dead|down|panic)/.test(text)) {",
    "        tags.add('urgent');",
    "        tags.add('critical');",
    "        tags.add('errors');",
    "        tags.add('high');",
    "    }",
    "    if (/(approval|approve|guardrail|review|escalat)/.test(text)) {",
    "        tags.add('approvals');",
    "        tags.add('high');",
    "    }",
    "    if (/(newsletter|digest|bulletin|broadcast)/.test(text)) {",
    "        tags.add('newsletter');",
    "        tags.add('fyi');",
    "        tags.add('low');",
    "    }",
    "    if (/(receipt|invoice|payment|subscription|finance|budget|spend)/.test(text)) {",
    "        tags.add('receipts');",
    "        tags.add('finance');",
    "    }",
    "    if (/(workflow|flow|automation|cron|job|run)/.test(text)) {",
    "        tags.add('workflows');",
    "        tags.add('automations');",
    "    }",
    "    if (/(integrat|connector|webhook|oauth|token|scope|api key)/.test(text)) {",
    "        tags.add('integrations');",
    "    }",
    "    if (/(build|deploy|ci|test|pr|issue|repo|commit|code)/.test(text)) {",
    "        tags.add('dev');",
    "    }",
    "    if (/(video|audio|image|render|asset|studio|thumbnail|caption)/.test(text)) {",
    "        tags.add('studio');",
    "    }",
    "    if (/(game|playtest|unity|unreal|godot|npc|level)/.test(text)) {",
    "        tags.add('game');",
    "    }",
    "    if (/(3d|cad|print|mesh|slicer|stl|obj)/.test(text)) {",
    "        tags.add('lab_3d');",
    "    }",
    "    if (/(research|citation|source|brief|analysis|competitor|pdf)/.test(text)) {",
    "        tags.add('research');",
    "    }",
    "    if (/(people|contact|client|vendor|relationship)/.test(text)) {",
    "        tags.add('people');",
    "    }",
    "    if (/(device|mobile|handoff|offline|voice|camera|push|companion)/.test(text)) {",
    "        tags.add('infinite');",
    "    }",
    "    if (/(warn|degrad|retry|delay|pending)/.test(text)) {",
    "        tags.add('high');",
    "    }",
    "",
    "    if (!tags.has('critical') && !tags.has('high') && !tags.has('low')) {",
    "        tags.add('normal');",
    "    }",
    "    if (!tags.size) {",
    "        tags.add('fyi');",
    "        tags.add('normal');",
    "    }",
    "    return tags;",
    "}",
    "",
    "function moduleEventTone(tags) {",
    "    if (tags.has('critical') || tags.has('errors')) return 'error';",
    "    if (tags.has('urgent') || tags.has('high')) return 'warn';",
    "    return 'ok';",
    "}",
    "",
    "function moduleBuildEventRows(eventsRaw = [], { limit = 8, includeTags = [] } = {}) {",
    "    const filters = includeTags.map((tag) => safeString(tag).toLowerCase()).filter(Boolean);",
    "    const rows = [];",
    "    moduleEventSort(eventsRaw).forEach((event, index) => {",
    "        const tags = moduleEventTags(event);",
    "        if (filters.length && !filters.some((tag) => tags.has(tag))) {",
    "            return;",
    "        }",
    "        const typeLabel = safeString(event?.type).replace(/_/g, ' ') || 'event';",
    "        const sourceLabel = safeString(event?.source).replace(/_/g, ' ') || 'signal';",
    "        rows.push({",
    "            id: `event-${missionToEpoch(event?.ts) || Date.now()}-${index}`,",
    "            title: typeLabel,",
    "            meta: `${moduleEventNarrative(event)} | ${missionRelativeTime(event?.ts)}`,",
    "            badge: sourceLabel,",
    "            tone: moduleEventTone(tags),",
    "            tags: Array.from(tags),",
    "            actions: [{ id: 'open', label: 'Open' }, { id: 'ack', label: 'Acknowledge' }],",
    "        });",
    "    });",
    "    return rows.slice(0, Math.max(1, limit));",
    "}",
    "",
    "function moduleBuildJobRows(jobsRaw = [], { limit = 8, recurring = null, keyword = '' } = {}) {",
    "    const keywordLower = safeString(keyword).toLowerCase();",
    "    const rows = [];",
    "    const jobs = [...jobsRaw].sort((a, b) => {",
    "        const byStatus = missionJobStatusRank(a?.status) - missionJobStatusRank(b?.status);",
    "        if (byStatus !== 0) return byStatus;",
    "        return missionToEpoch(b?.updated_at) - missionToEpoch(a?.updated_at);",
    "    });",
    "    jobs.forEach((job, index) => {",
    "        const descriptor = missionScheduleDescriptor(job);",
    "        if (typeof recurring === 'boolean' && descriptor.recurring !== recurring) return;",
    "        const summary = missionJobSummary(job);",
    "        const name = safeString(job?.name) || safeString(job?.id) || 'Mission job';",
    "        const searchText = `${name} ${summary} ${safeString(job?.kind)}`.toLowerCase();",
    "        if (keywordLower && !searchText.includes(keywordLower)) return;",
    "        const status = missionStatusValue(job?.status);",
    "        const tone = (status === 'failed' || status === 'dead' || status === 'cancelled')",
    "            ? 'error'",
    "            : (status === 'awaiting_approval' || status === 'blocked' ? 'warn' : 'ok');",
    "        rows.push({",
    "            id: safeString(job?.id) || `job-${index}`,",
    "            title: name,",
    "            meta: `${summary} | ${descriptor.cadence} | ${descriptor.next === '--' ? 'next --' : `next ${descriptor.next}`}`,",
    "            badge: descriptor.recurring ? 'cron' : 'task',",
    "            tone,",
    "            actions: [{ id: 'open', label: 'Open' }, { id: 'done', label: 'Done' }],",
    "        });",
    "    });",
    "    return rows.slice(0, Math.max(1, limit));",
    "}",
    "",
    "function moduleBuildApprovalRows(snapshot, { limit = 8 } = {}) {",
    "    const rows = [];",
    "    snapshot.approvalsAutonomy.forEach((item, index) => {",
    "        const action = item?.action && typeof item.action === 'object' ? item.action : {};",
    "        rows.push({",
    "            id: safeString(item?.id) || `approval-auto-${index}`,",
    "            title: safeString(action?.title || action?.tool_name || item?.id) || 'Autonomy approval',",
    "            meta: `${safeString(action?.summary) || safeString(item?.decision_reason) || 'Approval required'} | requested ${missionRelativeTime(item?.requested_at)}`,",
    "            badge: 'approval',",
    "            tone: 'warn',",
    "            tags: ['approvals', 'high'],",
    "            actions: [{ id: 'open', label: 'Open' }, { id: 'ack', label: 'Acknowledge' }],",
    "        });",
    "    });",
    "    snapshot.approvalsGuardrails.forEach((item, index) => {",
    "        const tool = safeString(item?.tool_name) || 'tool';",
    "        rows.push({",
    "            id: safeString(item?.tool_call_id || item?.run_id) || `approval-guard-${index}`,",
    "            title: `Tool approval: ${tool}`,",
    "            meta: `${safeString(item?.reason) || 'Guardrails requested review'} | requested ${missionRelativeTime(item?.requested_at)}`,",
    "            badge: 'guardrails',",
    "            tone: 'warn',",
    "            tags: ['approvals', 'high'],",
    "            actions: [{ id: 'open', label: 'Open' }, { id: 'ack', label: 'Acknowledge' }],",
    "        });",
    "    });",
    "    return rows.slice(0, Math.max(1, limit));",
    "}",
    "",
    "function moduleBuildAgentRows(agentsRaw = [], { limit = 8 } = {}) {",
    "    return [...agentsRaw]",
    "        .sort((a, b) => missionStatusRank(a?.status) - missionStatusRank(b?.status))",
    "        .slice(0, Math.max(1, limit))",
    "        .map((agent, index) => {",
    "            const status = missionStatusValue(agent?.status);",
    "            const tone = (status === 'failed' || status === 'dead' || status === 'cancelled')",
    "                ? 'error'",
    "                : (status === 'blocked' || status === 'awaiting_approval' ? 'warn' : 'ok');",
    "            const room = safeString(agent?.room) || 'unassigned';",
    "            return {",
    "                id: safeString(agent?.id) || `agent-${index}`,",
    "                title: safeString(agent?.name) || `Agent ${index + 1}`,",
    "                meta: `${safeString(agent?.summary) || 'No summary'} | room ${room} | ${missionRelativeTime(agent?.updated_at)}`,",
    "                badge: missionStatusLabel(status),",
    "                tone,",
    "                actions: [{ id: 'open', label: 'Open' }, { id: 'done', label: 'Done' }],",
    "            };",
    "        });",
    "}",
    "",
    "function moduleBuildPlatformRows(platformsRaw = [], { limit = 8 } = {}) {",
    "    return [...platformsRaw]",
    "        .slice(0, Math.max(1, limit))",
    "        .map((platform, index) => {",
    "            const connected = contentPlatformConnected(platform);",
    "            const name = safeString(platform?.name) || `platform-${index + 1}`;",
    "            const queued = contentToCount(platform?.queued);",
    "            const running = contentToCount(platform?.running);",
    "            const failed = contentToCount(platform?.failed);",
    "            return {",
    "                id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),",
    "                title: name,",
    "                meta: `${connected ? 'connected' : 'not connected'} | queued ${queued} | running ${running} | failed ${failed}`,",
    "                badge: connected ? 'connected' : 'offline',",
    "                tone: connected ? (failed > 0 ? 'warn' : 'ok') : 'error',",
    "                actions: [{ id: 'open', label: 'Open' }, { id: connected ? 'done' : 'reconnect', label: connected ? 'Done' : 'Reconnect' }],",
    "            };",
    "        });",
    "}",
    "",
    "function moduleBuildWorkflowRows(workflowsRaw = [], { limit = 8 } = {}) {",
    "    return [...workflowsRaw]",
    "        .slice(0, Math.max(1, limit))",
    "        .map((workflow, index) => {",
    "            const name = safeString(workflow?.name) || `workflow-${index + 1}`;",
    "            const trigger = safeString(workflow?.trigger) || 'trigger';",
    "            const approval = safeString(workflow?.approval) || 'no approval policy';",
    "            const active = contentToCount(workflow?.active_jobs);",
    "            const total = contentToCount(workflow?.total_jobs);",
    "            return {",
    "                id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),",
    "                title: name,",
    "                meta: `${trigger} | ${approval} | ${active} active / ${total} total`,",
    "                badge: 'workflow',",
    "                tone: active > 0 ? 'ok' : '',",
    "                actions: [{ id: 'open', label: 'Open' }, { id: 'done', label: 'Done' }],",
    "            };",
    "        });",
    "}",
    "",
    "function moduleBuildSchedulerRows(scheduleRaw = [], { limit = 8 } = {}) {",
    "    return [...scheduleRaw]",
    "        .slice(0, Math.max(1, limit))",
    "        .map((item, index) => {",
    "            const runAt = safeString(item?.run_at);",
    "            const day = safeString(item?.day) || contentFormatScheduleDay(runAt);",
    "            const time = safeString(item?.time) || contentFormatScheduleTime(runAt);",
    "            const platform = safeString(item?.platform || item?.channel) || 'all channels';",
    "            const type = safeString(item?.type || item?.workflow) || 'scheduled content';",
    "            const status = safeString(item?.status) || 'queued';",
    "            const tone = /failed|error|cancel/i.test(status) ? 'error' : (/await|pending/i.test(status) ? 'warn' : 'ok');",
    "            return {",
    "                id: `scheduler-${index}-${platform}`.toLowerCase().replace(/[^a-z0-9-]+/g, '-'),",
    "                title: `${day} ${time} - ${platform}`,",
    "                meta: `${type} | ${status}`,",
    "                badge: 'schedule',",
    "                tone,",
    "                actions: [{ id: 'open', label: 'Open' }, { id: 'done', label: 'Done' }],",
    "            };",
    "        });",
    "}",
    "",
    "function moduleBuildToolRows(toolsRaw = [], { limit = 8 } = {}) {",
    "    return [...toolsRaw]",
    "        .slice(0, Math.max(1, limit))",
    "        .map((tool, index) => {",
    "            const name = safeString(tool?.name) || safeString(tool?.label) || `tool-${index + 1}`;",
    "            const detail = safeString(tool?.description || tool?.detail || tool?.summary) || 'No detail';",
    "            const status = safeString(tool?.status) || '';",
    "            const tone = /fail|error|down|offline/i.test(status)",
    "                ? 'error'",
    "                : (/warn|degrad|pending/i.test(status) ? 'warn' : 'ok');",
    "            return {",
    "                id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),",
    "                title: name,",
    "                meta: status ? `${detail} | ${status}` : detail,",
    "                badge: 'tool',",
    "                tone,",
    "                actions: [{ id: 'open', label: 'Open' }, { id: 'done', label: 'Done' }],",
    "            };",
    "        });",
    "}",
    "",
    "function moduleBuildHealthRows(snapshot, { limit = 8 } = {}) {",
    "    const rows = [];",
    "    const runStore = Boolean(snapshot.missionPayload?.engine?.run_store_enabled);",
    "    const autonomy = Boolean(snapshot.missionPayload?.engine?.autonomy_enabled);",
    "    rows.push({",
    "        id: 'health-engine',",
    "        title: 'Autonomy engine',",
    "        meta: `run-store ${runStore ? 'on' : 'off'} | autonomy ${autonomy ? 'on' : 'off'}`,",
    "        badge: autonomy ? 'online' : 'limited',",
    "        tone: autonomy ? 'ok' : 'warn',",
    "        actions: [{ id: 'open', label: 'Open' }],",
    "    });",
    "    snapshot.healthChecks.forEach((check, index) => {",
    "        const name = safeString(check?.name) || `health-${index + 1}`;",
    "        const status = safeString(check?.status) || 'unknown';",
    "        const detail = safeString(check?.detail) || 'No detail';",
    "        const tone = /fail|error|down|offline/i.test(status)",
    "            ? 'error'",
    "            : (/warn|degrad|pending/i.test(status) ? 'warn' : 'ok');",
    "        rows.push({",
    "            id: `health-check-${index}`,",
    "            title: name,",
    "            meta: `${detail} | ${status}`,",
    "            badge: 'check',",
    "            tone,",
    "            actions: [{ id: 'open', label: 'Open' }, { id: 'ack', label: 'Acknowledge' }],",
    "        });",
    "    });",
    "    if (!snapshot.healthChecks.length) {",
    "        rows.push(...moduleBuildPlatformRows(snapshot.platforms, { limit: 3 }));",
    "    }",
    "    return rows.slice(0, Math.max(1, limit));",
    "}",
    "",
    "function moduleBuildContactContextRows(snapshot) {",
    "    return [",
    "        {",
    "            id: 'contact-sessions',",
    "            title: 'Recent chat session context',",
    "            meta: `${snapshot.sessions.length} sessions currently available in chat history`,",
    "            badge: 'context',",
    "            tone: snapshot.sessions.length > 0 ? 'ok' : 'warn',",
    "            actions: [{ id: 'open', label: 'Open' }],",
    "        },",
    "        {",
    "            id: 'contact-approvals',",
    "            title: 'Open commitments requiring approval',",
    "            meta: `${snapshot.approvalsPending} approvals currently waiting`,",
    "            badge: 'commitments',",
    "            tone: snapshot.approvalsPending > 0 ? 'warn' : 'ok',",
    "            actions: [{ id: 'open', label: 'Open' }],",
    "        },",
    "    ];",
    "}",
    "",
    "function moduleCollectSignals(snapshot = moduleBuildSnapshot()) {",
"    const marketplaceApps = Array.isArray(snapshot.marketplace?.apps) ? snapshot.marketplace.apps : [];",
"    const marketplaceModules = Array.isArray(snapshot.marketplace?.modules) ? snapshot.marketplace.modules : [];",
"    const marketplaceInstalledById = moduleBuildMarketplaceInstalledMap(marketplaceModules);",
"    const cronJobs = snapshot.jobs.filter((job) => missionScheduleDescriptor(job).recurring).length;",
    "    const taskJobs = Math.max(0, snapshot.jobs.length - cronJobs);",
    "    const connected = snapshot.platforms.filter((platform) => contentPlatformConnected(platform)).length;",
    "    const known = contentToCount(snapshot.summary?.known_platforms, snapshot.platforms.length);",
    "    const degraded = Math.max(0, known - connected);",
    "    const workflows = contentToCount(snapshot.summary?.workflows, snapshot.workflows.length);",
    "    const scheduleRows = snapshot.scheduler.length;",
    "    const toolsCount = snapshot.tools.length;",
    "",
    "    let inboxUnread = 0;",
    "    let inboxUrgent = 0;",
    "    let inboxNeedsReply = 0;",
    "    let inboxNewsletters = 0;",
    "    let notifCritical = 0;",
    "    let notifHigh = 0;",
    "    let notifNormal = 0;",
    "    let financeSignals = 0;",
    "    let researchSignals = 0;",
    "    let gameSignals = 0;",
    "    let labSignals = 0;",
    "    let infiniteSignals = 0;",
    "",
    "    snapshot.events.forEach((event) => {",
    "        const tags = moduleEventTags(event);",
    "        if (tags.has('inbox') || tags.has('needs_reply') || tags.has('newsletter') || tags.has('receipts')) inboxUnread += 1;",
    "        if (tags.has('urgent')) inboxUrgent += 1;",
    "        if (tags.has('needs_reply')) inboxNeedsReply += 1;",
    "        if (tags.has('newsletter')) inboxNewsletters += 1;",
    "        if (tags.has('critical')) notifCritical += 1;",
    "        if (tags.has('high')) notifHigh += 1;",
    "        if (tags.has('normal') || tags.has('low')) notifNormal += 1;",
    "        if (tags.has('finance')) financeSignals += 1;",
    "        if (tags.has('research')) researchSignals += 1;",
    "        if (tags.has('game')) gameSignals += 1;",
    "        if (tags.has('lab_3d')) labSignals += 1;",
    "        if (tags.has('infinite')) infiniteSignals += 1;",
    "    });",
    "",
    "    return {",
    "        task_jobs: taskJobs + (snapshot.goalStats?.open_n || 0) + (snapshot.goalStats?.ip_n || 0),",
    "        cron_jobs: cronJobs,",
    "        approvals_pending: snapshot.approvalsPending,",
    "        integrations_connected: connected,",
    "        integrations_degraded: degraded,",
    "        integrations_reconnects: degraded,",
    "        connectors_total: known,",
    "        flow_active: workflows,",
    "        flow_failures: snapshot.jobs.filter((job) => {",
    "            const status = missionStatusValue(job?.status);",
    "            return status === 'failed' || status === 'dead' || status === 'cancelled';",
    "        }).length,",
    "        flow_approvals: snapshot.approvalsPending,",
    "        webhook_rate: snapshot.events.filter((event) => moduleEventTags(event).has('integrations')).length,",
    "        inbox_unread: inboxUnread,",
    "        inbox_urgent: inboxUrgent,",
    "        inbox_needs_reply: inboxNeedsReply,",
    "        inbox_newsletters: inboxNewsletters,",
    "        notif_rules: snapshot.healthChecks.length,",
    "        notif_bundled: notifNormal,",
    "        notif_escalations: notifCritical,",
    "        notif_muted: 0,",
    "        agent_active: snapshot.agents.filter((agent) => {",
    "            const status = missionStatusValue(agent?.status);",
    "            return status === 'running' || status === 'active';",
    "        }).length,",
    "        agent_delegated: snapshot.agents.length,",
    "        agent_approval_only: snapshot.approvalsPending,",
    "        agent_escalations: snapshot.agents.filter((agent) => missionStatusValue(agent?.status) === 'blocked').length,",
    "        render_queue: scheduleRows,",
    "        exports_today: snapshot.events.filter((event) => moduleEventTags(event).has('studio')).length,",
    "        brand_kits: 0,",
    "        assets_total: 0,",
    "        dev_pr_open: snapshot.events.filter((event) => moduleEventTags(event).has('dev')).length,",
    "        dev_failures: snapshot.jobs.filter((job) => missionStatusValue(job?.status) === 'failed').length,",
    "        deploys_today: snapshot.events.filter((event) => /deploy|release/.test(`${safeString(event?.type)} ${safeString(event?.text)}`.toLowerCase())).length,",
    "        hotfixes_open: snapshot.jobs.filter((job) => /hotfix/i.test(safeString(job?.name))).length,",
    "        apps_published: workflows,",
    "        apps_draft: snapshot.jobs.filter((job) => /draft|pending/i.test(safeString(job?.status))).length,",
    "        roles_total: 0,",
    "        game_projects: gameSignals,",
    "        game_playtests: snapshot.events.filter((event) => /playtest/.test(`${safeString(event?.type)} ${safeString(event?.text)}`.toLowerCase())).length,",
    "        game_bugs: snapshot.events.filter((event) => {",
    "            const tags = moduleEventTags(event);",
    "            return tags.has('game') && tags.has('errors');",
    "        }).length,",
    "        game_gen_jobs: snapshot.jobs.filter((job) => /game/i.test(`${safeString(job?.name)} ${safeString(job?.kind)}`)).length,",
    "        print_queue: snapshot.jobs.filter((job) => /print|slice|3d|cad/i.test(`${safeString(job?.name)} ${safeString(job?.kind)}`)).length,",
    "        model_revisions: labSignals,",
    "        materials_total: 0,",
    "        printer_uptime: null,",
    "        research_briefs: researchSignals,",
    "        research_citations: snapshot.events.filter((event) => /citation|source/i.test(`${safeString(event?.text)} ${safeString(event?.type)}`)).length,",
    "        research_competitors: snapshot.events.filter((event) => /competitor/i.test(`${safeString(event?.text)} ${safeString(event?.type)}`)).length,",
    "        research_docs: snapshot.events.filter((event) => { const tags = moduleEventTags(event); return tags.has('research') && /doc|pdf|brief/i.test(safeString(event?.text) + ' ' + safeString(event?.type)); }).length,",
    "        people_contacts: snapshot.sessions.length,",
    "        people_followups: inboxNeedsReply,",
    "        people_at_risk: snapshot.events.filter((event) => /stale|risk|no response/i.test(`${safeString(event?.text)} ${safeString(event?.type)}`.toLowerCase())).length,",
    "        people_commitments: snapshot.approvalsPending,",
    "        finance_burn: snapshot.spend?.total_usd != null ? '$' + Number(snapshot.spend.total_usd).toFixed(2) : null,",
    "        finance_subscriptions: Object.keys(snapshot.spend?.by_model || {}).length || null,",
    "        finance_anomalies: financeSignals,",
    "        finance_approvals: snapshot.approvalsPending,",
    "        webhooks_live: snapshot.healthChecks.filter((check) => /webhook/i.test(safeString(check?.name))).length || connected,",
"        market_installed: marketplaceModules.length,",
"        market_updates: marketplaceApps.reduce((count, app) => {",
"            const moduleId = safeString(app?.module_id);",
"            if (!moduleId) return count;",
"            const installed = marketplaceInstalledById[moduleId];",
"            if (!installed) return count;",
"            const installedVersion = safeString(installed.version || installed?.installed_version || installed?.module_version);",
"            const latestVersion = moduleLatestReleaseVersion(app);",
"            if (installedVersion && latestVersion && moduleIsVersionNewer(latestVersion, installedVersion)) {",
"                return count + 1;",
"            }",
"            return count;",
"        }, 0),",
    "        market_private: marketplaceApps.filter((app) => {",
    "            const access = safeString(app?.access_level).toLowerCase();",
    "            const visibility = safeString(app?.visibility).toLowerCase();",
    "            const compatibility = app?.compatibility && typeof app.compatibility === 'object' ? app.compatibility : {};",
    "            const hasCompatibility = Object.prototype.toString.call(compatibility) === '[object Object]';",
    "            const ineligible = hasCompatibility && !Boolean(compatibility?.eligible);",
    "            return access === 'private' || visibility === 'private' || ineligible;",
    "        }).length,",
    "        market_saves: 0,",
    "        vault_secrets: contentToCount(snapshot.summary?.api_keys_configured, null),",
    "        vault_expiring: 0,",
    "        vault_sources: toolsCount,",
    "        vault_retention: null,",
    "        timeline_events: snapshot.events.length,",
    "        timeline_automated: snapshot.events.filter((event) => /automation|workflow|job|run/.test(`${safeString(event?.type)} ${safeString(event?.text)}`.toLowerCase())).length,",
    "        timeline_approvals: snapshot.approvalsAutonomy.length + snapshot.approvalsGuardrails.length,",
    "        timeline_retries: snapshot.events.filter((event) => /retry/.test(`${safeString(event?.type)} ${safeString(event?.text)}`.toLowerCase())).length,",
    "        devices_paired: 0,",
    "        handoffs_pending: infiniteSignals,",
    "        offline_captures: snapshot.events.filter((event) => /offline|capture/.test(`${safeString(event?.type)} ${safeString(event?.text)}`.toLowerCase())).length,",
    "        push_routes: null,",
    "    };",
    "}",
    "",
    "function moduleResolveMetric(metric, signals) {",
    "    const key = safeString(metric?.key);",
    "    if (!key) return '--';",
    "    if (!Object.prototype.hasOwnProperty.call(signals, key)) return '--';",
    "    const value = signals[key];",
    "    if (value === null || value === undefined) return '--';",
    "    if (typeof value === 'number' && Number.isFinite(value)) return value.toLocaleString();",
    "    const text = safeString(value);",
    "    return text || '--';",
    "}",
    "",
    "function moduleBuildTriage(mode, snapshot) {",
    "    if (mode !== 'inbox' && mode !== 'notifications' && mode !== 'timeline') {",
    "        return null;",
    "    }",
    "    if (mode === 'inbox') {",
    "        return {",
    "            title: 'Triage Modes',",
    "            meta: 'urgent / needs reply / FYI / newsletter / receipts',",
    "            defaultFilter: 'urgent',",
    "            filters: ['all', 'urgent', 'needs_reply', 'fyi', 'newsletter', 'receipts'],",
    "            rows: moduleBuildEventRows(snapshot.events, { limit: 40, includeTags: ['inbox', 'urgent', 'needs_reply', 'newsletter', 'receipts', 'fyi'] }),",
    "        };",
    "    }",
    "    if (mode === 'notifications') {",
    "        return {",
    "            title: 'Severity Queue',",
    "            meta: 'critical / high / normal / low',",
    "            defaultFilter: 'critical',",
    "            filters: ['all', 'critical', 'high', 'normal', 'low'],",
    "            rows: moduleBuildEventRows(snapshot.events, { limit: 40, includeTags: ['critical', 'high', 'normal', 'low'] }),",
    "        };",
    "    }",
    "    return {",
    "        title: 'Timeline Filters',",
    "        meta: 'all / errors / approvals / workflows',",
    "        defaultFilter: 'errors',",
    "        filters: ['all', 'errors', 'approvals', 'workflows'],",
    "        rows: moduleBuildEventRows(snapshot.events, { limit: 40, includeTags: ['errors', 'approvals', 'workflows'] }),",
    "    };",
    "}",
    "",
    "function moduleModeLayout(mode) {",
    "    return safeString(moduleModeSurface(mode)?.layout) || 'hub';",
    "}",
    "",
    "function modulePanelLabels(mode) {",
    "    const labels = {",
    "        queueTitle: 'Priority Queue',",
    "        queueMeta: 'Most relevant work on top',",
    "        healthTitle: 'Health + Status',",
    "        healthMeta: 'Critical checks and integrations',",
    "        actionsTitle: 'Quick Actions',",
    "        actionsMeta: 'Run immediate actions',",
    "        activityTitle: 'Activity',",
    "        activityMeta: 'Recent events and auto updates',",
    "    };",
    "    if (mode === 'inbox') {",
    "        labels.queueTitle = 'Unified Inbox';",
    "        labels.queueMeta = 'Threads requiring action first';",
    "        labels.healthTitle = 'Contact Context';",
    "        labels.healthMeta = 'Commitments and conversation context';",
    "        labels.actionsTitle = 'Thread Actions';",
    "        labels.actionsMeta = 'Summarize, draft, and follow up';",
    "        labels.activityTitle = 'Recent Threads';",
    "        labels.activityMeta = 'Latest communication updates';",
    "    } else if (mode === 'operations') {",
    "        labels.queueTitle = 'Today Queue';",
    "        labels.queueMeta = 'Orders, shifts, and exceptions sorted by urgency';",
    "        labels.healthTitle = 'System + Integrations';",
    "        labels.healthMeta = 'Payment, messaging, and inventory connectors';",
    "        labels.actionsTitle = 'Ops Actions';",
    "        labels.actionsMeta = 'Customer follow-up, reorder, and escalation';",
    "        labels.activityTitle = 'Operations Activity';",
    "        labels.activityMeta = 'Recent operational events and incident notes';",
    "    } else if (mode === 'notifications') {",
    "        labels.queueTitle = 'Notification Rules';",
    "        labels.queueMeta = 'Rules and escalation behavior';",
    "        labels.healthTitle = 'Channel Health';",
    "        labels.healthMeta = 'Push, desktop, and SMS state';",
    "        labels.actionsTitle = 'Notification Controls';",
    "        labels.actionsMeta = 'Snooze, bundle, escalate';",
    "        labels.activityTitle = 'Notification History';",
    "        labels.activityMeta = 'What fired and why';",
    "    } else if (mode === 'automations') {",
    "        labels.queueTitle = 'Flow Queue';",
    "        labels.queueMeta = 'Highest-impact runs and failures';",
    "        labels.healthTitle = 'Runner Health';",
    "        labels.healthMeta = 'Execution and webhook status';",
    "        labels.actionsTitle = 'Builder Actions';",
    "        labels.actionsMeta = 'Create, run, and rollback';",
    "    } else if (mode === 'agents') {",
    "        labels.queueTitle = 'Agent Assignments';",
    "        labels.queueMeta = 'Current delegated responsibilities';",
    "        labels.healthTitle = 'Guardrails';",
    "        labels.healthMeta = 'Permissions and memory boundaries';",
    "    } else if (mode === 'studio' || mode === 'game_studio' || mode === 'lab_3d') {",
    "        labels.queueTitle = 'Production Queue';",
    "        labels.queueMeta = 'Current pipeline stages';",
    "        labels.activityTitle = 'Recent Output';",
    "        labels.activityMeta = 'Latest renders, tests, and runs';",
    "    } else if (mode === 'dev_studio') {",
    "        labels.queueTitle = 'Engineering Queue';",
    "        labels.queueMeta = 'PRs, tests, and deploy tasks';",
    "        labels.healthTitle = 'Delivery Health';",
    "        labels.healthMeta = 'Build, test, deploy state';",
    "    } else if (mode === 'app_builder') {",
    "        labels.queueTitle = 'Build Queue';",
    "        labels.queueMeta = 'Apps and publish readiness';",
    "        labels.healthTitle = 'Connector Health';",
    "        labels.healthMeta = 'Data links and permissions';",
    "    } else if (mode === 'research_lab') {",
    "        labels.queueTitle = 'Research Queue';",
    "        labels.queueMeta = 'Active investigations and briefs';",
    "        labels.activityTitle = 'Research Updates';",
    "        labels.activityMeta = 'Latest findings and source signals';",
    "    } else if (mode === 'people') {",
    "        labels.queueTitle = 'Relationship Queue';",
    "        labels.queueMeta = 'Follow-ups and commitments';",
    "    } else if (mode === 'finance') {",
    "        labels.queueTitle = 'Finance Queue';",
    "        labels.queueMeta = 'Approvals, anomalies, and reconciliation';",
"    } else if (mode === 'integrations') {",
"        labels.queueTitle = 'Connector Queue';",
"        labels.queueMeta = 'Reconnect and scope issues';",
"    } else if (mode === 'marketplace') {",
"        labels.queueTitle = 'Feature Store';",
"        labels.queueMeta = 'Enable and manage installable features';",
"        labels.healthTitle = 'Store Health';",
"        labels.healthMeta = 'Compatibility and version status';",
"        labels.activityTitle = 'Store Activity';",
"        labels.activityMeta = 'Recent installs and updates';",
"    } else if (mode === 'vault') {",
"        labels.queueTitle = 'Security Queue';",
"        labels.queueMeta = 'Secrets, policies, and retention';",
"    } else if (mode === 'timeline') {",
    "        labels.queueTitle = 'Action Timeline';",
    "        labels.queueMeta = 'Most recent actions first';",
    "        labels.actionsTitle = 'Timeline Actions';",
    "        labels.actionsMeta = 'Filter, export, rollback';",
    "    } else if (mode === 'infinite') {",
    "        labels.queueTitle = 'Companion Queue';",
    "        labels.queueMeta = 'Device handoffs and sync';",
    "    }",
    "    return labels;",
    "}",
    "",
    "function moduleBuildDefinition(mode, snapshot, signals) {",
    "    const seed = moduleSeed(mode);",
    "    const state = moduleEnsureRuntime();",
    "    const injectedActivity = Array.isArray(state?.activity?.[mode]) ? state.activity[mode] : [];",
    "    const baseEvents = moduleBuildEventRows(snapshot.events, { limit: 10 });",
    "    const baseJobs = moduleBuildJobRows(snapshot.jobs, { limit: 10 });",
    "    const baseHealth = moduleBuildHealthRows(snapshot, { limit: 10 });",
    "    const baseApprovals = moduleBuildApprovalRows(snapshot, { limit: 8 });",
    "    const basePlatforms = moduleBuildPlatformRows(snapshot.platforms, { limit: 10 });",
"    const baseWorkflows = moduleBuildWorkflowRows(snapshot.workflows, { limit: 10 });",
"    const baseScheduler = moduleBuildSchedulerRows(snapshot.scheduler, { limit: 10 });",
"    const baseAgents = moduleBuildAgentRows(snapshot.agents, { limit: 10 });",
"    const baseTools = moduleBuildToolRows(snapshot.tools, { limit: 10 });",
"    const marketplaceSection = moduleMarketplaceSectionId(safeString(state?.subnavFocus?.marketplace) || 'featured');",
"    const marketplaceSearch = safeString(state?.marketplace?.search);",
    "",
    "    let queueRows = baseJobs;",
    "    let healthRows = baseHealth;",
    "    let activityRows = [...injectedActivity, ...baseEvents].slice(0, 10);",
    "",
    "    if (mode === 'dashboard') {",
    "        queueRows = [...baseJobs.slice(0, 6), ...baseApprovals.slice(0, 4)].slice(0, 8);",
    "    } else if (mode === 'operations') {",
    "        queueRows = [...baseJobs.slice(0, 6), ...moduleBuildEventRows(snapshot.events, { limit: 6, includeTags: ['inbox', 'finance', 'errors'] })].slice(0, 10);",
    "        healthRows = [...basePlatforms.slice(0, 5), ...baseHealth.slice(0, 5)].slice(0, 10);",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['approvals', 'errors', 'inbox', 'finance'] })].slice(0, 10);",
    "    } else if (mode === 'inbox') {",
    "        queueRows = moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['inbox', 'urgent', 'needs_reply', 'newsletter', 'receipts'] });",
    "        healthRows = moduleBuildContactContextRows(snapshot);",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['inbox', 'needs_reply', 'receipts', 'fyi'] })].slice(0, 10);",
    "    } else if (mode === 'notifications') {",
    "        queueRows = moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['critical', 'high', 'normal', 'low'] });",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['critical', 'high', 'errors', 'approvals'] })].slice(0, 10);",
    "    } else if (mode === 'automations') {",
    "        queueRows = [...moduleBuildJobRows(snapshot.jobs, { limit: 8, recurring: true }), ...moduleBuildJobRows(snapshot.jobs, { limit: 8, recurring: false })].slice(0, 10);",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['automations', 'workflows', 'errors'] })].slice(0, 10);",
    "    } else if (mode === 'agents') {",
    "        queueRows = baseAgents;",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['approvals', 'workflows'] })].slice(0, 10);",
    "    } else if (mode === 'studio') {",
    "        queueRows = baseScheduler;",
    "        healthRows = basePlatforms;",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['studio'] })].slice(0, 10);",
    "    } else if (mode === 'dev_studio') {",
    "        queueRows = moduleBuildJobRows(snapshot.jobs, { limit: 10, keyword: 'deploy' });",
    "        if (!queueRows.length) queueRows = moduleBuildJobRows(snapshot.jobs, { limit: 10, keyword: 'test' });",
    "        if (!queueRows.length) queueRows = baseJobs;",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['dev', 'errors', 'workflows'] })].slice(0, 10);",
    "    } else if (mode === 'app_builder') {",
    "        queueRows = baseWorkflows;",
    "        healthRows = basePlatforms;",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['workflows', 'integrations'] })].slice(0, 10);",
    "    } else if (mode === 'game_studio') {",
    "        queueRows = moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['game'] });",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['game', 'errors'] })].slice(0, 10);",
    "    } else if (mode === 'lab_3d') {",
    "        queueRows = moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['lab_3d'] });",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['lab_3d', 'workflows'] })].slice(0, 10);",
    "    } else if (mode === 'research_lab') {",
    "        queueRows = moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['research'] });",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['research', 'workflows'] })].slice(0, 10);",
    "    } else if (mode === 'people') {",
    "        queueRows = moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['people', 'needs_reply', 'inbox'] });",
    "        healthRows = moduleBuildContactContextRows(snapshot);",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['people', 'needs_reply'] })].slice(0, 10);",
    "    } else if (mode === 'finance') {",
    "        queueRows = [...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['finance', 'receipts'] }), ...baseApprovals].slice(0, 10);",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['finance', 'approvals', 'errors'] })].slice(0, 10);",
"    } else if (mode === 'integrations') {",
"        queueRows = basePlatforms;",
"        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['integrations', 'errors'] })].slice(0, 10);",
"    } else if (mode === 'marketplace') {",
"        queueRows = moduleBuildMarketplaceRows(snapshot, { limit: 0, section: marketplaceSection, search: marketplaceSearch });",
"        healthRows = [];",
"        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['marketplace', 'templates', 'packs', 'apps', 'install', 'update', 'workflow'] })].slice(0, 10);",
"    } else if (mode === 'vault') {",
"        queueRows = [...baseApprovals, ...baseHealth].slice(0, 10);",
"        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['approvals', 'integrations', 'errors'] })].slice(0, 10);",
    "    } else if (mode === 'timeline') {",
    "        queueRows = baseEvents;",
    "    } else if (mode === 'infinite') {",
    "        queueRows = moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['infinite'] });",
    "        activityRows = [...injectedActivity, ...moduleBuildEventRows(snapshot.events, { limit: 10, includeTags: ['infinite', 'inbox'] })].slice(0, 10);",
    "    }",
    "",
    "    return {",
    "        ...seed,",
    "        layout: moduleModeLayout(mode),",
    "        panelLabels: modulePanelLabels(mode),",
    "        kpis: (seed.kpis || []).map((metric) => ({ ...metric, value: moduleResolveMetric(metric, signals) })),",
    "        queueRows,",
    "        healthRows,",
    "        activityRows,",
    "        triage: moduleBuildTriage(mode, snapshot),",
    "    };",
    "}",
    "",
    "function moduleRenderEmpty(container, text) {",
    "    if (!container) return;",
    "    container.innerHTML = '';",
    "    const empty = document.createElement('div');",
    "    empty.className = 'module-empty';",
    "    empty.textContent = safeString(text) || 'No items right now.';",
    "    container.appendChild(empty);",
    "}",
    "",
    "function moduleRenderKpis(definition) {",
    "    if (!moduleKpiGrid) return;",
    "    moduleKpiGrid.innerHTML = '';",
    "    const metrics = Array.isArray(definition?.kpis) ? definition.kpis : [];",
    "    if (!metrics.length) {",
    "        moduleRenderEmpty(moduleKpiGrid, 'No KPI metrics available.');",
    "        return;",
    "    }",
    "    const frag = document.createDocumentFragment();",
    "    metrics.forEach((metric) => {",
    "        const card = document.createElement('article');",
    "        card.className = 'module-kpi-card';",
    "        card.innerHTML = `",
    "            <span>${escapeHtml(safeString(metric?.label) || 'Metric')}</span>",
    "            <strong>${escapeHtml(safeString(metric?.value) || '0')}</strong>",
    "            <em>${escapeHtml(safeString(metric?.meta) || '')}</em>",
    "        `;",
    "        frag.appendChild(card);",
    "    });",
    "    moduleKpiGrid.appendChild(frag);",
    "}",
    "",
    "function moduleFocusValue(value) {",
    "    if (value === null || value === undefined) return '--';",
    "    if (typeof value === 'number' && Number.isFinite(value)) return value.toLocaleString();",
    "    const text = safeString(value);",
    "    return text || '--';",
    "}",
    "",
    "function moduleBuildFocusCards(mode, snapshot, signals) {",
    "    const jobs = Array.isArray(snapshot?.jobs) ? snapshot.jobs : [];",
    "    const agents = Array.isArray(snapshot?.agents) ? snapshot.agents : [];",
    "    const events = Array.isArray(snapshot?.events) ? snapshot.events : [];",
    "    const nextRun = [...jobs]",
    "        .map((job) => missionToEpoch(job?.next_run_at))",
    "        .filter((epoch) => Number.isFinite(epoch) && epoch > 0)",
    "        .sort((a, b) => a - b)[0];",
    "    const nextRunMeta = nextRun ? missionRelativeTime(new Date(nextRun).toISOString()) : 'No scheduled run';",
    "    const blockedAgents = agents.filter((agent) => {",
    "        const status = missionStatusValue(agent?.status);",
    "        return status === 'blocked' || status === 'awaiting_approval' || status === 'failed' || status === 'dead';",
    "    }).length;",
    "    const criticalEvents = events.filter((event) => moduleEventTags(event).has('critical')).length;",
    "",
    "    if (mode === 'dashboard') {",
    "        return [",
    "            { label: 'Urgent Signals', value: criticalEvents, meta: 'highest-severity events first', tone: criticalEvents > 0 ? 'warn' : 'ok' },",
    "            { label: 'Active Jobs', value: signals?.task_jobs, meta: 'current workflow tasks', tone: Number(signals?.task_jobs || 0) > 0 ? 'ok' : '' },",
    "            { label: 'Next Run', value: nextRun ? 'Scheduled' : 'None', meta: nextRunMeta, tone: nextRun ? 'ok' : '' },",
    "        ];",
    "    }",
    "    if (mode === 'operations') {",
    "        return [",
    "            { label: 'Open Operations', value: signals?.task_jobs, meta: 'active execution items', tone: Number(signals?.task_jobs || 0) > 0 ? 'ok' : '' },",
    "            { label: 'Exception Load', value: signals?.flow_failures, meta: 'failed or blocked tasks', tone: Number(signals?.flow_failures || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Pending Decisions', value: signals?.approvals_pending, meta: 'requires human approval', tone: Number(signals?.approvals_pending || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'inbox') {",
    "        return [",
    "            { label: 'Urgent', value: signals?.inbox_urgent, meta: 'needs immediate response', tone: Number(signals?.inbox_urgent || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Needs Reply', value: signals?.inbox_needs_reply, meta: 'open commitments', tone: Number(signals?.inbox_needs_reply || 0) > 0 ? 'warn' : '' },",
    "            { label: 'Unread', value: signals?.inbox_unread, meta: 'across channels', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'notifications') {",
    "        return [",
    "            { label: 'Critical', value: signals?.notif_escalations, meta: 'escalation-ready alerts', tone: Number(signals?.notif_escalations || 0) > 0 ? 'error' : 'ok' },",
    "            { label: 'High Priority', value: signals?.notif_bundled, meta: 'batched notification load', tone: '' },",
    "            { label: 'Rules', value: signals?.notif_rules, meta: 'active notification policies', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'automations' || mode === 'app_builder') {",
    "        return [",
    "            { label: 'Failing Runs', value: signals?.flow_failures, meta: 'needs intervention', tone: Number(signals?.flow_failures || 0) > 0 ? 'error' : 'ok' },",
    "            { label: 'Approvals', value: signals?.flow_approvals, meta: 'human gates waiting', tone: Number(signals?.flow_approvals || 0) > 0 ? 'warn' : '' },",
    "            { label: 'Active Flows', value: signals?.flow_active, meta: 'live workflow count', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'agents') {",
    "        return [",
    "            { label: 'Active Agents', value: signals?.agent_active, meta: 'currently executing', tone: Number(signals?.agent_active || 0) > 0 ? 'ok' : '' },",
    "            { label: 'Needs Approval', value: signals?.agent_approval_only, meta: 'cannot auto-execute', tone: Number(signals?.agent_approval_only || 0) > 0 ? 'warn' : '' },",
    "            { label: 'Blocked', value: blockedAgents, meta: 'require intervention', tone: blockedAgents > 0 ? 'error' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'studio' || mode === 'game_studio' || mode === 'lab_3d') {",
    "        return [",
    "            { label: 'Queue', value: signals?.render_queue ?? signals?.print_queue ?? '--', meta: 'work waiting in pipeline', tone: '' },",
    "            { label: 'Failures', value: signals?.flow_failures, meta: 'runs with errors', tone: Number(signals?.flow_failures || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Recent Output', value: signals?.exports_today ?? signals?.game_playtests ?? '--', meta: 'latest generated output', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'dev_studio') {",
    "        return [",
    "            { label: 'Failing Tests', value: signals?.dev_failures, meta: 'CI + local failures', tone: Number(signals?.dev_failures || 0) > 0 ? 'error' : 'ok' },",
    "            { label: 'Open PR Signals', value: signals?.dev_pr_open, meta: 'review workload', tone: '' },",
    "            { label: 'Deploys Today', value: signals?.deploys_today, meta: 'staging + production', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'research_lab') {",
    "        return [",
    "            { label: 'Open Briefs', value: signals?.research_briefs, meta: 'active research tracks', tone: '' },",
    "            { label: 'Citations', value: signals?.research_citations, meta: 'source-backed points', tone: '' },",
    "            { label: 'Competitor Watch', value: signals?.research_competitors, meta: 'tracked references', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'people') {",
    "        return [",
    "            { label: 'Follow-ups', value: signals?.people_followups, meta: 'due now', tone: Number(signals?.people_followups || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'At Risk', value: signals?.people_at_risk, meta: 'stale relationships', tone: Number(signals?.people_at_risk || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Commitments', value: signals?.people_commitments, meta: 'open promises', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'finance') {",
    "        return [",
    "            { label: 'Anomalies', value: signals?.finance_anomalies, meta: 'unusual activity', tone: Number(signals?.finance_anomalies || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Approvals', value: signals?.finance_approvals, meta: 'payments waiting', tone: Number(signals?.finance_approvals || 0) > 0 ? 'warn' : '' },",
    "            { label: 'Subscriptions', value: signals?.finance_subscriptions, meta: 'recurring spend markers', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'integrations') {",
    "        return [",
    "            { label: 'Connected', value: signals?.integrations_connected, meta: 'healthy connectors', tone: 'ok' },",
    "            { label: 'Degraded', value: signals?.integrations_degraded, meta: 'needs reconnect', tone: Number(signals?.integrations_degraded || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Reconnects', value: signals?.integrations_reconnects, meta: 'pending auth fixes', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'marketplace') {",
    "        return [",
    "            { label: 'Installed', value: signals?.market_installed, meta: 'available packs', tone: '' },",
    "            { label: 'Updates', value: signals?.market_updates, meta: 'new versions waiting', tone: Number(signals?.market_updates || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Sources', value: signals?.connectors_total, meta: 'connected capabilities', tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'vault') {",
    "        return [",
    "            { label: 'Secrets', value: signals?.vault_secrets, meta: 'configured credentials', tone: '' },",
    "            { label: 'Expiring', value: signals?.vault_expiring, meta: 'rotation needed', tone: Number(signals?.vault_expiring || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Policy Alerts', value: blockedAgents, meta: 'risk posture checks', tone: blockedAgents > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'timeline') {",
    "        return [",
    "            { label: 'Events 24h', value: signals?.timeline_events, meta: 'auditable receipts', tone: '' },",
    "            { label: 'Automated', value: signals?.timeline_automated, meta: 'agent/workflow actions', tone: '' },",
    "            { label: 'Retries', value: signals?.timeline_retries, meta: 'recovery attempts', tone: Number(signals?.timeline_retries || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'infinite') {",
    "        return [",
    "            { label: 'Handoffs', value: signals?.handoffs_pending, meta: 'cross-device continuation', tone: '' },",
    "            { label: 'Offline Captures', value: signals?.offline_captures, meta: 'awaiting sync', tone: Number(signals?.offline_captures || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Push Routes', value: signals?.push_routes, meta: 'notification routes', tone: '' },",
    "        ];",
    "    }",
    "    return [];",
    "}",
    "",
    "function moduleRenderFocus(cardsRaw) {",
    "    if (!moduleFocusStrip) return;",
    "    const cards = Array.isArray(cardsRaw) ? cardsRaw.filter(Boolean) : [];",
    "    moduleFocusStrip.innerHTML = '';",
    "    if (!cards.length) {",
    "        moduleFocusStrip.classList.add('hidden');",
    "        return;",
    "    }",
    "    moduleFocusStrip.classList.remove('hidden');",
    "    const frag = document.createDocumentFragment();",
    "    cards.forEach((cardRaw) => {",
    "        const tone = moduleToneClass(cardRaw?.tone);",
    "        const card = document.createElement('article');",
    "        card.className = `module-focus-card${tone ? ` ${tone}` : ''}`;",
    "        card.innerHTML = `",
    "            <span>${escapeHtml(safeString(cardRaw?.label) || 'Focus')}</span>",
    "            <strong>${escapeHtml(moduleFocusValue(cardRaw?.value))}</strong>"
].join("\n");
