/* split from part-001.js */
export default [
    "    { id: 'room-pods', label: 'Focus Pods', meta: 'Task swarms + deep work', x: 76, y: 54, w: 18, h: 12, kind: 'work', theme: 'pods', doorX: 76, doorY: 70, hallId: 'hall-south-east' },",
    "    { id: 'room-lobby', label: 'Main Lobby', meta: 'Free roaming + dispatch', x: 56, y: 6, w: 16, h: 10, kind: 'lobby', theme: 'lobby', doorX: 64, doorY: 24, hallId: 'hall-north-mid' },",
    "];",
    "const OFFICE_HALL_NODES = [",
    "    { id: 'hall-north-west', x: 20, y: 24 },",
    "    { id: 'hall-north-mid', x: 48, y: 24 },",
    "    { id: 'hall-north-east', x: 82, y: 24 },",
    "    { id: 'hall-west', x: 20, y: 48 },",
    "    { id: 'hall-center', x: 48, y: 48 },",
    "    { id: 'hall-east', x: 82, y: 48 },",
    "    { id: 'hall-south-west', x: 24, y: 76 },",
    "    { id: 'hall-south-mid', x: 57, y: 76 },",
    "    { id: 'hall-south-east', x: 82, y: 76 },",
    "];",
    "const OFFICE_HALL_EDGES = [",
    "    ['hall-north-west', 'hall-north-mid'],",
    "    ['hall-north-mid', 'hall-north-east'],",
    "    ['hall-north-west', 'hall-west'],",
    "    ['hall-west', 'hall-center'],",
    "    ['hall-center', 'hall-east'],",
    "    ['hall-north-east', 'hall-east'],",
    "    ['hall-north-mid', 'hall-center'],",
    "    ['hall-north-west', 'hall-center'],",
    "    ['hall-north-east', 'hall-center'],",
    "    ['hall-west', 'hall-south-west'],",
    "    ['hall-center', 'hall-south-mid'],",
    "    ['hall-east', 'hall-south-east'],",
    "    ['hall-south-west', 'hall-south-mid'],",
    "    ['hall-south-mid', 'hall-south-east'],",
    "    ['hall-center', 'hall-south-west'],",
    "    ['hall-center', 'hall-south-east'],",
    "];",
    "const OFFICE_CORRIDORS = [",
    "    { x: 16.2, y: 20.2, w: 70.8, h: 7.8, orientation: 'h' },",
    "    { x: 16.2, y: 44.0, w: 70.8, h: 8.4, orientation: 'h' },",
    "    { x: 21.5, y: 72.0, w: 64.8, h: 8.8, orientation: 'h' },",
    "    { x: 16.2, y: 20.2, w: 7.8, h: 60.8, orientation: 'v' },",
    "    { x: 44.1, y: 20.2, w: 8.2, h: 60.8, orientation: 'v' },",
    "    { x: 78.0, y: 20.2, w: 8.2, h: 60.8, orientation: 'v' },",
    "];",
    "const OFFICE_AMBIENT_DECOR = [",
    "    { type: 'tree', x: 1.8, y: 10.4, w: 5.8, h: 8.8 },",
    "    { type: 'tree', x: 1.8, y: 84.2, w: 5.8, h: 8.8 },",
    "    { type: 'tree', x: 95.4, y: 10.4, w: 5.8, h: 8.8 },",
    "    { type: 'tree', x: 95.4, y: 84.2, w: 5.8, h: 8.8 },",
    "    { type: 'windowstrip', x: 24, y: 4.2, w: 18, h: 2.8 },",
    "    { type: 'windowstrip', x: 46, y: 4.2, w: 18, h: 2.8 },",
    "    { type: 'windowstrip', x: 68, y: 4.2, w: 18, h: 2.8 },",
    "    { type: 'planterrow', x: 40, y: 24.6, w: 18, h: 3.4 },",
    "    { type: 'planterrow', x: 22, y: 70.8, w: 12, h: 3.2 },",
    "    { type: 'planterrow', x: 52, y: 70.8, w: 12, h: 3.2 },",
    "    { type: 'planterrow', x: 78, y: 70.8, w: 10, h: 3.2 },",
    "    { type: 'whiteboard', x: 8.4, y: 34, w: 7.2, h: 2.6 },",
    "    { type: 'whiteboard', x: 62.8, y: 34, w: 7.2, h: 2.6 },",
    "    { type: 'bookshelf', x: 8.6, y: 60.2, w: 8.4, h: 3.4 },",
    "    { type: 'bookshelf', x: 88, y: 34, w: 7.2, h: 3.2 },",
    "    { type: 'meetingtable', x: 30.4, y: 41.2, w: 11.2, h: 3.8 },",
    "    { type: 'kiosk', x: 47.8, y: 66, w: 4, h: 4.6 },",
    "    { type: 'watercooler', x: 18.2, y: 72.2, w: 3.3, h: 5 },",
    "    { type: 'watercooler', x: 57.4, y: 72.2, w: 3.3, h: 5 },",
    "    { type: 'vending', x: 12, y: 67.8, w: 3.8, h: 6 },",
    "    { type: 'vending', x: 67.8, y: 67.8, w: 3.8, h: 6 },",
    "    { type: 'sofa', x: 40.6, y: 72.4, w: 10.6, h: 3.2 },",
    "    { type: 'bench', x: 79.8, y: 78.6, w: 8.8, h: 3.1 },",
    "    { type: 'table', x: 26.4, y: 76, w: 4.8, h: 3.4 },",
    "    { type: 'lamp', x: 64, y: 66.8, w: 2.4, h: 4.9 },",
    "    { type: 'lamp', x: 70.2, y: 66.8, w: 2.4, h: 4.9 },",
    "    { type: 'floor-art', x: 35.2, y: 49.4, w: 7.4, h: 3.4 },",
    "    { type: 'floor-art', x: 49.2, y: 49.4, w: 7.4, h: 3.4 },",
    "    { type: 'lounge-rug', x: 33, y: 61.8, w: 26, h: 17.5 },",
    "];",
    "const OFFICE_DYNAMIC_ROOM_SLOTS = [",
    "    { x: 46, y: 84, w: 9, h: 5 },",
    "    { x: 56, y: 84, w: 9, h: 5 },",
    "    { x: 66, y: 84, w: 9, h: 5 },",
    "    { x: 76, y: 84, w: 9, h: 5 },",
    "    { x: 46, y: 90, w: 9, h: 5 },",
    "    { x: 56, y: 90, w: 9, h: 5 },",
    "    { x: 66, y: 90, w: 9, h: 5 },",
    "    { x: 76, y: 90, w: 9, h: 5 },",
    "    { x: 46, y: 95, w: 9, h: 5 },",
    "    { x: 56, y: 95, w: 9, h: 5 },",
    "    { x: 66, y: 95, w: 9, h: 5 },",
    "    { x: 76, y: 95, w: 9, h: 5 },",
    "];",
    "const OFFICE_TASK_ROOM_RULES = [",
    "    { pattern: /\\b(code|coding|bug|fix|refactor|script|api|backend|frontend|test|suite|engineer(?:ing)?)\\b/i, roomId: 'room-engineering' },",
    "    { pattern: /\\b(content|video|youtube|social|post|edit|thumbnail|brand|marketing)\\b/i, roomId: 'room-content' },",
    "    { pattern: /\\b(research|compare|competitor|benchmark|analysis|document|docs|investigate)\\b/i, roomId: 'room-research' },",
    "    { pattern: /\\b(deploy|infra|infrastructure|ops|monitor|reliability|performance|server|hosting)\\b/i, roomId: 'room-ops' },",
    "    { pattern: /\\b(plan|roadmap|strategy|scope|milestone|timeline)\\b/i, roomId: 'room-planning' },",
    "    { pattern: /\\b(support|ticket|customer|feedback|help)\\b/i, roomId: 'room-support' },",
    "    { pattern: /\\b(design|ui|ux|landing|website|visual|brand)\\b/i, roomId: 'room-design' },",
    "    { pattern: /\\b(focus|deep work|pod|quiet)\\b/i, roomId: 'room-pods' },",
    "];",
    "const OFFICE_AGENT_SEEDS = [",
    "    { name: 'Brandon', color: '#9ad8ff', costume: 'visor', tint: 'blue' },",
    "    { name: 'Trey', color: '#9becc9', costume: 'headset', tint: 'green' },",
    "    { name: 'Zach', color: '#ffd49f', costume: 'cap', tint: 'orange' },",
    "    { name: 'Matt', color: '#ffc7eb', costume: 'bowtie', tint: 'pink' },",
    "    { name: 'Taylor', color: '#d7c8ff', costume: 'none', tint: 'purple' },",
    "    { name: 'John', color: '#ffeaa9', costume: 'visor', tint: 'yellow' },",
    "    { name: 'Nova', color: '#9ad8ff', costume: 'cap', tint: 'blue' },",
    "    { name: 'Pixel', color: '#9becc9', costume: 'headset', tint: 'green' },",
    "    { name: 'Byte', color: '#f4c4ff', costume: 'bowtie', tint: 'purple' },",
    "    { name: 'Orbit', color: '#9fd9ff', costume: 'none', tint: 'blue' },",
    "    { name: 'Echo', color: '#b2ffc8', costume: 'visor', tint: 'green' },",
    "    { name: 'Glitch', color: '#ffd0a8', costume: 'cap', tint: 'orange' },",
    "];",
    "const OFFICE_AGENT_STYLE_COLOR_POOL = [",
    "    '#9ad8ff',",
    "    '#9becc9',",
    "    '#ffd49f',",
    "    '#ffc7eb',",
    "    '#d7c8ff',",
    "    '#ffeaa9',",
    "    '#9fd9ff',",
    "    '#b2ffc8',",
    "    '#f4c4ff',",
    "    '#ffd0a8',",
    "    '#a7ffe3',",
    "    '#b7d6ff',",
    "    '#ffd8c2',",
    "    '#e4ceff',",
    "    '#c6f4ff',",
    "];",
    "const OFFICE_AGENT_COSTUME_POOL = ['none', 'cap', 'visor', 'headset', 'bowtie'];",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  VIRTUAL OFFICE DATA                                                    ║",
    "// ║  Agent dialogue trees, robot status sayings, UI notification helpers    ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "const OFFICE_DIALOGUE = {",
    "    startup: [",
    "        'Office simulation online. Local-only mode: no API tokens burned.',",
    "        'Virtual office booted. Agents are clocking in.',",
    "    ],",
    "    queued: [",
    "        'Task queued in {room}: {task}.',",
    "        'Logged new work for {room}.',",
    "        '{task} just hit the board.',",
    "    ],",
    "    pickup: [",
    "        'On it. Heading to {room}.',",
    "        'Routing to {room} now.',",
    "        'Copy that, moving to {room}.',",
    "    ],",
    "    working: [",
    "        'Compiling ideas and caffeine.',",
    "        'Low-key cooking in this room.',",
    "        'Focused mode: do not boop.',",
    "        'If this works first try, everyone acts normal.',",
    "        'Brandon said banana pro is unfair. Noted.',",
    "    ],",
    "    complete: [",
    "        'Task wrapped. Sending result vibes.',",
    "        'Done and documented.',",
    "        'Shipping this one.',",
    "    ],",
    "    break: [",
    "        'Coffee break acquired.',",
    "        'Lunch room debrief in progress.',",
    "        'Quick reset, then back to work.',",
    "    ],",
    "    collision: [",
    "        'Oops, my bad.',",
    "        'Watch out!',",
    "        'Sorry, rerouting.',",
    "        'Friendly traffic jam.',",
    "        'Hallway merge conflict.',",
    "        'My lane, your lane, our lane.',",
    "        'Sorry, boot-skid.',",
    "        'Desk side road rage avoided.',",
    "    ],",
    "    clicked: [",
    "        'Booped! Retreating!',",
    "        'You tapped me. Tactical sprint!',",
    "        'Zoom mode engaged.',",
    "    ],",
    "    mention: [",
    "        'Heard you loud and clear.',",
    "        'Copy that. I can reroute now.',",
    "        'Good call. I will handle it.',",
    "        'Roger. Updating my queue.',",
    "    ],",
    "    mentionStatus: [",
    "        'I have {count} active tasks right now.',",
    "        'Current load: {count} tasks and holding.',",
    "    ],",
    "};",
    "const OFFICE_PERSONA_LIBRARY = {",
    "    blue: {",
    "        working: [",
    "            'Latency low, momentum high.',",
    "            'Code path stabilized and cooking.',",
    "            'Shipping energy confirmed.',",
    "        ],",
    "        break: [",
    "            'Hydration checkpoint.',",
    "            'Coffee patch applied.',",
    "        ],",
    "        socialLead: [",
    "            'Quick sync before we ship this?',",
    "            'Any blockers before next sprint hop?',",
    "        ],",
    "        socialReply: [",
    "            'All clear on my side.',",
    "            'Looks clean. Let us run it.',",
    "        ],",
    "        collision: [",
    "            'Sorry, lane correction.',",
    "            'My pathing glitched for a sec.',",
    "        ],",
    "    },",
    "    green: {",
    "        working: [",
    "            'Research stack is humming.',",
    "            'Scanning options and ranking outcomes.',",
    "            'Signal over noise mode.',",
    "        ],",
    "        break: [",
    "            'Tea protocol engaged.',",
    "            'Recharging social battery for 60 seconds.',",
    "        ],",
    "        socialLead: [",
    "            'Want a quick quality pass?',",
    "            'Can we validate assumptions together?',",
    "        ],",
    "        socialReply: [",
    "            'Yep, that is a solid call.',",
    "            'I can sanity check the edge cases.',",
    "        ],",
    "        collision: [",
    "            'Oops, watch your lane.',"
].join("\n");
