/* app.js lines 15001-16000 */
export default [
    "    }",
    "    if (action.startsWith('focus:')) {",
    "        const roomId = safeString(action.split(':')[1]) || 'room-pods';",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            officeRouteAgentToRoom(agent, roomId, {",
    "                intent: 'wander',",
    "                speed: officeRandomRange(3.2, 4.3),",
    "            });",
    "        });",
    "        const roomLabel = officeRoomById(roomId)?.label || roomId;",
    "        officePushChatLine(`System: Focus wave sent to ${roomLabel}.`);",
    "        officeBusEmit('quick_action.run', { ...eventPayload, roomId }, now);",
    "    }",
    "}",
    "",
    "function officeTouchActivePointers() {",
    "    if (!officeState?.touchGesture?.pointerById) return [];",
    "    return [...officeState.touchGesture.pointerById.values()];",
    "}",
    "",
    "function officeTouchGestureDown(event) {",
    "    if (!officeState?.touchGesture) return;",
    "    const gesture = officeState.touchGesture;",
    "    gesture.pointerById.set(event.pointerId, {",
    "        x: event.clientX,",
    "        y: event.clientY,",
    "    });",
    "    const pointers = officeTouchActivePointers();",
    "    if (pointers.length < 2) {",
    "        gesture.active = true;",
    "        gesture.baseDistance = 0;",
    "        gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "        gesture.lastCenterX = event.clientX;",
    "        gesture.lastCenterY = event.clientY;",
    "        return;",
    "    }",
    "    const a = pointers[0];",
    "    const b = pointers[1];",
    "    gesture.active = true;",
    "    gesture.baseDistance = Math.max(0.001, Math.hypot(b.x - a.x, b.y - a.y));",
    "    gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "    gesture.lastCenterX = (a.x + b.x) / 2;",
    "    gesture.lastCenterY = (a.y + b.y) / 2;",
    "}",
    "",
    "function officeTouchGestureMove(event) {",
    "    if (!officeState?.touchGesture) return false;",
    "    const gesture = officeState.touchGesture;",
    "    if (!gesture.pointerById.has(event.pointerId)) return false;",
    "    gesture.pointerById.set(event.pointerId, {",
    "        x: event.clientX,",
    "        y: event.clientY,",
    "    });",
    "    const pointers = officeTouchActivePointers();",
    "    if (pointers.length >= 2) {",
    "        const a = pointers[0];",
    "        const b = pointers[1];",
    "        const centerX = (a.x + b.x) / 2;",
    "        const centerY = (a.y + b.y) / 2;",
    "        const distance = Math.max(0.001, Math.hypot(b.x - a.x, b.y - a.y));",
    "        if (!gesture.active) {",
    "            gesture.active = true;",
    "            gesture.baseDistance = distance;",
    "            gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "            gesture.lastCenterX = centerX;",
    "            gesture.lastCenterY = centerY;",
    "            return true;",
    "        }",
    "        const ratio = distance / Math.max(0.001, gesture.baseDistance || distance);",
    "        const nextZoom = (gesture.baseZoom || officeState.zoomLevel) * ratio;",
    "        officeSetZoom(nextZoom, {",
    "            anchorClientX: centerX,",
    "            anchorClientY: centerY,",
    "        });",
    "        const deltaX = centerX - (gesture.lastCenterX || centerX);",
    "        const deltaY = centerY - (gesture.lastCenterY || centerY);",
    "        if (Math.abs(deltaX) > 0.2 || Math.abs(deltaY) > 0.2) {",
    "            officePanBy(deltaX, deltaY);",
    "        }",
    "        gesture.lastCenterX = centerX;",
    "        gesture.lastCenterY = centerY;",
    "        return true;",
    "    }",
    "    if (pointers.length === 1 && gesture.active) {",
    "        const pointer = pointers[0];",
    "        const deltaX = pointer.x - (gesture.lastCenterX || pointer.x);",
    "        const deltaY = pointer.y - (gesture.lastCenterY || pointer.y);",
    "        if (Math.abs(deltaX) > 0.1 || Math.abs(deltaY) > 0.1) {",
    "            officePanBy(deltaX, deltaY);",
    "        }",
    "        gesture.lastCenterX = pointer.x;",
    "        gesture.lastCenterY = pointer.y;",
    "        return true;",
    "    }",
    "    return false;",
    "}",
    "",
    "function officeTouchGestureEnd(event) {",
    "    if (!officeState?.touchGesture) return;",
    "    const gesture = officeState.touchGesture;",
    "    gesture.pointerById.delete(event.pointerId);",
    "    const pointers = officeTouchActivePointers();",
    "    if (pointers.length >= 2) {",
    "        const a = pointers[0];",
    "        const b = pointers[1];",
    "        gesture.baseDistance = Math.max(0.001, Math.hypot(b.x - a.x, b.y - a.y));",
    "        gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "        gesture.lastCenterX = (a.x + b.x) / 2;",
    "        gesture.lastCenterY = (a.y + b.y) / 2;",
    "        gesture.active = true;",
    "        return;",
    "    }",
    "    if (pointers.length === 1) {",
    "        const pointer = pointers[0];",
    "        gesture.lastCenterX = pointer.x;",
    "        gesture.lastCenterY = pointer.y;",
    "        gesture.baseDistance = 0;",
    "        gesture.active = true;",
    "        return;",
    "    }",
    "    gesture.active = false;",
    "    gesture.baseDistance = 0;",
    "}",
    "",
    "function officeBindControls() {",
    "    if (!officeState || officeState.controlsBound) return;",
    "    officeState.controlsBound = true;",
    "",
    "    if (officeEditorToggleBtn) {",
    "        officeEditorToggleBtn.addEventListener('click', () => {",
    "            officeSetEditorOpen(true);",
    "        });",
    "    }",
    "    if (officeEditorCloseBtn) {",
    "        officeEditorCloseBtn.addEventListener('click', () => {",
    "            officeSetEditorOpen(false);",
    "        });",
    "    }",
    "    if (officeEditorModal) {",
    "        officeEditorModal.addEventListener('pointerdown', (event) => {",
    "            if (!(event.target instanceof Element)) return;",
    "            if (event.target.closest('.office-editor-card')) return;",
    "            officeSetEditorOpen(false);",
    "        });",
    "        officeEditorModal.addEventListener('keydown', (event) => {",
    "            if (event.key !== 'Tab') return;",
    "            const focusables = [...officeEditorModal.querySelectorAll(",
    "                'button, input, select, textarea, [tabindex]:not([tabindex=\"-1\"])',",
    "            )].filter((node) => !node.hasAttribute('disabled') && !node.classList.contains('hidden'));",
    "            if (!focusables.length) return;",
    "            const first = focusables[0];",
    "            const last = focusables[focusables.length - 1];",
    "            if (event.shiftKey && document.activeElement === first) {",
    "                event.preventDefault();",
    "                last.focus();",
    "                return;",
    "            }",
    "            if (!event.shiftKey && document.activeElement === last) {",
    "                event.preventDefault();",
    "                first.focus();",
    "            }",
    "        });",
    "    }",
    "    document.addEventListener('keydown', (event) => {",
    "        if (event.key === 'Escape') {",
    "            officeSetEditorOpen(false);",
    "        }",
    "    });",
    "",
    "    if (officeChatSendBtn) {",
    "        officeChatSendBtn.addEventListener('click', officeHandleChatSend);",
    "    }",
    "    if (officeChatInput) {",
    "        officeChatInput.addEventListener('keydown', (event) => {",
    "            if (event.key === 'Enter' && !event.shiftKey) {",
    "                event.preventDefault();",
    "                officeHandleChatSend();",
    "            }",
    "        });",
    "    }",
    "",
    "    if (officeAgentSelect) {",
    "        officeAgentSelect.addEventListener('change', () => {",
    "            officeState.selectedAgentId = safeString(officeAgentSelect.value);",
    "            officeSyncCustomizerFields();",
    "            if (safeString(officeState.followAgentId)) {",
    "                officeSetFollowMode(true, officeState.selectedAgentId);",
    "            }",
    "        });",
    "    }",
    "",
    "    if (officeFollowToggleBtn) {",
    "        officeFollowToggleBtn.addEventListener('click', () => {",
    "            const enable = !safeString(officeState?.followAgentId);",
    "            officeSetFollowMode(enable, officeState?.selectedAgentId || '');",
    "        });",
    "    }",
    "",
    "    if (officeMinimapCanvas) {",
    "        const minimapPan = (event) => {",
    "            if (!officeState) return;",
    "            event.preventDefault();",
    "            officePanToMinimapEvent(event);",
    "        };",
    "        const minimapEnd = (event) => {",
    "            if (!officeState?.minimapDrag?.active) return;",
    "            if (event.pointerId !== officeState.minimapDrag.pointerId) return;",
    "            officeState.minimapDrag.active = false;",
    "            officeState.minimapDrag.pointerId = -1;",
    "            if (officeMinimap && officeMinimap.classList) {",
    "                officeMinimap.classList.remove('dragging');",
    "            }",
    "            if (officeMinimapCanvas.hasPointerCapture(event.pointerId)) {",
    "                officeMinimapCanvas.releasePointerCapture(event.pointerId);",
    "            }",
    "        };",
    "        officeMinimapCanvas.addEventListener('pointerdown', (event) => {",
    "            if (!officeState) return;",
    "            if (safeString(officeState.followAgentId)) {",
    "                officeSetFollowMode(false);",
    "            }",
    "            officeState.minimapDrag.active = true;",
    "            officeState.minimapDrag.pointerId = event.pointerId;",
    "            officeMinimapCanvas.setPointerCapture(event.pointerId);",
    "            if (officeMinimap && officeMinimap.classList) {",
    "                officeMinimap.classList.add('dragging');",
    "            }",
    "            minimapPan(event);",
    "        });",
    "        officeMinimapCanvas.addEventListener('pointermove', (event) => {",
    "            if (!officeState?.minimapDrag?.active) return;",
    "            if (event.pointerId !== officeState.minimapDrag.pointerId) return;",
    "            minimapPan(event);",
    "        });",
    "        officeMinimapCanvas.addEventListener('pointerup', minimapEnd);",
    "        officeMinimapCanvas.addEventListener('pointercancel', minimapEnd);",
    "    }",
    "",
    "    if (officeAgentNameInput) {",
    "        officeAgentNameInput.addEventListener('input', () => {",
    "            const agent = officeGetAgentById(officeState.selectedAgentId);",
    "            if (!agent) return;",
    "            const proposed = safeString(officeAgentNameInput.value).slice(0, 24);",
    "            if (!proposed) return;",
    "            const normalized = officeAgentHandle(proposed);",
    "            const duplicate = officeState.agents.find((entry) => (",
    "                entry.id !== agent.id && officeAgentHandle(entry.name) === normalized",
    "            ));",
    "            if (duplicate) {",
    "                const suffix = Math.floor(officeRandomRange(2, 99));",
    "                agent.name = `${proposed.slice(0, 20)} ${suffix}`;",
    "            } else {",
    "                agent.name = proposed;",
    "            }",
    "            officeRenderAgentSelector(agent.id);",
    "            officePersistAgentPrefs();",
    "            officeBusEmit('agent.customized', {",
    "                agentId: agent.id,",
    "                field: 'name',",
    "                value: agent.name,",
    "            });",
    "        });",
    "    }",
    "",
    "    if (officeAgentColorInput) {",
    "        officeAgentColorInput.addEventListener('input', () => {",
    "            const agent = officeGetAgentById(officeState.selectedAgentId);",
    "            if (!agent) return;",
    "            const color = safeString(officeAgentColorInput.value);",
    "            if (!/^#[0-9a-f]{6}$/i.test(color)) return;",
    "            agent.color = color;",
    "            agent.tint = officeAgentTintFromColor(color);",
    "            officeRenderAgents();",
    "            officePersistAgentPrefs();",
    "            officeBusEmit('agent.customized', {",
    "                agentId: agent.id,",
    "                field: 'color',",
    "                value: color,",
    "            });",
    "        });",
    "    }",
    "",
    "    if (officeAgentCostumeSelect) {",
    "        officeAgentCostumeSelect.addEventListener('change', () => {",
    "            const agent = officeGetAgentById(officeState.selectedAgentId);",
    "            if (!agent) return;",
    "            const costume = safeString(officeAgentCostumeSelect.value).toLowerCase();",
    "            if (!['none', 'cap', 'visor', 'headset', 'bowtie'].includes(costume)) return;",
    "            agent.costume = costume;",
    "            officeRenderAgents();",
    "            officePersistAgentPrefs();",
    "            officeBusEmit('agent.customized', {",
    "                agentId: agent.id,",
    "                field: 'costume',",
    "                value: costume,",
    "            });",
    "        });",
    "    }",
    "",
    "    if (officeActionSummonBtn) {",
    "        officeActionSummonBtn.addEventListener('click', () => {",
    "            officeRunQuickAction('summon');",
    "        });",
    "    }",
    "    if (officeActionBreakBtn) {",
    "        officeActionBreakBtn.addEventListener('click', () => {",
    "            officeRunQuickAction('break');",
    "        });",
    "    }",
    "    if (officeActionResumeBtn) {",
    "        officeActionResumeBtn.addEventListener('click', () => {",
    "            officeRunQuickAction('resume');",
    "        });",
    "    }",
    "",
    "    if (officeZoomOutBtn) {",
    "        officeZoomOutBtn.addEventListener('click', () => {",
    "            const baseZoom = Number.isFinite(officeState?.targetZoomLevel) ? officeState.targetZoomLevel : (officeState?.zoomLevel || 1);",
    "            officeSetZoom(baseZoom - OFFICE_ZOOM_STEP);",
    "        });",
    "    }",
    "    if (officeZoomInBtn) {",
    "        officeZoomInBtn.addEventListener('click', () => {",
    "            const baseZoom = Number.isFinite(officeState?.targetZoomLevel) ? officeState.targetZoomLevel : (officeState?.zoomLevel || 1);",
    "            officeSetZoom(baseZoom + OFFICE_ZOOM_STEP);",
    "        });",
    "    }",
    "    if (officeZoomResetBtn) {",
    "        officeZoomResetBtn.addEventListener('click', () => {",
    "            officeResetViewport();",
    "        });",
    "    }",
    "    if (officeDebugToggleBtn) {",
    "        officeDebugToggleBtn.addEventListener('click', () => {",
    "            if (!officeState) return;",
    "            officeState.debugOverlayOpen = !officeState.debugOverlayOpen;",
    "            officeDebugToggleBtn.classList.toggle('active', officeState.debugOverlayOpen);",
    "            officeDebugToggleBtn.setAttribute('aria-pressed', officeState.debugOverlayOpen ? 'true' : 'false');",
    "            officeRenderDebugOverlay();",
    "        });",
    "    }",
    "    if (officeSceneWrap) {",
    "        officeSceneWrap.addEventListener('pointerdown', (event) => {",
    "            if (!officeState) return;",
    "            if (!(event.target instanceof Element)) return;",
    "            if (event.target.closest('.office-agent-hitbox')) return;",
    "            if (event.target.closest('.office-map-controls')) return;",
    "            if (event.target.closest('.office-minimap')) return;",
    "            if (event.target.closest('.office-editor-card')) return;",
    "            if (safeString(officeState.followAgentId)) {",
    "                officeSetFollowMode(false);",
    "            }",
    "",
    "            if (event.pointerType === 'touch') {",
    "                event.preventDefault();",
    "                officeTouchGestureDown(event);",
    "                officeSceneWrap.setPointerCapture(event.pointerId);",
    "                return;",
    "            }",
    "            if (event.button !== 0) return;",
    "",
    "            officeState.dragging = {",
    "                active: true,",
    "                pointerId: event.pointerId,",
    "                lastX: event.clientX,",
    "                lastY: event.clientY,",
    "            };",
    "            officeSceneWrap.classList.add('is-panning');",
    "            officeSceneWrap.setPointerCapture(event.pointerId);",
    "        });",
    "        officeSceneWrap.addEventListener('pointermove', (event) => {",
    "            if (event.pointerType === 'touch') {",
    "                const consumed = officeTouchGestureMove(event);",
    "                if (consumed) {",
    "                    event.preventDefault();",
    "                    return;",
    "                }",
    "            }",
    "            if (!officeState?.dragging?.active) return;",
    "            if (event.pointerId !== officeState.dragging.pointerId) return;",
    "            const deltaX = event.clientX - officeState.dragging.lastX;",
    "            const deltaY = event.clientY - officeState.dragging.lastY;",
    "            officeState.dragging.lastX = event.clientX;",
    "            officeState.dragging.lastY = event.clientY;",
    "            officePanBy(deltaX, deltaY);",
    "        });",
    "        const endDrag = (event) => {",
    "            if (event.pointerType === 'touch') {",
    "                officeTouchGestureEnd(event);",
    "                if (officeSceneWrap.hasPointerCapture(event.pointerId)) {",
    "                    officeSceneWrap.releasePointerCapture(event.pointerId);",
    "                }",
    "            }",
    "            if (!officeState?.dragging?.active) return;",
    "            if (event.pointerId !== officeState.dragging.pointerId) return;",
    "            officeState.dragging.active = false;",
    "            officeSceneWrap.classList.remove('is-panning');",
    "            if (officeSceneWrap.hasPointerCapture(event.pointerId)) {",
    "                officeSceneWrap.releasePointerCapture(event.pointerId);",
    "            }",
    "        };",
    "        officeSceneWrap.addEventListener('pointerup', endDrag);",
    "        officeSceneWrap.addEventListener('pointercancel', endDrag);",
    "        officeSceneWrap.addEventListener('wheel', (event) => {",
    "            if (!officeState) return;",
    "            event.preventDefault();",
    "            const deltaUnit = event.deltaMode === 1 ? 14 : (event.deltaMode === 2 ? 120 : 1);",
    "            const normalizedDelta = officeClamp(event.deltaY * deltaUnit, -220, 220);",
    "            const baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "            const factor = Math.exp(-normalizedDelta * OFFICE_WHEEL_ZOOM_SENSITIVITY);",
    "            officeSetZoom(",
    "                baseZoom * factor,",
    "                { anchorClientX: event.clientX, anchorClientY: event.clientY },",
    "            );",
    "        }, { passive: false });",
    "        officeSceneWrap.addEventListener('keydown', (event) => {",
    "            if (!officeState) return;",
    "            const panStep = event.shiftKey ? 88 : 46;",
    "            if (event.key === 'ArrowLeft') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(panStep, 0);",
    "                return;",
    "            }",
    "            if (event.key === 'ArrowRight') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(-panStep, 0);",
    "                return;",
    "            }",
    "            if (event.key === 'ArrowUp') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(0, panStep);",
    "                return;",
    "            }",
    "            if (event.key === 'ArrowDown') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(0, -panStep);",
    "                return;",
    "            }",
    "            if (event.key === '+' || event.key === '=' || event.key === 'Add') {",
    "                event.preventDefault();",
    "                const baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "                officeSetZoom(baseZoom + OFFICE_ZOOM_STEP);",
    "                return;",
    "            }",
    "            if (event.key === '-' || event.key === '_' || event.key === 'Subtract') {",
    "                event.preventDefault();",
    "                const baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "                officeSetZoom(baseZoom - OFFICE_ZOOM_STEP);",
    "                return;",
    "            }",
    "            if (event.key === '0' || event.key === 'Home') {",
    "                event.preventDefault();",
    "                officeResetViewport();",
    "                return;",
    "            }",
    "            if (event.key === '`' || event.key === 'd' || event.key === 'D') {",
    "                event.preventDefault();",
    "                if (officeDebugToggleBtn) {",
    "                    officeDebugToggleBtn.click();",
    "                }",
    "            }",
    "        });",
    "    }",
    "    window.addEventListener('resize', () => {",
    "        if (!officeState) return;",
    "        officeResetViewport({ preserveZoom: true });",
    "    });",
    "    document.addEventListener('visibilitychange', () => {",
    "        if (!officeState) return;",
    "        if (document.hidden) {",
    "            officeState.hiddenAtEpoch = Date.now();",
    "            officePersistRuntimeState(performance.now(), { force: true });",
    "            return;",
    "        }",
    "        officeState.hiddenAtEpoch = 0;",
    "        officeState.lastWallClockTickAt = Date.now();",
    "        officeRenderAgents();",
    "        if (officeState.tasksDirty) {",
    "            officeState.tasksDirty = false;",
    "            officeRenderTaskList();",
    "        }",
    "        officeUpdateRoomMeta();",
    "        officeRenderMinimap();",
    "        officePersistRuntimeState(performance.now(), { force: true });",
    "    });",
    "    window.addEventListener('beforeunload', () => {",
    "        if (!officeState) return;",
    "        officeStopMissionStream();",
    "        officeStopBackgroundTickTimer();",
    "        officePersistCameraState(Number.POSITIVE_INFINITY);",
    "        officePersistLayoutState();",
    "        officePersistAgentPrefs();",
    "        officePersistRuntimeState(performance.now(), { force: true });",
    "    });",
    "}",
    "",
    "function officeEnsureState() {",
    "    if (officeState) {",
    "        return true;",
    "    }",
    "    if (!officeScene || !officeWorkspace) {",
    "        return false;",
    "    }",
    "",
    "    const now = performance.now();",
    "    const storedLayout = loadStoredOfficeLayoutState();",
    "    const storedRuntime = loadStoredOfficeRuntimeState();",
    "    const dynamicRoomBySlug = new Map();",
    "    let dynamicIndex = 0;",
    "    const rooms = OFFICE_STATIC_ROOMS.map((room) => ({ ...room, dynamic: false }));",
    "    if (Array.isArray(storedLayout?.dynamicRooms)) {",
    "        storedLayout.dynamicRooms.forEach((roomRaw, idx) => {",
    "            const room = officeSanitizeDynamicRoomSnapshot(roomRaw, idx);",
    "            if (!room) return;",
    "            rooms.push(room);",
    "            const idMatch = safeString(room.id).match(/^room-dynamic-(\\d+)$/i);",
    "            const numericIndex = Number(idMatch?.[1]);",
    "            if (Number.isFinite(numericIndex) && numericIndex > dynamicIndex) {",
    "                dynamicIndex = numericIndex;",
    "            }",
    "        });",
    "    }",
    "    if (storedLayout?.dynamicRoomBySlug && typeof storedLayout.dynamicRoomBySlug === 'object') {",
    "        Object.entries(storedLayout.dynamicRoomBySlug).forEach(([slug, roomId]) => {",
    "            const key = safeString(slug);",
    "            const id = safeString(roomId);",
    "            if (!key || !id) return;",
    "            if (!rooms.some((room) => room.id === id)) return;",
    "            dynamicRoomBySlug.set(key, id);",
    "        });",
    "    }",
    "    const roomById = new Map();",
    "    rooms.forEach((room) => {",
    "        roomById.set(room.id, room);",
    "    });",
    "    const { navMap, roomNav } = officeBuildNavGraph(rooms);",
    "    const lobbyCenterId = roomNav.get('room-lobby')?.centerNodeId || '';",
    "    const lobbyCenter = lobbyCenterId ? navMap.get(lobbyCenterId) : null;",
    "    const spawnRoomSequence = [",
    "        'room-engineering',",
    "        'room-content',",
    "        'room-research',",
    "        'room-ops',",
    "        'room-planning',",
    "        'room-support',",
    "        'room-design',",
    "        'room-pods',",
    "        'room-break',",
    "        'room-coffee',",
    "        'room-lobby',",
    "    ].filter((roomId) => roomById.has(roomId));",
    "",
    "    const pickSpawnNodeForAgent = (seed, index) => {",
    "        const preferredRoomId = spawnRoomSequence[index % Math.max(1, spawnRoomSequence.length)] || 'room-lobby';",
    "        const nav = roomNav.get(preferredRoomId);",
    "        const slotNodeIds = Array.isArray(nav?.slotNodeIds) ? nav.slotNodeIds : [];",
    "        if (slotNodeIds.length) {",
    "            const slotIndex = officeStableHash(`${safeString(seed?.name)}|${index}`) % slotNodeIds.length;",
    "            const nodeId = slotNodeIds[slotIndex];",
    "            const node = navMap.get(nodeId);",
    "            if (node) return node;",
    "        }",
    "        const centerNode = navMap.get(nav?.centerNodeId || '');",
    "        if (centerNode) return centerNode;",
    "        return lobbyCenter || null;",
    "    };",
    "",
    "    const agents = OFFICE_AGENT_SEEDS.map((seed, index) => {",
    "        const spawnNode = pickSpawnNodeForAgent(seed, index);",
    "        return ({",
    "        id: `agent-${index + 1}`,",
    "        name: seed.name,",
    "        color: seed.color,",
    "        costume: seed.costume,",
    "        tint: seed.tint || 'blue',",
    "        x: spawnNode ? officeClamp(spawnNode.x + officeRandomRange(-0.18, 0.18), 3, 97) : officeRandomRange(35, 92),",
    "        y: spawnNode ? officeClamp(spawnNode.y + officeRandomRange(-0.18, 0.18), 7, 92) : officeRandomRange(67, 88),",
    "        targetX: 0,",
    "        targetY: 0,",
    "        speed: officeRandomRange(2.35, 3.75),",
    "        facing: officeChance(0.5) ? 1 : -1,",
    "        laneBias: officeRandomRange(-0.65, 0.65),",
    "        state: 'idle',",
    "        intent: 'wander',",
    "        taskId: '',",
    "        workStreak: 0,",
    "        workUntil: 0,",
    "        breakUntil: 0,",
    "        idleUntil: now + (index * 180) + officeRandomRange(450, 1700),",
    "        nextAmbientAt: now + officeRandomRange(3500, 9000),",
    "        nextWorkLineAt: now + officeRandomRange(2400, 6200),",
    "        nextSocialAt: now + officeRandomRange(5000, 14000),",
    "        nextBreakAt: now + officeRandomRange(34_000, 82_000),",
    "        speech: null,",
    "        bumpUntil: 0,",
    "        jumpUntil: 0,",
    "        collisionCooldownUntil: 0,",
    "        crowdReliefUntil: 0,",
    "        yieldUntil: 0,",
    "        yieldResumeIntent: '',",
    "        stuckSince: 0,",
    "        lastMoveX: 0,",
    "        lastMoveY: 0,",
    "        returnAfterRunAt: 0,",
    "        spawnUntil: 0,",
    "        teleportUntil: 0,",
    "        nextTaskRoamAt: 0,",
    "        runawayPhase: '',",
    "        runawayExitX: 0,",
    "        runawayExitY: 0,",
    "        currentNodeId: '',",
    "        routeWaypoints: [],",
    "        routeDestinationNodeId: '',",
    "        reservedLaneEdgeKey: '',",
    "    });",
    "    });",
    "    const storedAgentPrefs = loadStoredOfficeAgentPrefs();",
    "    officeApplyDefaultAgentStyleDiversification(agents, storedAgentPrefs);",
    "    officeApplyStoredAgentPrefs(agents, storedAgentPrefs);",
    "    agents.forEach((agent) => {",
    "        agent.targetX = agent.x;",
    "        agent.targetY = agent.y;",
    "        agent.lastMoveX = agent.x;",
    "        agent.lastMoveY = agent.y;",
    "        agent.currentNodeId = officeFindNearestNode(navMap, agent.x, agent.y);",
    "    });",
    "    const initialMap = officeMapDimensionsForRoomCount(rooms.length);",
    "    const storedCamera = loadStoredOfficeCameraState();",
    "    const storedZoom = Number.isFinite(storedCamera?.zoom) ? officeClamp(storedCamera.zoom, OFFICE_ZOOM_MIN, OFFICE_ZOOM_MAX) : 0.9;",
    "",
    "    officeState = {",
    "        rooms,",
    "        roomById,",
    "        navMap,",
    "        roomNav,",
    "        corridors: [...OFFICE_CORRIDORS],",
    "        dynamicRoomBySlug,",
    "        dynamicIndex,",
    "        agents,",
    "        tasks: [],",
    "        taskCounter: 0,",
    "        chatLines: [],",
    "        officeEvents: [],",
    "        officeBusListeners: new Set(),",
    "        selectedAgentId: agents[0]?.id || '',",
    "        controlsBound: false,",
    "        roomLayerEl: null,",
    "        agentLayerEl: null,",
    "        agentElements: new Map(),",
    "        tasksDirty: true,",
    "        lastRoomMetaSyncAt: 0,",
    "        lastCameraPersistAt: 0,",
    "        lastCameraPersistSignature: '',",
    "        lastRuntimePersistAt: 0,",
    "        lastWallClockTickAt: Date.now(),",
    "        hiddenAtEpoch: 0,",
    "        lastCollisionCooldownPurgeAt: 0,",
    "        nextGlobalSpeechAt: 0,",
    "        collisionSpeechCooldownUntil: 0,",
    "        collisionPairCooldowns: new Map(),",
    "        laneReservations: new Map(),",
    "        lastSocialTickAt: 0,",
    "        nextSocialWindowAt: now + officeRandomRange(1800, 4000),",
    "        debugOverlayOpen: false,",
    "        lastDebugRenderAt: 0,",
    "        debugFrameRate: 0,",
    "        followAgentId: safeString(storedCamera?.followAgentId),",
    "        rafId: 0,",
    "        lastFrameAt: 0,",
    "        active: false,",
    "        backgroundTickTimerId: 0,",
    "        mapWidth: initialMap.width,",
    "        mapHeight: initialMap.height,",
    "        zoomLevel: storedZoom,",
    "        targetZoomLevel: storedZoom,",
    "        panX: Number(storedCamera?.panX) || 0,",
    "        panY: Number(storedCamera?.panY) || 0,",
    "        targetPanX: Number(storedCamera?.panX) || 0,",
    "        targetPanY: Number(storedCamera?.panY) || 0,",
    "        dragging: {",
    "            active: false,",
    "            pointerId: -1,",
    "            lastX: 0,",
    "            lastY: 0,",
    "        },",
    "        minimapDrag: {",
    "            active: false,",
    "            pointerId: -1,",
    "        },",
    "        touchGesture: {",
    "            pointerById: new Map(),",
    "            active: false,",
    "            baseDistance: 0,",
    "            baseZoom: 1,",
    "            lastCenterX: 0,",
    "            lastCenterY: 0,",
    "        },",
    "        stream: {",
    "            connected: false,",
    "            connecting: false,",
    "            retryMs: OFFICE_STREAM_RETRY_MIN_MS,",
    "            reconnectTimer: 0,",
    "            controller: null,",
    "            lastSeq: 0,",
    "            lastMessageAt: 0,",
    "        },",
    "    };",
    "",
    "    officeApplyRuntimeSnapshot(storedRuntime, now);",
    "",
    "    officeRenderScene();",
    "    officeRenderTaskList();",
    "    officeRenderAgentSelector();",
    "    officeBindControls();",
    "    officeResetViewport();",
    "    if (storedCamera) {",
    "        officeState.zoomLevel = storedZoom;",
    "        officeState.targetZoomLevel = storedZoom;",
    "        const clampedPan = officeClampPan(",
    "            Number(storedCamera.panX) || 0,",
    "            Number(storedCamera.panY) || 0,",
    "            storedZoom,",
    "        );",
    "        officeState.panX = clampedPan.panX;",
    "        officeState.panY = clampedPan.panY;",
    "        officeState.targetPanX = clampedPan.panX;",
    "        officeState.targetPanY = clampedPan.panY;",
    "        officeApplyZoom();",
    "    }",
    "    if (safeString(storedCamera?.followAgentId)) {",
    "        officeSetFollowMode(true, storedCamera.followAgentId);",
    "    }",
    "    officeUpdateFollowUi();",
    "    officeSetEditorOpen(false);",
    "    officePushChatLine(officePick(OFFICE_DIALOGUE.startup));",
    "    officePersistCameraState();",
    "    officePersistLayoutState();",
    "    officePersistAgentPrefs();",
    "    officePersistRuntimeState(now, { force: true });",
    "    officeBusEmit('office.booted', {",
    "        rooms: officeState.rooms.length,",
    "        dynamicRooms: officeState.rooms.filter((room) => room.dynamic).length,",
    "        agents: officeState.agents.length,",
    "    });",
    "    officeStartLoop();",
    "    return true;",
    "}",
    "",
    "function officeSyncReducedMotionPreference() {",
    "    if (!officeWorkspace) return;",
    "    const prefersReduced = Boolean(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);",
    "    const prefersHighContrast = Boolean(window.matchMedia && window.matchMedia('(prefers-contrast: more)').matches);",
    "    officeWorkspace.classList.toggle('reduced-motion', prefersReduced);",
    "    officeWorkspace.classList.toggle('high-contrast', prefersHighContrast);",
    "}",
    "",
    "function initOfficeWorkspace() {",
    "    if (!officeScene || !officeWorkspace) return;",
    "    officeEnsureState();",
    "    officeUpdateFollowUi();",
    "    officeRenderMinimap();",
    "    officeSyncReducedMotionPreference();",
    "    if (!officeReducedMotionListenerBound && window.matchMedia) {",
    "        officeReducedMotionListenerBound = true;",
    "        const handler = () => officeSyncReducedMotionPreference();",
    "        const queryList = [",
    "            window.matchMedia('(prefers-reduced-motion: reduce)'),",
    "            window.matchMedia('(prefers-contrast: more)'),",
    "        ];",
    "        queryList.forEach((query) => {",
    "            if (!query) return;",
    "            if (typeof query.addEventListener === 'function') {",
    "                query.addEventListener('change', handler);",
    "            } else if (typeof query.addListener === 'function') {",
    "                query.addListener(handler);",
    "            }",
    "        });",
    "    }",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  MISSION CONTROL                                                        ║",
    "// ║  Agent ops, job tracking, approvals, KPIs, timeline, room load          ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function missionEnsureState() {",
    "    if (missionState) {",
    "        return missionState;",
    "    }",
    "    if (!missionWorkspace) {",
    "        return null;",
    "    }",
    "    missionState = {",
    "        active: false,",
    "        loading: false,",
    "        actionInFlight: false,",
    "        controlsBound: false,",
    "        pollTimerId: 0,",
    "        autoRefresh: true,",
    "        lastPayload: null,",
    "        lastJobsPayload: null,",
    "        lastFetchedAt: 0,",
    "    };",
    "    return missionState;",
    "}",
    "",
    "function missionToEpoch(value) {",
    "    const raw = safeString(value);",
    "    if (!raw) return 0;",
    "    const epoch = Date.parse(raw);",
    "    return Number.isFinite(epoch) ? epoch : 0;",
    "}",
    "",
    "function missionRelativeTime(value) {",
    "    const epoch = missionToEpoch(value);",
    "    if (!epoch) return '--';",
    "    const delta = Date.now() - epoch;",
    "    const abs = Math.abs(delta);",
    "    const minute = 60 * 1000;",
    "    const hour = 60 * minute;",
    "    const day = 24 * hour;",
    "",
    "    if (abs < 45000) return delta >= 0 ? 'just now' : 'soon';",
    "    if (abs < hour) {",
    "        const n = Math.max(1, Math.round(abs / minute));",
    "        return delta >= 0 ? `${n}m ago` : `in ${n}m`;",
    "    }",
    "    if (abs < day) {",
    "        const n = Math.max(1, Math.round(abs / hour));",
    "        return delta >= 0 ? `${n}h ago` : `in ${n}h`;",
    "    }",
    "    const n = Math.max(1, Math.round(abs / day));",
    "    return delta >= 0 ? `${n}d ago` : `in ${n}d`;",
    "}",
    "",
    "function missionStatusValue(statusRaw) {",
    "    return safeString(statusRaw).toLowerCase().replace(/\\s+/g, '_') || 'unknown';",
    "}",
    "",
    "function missionStatusLabel(statusRaw) {",
    "    const normalized = missionStatusValue(statusRaw);",
    "    if (normalized === 'awaiting_approval') return 'awaiting approval';",
    "    return normalized.replace(/_/g, ' ');",
    "}",
    "",
    "function missionStatusRank(statusRaw) {",
    "    const normalized = missionStatusValue(statusRaw);",
    "    const rank = {",
    "        failed: 0,",
    "        dead: 0,",
    "        cancelled: 1,",
    "        blocked: 2,",
    "        awaiting_approval: 3,",
    "        running: 4,",
    "        active: 4,",
    "        queued: 5,",
    "        pending: 5,",
    "        succeeded: 8,",
    "        completed: 8,",
    "    };",
    "    return Object.prototype.hasOwnProperty.call(rank, normalized) ? rank[normalized] : 6;",
    "}",
    "",
    "function missionRoomRank(roomRaw) {",
    "    const room = safeString(roomRaw).toLowerCase();",
    "    const rank = {",
    "        review: 0,",
    "        planning: 1,",
    "        tools: 2,",
    "        files: 3,",
    "        inbox: 4,",
    "        done: 5,",
    "    };",
    "    return Object.prototype.hasOwnProperty.call(rank, room) ? rank[room] : 6;",
    "}",
    "",
    "function missionSetConnectionState(kind = 'neutral', text = 'Standby') {",
    "    if (!missionConnectionPill) return;",
    "    missionConnectionPill.className = `mission-meta-pill ${safeString(kind) || 'neutral'}`;",
    "    missionConnectionPill.textContent = safeString(text) || 'Standby';",
    "}",
    "",
    "function missionRenderEmpty(container, message) {",
    "    if (!container) return;",
    "    container.innerHTML = '';",
    "    const empty = document.createElement('div');",
    "    empty.className = 'mission-item-empty';",
    "    empty.textContent = safeString(message) || 'No data available.';",
    "    container.appendChild(empty);",
    "}",
    "",
    "function missionCreatePill(label, extraClass = '') {",
    "    const pill = document.createElement('span');",
    "    pill.className = `mission-pill ${safeString(extraClass)}`.trim();",
    "    pill.textContent = safeString(label);",
    "    return pill;",
    "}",
    "",
    "function missionFormatSeconds(secondsRaw) {",
    "    const seconds = Number(secondsRaw || 0);",
    "    if (!Number.isFinite(seconds) || seconds <= 0) return '--';",
    "    if (seconds < 60) return `${Math.round(seconds)}s`;",
    "    if (seconds < 3600) return `${Math.round(seconds / 60)}m`;",
    "    if (seconds < 86400) return `${Math.round(seconds / 3600)}h`;",
    "    return `${Math.round(seconds / 86400)}d`;",
    "}",
    "",
    "function missionScheduleDescriptor(job) {",
    "    const schedule = job?.schedule && typeof job.schedule === 'object' ? job.schedule : null;",
    "    const nextRun = safeString(job?.next_run_at);",
    "    if (!schedule) {",
    "        return {",
    "            recurring: false,",
    "            cadence: nextRun ? 'one-time' : 'manual',",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "        };",
    "    }",
    "",
    "    const stype = safeString(schedule?.type).toLowerCase();",
    "    if (stype === 'interval') {",
    "        return {",
    "            recurring: true,",
    "            cadence: `every ${missionFormatSeconds(schedule?.every_seconds)}`,",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "        };",
    "    }",
    "    if (stype === 'daily') {",
    "        const at = safeString(schedule?.at) || '--:--';",
    "        const tz = safeString(schedule?.tz) || 'UTC';",
    "        return {",
    "            recurring: true,",
    "            cadence: `daily ${at}`,",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "            detail: tz,",
    "        };",
    "    }",
    "    if (stype === 'weekly') {",
    "        const at = safeString(schedule?.at) || '--:--';",
    "        const tz = safeString(schedule?.tz) || 'UTC';",
    "        const dows = Array.isArray(schedule?.dow) ? schedule.dow : [];",
    "        const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];",
    "        const dowLabel = dows",
    "            .map((raw) => Number(raw))",
    "            .filter((idx) => Number.isInteger(idx) && idx >= 0 && idx <= 6)",
    "            .slice(0, 7)",
    "            .map((idx) => labels[idx])",
    "            .join(', ');",
    "        return {",
    "            recurring: true,",
    "            cadence: `weekly ${at}`,",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "            detail: `${dowLabel || 'no days'} | ${tz}`,",
    "        };",
    "    }",
    "    if (stype === 'once') {",
    "        return {",
    "            recurring: false,",
    "            cadence: 'one-time',",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "        };",
    "    }",
    "    return {",
    "        recurring: MISSION_RECURRING_SCHEDULE_TYPES.has(stype),",
    "        cadence: stype || 'scheduled',",
    "        next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "    };",
    "}",
    "",
    "function missionJobStatusRank(statusRaw) {",
    "    const status = missionStatusValue(statusRaw);",
    "    const rank = {",
    "        running: 0,",
    "        awaiting_approval: 1,",
    "        queued: 2,",
    "        blocked: 3,",
    "        failed: 4,",
    "        dead: 4,",
    "        cancelled: 5,",
    "        succeeded: 6,",
    "        completed: 6,",
    "    };",
    "    return Object.prototype.hasOwnProperty.call(rank, status) ? rank[status] : 7;",
    "}",
    "",
    "function missionJobSummary(job) {",
    "    const payload = job?.payload && typeof job.payload === 'object' ? job.payload : {};",
    "    return (",
    "        safeString(payload?.goal)",
    "        || safeString(payload?.prompt)",
    "        || safeString(payload?.task)",
    "        || safeString(payload?.message)",
    "        || 'No task summary provided.'",
    "    );",
    "}",
    "",
    "function missionJobActionUrl(jobId, action) {",
    "    const safeId = encodeURIComponent(safeString(jobId));",
    "    if (!safeId) return '';"
].join("\n");
