/* split from part-025.js */
export default [
    "            wb.selectedAssetId = assetId;",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (clipId) {",
    "            wb.selectedClipId = clipId;",
    "            const clip = clipById(clipId);",
    "            if (clip) wb.playhead = clip.start;",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (action === 'copy_audio') {",
    "            moduleWorkbenchCopyText(moduleStudioAudioPresetCommand(wb), 'Comfy Studio Audio Chain');",
    "            pushStudioLog('Copied audio chain command.', 'ok');",
    "            renderLogs();",
    "            return;",
    "        }",
    "        if (action === 'copy_render') {",
    "            moduleWorkbenchCopyText(moduleStudioRenderPresetCommand(wb), 'Comfy Studio Render Command');",
    "            pushStudioLog('Copied render preset command.', 'ok');",
    "            renderLogs();",
    "            return;",
    "        }",
    "        if (action === 'copy_gen') {",
    "            moduleWorkbenchCopyText(moduleStudioGenerationCommand(wb), 'Comfy Studio Generation Command');",
    "            pushStudioLog('Copied generation bridge command.', 'ok');",
    "            renderLogs();",
    "            return;",
    "        }",
    "        if (action === 'queue_preset') {",
    "            const queued = moduleStudioQueueRenderJob(wb, selectedAsset());",
    "            if (queued) pushStudioLog(`Queued ${safeString(queued.name)} with ${safeString(queued.preset)}.`, 'ok');",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (action === 'clear_queue') {",
    "            wb.batchQueue = [];",
    "            pushStudioLog('Cleared render queue.', 'warn');",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (action === 'load') {",
    "            wb.selectedAssetId = assetId;",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (action === 'edit') {",
    "            wb.selectedAssetId = assetId;",
    "            moduleStudioLoadForgeFromPixelAsset(wb, selectedAsset());",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (action === 'insert') {",
    "            const asset = assetById(assetId);",
    "            if (asset) {",
    "                const clip = { id: `clip-${wb.nextId++}`, name: safeString(asset.name), duration: moduleWorkbenchClamp(Number(asset.duration) || 1, 0.5, 900), start: 0 };",
    "                wb.timeline.push(clip);",
    "                wb.selectedClipId = clip.id;",
    "                pushStudioLog(`Inserted clip from ${safeString(asset.name)}.`, 'ok');",
    "            }",
    "        }",
    "        if (action === 'play') setPlaying(!wb.playing);",
    "        if (action === 'stop') {",
    "            setPlaying(false);",
    "            wb.playhead = 0;",
    "        }",
    "        if (action === 'export') {",
    "            moduleWorkbenchCopyJson({",
    "                assets: wb.assets.map((asset) => ({",
    "                    ...asset,",
    "                    url: safeString(asset.url).startsWith('data:') ? '[data-url]' : (asset.url ? '[object-url]' : ''),",
    "                })),",
    "                timeline: wb.timeline,",
    "                duration: recompute(),",
    "            }, 'Comfy Studio Render Queue JSON');",
    "            const queued = wb.batchQueue.find((entry) => safeString(entry.status) === 'queued');",
    "            if (queued) {",
    "                queued.status = 'done';",
    "                queued.eta = 'complete';",
    "                queued.at = moduleWorkbenchTimeStamp();",
    "            }",
    "            pushStudioLog('Export payload copied and queue advanced.', 'ok');",
    "        }",
    "        if (action === 'export_otio') moduleWorkbenchCopyJson(moduleWorkbenchStudioTimelineToOtio(wb), 'Comfy Studio OTIO JSON');",
    "        if (action === 'ffmpeg') moduleWorkbenchCopyText(moduleWorkbenchStudioFfmpegConcatCommand(wb), 'Comfy Studio ffmpeg Concat Command');",
    "        if (action === 'remove') {",
    "            wb.timeline = wb.timeline.filter((clip) => safeString(clip.id) !== safeString(wb.selectedClipId));",
    "            wb.selectedClipId = '';",
    "        }",
    "        if (action === 'left' || action === 'right') {",
    "            const index = wb.timeline.findIndex((clip) => safeString(clip.id) === safeString(wb.selectedClipId));",
    "            if (index >= 0) {",
    "                const next = action === 'left' ? index - 1 : index + 1;",
    "                if (next >= 0 && next < wb.timeline.length) {",
    "                    const tmp = wb.timeline[index];",
    "                    wb.timeline[index] = wb.timeline[next];",
    "                    wb.timeline[next] = tmp;",
    "                }",
    "            }",
    "        }",
    "        renderAll();",
    "    });",
    "    inspector.addEventListener('input', (event) => {",
    "        const target = event.target;",
    "        if (!(target instanceof HTMLInputElement)) return;",
    "        const clip = clipById(wb.selectedClipId);",
    "        if (!clip) return;",
    "        const prop = safeString(target.dataset.studioClipProp);",
    "        if (!prop) return;",
    "        if (prop === 'name') clip.name = safeString(target.value).slice(0, 100);",
    "        if (prop === 'duration') clip.duration = moduleWorkbenchClamp(Number(target.value) || clip.duration, 0.5, 900);",
    "        renderAll();",
    "    });",
    "}",
    "",
    "function moduleDevStudioScanIssues(codeRaw) {",
    "    const code = safeString(codeRaw);",
    "    const lines = code.split(/\\r?\\n/);",
    "    const issues = [];",
    "    if (!code.trim()) {",
    "        issues.push({ tone: 'warn', text: 'Editor is empty.', line: 1 });",
    "    }",
    "    const openCount = (code.match(/{/g) || []).length;",
    "    const closeCount = (code.match(/}/g) || []).length;",
    "    if (openCount !== closeCount) {",
    "        issues.push({ tone: 'error', text: `Brace mismatch: ${openCount} open vs ${closeCount} close.`, line: 1 });",
    "    }",
    "    lines.forEach((line, index) => {",
    "        if (line.includes('TODO')) {",
    "            issues.push({ tone: 'warn', text: 'TODO marker still present.', line: index + 1 });",
    "        }",
    "        if (/console\\.log\\(/.test(line)) {",
    "            issues.push({ tone: 'warn', text: 'Debug console.log found.', line: index + 1 });",
    "        }",
    "    });",
    "    if (!/\\b(test|describe|it)\\s*\\(/.test(code)) {",
    "        issues.push({ tone: 'warn', text: 'No tests detected in this file.', line: 1 });",
    "    }",
    "    if (!issues.length) {",
    "        issues.push({ tone: 'ok', text: 'No obvious static issues.', line: 1 });",
    "    }",
    "    return issues.slice(0, 30);",
    "}",
    "",
    "function moduleWorkbenchDevDockerfileSnippet() {",
    "    return [",
    "        'FROM node:22-alpine',",
    "        'WORKDIR /app',",
    "        'COPY package*.json ./',",
    "        'RUN npm ci --omit=dev',",
    "        'COPY . .',",
    "        'EXPOSE 3000',",
    "        'CMD [\"npm\", \"run\", \"start\"]',",
    "    ].join('\\n');",
    "}",
    "",
    "function moduleRenderWorkbenchDevStudioOss(container, wb) {",
    "    if (!container || !wb) return false;",
    "    if (wb.ossError) return false;",
    "    if (!wb.ossReady || !window.ace?.edit) {",
    "        moduleWorkbenchRenderEngineLoading(",
    "            container,",
    "            'Dev Studio Code Engine',",
    "            'Ace editor with inline diagnostics and build/test actions.',",
    "            'Loading Ace...',",
    "            'Fallback textarea editor opens automatically if Ace fails.',",
    "        );",
    "        if (!wb.ossLoading) {",
    "            wb.ossLoading = true;",
    "            void moduleWorkbenchLoadAce().then(() => {",
    "                wb.ossReady = true;",
    "                wb.ossLoading = false;",
    "                wb.ossError = '';",
    "                moduleWorkbenchRefreshMode('dev_studio');",
    "            }).catch((error) => {",
    "                wb.ossLoading = false;",
    "                wb.ossReady = false;",
    "                wb.ossError = safeString(error?.message) || 'Failed to load Ace.';",
    "                notifyUser('Ace failed to load, using fallback code editor.', { tone: 'warn', durationMs: 2300, debugKind: 'dev-studio' });",
    "                moduleWorkbenchRefreshMode('dev_studio');",
    "            });",
    "        }",
    "        return true;",
    "    }",
    "",
    "    wb.code = safeString(wb.code);",
    "    if (!Array.isArray(wb.logs)) wb.logs = [];",
    "    if (!Array.isArray(wb.issues)) wb.issues = [];",
    "    if (!wb.code.trim()) {",
    "        wb.code = `export async function handler(ctx) {\\n    const data = await ctx.fetch();\\n    return { ok: true, size: Array.isArray(data) ? data.length : 0 };\\n}\\n`;",
    "    }",
    "",
    "    moduleWorkbenchHeader(container, 'Dev Studio Code Engine', 'Thomas executes coding/test pipelines while you review diffs, checks, and build snapshots.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-dev-oss';",
    "    shell.innerHTML = `",
    "        <section class=\"module-wb-stage-card\">",
    "            <div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Code Editor</span><span class=\"module-wb-stage-meta\" data-dev-status></span></div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-dev-action=\"analyze\">Analyze</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-dev-action=\"tests\">Run Tests</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-dev-action=\"build\">Build</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-dev-action=\"format\">Format</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-dev-action=\"snippet\">Snippet</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-dev-action=\"dockerfile\">Dockerfile</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-dev-action=\"export\">Export</button>",
    "            </div>",
    "            <div class=\"module-wb-monaco\" data-dev-monaco></div>",
    "        </section>",
    "        <aside class=\"module-wb-inspector-card\">",
    "            <h4>Issues</h4>",
    "            <div class=\"module-wb-issues\" data-dev-issues></div>",
    "            <h4>Logs</h4>",
    "            <div class=\"module-wb-log-list\" data-dev-logs></div>",
    "        </aside>",
    "        ${moduleWorkbenchRenderOssStack('dev_studio')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const editorWrap = shell.querySelector('[data-dev-monaco]');",
    "    const status = shell.querySelector('[data-dev-status]');",
    "    const issuesEl = shell.querySelector('[data-dev-issues]');",
    "    const logsEl = shell.querySelector('[data-dev-logs]');",
    "    if (!(editorWrap instanceof HTMLElement) || !(status instanceof HTMLElement) || !(issuesEl instanceof HTMLElement) || !(logsEl instanceof HTMLElement)) {",
    "        return false;",
    "    }",
    "",
    "    if (wb.aceEditor?.destroy) {",
    "        try {",
    "            wb.aceEditor.destroy();",
    "        } catch (_error) {}",
    "    }",
    "    editorWrap.innerHTML = '';",
    "",
    "    const ace = window.ace;",
    "    const editor = ace.edit(editorWrap, {",
    "        mode: 'ace/mode/javascript',",
    "        theme: 'ace/theme/tomorrow_night_eighties',",
    "        fontSize: 13,",
    "        showPrintMargin: false,"
].join("\n");
