/* split from part-014.js */
export default [
    "function officeMissionStatusToOfficeState(statusRaw) {",
    "    const status = safeString(statusRaw).toLowerCase();",
    "    if (status === 'active' || status === 'running' || status === 'in_progress') return 'working';",
    "    if (status === 'idle' || status === 'waiting') return 'idle';",
    "    if (status === 'blocked' || status === 'paused') return 'yield';",
    "    if (status === 'break') return 'break';",
    "    return '';",
    "}",
    "",
    "function officeReconcileFromMissionPayload(payload, now = performance.now()) {",
    "    if (!officeState || !payload || typeof payload !== 'object') return false;",
    "    let changed = false;",
    "",
    "    const rooms = Array.isArray(payload.rooms) ? payload.rooms : [];",
    "    rooms.forEach((entry) => {",
    "        const id = safeString(entry?.id);",
    "        if (!id) return;",
    "        const room = officeRoomById(id);",
    "        if (!room) return;",
    "        const nextLabel = safeString(entry?.label);",
    "        if (nextLabel && room.label !== nextLabel) {",
    "            room.label = nextLabel;",
    "            changed = true;",
    "        }",
    "    });",
    "",
    "    const tasks = Array.isArray(payload.tasks) ? payload.tasks : [];",
    "    tasks.forEach((entry) => {",
    "        const id = safeString(entry?.id);",
    "        if (!id) return;",
    "        const existing = officeState.tasks.find((task) => task.id === id);",
    "        if (existing) {",
    "            const nextStatus = safeString(entry?.status).toLowerCase();",
    "            if (nextStatus && nextStatus !== existing.status) {",
    "                existing.status = nextStatus;",
    "                changed = true;",
    "            }",
    "            const assignedAgentId = safeString(entry?.assigned_agent_id || entry?.assignedAgentId);",
    "            if (assignedAgentId && existing.assignedAgentId !== assignedAgentId) {",
    "                existing.assignedAgentId = assignedAgentId;",
    "                changed = true;",
    "            }",
    "            return;",
    "        }",
    "        const label = safeString(entry?.title || entry?.name || id);",
    "        const roomId = safeString(entry?.room || entry?.room_id || 'room-lobby');",
    "        const room = officeRoomById(roomId) || officeRoomById('room-lobby');",
    "        officeState.tasks.push({",
    "            id,",
    "            title: officeTaskTitle(label),",
    "            rawText: label,",
    "            source: 'mission-stream',",
    "            roomId: room?.id || 'room-lobby',",
    "            roomLabel: room?.label || 'Main Lobby',",
    "            status: safeString(entry?.status).toLowerCase() || 'queued',",
    "            assignedAgentId: safeString(entry?.assigned_agent_id || entry?.assignedAgentId),",
    "            createdAt: Date.now(),",
    "            startedAt: 0,",
    "            completedAt: 0,",
    "        });",
    "        changed = true;",
    "    });",
    "",
    "    const agents = Array.isArray(payload.agents) ? payload.agents : [];",
    "    agents.forEach((entry) => {",
    "        const remoteId = safeString(entry?.id);",
    "        const remoteName = safeString(entry?.name);",
    "        const local = officeState.agents.find((agent) => (",
    "            (remoteId && agent.id === remoteId)",
    "            || (remoteName && officeAgentHandle(agent.name) === officeAgentHandle(remoteName))",
    "        ));",
    "        if (!local) return;",
    "        const mappedState = officeMissionStatusToOfficeState(entry?.status);",
    "        if (!mappedState) return;",
    "        local.remoteStatus = mappedState;",
    "        if (local.taskId) return;",
    "        if (mappedState === 'working' && local.state === 'idle') {",
    "            local.state = 'working';",
    "            local.workUntil = now + officeRandomRange(2800, 6400);",
    "            local.nextWorkLineAt = now + officeRandomRange(1400, 2600);",
    "            changed = true;",
    "        } else if (mappedState === 'break' && local.state === 'idle') {",
    "            local.state = 'break';",
    "            local.breakUntil = now + officeRandomRange(1900, 4600);",
    "            local.nextWorkLineAt = now + officeRandomRange(900, 1800);",
    "            changed = true;",
    "        } else if (mappedState === 'yield' && local.state === 'walking') {",
    "            officeSetYieldState(local, now, officeRandomRange(-0.8, 0.8), officeRandomRange(-0.8, 0.8));",
    "            changed = true;",
    "        }",
    "    });",
    "",
    "    if (changed) {",
    "        officeTrimTasks();",
    "        officeState.tasksDirty = true;",
    "    }",
    "    return changed;",
    "}",
    "",
    "function officeHandleMissionStreamLine(lineRaw) {",
    "    if (!officeState) return;",
    "    const line = safeString(lineRaw);",
    "    if (!line) return;",
    "    let parsed = null;",
    "    try {",
    "        parsed = JSON.parse(line);",
    "    } catch {",
    "        return;",
    "    }",
    "    if (!parsed || typeof parsed !== 'object') return;",
    "    const type = safeString(parsed.type).toLowerCase() || 'snapshot';",
    "    const seq = Number(parsed.seq) || 0;",
    "    if (type === 'snapshot' && parsed.payload && typeof parsed.payload === 'object') {",
    "        const changed = officeReconcileFromMissionPayload(parsed.payload);",
    "        officeState.stream.lastSeq = seq || officeState.stream.lastSeq;",
    "        officeBusEmit('stream.snapshot', {",
    "            seq,",
    "            changed,",
    "        });",
    "        return;",
    "    }",
    "    officeBusEmit('stream.event', {",
    "        type,",
    "        seq,",
    "    });",
    "}",
    "",
    "function officeScheduleMissionStreamReconnect(delayMs = 0) {",
    "    if (!officeState?.stream || !officeState.active) return;",
    "    const stream = officeState.stream;",
    "    if (stream.reconnectTimer) return;",
    "    const retryMs = delayMs > 0",
    "        ? delayMs",
    "        : officeClamp(Number(stream.retryMs) || OFFICE_STREAM_RETRY_MIN_MS, OFFICE_STREAM_RETRY_MIN_MS, OFFICE_STREAM_RETRY_MAX_MS);",
    "    stream.retryMs = Math.min(OFFICE_STREAM_RETRY_MAX_MS, Math.round(retryMs * 1.75));",
    "    stream.reconnectTimer = window.setTimeout(() => {",
    "        if (!officeState?.stream) return;",
    "        officeState.stream.reconnectTimer = 0;",
    "        void officeStartMissionStream();",
    "    }, retryMs);",
    "}",
    "",
    "function officeStopMissionStream() {",
    "    if (!officeState?.stream) return;",
    "    const stream = officeState.stream;",
    "    if (stream.reconnectTimer) {",
    "        window.clearTimeout(stream.reconnectTimer);",
    "        stream.reconnectTimer = 0;",
    "    }",
    "    if (stream.controller) {",
    "        try {",
    "            stream.controller.abort();",
    "        } catch {",
    "            // Ignore abort failures.",
    "        }",
    "    }",
    "    stream.connected = false;",
    "    stream.connecting = false;",
    "    stream.controller = null;",
    "}",
    "",
    "async function officeStartMissionStream() {",
    "    if (!officeState?.stream || !officeState.active) return;",
    "    const stream = officeState.stream;",
    "    if (stream.connecting || stream.connected) return;",
    "    if (typeof fetch !== 'function' || typeof TextDecoder === 'undefined') return;",
    "",
    "    stream.connecting = true;",
    "    const controller = new AbortController();",
    "    stream.controller = controller;",
    "    const url = '/api/mission/stream?interval=1.8';",
    "",
    "    try {",
    "        const response = await fetch(url, {",
    "            method: 'GET',",
    "            headers: {",
    "                Accept: 'application/x-ndjson',",
    "            },",
    "            signal: controller.signal,",
    "            cache: 'no-store',",
    "        });",
    "        if (!response.ok || !response.body) {",
    "            throw new Error(`mission_stream_http_${response.status}`);",
    "        }",
    "",
    "        stream.connected = true;",
    "        stream.connecting = false;",
    "        stream.retryMs = OFFICE_STREAM_RETRY_MIN_MS;",
    "        stream.lastMessageAt = Date.now();",
    "        officeBusEmit('stream.connected', { url });",
    "",
    "        const reader = response.body.getReader();",
    "        const decoder = new TextDecoder();",
    "        let buffer = '';",
    "",
    "        while (officeState && officeState.active && !controller.signal.aborted) {",
    "            const { done, value } = await reader.read();",
    "            if (done) break;",
    "            stream.lastMessageAt = Date.now();",
    "            buffer += decoder.decode(value, { stream: true });",
    "            let newlineIndex = buffer.indexOf('\\n');",
    "            while (newlineIndex >= 0) {",
    "                const line = buffer.slice(0, newlineIndex).trim();",
    "                buffer = buffer.slice(newlineIndex + 1);",
    "                if (line) {",
    "                    officeHandleMissionStreamLine(line);",
    "                }",
    "                newlineIndex = buffer.indexOf('\\n');",
    "            }",
    "        }",
    "    } catch (error) {",
    "        if (!controller.signal.aborted) {",
    "            officeBusEmit('stream.error', {",
    "                reason: safeString(error?.message || error),",
    "            });",
    "        }",
    "    } finally {",
    "        if (!officeState?.stream) return;",
    "        stream.connected = false;",
    "        stream.connecting = false;",
    "        stream.controller = null;",
    "        if (officeState.active) {",
    "            officeScheduleMissionStreamReconnect();",
    "        }",
    "    }",
    "}",
    "",
    "function officeTickAgent(agent, now, dt) {",
    "    if (!agent) return;",
    "    if (agent.state !== 'runaway') {",
    "        officeSafeguardAgentPosition(agent, now, { reroute: false });",
    "    }",
    "    if (agent.state === 'runaway') {",
    "        const arrived = officeMoveAgent(agent, dt);",
    "        if (arrived && safeString(agent.runawayPhase) === 'to-hall') {",
    "            agent.runawayPhase = 'exiting';",
    "            officeSetAgentTarget(agent, agent.runawayExitX, agent.runawayExitY, {",
    "                intent: 'runaway',",
    "                speed: officeRandomRange(5.8, 7.2),",
    "            });"
].join("\n");
