/* split from part-021.js */
export default [
    "                    transform.setTranslationSnap(null);",
    "                    transform.setRotationSnap(null);",
    "                    transform.setScaleSnap(null);",
    "                }",
    "                gridHelper.visible = wb.showGrid;",
    "                rebuildScene();",
    "                renderInspector();",
    "                renderStatus();",
    "                renderProjectSelect();",
    "                notifyUser(`Loaded model project: ${safeString(project.name)}.`, { tone: 'success', durationMs: 1700, debugKind: 'lab3d' });",
    "                return;",
    "            }",
    "            if (action === 'delete') {",
    "                if (!selectedId) return;",
    "                if (moduleWorkbenchProjectDelete('lab_3d', selectedId)) {",
    "                    wb.selectedProjectId = '';",
    "                    renderProjectSelect();",
    "                    notifyUser('Deleted model project.', { tone: 'warn', durationMs: 1600, debugKind: 'lab3d' });",
    "                }",
    "                return;",
    "            }",
    "        }",
    "        const target = event.target instanceof Element ? event.target.closest('[data-lab3d-add], [data-lab3d-transform], [data-lab3d-action]') : null;",
    "        if (!target) return;",
    "        const addType = safeString(target.dataset.lab3dAdd);",
    "        const transformMode = safeString(target.dataset.lab3dTransform);",
    "        const action = safeString(target.dataset.lab3dAction).toLowerCase();",
    "        if (addType) {",
    "            addMesh(addType);",
    "            return;",
    "        }",
    "        if (transformMode) {",
    "            wb.transformMode = transformMode;",
    "            transform.setMode(transformMode);",
    "            shell.querySelectorAll('[data-lab3d-transform]').forEach((button) => button.classList.toggle('active', safeString(button.dataset.lab3dTransform) === transformMode));",
    "            renderStatus();",
    "            return;",
    "        }",
    "        if (action === 'snap') {",
    "            wb.transformSnap = !wb.transformSnap;",
    "            if (wb.transformSnap) {",
    "                transform.setTranslationSnap(0.25);",
    "                transform.setRotationSnap(Math.PI / 12);",
    "                transform.setScaleSnap(0.1);",
    "            } else {",
    "                transform.setTranslationSnap(null);",
    "                transform.setRotationSnap(null);",
    "                transform.setScaleSnap(null);",
    "            }",
    "            renderStatus();",
    "            return;",
    "        }",
    "        if (action === 'space') {",
    "            wb.transformSpace = wb.transformSpace === 'local' ? 'world' : 'local';",
    "            transform.setSpace(wb.transformSpace);",
    "            renderStatus();",
    "            return;",
    "        }",
    "        if (action === 'wireframe') {",
    "            wb.wireframe = !wb.wireframe;",
    "            applyMaterialVisuals();",
    "            renderStatus();",
    "            return;",
    "        }",
    "        if (action === 'grid') {",
    "            wb.showGrid = !wb.showGrid;",
    "            gridHelper.visible = wb.showGrid;",
    "            renderStatus();",
    "            return;",
    "        }",
    "        if (action === 'import_json') {",
    "            if (importInput instanceof HTMLInputElement) {",
    "                importInput.click();",
    "            }",
    "            return;",
    "        }",
    "        if (action === 'delete' && wb.selectedId) {",
    "            wb.objects = wb.objects.filter((spec) => safeString(spec.id) !== safeString(wb.selectedId));",
    "            wb.selectedId = wb.objects[0] ? safeString(wb.objects[0].id) : '';",
    "            rebuildScene();",
    "            renderInspector();",
    "            renderStatus();",
    "        }",
    "        if (action === 'export') {",
    "            syncAllSpecs();",
    "            moduleWorkbenchCopyJson({ units: wb.units, objects: wb.objects }, '3D Lab Scene JSON');",
    "        }",
    "        if (action === 'export_gltf') {",
    "            syncAllSpecs();",
    "            const exporter = new GLTFExporter();",
    "            const exportScene = new THREE.Scene();",
    "            wb.objects.forEach((spec) => {",
    "                const mesh = meshes.get(safeString(spec.id));",
    "                if (mesh) exportScene.add(mesh.clone(true));",
    "            });",
    "            exporter.parse(",
    "                exportScene,",
    "                (result) => {",
    "                    if (typeof result === 'string') {",
    "                        moduleWorkbenchCopyText(result, '3D Lab GLTF');",
    "                    } else {",
    "                        moduleWorkbenchCopyJson(result, '3D Lab GLTF');",
    "                    }",
    "                },",
    "                (error) => {",
    "                    notifyUser(`GLTF export failed: ${safeString(error?.message) || 'unknown error'}`, { tone: 'warn', durationMs: 2200, debugKind: 'lab3d' });",
    "                },",
    "                { binary: false },",
    "            );",
    "        }",
    "        if (action === 'export_stl' && STLExporter) {",
    "            syncAllSpecs();",
    "            const exporter = new STLExporter();",
    "            const exportScene = new THREE.Scene();",
    "            wb.objects.forEach((spec) => {",
    "                const mesh = meshes.get(safeString(spec.id));",
    "                if (mesh) exportScene.add(mesh.clone(true));",
    "            });",
    "            try {",
    "                const stl = exporter.parse(exportScene, { binary: false });",
    "                const stlText = typeof stl === 'string' ? stl : '';",
    "                if (stlText) {",
    "                    moduleWorkbenchDownloadText('lab3d-scene.stl', stlText, 'model/stl');",
    "                    notifyUser('STL downloaded.', { tone: 'success', durationMs: 1600, debugKind: 'lab3d' });",
    "                } else {",
    "                    notifyUser('STL export produced no text payload.', { tone: 'warn', durationMs: 1900, debugKind: 'lab3d' });",
    "                }",
    "            } catch (error) {",
    "                notifyUser(`STL export failed: ${safeString(error?.message) || 'unknown error'}`, { tone: 'warn', durationMs: 2200, debugKind: 'lab3d' });",
    "            }",
    "        }",
    "    });",
    "",
    "    if (importInput instanceof HTMLInputElement) {",
    "        importInput.addEventListener('change', async () => {",
    "            const file = importInput.files?.[0];",
    "            if (!file) return;",
    "            try {",
    "                const raw = await file.text();",
    "                const parsed = JSON.parse(raw);",
    "                const nextObjects = parseImportedObjects(parsed);",
    "                if (!nextObjects.length) {",
    "                    notifyUser('No valid meshes found in imported JSON.', { tone: 'warn', durationMs: 2200, debugKind: 'lab3d' });",
    "                    importInput.value = '';",
    "                    return;",
    "                }",
    "                wb.objects = nextObjects;",
    "                wb.nextId = nextObjects.length + 1;",
    "                wb.selectedId = safeString(nextObjects[0]?.id);",
    "                rebuildScene();",
    "                renderInspector();",
    "                renderStatus();",
    "                notifyUser(`Imported ${nextObjects.length} mesh definitions.`, { tone: 'success', durationMs: 1700, debugKind: 'lab3d' });",
    "            } catch (error) {",
    "                notifyUser(`Import failed: ${safeString(error?.message) || 'invalid JSON'}`, { tone: 'warn', durationMs: 2200, debugKind: 'lab3d' });",
    "            } finally {",
    "                importInput.value = '';",
    "            }",
    "        });",
    "    }",
    "    const projectSelect = shell.querySelector('select[data-wb-project-select=\"lab_3d\"]');",
    "    if (projectSelect instanceof HTMLSelectElement) {",
    "        projectSelect.addEventListener('change', () => {",
    "            wb.selectedProjectId = safeString(projectSelect.value);",
    "        });",
    "    }",
    "",
    "    inspector.addEventListener('input', (event) => {",
    "        const target = event.target;",
    "        if (!(target instanceof HTMLInputElement)) return;",
    "        const spec = selectedSpec();",
    "        const mesh = selectedMesh();",
    "        if (!spec || !mesh) return;",
    "        const prop = safeString(target.dataset.lab3dProp);",
    "        if (!prop) return;",
    "        if (prop === 'name') spec.name = safeString(target.value).slice(0, 80);",
    "        if (prop === 'color') spec.color = cleanColor(target.value, spec.color);",
    "        if (prop === 'x' || prop === 'y' || prop === 'z') {",
    "            const next = Number(target.value);",
    "            if (Number.isFinite(next)) {",
    "                spec.position = ensureVector3(spec.position, { x: 0, y: 0.5, z: 0 });",
    "                spec.position[prop] = next;",
    "            }",
    "        }",
    "        if (prop === 'scale') {",
    "            const next = moduleWorkbenchClamp(Number(target.value) || 1, 0.1, 12);",
    "            spec.scale = { x: next, y: next, z: next };",
    "        }",
    "        mesh.position.set(spec.position?.x || 0, spec.position?.y || 0, spec.position?.z || 0);",
    "        mesh.scale.set(spec.scale?.x || 1, spec.scale?.y || 1, spec.scale?.z || 1);",
    "        if (mesh.material?.color) mesh.material.color.set(spec.color || '#7fbfff');",
    "        renderInspector();",
    "        renderStatus();",
    "    });",
    "",
    "    wb.ossEngine = {",
    "        dispose: () => {",
    "            window.cancelAnimationFrame(rafId);",
    "            renderer.domElement.removeEventListener('pointerdown', onPointerDown);",
    "            window.removeEventListener('resize', onWindowResize);",
    "            resizeObserver?.disconnect?.();",
    "            transform.detach();",
    "            transform.dispose?.();",
    "            controls.dispose?.();",
    "            meshes.forEach((mesh) => {",
    "                mesh.geometry?.dispose?.();",
    "                if (Array.isArray(mesh.material)) {",
    "                    mesh.material.forEach((material) => material?.dispose?.());",
    "                } else {",
    "                    mesh.material?.dispose?.();",
    "                }",
    "            });",
    "            renderer.dispose?.();",
    "            if (stage.contains(renderer.domElement)) stage.removeChild(renderer.domElement);",
    "        },",
    "    };",
    "    return true;",
    "}",
    "",
    "function moduleRenderWorkbenchLab3d(container, wb) {",
    "    if (moduleRenderWorkbenchLab3dOss(container, wb)) return;",
    "    if (!container || !wb) return;",
    "    if (!Array.isArray(wb.shapes)) wb.shapes = [];",
    "    wb.tool = safeString(wb.tool) || 'rect';",
    "    wb.grid = moduleWorkbenchClamp(Number(wb.grid) || 24, 8, 64);",
    "    wb.snap = wb.snap !== false;",
    "    wb.units = safeString(wb.units) || 'mm';",
    "    wb.canvasWidth = moduleWorkbenchClamp(Number(wb.canvasWidth) || 860, 500, 1400);",
    "    wb.canvasHeight = moduleWorkbenchClamp(Number(wb.canvasHeight) || 420, 260, 760);",
    "",
    "    moduleWorkbenchHeader(container, '3D Lab Workbench', 'Dispatch fabrication-ready modeling tasks to Thomas and review generated CAD outputs.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-lab3d';",
    "    shell.innerHTML = `",
    "        <div class=\"module-wb-toolbar\">",
    "            <div class=\"module-wb-tool-group\" data-lab-tools></div>",
    "            <div class=\"module-wb-toolbar-actions\">",
    "                <label class=\"module-wb-inline-field\">Grid <input type=\"number\" data-lab-grid min=\"8\" max=\"64\" step=\"2\" value=\"${escapeHtml(String(wb.grid))}\" /></label>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab-action=\"snap\">${wb.snap ? 'Snap On' : 'Snap Off'}</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-lab-action=\"clear\">Clear</button>"
].join("\n");
