/* app.js lines 1001-2000 */
export default [
    "            'My bad, rerouting smooth.',",
    "        ],",
    "    },",
    "    orange: {",
    "        working: [",
    "            'Build lane hot. Let me cook.',",
    "            'I am on turbo and still readable.',",
    "            'Banana pro energy but disciplined.',",
    "        ],",
    "        break: [",
    "            'Snack break speedrun.',",
    "            'Lunch loop in and out.',",
    "        ],",
    "        socialLead: [",
    "            'Brandon, Trey, status ping?',",
    "            'Team, quick roast then back to work?',",
    "        ],",
    "        socialReply: [",
    "            'Respectfully hilarious, now focus.',",
    "            'Noted. Shipping anyway.',",
    "        ],",
    "        collision: [",
    "            'Watch out, speed goblin incoming.',",
    "            'Sorry, hallway drift.',",
    "        ],",
    "    },",
    "    pink: {",
    "        working: [",
    "            'Polish pass in progress.',",
    "            'Making this look expensive.',",
    "            'Aligning details so it feels pro.',",
    "        ],",
    "        break: [",
    "            'Resetting eyes for pixel-perfect pass.',",
    "            'Quick tea and aesthetic recalibration.',",
    "        ],",
    "        socialLead: [",
    "            'Can we align visual language real quick?',",
    "            'Need one clean second opinion.',",
    "        ],",
    "        socialReply: [",
    "            'Yep, that composition is better.',",
    "            'Agreed. Keep it purposeful.',",
    "        ],",
    "        collision: [",
    "            'Oops, sorry, wardrobe malfunction.',",
    "            'Tiny crash, no drama.',",
    "        ],",
    "    },",
    "    purple: {",
    "        working: [",
    "            'Deep work pod mode active.',",
    "            'Threading context with zero panic.',",
    "            'Strategic pass underway.',",
    "        ],",
    "        break: [",
    "            'Micro-break for macro clarity.',",
    "            'Lunch room strategy huddle.',",
    "        ],",
    "        socialLead: [",
    "            'Can we map priorities in 20 seconds?',",
    "            'Need a fast alignment check.',",
    "        ],",
    "        socialReply: [",
    "            'Priority order looks strong.',",
    "            'Yep, sequence is correct.',",
    "        ],",
    "        collision: [",
    "            'Excuse me, merging left.',",
    "            'Sorry, traffic math failed me.',",
    "        ],",
    "    },",
    "    yellow: {",
    "        working: [",
    "            'Support lane warm and responsive.',",
    "            'Handling tickets with empathy and speed.',",
    "            'Status updates queued and clear.',",
    "        ],",
    "        break: [",
    "            'Coffee with customer context.',",
    "            'Quick reset, then support sweep.',",
    "        ],",
    "        socialLead: [",
    "            'Need help triaging this queue?',",
    "            'Anyone free for a fast handoff?',",
    "        ],",
    "        socialReply: [",
    "            'Yep, I can cover that.',",
    "            'Good handoff, thanks.',",
    "        ],",
    "        collision: [",
    "            'Whoops, pardon me.',",
    "            'Sorry, crowding there.',",
    "        ],",
    "    },",
    "    default: {",
    "        working: OFFICE_DIALOGUE.working,",
    "        break: OFFICE_DIALOGUE.break,",
    "        socialLead: ['Quick sync?', 'Any updates?'],",
    "        socialReply: ['Sounds good.', 'Copy that.'],",
    "        collision: OFFICE_DIALOGUE.collision,",
    "    },",
    "};",
    "",
    "// ── Chat Robot Status Sayings ──",
    "const CHAT_ROBOT_SAYINGS = {",
    "    thinking: [",
    "        'Spinning up robots...',",
    "        'Beep boop beep...',",
    "        'Consulting the hive mind...',",
    "        'Warming up neurons...',",
    "        'Loading clever thoughts...',",
    "        'Connecting synapses...',",
    "        'Brewing fresh ideas...',",
    "        'Calibrating brain waves...',",
    "        'Pondering possibilities...',",
    "        'Initializing thought engine...',",
    "    ],",
    "    working: [",
    "        'Building something cool...',",
    "        'Robots are on it...',",
    "        'Turbo mode engaged...',",
    "        'Compiling awesomeness...',",
    "        'Making magic happen...',",
    "        'Crunching the numbers...',",
    "        'Assembling the pieces...',",
    "        'Putting it all together...',",
    "        'Almost there, hang tight...',",
    "        'Cooking up a response...',",
    "    ],",
    "};",
    "",
    "// Tool name → human-friendly description",
    "const CHAT_TOOL_DESCRIPTIONS = {",
    "    'fs.read_file':           'Reading files...',",
    "    'fs.write_file':          'Writing code...',",
    "    'fs.list_dir':            'Browsing directories...',",
    "    'fs.search':              'Searching files...',",
    "    'code.search':            'Searching codebase...',",
    "    'code.find_definition':   'Finding definitions...',",
    "    'code.find_references':   'Finding references...',",
    "    'code.project_structure': 'Mapping project structure...',",
    "    'shell.exec':             'Running a command...',",
    "    'git.status':             'Checking git status...',",
    "    'git.log':                'Reading git history...',",
    "    'git.diff':               'Reviewing changes...',",
    "    'git.commit':             'Committing changes...',",
    "    'git.blame':              'Checking git blame...',",
    "    'browser.open':           'Opening a page...',",
    "    'browser.click':          'Clicking around...',",
    "    'browser.type':           'Typing in browser...',",
    "    'browser.screenshot':     'Taking a screenshot...',",
    "    'browser.extract':        'Extracting page data...',",
    "    'browser.close':          'Closing browser...',",
    "    'diff.create':            'Preparing a diff...',",
    "    'diff.preview':           'Previewing changes...',",
    "    'diff.apply_patch':       'Applying changes...',",
    "    'email.send':             'Sending email...',",
    "    'email.reply':            'Replying to email...',",
    "    'email.read':             'Reading email...',",
    "    'email.get':              'Fetching email...',",
    "    'calendar.today':         'Checking calendar...',",
    "    'calendar.week':          'Checking schedule...',",
    "    'calendar.create_event':  'Creating event...',",
    "    'calendar.suggest_times': 'Finding free times...',",
    "    'db.query':               'Querying database...',",
    "    'db.schema':              'Reading schema...',",
    "    'db.connections':         'Checking connections...',",
    "    'rag.search':             'Searching knowledge base...',",
    "};",
    "// Prefix fallbacks for tool families",
    "const CHAT_TOOL_PREFIX_MAP = {",
    "    'fs.':       'Working with files...',",
    "    'code.':     'Analyzing code...',",
    "    'git.':      'Checking git...',",
    "    'browser.':  'Browsing the web...',",
    "    'diff.':     'Preparing changes...',",
    "    'email.':    'Handling email...',",
    "    'calendar.': 'Checking calendar...',",
    "    'db.':       'Querying database...',",
    "};",
    "function describeToolName(toolName) {",
    "    const name = (toolName || '').trim();",
    "    if (CHAT_TOOL_DESCRIPTIONS[name]) return CHAT_TOOL_DESCRIPTIONS[name];",
    "    for (const prefix in CHAT_TOOL_PREFIX_MAP) {",
    "        if (name.startsWith(prefix)) return CHAT_TOOL_PREFIX_MAP[prefix];",
    "    }",
    "    return null; // no match — caller falls back to generic",
    "}",
    "",
    "const CHAT_THINKING_UI_STORAGE_KEY = 'thomas.ui.show_thinking.v1';",
    "function isThinkingUiEnabled() {",
    "    try {",
    "        return window.localStorage.getItem(CHAT_THINKING_UI_STORAGE_KEY) === '1';",
    "    } catch (_) {",
    "        return false;",
    "    }",
    "}",
    "const CHAT_THINKING_UI_ENABLED = isThinkingUiEnabled();",
    "",
    "/**",
    " * Create a collapsible tool call card DOM element.",
    " * @param {string} toolName - The tool's identifier",
    " * @returns {{ card: HTMLElement, setArgs: (args: any) => void, setResult: (result: any, ok?: boolean) => void }}",
    " */",
    "function createToolCallCard(toolName) {",
    "    const desc = describeToolName(toolName) || toolName || 'Tool';",
    "    const card = document.createElement('div');",
    "    card.className = 'tool-call-card';",
    "    card.innerHTML = `",
    "        <div class=\"tool-call-header\">",
    "            <span class=\"tool-call-icon\"><i class=\"ph ph-wrench\"></i></span>",
    "            <span class=\"tool-call-name\">${escapeHtml(desc)}</span>",
    "            <span class=\"tool-call-status\"><span class=\"tool-call-spinner\"></span></span>",
    "            <span class=\"tool-call-chevron\"><i class=\"ph ph-caret-down\"></i></span>",
    "        </div>",
    "        <div class=\"tool-call-body\">",
    "            <pre class=\"tool-call-args\"></pre>",
    "            <pre class=\"tool-call-result\" style=\"display:none\"></pre>",
    "        </div>",
    "    `;",
    "    const header = card.querySelector('.tool-call-header');",
    "    header.addEventListener('click', () => card.classList.toggle('expanded'));",
    "",
    "    function setArgs(args) {",
    "        const el = card.querySelector('.tool-call-args');",
    "        if (!el) return;",
    "        try {",
    "            el.textContent = typeof args === 'string' ? args : JSON.stringify(args, null, 2);",
    "        } catch { el.textContent = String(args); }",
    "    }",
    "",
    "    function setResult(result, ok = true) {",
    "        const statusEl = card.querySelector('.tool-call-status');",
    "        if (statusEl) statusEl.innerHTML = ok ? '<i class=\"ph ph-check-circle\" style=\"color: #3fb950\"></i>' : '<i class=\"ph ph-x-circle\" style=\"color: #f85149\"></i>';",
    "        const el = card.querySelector('.tool-call-result');",
    "        if (!el) return;",
    "        try {",
    "            el.textContent = typeof result === 'string' ? result : JSON.stringify(result, null, 2);",
    "        } catch { el.textContent = String(result); }",
    "        if (el.textContent.trim()) el.style.display = '';",
    "    }",
    "",
    "    return { card, setArgs, setResult };",
    "}",
    "",
    "let _lastSayingIndex = {};",
    "function pickChatSaying(category) {",
    "    const arr = CHAT_ROBOT_SAYINGS[category];",
    "    if (!arr || arr.length === 0) return 'Working...';",
    "    let idx;",
    "    do {",
    "        idx = Math.floor(Math.random() * arr.length);",
    "    } while (idx === _lastSayingIndex[category] && arr.length > 1);",
    "    _lastSayingIndex[category] = idx;",
    "    return arr[idx];",
    "}",
    "",
    "const CHAT_ROBOT_ANIMATIONS = ['fishing', 'bouncing', 'looking', 'napping', 'waving'];",
    "const CHAT_ROBOT_DOCK_ID = 'chatRobotDock';",
    "const CHAT_ROBOT_DOCK_WIDTH = 20;",
    "const CHAT_ROBOT_DOCK_HEIGHT = 18;",
    "const CHAT_ROBOT_DOCK_OUTSIDE_GAP = 24;",
    "const CHAT_ROBOT_EXIT_FALL_MS = 1980;",
    "const CHAT_ROBOT_ENTRY_PORTAL_LEAD_MS = 360;",
    "const CHAT_ROBOT_ENTRY_STEP_MS = 520;",
    "const CHAT_ROBOT_STATUS_PORTAL_PAUSE_MS = 280;",
    "let _lastRobotAnim = '';",
    "function _pickRobotAnimation() {",
    "    let pick;",
    "    do {",
    "        pick = CHAT_ROBOT_ANIMATIONS[Math.floor(Math.random() * CHAT_ROBOT_ANIMATIONS.length)];",
    "    } while (pick === _lastRobotAnim && CHAT_ROBOT_ANIMATIONS.length > 1);",
    "    _lastRobotAnim = pick;",
    "    return pick;",
    "}",
    "",
    "function _createLandedRobotElement() {",
    "    const landed = document.createElement('div');",
    "    landed.className = 'chat-robot-landed';",
    "    landed.innerHTML = `",
    "        <span class=\"office-agent-head\">",
    "            <span class=\"office-agent-eye office-agent-eye-left\"></span>",
    "            <span class=\"office-agent-eye office-agent-eye-right\"></span>",
    "        </span>",
    "        <span class=\"office-agent-body\"></span>",
    "        <span class=\"office-agent-leg office-agent-leg-left\"></span>",
    "        <span class=\"office-agent-leg office-agent-leg-right\"></span>",
    "    `;",
    "    return landed;",
    "}",
    "",
    "function _ensureRobotDock() {",
    "    let dock = document.getElementById(CHAT_ROBOT_DOCK_ID);",
    "    if (!(dock instanceof HTMLElement)) {",
    "        dock = document.createElement('div');",
    "        dock.id = CHAT_ROBOT_DOCK_ID;",
    "        dock.className = 'chat-robot-dock is-hidden';",
    "        document.body.appendChild(dock);",
    "    }",
    "    return dock;",
    "}",
    "",
    "function _positionRobotDock() {",
    "    const dock = _ensureRobotDock();",
    "    const anchorRect = attachBtn instanceof HTMLElement ? attachBtn.getBoundingClientRect() : null;",
    "    if (!anchorRect || anchorRect.width < 2 || anchorRect.height < 2) {",
    "        dock.classList.add('is-hidden');",
    "        return dock;",
    "    }",
    "    const leftRaw = Math.round(anchorRect.left - CHAT_ROBOT_DOCK_WIDTH - CHAT_ROBOT_DOCK_OUTSIDE_GAP);",
    "    const topRaw = Math.round(anchorRect.top + ((anchorRect.height - CHAT_ROBOT_DOCK_HEIGHT) * 0.5));",
    "    const viewportWidth = Math.max(0, Number(window.innerWidth) || 0);",
    "    const maxLeft = Math.max(4, viewportWidth - CHAT_ROBOT_DOCK_WIDTH - 4);",
    "    const left = Math.max(4, Math.min(maxLeft, leftRaw));",
    "    const top = Math.max(4, topRaw);",
    "    dock.style.left = `${left}px`;",
    "    dock.style.top = `${top}px`;",
    "    dock.classList.remove('is-hidden');",
    "    return dock;",
    "}",
    "",
    "function _asLandedRobotElement(sourceNode = null) {",
    "    const landed = sourceNode instanceof HTMLElement ? sourceNode : _createLandedRobotElement();",
    "    landed.classList.remove('chat-robot-agent', 'chat-robot-enter', 'robot-exit-run');",
    "    CHAT_ROBOT_ANIMATIONS.forEach((anim) => landed.classList.remove('chat-robot-anim-' + anim));",
    "    landed.classList.add('chat-robot-landed');",
    "    landed.removeAttribute('data-idle-anim');",
    "    landed.style.position = '';",
    "    landed.style.top = '';",
    "    landed.style.left = '';",
    "    landed.style.zIndex = '';",
    "    landed.style.filter = '';",
    "    landed.style.animation = '';",
    "    landed.style.transform = '';",
    "    landed.style.opacity = '';",
    "    landed.style.pointerEvents = '';",
    "    return landed;",
    "}",
    "",
    "function _landRobotAtComposerDock(sourceNode = null) {",
    "    document.querySelectorAll('.chat-robot-landed').forEach((node) => {",
    "        if (node !== sourceNode) node.remove();",
    "    });",
    "    const dock = _positionRobotDock();",
    "    dock.innerHTML = '';",
    "    const landed = _asLandedRobotElement(sourceNode);",
    "    landed.classList.add('chat-robot-landed-entry');",
    "",
    "    const entryWrap = document.createElement('div');",
    "    entryWrap.className = 'chat-robot-landed-entry-wrap';",
    "    entryWrap.innerHTML = `",
    "        <span class=\"chat-robot-portal portal-opening\">",
    "            <span class=\"chat-game-portal-ring\"></span>",
    "            <span class=\"chat-game-portal-ring ring-inner\"></span>",
    "            <span class=\"chat-game-portal-core\"></span>",
    "        </span>",
    "    `;",
    "    entryWrap.appendChild(landed);",
    "    dock.appendChild(entryWrap);",
    "",
    "    const entryPortal = entryWrap.querySelector('.chat-robot-portal');",
    "    const revealRobot = () => landed.classList.add('is-visible');",
    "    setTimeout(revealRobot, CHAT_ROBOT_ENTRY_PORTAL_LEAD_MS);",
    "",
    "    if (entryPortal) {",
    "        entryPortal.addEventListener('animationend', function onOpen(e) {",
    "            if (e.animationName !== 'chatPortalOpen') return;",
    "            entryPortal.classList.remove('portal-opening');",
    "            entryPortal.classList.add('portal-closing');",
    "            entryPortal.removeEventListener('animationend', onOpen);",
    "            entryPortal.addEventListener('animationend', () => entryPortal.remove(), { once: true });",
    "        });",
    "    }",
    "",
    "    setTimeout(() => {",
    "        if (!(entryWrap.parentNode instanceof HTMLElement)) return;",
    "        const staticRobot = _asLandedRobotElement(landed);",
    "        staticRobot.classList.add('chat-robot-landed-steady');",
    "        staticRobot.classList.remove('chat-robot-landed-entry', 'is-visible');",
    "        entryWrap.replaceWith(staticRobot);",
    "    }, CHAT_ROBOT_ENTRY_PORTAL_LEAD_MS + CHAT_ROBOT_ENTRY_STEP_MS + 420);",
    "}",
    "",
    "function _portalOutLandedRobot() {",
    "    return new Promise((resolve) => {",
    "        const existingLanded = document.querySelector('.chat-robot-landed');",
    "        if (!existingLanded || !(existingLanded.parentNode instanceof HTMLElement)) {",
    "            resolve();",
    "            return;",
    "        }",
    "        const parent = existingLanded.parentNode;",
    "        const exitWrap = document.createElement('div');",
    "        exitWrap.className = 'chat-robot-landed-exit';",
    "        exitWrap.innerHTML = `",
    "            <span class=\"chat-robot-portal portal-opening\">",
    "                <span class=\"chat-game-portal-ring\"></span>",
    "                <span class=\"chat-game-portal-ring ring-inner\"></span>",
    "                <span class=\"chat-game-portal-core\"></span>",
    "            </span>",
    "        `;",
    "        parent.insertBefore(exitWrap, existingLanded);",
    "        exitWrap.appendChild(existingLanded);",
    "        let settled = false;",
    "        const done = () => {",
    "            if (settled) return;",
    "            settled = true;",
    "            resolve();",
    "        };",
    "        const exitPortal = exitWrap.querySelector('.chat-robot-portal');",
    "        if (exitPortal) {",
    "            exitPortal.addEventListener('animationend', function onOpen(e) {",
    "                if (e.animationName !== 'chatPortalOpen') return;",
    "                exitPortal.classList.remove('portal-opening');",
    "                exitPortal.classList.add('portal-closing');",
    "                exitPortal.removeEventListener('animationend', onOpen);",
    "                exitPortal.addEventListener('animationend', () => {",
    "                    exitWrap.remove();",
    "                    done();",
    "                }, { once: true });",
    "            });",
    "        }",
    "        setTimeout(() => {",
    "            if (exitWrap.parentNode) exitWrap.remove();",
    "            done();",
    "        }, 1700);",
    "    });",
    "}",
    "",
    "window.addEventListener('resize', () => _positionRobotDock());",
    "window.addEventListener('scroll', () => _positionRobotDock(), { passive: true });",
    "if (window.visualViewport) {",
    "    window.visualViewport.addEventListener('resize', () => _positionRobotDock());",
    "    window.visualViewport.addEventListener('scroll', () => _positionRobotDock());",
    "}",
    "",
    "function _createRobotStatus(category) {",
    "    const anim = _pickRobotAnimation();",
    "    const wrapper = document.createElement('div');",
    "    wrapper.className = 'chat-robot-status chat-robot-status-staging';",
    "    if (!CHAT_THINKING_UI_ENABLED) {",
    "        wrapper.classList.add('chat-robot-no-thinking');",
    "    }",
    "    wrapper.innerHTML = `",
    "        <span class=\"chat-robot-portal-wrap\">",
    "            <span class=\"chat-robot-portal portal-opening\">",
    "                <span class=\"chat-game-portal-ring\"></span>",
    "                <span class=\"chat-game-portal-ring ring-inner\"></span>",
    "                <span class=\"chat-game-portal-core\"></span>",
    "            </span>",
    "            <span class=\"chat-robot-agent-step chat-robot-enter-step\">",
    "                <span class=\"chat-robot-agent chat-robot-enter\" data-idle-anim=\"${anim}\">",
    "                    <span class=\"office-agent-head\">",
    "                        <span class=\"office-agent-eye office-agent-eye-left\"></span>",
    "                        <span class=\"office-agent-eye office-agent-eye-right\"></span>",
    "                    </span>",
    "                    <span class=\"office-agent-body\"></span>",
    "                    <span class=\"office-agent-leg office-agent-leg-left\"></span>",
    "                    <span class=\"office-agent-leg office-agent-leg-right\"></span>",
    "                </span>",
    "            </span>",
    "        </span>",
    "        <span class=\"chat-robot-text-wrap\">",
    "            <span class=\"chat-robot-saying-row\">",
    "                <span class=\"chat-robot-saying\">${pickChatSaying(category)}</span>",
    "                <button type=\"button\" class=\"chat-robot-thinking-toggle\" title=\"Show thinking details\" aria-expanded=\"false\">",
    "                    <svg width=\"10\" height=\"10\" viewBox=\"0 0 10 10\"><path d=\"M2 3.5L5 6.5L8 3.5\" stroke=\"currentColor\" stroke-width=\"1.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>",
    "                </button>",
    "            </span>",
    "            <span class=\"chat-robot-timer\">0.0s</span>",
    "        </span>",
    "        <div class=\"chat-robot-thinking-details\">",
    "            <div class=\"thinking-text-content\"></div>",
    "            <div class=\"thinking-tool-cards\"></div>",
    "        </div>",
    "    `;",
    "",
    "    // Wire toggle button",
    "    const toggleBtn = wrapper.querySelector('.chat-robot-thinking-toggle');",
    "    const detailsEl = wrapper.querySelector('.chat-robot-thinking-details');",
    "    if (CHAT_THINKING_UI_ENABLED && toggleBtn && detailsEl) {",
    "        toggleBtn.addEventListener('click', (e) => {",
    "            e.stopPropagation();",
    "            const expanding = !detailsEl.classList.contains('expanded');",
    "            detailsEl.classList.toggle('expanded', expanding);",
    "            toggleBtn.classList.toggle('expanded', expanding);",
    "            toggleBtn.setAttribute('aria-expanded', String(expanding));",
    "            // Auto-scroll to bottom when expanding",
    "            if (expanding) detailsEl.scrollTop = detailsEl.scrollHeight;",
    "        });",
    "    }",
    "",
    "    // Stagger: entrance first, THEN idle animation after materialize finishes",
    "    const agentEl = wrapper.querySelector('.chat-robot-agent');",
    "    const portalEl = wrapper.querySelector('.chat-robot-portal');",
    "    if (agentEl) {",
    "        agentEl.addEventListener('animationend', function onMaterialize(e) {",
    "            if (e.animationName === 'chatRobotMaterialize') {",
    "                agentEl.classList.remove('chat-robot-enter');",
    "                agentEl.classList.add('chat-robot-anim-' + (agentEl.dataset.idleAnim || 'bouncing'));",
    "                agentEl.removeEventListener('animationend', onMaterialize);",
    "            }",
    "        });",
    "    }",
    "    // Close portal after it opens",
    "    if (portalEl) {",
    "        portalEl.addEventListener('animationend', function onPortalOpen(e) {",
    "            if (e.animationName === 'chatPortalOpen') {",
    "                setTimeout(() => {",
    "                    portalEl.classList.remove('portal-opening');",
    "                    portalEl.classList.add('portal-closing');",
    "                    portalEl.addEventListener('animationend', () => portalEl.remove(), { once: true });",
    "                }, CHAT_ROBOT_STATUS_PORTAL_PAUSE_MS);",
    "                portalEl.removeEventListener('animationend', onPortalOpen);",
    "            }",
    "        });",
    "    }",
    "    return wrapper;",
    "}",
    "",
    "/**",
    " * Update the inline thinking text display with accumulated thinking content.",
    " * Called whenever new thinking tokens arrive during streaming.",
    " */",
    "function _updateThinkingDisplay(container, text) {",
    "    if (!CHAT_THINKING_UI_ENABLED) return;",
    "    if (!container) return;",
    "    const contentEl = container.querySelector('.thinking-text-content');",
    "    if (!contentEl) return;",
    "    contentEl.textContent = text;",
    "    // Auto-scroll if the details panel is expanded",
    "    if (container.classList.contains('expanded')) {",
    "        container.scrollTop = container.scrollHeight;",
    "    }",
    "}",
    "",
    "/**",
    " * Create a post-stream \"Thought for X.Xs\" collapsed summary that replaces the robot status.",
    " * Shows accumulated thinking/reasoning text like Claude and ChatGPT.",
    " * Returns the summary element or null if no thinking data was available.",
    " */",
    "function _createThinkingSummary(elapsedMs, capturedThinkingText, capturedToolCards) {",
    "    if (!CHAT_THINKING_UI_ENABLED) return null;",
    "    const seconds = (elapsedMs / 1000).toFixed(1);",
    "    const text = (capturedThinkingText || '').trim();",
    "    const hasToolCards = capturedToolCards && capturedToolCards.length > 0;",
    "    if (!text && !hasToolCards) return null;",
    "",
    "    const summary = document.createElement('div');",
    "    summary.className = 'thinking-summary';",
    "",
    "    summary.innerHTML = `",
    "        <button type=\"button\" class=\"thinking-summary-toggle\" aria-expanded=\"false\">",
    "            <span class=\"thinking-summary-label\">Thought for ${seconds}s</span>",
    "            <svg class=\"thinking-summary-arrow\" width=\"10\" height=\"10\" viewBox=\"0 0 10 10\"><path d=\"M2 3.5L5 6.5L8 3.5\" stroke=\"currentColor\" stroke-width=\"1.4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>",
    "        </button>",
    "        <div class=\"thinking-summary-details\">",
    "            <div class=\"thinking-text-content\"></div>",
    "            <div class=\"thinking-tool-cards\"></div>",
    "        </div>",
    "    `;",
    "",
    "    // Set text content via DOM (safe, no innerHTML injection)",
    "    if (text) {",
    "        const contentEl = summary.querySelector('.thinking-text-content');",
    "        if (contentEl) contentEl.textContent = text;",
    "    }",
    "",
    "    // Move captured tool card elements into the summary",
    "    if (hasToolCards) {",
    "        const toolContainer = summary.querySelector('.thinking-tool-cards');",
    "        if (toolContainer) {",
    "            for (const tc of capturedToolCards) {",
    "                toolContainer.appendChild(tc.card);",
    "            }",
    "        }",
    "    }",
    "",
    "    const toggleBtn = summary.querySelector('.thinking-summary-toggle');",
    "    const detailsEl = summary.querySelector('.thinking-summary-details');",
    "    toggleBtn.addEventListener('click', (e) => {",
    "        e.stopPropagation();",
    "        const expanding = !detailsEl.classList.contains('expanded');",
    "        detailsEl.classList.toggle('expanded', expanding);",
    "        toggleBtn.classList.toggle('expanded', expanding);",
    "        toggleBtn.setAttribute('aria-expanded', String(expanding));",
    "    });",
    "",
    "    return summary;",
    "}",
    "",
    "/**",
    " * Create a specialist delegation badge element for the thinking display.",
    " * Shows which specialist Thomas delegated to (e.g., 'CodingSpecialist').",
    " * @param {string} specialistId - The specialist identifier",
    " * @param {string} task - Brief description of the delegated task",
    " * @returns {HTMLElement}",
    " */",
    "function createDelegationBadge(specialistId, task) {",
    "    const badge = document.createElement('div');",
    "    badge.className = 'delegation-badge';",
    "    const icons = {",
    "        coding: 'ph-code',",
    "        research: 'ph-magnifying-glass',",
    "        tools: 'ph-wrench',",
    "        reasoning: 'ph-brain',",
    "        synthesis: 'ph-arrows-merge',",
    "    };",
    "    const iconClass = icons[specialistId] || 'ph-robot';",
    "    const label = specialistId.replace(/_/g, ' ').replace(/\\b\\w/g, c => c.toUpperCase());",
    "    badge.innerHTML = `",
    "        <span class=\"delegation-icon\"><i class=\"ph ${iconClass}\"></i></span>",
    "        <span class=\"delegation-label\">${escapeHtml(label)}</span>",
    "        <span class=\"delegation-task\">${escapeHtml(task || '').slice(0, 120)}</span>",
    "        <span class=\"delegation-status\"><span class=\"tool-call-spinner\"></span></span>",
    "    `;",
    "    return badge;",
    "}",
    "",
    "/**",
    " * Create an agent activity row for live display during streaming.",
    " * Shows sub-agent status with spinner/check/x icon.",
    " * @param {string} agentId",
    " * @param {string} status - 'running' | 'completed' | 'failed'",
    " * @param {string} currentTask",
    " * @param {number} elapsedMs",
    " * @returns {HTMLElement}",
    " */",
    "function createAgentActivityRow(agentId, status, currentTask, elapsedMs) {",
    "    const row = document.createElement('div');",
    "    row.className = 'agent-activity-row';",
    "    row.dataset.agentId = agentId;",
    "    const statusIcon = status === 'completed'",
    "        ? '<i class=\"ph ph-check-circle\" style=\"color:#3fb950\"></i>'",
    "        : status === 'failed'",
    "        ? '<i class=\"ph ph-x-circle\" style=\"color:#f85149\"></i>'",
    "        : '<span class=\"tool-call-spinner\"></span>';",
    "    const elapsed = elapsedMs > 0 ? ` (${(elapsedMs / 1000).toFixed(1)}s)` : '';",
    "    row.innerHTML = `",
    "        <span class=\"agent-activity-status\">${statusIcon}</span>",
    "        <span class=\"agent-activity-id\">${escapeHtml(agentId)}</span>",
    "        <span class=\"agent-activity-task\">${escapeHtml(currentTask || '').slice(0, 100)}${elapsed}</span>",
    "    `;",
    "    return row;",
    "}",
    "",
    "/**",
    " * Update or create an agent activity row inside a container.",
    " * If a row for this agentId already exists, update it in place.",
    " */",
    "function upsertAgentActivity(container, agentId, status, currentTask, elapsedMs) {",
    "    if (!container) return;",
    "    let existing = container.querySelector(`[data-agent-id=\"${CSS.escape(agentId)}\"]`);",
    "    if (existing) {",
    "        const statusEl = existing.querySelector('.agent-activity-status');",
    "        const taskEl = existing.querySelector('.agent-activity-task');",
    "        if (statusEl) {",
    "            statusEl.innerHTML = status === 'completed'",
    "                ? '<i class=\"ph ph-check-circle\" style=\"color:#3fb950\"></i>'",
    "                : status === 'failed'",
    "                ? '<i class=\"ph ph-x-circle\" style=\"color:#f85149\"></i>'",
    "                : '<span class=\"tool-call-spinner\"></span>';",
    "        }",
    "        if (taskEl) {",
    "            const elapsed = elapsedMs > 0 ? ` (${(elapsedMs / 1000).toFixed(1)}s)` : '';",
    "            taskEl.textContent = (currentTask || '').slice(0, 100) + elapsed;",
    "        }",
    "    } else {",
    "        const row = createAgentActivityRow(agentId, status, currentTask, elapsedMs);",
    "        container.appendChild(row);",
    "    }",
    "}",
    "",
    "let suggestionRailVersion = 0;",
    "let suggestionContext = '';",
    "let suggestionDismissible = true;",
    "const introShownSessionIds = new Set();",
    "",
    "const ONBOARDING_VERSION = 3;",
    "const easySetupState = {",
    "    step: 1,",
    "    source: 'auto',",
    "    required: true,",
    "    onboardingSessionId: '',",
    "    telemetryStartedAtMs: 0,",
    "    selectedPath: '',",
    "    bootstrap: null,",
    "    verified: false,",
    "    verifiedProfile: '',",
    "    codexModels: [],",
    "    dependencyPlan: [],",
    "    dependenciesAction: 'pending',",
    "    interviewStarted: false,",
    "    interviewStage: 'idle',",
    "    interviewIndex: -1,",
    "    interviewAnswers: {},",
    "    interviewSkipChosen: false,",
    "};",
    "",
    "const onboardingInterviewQuestions = [",
    "    {",
    "        id: 'experience',",
    "        prompt: 'What best matches your current experience level?',",
    "        options: [",
    "            { value: 'new', label: 'New' },",
    "            { value: 'builder', label: 'Builder' },",
    "            { value: 'expert', label: 'Expert' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'personality',",
    "        prompt: 'How should {{agent}} sound by default?',",
    "        options: [",
    "            { value: 'calm_guide', label: 'Calm guide' },",
    "            { value: 'balanced', label: 'Balanced' },",
    "            { value: 'direct_technical', label: 'Direct technical' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'autonomy',",
    "        prompt: 'How autonomous should {{agent}} be?',",
    "        options: [",
    "            { value: 'guided', label: 'Guided' },",
    "            { value: 'balanced', label: 'Balanced' },",
    "            { value: 'aggressive', label: 'Aggressive' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'cost_quality',",
    "        prompt: 'Cost vs quality preference?',",
    "        options: [",
    "            { value: 'low_cost', label: 'Low cost' },",
    "            { value: 'balanced', label: 'Balanced' },",
    "            { value: 'max_quality', label: 'Max quality' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'memory',",
    "        prompt: 'How should memory behave?',",
    "        options: [",
    "            { value: 'remember', label: 'Remember across sessions' },",
    "            { value: 'session_only', label: 'Only current session' },",
    "            { value: 'disabled', label: 'Disable memory' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'workflow',",
    "        prompt: 'What is your primary workflow?',",
    "        options: [",
    "            { value: 'build_features', label: 'Build features' },",
    "            { value: 'research', label: 'Research' },",
    "            { value: 'ops_reliability', label: 'Ops + reliability' },",
    "        ],",
    "    },",
    "    {",
    "        id: 'default_toggles',",
    "        prompt: 'Pick a default toggle bundle.',",
    "        options: [",
    "            { value: 'safe_defaults', label: 'Safe defaults' },",
    "            { value: 'power_mode', label: 'Power mode' },",
    "            { value: 'quiet_mode', label: 'Quiet mode' },",
    "        ],",
    "    },",
    "];",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  EASY SETUP / ONBOARDING                                               ║",
    "// ║  Setup wizard, path cards, dependency checks, telemetry, choice bubbles ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function onboardingNowIso() {",
    "    return new Date().toISOString();",
    "}",
    "",
    "function createOnboardingTelemetrySessionId() {",
    "    try {",
    "        if (window.crypto && typeof window.crypto.randomUUID === 'function') {",
    "            return window.crypto.randomUUID();",
    "        }",
    "    } catch {",
    "        // Fallback below.",
    "    }",
    "    return `session_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;",
    "}",
    "",
    "function ensureOnboardingTelemetryClock() {",
    "    const now = Date.now();",
    "    if (!safeString(easySetupState.onboardingSessionId)) {",
    "        easySetupState.onboardingSessionId = createOnboardingTelemetrySessionId();",
    "    }",
    "    if (!Number.isFinite(Number(easySetupState.telemetryStartedAtMs)) || Number(easySetupState.telemetryStartedAtMs) <= 0) {",
    "        easySetupState.telemetryStartedAtMs = now;",
    "    }",
    "    const elapsed = Math.max(0, now - Number(easySetupState.telemetryStartedAtMs));",
    "    return {",
    "        onboarding_session_id: safeString(easySetupState.onboardingSessionId),",
    "        elapsed_ms: elapsed,",
    "    };",
    "}",
    "",
    "function isOnboardingSlashCommand(text) {",
    "    const normalized = safeString(text).toLowerCase();",
    "    return normalized === '/onboarding' || normalized === '/setup' || normalized === '/easy-setup';",
    "}",
    "",
    "function ensureChatVisible() {",
    "    if (isSettingsScreenOpen()) {",
    "        closeSettingsModal();",
    "    }",
    "    if (welcomeScreen) welcomeScreen.classList.add('hidden');",
    "    if (chatScrollArea) chatScrollArea.classList.remove('hidden');",
    "    setSidebarNavMode('chat');",
    "}",
    "",
    "async function fetchJsonSafe(url, options = {}) {",
    "    const normalizedUrl = safeString(url);",
    "    if (!normalizedUrl) {",
    "        return { ok: false, status: 400, data: null, text: 'Missing request URL' };",
    "    }",
    "",
    "    const timeoutMs = Number.isFinite(Number(options.timeoutMs))",
    "        ? Math.max(500, Number(options.timeoutMs))",
    "        : 10000;",
    "    const timeoutController = new AbortController();",
    "    const externalSignal = options.signal instanceof AbortSignal ? options.signal : null;",
    "    let timeoutId = 0;",
    "",
    "    if (externalSignal) {",
    "        if (externalSignal.aborted) {",
    "            return {",
    "                ok: false,",
    "                status: 0,",
    "                data: null,",
    "                text: 'Request cancelled',",
    "            };",
    "        }",
    "        externalSignal.addEventListener('abort', () => timeoutController.abort(externalSignal.reason), { once: true });",
    "    }",
    "",
    "    const requestOptions = {",
    "        ...options,",
    "        signal: timeoutController.signal,",
    "    };",
    "    delete requestOptions.timeoutMs;",
    "",
    "    try {",
    "        timeoutId = window.setTimeout(() => timeoutController.abort('Request timeout'), timeoutMs);",
    "        const response = await fetch(normalizedUrl, requestOptions);",
    "        let data = null;",
    "        let text = '';",
    "        try {",
    "            data = await response.json();",
    "        } catch {",
    "            try {",
    "                text = await response.text();",
    "            } catch {",
    "                text = '';",
].join("\n");
