/* split from part-009.js */
export default [
    "    } else if (ok) {",
    "        statusText = 'Onboarding KPI thresholds passing for current telemetry window.';",
    "    }",
    "    setDebugStatusNode(debugOnboardingGateStatus, statusText, tone);",
    "",
    "    if (!debugOnboardingGateList) return;",
    "    debugOnboardingGateList.innerHTML = '';",
    "    const frag = document.createDocumentFragment();",
    "",
    "    const completionTone = !sampleReady",
    "        ? 'warn'",
    "        : (completionRate >= minCompletionRate ? 'ok' : 'error');",
    "    const recoveryTone = !sampleReady || recoveryAttempts <= 0",
    "        ? 'warn'",
    "        : (recoverySuccessRate >= minRecoverySuccessRate ? 'ok' : 'error');",
    "    const medianTone = !sampleReady || completedWithTiming <= 0",
    "        ? 'warn'",
    "        : (medianReadySeconds <= maxMedianReadySeconds ? 'ok' : 'error');",
    "",
    "    frag.appendChild(debugCreateItemCard({",
    "        title: 'Gate Verdict',",
    "        pill: gateLabel,",
    "        pillTone: tone,",
    "        meta: [",
    "            `strict mode: ${strict ? 'on' : 'off'}`,",
    "            `sample readiness: ${sampleReady ? 'threshold checks active' : `insufficient sample (events=${events}, required>=${minEvents})`}`,",
    "            `errors: ${errors.length} | warnings: ${warnings.length}`,",
    "        ],",
    "    }));",
    "",
    "    frag.appendChild(debugCreateItemCard({",
    "        title: 'Completion Rate',",
    "        pill: formatDebugPercent(completionRate, 1),",
    "        pillTone: completionTone,",
    "        meta: [",
    "            `target: >= ${formatDebugPercent(minCompletionRate, 1)}`,",
    "            `opened: ${Number(summary?.wizard_opened || 0)} | completed: ${Number(summary?.onboarding_completed || 0)}`,",
    "        ],",
    "    }));",
    "",
    "    frag.appendChild(debugCreateItemCard({",
    "        title: 'Recovery Success',",
    "        pill: formatDebugPercent(recoverySuccessRate, 1),",
    "        pillTone: recoveryTone,",
    "        meta: [",
    "            `target: >= ${formatDebugPercent(minRecoverySuccessRate, 1)}`,",
    "            `attempts: ${recoveryAttempts} | succeeded: ${Number(summary?.recovery_succeeded || 0)}`,",
    "        ],",
    "    }));",
    "",
    "    frag.appendChild(debugCreateItemCard({",
    "        title: 'Median Time-To-Ready',",
    "        pill: Number.isFinite(medianReadySeconds) ? `${medianReadySeconds.toFixed(1)}s` : '-',",
    "        pillTone: medianTone,",
    "        meta: [",
    "            `target: <= ${Number.isFinite(maxMedianReadySeconds) ? maxMedianReadySeconds.toFixed(1) : '-'}s`,",
    "            `completed journeys with timing: ${completedWithTiming}`,",
    "        ],",
    "    }));",
    "",
    "    if (errors.length > 0) {",
    "        frag.appendChild(debugCreateItemCard({",
    "            title: 'Top Gate Error',",
    "            pill: 'action required',",
    "            pillTone: 'error',",
    "            meta: [safeString(errors[0]) || 'Unknown onboarding gate error'],",
    "        }));",
    "    } else if (warnings.length > 0) {",
    "        frag.appendChild(debugCreateItemCard({",
    "            title: 'Top Gate Warning',",
    "            pill: 'warning',",
    "            pillTone: 'warn',",
    "            meta: [safeString(warnings[0]) || 'Unknown onboarding gate warning'],",
    "        }));",
    "    }",
    "",
    "    debugOnboardingGateList.appendChild(frag);",
    "}",
    "",
    "async function runDebugOnboardingRepairNow() {",
    "    if (debugOnboardingRepairInFlight) return;",
    "    debugOnboardingRepairInFlight = true;",
    "    setDebugOnboardingRepairButtonState({",
    "        visible: true,",
    "        enabled: false,",
    "        label: 'Repairing...',",
    "    });",
    "    setDebugStatusNode(",
    "        debugOnboardingGateStatus,",
    "        'Running setup repair. You may need to approve system installer prompts.',",
    "        'warn',",
    "    );",
    "    pushDebugEvent('setup', 'Triggered onboarding repair from Tools Console.');",
    "    emitOnboardingTelemetry('repair.triggered', { trigger: 'tools_console_gate' });",
    "",
    "    try {",
    "        const res = await fetchJsonSafe('/api/setup/repair', {",
    "            method: 'POST',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({",
    "                auto_install_tools: true,",
    "                skip_install: false,",
    "                skip_doctor: false,",
    "            }),",
    "        });",
    "",
    "        if (!res.ok || !res.data) {",
    "            const reason = safeString(res.data?.error) || safeString(res.text) || 'Repair call failed.';",
    "            setDebugStatusNode(",
    "                debugOnboardingGateStatus,",
    "                `${reason} Remediation: run repair from command line and retry.`,",
    "                'error',",
    "            );",
    "            emitOnboardingTelemetry('wizard.download_approval_failed', {",
    "                trigger: 'tools_console_gate',",
    "                error: reason,",
    "            });",
    "            notifyUser(`Setup repair failed: ${reason}`, {",
    "                tone: 'error',",
    "                durationMs: 3200,",
    "                debugKind: 'error',",
    "            });",
    "            pushDebugEvent('setup', `Onboarding repair failed: ${reason}`);",
    "            return;",
    "        }",
    "",
    "        if (!Boolean(res.data?.ok)) {",
    "            const errorMsg = safeString(res.data?.error) || `Repair exited with code ${res.data?.exit_code}.`;",
    "            const stderrTail = safeString(res.data?.stderr_tail);",
    "            const finalMsg = stderrTail ? `${errorMsg} ${stderrTail}` : errorMsg;",
    "            setDebugStatusNode(",
    "                debugOnboardingGateStatus,",
    "                `${finalMsg} Remediation: approve prompts and retry.`,",
    "                'error',",
    "            );",
    "            emitOnboardingTelemetry('wizard.download_approval_failed', {",
    "                trigger: 'tools_console_gate',",
    "                error: errorMsg,",
    "            });",
    "            notifyUser(`Setup repair failed: ${errorMsg}`, {",
    "                tone: 'error',",
    "                durationMs: 3200,",
    "                debugKind: 'error',",
    "            });",
    "            pushDebugEvent('setup', `Onboarding repair failed: ${errorMsg}`);",
    "            return;",
    "        }",
    "",
    "        const reportPath = safeString(res.data?.report_path);",
    "        const successText = reportPath",
    "            ? `Repair completed. Report: ${reportPath}`",
    "            : 'Repair completed successfully.';",
    "        setDebugStatusNode(debugOnboardingGateStatus, successText, 'ok');",
    "        emitOnboardingTelemetry('wizard.download_approved', {",
    "            trigger: 'tools_console_gate',",
    "            report_path: reportPath,",
    "        });",
    "        notifyUser('Setup repair completed. Refreshing onboarding diagnostics.', {",
    "            tone: 'success',",
    "            durationMs: 2500,",
    "            debugKind: 'setup',",
    "        });",
    "        pushDebugEvent('setup', successText);",
    "    } catch (error) {",
    "        const reason = safeString(error?.message) || 'unknown repair error';",
    "        setDebugStatusNode(debugOnboardingGateStatus, `Setup repair failed: ${reason}`, 'error');",
    "        emitOnboardingTelemetry('wizard.download_approval_failed', {",
    "            trigger: 'tools_console_gate',",
    "            error: reason,",
    "        });",
    "        notifyUser(`Setup repair failed: ${reason}`, {",
    "            tone: 'error',",
    "            durationMs: 3200,",
    "            debugKind: 'error',",
    "        });",
    "        pushDebugEvent('setup', `Onboarding repair failed: ${reason}`);",
    "    } finally {",
    "        debugOnboardingRepairInFlight = false;",
    "        await refreshDebugLiveData({ force: true, reason: 'manual' });",
    "    }",
    "}",
    "",
    "function renderDebugSystemPanel() {",
    "    const payload = debugLiveCache.system;",
    "    if (!payload) {",
    "        if (debugSystemVersion) debugSystemVersion.textContent = '-';",
    "        if (debugSystemReady) debugSystemReady.textContent = '-';",
    "        if (debugSystemEngineCount) debugSystemEngineCount.textContent = '0';",
    "        setDebugSystemStatus('Use Refresh to fetch system status.');",
    "        debugRenderEmpty(debugSystemEngineList, 'No engine data yet.');",
    "        renderDebugOnboardingGatePanel(null);",
    "        return;",
    "    }",
    "",
    "    const version = safeString(payload?.version?.version || payload?.version);",
    "    const bootstrap = payload?.bootstrap || {};",
    "    const quickStart = bootstrap?.quick_start || {};",
    "    const recommendedPath = safeString(quickStart?.recommended_path).toLowerCase() || '-';",
    "    const reason = safeString(quickStart?.reason);",
    "    const enginesRaw = payload?.engines || {};",
    "    const engineRows = parseEngineRows(enginesRaw);",
    "    const healthyEngines = engineRows.filter((engine) => engine.running && !engine.error).length;",
    "",
    "    if (debugSystemVersion) debugSystemVersion.textContent = version || '-';",
    "    if (debugSystemReady) debugSystemReady.textContent = recommendedPath || '-';",
    "    if (debugSystemEngineCount) debugSystemEngineCount.textContent = String(engineRows.length);",
    "",
    "    if (!engineRows.length) {",
    "        setDebugSystemStatus(reason || 'Engine manager unavailable.', 'warn');",
    "        debugRenderEmpty(debugSystemEngineList, 'No engine rows returned.');",
    "        renderDebugOnboardingGatePanel(payload?.onboarding_gate || null);",
    "        return;",
    "    }",
    "",
    "    const hasEngineErrors = engineRows.some((engine) => safeString(engine.error));",
    "    const allRunning = healthyEngines === engineRows.length;",
    "    const statusTone = hasEngineErrors ? 'error' : (allRunning ? 'ok' : 'warn');",
    "    const statusText = reason",
    "        ? `${reason} | ${healthyEngines}/${engineRows.length} engines healthy`",
    "        : `${healthyEngines}/${engineRows.length} engines healthy`;",
    "    setDebugSystemStatus(statusText, statusTone);",
    "",
    "    if (!debugSystemEngineList) return;",
    "    debugSystemEngineList.innerHTML = '';",
    "    const frag = document.createDocumentFragment();",
    "    engineRows.forEach((engine) => {",
    "        const tone = engine.error ? 'error' : (engine.running ? 'ok' : 'warn');",
    "        frag.appendChild(debugCreateItemCard({",
    "            title: engine.name,",
    "            pill: engine.error ? 'error' : (engine.running ? 'running' : 'stopped'),",
    "            pillTone: tone,",
    "            meta: [",
    "                `cycles: ${Number.isFinite(engine.cycles) ? engine.cycles : 0}`,",
    "                `last activity: ${formatDebugWhen(engine.lastActivity)}`,",
    "                engine.error ? `error: ${engine.error}` : '',",
    "            ],",
    "        }));",
    "    });",
    "    debugSystemEngineList.appendChild(frag);",
    "    renderDebugOnboardingGatePanel(payload?.onboarding_gate || null);"
].join("\n");
