/* split from part-024.js */
export default [
    "    };",
    "",
    "    let painting = false;",
    "    canvas.addEventListener('pointerdown', (event) => {",
    "        event.preventDefault();",
    "        const point = eventToCell(event);",
    "        if (!point) return;",
    "        if (paintCell(point.x, point.y)) {",
    "            painting = true;",
    "            render();",
    "        }",
    "    });",
    "    canvas.addEventListener('pointermove', (event) => {",
    "        if (!painting) return;",
    "        const point = eventToCell(event);",
    "        if (!point) return;",
    "        if (paintCell(point.x, point.y)) {",
    "            render();",
    "        }",
    "    });",
    "    const stopPaint = () => {",
    "        painting = false;",
    "    };",
    "    canvas.addEventListener('pointerup', stopPaint);",
    "    canvas.addEventListener('pointerleave', stopPaint);",
    "    canvas.addEventListener('pointercancel', stopPaint);",
    "",
    "    if (promptInput instanceof HTMLInputElement) {",
    "        promptInput.addEventListener('input', () => {",
    "            const forge = activeForge();",
    "            if (!forge) return;",
    "            forge.prompt = safeString(promptInput.value).slice(0, 180);",
    "        });",
    "    }",
    "    if (nameInput instanceof HTMLInputElement) {",
    "        nameInput.addEventListener('input', () => {",
    "            const forge = activeForge();",
    "            if (!forge) return;",
    "            forge.draftName = safeString(nameInput.value).slice(0, 96);",
    "        });",
    "    }",
    "",
    "    root.addEventListener('click', (event) => {",
    "        const colorTarget = event.target instanceof Element ? event.target.closest('[data-studio-forge-color]') : null;",
    "        if (colorTarget) {",
    "            const forge = activeForge();",
    "            if (!forge) return;",
    "            forge.selectedColor = safeString(colorTarget.getAttribute('data-studio-forge-color')).toLowerCase();",
    "            forge.tool = 'paint';",
    "            render();",
    "            return;",
    "        }",
    "        const toolTarget = event.target instanceof Element ? event.target.closest('[data-studio-forge-tool]') : null;",
    "        if (toolTarget) {",
    "            const forge = activeForge();",
    "            if (!forge) return;",
    "            const tool = safeString(toolTarget.getAttribute('data-studio-forge-tool')).toLowerCase();",
    "            forge.tool = tool === 'erase' ? 'erase' : 'paint';",
    "            render();",
    "            return;",
    "        }",
    "        const actionTarget = event.target instanceof Element ? event.target.closest('[data-studio-forge-action]') : null;",
    "        if (!actionTarget) return;",
    "        const forge = activeForge();",
    "        if (!forge) return;",
    "        const action = safeString(actionTarget.getAttribute('data-studio-forge-action')).toLowerCase();",
    "        if (action === 'generate') {",
    "            forge.draftPixels = moduleStudioGeneratePixelPrompt(forge.prompt || forge.draftName, forge.size, forge.palette);",
    "            forge.editingAssetId = '';",
    "            forge.syncedSelectionId = safeString(wb.selectedAssetId);",
    "            pushLog('Generated local pixel draft.', 'ok');",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'clear') {",
    "            forge.draftPixels = moduleStudioPixelBlank(forge.size);",
    "            forge.editingAssetId = '';",
    "            forge.syncedSelectionId = safeString(wb.selectedAssetId);",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'mirror') {",
    "            mirrorDraft();",
    "            pushLog('Mirrored pixel draft.', 'ok');",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'save') {",
    "            const asset = moduleStudioSaveForgeAsset(wb, safeString(forge.editingAssetId));",
    "            if (!asset) {",
    "                pushLog('Nothing to save yet. Add pixels first.', 'warn');",
    "                return;",
    "            }",
    "            pushLog(`Saved ${safeString(asset.name)}.`, 'ok');",
    "            callChanged();",
    "            render();",
    "            return;",
    "        }",
    "        if (action === 'export') {",
    "            const filename = `${(safeString(forge.draftName).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'pixel-asset')}.png`;",
    "            const dataUrl = moduleStudioPixelsToDataUrl(forge.draftPixels, forge.size, 10);",
    "            moduleStudioDownloadDataUrl(filename, dataUrl);",
    "            pushLog(`Exported ${filename}.`, 'ok');",
    "            return;",
    "        }",
    "    });",
    "",
    "    render();",
    "    return { render };",
    "}",
    "",
    "function moduleRenderWorkbenchStudioOss(container, wb) {",
    "    if (!container || !wb) return false;",
    "    if (wb.ossError) return false;",
    "    if (!wb.ossReady || !window.WaveSurfer) {",
    "        moduleWorkbenchRenderEngineLoading(",
    "            container,",
    "            'Comfy Studio Engine',",
    "            'WaveSurfer timeline with media asset queue and clip sequencing.',",
    "            'Loading Comfy Studio audio engine...',",
    "            'Fallback timeline editor will run if loading fails.',",
    "        );",
    "        if (!wb.ossLoading) {",
    "            wb.ossLoading = true;",
    "            void moduleWorkbenchLoadWaveSurfer().then(() => {",
    "                wb.ossReady = true;",
    "                wb.ossLoading = false;",
    "                wb.ossError = '';",
    "                moduleWorkbenchRefreshMode('studio');",
    "            }).catch((error) => {",
    "                wb.ossLoading = false;",
    "                wb.ossReady = false;",
    "                wb.ossError = safeString(error?.message) || 'Failed to load WaveSurfer.';",
    "                notifyUser('Comfy Studio audio engine failed to load, using fallback timeline.', { tone: 'warn', durationMs: 2300, debugKind: 'studio' });",
    "                moduleWorkbenchRefreshMode('studio');",
    "            });",
    "        }",
    "        return true;",
    "    }",
    "",
    "    if (!Array.isArray(wb.assets)) wb.assets = [];",
    "    if (!Array.isArray(wb.timeline)) wb.timeline = [];",
    "    if (!Array.isArray(wb.logs)) wb.logs = [];",
    "    wb.nextId = Math.max(1, Number(wb.nextId) || 1);",
    "    wb.selectedAssetId = safeString(wb.selectedAssetId);",
    "    wb.selectedClipId = safeString(wb.selectedClipId);",
    "    wb.playhead = Math.max(0, Number(wb.playhead) || 0);",
    "    moduleStudioEnsureForgeState(wb);",
    "    moduleStudioEnsureWorkbenchState(wb);",
    "",
    "    moduleWorkbenchHeader(container, 'Comfy Studio Engine', 'Thomas-managed Comfy pipelines with connected tools, queue orchestration, and delivery outputs.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-studio-oss';",
    "    shell.innerHTML = `",
    "        <aside class=\"module-wb-side-card module-wb-studio-library\">",
    "            <h4>Asset Library</h4>",
    "            <div class=\"module-wb-studio-chip-row\" data-studio-library-stats></div>",
    "            <div class=\"module-wb-field-grid module-wb-studio-filter-grid\">",
    "                <label class=\"module-wb-field module-wb-field-wide\">Search",
    "                    <input type=\"text\" data-studio-filter-query value=\"${escapeHtml(wb.assetQuery)}\" placeholder=\"Search assets, mime, or type\" />",
    "                </label>",
    "                <label class=\"module-wb-field\">Type",
    "                    <select data-studio-filter-type>",
    "                        ${moduleStudioOptionMarkup(MODULE_STUDIO_ASSET_TYPES, wb.assetType)}",
    "                    </select>",
    "                </label>",
    "            </div>",
    "            <form class=\"module-wb-inline-form\" data-studio-asset-form>",
    "                <input type=\"text\" data-studio-asset-name placeholder=\"Asset name\" />",
    "                <input type=\"number\" data-studio-asset-duration min=\"1\" max=\"900\" value=\"6\" />",
    "                <button type=\"submit\" class=\"module-item-btn\">Add Note Asset</button>",
    "            </form>",
    "            <label class=\"module-wb-file-pick\">",
    "                <input type=\"file\" data-studio-file-input accept=\"audio/*,video/*,image/*\" multiple />",
    "                <span>Import audio/video/image</span>",
    "            </label>",
    "            <div class=\"module-wb-asset-list\" data-studio-assets></div>",
    "            ${moduleStudioForgeMarkup(wb)}",
    "        </aside>",
    "        <section class=\"module-wb-stage-card module-wb-studio-stage\">",
    "            <div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Pipeline Preview</span><span class=\"module-wb-stage-meta\" data-studio-status></span></div>",
    "            <div class=\"module-wb-wave-stage\" data-studio-wave></div>",
    "            <div class=\"module-wb-image-stage hidden\" data-studio-image-stage></div>",
    "            <input type=\"range\" class=\"module-wb-range\" data-studio-playhead min=\"0\" max=\"1\" step=\"0.05\" value=\"0\" />",
    "            <div class=\"module-wb-timeline\" data-studio-timeline></div>",
    "            <section class=\"module-wb-studio-control-grid\">",
    "                <label class=\"module-wb-field\">Audio Preset",
    "                    <select data-studio-audio-preset>",
    "                        ${moduleStudioOptionMarkup(MODULE_STUDIO_AUDIO_PRESETS, wb.audioPreset)}",
    "                    </select>",
    "                </label>",
    "                <label class=\"module-wb-field\">Render Preset",
    "                    <select data-studio-render-preset>",
    "                        ${moduleStudioOptionMarkup(MODULE_STUDIO_RENDER_PRESETS, wb.renderPreset)}",
    "                    </select>",
    "                </label>",
    "                <label class=\"module-wb-field\">Generation Tool",
    "                    <select data-studio-generation-tool>",
    "                        ${moduleStudioOptionMarkup(MODULE_STUDIO_GENERATION_TOOLS, wb.generationTool)}",
    "                    </select>",
    "                </label>",
    "                <label class=\"module-wb-field module-wb-field-wide\">Generation Prompt",
    "                    <input type=\"text\" data-studio-generation-prompt value=\"${escapeHtml(wb.generationPrompt)}\" placeholder=\"isometric robot office, clean product art\" />",
    "                </label>",
    "            </section>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"play\">${wb.playing ? 'Pause' : 'Play'}</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"stop\">Stop</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"export\">Export</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"export_otio\">OTIO</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"ffmpeg\">ffmpeg</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"copy_audio\">Audio Chain</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"copy_render\">Render Cmd</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"copy_gen\">Gen Cmd</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"queue_preset\">Queue Preset</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-action=\"clear_queue\">Clear Queue</button>",
    "            </div>",
    "        </section>",
    "        <aside class=\"module-wb-inspector-card module-wb-studio-inspector\">",
    "            <div data-studio-inspector></div>",
    "            <h4>Render Queue</h4>",
    "            <div class=\"module-wb-log-list\" data-studio-batch></div>",
    "            <h4>Run Log</h4>",
    "            <div class=\"module-wb-log-list\" data-studio-logs></div>",
    "        </aside>",
    "        ${moduleWorkbenchRenderOssStack('studio', 'Comfy Studio OSS Toolchain')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const assets = shell.querySelector('[data-studio-assets]');",
    "    const timeline = shell.querySelector('[data-studio-timeline]');",
    "    const status = shell.querySelector('[data-studio-status]');",
    "    const inspector = shell.querySelector('[data-studio-inspector]');",
    "    const logs = shell.querySelector('[data-studio-logs]');",
    "    const batch = shell.querySelector('[data-studio-batch]');",
    "    const slider = shell.querySelector('[data-studio-playhead]');",
    "    const form = shell.querySelector('[data-studio-asset-form]');",
    "    const fileInput = shell.querySelector('[data-studio-file-input]');",
    "    const filterQueryInput = shell.querySelector('[data-studio-filter-query]');",
    "    const filterTypeSelect = shell.querySelector('[data-studio-filter-type]');"
].join("\n");
