/* app.js lines 30001-31000 */
export default [
    "            void refreshTaskContinuity({ force: true });",
    "        });",
    "    }",
    "    updateTaskContinuityVisibility({ refresh: true });",
    "    initDebugDockTabs();",
    "    renderDebugEventLog();",
    "    renderDebugConsoleLog();",
    "    renderDebugNetworkLog();",
    "    renderDebugLivePanels();",
    "    updateDebugNetworkSummary();",
    "    startDebugConsoleCapture();",
    "    startDebugNetworkCapture();",
    "    syncLayoutOffsets();",
    "    if (mainContent) {",
    "        mainContent.addEventListener('scroll', normalizeMainContentScroll, { passive: true });",
    "    }",
    "    normalizeMainContentScroll();",
    "    window.addEventListener('resize', syncLayoutOffsets);",
    "",
    "    const toggleSidebarCollapsed = () => {",
    "        if (!sidebar || isSidebarAnimating()) return;",
    "        startSidebarAnimationLock();",
    "        sidebar.classList.toggle('collapsed');",
    "        saveStoredSidebarCollapsed(Boolean(sidebar.classList.contains('collapsed')));",
    "        syncLayoutOffsets();",
    "        pushDebugEvent('layout', sidebar.classList.contains('collapsed') ? 'Collapsed sidebar' : 'Expanded sidebar');",
    "    };",
    "",
    "    if (sidebarToggleBtn) {",
    "        sidebarToggleBtn.addEventListener('click', toggleSidebarCollapsed);",
    "    }",
    "    if (sidebarCollapseBtn) {",
    "        sidebarCollapseBtn.addEventListener('click', toggleSidebarCollapsed);",
    "    }",
    "",
    "    if (newChatSidebar) {",
    "        newChatSidebar.addEventListener('click', (event) => {",
    "            const wantsNewChat = Boolean(event && (event.shiftKey || event.metaKey || event.ctrlKey));",
    "            if (wantsNewChat) {",
    "                ensureSettingsUiClosed();",
    "                createNewSessionAndRefresh();",
    "                if (globalSearchInput) globalSearchInput.value = '';",
    "                setSidebarNavMode('chat');",
    "                setSidebarSearchScope('chat');",
    "                return;",
    "            }",
    "            void promptRenameAgentIdentity();",
    "        });",
    "    }",
    "",
    "    if (navChatBtn) {",
    "        navChatBtn.addEventListener('click', (event) => {",
    "            const isCaretClick = Boolean(event.target instanceof Element && event.target.closest('.nav-chat-caret'));",
    "            if (isCaretClick) {",
    "                event.preventDefault();",
    "                event.stopPropagation();",
    "                if (sidebarNavMode !== 'chat') {",
    "                    ensureSettingsUiClosed();",
    "                    setSidebarNavMode('chat');",
    "                    setSidebarSearchScope('chat');",
    "                }",
    "                setChatListExpanded(!chatListExpanded);",
    "                return;",
    "            }",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('chat');",
    "            setSidebarSearchScope('chat');",
    "            if (globalSearchInput) globalSearchInput.focus();",
    "        });",
    "    }",
    "",
    "    if (navOfficeBtn) {",
    "        navOfficeBtn.addEventListener('click', () => {",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('office');",
    "        });",
    "    }",
    "",
    "    if (navMissionBtn) {",
    "        navMissionBtn.addEventListener('click', () => {",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('mission');",
    "        });",
    "    }",
    "",
    "    if (navContentBtn) {",
    "        navContentBtn.addEventListener('click', () => {",
    "            ensureSettingsUiClosed();",
    "            setSidebarNavMode('content');",
    "        });",
    "    }",
    "",
    "    if (sidebarModeButtons.length) {",
    "        sidebarModeButtons.forEach((button) => {",
    "            button.addEventListener('click', () => {",
    "                const mode = normalizeNavMode(button.dataset.navMode);",
    "                if (!MODULE_NAV_MODE_SET.has(mode)) return;",
    "                ensureSettingsUiClosed();",
    "                setSidebarNavMode(mode);",
    "            });",
    "        });",
    "    }",
    "",
    "    if (globalSearchInput) {",
    "        globalSearchInput.addEventListener('input', () => {",
    "            renderSidebarChatList();",
    "        });",
    "    }",
    "",
    "    if (debugDockToggleBtn) {",
    "        debugDockToggleBtn.addEventListener('click', () => {",
    "            if (isDebugDockAnimating()) return;",
    "            const open = Boolean(appRoot?.classList.contains('debug-dock-open'));",
    "            setDebugDockOpen(!open);",
    "        });",
    "    }",
    "",
    "    if (debugDockCloseBtn) {",
    "        debugDockCloseBtn.addEventListener('click', () => {",
    "            if (isDebugDockAnimating()) return;",
    "            setDebugDockOpen(false);",
    "        });",
    "    }",
    "",
    "    if (debugDockRefreshBtn) {",
    "        debugDockRefreshBtn.addEventListener('click', () => {",
    "            void refreshDebugLiveData({ force: true, reason: 'manual' });",
    "        });",
    "    }",
    "",
    "    if (debugCopySnapshotBtn) {",
    "        debugCopySnapshotBtn.addEventListener('click', () => {",
    "            void copyDebugSnapshotToClipboard();",
    "        });",
    "    }",
    "",
    "    if (debugOnboardingRepairBtn) {",
    "        debugOnboardingRepairBtn.addEventListener('click', () => {",
    "            void runDebugOnboardingRepairNow();",
    "        });",
    "    }",
    "",
    "    if (debugClearEventsBtn) {",
    "        debugClearEventsBtn.addEventListener('click', () => {",
    "            debugEvents = [];",
    "            renderDebugEventLog();",
    "            pushDebugEvent('tools', 'Cleared debug events');",
    "        });",
    "    }",
    "",
    "    if (debugClearConsoleBtn) {",
    "        debugClearConsoleBtn.addEventListener('click', () => {",
    "            debugConsoleEntries = [];",
    "            renderDebugConsoleLog();",
    "            updateDebugDockSnapshot();",
    "            pushDebugEvent('tools', 'Cleared console diagnostics');",
    "        });",
    "    }",
    "",
    "    if (debugClearNetworkBtn) {",
    "        debugClearNetworkBtn.addEventListener('click', () => {",
    "            debugNetworkEntries = [];",
    "            renderDebugNetworkLog();",
    "            updateDebugNetworkSummary();",
    "            updateDebugDockSnapshot();",
    "            pushDebugEvent('tools', 'Cleared network diagnostics');",
    "        });",
    "    }",
    "",
    "    window.addEventListener('resize', syncLayoutOffsets);",
    "",
    "    if (chatHistorySelector) {",
    "        chatHistorySelector.addEventListener('change', () => {",
    "            const selectedSession = chatHistorySelector.value;",
    "            if (selectedSession === 'new') {",
    "                createNewSessionAndRefresh();",
    "            } else {",
    "                loadSessionFromHistory(selectedSession);",
    "            }",
    "        });",
    "    }",
    "",
    "    if (settingsAdvancedToggle && settingsSuite) {",
    "        settingsAdvancedToggle.addEventListener('change', () => {",
    "            settingsSuite.classList.toggle('advanced-mode', settingsAdvancedToggle.checked);",
    "            updateSettingsSectionNavVisibility();",
    "        });",
    "    }",
    "    initSettingsSectionNavigation();",
    "",
    "    bindRangeValue(settingFontSize, settingFontSizeValue, (v) => `${Math.round(v)}px`);",
    "    bindRangeValue(settingVoiceSpeed, settingVoiceSpeedValue, (v) => `${v.toFixed(2)}x`);",
    "    bindRangeValue(settingAdvTemperature, settingAdvTemperatureValue, (v) => v.toFixed(2));",
    "    bindRangeValue(settingAdvTopP, settingAdvTopPValue, (v) => v.toFixed(2));",
    "    bindRangeValue(settingAdvFrequencyPenalty, settingAdvFrequencyPenaltyValue, (v) => v.toFixed(1));",
    "    bindRangeValue(settingAdvPresencePenalty, settingAdvPresencePenaltyValue, (v) => v.toFixed(1));",
    "    bindRangeValue(settingAdvAutoToolThreshold, settingAdvAutoToolThresholdValue, (v) => v.toFixed(2));",
    "",
    "    if (changeAvatarBtn && settingsAvatarInput) {",
    "        changeAvatarBtn.addEventListener('click', () => {",
    "            settingsAvatarInput.click();",
    "        });",
    "    }",
    "",
    "    if (settingsAvatarInput) {",
    "        settingsAvatarInput.addEventListener('change', () => {",
    "            const file = settingsAvatarInput.files && settingsAvatarInput.files[0];",
    "            if (!file) return;",
    "            if (!file.type.startsWith('image/')) {",
    "                notifyUser('Please choose an image file for your profile photo.', {",
    "                    tone: 'warning',",
    "                    debugKind: 'warning',",
    "                    durationMs: 2800,",
    "                });",
    "                settingsAvatarInput.value = '';",
    "                return;",
    "            }",
    "            const reader = new FileReader();",
    "            reader.onload = (event) => {",
    "                pendingAvatarOverride = safeString(event.target?.result);",
    "                refreshSettingsAvatarPreview();",
    "            };",
    "            reader.readAsDataURL(file);",
    "            settingsAvatarInput.value = '';",
    "        });",
    "    }",
    "",
    "    if (removeAvatarBtn) {",
    "        removeAvatarBtn.addEventListener('click', () => {",
    "            pendingAvatarOverride = '';",
    "            refreshSettingsAvatarPreview();",
    "        });",
    "    }",
    "",
    "    if (settingsDisplayName) {",
    "        settingsDisplayName.addEventListener('input', refreshSettingsAvatarPreview);",
    "    }",
    "",
    "    if (settingsBtn && settingsModal) {",
    "        settingsBtn.addEventListener('click', () => {",
    "            openSettingsModal();",
    "        });",
    "    }",
    "",
    "    if (closeSettingsBtn && settingsModal) {",
    "        closeSettingsBtn.addEventListener('click', closeSettingsModal);",
    "    }",
    "",
    "    if (saveSettingsBtn) {",
    "        saveSettingsBtn.addEventListener('click', saveSettings);",
    "    }",
    "",
    "    initModelSetup();",
    "    pushDebugEvent('runtime', 'UI initialized');",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  MODEL SETUP & SETTINGS                                                 ║",
    "// ║  Model selector, profile switching, settings form, save/load prefs      ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function initModelSetup() {",
    "    // Open Trigger",
    "    modelSetupBtn.addEventListener('click', () => {",
    "        modelSetupModal.classList.add('active');",
    "        modelSetupModal.style.display = 'flex';",
    "",
    "        // Seed from saved preferences or current active profile",
    "        const savedProfile = safeString(currentPreferences?.advanced?.model?.active_profile)",
    "            || modelSelector.value;",
    "        setupProviderSelector.value = savedProfile;",
    "",
    "        // Restore segmented controls from preferences",
    "        const savedAutonomy = safeString(currentPreferences?.autonomy?.default_level).replace('L', '');",
    "        if (savedAutonomy) {",
    "            activeAutonomyLevel = parseInt(savedAutonomy, 10) || 3;",
    "            setSegmentedControlSelection('setupAutonomyGroup', String(activeAutonomyLevel));",
    "        }",
    "        const prefsEconomy = safeString(currentPreferences?.advanced?.runtime?.default_token_economy);",
    "        const econRevMap = { cheap: 'cheap', optimal: 'balanced', max: 'max' };",
    "        if (prefsEconomy && econRevMap[prefsEconomy]) {",
    "            activeTokenEconomy = econRevMap[prefsEconomy];",
    "            setSegmentedControlSelection('setupEconomyGroup', activeTokenEconomy);",
    "        }",
    "",
    "        if (typeof _syncProviderUI === 'function') _syncProviderUI(savedProfile);",
    "    });",
    "",
    "    // Close Triggers",
    "    closeModelSetupBtn.addEventListener('click', () => {",
    "        modelSetupModal.style.display = 'none';",
    "    });",
    "",
    "    document.getElementById('modelSetupBackdrop').addEventListener('click', () => {",
    "        modelSetupModal.style.display = 'none';",
    "    });",
    "",
    "    // Personality Dropdown Logic (Show/Hide Custom Textarea)",
    "    setupPersonalitySelector.addEventListener('change', (e) => {",
    "        if (e.target.value === 'custom') {",
    "            customPersonalityGroup.classList.remove('hidden');",
    "        } else {",
    "            customPersonalityGroup.classList.add('hidden');",
    "        }",
    "    });",
    "",
    "    // Segmented Controls (Autonomy & Economy)",
    "    const bindSegmentedControl = (groupId, updateCallback) => {",
    "        const group = document.getElementById(groupId);",
    "        group.querySelectorAll('.segment').forEach(btn => {",
    "            btn.addEventListener('click', (e) => {",
    "                // Clear active",
    "                group.querySelectorAll('.segment').forEach(b => b.classList.remove('active'));",
    "                // Set active",
    "                const target = e.currentTarget;",
    "                target.classList.add('active');",
    "                updateCallback(target.dataset.level);",
    "            });",
    "        });",
    "    };",
    "",
    "    bindSegmentedControl('setupAutonomyGroup', val => activeAutonomyLevel = parseInt(val, 10));",
    "    bindSegmentedControl('setupEconomyGroup', val => activeTokenEconomy = val);",
    "    bindSegmentedControl('setupReasoningEffortGroup', val => { activeReasoningEffort = val; });",
    "",
    "    // Provider change: sync model select, reasoning effort, and meta",
    "    const _syncProviderUI = (profileName) => {",
    "        const p = availableModelProfiles.find(m => m.name === profileName);",
    "        const reasoningGroup = document.getElementById('setupReasoningGroup');",
    "        const metaEl = document.getElementById('setupProfileMeta');",
    "",
    "        // --- Model <select> ---",
    "        if (p && setupModelSelector) {",
    "            const defaultModel = safeString(p.model).split('/').pop() || '';",
    "            _populateModelSelect([defaultModel, ...(KNOWN_MODEL_SUGGESTIONS[p.provider] || [])]);",
    "            setupModelSelector.value = defaultModel;",
    "            activeModelOverride = defaultModel;",
    "            _discoverProfileModels(profileName, defaultModel);",
    "        }",
    "",
    "        // --- Reasoning effort ---",
    "        if (p && (p.provider === 'codex' || p.reasoning_effort)) {",
    "            if (reasoningGroup) reasoningGroup.style.display = '';",
    "            const cur = p.reasoning_effort || 'medium';",
    "            activeReasoningEffort = cur;",
    "            setSegmentedControlSelection('setupReasoningEffortGroup', cur);",
    "        } else {",
    "            if (reasoningGroup) reasoningGroup.style.display = 'none';",
    "            activeReasoningEffort = '';",
    "        }",
    "",
    "        // --- Profile meta (provider + url) ---",
    "        if (metaEl && p) {",
    "            const url = safeString(p.base_url);",
    "            metaEl.textContent = p.provider + (url ? '  \\u2022  ' + url : '');",
    "        } else if (metaEl) {",
    "            metaEl.textContent = '';",
    "        }",
    "    };",
    "",
    "    // Populate model <select> with deduped options",
    "    function _populateModelSelect(modelIds) {",
    "        if (!setupModelSelector) return;",
    "        const currentVal = setupModelSelector.value;",
    "        setupModelSelector.innerHTML = '';",
    "        const seen = new Set();",
    "        for (const id of modelIds) {",
    "            const clean = safeString(id);",
    "            if (!clean || seen.has(clean)) continue;",
    "            seen.add(clean);",
    "            const opt = document.createElement('option');",
    "            opt.value = clean;",
    "            opt.textContent = clean;",
    "            setupModelSelector.appendChild(opt);",
    "        }",
    "        if (currentVal && seen.has(currentVal)) setupModelSelector.value = currentVal;",
    "    }",
    "",
    "    // Async model discovery from server",
    "    async function _discoverProfileModels(profileName, defaultModel) {",
    "        try {",
    "            const res = await fetch(`/api/models/${encodeURIComponent(profileName)}/ids`);",
    "            if (!res.ok) return;",
    "            const data = await res.json();",
    "            const discovered = Array.isArray(data.models) ? data.models : [];",
    "            const provider = (availableModelProfiles.find(m => m.name === profileName) || {}).provider || '';",
    "            const staticFallbacks = KNOWN_MODEL_SUGGESTIONS[provider] || [];",
    "            const merged = [defaultModel, ...discovered, ...staticFallbacks];",
    "            _populateModelSelect(merged);",
    "            // Re-select saved model_id if available",
    "            const savedModelId = safeString(currentPreferences?.advanced?.model?.model_id);",
    "            if (savedModelId && setupModelSelector.querySelector(`option[value=\"${CSS.escape(savedModelId)}\"]`)) {",
    "                setupModelSelector.value = savedModelId;",
    "                activeModelOverride = savedModelId;",
    "            }",
    "        } catch (e) {",
    "            console.warn('Model discovery failed for', profileName, e);",
    "        }",
    "    }",
    "",
    "    setupProviderSelector.addEventListener('change', (e) => _syncProviderUI(e.target.value));",
    "",
    "    // Model selector change tracking",
    "    if (setupModelSelector) {",
    "        setupModelSelector.addEventListener('change', (e) => {",
    "            activeModelOverride = safeString(e.target.value);",
    "        });",
    "    }",
    "",
    "    // Apply Button — persist ALL settings",
    "    applyModelSetupBtn.addEventListener('click', async () => {",
    "        // 1. Capture current UI state",
    "        const selectedProfile = setupProviderSelector.value;",
    "        const selectedModel = setupModelSelector ? safeString(setupModelSelector.value) : '';",
    "        activeModelOverride = selectedModel;",
    "        modelSelector.value = selectedProfile;",
    "",
    "        // 2. Update header label + localStorage backup",
    "        modelSetupCurrentLabel.textContent = _profileHeaderLabel(selectedProfile);",
    "        try { window.localStorage.setItem('thomas_active_profile', selectedProfile); } catch (_) {}",
    "        try { window.localStorage.setItem('thomas_active_model_id', selectedModel); } catch (_) {}",
    "",
    "        // 3. Build preferences patch (map UI values to preferences schema)",
    "        const economyMap = { cheap: 'cheap', balanced: 'optimal', max: 'max' };",
    "        const patch = {",
    "            memory: { enabled_global: Boolean(setupMemoryToggle && setupMemoryToggle.checked) },",
    "            autonomy: { default_level: 'L' + activeAutonomyLevel },",
    "            advanced: {",
    "                model: {",
    "                    active_profile: selectedProfile,",
    "                    model_id: selectedModel,",
    "                    reasoning_effort: activeReasoningEffort || 'medium',",
    "                },",
    "                runtime: {",
    "                    default_token_economy: economyMap[activeTokenEconomy] || 'optimal',",
    "                },",
    "            },",
    "        };",
    "",
    "        // 4. PATCH to server",
    "        try {",
    "            const res = await fetch('/api/preferences', {",
    "                method: 'PATCH',",
    "                headers: { 'Content-Type': 'application/json' },",
    "                body: JSON.stringify(patch),",
    "            });",
    "            if (res.ok) {",
    "                currentPreferences = await res.json();",
    "                updateSidebarIdentity();",
    "            }",
    "        } catch (e) {",
    "            console.error('Failed to persist model setup:', e);",
    "        }",
    "",
    "        // 5. Close Modal",
    "        modelSetupModal.style.display = 'none';",
    "    });",
    "",
    "    // Restart Server button",
    "    if (restartServerBtn) {",
    "        restartServerBtn.addEventListener('click', async () => {",
    "            if (!confirm('Restart the Thomas server? Active requests will be interrupted.')) return;",
    "            try {",
    "                await fetch('/api/server/restart', { method: 'POST' });",
    "            } catch (e) { console.error('Restart request failed:', e); }",
    "",
    "            modelSetupModal.style.display = 'none';",
    "            if (restartOverlay) restartOverlay.classList.remove('hidden');",
    "",
    "            // Poll /api/health until server comes back (max 30s, poll every 500ms)",
    "            const restartStatus = document.getElementById('restartStatus');",
    "            for (let i = 0; i < 60; i++) {",
    "                if (restartStatus) restartStatus.textContent = `Waiting\\u2026 ${Math.floor(i * 0.5)}s`;",
    "                await new Promise(r => setTimeout(r, 500));",
    "                try {",
    "                    const probe = await fetch('/api/health', { signal: AbortSignal.timeout(1500) });",
    "                    if (probe.ok) {",
    "                        if (restartStatus) restartStatus.textContent = 'Reconnecting\\u2026';",
    "                        if (restartOverlay) restartOverlay.classList.add('hidden');",
    "                        await fetchModels();",
    "                        // Re-import conversation into a fresh server session",
    "                        if (chatHistory.length > 0) {",
    "                            try {",
    "                                const importPayload = {",
    "                                    profile: (setupProviderSelector && setupProviderSelector.value) || 'local',",
    "                                    conversation: chatHistory.map(m => ({",
    "                                        role: safeString(m.role),",
    "                                        content: safeString(m.content),",
    "                                    })),",
    "                                };",
    "                                const importRes = await fetch('/api/session/import', {",
    "                                    method: 'POST',",
    "                                    headers: { 'Content-Type': 'application/json' },",
    "                                    body: JSON.stringify(importPayload),",
    "                                });",
    "                                if (importRes.ok) {",
    "                                    const imported = await importRes.json();",
    "                                    if (safeString(imported?.session_id)) {",
    "                                        sessionId = safeString(imported.session_id);",
    "                                    }",
    "                                }",
    "                            } catch (_e) { console.warn('Session re-import after restart failed:', _e); }",
    "                        }",
    "                        return;",
    "                    }",
    "                } catch (_) { /* server still down */ }",
    "            }",
    "            if (restartOverlay) restartOverlay.classList.add('hidden');",
    "            alert('Server did not come back within 30 seconds. Check manually.');",
    "        });",
    "    }",
    "}",
    "",
    "async function persistMemorySetting(isEnabled) {",
    "    try {",
    "        const res = await fetch('/api/preferences', {",
    "            method: 'PATCH',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({",
    "                memory: { enabled_global: isEnabled }",
    "            })",
    "        });",
    "        if (res.ok) {",
    "            currentPreferences = await res.json();",
    "            updateSidebarIdentity();",
    "        }",
    "    } catch (e) {",
    "        console.error(\"Failed to save memory preference:\", e);",
    "    }",
    "}",
    "",
    "function openSettingsModal() {",
    "    if (!settingsModal) return;",
    "    setDebugDockOpen(false, { recordEvent: false });",
    "    settingsModal.classList.remove('hidden');",
    "    if (appRoot) appRoot.classList.add('settings-active');",
    "    settingsReturnNavMode = normalizeNavMode(sidebarNavMode);",
    "    setSidebarNavMode('chat', { persist: false });",
    "    if (settingsBtn) settingsBtn.classList.add('active');",
    "    loadSettings();",
    "}",
    "",
    "function isSettingsScreenOpen() {",
    "    return Boolean(settingsModal && !settingsModal.classList.contains('hidden'));",
    "}",
    "",
    "function ensureSettingsUiClosed() {",
    "    if (!settingsModal) return;",
    "    if (isSettingsScreenOpen()) {",
    "        closeSettingsModal();",
    "        return;",
    "    }",
    "    settingsModal.classList.add('hidden');",
    "    if (appRoot) appRoot.classList.remove('settings-active');",
    "    if (settingsBtn) settingsBtn.classList.remove('active');",
    "}",
    "",
    "function closeSettingsModal() {",
    "    if (!settingsModal) return;",
    "    settingsModal.classList.add('hidden');",
    "    if (appRoot) appRoot.classList.remove('settings-active');",
    "    if (settingsBtn) settingsBtn.classList.remove('active');",
    "    setSidebarNavMode(settingsReturnNavMode || loadStoredNavMode(), { persist: false });",
    "",
    "    const hasMessages = Boolean(chatMessagesInner && chatMessagesInner.children.length > 0);",
    "    if (welcomeScreen) welcomeScreen.classList.toggle('hidden', hasMessages);",
    "    if (chatScrollArea) chatScrollArea.classList.toggle('hidden', !hasMessages);",
    "}",
    "",
    "function toInt(value, fallback, min, max) {",
    "    const n = Number.parseInt(String(value), 10);",
    "    if (!Number.isFinite(n)) return fallback;",
    "    return Math.max(min, Math.min(max, n));",
    "}",
    "",
    "function toFloat(value, fallback, min, max) {",
    "    const n = Number.parseFloat(String(value));",
    "    if (!Number.isFinite(n)) return fallback;",
    "    return Math.max(min, Math.min(max, n));",
    "}",
    "",
    "function bindRangeValue(inputEl, valueEl, formatter) {",
    "    if (!inputEl || !valueEl) return;",
    "    const update = () => {",
    "        valueEl.textContent = formatter(Number(inputEl.value));",
    "    };",
    "    inputEl.addEventListener('input', update);",
    "    update();",
    "}",
    "",
    "function applyApiKeyPlaceholders(apiKeys = {}) {",
    "    const mapping = {",
    "        openai: settingApiKeyOpenai,",
    "        anthropic: settingApiKeyAnthropic,",
    "        google: settingApiKeyGoogle,",
    "        elevenlabs: settingApiKeyElevenlabs,",
    "        azure_openai: settingApiKeyAzureOpenai,",
    "        custom: settingApiKeyCustom,",
    "    };",
    "    Object.entries(mapping).forEach(([provider, input]) => {",
    "        if (!input) return;",
    "        input.value = '';",
    "        input.placeholder = safeString(apiKeys[provider]) || 'Not set';",
    "    });",
    "}",
    "",
    "function normalizeChatMode(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    return new Set(['auto', 'fast', 'thinking', 'swarm', 'batch']).has(mode) ? mode : '';",
    "}",
    "",
    "function _profileHeaderLabel(profileName) {",
    "    const p = availableModelProfiles.find(m => m.name === profileName);",
    "    if (!p) return profileName;",
    "    // Prefer active overrides over profile defaults",
    "    const model = activeModelOverride",
    "        || safeString(p.model).split('/').pop()",
    "        || profileName;",
    "    const effort = activeReasoningEffort || safeString(p.reasoning_effort);",
    "    return effort ? `${model} (${effort})` : model;",
    "}",
    "",
    "function applyProfileSelection(profileRaw) {",
    "    const profile = safeString(profileRaw);",
    "    if (!profile) return;",
    "    if (setupProviderSelector) setupProviderSelector.value = profile;",
    "    if (modelSelector) modelSelector.value = profile;",
    "    if (modelSetupCurrentLabel) modelSetupCurrentLabel.textContent = _profileHeaderLabel(profile);",
    "}",
    "",
    "function setSegmentedControlSelection(groupId, levelRaw) {",
    "    const group = document.getElementById(groupId);",
    "    if (!group) return;",
    "    const level = safeString(levelRaw);",
    "    group.querySelectorAll('.segment').forEach((segmentBtn) => {",
    "        const isActive = safeString(segmentBtn.dataset.level) === level;",
    "        segmentBtn.classList.toggle('active', isActive);",
    "    });",
    "}",
    "",
    "function applyUiStatePatchEvent(evt) {",
    "    if (!evt || typeof evt !== 'object') return;",
    "    const rawPatch = evt.applied_patch && typeof evt.applied_patch === 'object'",
    "        ? evt.applied_patch",
    "        : (evt.patch && typeof evt.patch === 'object' ? evt.patch : null);",
    "    if (!rawPatch) return;",
    "",
    "    applyProfileSelection(rawPatch.activeProfile);",
    "",
    "    const mode = normalizeChatMode(rawPatch.mode);",
    "    if (mode) {",
    "        activeChatMode = mode;",
    "        if (settingAdvDefaultMode) settingAdvDefaultMode.value = mode;",
    "    }",
    "",
    "    const settings = rawPatch.settings;",
    "    if (!settings || typeof settings !== 'object') return;",
    "",
    "    const autonomyLevel = Number.parseInt(String(settings.autonomyLevel ?? ''), 10);",
    "    if (Number.isFinite(autonomyLevel)) {",
    "        const nextLevel = Math.max(1, Math.min(4, autonomyLevel));",
    "        activeAutonomyLevel = nextLevel;",
    "        setSegmentedControlSelection('setupAutonomyGroup', String(nextLevel));",
    "        if (settingAutonomy) settingAutonomy.value = `L${nextLevel}`;",
    "    }",
    "",
    "    const themeRaw = safeString(settings.theme).toLowerCase();",
    "    if (themeRaw) {",
    "        const themeValue = themeRaw === 'system' ? 'auto' : themeRaw;",
    "        if (settingTheme && new Set(['auto', 'light', 'dark']).has(themeValue)) {",
    "            settingTheme.value = themeValue;",
    "        }",
    "    }",
    "}",
    "",
    "function refreshSettingsAvatarPreview() {",
    "    const name = safeString(settingsDisplayName?.value) || resolveAgentName(currentPreferences);",
    "    const avatarBase = pendingAvatarOverride !== null",
    "        ? pendingAvatarOverride",
    "        : safeString(currentPreferences?.profile?.avatar_url);",
    "    const avatarUrl = safeString(avatarBase) || safeString(currentCodexStatus?.avatar_url);",
    "    setAvatarVisual(settingsProfileAvatar, {",
    "        text: initialsFromName(name),",
    "        imageUrl: avatarUrl,",
    "    });",
    "}",
    "",
    "async function refreshIdentityState() {",
    "    try {",
    "        const [prefsRes, codexRes] = await Promise.all([",
    "            fetchJsonSafe('/api/preferences'),",
    "            fetchJsonSafe('/api/codex/status'),",
    "        ]);",
    "        if (prefsRes.ok) {",
    "            currentPreferences = prefsRes.data || {};",
    "            const prefAutonomyRaw = safeString(currentPreferences?.autonomy?.default_level).replace(/^l/i, '');",
    "            const prefAutonomy = Number.parseInt(prefAutonomyRaw, 10);",
    "            if (Number.isFinite(prefAutonomy)) {",
    "                activeAutonomyLevel = Math.max(1, Math.min(4, prefAutonomy));",
    "                setSegmentedControlSelection('setupAutonomyGroup', String(activeAutonomyLevel));",
    "                if (settingAutonomy) settingAutonomy.value = `L${activeAutonomyLevel}`;",
    "            }",
    "        }",
    "        if (codexRes.ok) {",
    "            currentCodexStatus = codexRes.data || null;",
    "        } else if (!codexRes.ok && codexRes.status) {",
    "            currentCodexStatus = null;",
    "        }",
    "    } catch (e) {",
    "        console.error('Failed to load identity state', e);",
    "    } finally {",
    "        applyInterfaceMotionPreference();",
    "        updateSidebarIdentity();",
    "        setDebugDockOpen(false, { recordEvent: false });",
    "        updateDebugDockSnapshot();",
    "    }",
    "}",
    "",
    "async function loadSettings() {",
    "    try {",
    "        const [prefsRes, codexRes] = await Promise.all([",
    "            fetchJsonSafe('/api/preferences'),",
    "            fetchJsonSafe('/api/codex/status'),",
    "        ]);",
    "        if (!prefsRes.ok) {",
    "            throw new Error(`Failed to load preferences (${prefsRes.status})`);",
    "        }",
    "",
    "        currentPreferences = prefsRes.data || {};",
    "        currentCodexStatus = codexRes.ok ? (codexRes.data || null) : null;",
    "        applyInterfaceMotionPreference();",
    "",
    "        const appearance = currentPreferences.appearance || {};",
    "        const memory = currentPreferences.memory || {};",
    "        const notifications = currentPreferences.notifications || {};",
    "        const autonomy = currentPreferences.autonomy || {};",
    "        const voice = currentPreferences.voice || {};",
    "        const advanced = currentPreferences.advanced || {};",
    "        const advModel = advanced.model || {};",
    "        const advTools = advanced.tools || {};",
    "        const advMemory = advanced.memory || {};",
    "        const advCost = advanced.cost || {};",
    "        const advRuntime = advanced.runtime || {};",
    "        const advFailover = advanced.failover || {};",
    "        const advPrivacy = advanced.privacy || {};",
    "        const advInterface = advanced.interface || {};",
    "",
    "        if (settingsAdvancedToggle && settingsSuite) {",
    "            settingsAdvancedToggle.checked = false;",
    "            settingsSuite.classList.remove('advanced-mode');",
    "        }",
    "        if (settingsSectionSearch) settingsSectionSearch.value = '';",
    "        if (settingsSections) settingsSections.scrollTop = 0;",
    "        updateSettingsSectionNavVisibility();",
    "",
    "        if (settingTheme) settingTheme.value = safeString(appearance.theme) || 'auto';",
    "        const autonomyDefaultLevel = safeString(autonomy.default_level) || 'L2';",
    "        if (settingAutonomy) settingAutonomy.value = autonomyDefaultLevel;",
    "        const autonomyNumeric = Number.parseInt(autonomyDefaultLevel.replace(/^l/i, ''), 10);",
    "        if (Number.isFinite(autonomyNumeric)) {",
    "            activeAutonomyLevel = Math.max(1, Math.min(4, autonomyNumeric));",
    "            setSegmentedControlSelection('setupAutonomyGroup', String(activeAutonomyLevel));",
    "        }",
    "",
    "        if (settingFontSize) {",
    "            const fontSize = toInt(appearance.font_size, 16, 12, 28);",
    "            settingFontSize.value = String(fontSize);",
    "            if (settingFontSizeValue) settingFontSizeValue.textContent = `${fontSize}px`;",
    "        }",
    "",
    "        if (settingBubbleStyle) settingBubbleStyle.value = safeString(appearance.bubble_style) || 'rounded';",
    "        if (settingMemoryEnabled) settingMemoryEnabled.checked = Boolean(memory.enabled_global);",
    "        if (setupMemoryToggle) setupMemoryToggle.checked = Boolean(memory.enabled_global);",
    "        if (settingDesktopNotifications) settingDesktopNotifications.checked = Boolean(notifications.desktop);",
    "",
    "        if (settingVoice) settingVoice.value = safeString(voice.tts_voice) || 'default';",
    "        if (settingMicDeviceId) settingMicDeviceId.value = safeString(voice.mic_device_id);",
    "        if (settingWakeWordEnabled) settingWakeWordEnabled.checked = Boolean(voice.wake_word_enabled);",
    "",
    "        if (settingVoiceSpeed) {",
    "            const voiceSpeed = toFloat(voice.speed, 1.0, 0.5, 2.0);",
    "            settingVoiceSpeed.value = String(voiceSpeed);",
    "            settingVoiceSpeed.dispatchEvent(new Event('input'));",
    "        }",
    "",
    "        if (settingConcurrencyLimit) {",
    "            settingConcurrencyLimit.value = String(toInt(autonomy.concurrency_limit, 2, 1, 64));",
    "        }",
    "",
    "        if (settingWebPush) settingWebPush.checked = Boolean(notifications.web_push);",
    "        if (settingTelegram) settingTelegram.checked = Boolean(notifications.telegram);",
    "",
    "        if (settingAdvTemperature) {",
    "            settingAdvTemperature.value = String(toFloat(advModel.temperature, 0.7, 0, 2));",
    "            settingAdvTemperature.dispatchEvent(new Event('input'));",
    "        }",
    "        if (settingAdvTopP) {",
    "            settingAdvTopP.value = String(toFloat(advModel.top_p, 1, 0, 1));",
    "            settingAdvTopP.dispatchEvent(new Event('input'));",
    "        }",
    "        if (settingAdvFrequencyPenalty) {",
    "            settingAdvFrequencyPenalty.value = String(toFloat(advModel.frequency_penalty, 0, -2, 2));",
    "            settingAdvFrequencyPenalty.dispatchEvent(new Event('input'));",
    "        }",
    "        if (settingAdvPresencePenalty) {",
    "            settingAdvPresencePenalty.value = String(toFloat(advModel.presence_penalty, 0, -2, 2));",
    "            settingAdvPresencePenalty.dispatchEvent(new Event('input'));",
    "        }",
    "        if (settingAdvMaxOutputTokens) settingAdvMaxOutputTokens.value = String(toInt(advModel.max_output_tokens, 4096, 128, 32768));",
    "        if (settingAdvReasoningEffort) settingAdvReasoningEffort.value = safeString(advModel.reasoning_effort) || 'medium';",
    "        if (settingAdvReasoningBudget) settingAdvReasoningBudget.value = String(toInt(advModel.reasoning_token_budget, 4096, 128, 65536));",
    "        if (settingAdvDeterministicSeed) settingAdvDeterministicSeed.value = advModel.deterministic_seed === null || advModel.deterministic_seed === undefined ? '' : String(advModel.deterministic_seed);",
    "        if (settingAdvJsonMode) settingAdvJsonMode.checked = Boolean(advModel.json_mode);",
    "        if (settingAdvStopSequences) settingAdvStopSequences.value = safeString(advModel.stop_sequences);",
    "        const runtimeDefaultMode = normalizeChatMode(safeString(advRuntime.default_mode) || 'auto') || 'auto';",
    "        if (settingAdvDefaultMode) settingAdvDefaultMode.value = runtimeDefaultMode;",
    "        activeChatMode = runtimeDefaultMode;",
    "",
    "        const runtimeDefaultEconomy = safeString(advRuntime.default_token_economy) || 'optimal';",
    "        if (settingAdvDefaultTokenEconomy) settingAdvDefaultTokenEconomy.value = runtimeDefaultEconomy;",
    "        const economyForComposer = runtimeDefaultEconomy === 'optimal' ? 'balanced' : runtimeDefaultEconomy;",
    "        if (new Set(['cheap', 'balanced', 'max']).has(economyForComposer)) {",
    "            activeTokenEconomy = economyForComposer;",
    "            setSegmentedControlSelection('setupEconomyGroup', economyForComposer);",
    "        }",
    "        if (settingAdvMaxAgentIterations) settingAdvMaxAgentIterations.value = String(toInt(advRuntime.max_agent_iterations, 0, 0, 200));",
    "        if (settingAdvQualityEnforce) settingAdvQualityEnforce.checked = Boolean(advRuntime.quality_enforce);",
    "        if (settingAdvQualityRequireVerification) settingAdvQualityRequireVerification.checked = Boolean(advRuntime.quality_require_verification_for_coding);",
    "        if (settingAdvQualityRequireTests) settingAdvQualityRequireTests.checked = Boolean(advRuntime.quality_require_tests_for_code_edits);",
    "        if (settingAdvQualityRequireMonolithGuard) settingAdvQualityRequireMonolithGuard.checked = Boolean(advRuntime.quality_require_monolith_guard_for_coding);",
    "",
    "        if (settingAdvAutoToolThreshold) {",
    "            settingAdvAutoToolThreshold.value = String(toFloat(advTools.auto_tool_threshold, 0.45, 0, 1));",
    "            settingAdvAutoToolThreshold.dispatchEvent(new Event('input'));",
    "        }",
    "        if (settingAdvToolTimeoutS) settingAdvToolTimeoutS.value = String(toInt(advTools.tool_timeout_s, 120, 5, 1800));",
    "        if (settingAdvMaxParallelTools) settingAdvMaxParallelTools.value = String(toInt(advTools.max_parallel_tools, 6, 1, 32));",
    "        if (settingAdvRequireCommandApproval) settingAdvRequireCommandApproval.checked = Boolean(advTools.require_command_approval);",
    "        if (settingAdvAllowShell) settingAdvAllowShell.checked = Boolean(advTools.allow_shell);",
    "        if (settingAdvAllowFileWrite) settingAdvAllowFileWrite.checked = Boolean(advTools.allow_file_write);",
    "        if (settingAdvAllowNetwork) settingAdvAllowNetwork.checked = Boolean(advTools.allow_network);",
    "        if (settingAdvAllowBrowser) settingAdvAllowBrowser.checked = Boolean(advTools.allow_browser);",
    "        if (settingAdvAllowChannels) settingAdvAllowChannels.checked = Boolean(advTools.allow_channels);",
    "        if (settingAdvAllowGit) settingAdvAllowGit.checked = Boolean(advTools.allow_git);",
    "        if (settingAdvAllowedPaths) settingAdvAllowedPaths.value = safeString(advTools.allowed_paths);",
    "        if (settingAdvBlockedCommands) settingAdvBlockedCommands.value = safeString(advTools.blocked_commands);",
    "",
    "        if (settingAdvIncludeGlobalMemory) settingAdvIncludeGlobalMemory.checked = Boolean(advMemory.include_global_memory);",
    "        if (settingAdvRetrievalTopK) settingAdvRetrievalTopK.value = String(toInt(advMemory.retrieval_top_k, 8, 1, 64));",
    "        if (settingAdvMaxPackTokens) settingAdvMaxPackTokens.value = String(toInt(advMemory.max_pack_tokens, 1200, 200, 64000));",
    "        if (settingAdvDecayHalfLifeHours) settingAdvDecayHalfLifeHours.value = String(toFloat(advMemory.decay_half_life_hours, 240, 1, 87600));",
    "        if (settingAdvAutoSummarizeThreshold) settingAdvAutoSummarizeThreshold.value = String(toInt(advMemory.auto_summarize_threshold, 80, 10, 2000));",
    "        if (settingAdvMemoryDecayDays) settingAdvMemoryDecayDays.value = String(toInt(advMemory.memory_decay_days, 90, 1, 3650));",
    "        if (settingAdvAutoCompactEnabled) settingAdvAutoCompactEnabled.checked = Boolean(advMemory.auto_compact_enabled);",
    "        if (settingAdvAutoCompactEpisodeThreshold) settingAdvAutoCompactEpisodeThreshold.value = String(toInt(advMemory.auto_compact_episode_threshold, 2000, 10, 1000000));",
    "        if (settingAdvAutoCompactMinIntervalHours) settingAdvAutoCompactMinIntervalHours.value = String(toFloat(advMemory.auto_compact_min_interval_hours, 24, 0.1, 8760));",
    "        if (settingAdvAutoOptimizeEnabled) settingAdvAutoOptimizeEnabled.checked = Boolean(advMemory.auto_optimize_enabled);",
    "        if (settingAdvAutoOptimizeWasteThreshold) settingAdvAutoOptimizeWasteThreshold.value = String(toFloat(advMemory.auto_optimize_waste_threshold, 0.22, 0, 1));",
    "        if (settingAdvAutoOptimizeMinIntervalHours) settingAdvAutoOptimizeMinIntervalHours.value = String(toFloat(advMemory.auto_optimize_min_interval_hours, 12, 0.1, 8760));",
    "        if (settingAdvContradictionPolicy) settingAdvContradictionPolicy.value = safeString(advMemory.contradiction_policy) || 'ask';",
    "        if (settingAdvContextPruneStrategy) settingAdvContextPruneStrategy.value = safeString(advMemory.context_prune_strategy) || 'balanced';",
    "        if (settingAdvIncludeProfileMemory) settingAdvIncludeProfileMemory.checked = Boolean(advMemory.include_profile_memory);",
    "        if (settingAdvIncludeThreadMemory) settingAdvIncludeThreadMemory.checked = Boolean(advMemory.include_thread_memory);",
    "        if (settingAdvPinsOnly) settingAdvPinsOnly.checked = Boolean(advMemory.pins_only);",
    "        if (settingAdvPinnedContext) settingAdvPinnedContext.value = safeString(advMemory.pinned_context);",
    "",
    "        if (settingAdvSessionTokenBudget) settingAdvSessionTokenBudget.value = String(toInt(advCost.session_token_budget, 200000, 1000, 5000000));",
    "        if (settingAdvDailyTokenBudget) settingAdvDailyTokenBudget.value = String(toInt(advCost.daily_token_budget, 2000000, 10000, 50000000));",
    "        if (settingAdvMaxRetries) settingAdvMaxRetries.value = String(toInt(advCost.max_retries, 2, 0, 20));",
    "        if (settingAdvRetryBackoffMs) settingAdvRetryBackoffMs.value = String(toInt(advCost.retry_backoff_ms, 800, 0, 120000));",
    "        if (settingAdvThrottleOnBudget) settingAdvThrottleOnBudget.checked = Boolean(advCost.throttle_on_budget);",
    "        if (settingAdvLowCostMode) settingAdvLowCostMode.checked = Boolean(advCost.low_cost_mode);",
    "        if (settingAdvProviderFailoverChain) settingAdvProviderFailoverChain.value = safeString(advCost.provider_failover_chain);",
    "        if (settingAdvModelFailoverChain) settingAdvModelFailoverChain.value = safeString(advCost.model_failover_chain);",
    "        if (settingAdvFailoverEnabled) settingAdvFailoverEnabled.checked = Boolean(advFailover.enabled);",
    "        if (settingAdvChatAutoFailover) settingAdvChatAutoFailover.checked = Boolean(advFailover.chat_auto_failover);",
    "        if (settingAdvFallbackOnAuthError) settingAdvFallbackOnAuthError.checked = Boolean(advFailover.fallback_on_auth_error);",
    "        if (settingAdvFailoverCooldownSeconds) settingAdvFailoverCooldownSeconds.value = String(toInt(advFailover.cooldown_seconds, 300, 0, 86400));",
    "",
    "        if (settingAdvRetentionDays) settingAdvRetentionDays.value = String(toInt(advPrivacy.retention_days, 90, 1, 3650));",
    "        if (settingAdvTelemetryEnabled) settingAdvTelemetryEnabled.checked = Boolean(advPrivacy.telemetry_enabled);",
    "        if (settingAdvRedactSecretsInLogs) settingAdvRedactSecretsInLogs.checked = Boolean(advPrivacy.redact_secrets_in_logs);",
    "        if (settingAdvPiiGuardStrict) settingAdvPiiGuardStrict.checked = Boolean(advPrivacy.pii_guard_strict);",
    "        if (settingAdvLocalOnlyMode) settingAdvLocalOnlyMode.checked = Boolean(advPrivacy.local_only_mode);",
    "        if (settingAdvAuditLogEnabled) settingAdvAuditLogEnabled.checked = Boolean(advPrivacy.audit_log_enabled);",
    "        if (settingAdvExportOnExit) settingAdvExportOnExit.checked = Boolean(advPrivacy.export_on_exit);",
    "",
    "        if (settingAdvUiDensity) settingAdvUiDensity.value = safeString(advInterface.ui_density) || 'comfortable';",
    "        if (settingAdvCodeTheme) settingAdvCodeTheme.value = safeString(advInterface.code_theme) || 'atom-one-dark';",
    "        if (settingAdvEventLogVerbosity) settingAdvEventLogVerbosity.value = safeString(advInterface.event_log_verbosity) || 'standard';",
    "        if (settingAdvShowTimestamps) settingAdvShowTimestamps.checked = Boolean(advInterface.show_timestamps);",
    "        if (settingAdvShowTokenMeter) settingAdvShowTokenMeter.checked = Boolean(advInterface.show_token_meter);",
    "        if (settingAdvAnimationsEnabled) settingAdvAnimationsEnabled.checked = Boolean(advInterface.animations_enabled);",
    "        if (settingAdvDebugPanelEnabled) settingAdvDebugPanelEnabled.checked = Boolean(advInterface.debug_panel_enabled);",
    "        if (settingAdvLabsFlags) settingAdvLabsFlags.value = safeString(advInterface.labs_flags);",
    "",
    "        applyApiKeyPlaceholders(currentPreferences.api_keys || {});",
    "",
    "        const displayName = resolveAgentName(currentPreferences);",
    "        if (settingsDisplayName) settingsDisplayName.value = displayName;",
    "        pendingAvatarOverride = null;",
    "        refreshSettingsAvatarPreview();",
    "",
    "        if (settingsAccountMeta) {",
    "            if (currentCodexStatus?.logged_in) {",
    "                const plan = safeString(currentCodexStatus.plan_type) || 'plan';",
    "                const email = safeString(currentCodexStatus.email) || 'account';",
    "                settingsAccountMeta.textContent = `Connected as ${email} (${plan})`;",
    "            } else {",
    "                settingsAccountMeta.textContent = 'Not connected. Profile will use local settings only.';",
    "            }",
    "        }",
    "    } catch (e) {",
    "        console.error(\"Failed to load settings\", e);",
    "        notifyUser('Could not load settings right now. Check backend and retry.', {",
    "            tone: 'error',",
    "            debugKind: 'error',",
    "            durationMs: 3200,",
    "        });",
    "    }",
    "}",
    "",
    "function collectApiKeysPatch() {",
    "    const mapping = {",
    "        openai: settingApiKeyOpenai,",
    "        anthropic: settingApiKeyAnthropic,",
    "        google: settingApiKeyGoogle,",
    "        elevenlabs: settingApiKeyElevenlabs,",
    "        azure_openai: settingApiKeyAzureOpenai,",
    "        custom: settingApiKeyCustom,",
    "    };",
    "    const patch = {};",
    "    Object.entries(mapping).forEach(([provider, input]) => {",
    "        if (!input) return;",
    "        const raw = safeString(input.value);",
    "        if (!raw) return;",
    "        patch[provider] = raw.toLowerCase() === 'clear' ? '' : raw;",
    "    });",
    "    return Object.keys(patch).length > 0 ? patch : null;",
    "}",
    "",
    "async function saveSettings() {",
    "    try {",
    "        saveSettingsBtn.textContent = 'Saving...';",
    "        const profileAvatarValue = pendingAvatarOverride !== null",
    "            ? safeString(pendingAvatarOverride)",
    "            : safeString(currentPreferences?.profile?.avatar_url);",
    "        const deterministicSeedRaw = safeString(settingAdvDeterministicSeed?.value);",
    "        const deterministicSeed = deterministicSeedRaw ? toInt(deterministicSeedRaw, 0, 0, 2147483647) : null;",
    "        const patch = {",
    "            profile: {",
    "                display_name: safeString(settingsDisplayName?.value),",
    "                avatar_url: profileAvatarValue,",
    "            },",
    "            appearance: {",
    "                theme: safeString(settingTheme?.value) || 'auto',",
    "                font_size: toInt(settingFontSize?.value, 16, 12, 28),",
    "                bubble_style: safeString(settingBubbleStyle?.value) || 'rounded',",
    "            },",
    "            memory: {",
    "                enabled_global: Boolean(settingMemoryEnabled?.checked),",
    "            },",
    "            notifications: {",
    "                desktop: Boolean(settingDesktopNotifications?.checked),",
    "                web_push: Boolean(settingWebPush?.checked),",
    "                telegram: Boolean(settingTelegram?.checked),",
    "            },",
    "            autonomy: {",
    "                default_level: safeString(settingAutonomy?.value) || 'L2',",
    "                concurrency_limit: toInt(settingConcurrencyLimit?.value, 2, 1, 64),",
    "            },",
    "            voice: {",
    "                tts_voice: safeString(settingVoice?.value) || 'default',",
    "                speed: toFloat(settingVoiceSpeed?.value, 1, 0.5, 2),",
    "                wake_word_enabled: Boolean(settingWakeWordEnabled?.checked),",
    "                mic_device_id: safeString(settingMicDeviceId?.value),",
    "            },",
    "            advanced: {",
    "                model: {",
    "                    active_profile: safeString(setupProviderSelector?.value) || safeString(currentPreferences?.advanced?.model?.active_profile),",
    "                    model_id: safeString(activeModelOverride) || safeString(currentPreferences?.advanced?.model?.model_id),",
    "                    temperature: toFloat(settingAdvTemperature?.value, 0.7, 0, 2),",
    "                    top_p: toFloat(settingAdvTopP?.value, 1, 0, 1),",
    "                    frequency_penalty: toFloat(settingAdvFrequencyPenalty?.value, 0, -2, 2),",
    "                    presence_penalty: toFloat(settingAdvPresencePenalty?.value, 0, -2, 2),",
    "                    max_output_tokens: toInt(settingAdvMaxOutputTokens?.value, 4096, 128, 32768),",
    "                    reasoning_effort: safeString(settingAdvReasoningEffort?.value) || 'medium',",
    "                    reasoning_token_budget: toInt(settingAdvReasoningBudget?.value, 4096, 128, 65536),",
    "                    json_mode: Boolean(settingAdvJsonMode?.checked),",
    "                    deterministic_seed: deterministicSeed,",
    "                    stop_sequences: safeString(settingAdvStopSequences?.value),",
    "                },",
    "                runtime: {",
    "                    default_mode: safeString(settingAdvDefaultMode?.value) || 'auto',",
    "                    default_token_economy: safeString(settingAdvDefaultTokenEconomy?.value) || 'optimal',",
    "                    max_agent_iterations: toInt(settingAdvMaxAgentIterations?.value, 0, 0, 200),",
    "                    quality_enforce: Boolean(settingAdvQualityEnforce?.checked),",
    "                    quality_require_verification_for_coding: Boolean(settingAdvQualityRequireVerification?.checked),",
    "                    quality_require_tests_for_code_edits: Boolean(settingAdvQualityRequireTests?.checked),",
    "                    quality_require_monolith_guard_for_coding: Boolean(settingAdvQualityRequireMonolithGuard?.checked),",
    "                },",
    "                tools: {"
].join("\n");
