/* split from part-016.js */
export default [
    "    officeEnsureState();",
    "    officeUpdateFollowUi();",
    "    officeRenderMinimap();",
    "    officeSyncReducedMotionPreference();",
    "    if (!officeReducedMotionListenerBound && window.matchMedia) {",
    "        officeReducedMotionListenerBound = true;",
    "        const handler = () => officeSyncReducedMotionPreference();",
    "        const queryList = [",
    "            window.matchMedia('(prefers-reduced-motion: reduce)'),",
    "            window.matchMedia('(prefers-contrast: more)'),",
    "        ];",
    "        queryList.forEach((query) => {",
    "            if (!query) return;",
    "            if (typeof query.addEventListener === 'function') {",
    "                query.addEventListener('change', handler);",
    "            } else if (typeof query.addListener === 'function') {",
    "                query.addListener(handler);",
    "            }",
    "        });",
    "    }",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  MISSION CONTROL                                                        ║",
    "// ║  Agent ops, job tracking, approvals, KPIs, timeline, room load          ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function missionEnsureState() {",
    "    if (missionState) {",
    "        return missionState;",
    "    }",
    "    if (!missionWorkspace) {",
    "        return null;",
    "    }",
    "    missionState = {",
    "        active: false,",
    "        loading: false,",
    "        actionInFlight: false,",
    "        controlsBound: false,",
    "        pollTimerId: 0,",
    "        autoRefresh: true,",
    "        lastPayload: null,",
    "        lastJobsPayload: null,",
    "        lastFetchedAt: 0,",
    "    };",
    "    return missionState;",
    "}",
    "",
    "function missionToEpoch(value) {",
    "    const raw = safeString(value);",
    "    if (!raw) return 0;",
    "    const epoch = Date.parse(raw);",
    "    return Number.isFinite(epoch) ? epoch : 0;",
    "}",
    "",
    "function missionRelativeTime(value) {",
    "    const epoch = missionToEpoch(value);",
    "    if (!epoch) return '--';",
    "    const delta = Date.now() - epoch;",
    "    const abs = Math.abs(delta);",
    "    const minute = 60 * 1000;",
    "    const hour = 60 * minute;",
    "    const day = 24 * hour;",
    "",
    "    if (abs < 45000) return delta >= 0 ? 'just now' : 'soon';",
    "    if (abs < hour) {",
    "        const n = Math.max(1, Math.round(abs / minute));",
    "        return delta >= 0 ? `${n}m ago` : `in ${n}m`;",
    "    }",
    "    if (abs < day) {",
    "        const n = Math.max(1, Math.round(abs / hour));",
    "        return delta >= 0 ? `${n}h ago` : `in ${n}h`;",
    "    }",
    "    const n = Math.max(1, Math.round(abs / day));",
    "    return delta >= 0 ? `${n}d ago` : `in ${n}d`;",
    "}",
    "",
    "function missionStatusValue(statusRaw) {",
    "    return safeString(statusRaw).toLowerCase().replace(/\\s+/g, '_') || 'unknown';",
    "}",
    "",
    "function missionStatusLabel(statusRaw) {",
    "    const normalized = missionStatusValue(statusRaw);",
    "    if (normalized === 'awaiting_approval') return 'awaiting approval';",
    "    return normalized.replace(/_/g, ' ');",
    "}",
    "",
    "function missionStatusRank(statusRaw) {",
    "    const normalized = missionStatusValue(statusRaw);",
    "    const rank = {",
    "        failed: 0,",
    "        dead: 0,",
    "        cancelled: 1,",
    "        blocked: 2,",
    "        awaiting_approval: 3,",
    "        running: 4,",
    "        active: 4,",
    "        queued: 5,",
    "        pending: 5,",
    "        succeeded: 8,",
    "        completed: 8,",
    "    };",
    "    return Object.prototype.hasOwnProperty.call(rank, normalized) ? rank[normalized] : 6;",
    "}",
    "",
    "function missionRoomRank(roomRaw) {",
    "    const room = safeString(roomRaw).toLowerCase();",
    "    const rank = {",
    "        review: 0,",
    "        planning: 1,",
    "        tools: 2,",
    "        files: 3,",
    "        inbox: 4,",
    "        done: 5,",
    "    };",
    "    return Object.prototype.hasOwnProperty.call(rank, room) ? rank[room] : 6;",
    "}",
    "",
    "function missionSetConnectionState(kind = 'neutral', text = 'Standby') {",
    "    if (!missionConnectionPill) return;",
    "    missionConnectionPill.className = `mission-meta-pill ${safeString(kind) || 'neutral'}`;",
    "    missionConnectionPill.textContent = safeString(text) || 'Standby';",
    "}",
    "",
    "function missionRenderEmpty(container, message) {",
    "    if (!container) return;",
    "    container.innerHTML = '';",
    "    const empty = document.createElement('div');",
    "    empty.className = 'mission-item-empty';",
    "    empty.textContent = safeString(message) || 'No data available.';",
    "    container.appendChild(empty);",
    "}",
    "",
    "function missionCreatePill(label, extraClass = '') {",
    "    const pill = document.createElement('span');",
    "    pill.className = `mission-pill ${safeString(extraClass)}`.trim();",
    "    pill.textContent = safeString(label);",
    "    return pill;",
    "}",
    "",
    "function missionFormatSeconds(secondsRaw) {",
    "    const seconds = Number(secondsRaw || 0);",
    "    if (!Number.isFinite(seconds) || seconds <= 0) return '--';",
    "    if (seconds < 60) return `${Math.round(seconds)}s`;",
    "    if (seconds < 3600) return `${Math.round(seconds / 60)}m`;",
    "    if (seconds < 86400) return `${Math.round(seconds / 3600)}h`;",
    "    return `${Math.round(seconds / 86400)}d`;",
    "}",
    "",
    "function missionScheduleDescriptor(job) {",
    "    const schedule = job?.schedule && typeof job.schedule === 'object' ? job.schedule : null;",
    "    const nextRun = safeString(job?.next_run_at);",
    "    if (!schedule) {",
    "        return {",
    "            recurring: false,",
    "            cadence: nextRun ? 'one-time' : 'manual',",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "        };",
    "    }",
    "",
    "    const stype = safeString(schedule?.type).toLowerCase();",
    "    if (stype === 'interval') {",
    "        return {",
    "            recurring: true,",
    "            cadence: `every ${missionFormatSeconds(schedule?.every_seconds)}`,",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "        };",
    "    }",
    "    if (stype === 'daily') {",
    "        const at = safeString(schedule?.at) || '--:--';",
    "        const tz = safeString(schedule?.tz) || 'UTC';",
    "        return {",
    "            recurring: true,",
    "            cadence: `daily ${at}`,",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "            detail: tz,",
    "        };",
    "    }",
    "    if (stype === 'weekly') {",
    "        const at = safeString(schedule?.at) || '--:--';",
    "        const tz = safeString(schedule?.tz) || 'UTC';",
    "        const dows = Array.isArray(schedule?.dow) ? schedule.dow : [];",
    "        const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];",
    "        const dowLabel = dows",
    "            .map((raw) => Number(raw))",
    "            .filter((idx) => Number.isInteger(idx) && idx >= 0 && idx <= 6)",
    "            .slice(0, 7)",
    "            .map((idx) => labels[idx])",
    "            .join(', ');",
    "        return {",
    "            recurring: true,",
    "            cadence: `weekly ${at}`,",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "            detail: `${dowLabel || 'no days'} | ${tz}`,",
    "        };",
    "    }",
    "    if (stype === 'once') {",
    "        return {",
    "            recurring: false,",
    "            cadence: 'one-time',",
    "            next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "        };",
    "    }",
    "    return {",
    "        recurring: MISSION_RECURRING_SCHEDULE_TYPES.has(stype),",
    "        cadence: stype || 'scheduled',",
    "        next: nextRun ? missionRelativeTime(nextRun) : '--',",
    "    };",
    "}",
    "",
    "function missionJobStatusRank(statusRaw) {",
    "    const status = missionStatusValue(statusRaw);",
    "    const rank = {",
    "        running: 0,",
    "        awaiting_approval: 1,",
    "        queued: 2,",
    "        blocked: 3,",
    "        failed: 4,",
    "        dead: 4,",
    "        cancelled: 5,",
    "        succeeded: 6,",
    "        completed: 6,",
    "    };",
    "    return Object.prototype.hasOwnProperty.call(rank, status) ? rank[status] : 7;",
    "}",
    "",
    "function missionJobSummary(job) {",
    "    const payload = job?.payload && typeof job.payload === 'object' ? job.payload : {};",
    "    return (",
    "        safeString(payload?.goal)",
    "        || safeString(payload?.prompt)",
    "        || safeString(payload?.task)",
    "        || safeString(payload?.message)",
    "        || 'No task summary provided.'",
    "    );",
    "}",
    "",
    "function missionJobActionUrl(jobId, action) {",
    "    const safeId = encodeURIComponent(safeString(jobId));",
    "    if (!safeId) return '';"
].join("\n");
