/* app.js lines 19001-20000 */
export default [
    "            <em>${escapeHtml(safeString(cardRaw?.meta) || '')}</em>",
    "        `;",
    "        frag.appendChild(card);",
    "    });",
    "    moduleFocusStrip.appendChild(frag);",
    "}",
    "",
    "function moduleRenderSubnav(modeRaw) {",
    "    if (!moduleSubnavRow || !moduleSubnavList) return;",
    "    const mode = MODULE_NAV_MODE_SET.has(modeRaw) ? modeRaw : 'dashboard';",
    "    const state = moduleEnsureRuntime();",
    "    const sections = Array.isArray(moduleModeSurface(mode)?.sections) ? moduleModeSurface(mode).sections : [];",
    "    moduleSubnavList.innerHTML = '';",
    "    if (!sections.length) {",
    "        moduleSubnavRow.classList.add('hidden');",
    "        return;",
    "    }",
    "    const selected = safeString(state?.subnavFocus?.[mode]).toLowerCase();",
    "    moduleSubnavRow.classList.remove('hidden');",
    "    const frag = document.createDocumentFragment();",
    "    sections.forEach((label, index) => {",
    "        const labelText = safeString(label);",
    "        const isActive = selected",
    "            ? selected === labelText.toLowerCase()",
    "            : index === 0;",
    "        const chip = document.createElement('button');",
    "        chip.type = 'button';",
    "        chip.className = `module-subnav-chip${isActive ? ' active' : ''}`;",
    "        chip.dataset.moduleMode = mode;",
    "        chip.dataset.moduleSectionLabel = labelText;",
    "        chip.innerHTML = `",
    "            <i class=\"ph ${moduleSectionIcon(labelText)}\" aria-hidden=\"true\"></i>",
    "            <span>${escapeHtml(labelText)}</span>",
    "        `;",
    "        frag.appendChild(chip);",
    "        if (!selected && index === 0 && state) {",
    "            state.subnavFocus[mode] = labelText;",
    "        }",
    "    });",
    "    moduleSubnavList.appendChild(frag);",
    "}",
    "",
    "function moduleBuildFlair(mode, signals, snapshot) {",
    "    const jobs = Array.isArray(snapshot?.jobs) ? snapshot.jobs.length : 0;",
    "    const events = Array.isArray(snapshot?.events) ? snapshot.events.length : 0;",
    "    const approvals = moduleFocusValue(signals?.approvals_pending);",
    "    const connectors = moduleFocusValue(signals?.integrations_connected);",
    "    const base = [",
    "        { label: 'Mode', value: safeString(moduleSeed(mode)?.pill) || 'Live', tone: 'ok' },",
    "        { label: 'Approvals', value: approvals, tone: Number(signals?.approvals_pending || 0) > 0 ? 'warn' : 'ok' },",
    "        { label: 'Connectors', value: connectors, tone: Number(signals?.integrations_connected || 0) > 0 ? 'ok' : 'warn' },",
    "    ];",
    "",
    "    if (mode === 'operations') {",
    "        return [",
    "            { label: 'Open Work', value: moduleFocusValue(signals?.task_jobs), tone: Number(signals?.task_jobs || 0) > 0 ? 'ok' : '' },",
    "            { label: 'Exceptions', value: moduleFocusValue(signals?.flow_failures), tone: Number(signals?.flow_failures || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Events', value: moduleFocusValue(events), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'inbox') {",
    "        return [",
    "            { label: 'Unread', value: moduleFocusValue(signals?.inbox_unread), tone: '' },",
    "            { label: 'Urgent', value: moduleFocusValue(signals?.inbox_urgent), tone: Number(signals?.inbox_urgent || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Needs Reply', value: moduleFocusValue(signals?.inbox_needs_reply), tone: Number(signals?.inbox_needs_reply || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'notifications') {",
    "        return [",
    "            { label: 'Critical', value: moduleFocusValue(signals?.notif_escalations), tone: Number(signals?.notif_escalations || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Bundled', value: moduleFocusValue(signals?.notif_bundled), tone: '' },",
    "            { label: 'Rules', value: moduleFocusValue(signals?.notif_rules), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'automations' || mode === 'app_builder') {",
    "        return [",
    "            { label: 'Flows', value: moduleFocusValue(signals?.flow_active), tone: '' },",
    "            { label: 'Failing', value: moduleFocusValue(signals?.flow_failures), tone: Number(signals?.flow_failures || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Jobs', value: moduleFocusValue(jobs), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'agents') {",
    "        return [",
    "            { label: 'Active', value: moduleFocusValue(signals?.agent_active), tone: Number(signals?.agent_active || 0) > 0 ? 'ok' : '' },",
    "            { label: 'Delegated', value: moduleFocusValue(signals?.agent_delegated), tone: '' },",
    "            { label: 'Escalations', value: moduleFocusValue(signals?.agent_escalations), tone: Number(signals?.agent_escalations || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'studio' || mode === 'game_studio' || mode === 'lab_3d') {",
    "        return [",
    "            { label: 'Queue', value: moduleFocusValue(signals?.render_queue ?? signals?.print_queue), tone: '' },",
    "            { label: 'Output', value: moduleFocusValue(signals?.exports_today ?? signals?.game_playtests), tone: '' },",
    "            { label: 'Failures', value: moduleFocusValue(signals?.flow_failures), tone: Number(signals?.flow_failures || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'dev_studio') {",
    "        return [",
    "            { label: 'Failing Tests', value: moduleFocusValue(signals?.dev_failures), tone: Number(signals?.dev_failures || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Open PR Signals', value: moduleFocusValue(signals?.dev_pr_open), tone: '' },",
    "            { label: 'Deploys', value: moduleFocusValue(signals?.deploys_today), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'research_lab') {",
    "        return [",
    "            { label: 'Briefs', value: moduleFocusValue(signals?.research_briefs), tone: '' },",
    "            { label: 'Citations', value: moduleFocusValue(signals?.research_citations), tone: '' },",
    "            { label: 'Watchlist', value: moduleFocusValue(signals?.research_competitors), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'people') {",
    "        return [",
    "            { label: 'Contacts', value: moduleFocusValue(signals?.people_contacts), tone: '' },",
    "            { label: 'Follow-ups', value: moduleFocusValue(signals?.people_followups), tone: Number(signals?.people_followups || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'At Risk', value: moduleFocusValue(signals?.people_at_risk), tone: Number(signals?.people_at_risk || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'finance') {",
    "        return [",
    "            { label: 'Anomalies', value: moduleFocusValue(signals?.finance_anomalies), tone: Number(signals?.finance_anomalies || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Approvals', value: moduleFocusValue(signals?.finance_approvals), tone: Number(signals?.finance_approvals || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Subscriptions', value: moduleFocusValue(signals?.finance_subscriptions), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'integrations') {",
    "        return [",
    "            { label: 'Connected', value: moduleFocusValue(signals?.integrations_connected), tone: Number(signals?.integrations_connected || 0) > 0 ? 'ok' : '' },",
    "            { label: 'Degraded', value: moduleFocusValue(signals?.integrations_degraded), tone: Number(signals?.integrations_degraded || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Reconnects', value: moduleFocusValue(signals?.integrations_reconnects), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'marketplace') {",
    "        return [",
    "            { label: 'Installed', value: moduleFocusValue(signals?.market_installed), tone: '' },",
    "            { label: 'Updates', value: moduleFocusValue(signals?.market_updates), tone: Number(signals?.market_updates || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Events', value: moduleFocusValue(events), tone: '' },",
    "        ];",
    "    }",
    "    if (mode === 'vault') {",
    "        return [",
    "            { label: 'Secrets', value: moduleFocusValue(signals?.vault_secrets), tone: '' },",
    "            { label: 'Expiring', value: moduleFocusValue(signals?.vault_expiring), tone: Number(signals?.vault_expiring || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Approvals', value: approvals, tone: Number(signals?.approvals_pending || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'timeline') {",
    "        return [",
    "            { label: 'Events 24h', value: moduleFocusValue(signals?.timeline_events), tone: '' },",
    "            { label: 'Automated', value: moduleFocusValue(signals?.timeline_automated), tone: '' },",
    "            { label: 'Retries', value: moduleFocusValue(signals?.timeline_retries), tone: Number(signals?.timeline_retries || 0) > 0 ? 'warn' : 'ok' },",
    "        ];",
    "    }",
    "    if (mode === 'infinite') {",
    "        return [",
    "            { label: 'Handoffs', value: moduleFocusValue(signals?.handoffs_pending), tone: '' },",
    "            { label: 'Offline', value: moduleFocusValue(signals?.offline_captures), tone: Number(signals?.offline_captures || 0) > 0 ? 'warn' : 'ok' },",
    "            { label: 'Routes', value: moduleFocusValue(signals?.push_routes), tone: '' },",
    "        ];",
    "    }",
    "",
    "    return base;",
    "}",
    "",
    "function moduleRenderFlair(flairRaw) {",
    "    if (!moduleFlairRow) return;",
    "    const flair = Array.isArray(flairRaw) ? flairRaw.filter(Boolean) : [];",
    "    moduleFlairRow.innerHTML = '';",
    "    if (!flair.length) {",
    "        moduleFlairRow.classList.add('hidden');",
    "        return;",
    "    }",
    "    moduleFlairRow.classList.remove('hidden');",
    "    const frag = document.createDocumentFragment();",
    "    flair.forEach((itemRaw) => {",
    "        const tone = moduleToneClass(itemRaw?.tone);",
    "        const item = document.createElement('article');",
    "        item.className = `module-flair-pill${tone ? ` ${tone}` : ''}`;",
    "        item.innerHTML = `",
    "            <span>${escapeHtml(safeString(itemRaw?.label) || 'Info')}</span>",
    "            <strong>${escapeHtml(moduleFocusValue(itemRaw?.value))}</strong>",
    "        `;",
    "        frag.appendChild(item);",
    "    });",
    "    moduleFlairRow.appendChild(frag);",
    "}",
    "",
    "function moduleWorkbenchMakeId(prefix = 'wb') {",
    "    return `${prefix}-${Date.now()}-${Math.round(Math.random() * 1_000_000)}`;",
    "}",
    "",
    "function moduleWorkbenchPointFromEvent(canvas, event) {",
    "    if (!(canvas instanceof HTMLCanvasElement) || !event) return { x: 0, y: 0 };",
    "    const rect = canvas.getBoundingClientRect();",
    "    const scaleX = rect.width > 0 ? (canvas.width / rect.width) : 1;",
    "    const scaleY = rect.height > 0 ? (canvas.height / rect.height) : 1;",
    "    return {",
    "        x: (event.clientX - rect.left) * scaleX,",
    "        y: (event.clientY - rect.top) * scaleY,",
    "    };",
    "}",
    "",
    "function moduleWorkbenchCopyJson(payload, label = 'Workbench JSON') {",
    "    const text = JSON.stringify(payload, null, 2);",
    "    if (navigator?.clipboard?.writeText) {",
    "        navigator.clipboard.writeText(text).then(() => {",
    "            notifyUser(`${label} copied to clipboard.`, { tone: 'success', durationMs: 1600, debugKind: 'workbench' });",
    "        }).catch(() => {",
    "            notifyUser(`${label} ready in console (clipboard blocked).`, { tone: 'info', durationMs: 2100, debugKind: 'workbench' });",
    "            console.log(label, text);",
    "        });",
    "        return;",
    "    }",
    "    notifyUser(`${label} ready in console.`, { tone: 'info', durationMs: 2100, debugKind: 'workbench' });",
    "    console.log(label, text);",
    "}",
    "",
    "function moduleWorkbenchCopyText(textRaw, label = 'Workbench Text') {",
    "    const text = safeString(textRaw);",
    "    if (!text) {",
    "        notifyUser(`${label} is empty.`, { tone: 'warn', durationMs: 1800, debugKind: 'workbench' });",
    "        return;",
    "    }",
    "    if (navigator?.clipboard?.writeText) {",
    "        navigator.clipboard.writeText(text).then(() => {",
    "            notifyUser(`${label} copied to clipboard.`, { tone: 'success', durationMs: 1600, debugKind: 'workbench' });",
    "        }).catch(() => {",
    "            notifyUser(`${label} ready in console (clipboard blocked).`, { tone: 'info', durationMs: 2100, debugKind: 'workbench' });",
    "            console.log(label, text);",
    "        });",
    "        return;",
    "    }",
    "    notifyUser(`${label} ready in console.`, { tone: 'info', durationMs: 2100, debugKind: 'workbench' });",
    "    console.log(label, text);",
    "}",
    "",
    "function moduleWorkbenchDownloadText(filenameRaw, textRaw, mime = 'text/plain;charset=utf-8') {",
    "    const filename = safeString(filenameRaw) || 'download.txt';",
    "    const text = safeString(textRaw);",
    "    const blob = new Blob([text], { type: safeString(mime) || 'text/plain;charset=utf-8' });",
    "    const url = URL.createObjectURL(blob);",
    "    const anchor = document.createElement('a');",
    "    anchor.href = url;",
    "    anchor.download = filename;",
    "    anchor.rel = 'noopener';",
    "    document.body.appendChild(anchor);",
    "    anchor.click();",
    "    window.setTimeout(() => {",
    "        anchor.remove();",
    "        URL.revokeObjectURL(url);",
    "    }, 80);",
    "}",
    "",
    "function moduleWorkbenchOssCatalog(modeRaw) {",
    "    const mode = safeString(modeRaw);",
    "    if (mode === 'lab_3d') {",
    "        return [",
    "            {",
    "                title: 'JSCAD',",
    "                license: 'MIT',",
    "                docsUrl: 'https://github.com/jscad/OpenJSCAD.org',",
    "                why: 'Parametric CAD in browser/CLI',",
    "                command: 'npx @jscad/cli design.jscad -o output.stl',",
    "            },",
    "            {",
    "                title: 'Maker.js',",
    "                license: 'Apache-2.0',",
    "                docsUrl: 'https://github.com/microsoft/maker.js',",
    "                why: '2D CAD/CNC geometry generation',",
    "                command: 'npm i makerjs',",
    "            },",
    "            {",
    "                title: 'Blender CLI',",
    "                license: 'GPL',",
    "                docsUrl: 'https://docs.blender.org/manual/en/latest/advanced/command_line/render.html',",
    "                why: 'Headless rendering and automation',",
    "                command: 'blender -b scene.blend -f 1',",
    "            },",
    "        ];",
    "    }",
    "    if (mode === 'automations') {",
    "        return [",
    "            {",
    "                title: 'n8n',",
    "                license: 'Fair-code',",
    "                docsUrl: 'https://github.com/n8n-io/n8n',",
    "                why: 'Production workflow automation',",
    "                command: 'docker run -it --rm --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n',",
    "            },",
    "            {",
    "                title: 'Node-RED',",
    "                license: 'Apache-2.0',",
    "                docsUrl: 'https://github.com/node-red/node-red',",
    "                why: 'Event-driven visual flows',",
    "                command: 'docker run -it --rm -p 1880:1880 -v node_red_data:/data nodered/node-red:latest',",
    "            },",
    "            {",
    "                title: 'LiteGraph.js',",
    "                license: 'MIT',",
    "                docsUrl: 'https://github.com/jagenjo/litegraph.js',",
    "                why: 'Embeddable node graph runtime',",
    "                command: 'npm i litegraph.js',",
    "            },",
    "        ];",
    "    }",
    "    if (mode === 'app_builder') {",
    "        return [",
    "            {",
    "                title: 'Appsmith',",
    "                license: 'Apache-2.0',",
    "                docsUrl: 'https://github.com/appsmithorg/appsmith',",
    "                why: 'Internal tools and admin panels',",
    "                command: 'docker run --pull always --rm -p 80:80 -p 443:443 -v appsmith-stacks:/appsmith-stacks appsmith/appsmith-ce',",
    "            },",
    "            {",
    "                title: 'Budibase',",
    "                license: 'GPLv3',",
    "                docsUrl: 'https://github.com/Budibase/budibase',",
    "                why: 'Low-code app + automation platform',",
    "                command: 'curl -s https://raw.githubusercontent.com/Budibase/budibase/master/hosting/docker-compose.yaml -o budibase-docker-compose.yaml',",
    "            },",
    "            {",
    "                title: 'NocoBase',",
    "                license: 'AGPL-3.0',",
    "                docsUrl: 'https://github.com/nocobase/nocobase',",
    "                why: 'Extensible enterprise low-code',",
    "                command: 'npm create nocobase-app@latest',",
    "            },",
    "        ];",
    "    }",
    "    if (mode === 'studio') {",
    "        return [",
    "            {",
    "                title: 'FFmpeg',",
    "                license: 'LGPL/GPL',",
    "                docsUrl: 'https://ffmpeg.org/legal.html',",
    "                why: 'Core transcoding, mastering, audio cleanup, and delivery exports.',",
    "                command: 'winget install --id Gyan.FFmpeg -e',",
    "            },",
    "            {",
    "                title: 'OpenTimelineIO',",
    "                license: 'Apache-2.0',",
    "                docsUrl: 'https://github.com/PixarAnimationStudios/OpenTimelineIO',",
    "                why: 'Portable editorial timeline interchange across tools.',",
    "                command: 'pip install opentimelineio',",
    "            },",
    "            {",
    "                title: 'WaveSurfer.js',",
    "                license: 'BSD-3-Clause',",
    "                docsUrl: 'https://github.com/katspaugh/wavesurfer.js',",
    "                why: 'In-browser waveform visualization and seek controls.',",
    "                command: 'npm i wavesurfer.js',",
    "            },",
    "            {",
    "                title: 'Blender',",
    "                license: 'GPL',",
    "                docsUrl: 'https://docs.blender.org/manual/en/latest/getting_started/about/license.html',",
    "                why: '3D scenes, motion graphics, and scripted rendering.',",
    "                command: 'winget install --id BlenderFoundation.Blender -e',",
    "            },",
    "            {",
    "                title: 'Krita',",
    "                license: 'GPL',",
    "                docsUrl: 'https://krita.org/en/about/license/',",
    "                why: 'Digital painting and concept art with pro brush engines.',",
    "                command: 'winget install --id KDE.Krita -e',",
    "            },",
    "            {",
    "                title: 'Inkscape',",
    "                license: 'GPL',",
    "                docsUrl: 'https://inkscape.org/about/',",
    "                why: 'Vector graphics for logos, icons, and UI assets.',",
    "                command: 'winget install --id Inkscape.Inkscape -e',",
    "            },",
    "            {",
    "                title: 'Kdenlive',",
    "                license: 'GPL-3.0',",
    "                docsUrl: 'https://apps.kde.org/kdenlive/',",
    "                why: 'Full NLE timeline editing with effect stacks.',",
    "                command: 'winget install --id KDE.Kdenlive -e',",
    "            },",
    "            {",
    "                title: 'Shotcut',",
    "                license: 'GPL-3.0',",
    "                docsUrl: 'https://github.com/mltframework/shotcut',",
    "                why: 'Fast cross-platform editor for quick cuts and exports.',",
    "                command: 'winget install --id Meltytech.Shotcut -e',",
    "            },",
    "            {",
    "                title: 'Comfy Studio',",
    "                license: 'GPL-3.0',",
    "                docsUrl: 'https://github.com/comfyanonymous/ComfyUI',",
    "                why: 'Thomas-integrated wrapper for local ComfyUI node workflows.',",
    "                command: 'git clone https://github.com/comfyanonymous/ComfyUI.git',",
    "            },",
    "            {",
    "                title: 'LMMS',",
    "                license: 'GPL-2.0',",
    "                docsUrl: 'https://github.com/LMMS/lmms',",
    "                why: 'Music and sound design for custom loops and stingers.',",
    "                command: 'winget install --id LMMS.LMMS -e',",
    "            },",
    "        ];",
    "    }",
    "    if (mode === 'dev_studio') {",
    "        return [",
    "            {",
    "                title: 'code-server',",
    "                license: 'MIT',",
    "                docsUrl: 'https://github.com/coder/code-server',",
    "                why: 'VS Code in browser',",
    "                command: 'curl -fsSL https://code-server.dev/install.sh | sh',",
    "            },",
    "            {",
    "                title: 'Ace Editor',",
    "                license: 'BSD-3-Clause',",
    "                docsUrl: 'https://github.com/ajaxorg/ace',",
    "                why: 'Embeddable code editor',",
    "                command: 'npm i ace-builds',",
    "            },",
    "            {",
    "                title: 'Monaco Editor',",
    "                license: 'MIT',",
    "                docsUrl: 'https://github.com/microsoft/monaco-editor',",
    "                why: 'VS Code core editor engine',",
    "                command: 'npm i monaco-editor',",
    "            },",
    "        ];",
    "    }",
    "    if (mode === 'game_studio') {",
    "        return [",
    "            {",
    "                title: 'Pixel Streaming Infrastructure',",
    "                license: 'MIT',",
    "                docsUrl: 'https://github.com/EpicGamesExt/PixelStreamingInfrastructure',",
    "                why: 'Open-source Unreal stream frontend/signalling stack for embedded and remote viewport workflows.',",
    "                command: 'git clone --branch UE5.5 https://github.com/EpicGamesExt/PixelStreamingInfrastructure.git',",
    "            },",
    "            {",
    "                title: 'Unreal Remote Control API',",
    "                license: 'Unreal feature',",
    "                docsUrl: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/remote-control-api-http-reference-for-unreal-engine',",
    "                why: 'Call Blueprint-callable functions over HTTP for editor automation and AI tooling.',",
    "                command: 'curl -X GET http://127.0.0.1:30010/remote/info',",
    "            },",
    "            {",
    "                title: 'Godot CLI',",
    "                license: 'MIT',",
    "                docsUrl: 'https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html',",
    "                why: 'Headless export and CI builds',",
    "                command: 'godot --headless --path ./game --export-release \"Windows Desktop\" build/game.exe',",
    "            },",
    "            {",
    "                title: 'Phaser',",
    "                license: 'MIT',",
    "                docsUrl: 'https://docs.phaser.io/api-documentation/api-documentation',",
    "                why: 'Fast 2D web playtest runtime',",
    "                command: 'npm i phaser',",
    "            },",
    "        ];",
    "    }",
    "    if (mode === 'research_lab') {",
    "        return [",
    "            {",
    "                title: 'JupyterLab',",
    "                license: 'BSD',",
    "                docsUrl: 'https://github.com/jupyterlab/jupyterlab',",
    "                why: 'Exploration notebooks and experiments',",
    "                command: 'pip install jupyterlab',",
    "            },",
    "            {",
    "                title: 'Zotero',",
    "                license: 'AGPL-3.0',",
    "                docsUrl: 'https://github.com/zotero/zotero',",
    "                why: 'Citation and source management',",
    "                command: 'winget install --id Zotero.Zotero -e',",
    "            },",
    "            {",
    "                title: 'OpenAlex API',",
    "                license: 'Open data',",
    "                docsUrl: 'https://docs.openalex.org/',",
    "                why: 'Research metadata and paper graph',",
    "                command: 'curl \"https://api.openalex.org/works?search=agentic+workflow\"',",
    "            },",
    "        ];",
    "    }",
    "    return [];",
    "}",
    "",
    "function moduleWorkbenchRenderOssStack(modeRaw, titleRaw = 'Open-Source Power Stack') {",
    "    const mode = safeString(modeRaw);",
    "    const title = safeString(titleRaw) || 'Open-Source Power Stack';",
    "    const rows = moduleWorkbenchOssCatalog(mode);",
    "    if (!rows.length) return '';",
    "    return `",
    "        <section class=\"module-wb-oss-stack\">",
    "            <h4>${escapeHtml(title)}</h4>",
    "            <div class=\"module-wb-oss-list\">",
    "                ${rows.map((row, index) => `",
    "                    <article class=\"module-wb-oss-item\">",
    "                        <div class=\"module-wb-oss-head\">",
    "                            <strong>${escapeHtml(safeString(row.title) || 'Tool')}</strong>",
    "                            <span>${escapeHtml(safeString(row.license) || 'OSS')}</span>",
    "                        </div>",
    "                        <p>${escapeHtml(safeString(row.why) || '')}</p>",
    "                        <div class=\"module-wb-inline-actions\">",
    "                            <button type=\"button\" class=\"module-item-btn\" data-oss-mode=\"${escapeHtml(mode)}\" data-oss-copy=\"${index}\">Copy command</button>",
    "                            <a class=\"module-item-btn\" href=\"${escapeHtml(safeString(row.docsUrl) || '#')}\" target=\"_blank\" rel=\"noopener noreferrer\">Docs</a>",
    "                        </div>",
    "                    </article>",
    "                `).join('')}",
    "            </div>",
    "        </section>",
    "    `;",
    "}",
    "",
    "function moduleWorkbenchHandleOssStackClick(targetRaw) {",
    "    const target = targetRaw instanceof Element ? targetRaw.closest('[data-oss-mode][data-oss-copy]') : null;",
    "    if (!target) return false;",
    "    const mode = safeString(target.dataset.ossMode);",
    "    const index = Number(target.dataset.ossCopy);",
    "    if (!mode || !Number.isInteger(index)) return false;",
    "    const rows = moduleWorkbenchOssCatalog(mode);",
    "    const row = rows[index];",
    "    if (!row?.command) return false;",
    "    moduleWorkbenchCopyText(row.command, `${safeString(row.title) || 'Integration'} Command`);",
    "    return true;",
    "}",
    "",
    "const MODULE_WORKBENCH_PROJECT_STORE_KEY = 'thomas.workbench.projects.v1';",
    "",
    "function moduleWorkbenchProjectsRead() {",
    "    try {",
    "        const raw = window.localStorage.getItem(MODULE_WORKBENCH_PROJECT_STORE_KEY);",
    "        if (!raw) return {};",
    "        const parsed = JSON.parse(raw);",
    "        return parsed && typeof parsed === 'object' ? parsed : {};",
    "    } catch (_error) {",
    "        return {};",
    "    }",
    "}",
    "",
    "function moduleWorkbenchProjectsWrite(storeRaw) {",
    "    const store = storeRaw && typeof storeRaw === 'object' ? storeRaw : {};",
    "    try {",
    "        window.localStorage.setItem(MODULE_WORKBENCH_PROJECT_STORE_KEY, JSON.stringify(store));",
    "    } catch (_error) {}",
    "}",
    "",
    "function moduleWorkbenchProjectList(modeRaw) {",
    "    const mode = safeString(modeRaw);",
    "    if (!mode) return [];",
    "    const store = moduleWorkbenchProjectsRead();",
    "    const rows = Array.isArray(store[mode]) ? store[mode] : [];",
    "    return rows.filter((row) => row && typeof row === 'object').slice(0, 20);",
    "}",
    "",
    "function moduleWorkbenchProjectSave(modeRaw, payloadRaw, nameRaw = '') {",
    "    const mode = safeString(modeRaw);",
    "    const payload = payloadRaw && typeof payloadRaw === 'object' ? payloadRaw : {};",
    "    if (!mode) return '';",
    "    const store = moduleWorkbenchProjectsRead();",
    "    const current = Array.isArray(store[mode]) ? store[mode] : [];",
    "    const name = safeString(nameRaw) || `Project ${moduleWorkbenchTimeStamp()}`;",
    "    const id = moduleWorkbenchMakeId(`${mode}-project`);",
    "    const next = [{ id, name: name.slice(0, 72), updatedAt: Date.now(), payload }, ...current]",
    "        .slice(0, 20);",
    "    store[mode] = next;",
    "    moduleWorkbenchProjectsWrite(store);",
    "    return id;",
    "}",
    "",
    "function moduleWorkbenchProjectGet(modeRaw, idRaw) {",
    "    const mode = safeString(modeRaw);",
    "    const id = safeString(idRaw);",
    "    if (!mode || !id) return null;",
    "    return moduleWorkbenchProjectList(mode).find((row) => safeString(row.id) === id) || null;",
    "}",
    "",
    "function moduleWorkbenchProjectDelete(modeRaw, idRaw) {",
    "    const mode = safeString(modeRaw);",
    "    const id = safeString(idRaw);",
    "    if (!mode || !id) return false;",
    "    const store = moduleWorkbenchProjectsRead();",
    "    const rows = Array.isArray(store[mode]) ? store[mode] : [];",
    "    const next = rows.filter((row) => safeString(row?.id) !== id);",
    "    store[mode] = next;",
    "    moduleWorkbenchProjectsWrite(store);",
    "    return next.length !== rows.length;",
    "}",
    "",
    "function moduleWorkbenchRenderProjectControls(modeRaw, titleRaw = 'Projects') {",
    "    const mode = safeString(modeRaw);",
    "    const title = safeString(titleRaw) || 'Projects';",
    "    const rows = moduleWorkbenchProjectList(mode);",
    "    return `",
    "        <section class=\"module-wb-project-panel\">",
    "            <h4>${escapeHtml(title)}</h4>",
    "            <div class=\"module-wb-inline-form module-wb-project-form\">",
    "                <input type=\"text\" data-wb-project-name=\"${escapeHtml(mode)}\" placeholder=\"Project name\" />",
    "                <div class=\"module-wb-inline-actions\">",
    "                    <button type=\"button\" class=\"module-item-btn\" data-wb-project-action=\"save\" data-wb-project-mode=\"${escapeHtml(mode)}\">Save</button>",
    "                    <button type=\"button\" class=\"module-item-btn\" data-wb-project-action=\"load\" data-wb-project-mode=\"${escapeHtml(mode)}\">Load</button>",
    "                    <button type=\"button\" class=\"module-item-btn\" data-wb-project-action=\"delete\" data-wb-project-mode=\"${escapeHtml(mode)}\">Delete</button>",
    "                </div>",
    "                <select data-wb-project-select=\"${escapeHtml(mode)}\">",
    "                    <option value=\"\">Select project</option>",
    "                    ${rows.map((row) => `<option value=\"${escapeHtml(safeString(row.id))}\">${escapeHtml(`${safeString(row.name)} (${new Date(Number(row.updatedAt) || Date.now()).toLocaleString()})`)}</option>`).join('')}",
    "                </select>",
    "            </div>",
    "        </section>",
    "    `;",
    "}",
    "",
    "function moduleWorkbenchPathGet(objRaw, pathRaw) {",
    "    const obj = objRaw && typeof objRaw === 'object' ? objRaw : {};",
    "    const path = safeString(pathRaw);",
    "    if (!path) return obj;",
    "    const parts = path.split('.').map((item) => safeString(item)).filter(Boolean);",
    "    let cursor = obj;",
    "    for (const part of parts) {",
    "        if (!cursor || typeof cursor !== 'object') return undefined;",
    "        cursor = cursor[part];",
    "    }",
    "    return cursor;",
    "}",
    "",
    "function moduleWorkbenchPathSet(objRaw, pathRaw, value) {",
    "    const obj = objRaw && typeof objRaw === 'object' ? objRaw : {};",
    "    const path = safeString(pathRaw);",
    "    if (!path) return obj;",
    "    const parts = path.split('.').map((item) => safeString(item)).filter(Boolean);",
    "    if (!parts.length) return obj;",
    "    let cursor = obj;",
    "    for (let index = 0; index < parts.length - 1; index += 1) {",
    "        const key = parts[index];",
    "        if (!cursor[key] || typeof cursor[key] !== 'object') cursor[key] = {};",
    "        cursor = cursor[key];",
    "    }",
    "    cursor[parts[parts.length - 1]] = value;",
    "    return obj;",
    "}",
    "",
    "function moduleWorkbenchPathDelete(objRaw, pathRaw) {",
    "    const obj = objRaw && typeof objRaw === 'object' ? objRaw : {};",
    "    const path = safeString(pathRaw);",
    "    if (!path) return obj;",
    "    const parts = path.split('.').map((item) => safeString(item)).filter(Boolean);",
    "    if (!parts.length) return obj;",
    "    let cursor = obj;",
    "    for (let index = 0; index < parts.length - 1; index += 1) {",
    "        const key = parts[index];",
    "        if (!cursor[key] || typeof cursor[key] !== 'object') return obj;",
    "        cursor = cursor[key];",
    "    }",
    "    delete cursor[parts[parts.length - 1]];",
    "    return obj;",
    "}",
    "",
    "function moduleWorkbenchDeepClone(value) {",
    "    try {",
    "        return JSON.parse(JSON.stringify(value));",
    "    } catch (_error) {",
    "        return value;",
    "    }",
    "}",
    "",
    "function formatDebugPercent(valueRaw, digits = 1, fallback = '-') {",
    "    const value = Number(valueRaw);",
    "    if (!Number.isFinite(value)) return fallback;",
    "    return `${(value * 100).toFixed(Math.max(0, Number(digits) || 0))}%`;",
    "}",
    "",
    "const MODULE_WORKBENCH_OSS = {",
    "    scriptPromises: Object.create(null),",
    "    styleLoaded: Object.create(null),",
    "    threePromise: null,",
    "    liteGraphPromise: null,",
    "    gridStackPromise: null,",
    "    waveSurferPromise: null,",
    "    monacoPromise: null,",
    "    acePromise: null,",
    "    phaserPromise: null,",
    "};",
    "",
    "function moduleWorkbenchModeIsActive(modeRaw) {",
    "    const mode = safeString(modeRaw);",
    "    if (!mode) return false;",
    "    return Boolean(moduleWorkbench && safeString(moduleWorkbench.dataset.mode) === mode);",
    "}",
    "",
    "function moduleWorkbenchRefreshMode(modeRaw) {",
    "    const mode = MODULE_NAV_MODE_SET.has(modeRaw) ? modeRaw : safeString(modeRaw);",
    "    if (!mode || !moduleWorkbenchModeIsActive(mode)) return;",
    "    const state = moduleEnsureRuntime();",
    "    if (state?.workbench?.[mode]) {",
    "        state.workbench[mode].mounted = false;",
    "    }",
    "    moduleRender(mode, { touch: false });",
    "}",
    "",
    "function moduleWorkbenchLoadStyle(urlRaw) {",
    "    const url = safeString(urlRaw);",
    "    if (!url) return;",
    "    if (MODULE_WORKBENCH_OSS.styleLoaded[url]) return;",
    "    MODULE_WORKBENCH_OSS.styleLoaded[url] = true;",
    "    if (!(document?.head instanceof HTMLHeadElement)) return;",
    "    const existing = document.head.querySelector(`link[rel=\"stylesheet\"][href=\"${url}\"]`);",
    "    if (existing) return;",
    "    const link = document.createElement('link');",
    "    link.rel = 'stylesheet';",
    "    link.href = url;",
    "    document.head.appendChild(link);",
    "}",
    "",
    "function moduleWorkbenchLoadScript(urlRaw, { globalName = '', globalCheck = null } = {}) {",
    "    const url = safeString(urlRaw);",
    "    if (!url) return Promise.reject(new Error('Missing script URL.'));",
    "    if (typeof globalCheck === 'function' && globalCheck()) {",
    "        return Promise.resolve(true);",
    "    }",
    "    if (globalName && window[globalName]) {",
    "        return Promise.resolve(true);",
    "    }",
    "    if (MODULE_WORKBENCH_OSS.scriptPromises[url]) {",
    "        return MODULE_WORKBENCH_OSS.scriptPromises[url];",
    "    }",
    "    MODULE_WORKBENCH_OSS.scriptPromises[url] = new Promise((resolve, reject) => {",
    "        if (!(document?.head instanceof HTMLHeadElement)) {",
    "            reject(new Error('Document head unavailable.'));",
    "            return;",
    "        }",
    "        const script = document.createElement('script');",
    "        script.src = url;",
    "        script.async = true;",
    "        script.onload = () => {",
    "            if (typeof globalCheck === 'function' && !globalCheck()) {",
    "                reject(new Error(`Loaded ${url} but expected symbol missing.`));",
    "                return;",
    "            }",
    "            if (globalName && !window[globalName]) {",
    "                reject(new Error(`Loaded ${url} but window.${globalName} is unavailable.`));",
    "                return;",
    "            }",
    "            resolve(true);",
    "        };",
    "        script.onerror = () => reject(new Error(`Failed to load script: ${url}`));",
    "        document.head.appendChild(script);",
    "    }).catch((error) => {",
    "        delete MODULE_WORKBENCH_OSS.scriptPromises[url];",
    "        throw error;",
    "    });",
    "    return MODULE_WORKBENCH_OSS.scriptPromises[url];",
    "}",
    "",
    "async function moduleWorkbenchLoadThreeBundle() {",
    "    if (MODULE_WORKBENCH_OSS.threePromise) return MODULE_WORKBENCH_OSS.threePromise;",
    "    MODULE_WORKBENCH_OSS.threePromise = (async () => {",
    "        const THREE = await import('https://cdn.jsdelivr.net/npm/three@0.183.1/+esm');",
    "        const orbitModule = await import('https://cdn.jsdelivr.net/npm/three@0.183.1/examples/jsm/controls/OrbitControls.js/+esm');",
    "        const transformModule = await import('https://cdn.jsdelivr.net/npm/three@0.183.1/examples/jsm/controls/TransformControls.js/+esm');",
    "        const gltfModule = await import('https://cdn.jsdelivr.net/npm/three@0.183.1/examples/jsm/exporters/GLTFExporter.js/+esm');",
].join("\n");
