/* split from part-029.js */
export default [
    "            moduleTouch(mode);",
    "            moduleRender(mode, { touch: false });",
    "        });",
    "    }",
    "",
    "    state.timerId = window.setInterval(() => {",
    "        if (!MODULE_NAV_MODE_SET.has(sidebarNavMode)) return;",
    "        moduleRender(sidebarNavMode);",
    "    }, MODULE_REFRESH_INTERVAL_MS);",
    "",
    "    moduleRender('dashboard', { touch: false });",
    "}",
    "",
    "function loadStoredNavMode() {",
    "    try {",
    "        if (!window?.localStorage) return 'chat';",
    "        return normalizeNavMode(window.localStorage.getItem(UI_NAV_MODE_STORAGE_KEY));",
    "    } catch {",
    "        return 'chat';",
    "    }",
    "}",
    "",
    "function saveStoredNavMode(modeRaw) {",
    "    const mode = normalizeNavMode(modeRaw);",
    "    try {",
    "        if (!window?.localStorage) return;",
    "        window.localStorage.setItem(UI_NAV_MODE_STORAGE_KEY, mode);",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function loadStoredSidebarCollapsed() {",
    "    try {",
    "        if (!window?.localStorage) return false;",
    "        return window.localStorage.getItem(UI_SIDEBAR_COLLAPSED_STORAGE_KEY) === '1';",
    "    } catch {",
    "        return false;",
    "    }",
    "}",
    "",
    "function saveStoredSidebarCollapsed(collapsed) {",
    "    try {",
    "        if (!window?.localStorage) return;",
    "        window.localStorage.setItem(UI_SIDEBAR_COLLAPSED_STORAGE_KEY, collapsed ? '1' : '0');",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function loadStoredChatListExpanded() {",
    "    try {",
    "        if (!window?.localStorage) return true;",
    "        const raw = window.localStorage.getItem(UI_CHAT_LIST_EXPANDED_STORAGE_KEY);",
    "        if (raw === null) return true;",
    "        return raw !== '0';",
    "    } catch {",
    "        return true;",
    "    }",
    "}",
    "",
    "function saveStoredChatListExpanded(expanded) {",
    "    try {",
    "        if (!window?.localStorage) return;",
    "        window.localStorage.setItem(UI_CHAT_LIST_EXPANDED_STORAGE_KEY, expanded ? '1' : '0');",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function loadStoredActiveChatId() {",
    "    try {",
    "        if (!window?.localStorage) return '';",
    "        return safeString(window.localStorage.getItem(UI_ACTIVE_CHAT_STORAGE_KEY));",
    "    } catch {",
    "        return '';",
    "    }",
    "}",
    "",
    "function saveStoredActiveChatId(chatIdRaw) {",
    "    try {",
    "        if (!window?.localStorage) return;",
    "        const chatId = safeString(chatIdRaw);",
    "        if (chatId) {",
    "            window.localStorage.setItem(UI_ACTIVE_CHAT_STORAGE_KEY, chatId);",
    "        } else {",
    "            window.localStorage.removeItem(UI_ACTIVE_CHAT_STORAGE_KEY);",
    "        }",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function loadStoredOfficeCameraState() {",
    "    try {",
    "        if (!window?.localStorage) return null;",
    "        const raw = safeString(window.localStorage.getItem(OFFICE_CAMERA_STORAGE_KEY));",
    "        if (!raw) return null;",
    "        const parsed = JSON.parse(raw);",
    "        if (!parsed || typeof parsed !== 'object') return null;",
    "        const zoom = Number(parsed.zoom);",
    "        const panX = Number(parsed.panX);",
    "        const panY = Number(parsed.panY);",
    "        const followAgentId = safeString(parsed.followAgentId);",
    "        if (!Number.isFinite(zoom) || !Number.isFinite(panX) || !Number.isFinite(panY)) {",
    "            return null;",
    "        }",
    "        return {",
    "            zoom: officeClamp(zoom, OFFICE_ZOOM_MIN, OFFICE_ZOOM_MAX),",
    "            panX,",
    "            panY,",
    "            followAgentId,",
    "        };",
    "    } catch {",
    "        return null;",
    "    }",
    "}",
    "",
    "function saveStoredOfficeCameraState(snapshot) {",
    "    try {",
    "        if (!window?.localStorage || !snapshot || typeof snapshot !== 'object') return;",
    "        const payload = {",
    "            zoom: officeClamp(Number(snapshot.zoom) || 1, OFFICE_ZOOM_MIN, OFFICE_ZOOM_MAX),",
    "            panX: Number(snapshot.panX) || 0,",
    "            panY: Number(snapshot.panY) || 0,",
    "            followAgentId: safeString(snapshot.followAgentId || ''),",
    "        };",
    "        window.localStorage.setItem(OFFICE_CAMERA_STORAGE_KEY, JSON.stringify(payload));",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function loadStoredOfficeLayoutState() {",
    "    try {",
    "        if (!window?.localStorage) return null;",
    "        const raw = safeString(window.localStorage.getItem(OFFICE_LAYOUT_STORAGE_KEY));",
    "        if (!raw) return null;",
    "        const parsed = JSON.parse(raw);",
    "        if (!parsed || typeof parsed !== 'object') return null;",
    "        return {",
    "            dynamicRooms: Array.isArray(parsed.dynamicRooms) ? parsed.dynamicRooms : [],",
    "            dynamicRoomBySlug: parsed.dynamicRoomBySlug && typeof parsed.dynamicRoomBySlug === 'object'",
    "                ? parsed.dynamicRoomBySlug",
    "                : {},",
    "        };",
    "    } catch {",
    "        return null;",
    "    }",
    "}",
    "",
    "function saveStoredOfficeLayoutState(snapshot) {",
    "    try {",
    "        if (!window?.localStorage || !snapshot || typeof snapshot !== 'object') return;",
    "        const payload = {",
    "            dynamicRooms: Array.isArray(snapshot.dynamicRooms) ? snapshot.dynamicRooms : [],",
    "            dynamicRoomBySlug: snapshot.dynamicRoomBySlug && typeof snapshot.dynamicRoomBySlug === 'object'",
    "                ? snapshot.dynamicRoomBySlug",
    "                : {},",
    "        };",
    "        window.localStorage.setItem(OFFICE_LAYOUT_STORAGE_KEY, JSON.stringify(payload));",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function loadStoredOfficeAgentPrefs() {",
    "    try {",
    "        if (!window?.localStorage) return null;",
    "        const raw = safeString(window.localStorage.getItem(OFFICE_AGENT_PREFS_STORAGE_KEY));",
    "        if (!raw) return null;",
    "        const parsed = JSON.parse(raw);",
    "        if (!parsed || typeof parsed !== 'object') return null;",
    "        return parsed;",
    "    } catch {",
    "        return null;",
    "    }",
    "}",
    "",
    "function saveStoredOfficeAgentPrefs(snapshot) {",
    "    try {",
    "        if (!window?.localStorage || !snapshot || typeof snapshot !== 'object') return;",
    "        window.localStorage.setItem(OFFICE_AGENT_PREFS_STORAGE_KEY, JSON.stringify(snapshot));",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function loadStoredOfficeRuntimeState() {",
    "    try {",
    "        if (!window?.localStorage) return null;",
    "        const raw = safeString(window.localStorage.getItem(OFFICE_RUNTIME_STORAGE_KEY));",
    "        if (!raw) return null;",
    "        const parsed = JSON.parse(raw);",
    "        if (!parsed || typeof parsed !== 'object') return null;",
    "        if (Number(parsed.version) !== OFFICE_RUNTIME_SCHEMA_VERSION) return null;",
    "        return parsed;",
    "    } catch {",
    "        return null;",
    "    }",
    "}",
    "",
    "function saveStoredOfficeRuntimeState(snapshot) {",
    "    try {",
    "        if (!window?.localStorage || !snapshot || typeof snapshot !== 'object') return;",
    "        window.localStorage.setItem(OFFICE_RUNTIME_STORAGE_KEY, JSON.stringify(snapshot));",
    "    } catch {",
    "        // Ignore storage failures.",
    "    }",
    "}",
    "",
    "function officeRuntimeTimerRemaining(now, targetRaw) {",
    "    const target = Number(targetRaw) || 0;",
    "    if (target <= 0) return 0;",
    "    return Math.max(0, Math.round(target - now));",
    "}",
    "",
    "function officeRuntimeTimerRestore(now, remainingRaw) {",
    "    const remaining = Math.max(0, Number(remainingRaw) || 0);",
    "    if (!remaining) return 0;",
    "    return now + remaining;",
    "}",
    "",
    "function officeCollectRuntimeSnapshot(now = performance.now()) {",
    "    if (!officeState) return null;",
    "    const timerNow = Number(now) || performance.now();",
    "    return {",
    "        version: OFFICE_RUNTIME_SCHEMA_VERSION,",
    "        savedAtEpoch: Date.now(),",
    "        savedAtPerf: timerNow,",
    "        selectedAgentId: safeString(officeState.selectedAgentId),",
    "        followAgentId: safeString(officeState.followAgentId),",
    "        taskCounter: Number(officeState.taskCounter) || 0,",
    "        chatLines: Array.isArray(officeState.chatLines)",
    "            ? officeState.chatLines",
    "                .slice(-OFFICE_MAX_CHAT_LINES)",
    "                .map((line) => ({",
    "                    message: safeString(line?.message),",
    "                    tone: safeString(line?.tone) || 'system',",
    "                    at: Number(line?.at) || Date.now(),"
].join("\n");
