/* app.js lines 22001-23000 */
export default [
    "",
    "    return true;",
    "}",
    "",
    "function moduleRenderWorkbenchAutomations(container, wb) {",
    "    if (moduleRenderWorkbenchAutomationsOss(container, wb)) return;",
    "    if (!container || !wb) return;",
    "    if (!Array.isArray(wb.nodes)) wb.nodes = [];",
    "    if (!Array.isArray(wb.edges)) wb.edges = [];",
    "    if (!Array.isArray(wb.logs)) wb.logs = [];",
    "    wb.selectedId = safeString(wb.selectedId);",
    "    wb.connectingFrom = safeString(wb.connectingFrom);",
    "    wb.nextId = Math.max(1, Number(wb.nextId) || 1);",
    "    wb.runInput = safeString(wb.runInput) || '{\\n  \"subject\": \"Ops status\",\\n  \"priority\": \"high\"\\n}';",
    "    if (!wb.runReport || typeof wb.runReport !== 'object') wb.runReport = null;",
    "    wb.selectedProjectId = safeString(wb.selectedProjectId);",
    "",
    "    moduleWorkbenchHeader(container, 'Automation Flow Builder', 'Compose workflows Thomas runs end to end with live logs, approvals, and recovery visibility.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-flow';",
    "    shell.innerHTML = `",
    "        <aside class=\"module-wb-side-card\"><h4>Blocks</h4><div class=\"module-wb-palette\" data-flow-palette></div>${moduleWorkbenchRenderProjectControls('automations', 'Flow Projects')}<label class=\"module-wb-field module-wb-field-wide\">Run Input JSON<textarea rows=\"6\" data-flow-run-input>${escapeHtml(wb.runInput)}</textarea></label><div class=\"module-wb-inspector-actions\"><button type=\"button\" class=\"module-item-btn\" data-flow-action=\"run\">Test Run</button><button type=\"button\" class=\"module-item-btn\" data-flow-action=\"run_dry\">Dry Run</button><button type=\"button\" class=\"module-item-btn\" data-flow-action=\"export\">Export</button><button type=\"button\" class=\"module-item-btn\" data-flow-action=\"export_n8n\">n8n JSON</button><button type=\"button\" class=\"module-item-btn\" data-flow-action=\"export_nodered\">Node-RED JSON</button><button type=\"button\" class=\"module-item-btn\" data-flow-action=\"clear\">Reset</button></div></aside>",
    "        <section class=\"module-wb-stage-card\"><div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Nodes + Links</span><span class=\"module-wb-stage-meta\" data-flow-status></span></div><div class=\"module-wb-flow-list\" data-flow-list></div><div class=\"module-wb-log-list\" data-flow-logs></div><div class=\"module-wb-run-report\" data-flow-report></div></section>",
    "        <aside class=\"module-wb-inspector-card\" data-flow-inspector></aside>",
    "        ${moduleWorkbenchRenderOssStack('automations')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const blockDefs = [",
    "        { id: 'schedule', kind: 'trigger', label: 'Schedule Trigger' },",
    "        { id: 'email', kind: 'trigger', label: 'New Email Trigger' },",
    "        { id: 'if_else', kind: 'logic', label: 'If / Else Branch' },",
    "        { id: 'approval', kind: 'logic', label: 'Human Approval' },",
    "        { id: 'send_message', kind: 'action', label: 'Send Message' },",
    "        { id: 'run_script', kind: 'action', label: 'Run Script' },",
    "    ];",
    "    const byId = (id) => wb.nodes.find((node) => safeString(node.id) === safeString(id)) || null;",
    "    const palette = shell.querySelector('[data-flow-palette]');",
    "    const list = shell.querySelector('[data-flow-list]');",
    "    const logs = shell.querySelector('[data-flow-logs]');",
    "    const report = shell.querySelector('[data-flow-report]');",
    "    const inspector = shell.querySelector('[data-flow-inspector]');",
    "    const status = shell.querySelector('[data-flow-status]');",
    "    const runInputEl = shell.querySelector('[data-flow-run-input]');",
    "",
    "    const renderPalette = () => { palette.innerHTML = blockDefs.map((block) => `<button type=\"button\" class=\"module-wb-palette-btn\" data-flow-node-type=\"${block.id}\"><strong>${block.label}</strong><span>${block.kind}</span></button>`).join(''); };",
    "    const renderList = () => {",
    "        list.innerHTML = wb.nodes.length ? wb.nodes.map((node) => `<article class=\"module-wb-list-item${safeString(node.id) === safeString(wb.selectedId) ? ' selected' : ''}\" data-flow-node-id=\"${escapeHtml(safeString(node.id))}\"><strong>${escapeHtml(safeString(node.label))}</strong><span>${escapeHtml(`${safeString(node.kind)} | ${safeString(node.type)}`)}</span><div class=\"module-wb-inline-actions\"><button type=\"button\" class=\"module-item-btn\" data-flow-node-action=\"from\" data-flow-node-id=\"${escapeHtml(safeString(node.id))}\">From</button><button type=\"button\" class=\"module-item-btn\" data-flow-node-action=\"to\" data-flow-node-id=\"${escapeHtml(safeString(node.id))}\">To</button></div></article>`).join('') : '<div class=\"module-wb-ghost\">Add your first workflow block.</div>';",
    "    };",
    "    const renderLogs = () => { logs.innerHTML = wb.logs.length ? wb.logs.slice(0, 16).map((entry) => `<article class=\"module-wb-log-item ${moduleToneClass(entry.tone) || 'ok'}\"><span>${escapeHtml(safeString(entry.time))}</span><p>${escapeHtml(safeString(entry.message))}</p></article>`).join('') : '<div class=\"module-wb-ghost\">No flow logs yet.</div>'; };",
    "    const renderInspector = () => {",
    "        const node = byId(wb.selectedId);",
    "        if (!node) {",
    "            inspector.innerHTML = `<h4>Inspector</h4><p class=\"module-wb-mini-note\">Select a node to edit it.</p><div class=\"module-wb-metrics\"><div><span>Nodes</span><strong>${wb.nodes.length}</strong></div><div><span>Links</span><strong>${wb.edges.length}</strong></div><div><span>Connect</span><strong>${wb.connectingFrom ? escapeHtml(wb.connectingFrom) : 'idle'}</strong></div></div>`;",
    "            return;",
    "        }",
    "        inspector.innerHTML = `<h4>${escapeHtml(safeString(node.label))}</h4><div class=\"module-wb-field-grid\"><label class=\"module-wb-field\">Label<input type=\"text\" data-flow-prop=\"label\" value=\"${escapeHtml(safeString(node.label))}\" /></label><label class=\"module-wb-field\">Type<select data-flow-prop=\"type\">${blockDefs.map((block) => `<option value=\"${block.id}\"${safeString(node.type) === block.id ? ' selected' : ''}>${block.label}</option>`).join('')}</select></label><label class=\"module-wb-field module-wb-field-check\"><input type=\"checkbox\" data-flow-prop=\"approval\" ${node.approval ? 'checked' : ''} />Require approval</label><label class=\"module-wb-field module-wb-field-wide\">Notes<textarea rows=\"4\" data-flow-prop=\"notes\">${escapeHtml(safeString(node.notes))}</textarea></label></div><div class=\"module-wb-inspector-actions\"><button type=\"button\" class=\"module-item-btn\" data-flow-node-action=\"duplicate\">Duplicate</button><button type=\"button\" class=\"module-item-btn\" data-flow-node-action=\"delete\">Delete</button></div>`;",
    "    };",
    "    const renderStatus = () => { status.textContent = `${wb.nodes.length} nodes | ${wb.edges.length} links${wb.connectingFrom ? ` | from ${wb.connectingFrom}` : ''}`; };",
    "    const renderAll = () => { renderList(); renderLogs(); renderReport(); renderInspector(); renderStatus(); renderProjectSelect(); };",
    "",
    "    renderPalette();",
    "    renderAll();",
    "",
    "    const toGraphData = () => {",
    "        const nodeId = (idRaw, fallback) => {",
    "            const match = safeString(idRaw).match(/\\d+/);",
    "            return Number(match?.[0]) || fallback;",
    "        };",
    "        const nodes = wb.nodes.map((node, index) => ({",
    "            id: nodeId(node.id, index + 1),",
    "            title: safeString(node.label) || `Flow ${index + 1}`,",
    "            pos: [120 + (index * 34), 120 + (index * 22)],",
    "            properties: {",
    "                kind: safeString(node.kind) || 'action',",
    "                blockType: safeString(node.type) || 'custom',",
    "                notes: safeString(node.notes),",
    "                approval: Boolean(node.approval),",
    "            },",
    "        }));",
    "        const links = {};",
    "        wb.edges.forEach((edge, index) => {",
    "            const from = nodeId(edge.from, index + 1);",
    "            const to = nodeId(edge.to, index + 2);",
    "            links[index + 1] = [index + 1, from, 0, to, 0, 'flow'];",
    "        });",
    "        return { nodes, links };",
    "    };",
    "    const parseRunInput = () => {",
    "        const raw = safeString(runInputEl instanceof HTMLTextAreaElement ? runInputEl.value : wb.runInput);",
    "        wb.runInput = raw;",
    "        if (!raw.trim()) return {};",
    "        try {",
    "            const parsed = JSON.parse(raw);",
    "            return parsed && typeof parsed === 'object' ? parsed : { value: parsed };",
    "        } catch (_error) {",
    "            return { _raw: raw };",
    "        }",
    "    };",
    "    const renderReport = () => {",
    "        const run = wb.runReport && typeof wb.runReport === 'object' ? wb.runReport : null;",
    "        if (!report) return;",
    "        if (!run) {",
    "            report.innerHTML = '<div class=\"module-wb-ghost\">Run report appears here after Test Run.</div>';",
    "            return;",
    "        }",
    "        report.innerHTML = `",
    "            <div class=\"module-wb-metrics\"><div><span>Nodes</span><strong>${Number(run.nodeCount) || 0}</strong></div><div><span>Edges</span><strong>${Number(run.edgeCount) || 0}</strong></div><div><span>Outputs</span><strong>${Array.isArray(run.outputs) ? run.outputs.length : 0}</strong></div></div>",
    "            <div class=\"module-wb-log-list\">${(Array.isArray(run.steps) ? run.steps : []).slice(0, 20).map((step) => `<article class=\"module-wb-log-item ${step.pendingApproval ? 'warn' : (step.pass ? 'ok' : 'error')}\"><span>${escapeHtml(safeString(step.title))}</span><p>${escapeHtml(safeString(step.note))}</p></article>`).join('')}</div>",
    "        `;",
    "    };",
    "    const renderProjectSelect = () => {",
    "        const select = shell.querySelector('select[data-wb-project-select=\"automations\"]');",
    "        if (!(select instanceof HTMLSelectElement)) return;",
    "        const rows = moduleWorkbenchProjectList('automations');",
    "        const current = safeString(wb.selectedProjectId);",
    "        select.innerHTML = `<option value=\"\">Select project</option>${rows.map((row) => `<option value=\"${escapeHtml(safeString(row.id))}\">${escapeHtml(`${safeString(row.name)} (${new Date(Number(row.updatedAt) || Date.now()).toLocaleString()})`)}</option>`).join('')}`;",
    "        select.value = rows.some((row) => safeString(row.id) === current) ? current : '';",
    "    };",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const projectActionEl = event.target instanceof Element",
    "            ? event.target.closest('[data-wb-project-action][data-wb-project-mode=\"automations\"]')",
    "            : null;",
    "        if (projectActionEl) {",
    "            const action = safeString(projectActionEl.dataset.wbProjectAction).toLowerCase();",
    "            const select = shell.querySelector('select[data-wb-project-select=\"automations\"]');",
    "            const input = shell.querySelector('input[data-wb-project-name=\"automations\"]');",
    "            const selectedId = safeString(select instanceof HTMLSelectElement ? select.value : wb.selectedProjectId);",
    "            if (action === 'save') {",
    "                wb.selectedProjectId = moduleWorkbenchProjectSave('automations', {",
    "                    nodes: wb.nodes,",
    "                    edges: wb.edges,",
    "                    runInput: wb.runInput,",
    "                }, safeString(input instanceof HTMLInputElement ? input.value : ''));",
    "                if (input instanceof HTMLInputElement) input.value = '';",
    "                renderAll();",
    "                return;",
    "            }",
    "            if (action === 'load') {",
    "                if (!selectedId) return;",
    "                const project = moduleWorkbenchProjectGet('automations', selectedId);",
    "                if (!project?.payload) return;",
    "                wb.nodes = Array.isArray(project.payload.nodes) ? project.payload.nodes : [];",
    "                wb.edges = Array.isArray(project.payload.edges) ? project.payload.edges : [];",
    "                wb.runInput = safeString(project.payload.runInput) || wb.runInput;",
    "                if (runInputEl instanceof HTMLTextAreaElement) runInputEl.value = wb.runInput;",
    "                wb.selectedProjectId = selectedId;",
    "                renderAll();",
    "                return;",
    "            }",
    "            if (action === 'delete') {",
    "                if (!selectedId) return;",
    "                moduleWorkbenchProjectDelete('automations', selectedId);",
    "                wb.selectedProjectId = '';",
    "                renderAll();",
    "                return;",
    "            }",
    "        }",
    "        const target = event.target instanceof Element ? event.target.closest('[data-flow-node-type], [data-flow-action], [data-flow-node-id], [data-flow-node-action]') : null;",
    "        if (!target) return;",
    "        const type = safeString(target.dataset.flowNodeType);",
    "        const action = safeString(target.dataset.flowAction).toLowerCase();",
    "        const nodeAction = safeString(target.dataset.flowNodeAction).toLowerCase();",
    "        const nodeId = safeString(target.dataset.flowNodeId);",
    "",
    "        if (type) {",
    "            const def = blockDefs.find((item) => item.id === type) || blockDefs[0];",
    "            const id = `flow-${wb.nextId++}`;",
    "            wb.nodes.push({ id, type: def.id, kind: def.kind, label: def.label, approval: false, notes: '' });",
    "            wb.selectedId = id;",
    "            moduleWorkbenchPushLog(wb.logs, `Added ${def.label}.`, 'ok', 80, 'flow-log');",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (action) {",
    "            if (action === 'run') {",
    "                const run = moduleAutomationRunGraphData(toGraphData(), parseRunInput());",
    "                wb.runReport = run;",
    "                moduleWorkbenchPushLog(wb.logs, `Run completed: ${run.steps.length} step(s), ${run.outputs.length} output(s).`, 'ok', 80, 'flow-log');",
    "            } else if (action === 'run_dry') {",
    "                const run = moduleAutomationRunGraphData(toGraphData(), parseRunInput());",
    "                wb.runReport = {",
    "                    ...run,",
    "                    outputs: [],",
    "                    steps: run.steps.map((step) => ({ ...step, note: `${safeString(step.note)} (dry run)` })),",
    "                };",
    "                moduleWorkbenchPushLog(wb.logs, `Dry run completed: ${run.steps.length} step(s).`, 'warn', 80, 'flow-log');",
    "            } else if (action === 'clear') {",
    "                wb.nodes = [];",
    "                wb.edges = [];",
    "                wb.logs = [];",
    "                wb.selectedId = '';",
    "                wb.connectingFrom = '';",
    "                wb.runReport = null;",
    "            } else if (action === 'export') {",
    "                moduleWorkbenchCopyJson({ nodes: wb.nodes, edges: wb.edges }, 'Automation Flow JSON');",
    "            } else if (action === 'export_n8n') {",
    "                moduleWorkbenchCopyJson(moduleWorkbenchFlowToN8n(toGraphData()), 'n8n Workflow JSON');",
    "            } else if (action === 'export_nodered') {",
    "                moduleWorkbenchCopyJson(moduleWorkbenchFlowToNodeRed(toGraphData()), 'Node-RED Flow JSON');",
    "            }",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (nodeId) wb.selectedId = nodeId;",
    "        if (nodeAction === 'from') wb.connectingFrom = nodeId;",
    "        if (nodeAction === 'to' && wb.connectingFrom && nodeId && wb.connectingFrom !== nodeId) {",
    "            const exists = wb.edges.some((edge) => safeString(edge.from) === wb.connectingFrom && safeString(edge.to) === nodeId);",
    "            if (!exists) wb.edges.push({ id: moduleWorkbenchMakeId('edge'), from: wb.connectingFrom, to: nodeId });",
    "            wb.connectingFrom = '';",
    "        }",
    "        if (nodeAction === 'duplicate') {",
    "            const node = byId(wb.selectedId);",
    "            if (node) {",
    "                const copy = { ...node, id: `flow-${wb.nextId++}`, label: `${node.label} Copy` };",
    "                wb.nodes.push(copy);",
    "                wb.selectedId = copy.id;",
    "            }",
    "        }",
    "        if (nodeAction === 'delete') {",
    "            wb.nodes = wb.nodes.filter((node) => safeString(node.id) !== safeString(wb.selectedId));",
    "            wb.edges = wb.edges.filter((edge) => safeString(edge.from) !== safeString(wb.selectedId) && safeString(edge.to) !== safeString(wb.selectedId));",
    "            wb.selectedId = '';",
    "            wb.connectingFrom = '';",
    "        }",
    "        renderAll();",
    "    });",
    "",
    "    if (inspector) {",
    "        inspector.addEventListener('input', (event) => {",
    "            const target = event.target;",
    "            if (!(target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement)) return;",
    "            const node = byId(wb.selectedId);",
    "            if (!node) return;",
    "            const prop = safeString(target.dataset.flowProp);",
    "            if (!prop) return;",
    "            if (prop === 'label' || prop === 'notes') node[prop] = safeString(target.value).slice(0, 2000);",
    "            if (prop === 'type') {",
    "                node.type = safeString(target.value);",
    "                const def = blockDefs.find((item) => item.id === node.type);",
    "                if (def) node.kind = def.kind;",
    "            }",
    "            if (prop === 'approval' && target instanceof HTMLInputElement) node.approval = target.checked;",
    "            renderAll();",
    "        });",
    "    }",
    "    if (runInputEl instanceof HTMLTextAreaElement) {",
    "        runInputEl.addEventListener('input', () => {",
    "            wb.runInput = safeString(runInputEl.value);",
    "        });",
    "    }",
    "    const projectSelect = shell.querySelector('select[data-wb-project-select=\"automations\"]');",
    "    if (projectSelect instanceof HTMLSelectElement) {",
    "        projectSelect.addEventListener('change', () => {",
    "            wb.selectedProjectId = safeString(projectSelect.value);",
    "        });",
    "    }",
    "}",
    "",
    "function moduleWorkbenchAppSchemaToAppsmith(wb) {",
    "    const components = Array.isArray(wb?.components) ? wb.components : [];",
    "    const widgets = components.map((component, index) => ({",
    "        widgetName: safeString(component.label) || `Widget${index + 1}`,",
    "        type: safeString(component.type).toUpperCase() || 'CONTAINER_WIDGET',",
    "        topRow: (Number(component.y) || 0) * 10,",
    "        bottomRow: ((Number(component.y) || 0) + (Number(component.h) || 1)) * 10,",
    "        leftColumn: (Number(component.x) || 0) * 8,",
    "        rightColumn: ((Number(component.x) || 0) + (Number(component.w) || 1)) * 8,",
    "        dynamicBindingPathList: safeString(component.binding) ? [{ key: 'defaultValue' }] : [],",
    "    }));",
    "    return {",
    "        pageName: 'ThomasApp',",
    "        layout: safeString(wb?.device) === 'mobile' ? 'MOBILE' : 'DESKTOP',",
    "        dsl: {",
    "            widgetName: 'MainContainer',",
    "            type: 'CANVAS_WIDGET',",
    "            children: widgets,",
    "        },",
    "    };",
    "}",
    "",
    "function moduleWorkbenchAppSchemaToBudibase(wb) {",
    "    const components = Array.isArray(wb?.components) ? wb.components : [];",
    "    return {",
    "        app: {",
    "            name: 'Thomas Internal Tool',",
    "            device: safeString(wb?.device) === 'mobile' ? 'mobile' : 'desktop',",
    "            screens: [",
    "                {",
    "                    name: 'Main',",
    "                    components: components.map((component, index) => ({",
    "                        id: safeString(component.id) || `c${index + 1}`,",
    "                        type: safeString(component.type) || 'table',",
    "                        label: safeString(component.label) || `Component ${index + 1}`,",
    "                        binding: safeString(component.binding),",
    "                        requiredRole: Boolean(component.required),",
    "                        layout: {",
    "                            x: Number(component.x) || 0,",
    "                            y: Number(component.y) || 0,",
    "                            w: Number(component.w) || 4,",
    "                            h: Number(component.h) || 3,",
    "                        },",
    "                    })),",
    "                },",
    "            ],",
    "        },",
    "    };",
    "}",
    "",
    "function moduleWorkbenchAppPreviewWidget(componentRaw) {",
    "    const component = componentRaw && typeof componentRaw === 'object' ? componentRaw : {};",
    "    const type = safeString(component.type) || 'table';",
    "    const label = safeString(component.label) || 'Widget';",
    "    const binding = safeString(component.binding) || '';",
    "    if (type === 'form') {",
    "        return `<form class=\"wb-preview-form\"><label>Name<input placeholder=\"Type...\" /></label><label>Email<input type=\"email\" placeholder=\"you@team.com\" /></label><button type=\"button\">${escapeHtml(label)}</button><small>${escapeHtml(binding || 'form.input')}</small></form>`;",
    "    }",
    "    if (type === 'chart') {",
    "        return `<div class=\"wb-preview-chart\"><div style=\"height:58%\"></div><div style=\"height:34%\"></div><div style=\"height:72%\"></div><div style=\"height:46%\"></div><small>${escapeHtml(binding || 'metrics.series')}</small></div>`;",
    "    }",
    "    if (type === 'button') {",
    "        return `<div class=\"wb-preview-button-wrap\"><button type=\"button\">${escapeHtml(label)}</button><small>${escapeHtml(binding || 'action.trigger')}</small></div>`;",
    "    }",
    "    if (type === 'modal') {",
    "        return `<div class=\"wb-preview-modal\"><header>${escapeHtml(label)}</header><p>Modal body content with approval context and action buttons.</p><footer><button type=\"button\">Cancel</button><button type=\"button\">Confirm</button></footer></div>`;",
    "    }",
    "    if (type === 'tabs') {",
    "        return `<div class=\"wb-preview-tabs\"><nav><button type=\"button\" class=\"active\">Overview</button><button type=\"button\">Details</button><button type=\"button\">History</button></nav><section>Tab content for ${escapeHtml(label)}</section></div>`;",
    "    }",
    "    return `<div class=\"wb-preview-table\"><header>${escapeHtml(label)}</header><table><thead><tr><th>ID</th><th>Name</th><th>Status</th></tr></thead><tbody><tr><td>1</td><td>Alpha</td><td>Active</td></tr><tr><td>2</td><td>Beta</td><td>Pending</td></tr></tbody></table><small>${escapeHtml(binding || 'data.table')}</small></div>`;",
    "}",
    "",
    "function moduleWorkbenchAppRuntimeHtml(wb) {",
    "    const components = Array.isArray(wb?.components) ? wb.components : [];",
    "    const sorted = components",
    "        .slice()",
    "        .sort((a, b) => (Number(a?.y) - Number(b?.y)) || (Number(a?.x) - Number(b?.x)));",
    "    const columns = safeString(wb?.device) === 'mobile' ? 4 : 12;",
    "    const blocks = sorted.map((component) => {",
    "        const span = moduleWorkbenchClamp(Number(component?.w) || 3, 1, columns);",
    "        const rowSpan = moduleWorkbenchClamp(Number(component?.h) || 2, 1, 8);",
    "        return `",
    "            <article class=\"wb-preview-card\" style=\"grid-column: span ${span}; grid-row: span ${rowSpan};\">",
    "                <header>",
    "                    <strong>${escapeHtml(safeString(component?.label) || 'Widget')}</strong>",
    "                    <span>${escapeHtml(safeString(component?.type) || 'table')}</span>",
    "                </header>",
    "                ${moduleWorkbenchAppPreviewWidget(component)}",
    "            </article>",
    "        `;",
    "    }).join('');",
    "    return `",
    "<!doctype html>",
    "<html lang=\"en\">",
    "<head>",
    "<meta charset=\"utf-8\" />",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
    "<title>Thomas App Preview</title>",
    "<style>",
    "* { box-sizing: border-box; }",
    "body { margin: 0; background: #0b1726; color: #eaf4ff; font: 13px/1.4 \"Segoe UI\", system-ui, sans-serif; }",
    ".wb-shell { padding: 14px; display: grid; gap: 10px; }",
    ".wb-shell h1 { margin: 0; font-size: 16px; font-weight: 700; }",
    ".wb-grid { display: grid; grid-template-columns: repeat(${columns}, minmax(0, 1fr)); gap: 8px; }",
    ".wb-preview-card { border: 1px solid rgba(130, 178, 235, 0.35); border-radius: 10px; background: linear-gradient(180deg, rgba(18, 37, 59, 0.95), rgba(11, 22, 37, 0.95)); padding: 8px; display: grid; gap: 8px; min-height: 90px; }",
    ".wb-preview-card > header { display: flex; justify-content: space-between; align-items: center; gap: 6px; }",
    ".wb-preview-card > header strong { font-size: 12px; }",
    ".wb-preview-card > header span { font-size: 10px; text-transform: uppercase; letter-spacing: 0.04em; color: #9eb7d4; }",
    ".wb-preview-table table { width: 100%; border-collapse: collapse; font-size: 11px; }",
    ".wb-preview-table th, .wb-preview-table td { border: 1px solid rgba(130, 178, 235, 0.24); padding: 4px 6px; text-align: left; }",
    ".wb-preview-form { display: grid; gap: 6px; }",
    ".wb-preview-form label { display: grid; gap: 4px; font-size: 11px; color: #b9cde7; }",
    ".wb-preview-form input { border: 1px solid rgba(130, 178, 235, 0.3); border-radius: 7px; background: rgba(6, 14, 22, 0.8); color: #f1f7ff; padding: 6px 8px; }",
    ".wb-preview-form button, .wb-preview-button-wrap button, .wb-preview-modal button, .wb-preview-tabs button { border: 1px solid rgba(130, 178, 235, 0.36); border-radius: 8px; background: rgba(80, 141, 212, 0.24); color: #eff7ff; padding: 6px 8px; cursor: pointer; }",
    ".wb-preview-chart { min-height: 96px; display: flex; align-items: end; gap: 6px; }",
    ".wb-preview-chart > div { flex: 1; border-radius: 6px 6px 3px 3px; background: linear-gradient(180deg, #8fcbff, #3d7dcc); }",
    ".wb-preview-modal { display: grid; gap: 8px; }",
    ".wb-preview-modal header { font-weight: 700; }",
    ".wb-preview-modal footer { display: flex; gap: 6px; }",
    ".wb-preview-tabs { display: grid; gap: 8px; }",
    ".wb-preview-tabs nav { display: flex; gap: 6px; }",
    ".wb-preview-tabs nav button.active { background: rgba(116, 201, 169, 0.25); border-color: rgba(116, 201, 169, 0.55); }",
    "small { color: #9ab5d4; font-size: 10px; }",
    "</style>",
    "</head>",
    "<body>",
    "<main class=\"wb-shell\">",
    "    <h1>Thomas Runtime Preview</h1>",
    "    <section class=\"wb-grid\">",
    "        ${blocks || '<article class=\"wb-preview-card\"><p>No components in this app yet.</p></article>'}",
    "    </section>",
    "</main>",
    "</body>",
    "</html>",
    "    `.trim();",
    "}",
    "",
    "function moduleRenderWorkbenchAppBuilderOss(container, wb) {",
    "    if (!container || !wb) return false;",
    "    if (wb.ossError) return false;",
    "    if (!wb.ossReady || !window.GridStack) {",
    "        moduleWorkbenchRenderEngineLoading(",
    "            container,",
    "            'App Builder Layout Engine',",
    "            'GridStack drag/resize UI builder with component schema export.',",
    "            'Loading GridStack...',",
    "            'Fallback list editor will open if engine loading fails.',",
    "        );",
    "        if (!wb.ossLoading) {",
    "            wb.ossLoading = true;",
    "            void moduleWorkbenchLoadGridStack().then(() => {",
    "                wb.ossReady = true;",
    "                wb.ossLoading = false;",
    "                wb.ossError = '';",
    "                moduleWorkbenchRefreshMode('app_builder');",
    "            }).catch((error) => {",
    "                wb.ossLoading = false;",
    "                wb.ossReady = false;",
    "                wb.ossError = safeString(error?.message) || 'Failed to load GridStack.';",
    "                notifyUser('GridStack failed to load, using fallback builder list.', { tone: 'warn', durationMs: 2300, debugKind: 'app-builder' });",
    "                moduleWorkbenchRefreshMode('app_builder');",
    "            });",
    "        }",
    "        return true;",
    "    }",
    "",
    "    if (!Array.isArray(wb.components)) wb.components = [];",
    "    wb.device = safeString(wb.device) === 'mobile' ? 'mobile' : 'desktop';",
    "    wb.selectedId = safeString(wb.selectedId);",
    "    wb.nextId = Math.max(1, Number(wb.nextId) || 1);",
    "    wb.selectedProjectId = safeString(wb.selectedProjectId);",
    "    wb.previewHtml = safeString(wb.previewHtml);",
    "",
    "    const defs = [",
    "        { id: 'table', label: 'Table', w: 4, h: 3 },",
    "        { id: 'form', label: 'Form', w: 4, h: 4 },",
    "        { id: 'chart', label: 'Chart', w: 5, h: 4 },",
    "        { id: 'button', label: 'Button', w: 3, h: 2 },",
    "        { id: 'modal', label: 'Modal', w: 6, h: 5 },",
    "        { id: 'tabs', label: 'Tabs', w: 5, h: 3 },",
    "    ];",
    "",
    "    moduleWorkbenchHeader(container, 'App Builder Layout Engine', 'Describe intent and let Thomas generate/edit app layouts while you validate structure and publish readiness.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-app-oss';",
    "    shell.innerHTML = `",
    "        <aside class=\"module-wb-side-card\">",
    "            <h4>Components</h4>",
    "            <div class=\"module-wb-palette\" data-app-palette></div>",
    "            ${moduleWorkbenchRenderProjectControls('app_builder', 'App Projects')}",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"preview\">Preview</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"publish\">Publish</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"export\">Export</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"export_html\">Export HTML</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"open_preview\">Open Preview</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"export_appsmith\">Appsmith JSON</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"export_budibase\">Budibase JSON</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"reset\">Reset</button>",
    "            </div>",
    "        </aside>",
    "        <section class=\"module-wb-stage-card\">",
    "            <div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Layout Canvas</span><span class=\"module-wb-stage-meta\" data-app-status></span></div>",
    "            <div class=\"module-wb-device-switch\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-device=\"desktop\">Desktop</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-device=\"mobile\">Mobile</button>",
    "            </div>",
    "            <div class=\"module-wb-gridstack-shell${wb.device === 'mobile' ? ' mobile-mode' : ''}\">",
    "                <div class=\"grid-stack module-wb-gridstack\" data-app-grid></div>",
    "            </div>",
    "            <div class=\"module-wb-preview-frame-wrap\">",
    "                <div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Runtime Preview</span><span class=\"module-wb-stage-meta\">live</span></div>",
    "                <iframe class=\"module-wb-preview-frame\" data-app-preview sandbox=\"allow-scripts\"></iframe>",
    "            </div>",
    "        </section>",
    "        <aside class=\"module-wb-inspector-card\" data-app-inspector></aside>",
    "        ${moduleWorkbenchRenderOssStack('app_builder')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const palette = shell.querySelector('[data-app-palette]');",
    "    const gridEl = shell.querySelector('[data-app-grid]');",
    "    const previewFrame = shell.querySelector('[data-app-preview]');",
    "    const status = shell.querySelector('[data-app-status]');",
    "    const inspector = shell.querySelector('[data-app-inspector]');",
    "    if (!(palette instanceof HTMLElement) || !(gridEl instanceof HTMLElement) || !(previewFrame instanceof HTMLIFrameElement) || !(status instanceof HTMLElement) || !(inspector instanceof HTMLElement)) {",
    "        return false;",
    "    }",
    "",
    "    if (wb.ossGrid?.destroy) {",
    "        try {",
    "            wb.ossGrid.destroy(false);",
    "        } catch (_error) {}",
    "        wb.ossGrid = null;",
    "    }",
    "",
    "    const byId = (idRaw) => wb.components.find((row) => safeString(row?.id) === safeString(idRaw)) || null;",
    "    const findWidgetById = (idRaw) => {",
    "        const id = safeString(idRaw);",
    "        return Array.from(gridEl.querySelectorAll('.grid-stack-item')).find((element) => safeString(element.getAttribute('gs-id')) === id) || null;",
    "    };",
    "    const safeWidget = (raw, index = 0) => ({",
    "        id: safeString(raw?.id) || `ui-${wb.nextId + index}`,",
    "        type: safeString(raw?.type) || 'table',",
    "        label: safeString(raw?.label) || 'Widget',",
    "        binding: safeString(raw?.binding),",
    "        required: Boolean(raw?.required),",
    "        x: moduleWorkbenchClamp(Number(raw?.x) || 0, 0, 120),",
    "        y: moduleWorkbenchClamp(Number(raw?.y) || 0, 0, 200),",
    "        w: moduleWorkbenchClamp(Number(raw?.w) || 4, 1, 12),",
    "        h: moduleWorkbenchClamp(Number(raw?.h) || 3, 1, 12),",
    "    });",
    "    wb.components = wb.components.map((component, index) => safeWidget(component, index));",
    "    if (!wb.components.length) {",
    "        wb.components.push({",
    "            id: `ui-${wb.nextId++}`,",
    "            type: 'table',",
    "            label: 'Primary Table',",
    "            binding: 'data.table',",
    "            required: false,",
    "            x: 0,",
    "            y: 0,",
    "            w: 5,",
    "            h: 3,",
    "        });",
    "    }",
    "",
    "    const widgetMarkup = (component) => `",
    "        <div class=\"module-wb-app-widget\" data-app-widget-id=\"${escapeHtml(safeString(component.id))}\">",
    "            <strong>${escapeHtml(safeString(component.label))}</strong>",
    "            <span>${escapeHtml(safeString(component.type))}</span>",
    "            <small>${escapeHtml(safeString(component.binding) || 'unbound')}</small>",
    "        </div>",
    "    `;",
    "",
    "    const grid = window.GridStack.init({",
    "        float: true,",
    "        cellHeight: 84,",
    "        margin: 8,",
    "        disableOneColumnMode: false,",
    "    }, gridEl);",
    "    wb.ossGrid = grid;",
    "",
    "    const syncSelection = () => {",
    "        Array.from(gridEl.querySelectorAll('.grid-stack-item')).forEach((item) => {",
    "            const id = safeString(item.getAttribute('gs-id'));",
    "            item.classList.toggle('selected', id === wb.selectedId);",
    "        });",
    "    };",
    "    const refreshWidgetContent = (component) => {",
    "        const item = findWidgetById(component.id);",
    "        if (!item) return;",
    "        const content = item.querySelector('.module-wb-app-widget');",
    "        if (content) {",
    "            content.innerHTML = `<strong>${escapeHtml(safeString(component.label))}</strong><span>${escapeHtml(safeString(component.type))}</span><small>${escapeHtml(safeString(component.binding) || 'unbound')}</small>`;",
    "        }",
    "    };",
    "    const renderInspector = () => {",
    "        const component = byId(wb.selectedId);",
    "        if (!component) {",
    "            inspector.innerHTML = `<h4>Inspector</h4><p class=\"module-wb-mini-note\">Select a widget to edit its bindings and dimensions.</p><div class=\"module-wb-metrics\"><div><span>Widgets</span><strong>${wb.components.length}</strong></div><div><span>Device</span><strong>${escapeHtml(wb.device)}</strong></div><div><span>Roles</span><strong>${wb.components.filter((row) => row.required).length}</strong></div></div>`;",
    "            syncSelection();",
    "            return;",
    "        }",
    "        inspector.innerHTML = `",
    "            <h4>${escapeHtml(safeString(component.label))}</h4>",
    "            <div class=\"module-wb-field-grid\">",
    "                <label class=\"module-wb-field\">Label<input type=\"text\" data-app-prop=\"label\" value=\"${escapeHtml(safeString(component.label))}\" /></label>",
    "                <label class=\"module-wb-field\">Type<select data-app-prop=\"type\">${defs.map((entry) => `<option value=\"${entry.id}\"${component.type === entry.id ? ' selected' : ''}>${entry.label}</option>`).join('')}</select></label>",
    "                <label class=\"module-wb-field\">X<input type=\"number\" data-app-prop=\"x\" min=\"0\" value=\"${component.x}\" /></label>",
    "                <label class=\"module-wb-field\">Y<input type=\"number\" data-app-prop=\"y\" min=\"0\" value=\"${component.y}\" /></label>",
    "                <label class=\"module-wb-field\">W<input type=\"number\" data-app-prop=\"w\" min=\"1\" max=\"12\" value=\"${component.w}\" /></label>",
    "                <label class=\"module-wb-field\">H<input type=\"number\" data-app-prop=\"h\" min=\"1\" max=\"12\" value=\"${component.h}\" /></label>",
    "                <label class=\"module-wb-field module-wb-field-wide\">Binding<input type=\"text\" data-app-prop=\"binding\" value=\"${escapeHtml(safeString(component.binding))}\" placeholder=\"crm.customers\" /></label>",
    "                <label class=\"module-wb-field module-wb-field-check\"><input type=\"checkbox\" data-app-prop=\"required\" ${component.required ? 'checked' : ''} />Require role gate</label>",
    "            </div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"duplicate\">Duplicate</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-app-action=\"delete\">Delete</button>",
    "            </div>",
    "        `;",
    "        syncSelection();",
    "    };",
    "    const renderStatus = () => {",
    "        status.textContent = `${wb.components.length} widget(s) | ${wb.device.toUpperCase()} mode`;",
    "        shell.querySelectorAll('[data-app-device]').forEach((button) => button.classList.toggle('active', safeString(button.dataset.appDevice) === wb.device));",
    "    };",
    "    const renderProjectSelect = () => {",
    "        const select = shell.querySelector('select[data-wb-project-select=\"app_builder\"]');",
    "        if (!(select instanceof HTMLSelectElement)) return;",
    "        const rows = moduleWorkbenchProjectList('app_builder');",
    "        const current = safeString(wb.selectedProjectId);",
    "        select.innerHTML = `<option value=\"\">Select project</option>${rows.map((row) => `<option value=\"${escapeHtml(safeString(row.id))}\">${escapeHtml(`${safeString(row.name)} (${new Date(Number(row.updatedAt) || Date.now()).toLocaleString()})`)}</option>`).join('')}`;",
    "        select.value = rows.some((row) => safeString(row.id) === current) ? current : '';",
    "    };",
    "    const renderPreview = () => {",
    "        wb.previewHtml = moduleWorkbenchAppRuntimeHtml(wb);",
    "        previewFrame.srcdoc = wb.previewHtml;",
    "    };",
    "    const syncFromGridItems = (itemsRaw) => {",
    "        const items = Array.isArray(itemsRaw) ? itemsRaw : [];",
    "        items.forEach((item) => {",
    "            const id = safeString(item?.id || item?.el?.getAttribute?.('gs-id'));",
    "            const component = byId(id);",
    "            if (!component) return;",
    "            component.x = moduleWorkbenchClamp(Number(item.x) || component.x, 0, 120);",
    "            component.y = moduleWorkbenchClamp(Number(item.y) || component.y, 0, 200);",
    "            component.w = moduleWorkbenchClamp(Number(item.w) || component.w, 1, 12);",
    "            component.h = moduleWorkbenchClamp(Number(item.h) || component.h, 1, 12);",
    "        });",
    "    };",
    "",
    "    palette.innerHTML = defs.map((entry) => `<button type=\"button\" class=\"module-wb-palette-btn\" data-app-component=\"${entry.id}\"><strong>${entry.label}</strong><span>${entry.w} x ${entry.h}</span></button>`).join('');",
    "",
    "    wb.components.forEach((component) => {",
    "        grid.addWidget({",
    "            id: component.id,",
    "            x: component.x,",
    "            y: component.y,",
    "            w: component.w,",
    "            h: component.h,",
    "            content: widgetMarkup(component),",
    "        });",
    "    });",
    "    if (!wb.selectedId && wb.components[0]) wb.selectedId = safeString(wb.components[0].id);",
    "    grid.column(wb.device === 'mobile' ? 4 : 12, 'moveScale');",
    "    renderStatus();",
    "    renderInspector();",
    "    renderProjectSelect();",
    "    renderPreview();",
    "",
    "    grid.on('change', (_event, items) => {",
    "        syncFromGridItems(items);",
    "        renderStatus();",
    "        renderInspector();",
    "        renderPreview();",
    "    });",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const projectActionEl = event.target instanceof Element",
    "            ? event.target.closest('[data-wb-project-action][data-wb-project-mode=\"app_builder\"]')",
    "            : null;",
    "        if (projectActionEl) {",
    "            const action = safeString(projectActionEl.dataset.wbProjectAction).toLowerCase();",
    "            const select = shell.querySelector('select[data-wb-project-select=\"app_builder\"]');",
    "            const input = shell.querySelector('input[data-wb-project-name=\"app_builder\"]');",
    "            const selectedId = safeString(select instanceof HTMLSelectElement ? select.value : wb.selectedProjectId);",
    "            if (action === 'save') {",
    "                const savedId = moduleWorkbenchProjectSave('app_builder', {",
    "                    device: wb.device,",
    "                    components: wb.components,",
    "                }, safeString(input instanceof HTMLInputElement ? input.value : ''));",
    "                wb.selectedProjectId = savedId;",
    "                if (input instanceof HTMLInputElement) input.value = '';",
    "                renderProjectSelect();",
    "                notifyUser('App project saved.', { tone: 'success', durationMs: 1600, debugKind: 'app-builder' });",
    "                return;",
    "            }",
    "            if (action === 'load') {",
    "                if (!selectedId) return;",
    "                const project = moduleWorkbenchProjectGet('app_builder', selectedId);",
    "                if (!project?.payload) return;",
    "                const payload = project.payload;",
    "                const components = Array.isArray(payload.components) ? payload.components : [];",
    "                grid.removeAll(false);",
    "                wb.components = components.map((component, index) => safeWidget(component, index));",
    "                wb.device = safeString(payload.device) === 'mobile' ? 'mobile' : 'desktop';",
    "                wb.components.forEach((component) => {",
    "                    grid.addWidget({",
    "                        id: component.id,",
    "                        x: component.x,",
    "                        y: component.y,",
    "                        w: component.w,",
    "                        h: component.h,",
    "                        content: widgetMarkup(component),",
    "                    });",
    "                });",
    "                wb.selectedId = wb.components[0] ? safeString(wb.components[0].id) : '';",
    "                wb.selectedProjectId = selectedId;",
    "                grid.column(wb.device === 'mobile' ? 4 : 12, 'moveScale');",
    "                shell.querySelector('.module-wb-gridstack-shell')?.classList.toggle('mobile-mode', wb.device === 'mobile');",
    "                renderStatus();",
    "                renderInspector();",
    "                renderPreview();",
    "                renderProjectSelect();",
    "                notifyUser(`Loaded app project: ${safeString(project.name)}.`, { tone: 'success', durationMs: 1800, debugKind: 'app-builder' });",
    "                return;",
    "            }",
    "            if (action === 'delete') {",
    "                if (!selectedId) return;",
    "                if (moduleWorkbenchProjectDelete('app_builder', selectedId)) {",
    "                    wb.selectedProjectId = '';",
    "                    renderProjectSelect();",
    "                    notifyUser('Deleted app project.', { tone: 'warn', durationMs: 1700, debugKind: 'app-builder' });",
    "                }",
    "                return;",
    "            }",
    "        }",
    "        const target = event.target instanceof Element ? event.target.closest('[data-app-component], [data-app-action], [data-app-device], .module-wb-app-widget') : null;",
    "        if (!target) return;",
    "        const componentType = safeString(target.dataset.appComponent);",
    "        const action = safeString(target.dataset.appAction).toLowerCase();",
    "        const device = safeString(target.dataset.appDevice);",
    "        const widgetId = safeString(target.dataset.appWidgetId);",
    "        if (widgetId) {",
    "            wb.selectedId = widgetId;",
    "            renderInspector();",
    "            return;",
    "        }",
    "        if (componentType) {",
    "            const def = defs.find((entry) => entry.id === componentType) || defs[0];",
    "            const component = {",
    "                id: `ui-${wb.nextId++}`,",
    "                type: def.id,",
    "                label: `${def.label} ${wb.nextId - 1}`,",
    "                binding: '',",
    "                required: false,",
    "                x: 0,",
    "                y: 0,",
    "                w: def.w,",
    "                h: def.h,",
    "            };",
    "            wb.components.push(component);",
    "            grid.addWidget({",
    "                id: component.id,",
    "                x: component.x,",
    "                y: component.y,",
    "                w: component.w,",
    "                h: component.h,",
    "                content: widgetMarkup(component),",
    "            });",
    "            wb.selectedId = component.id;",
    "            renderStatus();",
    "            renderInspector();",
    "            renderPreview();",
    "            return;",
    "        }",
    "        if (device) {",
    "            wb.device = device === 'mobile' ? 'mobile' : 'desktop';",
    "            grid.column(wb.device === 'mobile' ? 4 : 12, 'moveScale');",
    "            shell.querySelector('.module-wb-gridstack-shell')?.classList.toggle('mobile-mode', wb.device === 'mobile');",
    "            renderStatus();",
    "            renderPreview();",
    "            return;",
    "        }",
    "        const component = byId(wb.selectedId);",
    "        if (action === 'preview') {",
    "            renderPreview();",
    "            notifyUser('Runtime preview refreshed.', { tone: 'success', durationMs: 1300, debugKind: 'app-builder' });",
    "            return;",
    "        }",
    "        if (action === 'publish') {",
    "            notifyUser('App published to internal preview workspace.', { tone: 'success', durationMs: 1700, debugKind: 'app-builder' });",
    "            return;",
    "        }",
    "        if (action === 'export') {",
    "            moduleWorkbenchCopyJson({",
].join("\n");
