/* split from part-017.js */
export default [
    "    });",
    "",
    "    const activeJobsPayload = jobsPayload || missionState?.lastJobsPayload || { jobs: [] };",
    "    missionRenderOpsStrip(payload, activeJobsPayload);",
    "    missionRenderJobs(activeJobsPayload);",
    "    missionRenderHeaderAndKpis(payload);",
    "    missionRenderPriorityList(payload, roomLabelById);",
    "    missionRenderApprovals(payload);",
    "    missionRenderRooms(payload, roomLabelById);",
    "    missionRenderTimeline(payload);",
    "}",
    "",
    "function missionStopPolling() {",
    "    if (!missionState || !missionState.pollTimerId) return;",
    "    window.clearInterval(missionState.pollTimerId);",
    "    missionState.pollTimerId = 0;",
    "}",
    "",
    "function missionStartPolling() {",
    "    const state = missionEnsureState();",
    "    if (!state) return;",
    "    missionStopPolling();",
    "    if (!state.active || !state.autoRefresh) return;",
    "    state.pollTimerId = window.setInterval(() => {",
    "        if (!state.active || !state.autoRefresh) return;",
    "        void missionRefresh({ force: true, silent: true });",
    "    }, MISSION_POLL_INTERVAL_MS);",
    "}",
    "",
    "async function missionRefresh({ force = false, silent = false } = {}) {",
    "    const state = missionEnsureState();",
    "    if (!state) return;",
    "    if (!state.active && !force) return;",
    "    if (state.loading) return;",
    "",
    "    state.loading = true;",
    "    if (!silent) {",
    "        missionSetConnectionState('neutral', 'Refreshing');",
    "    }",
    "",
    "    try {",
    "        const [res, jobsRes] = await Promise.all([",
    "            fetch('/api/mission/control'),",
    "            fetch(`/api/mission/jobs?limit=${MISSION_JOBS_LIMIT}`),",
    "        ]);",
    "        if (!res.ok) {",
    "            const details = await res.text();",
    "            throw new Error(details || `HTTP ${res.status}`);",
    "        }",
    "        const payload = await res.json();",
    "        let jobsPayload = state.lastJobsPayload;",
    "        if (jobsRes.ok) {",
    "            jobsPayload = await jobsRes.json();",
    "        } else if (jobsRes.status === 404) {",
    "            jobsPayload = { ok: false, unavailable: true, jobs: [] };",
    "        } else {",
    "            const details = await jobsRes.text();",
    "            console.warn('Mission jobs refresh failed', details || `HTTP ${jobsRes.status}`);",
    "        }",
    "        state.lastPayload = payload;",
    "        state.lastJobsPayload = jobsPayload;",
    "        state.lastFetchedAt = Date.now();",
    "        missionRender(payload, jobsPayload);",
    "        missionSetConnectionState('ok', 'Live');",
    "    } catch (error) {",
    "        console.error('Mission refresh failed', error);",
    "        missionSetConnectionState('danger', 'Offline');",
    "        if (!silent) {",
    "            notifyUser('Mission Control refresh failed.', {",
    "                tone: 'warning',",
    "                debugKind: 'warning',",
    "                durationMs: 2600,",
    "            });",
    "        }",
    "    } finally {",
    "        state.loading = false;",
    "    }",
    "}",
    "",
    "function missionSetCreateMeta(text) {",
    "    if (!missionCreateMeta) return;",
    "    missionCreateMeta.textContent = safeString(text) || 'workflow task';",
    "}",
    "",
    "function missionUpdateScheduleFields() {",
    "    const mode = safeString(missionJobModeSelect?.value).toLowerCase() || 'now';",
    "    if (missionJobOnceAtRow) missionJobOnceAtRow.classList.toggle('hidden', mode !== 'once');",
    "    if (missionJobEverySecondsRow) missionJobEverySecondsRow.classList.toggle('hidden', mode !== 'interval');",
    "    const timeBased = mode === 'daily' || mode === 'weekly';",
    "    if (missionJobAtRow) missionJobAtRow.classList.toggle('hidden', !timeBased);",
    "    if (missionJobTimezoneRow) missionJobTimezoneRow.classList.toggle('hidden', !timeBased);",
    "    if (missionJobWeekdayRow) missionJobWeekdayRow.classList.toggle('hidden', mode !== 'weekly');",
    "",
    "    if (mode === 'now') missionSetCreateMeta('run immediately');",
    "    if (mode === 'once') missionSetCreateMeta('one-time schedule');",
    "    if (mode === 'interval') missionSetCreateMeta('recurring interval');",
    "    if (mode === 'daily') missionSetCreateMeta('daily cron');",
    "    if (mode === 'weekly') missionSetCreateMeta('weekly cron');",
    "",
    "    if (mode === 'once' && missionJobOnceAtInput && !safeString(missionJobOnceAtInput.value)) {",
    "        const dt = new Date(Date.now() + (15 * 60 * 1000));",
    "        dt.setSeconds(0, 0);",
    "        const yyyy = String(dt.getFullYear());",
    "        const mm = String(dt.getMonth() + 1).padStart(2, '0');",
    "        const dd = String(dt.getDate()).padStart(2, '0');",
    "        const hh = String(dt.getHours()).padStart(2, '0');",
    "        const min = String(dt.getMinutes()).padStart(2, '0');",
    "        missionJobOnceAtInput.value = `${yyyy}-${mm}-${dd}T${hh}:${min}`;",
    "    }",
    "}",
    "",
    "function missionApplyTemplate(button) {",
    "    if (!(button instanceof HTMLButtonElement)) return;",
    "    const ds = button.dataset || {};",
    "    const name = safeString(ds.name);",
    "    const goal = safeString(ds.goal);",
    "    const mode = safeString(ds.mode).toLowerCase();",
    "    const workflow = safeString(ds.workflow);",
    "    const at = safeString(ds.at);",
    "    const everySeconds = safeString(ds.everySeconds);",
    "",
    "    if (name && missionJobNameInput) missionJobNameInput.value = name;",
    "    if (goal && missionJobPromptInput) missionJobPromptInput.value = goal;",
    "    if (workflow && missionJobWorkflowInput) missionJobWorkflowInput.value = workflow;",
    "    if (mode && missionJobModeSelect) missionJobModeSelect.value = mode;",
    "    if (at && missionJobAtInput) missionJobAtInput.value = at;",
    "    if (everySeconds && missionJobEverySecondsInput) missionJobEverySecondsInput.value = everySeconds;",
    "",
    "    missionUpdateScheduleFields();",
    "    if (mode === 'once' && missionJobOnceAtInput && !safeString(missionJobOnceAtInput.value)) {",
    "        const dt = new Date(Date.now() + (20 * 60 * 1000));",
    "        dt.setSeconds(0, 0);",
    "        const yyyy = String(dt.getFullYear());",
    "        const mm = String(dt.getMonth() + 1).padStart(2, '0');",
    "        const dd = String(dt.getDate()).padStart(2, '0');",
    "        const hh = String(dt.getHours()).padStart(2, '0');",
    "        const min = String(dt.getMinutes()).padStart(2, '0');",
    "        missionJobOnceAtInput.value = `${yyyy}-${mm}-${dd}T${hh}:${min}`;",
    "    }",
    "    missionSetCreateMeta(`template: ${safeString(button.textContent).trim()}`);",
    "}",
    "",
    "function missionCollectWeekdays() {",
    "    if (!missionJobWeekdays) return [];",
    "    const out = [];",
    "    missionJobWeekdays.querySelectorAll('input[type=\"checkbox\"]').forEach((el) => {",
    "        if (!(el instanceof HTMLInputElement)) return;",
    "        if (!el.checked) return;",
    "        const val = Number(el.value);",
    "        if (!Number.isInteger(val) || val < 0 || val > 6) return;",
    "        out.push(val);",
    "    });",
    "    return out;",
    "}",
    "",
    "function missionDatetimeLocalToIso(valueRaw) {",
    "    const raw = safeString(valueRaw);",
    "    if (!raw) return '';",
    "    const dt = new Date(raw);",
    "    const epoch = dt.getTime();",
    "    if (!Number.isFinite(epoch)) return '';",
    "    return dt.toISOString();",
    "}",
    "",
    "function missionBuildCreateJobPayload() {",
    "    const mode = safeString(missionJobModeSelect?.value).toLowerCase() || 'now';",
    "    const name = safeString(missionJobNameInput?.value) || 'Mission Task';",
    "    const goal = safeString(missionJobPromptInput?.value);",
    "    if (!goal) {",
    "        throw new Error('Task / Goal is required.');",
    "    }",
    "",
    "    const workflow = safeString(missionJobWorkflowInput?.value) || 'chain';",
    "    const profile = safeString(missionJobProfileInput?.value);",
    "    const modelId = safeString(missionJobModelInput?.value);",
    "    const requiresApproval = Boolean(missionJobApprovalToggle?.checked);",
    "",
    "    const payload = {",
    "        name,",
    "        kind: 'workflow_task',",
    "        goal,",
    "        prompt: goal,",
    "        workflow,",
    "        requires_approval: requiresApproval,",
    "    };",
    "    if (profile) payload.profile = profile;",
    "    if (modelId) payload.model_id = modelId;",
    "",
    "    if (mode === 'once') {",
    "        const runAtIso = missionDatetimeLocalToIso(missionJobOnceAtInput?.value);",
    "        if (!runAtIso) {",
    "            throw new Error('Run at date/time is required for one-time jobs.');",
    "        }",
    "        payload.run_at = runAtIso;",
    "        return payload;",
    "    }",
    "",
    "    if (mode === 'interval') {",
    "        const everySeconds = Number(missionJobEverySecondsInput?.value || 0);",
    "        if (!Number.isFinite(everySeconds) || everySeconds <= 0) {",
    "            throw new Error('Every seconds must be a positive number.');",
    "        }",
    "        payload.schedule = {",
    "            type: 'interval',",
    "            every_seconds: Math.round(everySeconds),",
    "        };",
    "        return payload;",
    "    }",
    "",
    "    if (mode === 'daily') {",
    "        const at = safeString(missionJobAtInput?.value);",
    "        if (!/^\\d{2}:\\d{2}$/.test(at)) {",
    "            throw new Error('Daily time must be HH:MM.');",
    "        }",
    "        const tz = safeString(missionJobTimezoneInput?.value) || 'UTC';",
    "        payload.schedule = {",
    "            type: 'daily',",
    "            at,",
    "            tz,",
    "        };",
    "        return payload;",
    "    }",
    "",
    "    if (mode === 'weekly') {",
    "        const at = safeString(missionJobAtInput?.value);",
    "        if (!/^\\d{2}:\\d{2}$/.test(at)) {",
    "            throw new Error('Weekly time must be HH:MM.');",
    "        }",
    "        const dow = missionCollectWeekdays();",
    "        if (!dow.length) {",
    "            throw new Error('Select at least one weekday for weekly cron.');",
    "        }",
    "        const tz = safeString(missionJobTimezoneInput?.value) || 'UTC';",
    "        payload.schedule = {",
    "            type: 'weekly',",
    "            at,",
    "            tz,",
    "            dow,",
    "        };",
    "        return payload;",
    "    }",
    "",
    "    return payload;",
    "}",
    "",
    "async function missionCreateJobFromForm(event) {",
    "    if (event) event.preventDefault();",
    "    const state = missionEnsureState();",
    "    if (!state || state.actionInFlight) return;",
    "",
    "    let payload;",
    "    try {",
    "        payload = missionBuildCreateJobPayload();",
    "    } catch (error) {",
    "        notifyUser(String(error?.message || 'Invalid mission job input.'), {",
    "            tone: 'warning',",
    "            debugKind: 'warning',",
    "            durationMs: 2600,",
    "        });",
    "        return;",
    "    }",
    "",
    "    state.actionInFlight = true;",
    "    if (missionJobSubmitBtn) missionJobSubmitBtn.disabled = true;",
    "    missionSetCreateMeta('submitting...');",
    "    try {",
    "        const res = await fetch('/api/mission/jobs', {",
    "            method: 'POST',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify(payload),",
    "        });",
    "        if (!res.ok) {",
    "            const details = await res.text();",
    "            throw new Error(details || `HTTP ${res.status}`);",
    "        }",
    "        const created = await res.json();",
    "        const jobName = safeString(created?.job?.name) || safeString(payload?.name) || 'Mission job';",
    "        notifyUser(`${jobName} created.`, {",
    "            tone: 'success',",
    "            debugKind: 'success',",
    "            durationMs: 1900,",
    "        });",
    "        missionSetCreateMeta(`created ${jobName}`);",
    "        await missionRefresh({ force: true, silent: true });",
    "    } catch (error) {",
    "        console.error('Mission create job failed', error);",
    "        missionSetCreateMeta('create failed');",
    "        notifyUser('Failed to create mission job.', {",
    "            tone: 'warning',",
    "            debugKind: 'warning',",
    "            durationMs: 2600,",
    "        });",
    "    } finally {",
    "        state.actionInFlight = false;",
    "        if (missionJobSubmitBtn) missionJobSubmitBtn.disabled = false;",
    "    }",
    "}",
    "",
    "function missionEnterMode() {",
    "    const state = missionEnsureState();",
    "    if (!state) return;",
    "    state.active = true;",
    "    state.autoRefresh = true;",
    "    missionStartPolling();",
    "",
    "    const isStale = (Date.now() - Number(state.lastFetchedAt || 0)) > MISSION_POLL_INTERVAL_MS;",
    "    if (!state.lastPayload || isStale) {",
    "        void missionRefresh({ force: true });",
    "    } else {",
    "        missionRender(state.lastPayload, state.lastJobsPayload);",
    "        missionSetConnectionState('ok', 'Live');",
    "    }",
    "}",
    "",
    "function missionLeaveMode() {",
    "    if (!missionState) return;",
    "    missionState.active = false;",
    "    missionStopPolling();",
    "}",
    "",
    "function initMissionWorkspace() {",
    "    const state = missionEnsureState();",
    "    if (!state) return;",
    "    if (!state.controlsBound) {",
    "        state.controlsBound = true;",
    "        if (missionJobsList) {",
    "            missionJobsList.addEventListener('click', (event) => {",
    "                if (!(event.target instanceof Element)) return;",
    "                const button = event.target.closest('button[data-job-action][data-job-id]');",
    "                if (!(button instanceof HTMLButtonElement)) return;",
    "                const action = safeString(button.dataset.jobAction);",
    "                const jobId = safeString(button.dataset.jobId);",
    "                if (!action || !jobId) return;",
    "                void missionRunJobAction(jobId, action);",
    "            });",
    "        }",
    "        if (missionApprovalsList) {",
    "            missionApprovalsList.addEventListener('click', (event) => {",
    "                if (!(event.target instanceof Element)) return;",
    "                const button = event.target.closest('button[data-approval-action]');",
    "                if (!(button instanceof HTMLButtonElement)) return;",
    "                const source = safeString(button.dataset.approvalSource);",
    "                const action = safeString(button.dataset.approvalAction);",
    "                if (!source || !action) return;",
    "                const payload = {",
    "                    source,",
    "                    action,",
    "                    approvalId: safeString(button.dataset.approvalId),",
    "                    runId: safeString(button.dataset.runId),",
    "                    toolCallId: safeString(button.dataset.toolCallId),",
    "                    toolName: safeString(button.dataset.toolName),",
    "                    sessionId: safeString(button.dataset.sessionId),",
    "                };",
    "                void missionResolveApproval(payload);",
    "            });",
    "        }",
    "        if (missionJobModeSelect) {",
    "            missionJobModeSelect.addEventListener('change', () => {",
    "                missionUpdateScheduleFields();",
    "            });",
    "        }",
    "        if (missionJobForm) {",
    "            missionJobForm.addEventListener('submit', (event) => {",
    "                void missionCreateJobFromForm(event);",
    "            });",
    "        }",
    "        if (missionJobTemplates) {",
    "            missionJobTemplates.addEventListener('click', (event) => {",
    "                if (!(event.target instanceof Element)) return;",
    "                const button = event.target.closest('.mission-template-btn');",
    "                if (!(button instanceof HTMLButtonElement)) return;",
    "                missionApplyTemplate(button);",
    "            });",
    "        }",
    "    }",
    "",
    "    if (missionJobTimezoneInput && !safeString(missionJobTimezoneInput.value)) {",
    "        try {",
    "            const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';",
    "            if (tz) missionJobTimezoneInput.value = tz;",
    "        } catch (_error) {",
    "            missionJobTimezoneInput.value = 'UTC';",
    "        }",
    "    }",
    "    missionUpdateScheduleFields();",
    "    missionSetConnectionState('ok', 'Live');",
    "    if (missionJobsTaskCount) missionJobsTaskCount.textContent = '0';",
    "    if (missionJobsCronCount) missionJobsCronCount.textContent = '0';",
    "    if (missionJobsMeta && !state.lastJobsPayload) missionJobsMeta.textContent = 'No jobs loaded';",
    "    if (!state.lastPayload) {",
    "        missionRenderEmpty(missionJobsList, 'No jobs yet. Create a task or cron job from the form.');",
    "        missionRenderEmpty(missionPriorityList, 'No mission jobs yet. Activity appears idle.');",
    "        missionRenderEmpty(missionApprovalsList, 'No approvals are waiting.');",
    "        missionRenderEmpty(missionRoomsList, 'No active room load right now.');",
    "        missionRenderEmpty(missionTimelineList, 'No recent signals in the last 36 hours.');",
    "    }",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  CONTENT HUB                                                            ║",
    "// ║  Social platforms, workflows, scheduling, content track list            ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    ""
].join("\n");
