/* split from part-002.js */
export default [
    "            }",
    "        }",
    "        return {",
    "            ok: response.ok,",
    "            status: response.status,",
    "            data,",
    "            text,",
    "        };",
    "    } catch (error) {",
    "        const message = error && error.name === 'AbortError' ? 'Request timeout' : safeString(error?.message);",
    "        return {",
    "            ok: false,",
    "            status: 0,",
    "            data: null,",
    "            text: message || 'Network error',",
    "        };",
    "    } finally {",
    "        if (timeoutId) {",
    "            window.clearTimeout(timeoutId);",
    "        }",
    "    }",
    "}",
    "",
    "function taskContinuityStatusLabel(statusRaw) {",
    "    const status = safeString(statusRaw).toLowerCase();",
    "    if (status === 'complete') return 'complete';",
    "    if (status === 'blocked') return 'blocked';",
    "    return 'in_progress';",
    "}",
    "",
    "function taskContinuityShouldBeVisible() {",
    "    if (!taskContinuityPanel) return false;",
    "    if (isSettingsScreenOpen()) return false;",
    "    return sidebarNavMode === 'chat' || sidebarNavMode === 'search';",
    "}",
    "",
    "function stopTaskContinuityAutoRefresh() {",
    "    if (taskContinuityAutoRefreshTimer) {",
    "        window.clearInterval(taskContinuityAutoRefreshTimer);",
    "        taskContinuityAutoRefreshTimer = 0;",
    "    }",
    "}",
    "",
    "function startTaskContinuityAutoRefresh() {",
    "    if (taskContinuityAutoRefreshTimer) return;",
    "    taskContinuityAutoRefreshTimer = window.setInterval(() => {",
    "        if (!taskContinuityShouldBeVisible()) return;",
    "        void refreshTaskContinuity();",
    "    }, TASK_CONTINUITY_REFRESH_INTERVAL_MS);",
    "}",
    "",
    "function renderTaskContinuity(state, events, sessionToken, { error = '' } = {}) {",
    "    if (!taskContinuityPanel) return;",
    "",
    "    const hasState = Boolean(state && typeof state === 'object');",
    "    const normalizedEvents = Array.isArray(events) ? events.slice(0, 6) : [];",
    "    const status = taskContinuityStatusLabel(hasState ? state.status : (error ? 'blocked' : 'in_progress'));",
    "    const activeGoal = hasState ? safeString(state.active_goal) : '';",
    "    const progress = hasState ? safeString(state.last_progress) : '';",
    "    const missingInputs = hasState && Array.isArray(state.missing_inputs) ? state.missing_inputs.filter(Boolean) : [];",
    "    const updatedAtRaw = hasState ? safeString(state.updated_at) : '';",
    "    const sessionLabelRaw = safeString(sessionToken);",
    "    const sessionLabel = sessionLabelRaw.length > 16 ? `${sessionLabelRaw.slice(0, 16)}…` : (sessionLabelRaw || '--');",
    "",
    "    if (hasState) {",
    "        taskContinuityLatestState = state;",
    "    }",
    "    if (normalizedEvents.length) {",
    "        taskContinuityLatestEvents = normalizedEvents;",
    "    }",
    "    if (sessionLabelRaw) {",
    "        taskContinuityLatestSessionId = sessionLabelRaw;",
    "    }",
    "",
    "    if (taskContinuityStatusPill) {",
    "        taskContinuityStatusPill.textContent = status;",
    "        taskContinuityStatusPill.classList.remove('is-complete', 'is-blocked');",
    "        if (status === 'complete') taskContinuityStatusPill.classList.add('is-complete');",
    "        if (status === 'blocked') taskContinuityStatusPill.classList.add('is-blocked');",
    "    }",
    "",
    "    if (taskContinuityGoal) {",
    "        if (activeGoal) {",
    "            taskContinuityGoal.textContent = activeGoal;",
    "        } else if (error) {",
    "            taskContinuityGoal.textContent = 'Task continuity is temporarily unavailable.';",
    "        } else {",
    "            taskContinuityGoal.textContent = 'No active task tracked yet.';",
    "        }",
    "    }",
    "",
    "    if (taskContinuityProgress) {",
    "        if (progress) {",
    "            taskContinuityProgress.textContent = progress;",
    "        } else if (error) {",
    "            taskContinuityProgress.textContent = error;",
    "        } else {",
    "            taskContinuityProgress.textContent = 'Waiting for first update.';",
    "        }",
    "    }",
    "",
    "    if (taskContinuityBlockersWrap && taskContinuityBlockersList) {",
    "        taskContinuityBlockersWrap.classList.toggle('hidden', missingInputs.length === 0);",
    "        taskContinuityBlockersList.innerHTML = missingInputs",
    "            .map((item) => `<li>${escapeHtml(safeString(item))}</li>`)",
    "            .join('');",
    "    }",
    "",
    "    if (taskContinuityEventsList) {",
    "        if (normalizedEvents.length > 0) {",
    "            taskContinuityEventsList.classList.remove('hidden');",
    "            taskContinuityEventsList.innerHTML = normalizedEvents.map((entry) => {",
    "                const source = safeString(entry?.source).replace(/^chat\\./, '');",
    "                const line = safeString(entry?.last_progress);",
    "                const when = missionRelativeTime(entry?.created_at);",
    "                const text = [source || 'event', line].filter(Boolean).join(' | ');",
    "                const suffix = when && when !== '--' ? ` (${when})` : '';",
    "                return `<li title=\"${escapeHtml(text)}\">${escapeHtml(text)}${escapeHtml(suffix)}</li>`;",
    "            }).join('');",
    "        } else {",
    "            taskContinuityEventsList.classList.add('hidden');",
    "            taskContinuityEventsList.innerHTML = '';",
    "        }",
    "    }",
    "",
    "    if (taskContinuityUpdatedAt) {",
    "        taskContinuityUpdatedAt.textContent = updatedAtRaw ? `Updated ${missionRelativeTime(updatedAtRaw)}` : 'Not synced';",
    "    }",
    "    if (taskContinuitySession) {",
    "        taskContinuitySession.textContent = `Session: ${sessionLabel}`;",
    "    }",
    "}",
    "",
    "async function refreshTaskContinuity({ sessionOverride = '', force = false } = {}) {",
    "    if (taskContinuityInFlight && !force) return;",
    "",
    "    const sid = safeString(sessionOverride || sessionId || activeChatId || taskContinuityLatestSessionId);",
    "    const currentUrl = sid",
    "        ? `/api/task-ledger/current?session_id=${encodeURIComponent(sid)}`",
    "        : '/api/task-ledger/current';",
    "    const historyUrl = sid",
    "        ? `/api/task-ledger/history?session_id=${encodeURIComponent(sid)}&limit=6`",
    "        : '/api/task-ledger/history?limit=6';",
    "",
    "    taskContinuityInFlight = true;",
    "    if (taskContinuityRefreshBtn) taskContinuityRefreshBtn.disabled = true;",
    "    try {",
    "        const [currentResp, historyResp] = await Promise.all([",
    "            fetchJsonSafe(currentUrl),",
    "            fetchJsonSafe(historyUrl),",
    "        ]);",
    "        if (!currentResp.ok || !historyResp.ok) {",
    "            throw new Error('Unable to refresh task continuity right now.');",
    "        }",
    "        const currentPayload = currentResp.data && typeof currentResp.data === 'object' ? currentResp.data : {};",
    "        const historyPayload = historyResp.data && typeof historyResp.data === 'object' ? historyResp.data : {};",
    "        const state = currentPayload.state && typeof currentPayload.state === 'object' ? currentPayload.state : null;",
    "        const events = Array.isArray(historyPayload.events) ? historyPayload.events : [];",
    "        const resolvedSid = safeString(currentPayload.session_id || historyPayload.session_id || sid);",
    "        renderTaskContinuity(state, events, resolvedSid);",
    "    } catch (error) {",
    "        const fallbackState = taskContinuityLatestState;",
    "        const fallbackEvents = taskContinuityLatestEvents;",
    "        const fallbackSid = safeString(taskContinuityLatestSessionId || sid);",
    "        renderTaskContinuity(fallbackState, fallbackEvents, fallbackSid, {",
    "            error: safeString(error?.message) || 'Sync failed.',",
    "        });",
    "    } finally {",
    "        taskContinuityInFlight = false;",
    "        if (taskContinuityRefreshBtn) taskContinuityRefreshBtn.disabled = false;",
    "        taskContinuityPanel.classList.toggle('hidden', !taskContinuityShouldBeVisible());",
    "    }",
    "}",
    "",
    "function updateTaskContinuityVisibility({ refresh = false } = {}) {",
    "    if (!taskContinuityPanel) return;",
    "    const visible = taskContinuityShouldBeVisible();",
    "    taskContinuityPanel.classList.toggle('hidden', !visible);",
    "    if (!visible) {",
    "        stopTaskContinuityAutoRefresh();",
    "        return;",
    "    }",
    "    startTaskContinuityAutoRefresh();",
    "    if (refresh) {",
    "        void refreshTaskContinuity({ force: true });",
    "    }",
    "}",
    "",
    "async function emitOnboardingTelemetry(eventName, payload = {}) {",
    "    const normalized = safeString(eventName);",
    "    if (!normalized) return;",
    "    const basePayload = payload && typeof payload === 'object' ? { ...payload } : {};",
    "    const telemetryTiming = ensureOnboardingTelemetryClock();",
    "    if (!safeString(basePayload.onboarding_session_id)) {",
    "        basePayload.onboarding_session_id = telemetryTiming.onboarding_session_id;",
    "    }",
    "    if (!Number.isFinite(Number(basePayload.elapsed_ms))) {",
    "        basePayload.elapsed_ms = telemetryTiming.elapsed_ms;",
    "    }",
    "    try {",
    "        await fetch('/api/onboarding/telemetry', {",
    "            method: 'POST',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({",
    "                event: normalized,",
    "                payload: basePayload,",
    "            }),",
    "        });",
    "    } catch {",
    "        // Best-effort telemetry only.",
    "    }",
    "}",
    "",
    "function getOnboardingFromPrefs() {",
    "    return currentPreferences?.onboarding || {};",
    "}",
    "",
    "function isOnboardingComplete() {",
    "    return Boolean(getOnboardingFromPrefs()?.setup_completed);",
    "}",
    "",
    "function mapRecommendedPath(bootstrap) {",
    "    const recommended = safeString(bootstrap?.quick_start?.recommended_path).toLowerCase();",
    "    if (recommended === 'codex') return 'codex';",
    "    if (recommended === 'local') return 'local';",
    "    if (recommended === 'cloud') return 'manual';",
    "    return '';",
    "}",
    "",
    "function easySetupStepName(step) {",
    "    if (step <= 1) return 'choose_path';",
    "    if (step === 2) return 'connect';",
    "    if (step === 3) return 'downloads';",
    "    if (step === 4) return 'brain_ready';",
    "    return 'choose_path';",
    "}",
    "",
    "function stepFromOnboardingName(nameRaw) {",
    "    const name = safeString(nameRaw).toLowerCase();",
    "    if (name === 'connect') return 2;",
    "    if (name === 'downloads') return 3;",
    "    if (name === 'brain_ready') return 4;",
    "    if (name === 'interview' || name === 'completed') return 4;",
    "    return 1;",
    "}",
    "",
    "function setEasySetupStatus(targetEl, text, tone = '') {",
    "    if (!targetEl) return;",
    "    targetEl.textContent = safeString(text);",
    "    targetEl.classList.remove('ok', 'error');",
    "    if (tone === 'ok') targetEl.classList.add('ok');",
    "    if (tone === 'error') targetEl.classList.add('error');",
    "    if (tone === 'error') {",
    "        notifyUser(targetEl.textContent, {",
    "            tone: 'error',",
    "            durationMs: 3400,",
    "        });",
    "    }",
    "}",
    "",
    "function hideAssistantSuggestions({ force = false } = {}) {",
    "    if (!assistantSuggestionRail || !assistantSuggestionBubbles) return;",
    "    if (!force && !suggestionDismissible) return;",
    "    _stopSuggestionAutoScroll();",
    "    suggestionRailVersion += 1;",
    "    suggestionContext = '';",
    "    suggestionDismissible = true;",
    "    assistantSuggestionBubbles.innerHTML = '';",
    "    assistantSuggestionRail.classList.add('hidden');",
    "    assistantSuggestionRail.removeAttribute('data-context');",
    "    if (assistantSuggestionTitle) assistantSuggestionTitle.textContent = 'Suggestions';",
    "    if (assistantSuggestionDismissBtn) assistantSuggestionDismissBtn.classList.add('hidden');",
    "}",
    "",
    "// CSS marquee handles the scrolling animation via .assistant-suggestion-track",
    "// These are kept as no-ops for any callers that reference them",
    "function _startSuggestionAutoScroll() {}",
    "function _stopSuggestionAutoScroll() {}",
    "",
    "function setAssistantSuggestions({ title = 'Suggestions', options = [], context = 'general', dismissible = true } = {}) {",
    "    if (!assistantSuggestionRail || !assistantSuggestionBubbles) return;",
    "    // Don't show suggestions while the model is generating",
    "    if (isGenerating) return;",
    "",
    "    const validOptions = (Array.isArray(options) ? options : []).filter((option) => {",
    "        return Boolean(safeString(option?.label) || safeString(option?.value));",
    "    });",
    "    if (validOptions.length === 0) {",
    "        hideAssistantSuggestions({ force: true });",
    "        return;",
    "    }"
].join("\n");
