/* split from part-003.js */
export default [
    "    const dependencyPlanPayload = overrides.dependency_plan !== undefined",
    "        ? overrides.dependency_plan",
    "        : {",
    "            path: safeString(easySetupState.selectedPath),",
    "            items: Array.isArray(easySetupState.dependencyPlan) ? easySetupState.dependencyPlan : [],",
    "        };",
    "",
    "    const onboardingPatch = {",
    "        version: ONBOARDING_VERSION,",
    "        setup_completed: Boolean(",
    "            Object.prototype.hasOwnProperty.call(overrides, 'setup_completed')",
    "                ? overrides.setup_completed",
    "                : existing.setup_completed",
    "        ),",
    "        current_step: Object.prototype.hasOwnProperty.call(overrides, 'current_step')",
    "            ? overrides.current_step",
    "            : easySetupStepName(easySetupState.step),",
    "        connection_method: Object.prototype.hasOwnProperty.call(overrides, 'connection_method')",
    "            ? overrides.connection_method",
    "            : (safeString(easySetupState.selectedPath) || existing.connection_method || null),",
    "        dependency_plan: dependencyPlanPayload,",
    "        answers: mergedAnswers,",
    "    };",
    "",
    "    if (Object.prototype.hasOwnProperty.call(overrides, 'completed_at')) {",
    "        onboardingPatch.completed_at = overrides.completed_at;",
    "    }",
    "    if (Object.prototype.hasOwnProperty.call(overrides, 'dismissed_at')) {",
    "        onboardingPatch.dismissed_at = overrides.dismissed_at;",
    "    }",
    "",
    "    try {",
    "        const res = await fetch('/api/preferences', {",
    "            method: 'PATCH',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({ onboarding: onboardingPatch }),",
    "        });",
    "        if (!res.ok) return null;",
    "        currentPreferences = await res.json();",
    "        return currentPreferences?.onboarding || null;",
    "    } catch {",
    "        return null;",
    "    }",
    "}",
    "",
"function closeEasySetup() {",
"    if (!easySetupModal) return;",
"    easySetupModal.classList.remove('active');",
"    easySetupModal.style.display = 'none';",
"}",
"",
"function hasEasySetupDismissRecord() {",
"    const onboarding = getOnboardingFromPrefs();",
"    return Boolean(safeString(onboarding?.dismissed_at));",
"}",
"",
"function blockEasySetupClose(source = 'close_request') {",
"    const message = withAgentName('Setup is required before {{agent}} can run. Complete Easy Setup to continue.');",
"    if (easySetupState.step === 1 && easySetupRecommendedHint) {",
"        easySetupRecommendedHint.textContent = message;",
    "    } else {",
    "        const target = easySetupState.step >= 3 ? easySetupDependencyStatus : easySetupConnectionStatus;",
    "        setEasySetupStatus(target, message, 'error');",
    "    }",
    "    emitOnboardingTelemetry('wizard.close_blocked', {",
    "        source: safeString(source),",
    "        step: easySetupStepName(easySetupState.step),",
    "        path: safeString(easySetupState.selectedPath),",
    "    });",
    "}",
"",
"function requestEasySetupClose(source = 'close_request') {",
"    if (easySetupState.required && source !== 'footer_skip') {",
"        blockEasySetupClose(source);",
"        return;",
"    }",
"    if (source === 'footer_skip' && easySetupState.required) {",
"        easySetupState.required = false;",
"        void persistOnboardingPrefs({",
"            dismissed_at: onboardingNowIso(),",
"        });",
"        emitOnboardingTelemetry('wizard.skipped', {",
"            source: safeString(source),",
"            step: easySetupStepName(easySetupState.step),",
"            path: safeString(easySetupState.selectedPath),",
"        });",
"    }",
"    closeEasySetup();",
"    emitOnboardingTelemetry('wizard.closed', {",
"        source: safeString(source),",
"        step: easySetupStepName(easySetupState.step),",
"        path: safeString(easySetupState.selectedPath),",
    "    });",
    "}",
    "",
    "async function openEasySetup({ source = 'manual', force = false, restart = false } = {}) {",
    "    if (!easySetupModal) return;",
    "    if (!currentPreferences) {",
    "        await refreshIdentityState();",
    "    }",
    "",
"    const onboarding = getOnboardingFromPrefs();",
"    const setupCompleted = Boolean(onboarding?.setup_completed);",
"    if (!force && setupCompleted) {",
"        return;",
"    }",
"    easySetupState.required = !setupCompleted && !hasEasySetupDismissRecord();",
"    hideAssistantSuggestions({ force: true });",
    "",
    "    easySetupState.source = safeString(source) || 'manual';",
    "    easySetupState.onboardingSessionId = createOnboardingTelemetrySessionId();",
    "    easySetupState.telemetryStartedAtMs = Date.now();",
    "    if (restart) {",
    "        easySetupState.interviewAnswers = {};",
    "        easySetupState.interviewStarted = false;",
    "        easySetupState.interviewStage = 'idle';",
    "        easySetupState.interviewIndex = -1;",
    "        easySetupState.interviewSkipChosen = false;",
    "        easySetupState.dependenciesAction = 'pending';",
    "        easySetupState.selectedPath = '';",
    "    } else {",
    "        easySetupState.interviewAnswers = { ...(onboarding?.answers || {}) };",
    "        const restoredDependencyAction = safeString(onboarding?.answers?.dependency_action);",
    "        easySetupState.dependenciesAction = restoredDependencyAction === 'approved' ? 'approved' : 'pending';",
    "    }",
    "",
    "    try {",
    "        const bootstrap = await loadEasySetupBootstrap();",
    "        const recommendedPath = mapRecommendedPath(bootstrap);",
    "        if (!safeString(easySetupState.selectedPath)) {",
    "            easySetupState.selectedPath = safeString(onboarding?.connection_method) || recommendedPath || 'manual';",
    "        }",
    "        easySetupState.dependencyPlan = buildEasySetupDependencyPlan(bootstrap, easySetupState.selectedPath);",
    "",
    "        if (easySetupRecommendedHint) {",
    "            const quickStartReason = safeString(bootstrap?.quick_start?.reason);",
    "            if (recommendedPath) {",
    "                easySetupRecommendedHint.textContent = `Recommended: ${recommendedPath}. ${quickStartReason}`;",
    "            } else {",
    "                easySetupRecommendedHint.textContent = quickStartReason || 'Select the path you want. We will verify before applying.';",
    "            }",
    "        }",
    "    } catch (err) {",
    "        if (easySetupRecommendedHint) {",
    "            easySetupRecommendedHint.textContent = `Bootstrap check failed: ${safeString(err?.message) || 'unable to detect local readiness'}`;",
    "        }",
    "    }",
    "",
    "    refreshEasySetupProfileOptions();",
    "    renderEasySetupPathCards();",
    "    syncEasySetupConnectionBlocks();",
    "    setEasySetupStatus(easySetupConnectionStatus, 'Run connection test to continue.');",
    "    setEasySetupDependencyDefaultStatus();",
    "",
    "    const desiredStep = restart ? 1 : stepFromOnboardingName(onboarding?.current_step);",
    "    setEasySetupStep(desiredStep);",
    "    easySetupModal.classList.add('active');",
    "    easySetupModal.style.display = 'flex';",
    "    emitOnboardingTelemetry('wizard.opened', {",
    "        source: easySetupState.source,",
    "        path: safeString(easySetupState.selectedPath),",
    "        step: easySetupStepName(easySetupState.step),",
    "    });",
    "}",
    "",
"async function maybeAutoOpenEasySetup() {",
"    if (isOnboardingComplete()) {",
"        return;",
"    }",
"    if (hasEasySetupDismissRecord()) {",
"        return;",
"    }",
"    await openEasySetup({ source: 'auto', force: false, restart: false });",
"}",
    "",
    "function handleEasySetupPathSelect(path) {",
    "    easySetupState.selectedPath = safeString(path);",
    "    easySetupState.verified = false;",
    "    easySetupState.verifiedProfile = '';",
    "    easySetupState.codexModels = [];",
    "    easySetupState.dependenciesAction = 'pending';",
    "    easySetupState.dependencyPlan = buildEasySetupDependencyPlan(easySetupState.bootstrap, easySetupState.selectedPath);",
    "    renderEasySetupPathCards();",
    "    syncEasySetupConnectionBlocks();",
    "    setEasySetupStatus(easySetupConnectionStatus, 'Path selected. Run connection test.');",
    "    setEasySetupDependencyDefaultStatus();",
    "    updateEasySetupNavigation();",
    "}",
    "",
    "async function handleEasySetupConnectionTest() {",
    "    if (!safeString(easySetupState.selectedPath)) {",
    "        setEasySetupStatus(easySetupConnectionStatus, 'Pick a connection path first.', 'error');",
    "        return;",
    "    }",
    "",
    "    easySetupState.verified = false;",
    "    easySetupState.verifiedProfile = '';",
    "    setEasySetupStatus(easySetupConnectionStatus, 'Running live connection checks...');",
    "",
    "    try {",
    "        if (easySetupState.selectedPath === 'codex') {",
    "            const statusRes = await fetchJsonSafe('/api/codex/status');",
    "            let loggedIn = Boolean(statusRes.data?.logged_in);",
    "            if (!loggedIn) {",
    "                const loginRes = await fetchJsonSafe('/api/codex/login', { method: 'POST' });",
    "                loggedIn = Boolean(loginRes.data?.ok);",
    "                if (!loggedIn) {",
    "                    const errText = safeString(loginRes.data?.error) || 'Codex login failed.';",
    "                    throw new Error(`${errText} Remediation: install/login Codex CLI and retry.`);",
    "                }",
    "            }",
    "            const modelsRes = await fetchJsonSafe('/api/codex/models');",
    "            easySetupState.codexModels = Array.isArray(modelsRes.data?.models) ? modelsRes.data.models : [];",
    "",
    "            const codexProfile = availableModelProfiles.find((p) => safeString(p?.provider).toLowerCase() === 'codex');",
    "            if (codexProfile?.name) {",
    "                const validateRes = await fetchJsonSafe(`/api/models/${encodeURIComponent(codexProfile.name)}/validate?tool_smoke=0`);",
    "                if (!validateRes.ok || !Boolean(validateRes.data?.ok)) {",
    "                    const reason = safeString(validateRes.data?.error) || safeString(validateRes.text) || 'Codex profile validation failed.';",
    "                    throw new Error(`${reason} Remediation: run auto repair and retry.`);",
    "                }",
    "                easySetupState.verifiedProfile = safeString(codexProfile.name);",
    "            } else {",
    "                easySetupState.verifiedProfile = 'codex';",
    "            }",
    "",
    "            easySetupState.verified = true;",
    "            const codexName = safeString(statusRes.data?.display_name) || safeString(statusRes.data?.email) || 'Codex account';",
    "            setEasySetupStatus(",
    "                easySetupConnectionStatus,",
    "                `Connected as ${codexName}. Models detected: ${easySetupState.codexModels.length}.`,",
    "                'ok'",
    "            );",
    "            if (easySetupCodexMeta) {",
    "                easySetupCodexMeta.textContent = `Signed in. Detected ${easySetupState.codexModels.length} Codex model(s).`;",
    "            }",
    "        } else if (easySetupState.selectedPath === 'manual') {",
    "            const profile = safeString(easySetupManualProfile?.value);",
    "            if (!profile) {",
    "                throw new Error('No manual profile is configured. Add a cloud model profile first.');",
    "            }",
    "            const apiKey = safeString(easySetupManualApiKey?.value);",
    "            if (apiKey) {",
    "                const secretRes = await fetchJsonSafe(`/api/secrets/${encodeURIComponent(profile)}`, {",
    "                    method: 'POST',",
    "                    headers: { 'Content-Type': 'application/json' },",
    "                    body: JSON.stringify({",
    "                        api_key: apiKey,",
    "                        persist: Boolean(easySetupManualPersist?.checked),",
    "                    }),",
    "                });",
    "                if (!secretRes.ok) {",
    "                    const reason = safeString(secretRes.text) || `Could not save key for profile \"${profile}\".`;",
    "                    throw new Error(`${reason} Remediation: verify key format and profile.`);",
    "                }",
    "            }",
    "",
    "            const validateRes = await fetchJsonSafe(`/api/models/${encodeURIComponent(profile)}/validate?tool_smoke=0`);",
    "            if (!validateRes.ok || !Boolean(validateRes.data?.ok)) {",
    "                const reason = safeString(validateRes.data?.error) || safeString(validateRes.text) || 'Profile validation failed.';",
    "                throw new Error(`${reason} Remediation: verify provider key and endpoint.`);",
    "            }",
    "",
    "            easySetupState.verified = true;",
    "            easySetupState.verifiedProfile = profile;",
    "            setEasySetupStatus(",
    "                easySetupConnectionStatus,",
    "                `Manual profile \"${profile}\" validated.`,",
    "                'ok'",
    "            );",
    "        } else {",
    "            const profile = safeString(easySetupLocalProfile?.value) || 'local';",
    "            const validateRes = await fetchJsonSafe(`/api/models/${encodeURIComponent(profile)}/validate?tool_smoke=0`);",
    "            if (!validateRes.ok || !Boolean(validateRes.data?.ok)) {",
    "                const reason = safeString(validateRes.data?.error) || safeString(validateRes.text) || 'Local validation failed.';",
    "                throw new Error(`${reason} Remediation: install/start Ollama or run auto repair.`);",
    "            }",
    "            setEasySetupStatus(easySetupConnectionStatus, `Local profile \"${profile}\" validated. Syncing recommended local models...`);",
    "            const localSync = await runEasySetupLocalModelSync(profile);",
    "            easySetupState.verified = true;",
    "            easySetupState.verifiedProfile = profile;",
    "            const syncSummary = safeString(localSync?.summary);",
    "            setEasySetupStatus(",
    "                easySetupConnectionStatus,",
    "                syncSummary ? `Local profile \"${profile}\" validated. ${syncSummary}` : `Local profile \"${profile}\" validated.`,",
    "                'ok'",
    "            );",
    "        }",
    "    } catch (err) {",
    "        easySetupState.verified = false;",
    "        easySetupState.verifiedProfile = '';",
    "        setEasySetupStatus(easySetupConnectionStatus, safeString(err?.message) || 'Connection check failed.', 'error');",
    "    }",
    "",
    "    easySetupState.dependencyPlan = buildEasySetupDependencyPlan(easySetupState.bootstrap, easySetupState.selectedPath);",
    "    setEasySetupDependencyDefaultStatus();",
    "    updateEasySetupNavigation();",
    "    await persistOnboardingPrefs({",
    "        current_step: 'connect',",
    "        connection_method: safeString(easySetupState.selectedPath) || null,",
    "    });",
    "    emitOnboardingTelemetry('wizard.connection_tested', {",
    "        path: safeString(easySetupState.selectedPath),",
    "        verified: Boolean(easySetupState.verified),",
    "        profile: safeString(easySetupState.verifiedProfile),",
    "    });",
    "}",
    "",
    "async function runEasySetupRepair(trigger = 'repair') {",
    "    setEasySetupStatus(easySetupDependencyStatus, 'Running setup repair. You may need to approve system installer prompts.');",
    "    const res = await fetchJsonSafe('/api/setup/repair', {",
    "        method: 'POST',",
    "        headers: { 'Content-Type': 'application/json' },",
    "        body: JSON.stringify({",
    "            auto_install_tools: true,",
    "            skip_install: false,",
    "            skip_doctor: false,",
    "        }),",
    "    });",
    "",
    "    if (!res.ok || !res.data) {",
    "        const reason = safeString(res.data?.error) || safeString(res.text) || 'Repair call failed.';",
    "        setEasySetupStatus(easySetupDependencyStatus, `${reason} Remediation: run repair from command line and retry.`, 'error');",
    "        emitOnboardingTelemetry('wizard.download_approval_failed', {",
    "            trigger,",
    "            error: reason,",
    "        });",
    "        return false;",
    "    }",
    ""
].join("\n");
