/* split from part-023.js */
export default [
    "                device: wb.device,",
    "                components: wb.components,",
    "            }, 'App Builder Schema');",
    "            return;",
    "        }",
    "        if (action === 'export_html') {",
    "            renderPreview();",
    "            moduleWorkbenchDownloadText('thomas-app-preview.html', wb.previewHtml, 'text/html;charset=utf-8');",
    "            notifyUser('Exported runtime HTML.', { tone: 'success', durationMs: 1600, debugKind: 'app-builder' });",
    "            return;",
    "        }",
    "        if (action === 'open_preview') {",
    "            renderPreview();",
    "            const blob = new Blob([wb.previewHtml], { type: 'text/html;charset=utf-8' });",
    "            const url = URL.createObjectURL(blob);",
    "            window.open(url, '_blank', 'noopener');",
    "            window.setTimeout(() => URL.revokeObjectURL(url), 5000);",
    "            return;",
    "        }",
    "        if (action === 'export_appsmith') {",
    "            moduleWorkbenchCopyJson(moduleWorkbenchAppSchemaToAppsmith(wb), 'Appsmith Page JSON');",
    "            return;",
    "        }",
    "        if (action === 'export_budibase') {",
    "            moduleWorkbenchCopyJson(moduleWorkbenchAppSchemaToBudibase(wb), 'Budibase App JSON');",
    "            return;",
    "        }",
    "        if (action === 'reset') {",
    "            grid.removeAll(false);",
    "            wb.components = [];",
    "            wb.selectedId = '';",
    "            renderStatus();",
    "            renderInspector();",
    "            renderPreview();",
    "            return;",
    "        }",
    "        if (action === 'duplicate' && component) {",
    "            const copy = {",
    "                ...component,",
    "                id: `ui-${wb.nextId++}`,",
    "                label: `${component.label} Copy`,",
    "                x: component.x + 1,",
    "                y: component.y + 1,",
    "            };",
    "            wb.components.push(copy);",
    "            grid.addWidget({",
    "                id: copy.id,",
    "                x: copy.x,",
    "                y: copy.y,",
    "                w: copy.w,",
    "                h: copy.h,",
    "                content: widgetMarkup(copy),",
    "            });",
    "            wb.selectedId = copy.id;",
    "            renderStatus();",
    "            renderInspector();",
    "            renderPreview();",
    "            return;",
    "        }",
    "        if (action === 'delete' && component) {",
    "            const widget = findWidgetById(component.id);",
    "            if (widget) grid.removeWidget(widget, false);",
    "            wb.components = wb.components.filter((row) => safeString(row.id) !== safeString(component.id));",
    "            wb.selectedId = wb.components[0] ? safeString(wb.components[0].id) : '';",
    "            renderStatus();",
    "            renderInspector();",
    "            renderPreview();",
    "        }",
    "    });",
    "",
    "    inspector.addEventListener('input', (event) => {",
    "        const target = event.target;",
    "        if (!(target instanceof HTMLInputElement || target instanceof HTMLSelectElement)) return;",
    "        const component = byId(wb.selectedId);",
    "        if (!component) return;",
    "        const prop = safeString(target.dataset.appProp);",
    "        if (!prop) return;",
    "        if (prop === 'label' || prop === 'binding') component[prop] = safeString(target.value).slice(0, 120);",
    "        if (prop === 'type') component.type = safeString(target.value);",
    "        if (prop === 'required' && target instanceof HTMLInputElement) component.required = target.checked;",
    "        if (prop === 'x' || prop === 'y' || prop === 'w' || prop === 'h') {",
    "            const limits = prop === 'w' || prop === 'h'",
    "                ? { min: 1, max: 12 }",
    "                : { min: 0, max: 200 };",
    "            component[prop] = moduleWorkbenchClamp(Number(target.value) || component[prop], limits.min, limits.max);",
    "            const widget = findWidgetById(component.id);",
    "            if (widget) {",
    "                grid.update(widget, {",
    "                    x: component.x,",
    "                    y: component.y,",
    "                    w: component.w,",
    "                    h: component.h,",
    "                });",
    "            }",
    "        }",
    "        refreshWidgetContent(component);",
    "        renderStatus();",
    "        renderInspector();",
    "        renderPreview();",
    "    });",
    "",
    "    const projectSelect = shell.querySelector('select[data-wb-project-select=\"app_builder\"]');",
    "    if (projectSelect instanceof HTMLSelectElement) {",
    "        projectSelect.addEventListener('change', () => {",
    "            wb.selectedProjectId = safeString(projectSelect.value);",
    "        });",
    "    }",
    "",
    "    return true;",
    "}",
    "",
    "function moduleRenderWorkbenchAppBuilder(container, wb) {",
    "    if (moduleRenderWorkbenchAppBuilderOss(container, wb)) return;",
    "    if (!container || !wb) return;",
    "    if (!Array.isArray(wb.components)) wb.components = [];",
    "    wb.selectedId = safeString(wb.selectedId);",
    "    wb.device = safeString(wb.device) === 'mobile' ? 'mobile' : 'desktop';",
    "    wb.nextId = Math.max(1, Number(wb.nextId) || 1);",
    "    wb.selectedProjectId = safeString(wb.selectedProjectId);",
    "    wb.previewHtml = safeString(wb.previewHtml);",
    "",
    "    moduleWorkbenchHeader(container, 'App Builder Canvas', 'Guide Thomas-generated app components, bindings, and release-ready schema exports.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-app';",
    "    shell.innerHTML = `",
    "        <aside class=\"module-wb-side-card\"><h4>UI Blocks</h4><div class=\"module-wb-palette\" data-app-palette></div>${moduleWorkbenchRenderProjectControls('app_builder', 'App Projects')}<div class=\"module-wb-inspector-actions\"><button type=\"button\" class=\"module-item-btn\" data-app-action=\"preview\">Preview</button><button type=\"button\" class=\"module-item-btn\" data-app-action=\"publish\">Publish</button><button type=\"button\" class=\"module-item-btn\" data-app-action=\"export\">Export</button><button type=\"button\" class=\"module-item-btn\" data-app-action=\"export_html\">Export HTML</button><button type=\"button\" class=\"module-item-btn\" data-app-action=\"open_preview\">Open Preview</button><button type=\"button\" class=\"module-item-btn\" data-app-action=\"export_appsmith\">Appsmith JSON</button><button type=\"button\" class=\"module-item-btn\" data-app-action=\"export_budibase\">Budibase JSON</button><button type=\"button\" class=\"module-item-btn\" data-app-action=\"clear\">Clear</button></div></aside>",
    "        <section class=\"module-wb-stage-card\"><div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Layout</span><span class=\"module-wb-stage-meta\" data-app-status></span></div><div class=\"module-wb-device-switch\"><button type=\"button\" class=\"module-item-btn\" data-app-device=\"desktop\">Desktop</button><button type=\"button\" class=\"module-item-btn\" data-app-device=\"mobile\">Mobile</button></div><div class=\"module-wb-app-list\" data-app-list></div><div class=\"module-wb-preview-frame-wrap\"><div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Runtime Preview</span><span class=\"module-wb-stage-meta\">live</span></div><iframe class=\"module-wb-preview-frame\" data-app-preview sandbox=\"allow-scripts\"></iframe></div></section>",
    "        <aside class=\"module-wb-inspector-card\" data-app-inspector></aside>",
    "        ${moduleWorkbenchRenderOssStack('app_builder')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const defs = [",
    "        { id: 'table', label: 'Table', w: 220, h: 120 },",
    "        { id: 'form', label: 'Form', w: 220, h: 140 },",
    "        { id: 'chart', label: 'Chart', w: 220, h: 130 },",
    "        { id: 'button', label: 'Button', w: 140, h: 64 },",
    "        { id: 'modal', label: 'Modal', w: 260, h: 170 },",
    "        { id: 'tabs', label: 'Tabs', w: 240, h: 98 },",
    "    ];",
    "    const byId = (id) => wb.components.find((item) => safeString(item.id) === safeString(id)) || null;",
    "    const palette = shell.querySelector('[data-app-palette]');",
    "    const list = shell.querySelector('[data-app-list]');",
    "    const previewFrame = shell.querySelector('[data-app-preview]');",
    "    const status = shell.querySelector('[data-app-status]');",
    "    const inspector = shell.querySelector('[data-app-inspector]');",
    "",
    "    const renderPalette = () => { palette.innerHTML = defs.map((entry) => `<button type=\"button\" class=\"module-wb-palette-btn\" data-app-component=\"${entry.id}\"><strong>${entry.label}</strong><span>${entry.w}x${entry.h}</span></button>`).join(''); };",
    "    const renderList = () => { list.innerHTML = wb.components.length ? wb.components.map((item) => `<article class=\"module-wb-list-item${safeString(item.id) === safeString(wb.selectedId) ? ' selected' : ''}\" data-app-item-id=\"${escapeHtml(safeString(item.id))}\"><strong>${escapeHtml(safeString(item.label))}</strong><span>${escapeHtml(`${item.type} | ${item.w}x${item.h} | ${item.binding || 'no binding'}`)}</span></article>`).join('') : '<div class=\"module-wb-ghost\">Add components from the palette.</div>'; };",
    "    const renderInspector = () => {",
    "        const item = byId(wb.selectedId);",
    "        if (!item) { inspector.innerHTML = `<h4>Inspector</h4><p class=\"module-wb-mini-note\">Select a component to configure it.</p><div class=\"module-wb-metrics\"><div><span>Components</span><strong>${wb.components.length}</strong></div><div><span>Device</span><strong>${escapeHtml(wb.device)}</strong></div><div><span>Publish</span><strong>Draft</strong></div></div>`; return; }",
    "        inspector.innerHTML = `<h4>${escapeHtml(safeString(item.label))}</h4><div class=\"module-wb-field-grid\"><label class=\"module-wb-field\">Label<input type=\"text\" data-app-prop=\"label\" value=\"${escapeHtml(safeString(item.label))}\" /></label><label class=\"module-wb-field\">Type<select data-app-prop=\"type\">${defs.map((entry) => `<option value=\"${entry.id}\"${item.type === entry.id ? ' selected' : ''}>${entry.label}</option>`).join('')}</select></label><label class=\"module-wb-field\">Width<input type=\"number\" data-app-prop=\"w\" min=\"80\" value=\"${Number(item.w) || 80}\" /></label><label class=\"module-wb-field\">Height<input type=\"number\" data-app-prop=\"h\" min=\"40\" value=\"${Number(item.h) || 40}\" /></label><label class=\"module-wb-field module-wb-field-wide\">Binding<input type=\"text\" data-app-prop=\"binding\" value=\"${escapeHtml(safeString(item.binding))}\" placeholder=\"customers.list\" /></label><label class=\"module-wb-field module-wb-field-check\"><input type=\"checkbox\" data-app-prop=\"required\" ${item.required ? 'checked' : ''} />Require role gate</label></div><div class=\"module-wb-inspector-actions\"><button type=\"button\" class=\"module-item-btn\" data-app-item-action=\"duplicate\">Duplicate</button><button type=\"button\" class=\"module-item-btn\" data-app-item-action=\"delete\">Delete</button></div>`;",
    "    };",
    "    const renderProjectSelect = () => {",
    "        const select = shell.querySelector('select[data-wb-project-select=\"app_builder\"]');",
    "        if (!(select instanceof HTMLSelectElement)) return;",
    "        const rows = moduleWorkbenchProjectList('app_builder');",
    "        const current = safeString(wb.selectedProjectId);",
    "        select.innerHTML = `<option value=\"\">Select project</option>${rows.map((row) => `<option value=\"${escapeHtml(safeString(row.id))}\">${escapeHtml(`${safeString(row.name)} (${new Date(Number(row.updatedAt) || Date.now()).toLocaleString()})`)}</option>`).join('')}`;",
    "        select.value = rows.some((row) => safeString(row.id) === current) ? current : '';",
    "    };",
    "    const renderPreview = () => {",
    "        wb.previewHtml = moduleWorkbenchAppRuntimeHtml(wb);",
    "        if (previewFrame instanceof HTMLIFrameElement) {",
    "            previewFrame.srcdoc = wb.previewHtml;",
    "        }",
    "    };",
    "    const renderStatus = () => { status.textContent = `${wb.components.length} components | ${wb.device.toUpperCase()} preview`; shell.querySelectorAll('[data-app-device]').forEach((button) => button.classList.toggle('active', safeString(button.dataset.appDevice) === wb.device)); list.classList.toggle('mobile-mode', wb.device === 'mobile'); };",
    "    const renderAll = () => { renderList(); renderInspector(); renderStatus(); renderProjectSelect(); renderPreview(); };",
    "",
    "    renderPalette();",
    "    renderAll();",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        if (moduleWorkbenchHandleOssStackClick(event.target)) return;",
    "        const projectActionEl = event.target instanceof Element",
    "            ? event.target.closest('[data-wb-project-action][data-wb-project-mode=\"app_builder\"]')",
    "            : null;",
    "        if (projectActionEl) {",
    "            const action = safeString(projectActionEl.dataset.wbProjectAction).toLowerCase();",
    "            const select = shell.querySelector('select[data-wb-project-select=\"app_builder\"]');",
    "            const input = shell.querySelector('input[data-wb-project-name=\"app_builder\"]');",
    "            const selectedId = safeString(select instanceof HTMLSelectElement ? select.value : wb.selectedProjectId);",
    "            if (action === 'save') {",
    "                wb.selectedProjectId = moduleWorkbenchProjectSave('app_builder', { device: wb.device, components: wb.components }, safeString(input instanceof HTMLInputElement ? input.value : ''));",
    "                if (input instanceof HTMLInputElement) input.value = '';",
    "                renderAll();",
    "                return;",
    "            }",
    "            if (action === 'load') {",
    "                if (!selectedId) return;",
    "                const project = moduleWorkbenchProjectGet('app_builder', selectedId);",
    "                if (!project?.payload) return;",
    "                wb.device = safeString(project.payload.device) === 'mobile' ? 'mobile' : 'desktop';",
    "                wb.components = Array.isArray(project.payload.components) ? project.payload.components : [];",
    "                wb.selectedId = wb.components[0] ? safeString(wb.components[0].id) : '';",
    "                wb.selectedProjectId = selectedId;",
    "                renderAll();",
    "                return;",
    "            }",
    "            if (action === 'delete') {",
    "                if (!selectedId) return;",
    "                moduleWorkbenchProjectDelete('app_builder', selectedId);",
    "                wb.selectedProjectId = '';",
    "                renderAll();",
    "                return;",
    "            }",
    "        }",
    "        const target = event.target instanceof Element ? event.target.closest('[data-app-component], [data-app-action], [data-app-device], [data-app-item-id], [data-app-item-action]') : null;",
    "        if (!target) return;",
    "        const addType = safeString(target.dataset.appComponent);",
    "        const action = safeString(target.dataset.appAction).toLowerCase();",
    "        const device = safeString(target.dataset.appDevice);",
    "        const itemId = safeString(target.dataset.appItemId);",
    "        const itemAction = safeString(target.dataset.appItemAction).toLowerCase();",
    "        if (addType) {",
    "            const def = defs.find((entry) => entry.id === addType) || defs[0];",
    "            const id = `ui-${wb.nextId++}`;",
    "            wb.components.push({ id, type: def.id, label: def.label, w: def.w, h: def.h, binding: '', required: false });",
    "            wb.selectedId = id;",
    "            renderAll();",
    "            return;",
    "        }",
    "        if (device) { wb.device = device === 'mobile' ? 'mobile' : 'desktop'; renderStatus(); return; }",
    "        if (action) {",
    "            if (action === 'preview') renderAll();",
    "            if (action === 'publish') notifyUser('App builder draft published to internal preview.', { tone: 'success', durationMs: 1700, debugKind: 'app-builder' });",
    "            if (action === 'export') moduleWorkbenchCopyJson({ device: wb.device, components: wb.components }, 'App Builder Schema');",
    "            if (action === 'export_html') { renderPreview(); moduleWorkbenchDownloadText('thomas-app-preview.html', wb.previewHtml, 'text/html;charset=utf-8'); }",
    "            if (action === 'open_preview') {",
    "                renderPreview();",
    "                const blob = new Blob([wb.previewHtml], { type: 'text/html;charset=utf-8' });",
    "                const url = URL.createObjectURL(blob);",
    "                window.open(url, '_blank', 'noopener');",
    "                window.setTimeout(() => URL.revokeObjectURL(url), 5000);",
    "            }",
    "            if (action === 'export_appsmith') moduleWorkbenchCopyJson(moduleWorkbenchAppSchemaToAppsmith(wb), 'Appsmith Page JSON');",
    "            if (action === 'export_budibase') moduleWorkbenchCopyJson(moduleWorkbenchAppSchemaToBudibase(wb), 'Budibase App JSON');",
    "            if (action === 'clear') { wb.components = []; wb.selectedId = ''; }"
].join("\n");
