/* app.js lines 7761-8000 (split from part-008) */
export default [
    "    await streamChatResponse(payload, { userContext: newText });",
    "}",
    "",
    "/**",
    " * Regenerate an assistant response: remove it and re-stream from the",
    " * preceding user message.",
    " */",
    "async function regenerateResponse(row) {",
    "    if (isGenerating) return;",
    "",
    "    const msgId = row.id;",
    "    const histIdx = chatHistory.findIndex(m => m.id === msgId);",
    "    if (histIdx < 0) return;",
    "",
    "    // Find the preceding user message",
    "    let userIdx = -1;",
    "    for (let i = histIdx - 1; i >= 0; i--) {",
    "        if (chatHistory[i].role === 'user') {",
    "            userIdx = i;",
    "            break;",
    "        }",
    "    }",
    "    if (userIdx < 0) return; // No user message to regenerate from",
    "",
    "    const userMsg = chatHistory[userIdx];",
    "",
    "    // Truncate everything after (and including) the assistant message",
    "    chatHistory.length = histIdx;",
    "",
    "    // Remove DOM rows from the assistant message onward",
    "    let sibling = row;",
    "    while (sibling) {",
    "        const next = sibling.nextElementSibling;",
    "        if (sibling.classList.contains('message-row') || sibling.classList.contains('chat-robot-landed')) {",
    "            sibling.remove();",
    "        }",
    "        sibling = next;",
    "    }",
    "",
    "    syncActiveChatSidebarEntry();",
    "    void persistActiveChat({ quiet: true });",
    "",
    "    // Build payload and stream new response",
    "    setGeneratingState(true);",
    "    pushDebugEvent('chat', 'Regenerating assistant response');",
    "",
    "    let finalPrompt = setupPersonalitySelector.value;",
    "    if (finalPrompt === 'custom') {",
    "        finalPrompt = setupCustomPrompt.value.trim();",
    "    }",
    "    const selectedProfile = setupProviderSelector.value || modelSelector.value;",
    "    const studioChatContext = typeof moduleStudioBuildChatContext === 'function' ? moduleStudioBuildChatContext() : { enabled: false, preferredProfile: '', context: {} };",
    "    const preferredProfile = safeString(studioChatContext.preferredProfile);",
    "    const resolvedProfile = preferredProfile || selectedProfile;",
    "    if (preferredProfile && preferredProfile !== safeString(selectedProfile) && typeof applyProfileSelection === 'function') {",
    "        applyProfileSelection(preferredProfile);",
    "    }",
    "    const requestedMode = normalizeChatMode(activeChatMode) || 'auto';",
    "    const safeMode = requestedMode === 'swarm' ? 'auto' : requestedMode;",
    "    const payload = {",
    "        message: userMsg.content,",
    "        docs: [],",
    "        images: [],",
    "        session_id: sessionId,",
    "        profile: resolvedProfile,",
    "        model: resolvedProfile,",
    "        model_id: activeModelOverride || undefined,",
    "        mode: safeMode,",
    "        autonomy_level: activeAutonomyLevel,",
    "        token_economy: activeTokenEconomy,",
    "        reasoning_effort: activeReasoningEffort || undefined,",
    "        system_prompt: finalPrompt || undefined,",
    "    };",
    "    if (studioChatContext.enabled) {",
    "        payload.asset_studio_mode = 'comfy_studio';",
    "        payload.asset_studio_context = studioChatContext.context || {};",
    "    }",
    "",
    "    await streamChatResponse(payload, { userContext: userMsg.content });",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Conversation management: export, search, pin",
    "// ---------------------------------------------------------------------------",
    "",
    "/**",
    " * Export the current chat conversation as a downloadable file.",
    " * @param {'markdown'|'json'} [format='markdown']",
    " */",
    "function exportChatConversation(format = 'markdown') {",
    "    if (chatHistory.length === 0) {",
    "        showToast('Nothing to export — conversation is empty.');",
    "        return;",
    "    }",
    "",
    "    let content, filename, mimeType;",
    "    const ts = new Date().toISOString().slice(0, 10);",
    "",
    "    if (format === 'json') {",
    "        content = JSON.stringify(chatHistory, null, 2);",
    "        filename = `thomas-chat-${ts}.json`;",
    "        mimeType = 'application/json';",
    "    } else {",
    "        // Markdown format",
    "        const lines = [`# Thomas Chat Export — ${ts}\\n`];",
    "        for (const msg of chatHistory) {",
    "            const role = msg.role === 'user' ? '**You**' : '**Thomas**';",
    "            lines.push(`### ${role}`);",
    "            lines.push(msg.content || '_(empty)_');",
    "            lines.push('');",
    "        }",
    "        content = lines.join('\\n');",
    "        filename = `thomas-chat-${ts}.md`;",
    "        mimeType = 'text/markdown';",
    "    }",
    "",
    "    const blob = new Blob([content], { type: mimeType });",
    "    const url = URL.createObjectURL(blob);",
    "    const a = document.createElement('a');",
    "    a.href = url;",
    "    a.download = filename;",
    "    document.body.appendChild(a);",
    "    a.click();",
    "    setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);",
    "    showToast(`Exported as ${filename}`);",
    "}",
    "",
    "/**",
    " * In-conversation search: find messages matching a query.",
    " */",
    "let _chatSearchState = { visible: false, query: '', matches: [], current: -1 };",
    "",
    "function toggleChatSearch() {",
    "    const bar = document.getElementById('chatSearchBar');",
    "    if (!bar) return;",
    "    _chatSearchState.visible = !_chatSearchState.visible;",
    "    bar.classList.toggle('visible', _chatSearchState.visible);",
    "    if (_chatSearchState.visible) {",
    "        const input = bar.querySelector('input');",
    "        if (input) input.focus();",
    "    } else {",
    "        _clearSearchHighlights();",
    "    }",
    "}",
    "",
    "function _performChatSearch(query) {",
    "    _clearSearchHighlights();",
    "    _chatSearchState.query = query;",
    "    _chatSearchState.matches = [];",
    "    _chatSearchState.current = -1;",
    "",
    "    if (!query.trim()) {",
    "        _updateSearchCount();",
    "        return;",
    "    }",
    "",
    "    const lowerQ = query.toLowerCase();",
    "    const rows = chatMessagesInner ? chatMessagesInner.querySelectorAll('.message-row') : [];",
    "    rows.forEach(row => {",
    "        const content = row.querySelector('.message-content');",
    "        if (content && (content.textContent || '').toLowerCase().includes(lowerQ)) {",
    "            _chatSearchState.matches.push(row);",
    "        }",
    "    });",
    "",
    "    if (_chatSearchState.matches.length > 0) {",
    "        _chatSearchState.current = 0;",
    "        _highlightSearchMatch();",
    "    }",
    "    _updateSearchCount();",
    "}",
    "",
    "function _navigateSearch(dir) {",
    "    if (_chatSearchState.matches.length === 0) return;",
    "    _chatSearchState.matches[_chatSearchState.current]?.classList.remove('search-highlight');",
    "    _chatSearchState.current = (_chatSearchState.current + dir + _chatSearchState.matches.length) % _chatSearchState.matches.length;",
    "    _highlightSearchMatch();",
    "    _updateSearchCount();",
    "}",
    "",
    "function _highlightSearchMatch() {",
    "    const row = _chatSearchState.matches[_chatSearchState.current];",
    "    if (!row) return;",
    "    row.classList.add('search-highlight');",
    "    row.scrollIntoView({ behavior: 'smooth', block: 'center' });",
    "}",
    "",
    "function _clearSearchHighlights() {",
    "    if (!chatMessagesInner) return;",
    "    chatMessagesInner.querySelectorAll('.search-highlight').forEach(r => r.classList.remove('search-highlight'));",
    "}",
    "",
    "function _updateSearchCount() {",
    "    const countEl = document.querySelector('#chatSearchBar .search-count');",
    "    if (!countEl) return;",
    "    if (_chatSearchState.matches.length === 0) {",
    "        countEl.textContent = _chatSearchState.query ? 'No matches' : '';",
    "    } else {",
    "        countEl.textContent = `${_chatSearchState.current + 1} / ${_chatSearchState.matches.length}`;",
    "    }",
    "}",
    "",
    "/**",
    " * Toggle pin on a message.",
    " */",
    "function togglePinMessage(row) {",
    "    if (!row) return;",
    "    const msgId = row.id;",
    "    const entry = chatHistory.find(m => m.id === msgId);",
    "    const isPinned = row.classList.toggle('pinned');",
    "    if (entry) entry.pinned = isPinned;",
    "    void persistActiveChat({ quiet: true });",
    "    showToast(isPinned ? 'Message pinned' : 'Message unpinned');",
    "}",
    "",
    "function initChatSearch() {",
    "    const searchInput = document.getElementById('chatSearchInput');",
    "    const prevBtn = document.getElementById('chatSearchPrev');",
    "    const nextBtn = document.getElementById('chatSearchNext');",
    "    const closeBtn = document.getElementById('chatSearchClose');",
    "    if (!searchInput) return;",
    "",
    "    let _debounce = null;",
    "    searchInput.addEventListener('input', () => {",
    "        clearTimeout(_debounce);",
    "        _debounce = setTimeout(() => _performChatSearch(searchInput.value), 200);",
    "    });",
    "    searchInput.addEventListener('keydown', (e) => {",
    "        if (e.key === 'Enter') { e.preventDefault(); _navigateSearch(e.shiftKey ? -1 : 1); }",
    "        if (e.key === 'Escape') { e.preventDefault(); toggleChatSearch(); }",
    "    });",
    "    if (prevBtn) prevBtn.addEventListener('click', () => _navigateSearch(-1));",
    "    if (nextBtn) nextBtn.addEventListener('click', () => _navigateSearch(1));",
    "    if (closeBtn) closeBtn.addEventListener('click', () => toggleChatSearch());",
    "}",
    "",
    "function stopGeneration() {",
    "    if (currentAbortController) {",
    "        currentAbortController.abort();",
    "        currentAbortController = null;",
    "    }",
    "    setGeneratingState(false);",
    "}",
    "",
    "function setGeneratingState(generating) {",
    "    isGenerating = generating;",
    "    if (generating) {",
    "        sendBtn.classList.add('stop-state');",
    "        sendBtn.innerHTML = '<i class=\"ph ph-stop\"></i>';",
    "        sendBtn.disabled = false;",
    "        // Hide suggestions while generating — they're distracting",
    "        _stopSuggestionAutoScroll();",
    "        if (assistantSuggestionRail) assistantSuggestionRail.classList.add('hidden');",
    "    } else {",
    "        sendBtn.classList.remove('stop-state');",
    "        sendBtn.innerHTML = '<i class=\"ph ph-arrow-up\"></i>';",
    "        sendBtn.disabled = (composerTextarea.value.trim().length === 0 && pendingDocs.length === 0 && pendingImages.length === 0);",
    "    }",
    "    updateDebugDockSnapshot();",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  CHAT & MESSAGE RENDERING                                               ║",
    "// ║  Attachments, message bubbles, markdown, code blocks, robot alerts      ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function renderAttachmentsPreview() {",
    "    attachmentsPreview.replaceChildren();",
    "    const all = [...pendingDocs.map(d => ({ ...d, type: 'doc' })), ...pendingImages.map(i => ({ ...i, type: 'img' }))];",
    "",
    "    all.forEach((item, index) => {",
    "        const chip = document.createElement('div');",
    "        chip.className = 'attachment-chip';",
    "        const icon = document.createElement('i');",
    "        icon.className = `ph ${item.type === 'img' ? 'ph-image' : 'ph-file-text'}`;",
    "",
    "        const label = document.createElement('span');",
    "        label.textContent = String(item.name || '');",
    "",
    "        const remove = document.createElement('i');",
    "        remove.className = 'ph ph-x remove-btn';",
    "        remove.dataset.index = String(index);",
    "        remove.dataset.type = item.type;",
    "",
    "        chip.appendChild(icon);",
    "        chip.appendChild(label);",
    "        chip.appendChild(remove);",
    "        attachmentsPreview.appendChild(chip);",
    "    });",
    ""
].join("\n");
