/* app.js lines 23001-24000 */
export default [
    "            renderAll();",
    "            return;",
    "        }",
    "        if (itemId) wb.selectedId = itemId;",
    "        if (itemAction === 'duplicate') { const item = byId(wb.selectedId); if (item) { const copy = { ...item, id: `ui-${wb.nextId++}`, label: `${item.label} Copy` }; wb.components.push(copy); wb.selectedId = copy.id; } }",
    "        if (itemAction === 'delete') { wb.components = wb.components.filter((item) => safeString(item.id) !== safeString(wb.selectedId)); wb.selectedId = ''; }",
    "        renderAll();",
    "    });",
    "",
    "    if (inspector) {",
    "        inspector.addEventListener('input', (event) => {",
    "            const target = event.target;",
    "            if (!(target instanceof HTMLInputElement || target instanceof HTMLSelectElement)) return;",
    "            const item = byId(wb.selectedId);",
    "            if (!item) return;",
    "            const prop = safeString(target.dataset.appProp);",
    "            if (!prop) return;",
    "            if (prop === 'label' || prop === 'binding') item[prop] = safeString(target.value).slice(0, 120);",
    "            if (prop === 'type') item.type = safeString(target.value);",
    "            if (prop === 'w' || prop === 'h') item[prop] = moduleWorkbenchClamp(Number(target.value) || item[prop], prop === 'w' ? 80 : 40, prop === 'w' ? 900 : 700);",
    "            if (prop === 'required' && target instanceof HTMLInputElement) item.required = target.checked;",
    "            renderAll();",
    "        });",
    "    }",
    "}",
    "",
    "const MODULE_STUDIO_ASSET_TYPES = Object.freeze([",
    "    { id: 'all', label: 'All assets' },",
    "    { id: 'media', label: 'Audio / Video' },",
    "    { id: 'image', label: 'Images' },",
    "    { id: 'pixel', label: 'Pixel art' },",
    "    { id: 'note', label: 'Notes' },",
    "]);",
    "",
    "const MODULE_STUDIO_AUDIO_PRESETS = Object.freeze([",
    "    {",
    "        id: 'podcast_clean',",
    "        label: 'Podcast Clean',",
    "        description: 'Speech denoise + loudness target at -16 LUFS.',",
    "        ffmpeg: 'ffmpeg -i input.wav -af \"highpass=f=80,lowpass=f=12000,afftdn=nf=-25,loudnorm=I=-16:TP=-1.5:LRA=11\" output_podcast.wav',",
    "    },",
    "    {",
    "        id: 'voice_broadcast',",
    "        label: 'Broadcast Voice',",
    "        description: 'Tight dialog chain with compression and limiting.',",
    "        ffmpeg: 'ffmpeg -i input.wav -af \"highpass=f=90,acompressor=threshold=-18dB:ratio=3:attack=20:release=250,alimiter=limit=0.96,loudnorm=I=-14:TP=-1.0:LRA=9\" output_broadcast.wav',",
    "    },",
    "    {",
    "        id: 'cinematic_stems',",
    "        label: 'Cinematic Stems',",
    "        description: 'Dialogue/music/sfx-friendly mastering baseline.',",
    "        ffmpeg: 'ffmpeg -i input.wav -af \"highpass=f=55,lowpass=f=16000,dynaudnorm=f=150:g=9,loudnorm=I=-18:TP=-2.0:LRA=12\" output_stem.wav',",
    "    },",
    "]);",
    "",
    "const MODULE_STUDIO_RENDER_PRESETS = Object.freeze([",
    "    {",
    "        id: 'master_1080p',",
    "        label: 'Master 1080p',",
    "        description: 'H.264 archive master with high-quality audio.',",
    "        ffmpeg: 'ffmpeg -f concat -safe 0 -i clips.txt -c:v libx264 -preset slow -crf 18 -c:a aac -b:a 320k -movflags +faststart master_1080p.mp4',",
    "    },",
    "    {",
    "        id: 'social_vertical',",
    "        label: 'Social Vertical',",
    "        description: '9:16 export tuned for short-form delivery.',",
    "        ffmpeg: 'ffmpeg -f concat -safe 0 -i clips.txt -vf \"scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2\" -c:v libx264 -preset medium -crf 21 -c:a aac -b:a 192k social_vertical.mp4',",
    "    },",
    "    {",
    "        id: 'review_proxy',",
    "        label: 'Review Proxy',",
    "        description: 'Lightweight preview file for fast feedback loops.',",
    "        ffmpeg: 'ffmpeg -f concat -safe 0 -i clips.txt -vf \"scale=1280:-2\" -c:v libx264 -preset veryfast -crf 28 -c:a aac -b:a 128k review_proxy.mp4',",
    "    },",
    "]);",
    "",
    "const MODULE_STUDIO_GENERATION_TOOLS = Object.freeze([",
    "    {",
    "        id: 'comfyui',",
    "        label: 'Comfy Studio',",
    "        description: 'Node-based local image generation workflows.',",
    "        command: 'cd ComfyUI && python main.py --listen 127.0.0.1 --port 8188',",
    "    },",
    "    {",
    "        id: 'krita_ai',",
    "        label: 'Krita + AI Plugin',",
    "        description: 'Paint-over + local inpaint concept workflow.',",
    "        command: 'winget install --id KDE.Krita -e',",
    "    },",
    "    {",
    "        id: 'blender_gen',",
    "        label: 'Blender Scripted Render',",
    "        description: 'Scripted turntables and asset renders.',",
    "        command: 'blender -b scene.blend -P render_pipeline.py -a',",
    "    },",
    "]);",
    "",
    "function moduleStudioCatalogFind(catalogRaw, idRaw) {",
    "    const catalog = Array.isArray(catalogRaw) ? catalogRaw : [];",
    "    if (!catalog.length) return null;",
    "    const id = safeString(idRaw).toLowerCase();",
    "    return catalog.find((item) => safeString(item?.id).toLowerCase() === id) || catalog[0] || null;",
    "}",
    "",
    "function moduleStudioOptionMarkup(rowsRaw, selectedIdRaw) {",
    "    const rows = Array.isArray(rowsRaw) ? rowsRaw : [];",
    "    const selectedId = safeString(selectedIdRaw).toLowerCase();",
    "    return rows.map((row) => {",
    "        const id = safeString(row?.id).toLowerCase();",
    "        const label = safeString(row?.label) || id || 'option';",
    "        const selected = id === selectedId ? ' selected' : '';",
    "        return `<option value=\"${escapeHtml(id)}\"${selected}>${escapeHtml(label)}</option>`;",
    "    }).join('');",
    "}",
    "",
    "function moduleStudioEnsureWorkbenchState(wb) {",
    "    if (!wb || typeof wb !== 'object') return;",
    "    wb.assetQuery = safeString(wb.assetQuery).slice(0, 80);",
    "    const assetType = safeString(wb.assetType).toLowerCase();",
    "    wb.assetType = MODULE_STUDIO_ASSET_TYPES.some((row) => safeString(row.id) === assetType) ? assetType : 'all';",
    "    const audioPreset = safeString(wb.audioPreset).toLowerCase();",
    "    wb.audioPreset = moduleStudioCatalogFind(MODULE_STUDIO_AUDIO_PRESETS, audioPreset)?.id || MODULE_STUDIO_AUDIO_PRESETS[0].id;",
    "    const renderPreset = safeString(wb.renderPreset).toLowerCase();",
    "    wb.renderPreset = moduleStudioCatalogFind(MODULE_STUDIO_RENDER_PRESETS, renderPreset)?.id || MODULE_STUDIO_RENDER_PRESETS[0].id;",
    "    const generationTool = safeString(wb.generationTool).toLowerCase();",
    "    wb.generationTool = moduleStudioCatalogFind(MODULE_STUDIO_GENERATION_TOOLS, generationTool)?.id || MODULE_STUDIO_GENERATION_TOOLS[0].id;",
    "    wb.generationPrompt = safeString(wb.generationPrompt).slice(0, 220);",
    "    if (!Array.isArray(wb.batchQueue)) wb.batchQueue = [];",
    "    wb.batchQueue = wb.batchQueue",
    "        .filter((item) => item && typeof item === 'object')",
    "        .slice(0, 24);",
    "}",
    "",
    "function moduleStudioFilterAssets(wb) {",
    "    const rows = Array.isArray(wb?.assets) ? wb.assets : [];",
    "    const query = safeString(wb?.assetQuery).toLowerCase().trim();",
    "    const type = safeString(wb?.assetType).toLowerCase() || 'all';",
    "    return rows.filter((asset) => {",
    "        const kind = moduleStudioAssetKind(asset);",
    "        if (type !== 'all' && kind !== type) return false;",
    "        if (!query) return true;",
    "        const haystack = `${safeString(asset?.name)} ${safeString(asset?.mime)} ${kind}`.toLowerCase();",
    "        return haystack.includes(query);",
    "    });",
    "}",
    "",
    "function moduleStudioAssetCounts(wb) {",
    "    const assets = Array.isArray(wb?.assets) ? wb.assets : [];",
    "    const counts = { total: assets.length, media: 0, image: 0, pixel: 0, note: 0 };",
    "    assets.forEach((asset) => {",
    "        const kind = moduleStudioAssetKind(asset);",
    "        if (kind === 'media' || kind === 'image' || kind === 'pixel' || kind === 'note') {",
    "            counts[kind] += 1;",
    "        }",
    "    });",
    "    return counts;",
    "}",
    "",
    "function moduleStudioAudioPresetCommand(wb) {",
    "    const preset = moduleStudioCatalogFind(MODULE_STUDIO_AUDIO_PRESETS, wb?.audioPreset);",
    "    return safeString(preset?.ffmpeg) || MODULE_STUDIO_AUDIO_PRESETS[0].ffmpeg;",
    "}",
    "",
    "function moduleStudioRenderPresetCommand(wb) {",
    "    const preset = moduleStudioCatalogFind(MODULE_STUDIO_RENDER_PRESETS, wb?.renderPreset);",
    "    return safeString(preset?.ffmpeg) || MODULE_STUDIO_RENDER_PRESETS[0].ffmpeg;",
    "}",
    "",
    "function moduleStudioGenerationCommand(wb) {",
    "    const tool = moduleStudioCatalogFind(MODULE_STUDIO_GENERATION_TOOLS, wb?.generationTool);",
    "    const prompt = safeString(wb?.generationPrompt) || 'clean robot office concept, isometric, pixel style';",
    "    if (safeString(tool?.id) === 'comfyui') {",
    "        return [",
    "            '# 1) Start Comfy Studio (ComfyUI backend)',",
    "            safeString(tool?.command),",
    "            '# 2) Use this prompt in your workflow',",
    "            prompt,",
    "        ].join('\\n');",
    "    }",
    "    if (safeString(tool?.id) === 'blender_gen') {",
    "        return [",
    "            '# Edit render_pipeline.py to read PROMPT env',",
    "            `set PROMPT=${prompt.replace(/\\n/g, ' ')}`,",
    "            safeString(tool?.command),",
    "        ].join('\\n');",
    "    }",
    "    return safeString(tool?.command) || 'winget install --id KDE.Krita -e';",
    "}",
    "",
    "function moduleStudioQueueRenderJob(wb, assetRaw = null) {",
    "    if (!wb || typeof wb !== 'object') return null;",
    "    moduleStudioEnsureWorkbenchState(wb);",
    "    const preset = moduleStudioCatalogFind(MODULE_STUDIO_RENDER_PRESETS, wb.renderPreset);",
    "    const asset = assetRaw && typeof assetRaw === 'object' ? assetRaw : null;",
    "    const target = safeString(asset?.name) || (wb.timeline?.length ? `Timeline (${wb.timeline.length} clips)` : 'Timeline');",
    "    const row = {",
    "        id: `render-${Date.now()}-${Math.round(Math.random() * 10000)}`,",
    "        name: target,",
    "        preset: safeString(preset?.label) || 'Master 1080p',",
    "        status: 'queued',",
    "        eta: 'pending',",
    "        at: moduleWorkbenchTimeStamp(),",
    "    };",
    "    wb.batchQueue.unshift(row);",
    "    wb.batchQueue = wb.batchQueue.slice(0, 24);",
    "    return row;",
    "}",
    "",
    "function moduleStudioDuration(totalRaw) {",
    "    const total = Number(totalRaw) || 0;",
    "    const mins = Math.floor(total / 60);",
    "    const secs = Math.floor(total % 60);",
    "    return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;",
    "}",
    "",
    "function moduleWorkbenchStudioTimelineToOtio(wb) {",
    "    const timeline = Array.isArray(wb?.timeline) ? wb.timeline : [];",
    "    return {",
    "        OTIO_SCHEMA: 'Timeline.1',",
    "        name: 'Thomas Timeline Export',",
    "        tracks: {",
    "            OTIO_SCHEMA: 'Stack.1',",
    "            children: [",
    "                {",
    "                    OTIO_SCHEMA: 'Track.1',",
    "                    kind: 'Video',",
    "                    children: timeline.map((clip, index) => ({",
    "                        OTIO_SCHEMA: 'Clip.2',",
    "                        name: safeString(clip.name) || `Clip ${index + 1}`,",
    "                        source_range: {",
    "                            OTIO_SCHEMA: 'TimeRange.1',",
    "                            start_time: {",
    "                                OTIO_SCHEMA: 'RationalTime.1',",
    "                                value: Number(clip.start) || 0,",
    "                                rate: 1,",
    "                            },",
    "                            duration: {",
    "                                OTIO_SCHEMA: 'RationalTime.1',",
    "                                value: Number(clip.duration) || 1,",
    "                                rate: 1,",
    "                            },",
    "                        },",
    "                        metadata: {},",
    "                    })),",
    "                },",
    "            ],",
    "        },",
    "    };",
    "}",
    "",
    "function moduleWorkbenchStudioFfmpegConcatCommand(wb) {",
    "    const assets = Array.isArray(wb?.assets) ? wb.assets : [];",
    "    const media = assets.filter((asset) => Boolean(safeString(asset.url))).slice(0, 8);",
    "    if (!media.length) {",
    "        return 'ffmpeg -f concat -safe 0 -i clips.txt -c copy output.mp4';",
    "    }",
    "    const lines = media.map((asset) => `file '${safeString(asset.name).replace(/'/g, \"\\\\'\")}'`);",
    "    return [",
    "        '# 1) Save this as clips.txt',",
    "        ...lines,",
    "        '# 2) Run concat',",
    "        'ffmpeg -f concat -safe 0 -i clips.txt -c:v libx264 -c:a aac -shortest output.mp4',",
    "    ].join('\\n');",
    "}",
    "",
    "const MODULE_STUDIO_FORGE_SIZE = 16;",
    "const MODULE_STUDIO_FORGE_SCALE = 14;",
    "const MODULE_STUDIO_FORGE_PALETTE = [",
    "    '#0f1a2b',",
    "    '#1e3351',",
    "    '#2f4e73',",
    "    '#5f8cc0',",
    "    '#89b8f0',",
    "    '#91e1d6',",
    "    '#f2c27f',",
    "    '#f08d7f',",
    "    '#f5f8ff',",
    "];",
    "",
    "function moduleStudioAssetKind(assetRaw) {",
    "    const asset = assetRaw && typeof assetRaw === 'object' ? assetRaw : {};",
    "    const explicit = safeString(asset.kind).toLowerCase();",
    "    if (explicit === 'pixel' || explicit === 'image' || explicit === 'media') return explicit;",
    "    if (Array.isArray(asset.pixelData) && asset.pixelData.length) return 'pixel';",
    "    const mime = safeString(asset.mime).toLowerCase();",
    "    if (mime.startsWith('image/')) return 'image';",
    "    if (mime.startsWith('audio/') || mime.startsWith('video/')) return 'media';",
    "    return safeString(asset.url) ? 'media' : 'note';",
    "}",
    "",
    "function moduleStudioAssetKindLabel(assetRaw) {",
    "    const kind = moduleStudioAssetKind(assetRaw);",
    "    if (kind === 'pixel') return 'pixel';",
    "    if (kind === 'image') return 'image';",
    "    if (kind === 'media') return 'media';",
    "    return 'note';",
    "}",
    "",
    "function moduleStudioCanWaveLoad(assetRaw) {",
    "    const asset = assetRaw && typeof assetRaw === 'object' ? assetRaw : {};",
    "    if (!safeString(asset.url)) return false;",
    "    if (moduleStudioAssetKind(asset) !== 'media') return false;",
    "    const mime = safeString(asset.mime).toLowerCase();",
    "    if (!mime) return true;",
    "    return mime.startsWith('audio/') || mime.startsWith('video/');",
    "}",
    "",
    "function moduleStudioPixelBlank(sizeRaw = MODULE_STUDIO_FORGE_SIZE) {",
    "    const size = moduleWorkbenchClamp(Number(sizeRaw) || MODULE_STUDIO_FORGE_SIZE, 8, 32);",
    "    return Array.from({ length: size * size }, () => '');",
    "}",
    "",
    "function moduleStudioPixelNormalize(pixelsRaw, sizeRaw = MODULE_STUDIO_FORGE_SIZE) {",
    "    const size = moduleWorkbenchClamp(Number(sizeRaw) || MODULE_STUDIO_FORGE_SIZE, 8, 32);",
    "    const pixels = Array.isArray(pixelsRaw) ? pixelsRaw : [];",
    "    const total = size * size;",
    "    const next = Array.from({ length: total }, (_entry, index) => {",
    "        const value = safeString(pixels[index]).toLowerCase();",
    "        return /^#[0-9a-f]{6}$/.test(value) ? value : '';",
    "    });",
    "    return next;",
    "}",
    "",
    "function moduleStudioSeededRandom(seedRaw) {",
    "    let state = (Number(seedRaw) >>> 0) || 1;",
    "    return () => {",
    "        state = (Math.imul(1664525, state) + 1013904223) >>> 0;",
    "        return state / 4294967296;",
    "    };",
    "}",
    "",
    "function moduleStudioPixelSet(pixels, size, xRaw, yRaw, colorRaw) {",
    "    const x = moduleWorkbenchClamp(Math.floor(Number(xRaw) || 0), 0, size - 1);",
    "    const y = moduleWorkbenchClamp(Math.floor(Number(yRaw) || 0), 0, size - 1);",
    "    const index = (y * size) + x;",
    "    if (index < 0 || index >= pixels.length) return;",
    "    const color = safeString(colorRaw).toLowerCase();",
    "    pixels[index] = /^#[0-9a-f]{6}$/.test(color) ? color : '';",
    "}",
    "",
    "function moduleStudioGeneratePixelPrompt(promptRaw, sizeRaw = MODULE_STUDIO_FORGE_SIZE, paletteRaw = MODULE_STUDIO_FORGE_PALETTE) {",
    "    const size = moduleWorkbenchClamp(Number(sizeRaw) || MODULE_STUDIO_FORGE_SIZE, 8, 32);",
    "    const palette = Array.isArray(paletteRaw) && paletteRaw.length ? paletteRaw : MODULE_STUDIO_FORGE_PALETTE;",
    "    const prompt = safeString(promptRaw).toLowerCase();",
    "    const pixels = moduleStudioPixelBlank(size);",
    "    const seed = officeStableHash(`${prompt}|${size}`) || Date.now();",
    "    const rand = moduleStudioSeededRandom(seed);",
    "    const center = Math.floor(size / 2);",
    "    const dark = safeString(palette[1] || palette[0] || '#1e3351');",
    "    const body = safeString(palette[3] || palette[2] || '#5f8cc0');",
    "    const accent = safeString(palette[6] || palette[5] || '#f2c27f');",
    "    const highlight = safeString(palette[8] || palette[4] || '#f5f8ff');",
    "    const alt = safeString(palette[5] || palette[4] || '#91e1d6');",
    "",
    "    const paintMirror = (xRaw, yRaw, color) => {",
    "        const x = moduleWorkbenchClamp(Math.floor(Number(xRaw) || 0), 0, size - 1);",
    "        const y = moduleWorkbenchClamp(Math.floor(Number(yRaw) || 0), 0, size - 1);",
    "        moduleStudioPixelSet(pixels, size, x, y, color);",
    "        moduleStudioPixelSet(pixels, size, (size - 1) - x, y, color);",
    "    };",
    "    const fillMirrorRect = (x0Raw, y0Raw, widthRaw, heightRaw, color) => {",
    "        const x0 = moduleWorkbenchClamp(Math.floor(Number(x0Raw) || 0), 0, size - 1);",
    "        const y0 = moduleWorkbenchClamp(Math.floor(Number(y0Raw) || 0), 0, size - 1);",
    "        const width = Math.max(1, Math.floor(Number(widthRaw) || 1));",
    "        const height = Math.max(1, Math.floor(Number(heightRaw) || 1));",
    "        for (let y = y0; y < y0 + height && y < size; y += 1) {",
    "            for (let x = x0; x < x0 + width && x <= center; x += 1) {",
    "                paintMirror(x, y, color);",
    "            }",
    "        }",
    "    };",
    "",
    "    const bodyHalf = Math.max(2, Math.floor(size * (0.16 + (rand() * 0.12))));",
    "    const bodyHeight = Math.max(4, Math.floor(size * (0.34 + (rand() * 0.2))));",
    "    const bodyTop = moduleWorkbenchClamp(Math.floor(size * 0.36), 1, size - 3);",
    "    fillMirrorRect(center - bodyHalf, bodyTop, bodyHalf + 1, bodyHeight, body);",
    "",
    "    const headHalf = Math.max(2, bodyHalf - 1);",
    "    const headHeight = Math.max(2, Math.floor(size * (0.16 + (rand() * 0.08))));",
    "    const headTop = moduleWorkbenchClamp(bodyTop - headHeight - 1, 0, size - 3);",
    "    fillMirrorRect(center - headHalf, headTop, headHalf + 1, headHeight, dark);",
    "",
    "    const eyeY = moduleWorkbenchClamp(headTop + Math.floor(headHeight / 2), 0, size - 1);",
    "    paintMirror(center - 1, eyeY, highlight);",
    "    paintMirror(center - 2, eyeY, alt);",
    "    paintMirror(center - 1, eyeY + 1, highlight);",
    "",
    "    const legY = moduleWorkbenchClamp(bodyTop + bodyHeight, 1, size - 1);",
    "    paintMirror(center - 1, legY, dark);",
    "    paintMirror(center - 2, legY, dark);",
    "",
    "    if (/(desk|table|bench|counter|workspace)/.test(prompt)) {",
    "        const top = moduleWorkbenchClamp(Math.floor(size * 0.68), 0, size - 1);",
    "        for (let x = 1; x < size - 1; x += 1) {",
    "            moduleStudioPixelSet(pixels, size, x, top, accent);",
    "            if (x % 3 === 0) moduleStudioPixelSet(pixels, size, x, top + 1, dark);",
    "        }",
    "    }",
    "    if (/(server|rack|datacenter|compute|gpu)/.test(prompt)) {",
    "        const rackTop = moduleWorkbenchClamp(Math.floor(size * 0.24), 0, size - 1);",
    "        const rackBottom = moduleWorkbenchClamp(Math.floor(size * 0.82), 0, size - 1);",
    "        for (let y = rackTop; y <= rackBottom; y += 1) {",
    "            paintMirror(center - 4, y, dark);",
    "            if (y % 3 === 0) paintMirror(center - 3, y, accent);",
    "        }",
    "    }",
    "    if (/(plant|green|nature|tree|garden)/.test(prompt)) {",
    "        const leafY = moduleWorkbenchClamp(Math.floor(size * 0.18), 0, size - 1);",
    "        const leaf = safeString(palette[5] || palette[4] || '#91e1d6');",
    "        paintMirror(center - 2, leafY, leaf);",
    "        paintMirror(center - 3, leafY + 1, leaf);",
    "        paintMirror(center - 1, leafY + 1, leaf);",
    "    }",
    "    if (/(warning|danger|hazard|fire)/.test(prompt)) {",
    "        const hot = safeString(palette[7] || '#f08d7f');",
    "        for (let y = Math.floor(size * 0.58); y < size; y += 1) {",
    "            if (y % 2 === 0) {",
    "                paintMirror(center - 2, y, hot);",
    "                paintMirror(center - 4, y, hot);",
    "            }",
    "        }",
    "    }",
    "    if (/(goal|star|trophy|win)/.test(prompt)) {",
    "        const trophy = safeString(palette[6] || '#f2c27f');",
    "        const y = moduleWorkbenchClamp(Math.floor(size * 0.25), 0, size - 1);",
    "        paintMirror(center - 1, y, trophy);",
    "        paintMirror(center - 2, y + 1, trophy);",
    "        paintMirror(center - 1, y + 2, trophy);",
    "    }",
    "    const sparkleCount = Math.max(4, Math.floor(size * 0.6));",
    "    for (let i = 0; i < sparkleCount; i += 1) {",
    "        const x = Math.floor(rand() * (center + 1));",
    "        const y = Math.floor(rand() * size);",
    "        const color = rand() > 0.6 ? accent : highlight;",
    "        paintMirror(x, y, color);",
    "    }",
    "    return pixels;",
    "}",
    "",
    "function moduleStudioEnsureForgeState(wb) {",
    "    if (!wb || typeof wb !== 'object') return null;",
    "    if (!wb.forge || typeof wb.forge !== 'object') wb.forge = {};",
    "    const forge = wb.forge;",
    "    forge.size = MODULE_STUDIO_FORGE_SIZE;",
    "    forge.scale = MODULE_STUDIO_FORGE_SCALE;",
    "    if (!Array.isArray(forge.palette) || !forge.palette.length) {",
    "        forge.palette = [...MODULE_STUDIO_FORGE_PALETTE];",
    "    } else {",
    "        forge.palette = forge.palette",
    "            .map((color) => safeString(color).toLowerCase())",
    "            .filter((color) => /^#[0-9a-f]{6}$/.test(color))",
    "            .slice(0, 18);",
    "        if (!forge.palette.length) forge.palette = [...MODULE_STUDIO_FORGE_PALETTE];",
    "    }",
    "    forge.selectedColor = safeString(forge.selectedColor).toLowerCase();",
    "    if (!forge.palette.includes(forge.selectedColor)) {",
    "        forge.selectedColor = safeString(forge.palette[3] || forge.palette[0] || '#5f8cc0');",
    "    }",
    "    const tool = safeString(forge.tool).toLowerCase();",
    "    forge.tool = tool === 'erase' ? 'erase' : 'paint';",
    "    forge.prompt = safeString(forge.prompt).slice(0, 180);",
    "    forge.draftName = safeString(forge.draftName).slice(0, 96) || `Pixel ${Math.max(1, Number(wb.nextId) || 1)}`;",
    "    forge.draftPixels = moduleStudioPixelNormalize(forge.draftPixels, forge.size);",
    "    if (!forge.draftPixels.some(Boolean)) {",
    "        forge.draftPixels = moduleStudioGeneratePixelPrompt(forge.prompt || 'robot helper', forge.size, forge.palette);",
    "    }",
    "    forge.editingAssetId = safeString(forge.editingAssetId);",
    "    forge.syncedSelectionId = safeString(forge.syncedSelectionId);",
    "    return forge;",
    "}",
    "",
    "function moduleStudioPixelsToDataUrl(pixelsRaw, sizeRaw = MODULE_STUDIO_FORGE_SIZE, scaleRaw = 1) {",
    "    const size = moduleWorkbenchClamp(Number(sizeRaw) || MODULE_STUDIO_FORGE_SIZE, 8, 64);",
    "    const scale = moduleWorkbenchClamp(Number(scaleRaw) || 1, 1, 64);",
    "    const pixels = moduleStudioPixelNormalize(pixelsRaw, size);",
    "    const canvas = document.createElement('canvas');",
    "    canvas.width = size * scale;",
    "    canvas.height = size * scale;",
    "    const ctx = canvas.getContext('2d');",
    "    if (!ctx) return '';",
    "    ctx.clearRect(0, 0, canvas.width, canvas.height);",
    "    for (let y = 0; y < size; y += 1) {",
    "        for (let x = 0; x < size; x += 1) {",
    "            const color = safeString(pixels[(y * size) + x]).toLowerCase();",
    "            if (!/^#[0-9a-f]{6}$/.test(color)) continue;",
    "            ctx.fillStyle = color;",
    "            ctx.fillRect(x * scale, y * scale, scale, scale);",
    "        }",
    "    }",
    "    return canvas.toDataURL('image/png');",
    "}",
    "",
    "function moduleStudioAssetPreviewUrl(assetRaw) {",
    "    const asset = assetRaw && typeof assetRaw === 'object' ? assetRaw : null;",
    "    if (!asset) return '';",
    "    if (moduleStudioAssetKind(asset) === 'pixel') {",
    "        const size = moduleWorkbenchClamp(Number(asset.pixelSize) || MODULE_STUDIO_FORGE_SIZE, 8, 64);",
    "        const pixels = moduleStudioPixelNormalize(asset.pixelData, size);",
    "        const signature = `${size}:${pixels.join('|')}`;",
    "        if (safeString(asset.pixelPreviewSignature) !== signature) {",
    "            asset.pixelPreviewSignature = signature;",
    "            asset.pixelPreviewUrl = moduleStudioPixelsToDataUrl(pixels, size, 1);",
    "        }",
    "        return safeString(asset.pixelPreviewUrl);",
    "    }",
    "    return safeString(asset.url);",
    "}",
    "",
    "function moduleStudioLoadForgeFromPixelAsset(wb, assetRaw) {",
    "    const forge = moduleStudioEnsureForgeState(wb);",
    "    const asset = assetRaw && typeof assetRaw === 'object' ? assetRaw : null;",
    "    if (!forge || !asset || moduleStudioAssetKind(asset) !== 'pixel') return false;",
    "    forge.draftName = safeString(asset.name).slice(0, 96) || forge.draftName;",
    "    forge.prompt = safeString(asset.prompt).slice(0, 180);",
    "    forge.draftPixels = moduleStudioPixelNormalize(asset.pixelData, forge.size);",
    "    forge.editingAssetId = safeString(asset.id);",
    "    return true;",
    "}",
    "",
    "function moduleStudioSyncForgeWithSelection(wb, assetRaw) {",
    "    const forge = moduleStudioEnsureForgeState(wb);",
    "    if (!forge) return;",
    "    const selectedId = safeString(assetRaw?.id);",
    "    if (selectedId === safeString(forge.syncedSelectionId)) return;",
    "    forge.syncedSelectionId = selectedId;",
    "    moduleStudioLoadForgeFromPixelAsset(wb, assetRaw);",
    "}",
    "",
    "function moduleStudioSaveForgeAsset(wb, preferredIdRaw = '') {",
    "    if (!wb || typeof wb !== 'object') return null;",
    "    if (!Array.isArray(wb.assets)) wb.assets = [];",
    "    const forge = moduleStudioEnsureForgeState(wb);",
    "    if (!forge) return null;",
    "    const preferredId = safeString(preferredIdRaw);",
    "    const targetId = preferredId || safeString(forge.editingAssetId);",
    "    let target = wb.assets.find((item) => safeString(item?.id) === targetId) || null;",
    "    if (target && moduleStudioAssetKind(target) !== 'pixel') target = null;",
    "    const pixelData = moduleStudioPixelNormalize(forge.draftPixels, forge.size);",
    "    if (!pixelData.some(Boolean)) return null;",
    "    if (!target) {",
    "        target = {",
    "            id: `asset-${Math.max(1, Number(wb.nextId) || 1)}`,",
    "            duration: 6,",
    "        };",
    "        wb.nextId = Math.max(1, Number(wb.nextId) || 1) + 1;",
    "        wb.assets.unshift(target);",
    "    }",
    "    target.name = safeString(forge.draftName).slice(0, 96) || `Pixel ${safeString(target.id)}`;",
    "    target.duration = moduleWorkbenchClamp(Number(target.duration) || 6, 0.5, 900);",
    "    target.kind = 'pixel';",
    "    target.mime = 'image/png';",
    "    target.pixelSize = forge.size;",
    "    target.pixelData = pixelData;",
    "    target.prompt = safeString(forge.prompt).slice(0, 180);",
    "    target.pixelPreviewSignature = '';",
    "    target.pixelPreviewUrl = '';",
    "    target.url = moduleStudioAssetPreviewUrl(target);",
    "    wb.selectedAssetId = safeString(target.id);",
    "    forge.editingAssetId = safeString(target.id);",
    "    forge.syncedSelectionId = safeString(target.id);",
    "    return target;",
    "}",
    "",
    "function moduleStudioDownloadDataUrl(filenameRaw, dataUrlRaw) {",
    "    const filename = safeString(filenameRaw) || 'asset.png';",
    "    const dataUrl = safeString(dataUrlRaw);",
    "    if (!dataUrl.startsWith('data:image/')) return;",
    "    const anchor = document.createElement('a');",
    "    anchor.href = dataUrl;",
    "    anchor.download = filename;",
    "    anchor.rel = 'noopener';",
    "    document.body.appendChild(anchor);",
    "    anchor.click();",
    "    window.setTimeout(() => {",
    "        anchor.remove();",
    "    }, 80);",
    "}",
    "",
    "function moduleStudioForgeMarkup(wb) {",
    "    const forge = moduleStudioEnsureForgeState(wb);",
    "    if (!forge) return '';",
    "    return `",
    "        <section class=\"module-wb-forge-card\" data-studio-forge>",
    "            <h4>Pixel Forge</h4>",
    "            <label class=\"module-wb-field module-wb-field-wide\">Prompt",
    "                <input type=\"text\" data-studio-forge-prompt value=\"${escapeHtml(forge.prompt)}\" placeholder=\"robot desk terminal, blue glow\" />",
    "            </label>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-forge-action=\"generate\">Generate Local</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-forge-action=\"clear\">Clear</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-forge-action=\"mirror\">Mirror</button>",
    "            </div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-forge-tool=\"paint\">Paint</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-forge-tool=\"erase\">Erase</button>",
    "            </div>",
    "            <div class=\"module-wb-color-palette\" data-studio-forge-palette></div>",
    "            <canvas class=\"module-wb-pixel-canvas\" data-studio-forge-canvas width=\"${forge.size * forge.scale}\" height=\"${forge.size * forge.scale}\" aria-label=\"Pixel editor canvas\"></canvas>",
    "            <label class=\"module-wb-field module-wb-field-wide\">Asset Name",
    "                <input type=\"text\" data-studio-forge-name value=\"${escapeHtml(forge.draftName)}\" placeholder=\"office-asset\" />",
    "            </label>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-forge-action=\"save\">Save Pixel Asset</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-studio-forge-action=\"export\">Export PNG</button>",
    "            </div>",
    "            <p class=\"module-wb-mini-note\" data-studio-forge-meta></p>",
    "        </section>",
    "    `;",
    "}",
    "",
    "function moduleStudioRenderAssetPreview(stageEl, assetRaw) {",
    "    if (!(stageEl instanceof HTMLElement)) return;",
    "    const asset = assetRaw && typeof assetRaw === 'object' ? assetRaw : null;",
    "    const previewUrl = moduleStudioAssetPreviewUrl(asset);",
    "    stageEl.replaceChildren();",
    "    if (!asset || !previewUrl) {",
    "        const ghost = document.createElement('div');",
    "        ghost.className = 'module-wb-ghost';",
    "        ghost.textContent = 'Select an image or pixel asset to preview.';",
    "        stageEl.appendChild(ghost);",
    "        return;",
    "    }",
    "    const img = document.createElement('img');",
    "    img.src = previewUrl;",
    "    img.alt = safeString(asset.name) || 'Asset preview';",
    "    img.loading = 'lazy';",
    "    stageEl.appendChild(img);",
    "}",
    "",
    "function moduleStudioBindForge(shell, wb, { onChanged = null, onLog = null } = {}) {",
    "    const root = shell?.querySelector('[data-studio-forge]');",
    "    if (!(root instanceof HTMLElement)) {",
    "        return { render: () => {} };",
    "    }",
    "    const promptInput = root.querySelector('[data-studio-forge-prompt]');",
    "    const nameInput = root.querySelector('[data-studio-forge-name]');",
    "    const paletteEl = root.querySelector('[data-studio-forge-palette]');",
    "    const canvas = root.querySelector('[data-studio-forge-canvas]');",
    "    const metaEl = root.querySelector('[data-studio-forge-meta]');",
    "    const ctx = canvas instanceof HTMLCanvasElement ? canvas.getContext('2d') : null;",
    "    if (!(paletteEl instanceof HTMLElement) || !(canvas instanceof HTMLCanvasElement) || !ctx) {",
    "        return { render: () => {} };",
    "    }",
    "    const callChanged = () => {",
    "        if (typeof onChanged === 'function') onChanged();",
    "    };",
    "    const pushLog = (messageRaw, toneRaw = 'ok') => {",
    "        if (typeof onLog === 'function') onLog(messageRaw, toneRaw);",
    "    };",
    "    const activeForge = () => moduleStudioEnsureForgeState(wb);",
    "    const paintCell = (xRaw, yRaw) => {",
    "        const forge = activeForge();",
    "        if (!forge) return false;",
    "        const size = forge.size;",
    "        const x = moduleWorkbenchClamp(Math.floor(Number(xRaw) || 0), 0, size - 1);",
    "        const y = moduleWorkbenchClamp(Math.floor(Number(yRaw) || 0), 0, size - 1);",
    "        const index = (y * size) + x;",
    "        const next = forge.tool === 'erase' ? '' : forge.selectedColor;",
    "        if (safeString(forge.draftPixels[index]) === safeString(next)) return false;",
    "        forge.draftPixels[index] = next;",
    "        forge.syncedSelectionId = safeString(wb.selectedAssetId);",
    "        return true;",
    "    };",
    "    const eventToCell = (event) => {",
    "        const forge = activeForge();",
    "        if (!forge) return null;",
    "        const rect = canvas.getBoundingClientRect();",
    "        if (!rect.width || !rect.height) return null;",
    "        const px = ((event.clientX - rect.left) / rect.width) * forge.size;",
    "        const py = ((event.clientY - rect.top) / rect.height) * forge.size;",
    "        return {",
    "            x: moduleWorkbenchClamp(Math.floor(px), 0, forge.size - 1),",
    "            y: moduleWorkbenchClamp(Math.floor(py), 0, forge.size - 1),",
    "        };",
    "    };",
    "    const mirrorDraft = () => {",
    "        const forge = activeForge();",
    "        if (!forge) return;",
    "        const next = moduleStudioPixelBlank(forge.size);",
    "        for (let y = 0; y < forge.size; y += 1) {",
    "            for (let x = 0; x < forge.size; x += 1) {",
    "                const source = (y * forge.size) + x;",
    "                const target = (y * forge.size) + ((forge.size - 1) - x);",
    "                next[target] = safeString(forge.draftPixels[source]).toLowerCase();",
    "            }",
    "        }",
    "        forge.draftPixels = next;",
    "        forge.syncedSelectionId = safeString(wb.selectedAssetId);",
    "    };",
    "    const renderCanvas = () => {",
    "        const forge = activeForge();",
    "        if (!forge) return;",
    "        const size = forge.size;",
    "        const scale = forge.scale;",
    "        const targetSize = size * scale;",
    "        if (canvas.width !== targetSize || canvas.height !== targetSize) {",
    "            canvas.width = targetSize;",
    "            canvas.height = targetSize;",
    "        }",
    "        ctx.clearRect(0, 0, canvas.width, canvas.height);",
    "        for (let y = 0; y < size; y += 1) {",
    "            for (let x = 0; x < size; x += 1) {",
    "                const checker = (x + y) % 2 === 0 ? 'rgba(255,255,255,0.035)' : 'rgba(11,18,28,0.42)';",
    "                ctx.fillStyle = checker;",
    "                ctx.fillRect(x * scale, y * scale, scale, scale);",
    "                const color = safeString(forge.draftPixels[(y * size) + x]).toLowerCase();",
    "                if (!/^#[0-9a-f]{6}$/.test(color)) continue;",
    "                ctx.fillStyle = color;",
    "                ctx.fillRect(x * scale, y * scale, scale, scale);",
    "            }",
    "        }",
    "        ctx.strokeStyle = 'rgba(160, 193, 238, 0.16)';",
    "        ctx.lineWidth = 1;",
    "        for (let x = 0; x <= size; x += 1) {",
    "            const lineX = Math.round((x * scale) + 0.5);",
    "            ctx.beginPath();",
    "            ctx.moveTo(lineX, 0);",
    "            ctx.lineTo(lineX, canvas.height);",
    "            ctx.stroke();",
    "        }",
    "        for (let y = 0; y <= size; y += 1) {",
    "            const lineY = Math.round((y * scale) + 0.5);",
    "            ctx.beginPath();",
    "            ctx.moveTo(0, lineY);",
    "            ctx.lineTo(canvas.width, lineY);",
    "            ctx.stroke();",
    "        }",
    "    };",
    "    const renderPalette = () => {",
    "        const forge = activeForge();",
    "        if (!forge) return;",
    "        paletteEl.innerHTML = forge.palette.map((color) => `",
    "            <button",
    "                type=\"button\"",
    "                class=\"module-wb-color-chip${safeString(color) === safeString(forge.selectedColor) ? ' active' : ''}\"",
    "                data-studio-forge-color=\"${escapeHtml(safeString(color))}\"",
    "                style=\"--chip:${escapeHtml(safeString(color))};\"",
    "                aria-label=\"Pick ${escapeHtml(safeString(color))}\">",
    "            </button>",
    "        `).join('');",
    "        root.querySelectorAll('[data-studio-forge-tool]').forEach((btn) => {",
    "            const tool = safeString(btn.getAttribute('data-studio-forge-tool')).toLowerCase();",
    "            btn.classList.toggle('active', tool === safeString(forge.tool));",
    "        });",
    "    };",
    "    const render = () => {",
    "        const forge = activeForge();",
    "        if (!forge) return;",
    "        if (promptInput instanceof HTMLInputElement && document.activeElement !== promptInput) {",
    "            promptInput.value = forge.prompt;",
    "        }",
    "        if (nameInput instanceof HTMLInputElement && document.activeElement !== nameInput) {",
    "            nameInput.value = forge.draftName;",
    "        }",
    "        if (metaEl instanceof HTMLElement) {",
    "            const source = safeString(forge.editingAssetId) ? `editing ${safeString(forge.editingAssetId)}` : 'new draft';",
    "            metaEl.textContent = `${forge.size}x${forge.size} | ${forge.tool} | ${source}`;",
    "        }",
    "        renderPalette();",
    "        renderCanvas();",
].join("\n");
