/* split from part-027.js */
export default [
    "                                    <strong>Stream embed blocked.</strong>",
    "                                    <p>Target denies iframe embedding. Use Open Stream, or enable framing on the Unreal stream host.</p>",
    "                                </div>",
    "                            </div>",
    "                        </div>",
    "                    </div>",
    "                    <div class=\"module-wb-gs-terminal\">",
    "                        <div class=\"module-wb-gs-terminal-head\">Output Log</div>",
    "                        <div class=\"module-wb-log-list\" data-game-logs></div>",
    "                    </div>",
    "                </section>",
    "            </div>",
    "        </section>",
    "        <aside class=\"module-wb-inspector-card module-wb-gs-right\">",
    "            <h4>Session Stats</h4>",
    "            <div class=\"module-wb-metrics\" data-game-metrics></div>",
    "            <h4>Selection Details</h4>",
    "            <div class=\"module-wb-field-grid\">",
    "                <label class=\"module-wb-field module-wb-field-wide\">Name<input type=\"text\" data-game-actor-name placeholder=\"Select actor from outliner\" /></label>",
    "                <label class=\"module-wb-field\">Class",
    "                    <select data-game-actor-class>",
    "                        <option value=\"platform\">Platform</option>",
    "                        <option value=\"hazard\">Hazard</option>",
    "                        <option value=\"spawn\">Spawn</option>",
    "                        <option value=\"goal\">Goal</option>",
    "                        <option value=\"npc\">NPC</option>",
    "                        <option value=\"pickup\">Pickup</option>",
    "                        <option value=\"trigger\">Trigger</option>",
    "                        <option value=\"light\">Light</option>",
    "                        <option value=\"camera\">Camera</option>",
    "                        <option value=\"marker\">Marker</option>",
    "                    </select>",
    "                </label>",
    "                <label class=\"module-wb-field\">X<input type=\"number\" step=\"0.1\" data-game-actor-x value=\"0\" /></label>",
    "                <label class=\"module-wb-field\">Y<input type=\"number\" step=\"0.1\" data-game-actor-y value=\"0\" /></label>",
    "                <label class=\"module-wb-field\">Z<input type=\"number\" step=\"0.1\" data-game-actor-z value=\"0\" /></label>",
    "                <label class=\"module-wb-field\">Rot X<input type=\"number\" step=\"1\" data-game-actor-rx value=\"0\" /></label>",
    "                <label class=\"module-wb-field\">Rot Y<input type=\"number\" step=\"1\" data-game-actor-ry value=\"0\" /></label>",
    "                <label class=\"module-wb-field\">Rot Z<input type=\"number\" step=\"1\" data-game-actor-rz value=\"0\" /></label>",
    "                <label class=\"module-wb-field\">Scale X<input type=\"number\" step=\"0.1\" data-game-actor-sx value=\"1\" /></label>",
    "                <label class=\"module-wb-field\">Scale Y<input type=\"number\" step=\"0.1\" data-game-actor-sy value=\"1\" /></label>",
    "                <label class=\"module-wb-field\">Scale Z<input type=\"number\" step=\"0.1\" data-game-actor-sz value=\"1\" /></label>",
    "            </div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"apply_actor\">Apply Actor</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"delete_actor\">Delete Actor</button>",
    "            </div>",
    "            <p class=\"module-wb-hint\" data-game-actor-meta>Select an actor to edit transform and class.</p>",
    "            <h4>Unreal Bridge Session</h4>",
    "            <div class=\"module-wb-metrics\" data-game-bridge-metrics></div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"bridge_ping\">Ping</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"bridge_pull\">Pull State</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"bridge_push_actor\">Push Selected</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"bridge_push_scene\">Push Scene</button>",
    "            </div>",
    "            <p class=\"module-wb-hint\" data-game-bridge-status>Bridge idle.</p>",
    "            <h4>Details + Engine Bridge</h4>",
    "            <div class=\"module-wb-field-grid\">",
    "                <label class=\"module-wb-field module-wb-field-wide\">Godot project path<input type=\"text\" data-game-path=\"godot\" value=\"${escapeHtml(wb.godotProjectPath)}\" /></label>",
    "                <label class=\"module-wb-field module-wb-field-wide\">Unreal .uproject path<input type=\"text\" data-game-path=\"unreal\" value=\"${escapeHtml(wb.unrealProjectPath)}\" /></label>",
    "            </div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"godot_export\">Godot Export</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"unreal_export\">Unreal Export</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"godot_tscn\">Godot TSCN</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"unreal_csv\">Unreal CSV</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"godot_open\">Copy Godot Open</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"godot_build\">Copy Godot Build</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"unreal_open\">Copy Unreal Open</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"unreal_build\">Copy Unreal Build</button>",
    "            </div>",
    "            <h4>Unreal Viewport Link</h4>",
    "            <div class=\"module-wb-field-grid\">",
    "                <label class=\"module-wb-field module-wb-field-wide\">Pixel Streaming URL<input type=\"text\" data-game-unreal-url value=\"${escapeHtml(wb.unrealViewportUrl)}\" placeholder=\"http://127.0.0.1:8888\" /></label>",
    "            </div>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"connect_unreal\">Connect</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"reload_unreal\">Reload</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-game-action=\"open_unreal\">Open Popout</button>",
    "            </div>",
    "            <p class=\"module-wb-hint\">If iframe embed is blocked by host policy, use Open Popout and keep Remote Control connected.</p>",
    "            <details class=\"module-wb-collapsible\">",
    "                <summary>Unreal Remote Control (Advanced)</summary>",
    "                <div class=\"module-wb-field-grid\">",
    "                    <label class=\"module-wb-field\">Base URL<input type=\"text\" data-game-rc-url value=\"${escapeHtml(wb.unrealRcUrl)}\" placeholder=\"http://127.0.0.1:30010\" /></label>",
    "                    <label class=\"module-wb-field\">Endpoint<input type=\"text\" data-game-rc-endpoint value=\"${escapeHtml(wb.unrealRcEndpoint)}\" placeholder=\"/remote/object/call\" /></label>",
    "                    <label class=\"module-wb-field module-wb-field-wide\">Payload JSON<textarea rows=\"6\" data-game-rc-payload>${escapeHtml(wb.unrealRcPayload)}</textarea></label>",
    "                    <label class=\"module-wb-field module-wb-field-wide\">Response<textarea rows=\"7\" data-game-rc-response readonly>${escapeHtml(wb.unrealRcResponse)}</textarea></label>",
    "                </div>",
    "                <div class=\"module-wb-inspector-actions\">",
    "                    <button type=\"button\" class=\"module-item-btn\" data-game-action=\"rc_send\">Send to Unreal</button>",
    "                </div>",
    "            </details>",
    "        </aside>",
    "        ${moduleWorkbenchRenderOssStack('game_studio')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const brushes = [",
    "        { id: 0, label: 'Erase' },",
    "        { id: 1, label: 'Platform' },",
    "        { id: 2, label: 'Hazard' },",
    "        { id: 3, label: 'Spawn' },",
    "        { id: 4, label: 'Goal' },",
    "    ];",
    "    const viewModes = [",
    "        { id: 'edit', label: 'Edit Grid' },",
    "        { id: 'playtest', label: 'Playtest' },",
    "        { id: 'unreal', label: 'Unreal View' },",
    "        { id: 'split', label: 'Split' },",
    "    ];",
    "    const viewModeLabel = () => viewModes.find((entry) => entry.id === wb.viewMode)?.label || 'Split';",
    "    const brushBar = shell.querySelector('[data-game-brushes]');",
    "    const viewModeBar = shell.querySelector('[data-game-view-modes]');",
    "    const layout = shell.querySelector('[data-game-layout]');",
    "    const grid = shell.querySelector('[data-game-grid]');",
    "    const preview = shell.querySelector('[data-game-preview]');",
    "    const viewportStatus = shell.querySelector('[data-game-viewport-status]');",
    "    const viewportFrame = shell.querySelector('iframe[data-game-unreal-frame]');",
    "    const blockedHint = shell.querySelector('[data-game-unreal-blocked]');",
    "    const status = shell.querySelector('[data-game-status]');",
    "    const metrics = shell.querySelector('[data-game-metrics]');",
    "    const logs = shell.querySelector('[data-game-logs]');",
    "    const outliner = shell.querySelector('[data-game-outliner]');",
    "    const assetsList = shell.querySelector('[data-game-assets]');",
    "    const assetSearchInput = shell.querySelector('input[data-game-asset-search]');",
    "    const assetTypeSelect = shell.querySelector('select[data-game-asset-type]');",
    "    const sizeWidthInput = shell.querySelector('input[data-game-size=\"width\"]');",
    "    const sizeHeightInput = shell.querySelector('input[data-game-size=\"height\"]');",
    "    const unrealUrlInput = shell.querySelector('input[data-game-unreal-url]');",
    "    const rcUrlInput = shell.querySelector('input[data-game-rc-url]');",
    "    const rcEndpointInput = shell.querySelector('input[data-game-rc-endpoint]');",
    "    const rcPayloadInput = shell.querySelector('textarea[data-game-rc-payload]');",
    "    const rcResponseInput = shell.querySelector('textarea[data-game-rc-response]');",
    "    const aiPromptInput = shell.querySelector('input[data-game-ai-prompt]');",
    "    const actorNameInput = shell.querySelector('input[data-game-actor-name]');",
    "    const actorClassInput = shell.querySelector('select[data-game-actor-class]');",
    "    const actorXInput = shell.querySelector('input[data-game-actor-x]');",
    "    const actorYInput = shell.querySelector('input[data-game-actor-y]');",
    "    const actorZInput = shell.querySelector('input[data-game-actor-z]');",
    "    const actorRxInput = shell.querySelector('input[data-game-actor-rx]');",
    "    const actorRyInput = shell.querySelector('input[data-game-actor-ry]');",
    "    const actorRzInput = shell.querySelector('input[data-game-actor-rz]');",
    "    const actorSxInput = shell.querySelector('input[data-game-actor-sx]');",
    "    const actorSyInput = shell.querySelector('input[data-game-actor-sy]');",
    "    const actorSzInput = shell.querySelector('input[data-game-actor-sz]');",
    "    const actorMeta = shell.querySelector('[data-game-actor-meta]');",
    "    const bridgeMetrics = shell.querySelector('[data-game-bridge-metrics]');",
    "    const bridgeStatus = shell.querySelector('[data-game-bridge-status]');",
    "    if (!(brushBar instanceof HTMLElement)",
    "        || !(viewModeBar instanceof HTMLElement)",
    "        || !(layout instanceof HTMLElement)",
    "        || !(grid instanceof HTMLElement)",
    "        || !(preview instanceof HTMLElement)",
    "        || !(viewportStatus instanceof HTMLElement)",
    "        || !(viewportFrame instanceof HTMLIFrameElement)",
    "        || !(blockedHint instanceof HTMLElement)",
    "        || !(status instanceof HTMLElement)",
    "        || !(metrics instanceof HTMLElement)",
    "        || !(logs instanceof HTMLElement)",
    "        || !(outliner instanceof HTMLElement)",
    "        || !(assetsList instanceof HTMLElement)",
    "        || !(assetSearchInput instanceof HTMLInputElement)",
    "        || !(assetTypeSelect instanceof HTMLSelectElement)",
    "        || !(unrealUrlInput instanceof HTMLInputElement)",
    "        || !(rcUrlInput instanceof HTMLInputElement)",
    "        || !(rcEndpointInput instanceof HTMLInputElement)",
    "        || !(rcPayloadInput instanceof HTMLTextAreaElement)",
    "        || !(rcResponseInput instanceof HTMLTextAreaElement)",
    "        || !(aiPromptInput instanceof HTMLInputElement)",
    "        || !(actorNameInput instanceof HTMLInputElement)",
    "        || !(actorClassInput instanceof HTMLSelectElement)",
    "        || !(actorXInput instanceof HTMLInputElement)",
    "        || !(actorYInput instanceof HTMLInputElement)",
    "        || !(actorZInput instanceof HTMLInputElement)",
    "        || !(actorRxInput instanceof HTMLInputElement)",
    "        || !(actorRyInput instanceof HTMLInputElement)",
    "        || !(actorRzInput instanceof HTMLInputElement)",
    "        || !(actorSxInput instanceof HTMLInputElement)",
    "        || !(actorSyInput instanceof HTMLInputElement)",
    "        || !(actorSzInput instanceof HTMLInputElement)",
    "        || !(actorMeta instanceof HTMLElement)",
    "        || !(bridgeMetrics instanceof HTMLElement)",
    "        || !(bridgeStatus instanceof HTMLElement)) {",
    "        return false;",
    "    }",
    "",
    "    let paintDirty = false;",
    "    const paint = (x, y) => {",
    "        const value = moduleWorkbenchClamp(Number(wb.brush) || 0, 0, 4);",
    "        if (value === 3 || value === 4) {",
    "            wb.tiles.forEach((row, rowIndex) => row.forEach((tile, colIndex) => {",
    "                if (Number(tile) === value) wb.tiles[rowIndex][colIndex] = 0;",
    "            }));",
    "        }",
    "        wb.tiles[y][x] = value;",
    "        paintDirty = true;",
    "    };",
    "    const renderProjectSelect = () => {",
    "        const select = shell.querySelector('select[data-wb-project-select=\"game_studio\"]');",
    "        if (!(select instanceof HTMLSelectElement)) return;",
    "        const rows = moduleWorkbenchProjectList('game_studio');",
    "        const current = safeString(wb.selectedProjectId);",
    "        select.innerHTML = `<option value=\"\">Select project</option>${rows.map((row) => `<option value=\"${escapeHtml(safeString(row.id))}\">${escapeHtml(`${safeString(row.name)} (${new Date(Number(row.updatedAt) || Date.now()).toLocaleString()})`)}</option>`).join('')}`;",
    "        select.value = rows.some((row) => safeString(row.id) === current) ? current : '';",
    "    };",
    "    const projectPayload = () => ({",
    "        gridWidth: wb.gridWidth,",
    "        gridHeight: wb.gridHeight,",
    "        brush: wb.brush,",
    "        tiles: wb.tiles,",
    "        sceneActors: wb.sceneActors,",
    "        selectedActorId: wb.selectedActorId,",
    "        nextActorId: wb.nextActorId,",
    "        assets: wb.assets,",
    "        selectedAssetId: wb.selectedAssetId,",
    "        assetFilterType: wb.assetFilterType,",
    "        assetSearch: wb.assetSearch,",
    "        godotProjectPath: wb.godotProjectPath,",
    "        unrealProjectPath: wb.unrealProjectPath,",
    "        viewMode: wb.viewMode,",
    "        playTarget: wb.playTarget,",
    "        aiPrompt: wb.aiPrompt,",
    "        unrealViewportUrl: wb.unrealViewportUrl,",
    "        unrealRcUrl: wb.unrealRcUrl,",
    "        unrealRcEndpoint: wb.unrealRcEndpoint,",
    "        unrealRcPayload: wb.unrealRcPayload,",
    "        bridgeActorSyncPath: safeString(moduleGameStudioBridgeState(wb).actorSyncPath),",
    "    });",
    "    const applyProjectPayload = (payloadRaw) => {",
    "        const payload = payloadRaw && typeof payloadRaw === 'object' ? payloadRaw : {};",
    "        moduleGameStudioResizeGrid(wb, Number(payload.gridWidth) || wb.gridWidth, Number(payload.gridHeight) || wb.gridHeight);",
    "        const rawTiles = Array.isArray(payload.tiles) ? payload.tiles : [];",
    "        wb.tiles = Array.from({ length: wb.gridHeight }, (_row, y) => (",
    "            Array.from({ length: wb.gridWidth }, (_col, x) => moduleWorkbenchClamp(Number(rawTiles?.[y]?.[x]) || 0, 0, 4))",
    "        ));",
    "        wb.brush = moduleWorkbenchClamp(Number(payload.brush) || wb.brush || 1, 0, 4);",
    "        wb.godotProjectPath = safeString(payload.godotProjectPath) || wb.godotProjectPath;",
    "        wb.unrealProjectPath = safeString(payload.unrealProjectPath) || wb.unrealProjectPath;"
].join("\n");
