/* app.js lines 14001-15000 */
export default [
    "            agent.state = 'runaway';",
    "            agent.intent = 'runaway';",
    "            return;",
    "        }",
    "        const outOfBounds = agent.x < 0.5 || agent.x > 99.5 || agent.y < 0.5 || agent.y > 99.5;",
    "        if (arrived || outOfBounds || now >= agent.returnAfterRunAt) {",
    "            agent.x = officeClamp(agent.x, 2, 98);",
    "            agent.y = officeClamp(agent.y, 2, 98);",
    "            agent.targetX = agent.x;",
    "            agent.targetY = agent.y;",
    "            agent.state = 'walking';",
    "            agent.intent = 'wander';",
    "            agent.returnAfterRunAt = 0;",
    "            agent.runawayPhase = '';",
    "            agent.runawayExitX = 0;",
    "            agent.runawayExitY = 0;",
    "            agent.currentNodeId = officeFindNearestNode(officeState.navMap, agent.x, agent.y);",
    "            const routed = officeRouteAgentToRoom(agent, 'room-lobby', {",
    "                intent: 'wander',",
    "                speed: officeRandomRange(3.9, 5.2),",
    "            });",
    "            if (!routed) {",
    "                agent.state = 'idle';",
    "                agent.intent = 'wander';",
    "                agent.idleUntil = now + officeRandomRange(800, 1700);",
    "            }",
    "        }",
    "        return;",
    "    }",
    "",
    "    if (agent.state === 'teleporting') {",
    "        if (now < agent.teleportUntil) {",
    "            return;",
    "        }",
    "        agent.teleportUntil = 0;",
    "        const lobbyNodeId = officeSelectRoomDestinationNode('room-lobby', agent, { intent: 'wander' });",
    "        const lobbyNode = officeState?.navMap?.get(lobbyNodeId);",
    "        if (lobbyNode) {",
    "            agent.x = officeClamp(Number(lobbyNode.x) + officeRandomRange(-0.12, 0.12), 3, 97);",
    "            agent.y = officeClamp(Number(lobbyNode.y) + officeRandomRange(-0.12, 0.12), 7, 92);",
    "        }",
    "        agent.targetX = agent.x;",
    "        agent.targetY = agent.y;",
    "        agent.currentNodeId = officeFindNearestNode(officeState.navMap, agent.x, agent.y);",
    "        officeBeginSpawnSequence(agent, now);",
    "        return;",
    "    }",
    "",
    "    if (agent.state === 'spawning') {",
    "        if (now < agent.spawnUntil) {",
    "            return;",
    "        }",
    "        agent.spawnUntil = 0;",
    "        if (agent.taskId) {",
    "            const task = officeState.tasks.find((entry) => entry.id === agent.taskId);",
    "            if (task && task.status === 'active') {",
    "                const routedToTask = officeRouteAgentToRoom(agent, task.roomId, {",
    "                    intent: 'task',",
    "                    speed: Math.max(3.2, Number(agent.speed) || 0),",
    "                });",
    "                if (routedToTask) {",
    "                    return;",
    "                }",
    "            }",
    "        }",
    "        agent.state = 'idle';",
    "        agent.intent = 'wander';",
    "        agent.idleUntil = now + officeRandomRange(400, 1200);",
    "        return;",
    "    }",
    "",
    "    if (agent.state === 'yield') {",
    "        if (now >= agent.yieldUntil) {",
    "            agent.state = 'walking';",
    "            if (safeString(agent.yieldResumeIntent)) {",
    "                agent.intent = agent.yieldResumeIntent;",
    "            }",
    "            agent.yieldUntil = 0;",
    "            agent.yieldResumeIntent = '';",
    "        } else {",
    "            return;",
    "        }",
    "    }",
    "",
    "    if (agent.state === 'walking') {",
    "        const arrived = officeMoveAgent(agent, dt);",
    "        if (!arrived) {",
    "            officeSafeguardAgentPosition(agent, now, { reroute: true });",
    "            officeHandleAgentStuck(agent, now);",
    "            return;",
    "        }",
    "        agent.stuckSince = 0;",
    "",
    "        if (agent.intent === 'task' && agent.taskId) {",
    "            agent.state = 'working';",
    "            agent.workUntil = now + officeRandomRange(6200, 15000);",
    "            agent.nextWorkLineAt = now + officeRandomRange(2400, 5600);",
    "            officeBusEmit('agent.state', {",
    "                agentId: agent.id,",
    "                state: agent.state,",
    "                intent: agent.intent,",
    "            }, now);",
    "            return;",
    "        }",
    "        if (agent.intent === 'break') {",
    "            agent.state = 'break';",
    "            agent.breakUntil = now + officeRandomRange(3000, 7600);",
    "            agent.nextWorkLineAt = now + officeRandomRange(1200, 3200);",
    "            officeBusEmit('agent.state', {",
    "                agentId: agent.id,",
    "                state: agent.state,",
    "                intent: agent.intent,",
    "            }, now);",
    "            return;",
    "        }",
    "        agent.state = 'idle';",
    "        agent.intent = 'wander';",
    "        agent.idleUntil = now + officeRandomRange(1200, 3200);",
    "        return;",
    "    }",
    "",
    "    if (agent.state === 'working') {",
    "        if (now >= agent.workUntil) {",
    "            officeFinishTask(agent, now);",
    "            return;",
    "        }",
    "        if (now >= agent.nextWorkLineAt) {",
    "            const room = officeCurrentRoomForAgent(agent);",
    "            officeSpeak(agent, officeBanterForAgent(agent, 'ambient', {",
    "                roomTheme: room?.theme || room?.kind || '',",
    "            }));",
    "            agent.nextWorkLineAt = now + officeRandomRange(3500, 7200);",
    "        }",
    "        if (now >= (Number(agent.nextTaskRoamAt) || 0)) {",
    "            const task = officeState.tasks.find((entry) => entry.id === agent.taskId);",
    "            if (task && task.status === 'active') {",
    "                const rerouted = officeRouteAgentToRoom(agent, task.roomId, {",
    "                    intent: 'task',",
    "                    speed: officeRandomRange(2.4, 3.5),",
    "                });",
    "                if (rerouted) {",
    "                    agent.nextTaskRoamAt = now + officeRandomRange(1800, 4200);",
    "                    return;",
    "                }",
    "            }",
    "            agent.nextTaskRoamAt = now + officeRandomRange(1800, 4200);",
    "        }",
    "        return;",
    "    }",
    "",
    "    if (agent.state === 'break') {",
    "        if (now >= agent.breakUntil) {",
    "            agent.state = 'idle';",
    "            agent.intent = 'wander';",
    "            agent.idleUntil = now + officeRandomRange(600, 1800);",
    "            officeRouteAgentToRoom(agent, 'room-lobby', {",
    "                intent: 'wander',",
    "                speed: officeRandomRange(2.6, 3.6),",
    "            });",
    "            return;",
    "        }",
    "        if (now >= agent.nextWorkLineAt) {",
    "            const room = officeCurrentRoomForAgent(agent);",
    "            officeSpeak(agent, officeBanterForAgent(agent, 'break', {",
    "                roomTheme: room?.theme || room?.kind || '',",
    "            }));",
    "            agent.nextWorkLineAt = now + officeRandomRange(2600, 5600);",
    "        }",
    "        return;",
    "    }",
    "",
    "    if (agent.state !== 'idle') {",
    "        return;",
    "    }",
    "",
    "    if (now >= agent.nextAmbientAt) {",
    "        const room = officeCurrentRoomForAgent(agent);",
    "        if (room && room.kind === 'break') {",
    "            officeSpeak(agent, officeBanterForAgent(agent, 'break', { roomTheme: room.theme || room.kind }));",
    "        } else if (officeChance(0.62)) {",
    "            officeSpeak(agent, officeBanterForAgent(agent, 'ambient', { roomTheme: room?.theme || room?.kind || '' }));",
    "        }",
    "        agent.nextAmbientAt = now + officeRandomRange(8200, 16000);",
    "    }",
    "",
    "    if (now >= agent.idleUntil && !agent.taskId) {",
    "        if (officeChance(0.16)) {",
    "            const breakRoomId = officeChance(0.5) ? 'room-coffee' : 'room-break';",
    "            officeRouteAgentToRoom(agent, breakRoomId, {",
    "                intent: 'break',",
    "                speed: officeRandomRange(3, 4.1),",
    "            });",
    "            return;",
    "        }",
    "        const roamRoom = officePick(officeState.rooms);",
    "        officeRouteAgentToRoom(agent, roamRoom?.id || 'room-lobby', {",
    "            intent: 'wander',",
    "            speed: officeRandomRange(2.4, 3.5),",
    "        });",
    "    }",
    "}",
    "",
    "function officeAgentTrafficPriority(agent) {",
    "    if (!agent) return 0;",
    "    let score = 0;",
    "    if (agent.intent === 'task') score += 4;",
    "    if (agent.state === 'working') score += 3;",
    "    if (agent.intent === 'break') score += 1;",
    "    if (Array.isArray(agent.routeWaypoints)) {",
    "        score += Math.min(1.4, agent.routeWaypoints.length * 0.08);",
    "    }",
    "    const stableTieBreak = (safeString(agent.id).charCodeAt(safeString(agent.id).length - 1) || 0) / 2550;",
    "    return score + stableTieBreak;",
    "}",
    "",
    "function officeCollisionPairKey(aId, bId) {",
    "    const first = safeString(aId);",
    "    const second = safeString(bId);",
    "    if (!first || !second) return '';",
    "    return first < second ? `${first}|${second}` : `${second}|${first}`;",
    "}",
    "",
    "function officeLaneEdgeKey(fromId, toId) {",
    "    const first = safeString(fromId);",
    "    const second = safeString(toId);",
    "    if (!first || !second) return '';",
    "    return first < second ? `${first}<->${second}` : `${second}<->${first}`;",
    "}",
    "",
    "function officeAgentActiveRouteEdge(agent) {",
    "    if (!officeState || !agent || agent.state === 'runaway') return null;",
    "    const fromNodeId = safeString(agent.currentNodeId) || officeFindNearestNode(officeState.navMap, agent.x, agent.y);",
    "    let toNodeId = safeString(agent.routeWaypoints?.[0]?.nodeId);",
    "    if (!toNodeId) {",
    "        toNodeId = safeString(agent.routeDestinationNodeId);",
    "    }",
    "    if (!fromNodeId || !toNodeId || fromNodeId === toNodeId) return null;",
    "    const edgeKey = officeLaneEdgeKey(fromNodeId, toNodeId);",
    "    if (!edgeKey) return null;",
    "    return {",
    "        fromNodeId,",
    "        toNodeId,",
    "        edgeKey,",
    "        directedKey: `${fromNodeId}>${toNodeId}`,",
    "    };",
    "}",
    "",
    "function officeTickLaneReservations(now) {",
    "    if (!officeState) return;",
    "    const reservations = officeState.laneReservations || new Map();",
    "    officeState.laneReservations = reservations;",
    "",
    "    reservations.forEach((claim, edgeKey) => {",
    "        if (!claim || !Number.isFinite(claim.expiresAt) || claim.expiresAt <= now) {",
    "            reservations.delete(edgeKey);",
    "        }",
    "    });",
    "",
    "    const walkers = officeState.agents.filter((agent) => (",
    "        agent",
    "        && agent.state === 'walking'",
    "        && agent.intent !== 'runaway'",
    "    ));",
    "",
    "    walkers.forEach((agent) => {",
    "        const edge = officeAgentActiveRouteEdge(agent);",
    "        agent.reservedLaneEdgeKey = edge?.edgeKey || '';",
    "        if (!edge) return;",
    "",
    "        const priority = officeAgentTrafficPriority(agent);",
    "        const existing = reservations.get(edge.edgeKey);",
    "        if (!existing || safeString(existing.agentId) === agent.id) {",
    "            reservations.set(edge.edgeKey, {",
    "                edgeKey: edge.edgeKey,",
    "                directedKey: edge.directedKey,",
    "                priority,",
    "                agentId: agent.id,",
    "                expiresAt: now + 600,",
    "            });",
    "            return;",
    "        }",
    "",
    "        const otherAgent = officeGetAgentById(existing.agentId);",
    "        const otherPriority = Number(existing.priority) || 0;",
    "        const oppositeDirection = safeString(existing.directedKey) !== edge.directedKey;",
    "        const nearEnough = otherAgent",
    "            ? Math.hypot(otherAgent.x - agent.x, otherAgent.y - agent.y) <= 8.8",
    "            : true;",
    "",
    "        if (oppositeDirection && nearEnough && priority < otherPriority) {",
    "            const anchorX = otherAgent ? otherAgent.x : agent.targetX;",
    "            const anchorY = otherAgent ? otherAgent.y : agent.targetY;",
    "            const awayX = agent.x - anchorX;",
    "            const awayY = agent.y - anchorY;",
    "            const awayLen = Math.max(0.001, Math.hypot(awayX, awayY));",
    "            officeSetYieldState(",
    "                agent,",
    "                now,",
    "                (awayX / awayLen) * officeRandomRange(0.52, 1.08),",
    "                (awayY / awayLen) * officeRandomRange(0.52, 1.08),",
    "            );",
    "            return;",
    "        }",
    "",
    "        if (priority > otherPriority) {",
    "            reservations.set(edge.edgeKey, {",
    "                edgeKey: edge.edgeKey,",
    "                directedKey: edge.directedKey,",
    "                priority,",
    "                agentId: agent.id,",
    "                expiresAt: now + 600,",
    "            });",
    "        }",
    "    });",
    "}",
    "",
    "function officeSetYieldState(agent, now, awayX = 0, awayY = 0) {",
    "    if (!agent || agent.state === 'runaway') return;",
    "    if (agent.state !== 'walking' && agent.state !== 'idle' && agent.state !== 'break') return;",
    "    agent.yieldResumeIntent = agent.intent || 'wander';",
    "    agent.state = 'yield';",
    "    agent.yieldUntil = now + officeRandomRange(320, 620);",
    "    const fallbackX = officeClamp(agent.x + awayX, 3, 97);",
    "    const fallbackY = officeClamp(agent.y + awayY, 7, 92);",
    "    const walkableTarget = officeNearestWalkablePoint(fallbackX, fallbackY, agent.x, agent.y);",
    "    agent.targetX = officeClamp(walkableTarget.x, 3, 97);",
    "    agent.targetY = officeClamp(walkableTarget.y, 7, 92);",
    "}",
    "",
    "function officeHandleCollisions(now) {",
    "    if (!officeState) return;",
    "    const minDistance = OFFICE_AGENT_COLLISION_DISTANCE;",
    "    const pairCooldowns = officeState.collisionPairCooldowns || new Map();",
    "    if (!officeState.collisionPairCooldowns) {",
    "        officeState.collisionPairCooldowns = pairCooldowns;",
    "    }",
    "    if ((now - (officeState.lastCollisionCooldownPurgeAt || 0)) >= OFFICE_COLLISION_PAIR_PURGE_MS) {",
    "        officeState.lastCollisionCooldownPurgeAt = now;",
    "        pairCooldowns.forEach((until, pairKey) => {",
    "            if (!Number.isFinite(until) || until < now - OFFICE_COLLISION_PAIR_PURGE_MS) {",
    "                pairCooldowns.delete(pairKey);",
    "            }",
    "        });",
    "    }",
    "",
    "    for (let i = 0; i < officeState.agents.length; i += 1) {",
    "        for (let j = i + 1; j < officeState.agents.length; j += 1) {",
    "            const a = officeState.agents[i];",
    "            const b = officeState.agents[j];",
    "            if (!a || !b) continue;",
    "            if (a.state === 'runaway' || a.state === 'teleporting' || b.state === 'runaway' || b.state === 'teleporting') continue;",
    "            if (now < a.collisionCooldownUntil || now < b.collisionCooldownUntil) continue;",
    "            const pairKey = officeCollisionPairKey(a.id, b.id);",
    "            if (!pairKey) continue;",
    "            if (now < (pairCooldowns.get(pairKey) || 0)) continue;",
    "",
    "            let dx = b.x - a.x;",
    "            let dy = b.y - a.y;",
    "            let distance = Math.hypot(dx, dy);",
    "            if (distance === 0) {",
    "                dx = officeRandomRange(-1, 1);",
    "                dy = officeRandomRange(-1, 1);",
    "                distance = Math.max(0.001, Math.hypot(dx, dy));",
    "            }",
    "            if (distance >= minDistance) continue;",
    "",
    "            const overlap = minDistance - distance;",
    "            const nx = dx / distance;",
    "            const ny = dy / distance;",
    "            const separation = (overlap * 0.62) + 0.24;",
    "            const prevAX = a.x;",
    "            const prevAY = a.y;",
    "            const prevBX = b.x;",
    "            const prevBY = b.y;",
    "",
    "            const aMovable = a.state === 'walking' || a.state === 'yield' || a.state === 'idle' || a.state === 'break';",
    "            const bMovable = b.state === 'walking' || b.state === 'yield' || b.state === 'idle' || b.state === 'break';",
    "            if (!aMovable && !bMovable) continue;",
    "",
    "            if (aMovable && bMovable) {",
    "                a.x = officeClamp(a.x - (nx * separation), 2, 98);",
    "                a.y = officeClamp(a.y - (ny * separation), 6, 93);",
    "                b.x = officeClamp(b.x + (nx * separation), 2, 98);",
    "                b.y = officeClamp(b.y + (ny * separation), 6, 93);",
    "            } else if (aMovable) {",
    "                a.x = officeClamp(a.x - (nx * separation * 1.3), 2, 98);",
    "                a.y = officeClamp(a.y - (ny * separation * 1.3), 6, 93);",
    "            } else if (bMovable) {",
    "                b.x = officeClamp(b.x + (nx * separation * 1.3), 2, 98);",
    "                b.y = officeClamp(b.y + (ny * separation * 1.3), 6, 93);",
    "            }",
    "",
    "            if (aMovable) {",
    "                const aConstrained = officeConstrainWalkableMove(a, prevAX, prevAY, a.x, a.y);",
    "                a.x = officeClamp(aConstrained.x, 2, 98);",
    "                a.y = officeClamp(aConstrained.y, 6, 93);",
    "                officeSafeguardAgentPosition(a, now, { reroute: false });",
    "            }",
    "            if (bMovable) {",
    "                const bConstrained = officeConstrainWalkableMove(b, prevBX, prevBY, b.x, b.y);",
    "                b.x = officeClamp(bConstrained.x, 2, 98);",
    "                b.y = officeClamp(bConstrained.y, 6, 93);",
    "                officeSafeguardAgentPosition(b, now, { reroute: false });",
    "            }",
    "",
    "            const shouldYield = a.state === 'walking' && b.state === 'walking';",
    "            if (shouldYield) {",
    "                const aPriority = officeAgentTrafficPriority(a);",
    "                const bPriority = officeAgentTrafficPriority(b);",
    "                const yielder = aPriority <= bPriority ? a : b;",
    "                const awayDir = yielder.id === a.id ? -1 : 1;",
    "                officeSetYieldState(",
    "                    yielder,",
    "                    now,",
    "                    nx * awayDir * officeRandomRange(0.6, 1.4),",
    "                    ny * awayDir * officeRandomRange(0.6, 1.4),",
    "                );",
    "            }",
    "",
    "            a.bumpUntil = now + 520;",
    "            b.bumpUntil = now + 520;",
    "            a.collisionCooldownUntil = now + officeRandomRange(820, 1380);",
    "            b.collisionCooldownUntil = now + officeRandomRange(820, 1380);",
    "            pairCooldowns.set(pairKey, now + officeRandomRange(",
    "                OFFICE_COLLISION_PAIR_COOLDOWN_MIN,",
    "                OFFICE_COLLISION_PAIR_COOLDOWN_MAX,",
    "            ));",
    "            officePulseHaptic([10, 22, 10]);",
    "            officeBusEmit('agent.collision', {",
    "                pairKey,",
    "                aId: a.id,",
    "                bId: b.id,",
    "                aState: a.state,",
    "                bState: b.state,",
    "                distance: Number(distance.toFixed(3)),",
    "            }, now);",
    "",
    "            if (now >= officeState.collisionSpeechCooldownUntil) {",
    "                const speaker = officeChance(0.5) ? a : b;",
    "                const line = officeBanterForAgent(speaker, 'collision');",
    "                if (officeSpeak(speaker, line, { priority: true, durationMs: 1200 })) {",
    "                    officePushChatLine(`${speaker.name}: ${line}`);",
    "                    officeState.collisionSpeechCooldownUntil = now + 1050;",
    "                }",
    "            }",
    "        }",
    "    }",
    "}",
    "",
    "function officeDisperseCrowds(now) {",
    "    if (!officeState) return;",
    "    const activeAgents = officeState.agents.filter((agent) => (",
    "        agent",
    "        && agent.state !== 'runaway'",
    "        && !agent.taskId",
    "        && (",
    "            agent.state === 'idle'",
    "            || agent.state === 'break'",
    "            || agent.state === 'yield'",
    "            || (agent.state === 'walking' && safeString(agent.intent) === 'wander')",
    "        )",
    "    ));",
    "    if (activeAgents.length < OFFICE_CROWD_RELIEF_NEIGHBORS) return;",
    "",
    "    let redirected = 0;",
    "    activeAgents.forEach((agent) => {",
    "        if (redirected >= 3) return;",
    "        if (now < (agent.crowdReliefUntil || 0)) return;",
    "",
    "        const nearby = activeAgents.filter((other) => (",
    "            other.id !== agent.id",
    "            && Math.hypot(other.x - agent.x, other.y - agent.y) <= OFFICE_CROWD_RELIEF_RADIUS",
    "        ));",
    "        if (nearby.length < (OFFICE_CROWD_RELIEF_NEIGHBORS - 1)) return;",
    "",
    "        let centerX = agent.x;",
    "        let centerY = agent.y;",
    "        nearby.forEach((other) => {",
    "            centerX += other.x;",
    "            centerY += other.y;",
    "        });",
    "        const total = nearby.length + 1;",
    "        centerX /= total;",
    "        centerY /= total;",
    "",
    "        const awayX = agent.x - centerX;",
    "        const awayY = agent.y - centerY;",
    "        const awayLen = Math.max(0.001, Math.hypot(awayX, awayY));",
    "        const randomBias = officeRandomRange(-0.58, 0.58);",
    "        const baseAngle = Math.atan2(awayY / awayLen, awayX / awayLen) + randomBias;",
    "        const scatterDistance = officeRandomRange(4.8, 9.4);",
    "        const proposed = officeNearestWalkablePoint(",
    "            agent.x + (Math.cos(baseAngle) * scatterDistance),",
    "            agent.y + (Math.sin(baseAngle) * scatterDistance),",
    "            agent.x,",
    "            agent.y,",
    "        );",
    "        officeSetAgentTarget(agent, proposed.x, proposed.y, {",
    "            intent: 'wander',",
    "            speed: Math.max(2.35, agent.speed),",
    "        });",
    "        agent.collisionCooldownUntil = now + officeRandomRange(650, 1100);",
    "        agent.crowdReliefUntil = now + officeRandomRange(",
    "            OFFICE_CROWD_RELIEF_COOLDOWN_MS,",
    "            OFFICE_CROWD_RELIEF_COOLDOWN_MS + 900,",
    "        );",
    "        redirected += 1;",
    "    });",
    "}",
    "",
    "function officeTick(now, dt, options = {}) {",
    "    if (!officeState) return;",
    "    const background = Boolean(options.background);",
    "    officeState.debugFrameRate = dt > 0 ? (1 / dt) : 0;",
    "    officeTickBreakSchedules(now);",
    "    officeAssignQueuedTasks(now);",
    "    officeTickLaneReservations(now);",
    "    officeTickSocialIdle(now);",
    "    officeState.agents.forEach((agent) => officeTickAgent(agent, now, dt));",
    "    officeHandleCollisions(now);",
    "    officeState.agents.forEach((agent) => {",
    "        if (!agent || agent.state === 'runaway') return;",
    "        officeSafeguardAgentPosition(agent, now, { reroute: false });",
    "    });",
    "    officeDisperseCrowds(now);",
    "    officeTrimTasks();",
    "    if (!background) {",
    "        officeTickFollowCamera();",
    "        officeTickCamera(dt);",
    "        officePersistCameraState(now);",
    "        officeRenderAgents(now);",
    "        const shouldSyncRoomMeta = (now - (officeState.lastRoomMetaSyncAt || 0)) >= 220;",
    "        if (shouldSyncRoomMeta) {",
    "            officeState.lastRoomMetaSyncAt = now;",
    "            officeUpdateRoomMeta();",
    "        }",
    "        if (officeState.tasksDirty) {",
    "            officeState.tasksDirty = false;",
    "            officeRenderTaskList();",
    "            officeState.lastRoomMetaSyncAt = now;",
    "            officeUpdateRoomMeta();",
    "        }",
    "        officeRenderDebugOverlay(now);",
    "    }",
    "    officePersistRuntimeState(now);",
    "}",
    "",
    "function officeEnsureBackgroundTickTimer() {",
    "    if (!officeState || officeState.backgroundTickTimerId) return;",
    "    officeState.backgroundTickTimerId = window.setInterval(() => {",
    "        if (!officeState) return;",
    "        if (!document.hidden) return;",
    "        const wallNow = Date.now();",
    "        const lastWall = Number(officeState.lastWallClockTickAt) || wallNow;",
    "        const dt = officeClamp((wallNow - lastWall) / 1000, 0.18, 1.45);",
    "        officeState.lastWallClockTickAt = wallNow;",
    "        const nowPerf = performance.now();",
    "        officeState.lastFrameAt = nowPerf;",
    "        officeTick(nowPerf, dt, { background: true });",
    "    }, OFFICE_BACKGROUND_TICK_MS);",
    "}",
    "",
    "function officeStopBackgroundTickTimer() {",
    "    if (!officeState) return;",
    "    if (officeState.backgroundTickTimerId) {",
    "        window.clearInterval(officeState.backgroundTickTimerId);",
    "        officeState.backgroundTickTimerId = 0;",
    "    }",
    "}",
    "",
    "function officeAnimationLoop(now) {",
    "    if (!officeState) return;",
    "    if (!officeState.lastFrameAt) {",
    "        officeState.lastFrameAt = now;",
    "    }",
    "    const wallNow = Date.now();",
    "    if (!officeState.lastWallClockTickAt) {",
    "        officeState.lastWallClockTickAt = wallNow;",
    "    }",
    "    const dt = officeClamp((wallNow - officeState.lastWallClockTickAt) / 1000, 0.01, 0.16);",
    "    officeState.lastWallClockTickAt = wallNow;",
    "    officeState.lastFrameAt = now;",
    "    officeTick(now, dt, { background: false });",
    "    officeState.rafId = window.requestAnimationFrame(officeAnimationLoop);",
    "}",
    "",
    "function officeStartLoop() {",
    "    if (!officeState || officeState.rafId) return;",
    "    officeEnsureBackgroundTickTimer();",
    "    officeState.lastFrameAt = performance.now();",
    "    officeState.lastWallClockTickAt = Date.now();",
    "    officeState.rafId = window.requestAnimationFrame(officeAnimationLoop);",
    "}",
    "",
    "function officeNearestHallId(doorX, doorY) {",
    "    let bestId = 'hall-low-mid';",
    "    let bestDistance = Number.POSITIVE_INFINITY;",
    "    OFFICE_HALL_NODES.forEach((node) => {",
    "        if (!safeString(node?.id).startsWith('hall-mid') && !safeString(node?.id).startsWith('hall-low')) {",
    "            return;",
    "        }",
    "        const distance = Math.hypot((Number(doorX) || 0) - node.x, (Number(doorY) || 0) - node.y);",
    "        if (distance < bestDistance) {",
    "            bestDistance = distance;",
    "            bestId = node.id;",
    "        }",
    "    });",
    "    return bestId;",
    "}",
    "",
    "function officeDynamicRoomSlotByIndex(index) {",
    "    const baseSlot = OFFICE_DYNAMIC_ROOM_SLOTS[index];",
    "    if (baseSlot) return { ...baseSlot };",
    "",
    "    const generatedIndex = Math.max(0, index - OFFICE_DYNAMIC_ROOM_SLOTS.length);",
    "    const roomW = 6.6;",
    "    const roomH = 6.6;",
    "    const gapX = 0.8;",
    "    const gapY = 0.8;",
    "    const cols = 6;",
    "    const row = Math.floor(generatedIndex / cols);",
    "    const col = generatedIndex % cols;",
    "    const x = 55.2 + (col * (roomW + gapX));",
    "    const y = 56.8 + (row * (roomH + gapY));",
    "    if ((x + roomW) >= 96 || (y + roomH) >= 93.6) {",
    "        return null;",
    "    }",
    "    return { x, y, w: roomW, h: roomH };",
    "}",
    "",
    "function officePlanRunawayExit(agent) {",
    "    const exits = [",
    "        { hallId: 'hall-mid-left', x: OFFICE_RUNAWAY_EXIT_MARGIN, y: 53 },",
    "        { hallId: 'hall-top-left', x: 16, y: OFFICE_RUNAWAY_EXIT_MARGIN },",
    "        { hallId: 'hall-low-left', x: 16, y: 100 - OFFICE_RUNAWAY_EXIT_MARGIN },",
    "        { hallId: 'hall-top-right', x: 84, y: OFFICE_RUNAWAY_EXIT_MARGIN },",
    "        { hallId: 'hall-mid-right', x: 100 - OFFICE_RUNAWAY_EXIT_MARGIN, y: 53 },",
    "        { hallId: 'hall-low-right', x: 84, y: 100 - OFFICE_RUNAWAY_EXIT_MARGIN },",
    "    ];",
    "    const sourceX = Number(agent?.x) || 50;",
    "    const sourceY = Number(agent?.y) || 50;",
    "    const ranked = exits",
    "        .map((candidate) => {",
    "            const node = officeState?.navMap?.get(candidate.hallId);",
    "            const nodeX = Number(node?.x) || 50;",
    "            const nodeY = Number(node?.y) || 50;",
    "            return {",
    "                ...candidate,",
    "                x: officeClamp(Number(candidate.x) || nodeX, OFFICE_RUNAWAY_EXIT_MARGIN, 100 - OFFICE_RUNAWAY_EXIT_MARGIN),",
    "                y: officeClamp(Number(candidate.y) || nodeY, OFFICE_RUNAWAY_EXIT_MARGIN, 100 - OFFICE_RUNAWAY_EXIT_MARGIN),",
    "                score: Math.hypot(nodeX - sourceX, nodeY - sourceY) + officeRandomRange(0, 6),",
    "            };",
    "        })",
    "        .sort((a, b) => a.score - b.score);",
    "    return ranked[0] || exits[0];",
    "}",
    "",
    "function officeCreateDynamicRoom(taskText) {",
    "    if (!officeState) return officeRoomById('room-planning');",
    "    if (officeState.dynamicRoomBySlug.size >= OFFICE_MAX_DYNAMIC_ROOMS) {",
    "        return officeRoomById('room-planning') || officeState.rooms[0];",
    "    }",
    "",
    "    const baseTitle = officeTaskTitle(taskText);",
    "    const labelRoot = baseTitle",
    "        .replace(/[^a-zA-Z0-9\\s-]/g, '')",
    "        .split(/\\s+/)",
    "        .filter(Boolean)",
    "        .slice(0, 2)",
    "        .join(' ');",
    "    const label = labelRoot ? `${labelRoot} Pod` : `Task Pod ${officeState.dynamicIndex + 1}`;",
    "    const slot = officeDynamicRoomSlotByIndex(officeState.dynamicIndex);",
    "    if (!slot) {",
    "        return officeRoomById('room-planning') || officeState.rooms[0];",
    "    }",
    "    const roomId = `room-dynamic-${officeState.dynamicIndex + 1}`;",
    "    officeState.dynamicIndex += 1;",
    "    const doorY = slot.y >= 70 ? slot.y : slot.y + slot.h;",
    "    const doorX = slot.x + (slot.w / 2);",
    "    const hallId = officeNearestHallId(doorX, doorY);",
    "",
    "    const room = {",
    "        id: roomId,",
    "        label,",
    "        meta: 'Auto-generated feature room',",
    "        x: slot.x,",
    "        y: slot.y,",
    "        w: slot.w,",
    "        h: slot.h,",
    "        kind: 'work',",
    "        theme: 'dynamic',",
    "        doorX,",
    "        doorY,",
    "        hallId,",
    "        dynamic: true,",
    "    };",
    "    officeState.rooms.push(room);",
    "    officeState.roomById.set(room.id, room);",
    "    officeState.dynamicRoomBySlug.set(",
    "        officeTaskTitle(taskText)",
    "            .toLowerCase()",
    "            .replace(/[^a-z0-9]+/g, '-')",
    "            .replace(/^-+|-+$/g, '')",
    "            .slice(0, 42),",
    "        room.id,",
    "    );",
    "    officeRefreshNavGraph();",
    "    officeRecalculateMapSize({ preserveZoom: true, rerender: true });",
    "    officePersistLayoutState();",
    "    officeBusEmit('room.dynamic_created', {",
    "        roomId: room.id,",
    "        label: room.label,",
    "        theme: room.theme,",
    "    });",
    "    return room;",
    "}",
    "",
    "function officeResolveRoomForTask(taskText) {",
    "    const normalized = safeString(taskText).toLowerCase();",
    "    const featureExpansionHint = /\\b(feature|module|capability|integration|initiative|new room|new area|new workspace)\\b/i.test(normalized);",
    "    const slug = officeTaskTitle(taskText)",
    "        .toLowerCase()",
    "        .replace(/[^a-z0-9]+/g, '-')",
    "        .replace(/^-+|-+$/g, '')",
    "        .slice(0, 42);",
    "    if (slug && officeState?.dynamicRoomBySlug?.has(slug)) {",
    "        return officeRoomById(officeState.dynamicRoomBySlug.get(slug));",
    "    }",
    "    if (!featureExpansionHint) {",
    "        const matchedRule = OFFICE_TASK_ROOM_RULES.find((rule) => rule.pattern.test(normalized));",
    "        if (matchedRule) {",
    "            return officeRoomById(matchedRule.roomId) || officeState?.rooms?.[0];",
    "        }",
    "    }",
    "    const dynamicRoom = officeCreateDynamicRoom(taskText);",
    "    if (slug && dynamicRoom) {",
    "        officeState.dynamicRoomBySlug.set(slug, dynamicRoom.id);",
    "        officePersistLayoutState();",
    "    }",
    "    return dynamicRoom || officeRoomById('room-planning') || officeState?.rooms?.[0];",
    "}",
    "",
    "function officeQueueTask(taskText, { source = 'office-chat', announce = false, preferredAgentId = '' } = {}) {",
    "    if (!officeState) return null;",
    "    const clean = safeString(taskText).replace(/\\s+/g, ' ');",
    "    if (!clean) return null;",
    "    const room = officeResolveRoomForTask(clean);",
    "    if (!room) return null;",
    "",
    "    const task = {",
    "        id: `task-${officeState.taskCounter + 1}`,",
    "        title: officeTaskTitle(clean),",
    "        rawText: clean,",
    "        source: safeString(source) || 'office-chat',",
    "        roomId: room.id,",
    "        roomLabel: room.label,",
    "        status: 'queued',",
    "        assignedAgentId: '',",
    "        createdAt: Date.now(),",
    "        startedAt: 0,",
    "        completedAt: 0,",
    "    };",
    "    officeState.taskCounter += 1;",
    "    officeState.tasks.push(task);",
    "    officeState.tasksDirty = true;",
    "    officeTrimTasks();",
    "    officeBusEmit('task.queued', {",
    "        taskId: task.id,",
    "        source: task.source,",
    "        roomId: task.roomId,",
    "        roomLabel: task.roomLabel,",
    "        title: task.title,",
    "    });",
    "",
    "    if (preferredAgentId) {",
    "        const preferredAgent = officeGetAgentById(preferredAgentId);",
    "        if (preferredAgent && !preferredAgent.taskId && preferredAgent.state === 'idle') {",
    "            officeAssignTaskToAgent(task, preferredAgent, performance.now());",
    "        }",
    "    }",
    "    officeAssignQueuedTasks(performance.now());",
    "",
    "    if (announce) {",
    "        const queueLine = officePick(OFFICE_DIALOGUE.queued)",
    "            .replace('{room}', room.label)",
    "            .replace('{task}', task.title);",
    "        officePushChatLine(queueLine);",
    "    }",
    "",
    "    return task;",
    "}",
    "",
    "function officeMaybeQueueTaskFromPrompt(taskText, source = 'chat') {",
    "    if (!officeState) return null;",
    "    const clean = safeString(taskText);",
    "    if (!clean || clean.startsWith('/') || clean.startsWith('@')) return null;",
    "    if (!OFFICE_TASK_KEYWORDS.test(clean)) return null;",
    "    return officeQueueTask(clean, { source, announce: false });",
    "}",
    "",
    "function officeFindAgentByHandle(handleRaw) {",
    "    if (!officeState) return null;",
    "    const handle = officeAgentHandle(handleRaw);",
    "    if (!handle) return null;",
    "    return officeState.agents.find((agent) => officeAgentHandle(agent.name) === handle)",
    "        || officeState.agents.find((agent) => officeAgentHandle(agent.name).startsWith(handle))",
    "        || null;",
    "}",
    "",
    "function officeParseMentionCommand(messageRaw) {",
    "    const message = safeString(messageRaw).trim();",
    "    if (!message) return { command: 'status', args: '' };",
    "    const parts = message.split(/\\s+/);",
    "    const command = safeString(parts.shift()).toLowerCase();",
    "    const args = parts.join(' ').trim();",
    "    if (command === 'status' || command === 'where' || command === 'load') return { command: 'status', args };",
    "    if (command === 'break' || command === 'coffee' || command === 'lunch') return { command: 'break', args };",
    "    if (command === 'resume' || command === 'work') return { command: 'resume', args };",
    "    if (command === 'summon' || command === 'lobby') return { command: 'summon', args };",
    "    if (command === 'focus') return { command: 'focus', args };",
    "    if (command === 'task') return { command: 'task', args };",
    "    return { command: 'message', args: message };",
    "}",
    "",
    "function officeHandleMention(agent, messageRaw) {",
    "    if (!officeState || !agent) return;",
    "    const message = safeString(messageRaw);",
    "    const lower = message.toLowerCase();",
    "    const parsed = officeParseMentionCommand(message);",
    "    let reply = '';",
    "",
    "    if (parsed.command === 'status') {",
    "        const activeCount = officeState.tasks.filter((task) => task.status === 'active').length;",
    "        const room = officeCurrentRoomForAgent(agent);",
    "        const status = officePick(OFFICE_DIALOGUE.mentionStatus).replace('{count}', String(activeCount));",
    "        reply = `${status} I am in ${room?.label || 'the hallway'} right now.`;",
    "    } else if (parsed.command === 'break') {",
    "        const breakTarget = officeChance(0.5) ? 'room-coffee' : 'room-break';",
    "        officeRouteAgentToRoom(agent, breakTarget, {",
    "            intent: 'break',",
    "            speed: officeRandomRange(2.8, 3.9),",
    "        });",
    "        agent.nextBreakAt = performance.now() + officeRandomRange(40_000, 88_000);",
    "        reply = 'Copy. Taking a short break loop and returning to queue.';",
    "    } else if (parsed.command === 'resume') {",
    "        agent.state = 'idle';",
    "        agent.intent = 'wander';",
    "        agent.idleUntil = performance.now() + officeRandomRange(320, 1200);",
    "        const routed = officeRouteAgentToRoom(agent, 'room-lobby', {",
    "            intent: 'wander',",
    "            speed: officeRandomRange(2.8, 3.8),",
    "        });",
    "        reply = routed ? 'Resuming active route from lobby.' : 'Resuming in place.';",
    "    } else if (parsed.command === 'summon') {",
    "        officeRouteAgentToRoom(agent, 'room-lobby', {",
    "            intent: 'wander',",
    "            speed: officeRandomRange(3.2, 4.1),",
    "        });",
    "        reply = 'On my way to Main Lobby.';",
    "    } else if (parsed.command === 'focus') {",
    "        const target = safeString(parsed.args).toLowerCase();",
    "        const matched = OFFICE_TASK_ROOM_RULES.find((rule) => rule.pattern.test(target));",
    "        const roomId = matched?.roomId || 'room-pods';",
    "        const room = officeRoomById(roomId);",
    "        officeRouteAgentToRoom(agent, roomId, {",
    "            intent: 'wander',",
    "            speed: officeRandomRange(3.1, 4.1),",
    "        });",
    "        reply = `Switching to focus in ${room?.label || 'Focus Pods'}.`;",
    "    } else if (parsed.command === 'task' || OFFICE_TASK_KEYWORDS.test(message) || lower.includes('build') || lower.includes('ship')) {",
    "        const taskText = parsed.command === 'task' ? (parsed.args || 'new task') : message;",
    "        const task = officeQueueTask(taskText, {",
    "            source: `mention:${agent.id}`,",
    "            announce: false,",
    "            preferredAgentId: agent.id,",
    "        });",
    "        if (task && task.assignedAgentId === agent.id) {",
    "            reply = `Picked it up. I am moving to ${task.roomLabel}.`;",
    "        } else if (task) {",
    "            reply = `Queued it in ${task.roomLabel}. I will grab it after my current task.`;",
    "        } else {",
    "            reply = officePick(OFFICE_DIALOGUE.mention);",
    "        }",
    "    } else {",
    "        reply = officePick(OFFICE_DIALOGUE.mention);",
    "    }",
    "",
    "    if (officeSpeak(agent, reply, { priority: true, durationMs: 1700 })) {",
    "        officePushChatLine(`@${agent.name}: ${reply}`);",
    "        officeBusEmit('agent.mention', {",
    "            agentId: agent.id,",
    "            agentName: agent.name,",
    "            command: parsed.command,",
    "            args: safeString(parsed.args).slice(0, 160),",
    "        });",
    "    }",
    "}",
    "",
    "function officeHandleAgentTap(agentId) {",
    "    if (!officeState) return;",
    "    const agent = officeGetAgentById(agentId);",
    "    if (!agent) return;",
    "    officeState.selectedAgentId = agent.id;",
    "    officeSyncCustomizerFields();",
    "    if (safeString(officeState.followAgentId)) {",
    "        officeSetFollowMode(true, agent.id);",
    "    }",
    "    const now = performance.now();",
    "    const exit = officePlanRunawayExit(agent);",
    "    agent.jumpUntil = now + 460;",
    "    agent.bumpUntil = now + 460;",
    "    agent.state = 'runaway';",
    "    agent.intent = 'runaway';",
    "    agent.returnAfterRunAt = now + officeClamp(OFFICE_RUNAWAY_DURATION_MS * 0.46, 2000, 3200);",
    "    agent.taskId = '';",
    "    agent.facing = exit.x >= agent.x ? 1 : -1;",
    "    agent.runawayExitX = exit.x;",
    "    agent.runawayExitY = exit.y;",
    "    agent.runawayPhase = 'to-hall';",
    "    agent.routeWaypoints = [];",
    "    agent.routeDestinationNodeId = '';",
    "    const routed = officeRouteAgentToNode(agent, exit.hallId, {",
    "        intent: 'runaway',",
    "        speed: officeRandomRange(5.2, 6.8),",
    "    });",
    "    if (!routed) {",
    "        agent.runawayPhase = 'exiting';",
    "        officeSetAgentTarget(agent, exit.x, exit.y, {",
    "            intent: 'runaway',",
    "            speed: officeRandomRange(6.1, 7.8),",
    "        });",
    "    }",
    "    agent.state = 'runaway';",
    "    agent.intent = 'runaway';",
    "    const line = officePick(OFFICE_DIALOGUE.clicked);",
    "    officeSpeak(agent, line, { priority: true, durationMs: 1200 });",
    "    officePushChatLine(`${agent.name}: ${line}`);",
    "    officePulseHaptic([14, 24, 10]);",
    "    officeBusEmit('agent.tapped', {",
    "        agentId: agent.id,",
    "        agentName: agent.name,",
    "        runawayPhase: agent.runawayPhase,",
    "    });",
    "    officeState.tasks.forEach((task) => {",
    "        if (task.assignedAgentId === agent.id && task.status === 'active') {",
    "            task.status = 'queued';",
    "            task.assignedAgentId = '';",
    "            task.startedAt = 0;",
    "            officeState.tasksDirty = true;",
    "        }",
    "    });",
    "}",
    "",
    "function officeHandleChatSend() {",
    "    if (!officeState || !officeChatInput) return;",
    "    const input = safeString(officeChatInput.value);",
    "    if (!input) return;",
    "    officeChatInput.value = '';",
    "",
    "    const slashMatch = input.match(/^\\/([a-z_-]+)\\s*(.*)$/i);",
    "    if (slashMatch) {",
    "        const command = safeString(slashMatch[1]).toLowerCase();",
    "        const args = safeString(slashMatch[2]).trim();",
    "        if (command === 'summon' || command === 'break' || command === 'resume') {",
    "            officeRunQuickAction(command);",
    "            return;",
    "        }",
    "        if (command === 'focus') {",
    "            const mapped = OFFICE_TASK_ROOM_RULES.find((rule) => rule.pattern.test(args));",
    "            const roomId = mapped?.roomId || 'room-pods';",
    "            officeRunQuickAction(`focus:${roomId}`);",
    "            return;",
    "        }",
    "    }",
    "",
    "    const mentionMatch = input.match(/^@([a-z0-9._-]+)\\s*(.*)$/i);",
    "    if (mentionMatch) {",
    "        const handle = mentionMatch[1];",
    "        const message = safeString(mentionMatch[2]);",
    "        const agent = officeFindAgentByHandle(handle);",
    "        if (!agent) {",
    "            const handles = officeState.agents.map((entry) => `@${officeAgentHandle(entry.name)}`).join(', ');",
    "            officePushChatLine(`No agent found for @${handle}. Available: ${handles}`);",
    "            return;",
    "        }",
    "        officePushChatLine(`You -> @${agent.name}: ${message || 'status?'}`, 'user');",
    "        officeHandleMention(agent, message || 'status');",
    "        return;",
    "    }",
    "",
    "    officeQueueTask(input, { source: 'office-chat', announce: true });",
    "}",
    "",
    "function officeRunQuickAction(actionRaw) {",
    "    if (!officeState) return;",
    "    const action = safeString(actionRaw).toLowerCase();",
    "    const now = performance.now();",
    "    const eventPayload = {",
    "        action,",
    "        at: Date.now(),",
    "    };",
    "    if (action === 'summon') {",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            officeRouteAgentToRoom(agent, 'room-lobby', {",
    "                intent: 'wander',",
    "                speed: officeRandomRange(3.1, 4.2),",
    "            });",
    "        });",
    "        officePushChatLine('System: All agents summoned to the Main Lobby.');",
    "        officePulseHaptic([12, 18, 12]);",
    "        officeBusEmit('quick_action.run', eventPayload, now);",
    "        return;",
    "    }",
    "    if (action === 'break') {",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            const breakRoomId = officeChance(0.5) ? 'room-coffee' : 'room-break';",
    "            officeRouteAgentToRoom(agent, breakRoomId, {",
    "                intent: 'break',",
    "                speed: officeRandomRange(2.9, 3.8),",
    "            });",
    "            agent.nextBreakAt = now + officeRandomRange(42_000, 94_000);",
    "            if (officeChance(0.42)) {",
    "                officeSpeak(agent, officeBanterForAgent(agent, 'break', {",
    "                    roomTheme: officeRoomById(breakRoomId)?.theme || '',",
    "                }), { priority: true, durationMs: 1200 });",
    "            }",
    "        });",
    "        officePushChatLine('System: Break wave sent. Agents are rotating to coffee/lunch rooms.');",
    "        officePulseHaptic([10, 20, 10]);",
    "        officeBusEmit('quick_action.run', eventPayload, now);",
    "        return;",
    "    }",
    "    if (action === 'resume') {",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            const assignedTask = agent.taskId",
    "                ? officeState.tasks.find((task) => task.id === agent.taskId && task.status !== 'done')",
    "                : null;",
    "            if (assignedTask) {",
    "                officeRouteAgentToRoom(agent, assignedTask.roomId, {",
    "                    intent: 'task',",
    "                    speed: officeRandomRange(3.2, 4.2),",
    "                });",
    "                return;",
    "            }",
    "            agent.state = 'idle';",
    "            agent.intent = 'wander';",
    "            agent.idleUntil = now + officeRandomRange(400, 1200);",
    "        });",
    "        officePushChatLine('System: Resume signal sent. Agents are returning to active work routing.');",
    "        officePulseHaptic(14);",
    "        officeBusEmit('quick_action.run', eventPayload, now);",
    "        return;"
].join("\n");
