/* split from part-012.js */
export default [
    "                if (((x + (y * 2)) % 7) === 0) {",
    "                    ctx.fillStyle = accent;",
    "                    ctx.fillRect(ox + x, oy + y, 1, 1);",
    "                } else if (((x * 3) + y) % 13 === 0) {",
    "                    ctx.fillStyle = accentTwo;",
    "                    ctx.fillRect(ox + x, oy + y, 1, 1);",
    "                }",
    "            }",
    "        }",
    "        if (line) {",
    "            ctx.fillStyle = line;",
    "            ctx.fillRect(ox, oy + (tile / 2) - 1, tile, 1);",
    "            ctx.fillRect(ox + (tile / 2) - 1, oy, 1, tile);",
    "        }",
    "    };",
    "",
    "    const stampSprite = (col, row, pixels, palette, scale = 3) => {",
    "        const ox = col * tile;",
    "        const oy = row * tile;",
    "        const rowsRaw = Array.isArray(pixels) ? pixels : [];",
    "        rowsRaw.forEach((lineRaw, rowIndex) => {",
    "            const line = safeString(lineRaw);",
    "            for (let charIndex = 0; charIndex < line.length; charIndex += 1) {",
    "                const code = line.charAt(charIndex);",
    "                const fill = palette?.[code];",
    "                if (!fill) continue;",
    "                ctx.fillStyle = fill;",
    "                ctx.fillRect(",
    "                    ox + (charIndex * scale),",
    "                    oy + (rowIndex * scale),",
    "                    scale,",
    "                    scale,",
    "                );",
    "            }",
    "        });",
    "    };",
    "",
    "    fillTile(0, 0, '#e7f1fb', '#d7e6f7', '#c5d8ee', 'rgba(105, 134, 170, 0.36)');",
    "    fillTile(1, 0, '#d7ebff', '#c4ddfb', '#b0cef1', 'rgba(82, 123, 182, 0.34)');",
    "    fillTile(2, 0, '#eadffb', '#dccff4', '#c8bbe8', 'rgba(119, 101, 170, 0.32)');",
    "    fillTile(3, 0, '#d9f0e9', '#c8e3d8', '#b4d3c5', 'rgba(87, 134, 117, 0.32)');",
    "    fillTile(4, 0, '#f6e9d5', '#ebd9bf', '#dfc6a5', 'rgba(146, 110, 67, 0.34)');",
    "    fillTile(5, 0, '#dff0ff', '#cee4f6', '#bbd3eb', 'rgba(86, 126, 173, 0.34)');",
    "",
    "    fillTile(0, 1, '#edf5ff', '#deebf8', '#cfdef0', 'rgba(109, 140, 178, 0.36)');",
    "    fillTile(1, 1, '#d8e9ff', '#c7dcf8', '#b4ceec', 'rgba(75, 117, 176, 0.36)');",
    "    fillTile(2, 1, '#e5dcfa', '#d4c8ef', '#c1b2e1', 'rgba(111, 96, 160, 0.34)');",
    "    fillTile(3, 1, '#d5eee6', '#c2e0d2', '#adcfbf', 'rgba(79, 126, 108, 0.34)');",
    "    fillTile(4, 1, '#f3e2cb', '#e7d2b2', '#d8be98', 'rgba(140, 104, 60, 0.34)');",
    "    fillTile(5, 1, '#d8e9fb', '#c5dcf1', '#b1cae6', 'rgba(72, 112, 159, 0.36)');",
    "",
    "    fillTile(0, 2, '#e5effb', '#d4e4f3', '#c3d8eb', 'rgba(94, 126, 166, 0.34)');",
    "    fillTile(1, 2, '#d6e6ff', '#c4d9f8', '#afcaec', 'rgba(65, 107, 163, 0.36)');",
    "    fillTile(2, 2, '#e0d8f7', '#d0c3ec', '#beaee0', 'rgba(104, 90, 152, 0.32)');",
    "    fillTile(3, 2, '#d2eadf', '#bfd9ca', '#abc8b4', 'rgba(77, 119, 102, 0.34)');",
    "    fillTile(4, 2, '#eedbc0', '#e2caa7', '#d4b58d', 'rgba(132, 97, 57, 0.34)');",
    "    fillTile(5, 2, '#d2e3f7', '#bfd5ee', '#a9c7e4', 'rgba(66, 105, 153, 0.34)');",
    "",
    "    // Extra hallway surfaces and trim variants.",
    "    fillTile(6, 0, '#f1f5fb', '#e2ebf4', '#d2dfec', 'rgba(91, 116, 150, 0.26)');",
    "    fillTile(7, 0, '#ece4f3', '#dccfe6', '#cabed6', 'rgba(106, 90, 130, 0.24)');",
    "    fillTile(8, 0, '#e3f1eb', '#d1e2d8', '#bfd3c8', 'rgba(87, 116, 103, 0.24)');",
    "    fillTile(9, 0, '#f3eadf', '#e4d8c4', '#d3c5ac', 'rgba(121, 102, 72, 0.24)');",
    "    fillTile(10, 0, '#e2edfb', '#d1e2f3', '#bed3e9', 'rgba(72, 108, 155, 0.24)');",
    "    fillTile(11, 0, '#f0eaf6', '#e0d9ed', '#cec5e3', 'rgba(110, 96, 139, 0.24)');",
    "    fillTile(6, 1, '#e7effa', '#d6e3f2', '#c3d4e7', 'rgba(82, 109, 141, 0.28)');",
    "    fillTile(7, 1, '#ecf1fa', '#dbe5f1', '#c9d8e9', 'rgba(92, 118, 151, 0.28)');",
    "    fillTile(8, 1, '#dde8f3', '#cbd9e8', '#b7cade', 'rgba(79, 103, 133, 0.28)');",
    "    fillTile(9, 1, '#d9e4f0', '#c6d5e6', '#b2c5db', 'rgba(75, 100, 131, 0.3)');",
    "    fillTile(10, 1, '#e0ebf7', '#cddced', '#b9cde2', 'rgba(82, 108, 140, 0.3)');",
    "    fillTile(11, 1, '#e7eef8', '#d5e1ee', '#c1d2e4', 'rgba(90, 115, 147, 0.3)');",
    "",
    "    const spritePalette = {",
    "        o: '#22344f',",
    "        a: '#47688f',",
    "        b: '#5f88b6',",
    "        c: '#87add8',",
    "        d: '#b8d5f0',",
    "        e: '#e8f3ff',",
    "        f: '#5a9b74',",
    "        g: '#7bc296',",
    "        h: '#b0e3c4',",
    "        i: '#927ab7',",
    "        j: '#c4afe6',",
    "        k: '#f0c170',",
    "        l: '#ffe2a5',",
    "        m: '#b76a54',",
    "        n: '#dd9d7e',",
    "        p: '#6f86aa',",
    "        q: '#a3bad7',",
    "        r: '#d8e6f5',",
    "    };",
    "",
    "    stampSprite(0, 3, [",
    "        '........',",
    "        '.oooooo.',",
    "        '.obbbbo.',",
    "        '.ocddco.',",
    "        '.ocddco.',",
    "        '.obppbo.',",
    "        '.oqqqqo.',",
    "        '..o..o..',",
    "    ], spritePalette);",
    "    stampSprite(1, 3, [",
    "        '........',",
    "        '..oooo..',",
    "        '.obddbo.',",
    "        '.obrrbo.',",
    "        '.obrrbo.',",
    "        '..oooo..',",
    "        '.oo..oo.',",
    "        '........',",
    "    ], spritePalette);",
    "    stampSprite(2, 3, [",
    "        '........',",
    "        '...oo...',",
    "        '..obbo..',",
    "        '.obddbo.',",
    "        '.obddbo.',",
    "        '..obbo..',",
    "        '..o..o..',",
    "        '...oo...',",
    "    ], spritePalette);",
    "    stampSprite(3, 3, [",
    "        '........',",
    "        '.oooooo.',",
    "        '.okkkko.',",
    "        '.okllko.',",
    "        '.okllko.',",
    "        '.okkkko.',",
    "        '.oooooo.',",
    "        '........',",
    "    ], spritePalette);",
    "    stampSprite(4, 3, [",
    "        '........',",
    "        '.oooooo.',",
    "        '.onnnno.',",
    "        '.onnnno.',",
    "        '.ommmmo.',",
    "        '.ommmmo.',",
    "        '.oooooo.',",
    "        '........',",
    "    ], spritePalette);",
    "    stampSprite(5, 3, [",
    "        '...ff...',",
    "        '..fggf..',",
    "        '..fggf..',",
    "        '...ff...',",
    "        '..aaaa..',",
    "        '..apqa..',",
    "        '..apqa..',",
    "        '..aaaa..',",
    "    ], spritePalette);",
    "    stampSprite(6, 3, [",
    "        '........',",
    "        '.oooooo.',",
    "        '.obbbbo.',",
    "        '.obbbbo.',",
    "        '.obbbbo.',",
    "        '.obbbbo.',",
    "        '.oooooo.',",
    "        '........',",
    "    ], spritePalette);",
    "    stampSprite(7, 3, [",
    "        '.eeeeee.',",
    "        '.errrre.',",
    "        '.errrre.',",
    "        '.errrre.',",
    "        '.errrre.',",
    "        '.eeeeee.',",
    "        '..oooo..',",
    "        '..oooo..',",
    "    ], spritePalette);",
    "    stampSprite(8, 3, [",
    "        '........',",
    "        '..kkkk..',",
    "        '..kllk..',",
    "        '..kkkk..',",
    "        '...oo...',",
    "        '..obbo..',",
    "        '..obbo..',",
    "        '..oooo..',",
    "    ], spritePalette);",
    "    stampSprite(9, 3, [",
    "        '........',",
    "        '.oooooo.',",
    "        '.obddbo.',",
    "        '.obddbo.',",
    "        '.obddbo.',",
    "        '.obddbo.',",
    "        '.obbbbo.',",
    "        '.oooooo.',",
    "    ], spritePalette);",
    "    stampSprite(10, 3, [",
    "        '........',",
    "        '..oooo..',",
    "        '.obddbo.',",
    "        '.obddbo.',",
    "        '..oooo..',",
    "        '...oo...',",
    "        '..oooo..',",
    "        '........',",
    "    ], spritePalette);",
    "    stampSprite(11, 3, [",
    "        '........',",
    "        '..eeee..',",
    "        '..eeee..',",
    "        '...oo...',",
    "        '...oo...',",
    "        '...oo...',",
    "        '..obbo..',",
    "        '..obbo..',",
    "    ], spritePalette);",
    "",
    "    stampSprite(0, 4, [",
    "        '.eeeeee.',",
    "        '.edddde.',",
    "        '.edddde.',",
    "        '.edddde.',",
    "        '.edddde.',",
    "        '.eeeeee.',",
    "        '........',",
    "        '........',",
    "    ], spritePalette);",
    "    stampSprite(1, 4, [",
    "        '........',",
    "        '.oooooo.',",
    "        '.obbbbo.',",
    "        '.obkkbo.',",
    "        '.obkkbo.',",
    "        '.obbbbo.',",
    "        '.oooooo.',",
    "        '........',",
    "    ], spritePalette);",
    "    stampSprite(2, 4, [",
    "        '........',",
    "        '.oo..oo.',",
    "        '.obddbo.',",
    "        '.obddbo.',",
    "        '.obddbo.',"
].join("\n");
