/* app.js lines 1-1000 */
export default [
    "/**",
    " * Thomas UI - Super Cool & Neat Edition",
    " * Minimal, clean, vanilla JS to power the thoughtful interface.",
    " */",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  GLOBAL STATE & CONSTANTS                                               ║",
    "// ║  Chat state, game constants, composer presets, DOM element refs          ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "// Basic State",
    "let chatHistory = [];",
    "let isGenerating = false;",
    "let currentAbortController = null;",
    "let pendingDocs = [];",
    "let pendingImages = [];",
    "let pendingSendQueue = [];",
    "let queuedSendDrainActive = false;",
    "let sessionId = \"\";",
    "let activeChatId = \"\";",
    "let composerInputLockUntil = 0;",
    "let composerActionsOpen = false;",
    "let composerModeSelection = null;",
    "",
    "const CHAT_GAME_HIGHSCORE_STORAGE_KEYS = {",
    "    cloud_jump: 'thomas.chat_game.cloud_jump.high_score.v1',",
    "    jetpack_joyride: 'thomas.chat_game.jetpack_joyride.high_score.v1',",
    "    dino_run: 'thomas.chat_game.dino_run.high_score.v1',",
    "};",
    "const CHAT_GAME_BOT_WRAP_SIZE = 34;",
    "const CHAT_GAME_DOOR_BOT_MOUNT_LEFT = 8;",
    "const CHAT_GAME_DOOR_BOT_MOUNT_BOTTOM = 8;",
    "const CHAT_GAME_DOOR_BOT_ENTER_OFFSET_START = -8;",
    "const CHAT_GAME_DOOR_BOT_ENTER_OFFSET_END = 12;",
    "const CHAT_GAME_LAUNCH_PLATFORM_FALL_SPEED = 3.1;",
    "const CHAT_GAME_START_X_RATIO = 0.5;",
    "const CHAT_GAME_PLATFORM_MIN_WIDTH = 98;",
    "const CHAT_GAME_PLATFORM_MAX_WIDTH = 154;",
    "const CHAT_GAME_PLATFORM_GAP_MIN = 40;",
    "const CHAT_GAME_PLATFORM_GAP_MAX = 58;",
    "const CHAT_GAME_PLATFORM_PATH_STEP = 46;",
    "const CHAT_GAME_PLATFORM_DRIFT_MAX = 0.11;",
    "const CHAT_GAME_PLATFORM_DRIFT_CHANCE = 0.24;",
    "const CHAT_GAME_PLATFORM_CENTER_RATIO = 0.5;",
    "const CHAT_GAME_PLATFORM_CENTER_FOLLOW = 0.13;",
    "const CHAT_GAME_PLATFORM_CENTER_CORRECTION = 0.26;",
    "const CHAT_GAME_PLATFORM_SAFE_MARGIN = 14;",
    "const CHAT_GAME_PLATFORM_RUNWAY_COUNT = 10;",
    "const CHAT_GAME_PLATFORM_LAUNCH_RESPAWN_SECONDS = 6.2;",
    "const JETPACK_GAME_ID = 'jetpack_joyride';",
    "const DINO_GAME_ID = 'dino_run';",
    "const JETPACK_INTRO_DURATION_SECONDS = 2.6;",
    "const JETPACK_FLIGHT_START_X = -170;",
    "const JETPACK_FLIGHT_START_Y = -122;",
    "const JETPACK_PLAYER_X_RATIO = 0.22;",
    "const JETPACK_PLAYER_Y_RATIO = 0.52;",
    "const JETPACK_MOVE_SPEED = 5.7;",
    "const JETPACK_PLAYER_TOP_PADDING = 8;",
    "const JETPACK_PLAYER_BOTTOM_PADDING = 24;",
    "const JETPACK_SCROLL_BASE = 4.1;",
    "const JETPACK_SCROLL_MAX_BONUS = 3.1;",
    "const JETPACK_SPAWN_FRAMES_MIN = 48;",
    "const JETPACK_SPAWN_FRAMES_MAX = 86;",
    "const JETPACK_ZAPPER_LENGTH_MIN = 112;",
    "const JETPACK_ZAPPER_LENGTH_MAX = 182;",
    "const JETPACK_ZAPPER_THICKNESS = 12;",
    "const JETPACK_MISSILE_WIDTH = 52;",
    "const JETPACK_MISSILE_HEIGHT = 18;",
    "const JETPACK_LASER_WIDTH = 26;",
    "const JETPACK_LASER_HEIGHT_MIN = 128;",
    "const JETPACK_LASER_HEIGHT_MAX = 210;",
    "const JETPACK_HITBOX_PADDING = 4;",
    "const DINO_INTRO_DURATION_SECONDS = 2.1;",
    "const DINO_GROUND_PADDING = 34;",
    "const DINO_PLAYER_X_RATIO = 0.2;",
    "const DINO_PLAYER_NORMAL_HEIGHT = 34;",
    "const DINO_PLAYER_DUCK_HEIGHT = 24;",
    "const DINO_PLAYER_WIDTH = 30;",
    "const DINO_GRAVITY = 0.48;",
    "const DINO_JUMP_VELOCITY = -10.4;",
    "const DINO_SCROLL_BASE = 4.2;",
    "const DINO_SCROLL_MAX_BONUS = 3.9;",
    "const DINO_SPAWN_FRAMES_MIN = 52;",
    "const DINO_SPAWN_FRAMES_MAX = 96;",
    "const COMPOSER_MODE_PRESETS = {",
    "    research: {",
    "        id: 'research',",
    "        label: 'Research',",
    "        promptPrefix: 'Mode: Deep research. Provide a concise but thorough answer with prioritized findings and concrete next steps.',",
    "    },",
    "    create_image: {",
    "        id: 'create_image',",
    "        label: 'Create image',",
    "        promptPrefix: 'Mode: Create image. Respond with a polished concept plus a final production-ready image prompt.',",
    "    },",
    "    create_video: {",
    "        id: 'create_video',",
    "        label: 'Create video',",
    "        promptPrefix: 'Mode: Create video. Respond with concept, shot plan, and a final video generation prompt.',",
    "    },",
    "    create_song: {",
    "        id: 'create_song',",
    "        label: 'Create song',",
    "        promptPrefix: 'Mode: Create song. Respond with mood, structure, lyrics, and a polished generation prompt.',",
    "    },",
    "    add_files: {",
    "        id: 'add_files',",
    "        label: 'Add files',",
    "        promptPrefix: '',",
    "    },",
    "    games: {",
    "        id: 'games',",
    "        label: 'Games',",
    "        promptPrefix: '',",
    "    },",
    "    cloud_jump: {",
    "        id: 'cloud_jump',",
    "        label: 'Cloud Jump: Office Bot',",
    "        promptPrefix: '',",
    "        kind: 'game',",
    "    },",
    "    jetpack_joyride: {",
    "        id: 'jetpack_joyride',",
    "        label: 'Jetpack Joyride: Office Bot',",
    "        promptPrefix: '',",
    "        kind: 'game',",
    "    },",
    "    dino_run: {",
    "        id: 'dino_run',",
    "        label: 'Dino Run: Office Bot',",
    "        promptPrefix: '',",
    "        kind: 'game',",
    "    },",
    "};",
    "",
    "const chatGameRuntime = {",
    "    activeGameId: '',",
    "    rafId: 0,",
    "    lastFrameMs: 0,",
    "    input: {",
    "        left: false,",
    "        right: false,",
    "        up: false,",
    "        down: false,",
    "        thrust: false,",
    "    },",
    "    cloudJump: null,",
    "    jetpackJoyride: null,",
    "    dinoRun: null,",
    "};",
    "",
    "// DOM Elements",
    "const welcomeScreen = document.getElementById('welcomeScreen');",
    "const chatScrollArea = document.getElementById('chatScrollArea');",
    "const chatMessagesInner = document.getElementById('chatMessagesInner');",
    "const composerTextarea = document.getElementById('composerTextarea');",
    "const sendBtn = document.getElementById('sendBtn');",
    "const micBtn = document.getElementById('micBtn');",
    "const attachBtn = document.getElementById('attachBtn');",
    "const attachmentsPreview = document.getElementById('attachmentsPreview');",
    "const docFileInput = document.getElementById('docFileInput');",
    "const composerActionPopover = document.getElementById('composerActionPopover');",
    "const composerActionList = document.getElementById('composerActionList');",
    "const composerGamesColumn = document.getElementById('composerGamesColumn');",
    "const composerModeChip = document.getElementById('composerModeChip');",
    "const composerModeChipLabel = document.getElementById('composerModeChipLabel');",
    "const composerModeChipCloseBtn = document.getElementById('composerModeChipCloseBtn');",
    "const composerBox = document.querySelector('.composer-box');",
    "const toastContainer = document.getElementById('toastContainer');",
    "const composerDisclaimer = document.getElementById('composerDisclaimer');",
    "const chatGamePanel = document.getElementById('chatGamePanel');",
    "const chatGameLane = document.getElementById('chatGameLane');",
    "const chatGameCanvas = document.getElementById('chatGameCanvas');",
    "const chatGameDoor = document.getElementById('chatGameDoor');",
    "const chatGameBotWrap = document.getElementById('chatGameBotWrap');",
    "const chatGameBot = document.getElementById('chatGameBot');",
    "const chatGameBotName = document.getElementById('chatGameBotName');",
    "const chatGameCloseBtn = document.getElementById('chatGameCloseBtn');",
    "const chatGameRestartBtn = document.getElementById('chatGameRestartBtn');",
    "const chatGameScore = document.getElementById('chatGameScore');",
    "const chatGameHighScore = document.getElementById('chatGameHighScore');",
    "const chatGameStatusText = document.getElementById('chatGameStatusText');",
    "const composerDinoShell = document.getElementById('composerDinoShell');",
    "const composerDinoCanvas = document.getElementById('composerDinoCanvas');",
    "const composerDinoHud = document.getElementById('composerDinoHud');",
    "const composerDinoScore = document.getElementById('composerDinoScore');",
    "const composerDinoHighScore = document.getElementById('composerDinoHighScore');",
    "const composerDinoStatusText = document.getElementById('composerDinoStatusText');",
    "const chatGamePortal = document.getElementById('chatGamePortal');",
    "const assistantSuggestionRail = document.getElementById('assistantSuggestionRail');",
    "const assistantSuggestionTitle = document.getElementById('assistantSuggestionTitle');",
    "const assistantSuggestionBubbles = document.getElementById('assistantSuggestionBubbles');",
    "const assistantSuggestionDismissBtn = document.getElementById('assistantSuggestionDismissBtn');",
    "",
    "// New Phase 5 Elements",
    "const appRoot = document.getElementById('app');",
    "const sidebar = document.getElementById('sidebar');",
    "const sidebarToggleBtn = document.getElementById('sidebarToggleBtn');",
    "const sidebarCollapseBtn = document.getElementById('sidebarCollapseBtn');",
    "const modelSelector = document.getElementById('modelSelector');",
    "const newChatSidebar = document.getElementById('newChatSidebar');",
    "const navChatBtn = document.getElementById('navChatBtn');",
    "const navOfficeBtn = document.getElementById('navOfficeBtn');",
    "const navMissionBtn = document.getElementById('navMissionBtn');",
    "const navContentBtn = document.getElementById('navContentBtn');",
    "const topNav = document.querySelector('.top-nav');",
    "const mainContent = document.querySelector('.main-content');",
    "const composerContainer = document.querySelector('.composer-container');",
    "const officeWorkspace = document.getElementById('officeWorkspace');",
    "const officeSceneWrap = document.querySelector('.office-scene-wrap');",
    "const officeScenePanzoom = document.getElementById('officeScenePanzoom');",
    "const officeScene = document.getElementById('officeScene');",
    "const officeEditorModal = document.getElementById('officeEditorModal');",
    "const officeEditorToggleBtn = document.getElementById('officeEditorToggleBtn');",
    "const officeEditorCloseBtn = document.getElementById('officeEditorCloseBtn');",
    "const officeTaskList = document.getElementById('officeTaskList');",
    "const officeAgentSelect = document.getElementById('officeAgentSelect');",
    "const officeAgentNameInput = document.getElementById('officeAgentNameInput');",
    "const officeAgentColorInput = document.getElementById('officeAgentColorInput');",
    "const officeAgentCostumeSelect = document.getElementById('officeAgentCostumeSelect');",
    "const officeActionSummonBtn = document.getElementById('officeActionSummonBtn');",
    "const officeActionBreakBtn = document.getElementById('officeActionBreakBtn');",
    "const officeActionResumeBtn = document.getElementById('officeActionResumeBtn');",
    "const officeZoomOutBtn = document.getElementById('officeZoomOutBtn');",
    "const officeZoomInBtn = document.getElementById('officeZoomInBtn');",
    "const officeZoomResetBtn = document.getElementById('officeZoomResetBtn');",
    "const officeDebugToggleBtn = document.getElementById('officeDebugToggleBtn');",
    "const officeMinimap = document.getElementById('officeMinimap');",
    "const officeMinimapCanvas = document.getElementById('officeMinimapCanvas');",
    "const officeFollowToggleBtn = document.getElementById('officeFollowToggleBtn');",
    "const officeDebugOverlay = document.getElementById('officeDebugOverlay');",
    "const officeChatLog = document.getElementById('officeChatLog');",
    "const officeChatInput = document.getElementById('officeChatInput');",
    "const officeChatSendBtn = document.getElementById('officeChatSendBtn');",
    "const missionWorkspace = document.getElementById('missionWorkspace');",
    "const contentWorkspace = document.getElementById('contentWorkspace');",
    "const missionConnectionPill = document.getElementById('missionConnectionPill');",
    "const missionUpdatedAt = document.getElementById('missionUpdatedAt');",
    "const missionOpsNowTitle = document.getElementById('missionOpsNowTitle');",
    "const missionOpsNowMeta = document.getElementById('missionOpsNowMeta');",
    "const missionOpsNextTitle = document.getElementById('missionOpsNextTitle');",
    "const missionOpsNextMeta = document.getElementById('missionOpsNextMeta');",
    "const missionOpsBlockersTitle = document.getElementById('missionOpsBlockersTitle');",
    "const missionOpsBlockersMeta = document.getElementById('missionOpsBlockersMeta');",
    "const missionKpiActiveAgents = document.getElementById('missionKpiActiveAgents');",
    "const missionKpiActiveMeta = document.getElementById('missionKpiActiveMeta');",
    "const missionKpiApprovals = document.getElementById('missionKpiApprovals');",
    "const missionKpiApprovalsMeta = document.getElementById('missionKpiApprovalsMeta');",
    "const missionKpiRisks = document.getElementById('missionKpiRisks');",
    "const missionKpiRisksMeta = document.getElementById('missionKpiRisksMeta');",
    "const missionKpiEngine = document.getElementById('missionKpiEngine');",
    "const missionKpiEngineMeta = document.getElementById('missionKpiEngineMeta');",
    "const missionPriorityMeta = document.getElementById('missionPriorityMeta');",
    "const missionPriorityList = document.getElementById('missionPriorityList');",
    "const missionJobsMeta = document.getElementById('missionJobsMeta');",
    "const missionJobsList = document.getElementById('missionJobsList');",
    "const missionJobsTaskCount = document.getElementById('missionJobsTaskCount');",
    "const missionJobsCronCount = document.getElementById('missionJobsCronCount');",
    "const missionCreateMeta = document.getElementById('missionCreateMeta');",
    "const missionJobForm = document.getElementById('missionJobForm');",
    "const missionJobTemplates = document.getElementById('missionJobTemplates');",
    "const missionJobNameInput = document.getElementById('missionJobNameInput');",
    "const missionJobPromptInput = document.getElementById('missionJobPromptInput');",
    "const missionJobModeSelect = document.getElementById('missionJobModeSelect');",
    "const missionJobWorkflowInput = document.getElementById('missionJobWorkflowInput');",
    "const missionJobOnceAtRow = document.getElementById('missionJobOnceAtRow');",
    "const missionJobOnceAtInput = document.getElementById('missionJobOnceAtInput');",
    "const missionJobEverySecondsRow = document.getElementById('missionJobEverySecondsRow');",
    "const missionJobEverySecondsInput = document.getElementById('missionJobEverySecondsInput');",
    "const missionJobAtRow = document.getElementById('missionJobAtRow');",
    "const missionJobAtInput = document.getElementById('missionJobAtInput');",
    "const missionJobWeekdayRow = document.getElementById('missionJobWeekdayRow');",
    "const missionJobWeekdays = document.getElementById('missionJobWeekdays');",
    "const missionJobTimezoneRow = document.getElementById('missionJobTimezoneRow');",
    "const missionJobTimezoneInput = document.getElementById('missionJobTimezoneInput');",
    "const missionJobProfileInput = document.getElementById('missionJobProfileInput');",
    "const missionJobModelInput = document.getElementById('missionJobModelInput');",
    "const missionJobApprovalToggle = document.getElementById('missionJobApprovalToggle');",
    "const missionJobSubmitBtn = document.getElementById('missionJobSubmitBtn');",
    "const missionApprovalsMeta = document.getElementById('missionApprovalsMeta');",
    "const missionApprovalsList = document.getElementById('missionApprovalsList');",
    "const missionRoomsList = document.getElementById('missionRoomsList');",
    "const missionTimelineMeta = document.getElementById('missionTimelineMeta');",
    "const missionTimelineList = document.getElementById('missionTimelineList');",
    "const contentRefreshBtn = document.getElementById('contentRefreshBtn');",
    "const contentConnectedCount = document.getElementById('contentConnectedCount');",
    "const contentConnectedMeta = document.getElementById('contentConnectedMeta');",
    "const contentAudienceCount = document.getElementById('contentAudienceCount');",
    "const contentAudienceMeta = document.getElementById('contentAudienceMeta');",
    "const contentQueuedCount = document.getElementById('contentQueuedCount');",
    "const contentQueuedMeta = document.getElementById('contentQueuedMeta');",
    "const contentWorkflowCount = document.getElementById('contentWorkflowCount');",
    "const contentWorkflowMetaSummary = document.getElementById('contentWorkflowMetaSummary');",
    "const contentPlatformMeta = document.getElementById('contentPlatformMeta');",
    "const contentPlatformGrid = document.getElementById('contentPlatformGrid');",
    "const contentWorkflowMeta = document.getElementById('contentWorkflowMeta');",
    "const contentWorkflowGrid = document.getElementById('contentWorkflowGrid');",
    "const contentSchedulerMeta = document.getElementById('contentSchedulerMeta');",
    "const contentSchedulerRows = document.getElementById('contentSchedulerRows');",
    "const contentToolsMeta = document.getElementById('contentToolsMeta');",
    "const contentToolsGrid = document.getElementById('contentToolsGrid');",
    "const contentControlMeta = document.getElementById('contentControlMeta');",
    "const contentControlGrid = document.getElementById('contentControlGrid');",
    "const contentNavMeta = document.getElementById('contentNavMeta');",
    "const contentNavList = document.getElementById('contentNavList');",
    "const contentAxisMeta = document.getElementById('contentAxisMeta');",
    "const contentAxisList = document.getElementById('contentAxisList');",
    "const contentChecklistMeta = document.getElementById('contentChecklistMeta');",
    "const contentChecklistGrid = document.getElementById('contentChecklistGrid');",
    "const moduleWorkspace = document.getElementById('moduleWorkspace');",
    "const moduleWorkspaceTitle = document.getElementById('moduleWorkspaceTitle');",
    "const moduleWorkspaceSubtitle = document.getElementById('moduleWorkspaceSubtitle');",
    "const moduleWorkspaceModePill = document.getElementById('moduleWorkspaceModePill');",
    "const moduleWorkspaceMeta = document.getElementById('moduleWorkspaceMeta');",
    "const moduleKpiGrid = document.getElementById('moduleKpiGrid');",
    "const moduleSubnavRow = document.getElementById('moduleSubnavRow');",
    "const moduleSubnavList = document.getElementById('moduleSubnavList');",
    "const moduleFlairRow = document.getElementById('moduleFlairRow');",
    "const moduleFocusStrip = document.getElementById('moduleFocusStrip');",
    "const moduleSpecialGrid = document.getElementById('moduleSpecialGrid');",
    "const moduleWorkbench = document.getElementById('moduleWorkbench');",
    "const moduleQueuePanel = document.getElementById('moduleQueuePanel');",
    "const moduleQueueTitle = document.getElementById('moduleQueueTitle');",
    "const moduleQueueMeta = document.getElementById('moduleQueueMeta');",
    "const moduleQueueList = document.getElementById('moduleQueueList');",
    "const moduleHealthPanel = document.getElementById('moduleHealthPanel');",
    "const moduleHealthTitle = document.getElementById('moduleHealthTitle');",
    "const moduleHealthMeta = document.getElementById('moduleHealthMeta');",
    "const moduleHealthList = document.getElementById('moduleHealthList');",
    "const moduleActionsPanel = document.getElementById('moduleActionsPanel');",
    "const moduleActionsTitle = document.getElementById('moduleActionsTitle');",
    "const moduleActionsMeta = document.getElementById('moduleActionsMeta');",
    "const moduleActionsGrid = document.getElementById('moduleActionsGrid');",
    "const moduleActivityPanel = document.getElementById('moduleActivityPanel');",
    "const moduleActivityTitle = document.getElementById('moduleActivityTitle');",
    "const moduleActivityMeta = document.getElementById('moduleActivityMeta');",
    "const moduleActivityList = document.getElementById('moduleActivityList');",
    "const moduleTriagePanel = document.getElementById('moduleTriagePanel');",
    "const moduleTriageTitle = document.getElementById('moduleTriageTitle');",
    "const moduleTriageMeta = document.getElementById('moduleTriageMeta');",
    "const moduleTriageFilters = document.getElementById('moduleTriageFilters');",
    "const moduleTriageMessages = document.getElementById('moduleTriageMessages');",
    "const sidebarModeButtons = Array.from(document.querySelectorAll('.sidebar-nav [data-nav-mode]'));",
    "",
    "const settingsModal = document.getElementById('settingsModal');",
    "const settingsBtn = document.getElementById('settingsBtn');",
    "const closeSettingsBtn = document.getElementById('closeSettingsBtn');",
    "const saveSettingsBtn = document.getElementById('saveSettingsBtn');",
    "const settingTheme = document.getElementById('settingTheme');",
    "const settingAutonomy = document.getElementById('settingAutonomy');",
    "const settingFontSize = document.getElementById('settingFontSize');",
    "const settingFontSizeValue = document.getElementById('settingFontSizeValue');",
    "const settingBubbleStyle = document.getElementById('settingBubbleStyle');",
    "const settingMemoryEnabled = document.getElementById('settingMemoryEnabled');",
    "const settingDesktopNotifications = document.getElementById('settingDesktopNotifications');",
    "const settingsAdvancedToggle = document.getElementById('settingsAdvancedToggle');",
    "const settingsSuite = document.getElementById('settingsSuite');",
    "const settingsSectionNav = document.getElementById('settingsSectionNav');",
    "const settingsSectionSearch = document.getElementById('settingsSectionSearch');",
    "const settingsNavEmpty = document.getElementById('settingsNavEmpty');",
    "const settingsSections = document.getElementById('settingsSections');",
    "const settingsDisplayName = document.getElementById('settingsDisplayName');",
    "const settingsAccountMeta = document.getElementById('settingsAccountMeta');",
    "const settingsProfileAvatar = document.getElementById('settingsProfileAvatar');",
    "const settingsAvatarInput = document.getElementById('settingsAvatarInput');",
    "const changeAvatarBtn = document.getElementById('changeAvatarBtn');",
    "const removeAvatarBtn = document.getElementById('removeAvatarBtn');",
    "const settingVoice = document.getElementById('settingVoice');",
    "const settingVoiceSpeed = document.getElementById('settingVoiceSpeed');",
    "const settingVoiceSpeedValue = document.getElementById('settingVoiceSpeedValue');",
    "const settingWakeWordEnabled = document.getElementById('settingWakeWordEnabled');",
    "const settingMicDeviceId = document.getElementById('settingMicDeviceId');",
    "const settingConcurrencyLimit = document.getElementById('settingConcurrencyLimit');",
    "const settingWebPush = document.getElementById('settingWebPush');",
    "const settingTelegram = document.getElementById('settingTelegram');",
    "const settingApiKeyOpenai = document.getElementById('settingApiKeyOpenai');",
    "const settingApiKeyAnthropic = document.getElementById('settingApiKeyAnthropic');",
    "const settingApiKeyGoogle = document.getElementById('settingApiKeyGoogle');",
    "const settingApiKeyElevenlabs = document.getElementById('settingApiKeyElevenlabs');",
    "const settingApiKeyAzureOpenai = document.getElementById('settingApiKeyAzureOpenai');",
    "const settingApiKeyCustom = document.getElementById('settingApiKeyCustom');",
    "const settingAdvTemperature = document.getElementById('settingAdvTemperature');",
    "const settingAdvTemperatureValue = document.getElementById('settingAdvTemperatureValue');",
    "const settingAdvTopP = document.getElementById('settingAdvTopP');",
    "const settingAdvTopPValue = document.getElementById('settingAdvTopPValue');",
    "const settingAdvFrequencyPenalty = document.getElementById('settingAdvFrequencyPenalty');",
    "const settingAdvFrequencyPenaltyValue = document.getElementById('settingAdvFrequencyPenaltyValue');",
    "const settingAdvPresencePenalty = document.getElementById('settingAdvPresencePenalty');",
    "const settingAdvPresencePenaltyValue = document.getElementById('settingAdvPresencePenaltyValue');",
    "const settingAdvMaxOutputTokens = document.getElementById('settingAdvMaxOutputTokens');",
    "const settingAdvReasoningEffort = document.getElementById('settingAdvReasoningEffort');",
    "const settingAdvReasoningBudget = document.getElementById('settingAdvReasoningBudget');",
    "const settingAdvDeterministicSeed = document.getElementById('settingAdvDeterministicSeed');",
    "const settingAdvJsonMode = document.getElementById('settingAdvJsonMode');",
    "const settingAdvStopSequences = document.getElementById('settingAdvStopSequences');",
    "const settingAdvDefaultMode = document.getElementById('settingAdvDefaultMode');",
    "const settingAdvDefaultTokenEconomy = document.getElementById('settingAdvDefaultTokenEconomy');",
    "const settingAdvMaxAgentIterations = document.getElementById('settingAdvMaxAgentIterations');",
    "const settingAdvQualityEnforce = document.getElementById('settingAdvQualityEnforce');",
    "const settingAdvQualityRequireVerification = document.getElementById('settingAdvQualityRequireVerification');",
    "const settingAdvQualityRequireTests = document.getElementById('settingAdvQualityRequireTests');",
    "const settingAdvQualityRequireMonolithGuard = document.getElementById('settingAdvQualityRequireMonolithGuard');",
    "const settingAdvAutoToolThreshold = document.getElementById('settingAdvAutoToolThreshold');",
    "const settingAdvAutoToolThresholdValue = document.getElementById('settingAdvAutoToolThresholdValue');",
    "const settingAdvToolTimeoutS = document.getElementById('settingAdvToolTimeoutS');",
    "const settingAdvMaxParallelTools = document.getElementById('settingAdvMaxParallelTools');",
    "const settingAdvRequireCommandApproval = document.getElementById('settingAdvRequireCommandApproval');",
    "const settingAdvAllowShell = document.getElementById('settingAdvAllowShell');",
    "const settingAdvAllowFileWrite = document.getElementById('settingAdvAllowFileWrite');",
    "const settingAdvAllowNetwork = document.getElementById('settingAdvAllowNetwork');",
    "const settingAdvAllowBrowser = document.getElementById('settingAdvAllowBrowser');",
    "const settingAdvAllowChannels = document.getElementById('settingAdvAllowChannels');",
    "const settingAdvAllowGit = document.getElementById('settingAdvAllowGit');",
    "const settingAdvAllowedPaths = document.getElementById('settingAdvAllowedPaths');",
    "const settingAdvBlockedCommands = document.getElementById('settingAdvBlockedCommands');",
    "const settingAdvIncludeGlobalMemory = document.getElementById('settingAdvIncludeGlobalMemory');",
    "const settingAdvRetrievalTopK = document.getElementById('settingAdvRetrievalTopK');",
    "const settingAdvMaxPackTokens = document.getElementById('settingAdvMaxPackTokens');",
    "const settingAdvDecayHalfLifeHours = document.getElementById('settingAdvDecayHalfLifeHours');",
    "const settingAdvAutoSummarizeThreshold = document.getElementById('settingAdvAutoSummarizeThreshold');",
    "const settingAdvMemoryDecayDays = document.getElementById('settingAdvMemoryDecayDays');",
    "const settingAdvAutoCompactEnabled = document.getElementById('settingAdvAutoCompactEnabled');",
    "const settingAdvAutoCompactEpisodeThreshold = document.getElementById('settingAdvAutoCompactEpisodeThreshold');",
    "const settingAdvAutoCompactMinIntervalHours = document.getElementById('settingAdvAutoCompactMinIntervalHours');",
    "const settingAdvAutoOptimizeEnabled = document.getElementById('settingAdvAutoOptimizeEnabled');",
    "const settingAdvAutoOptimizeWasteThreshold = document.getElementById('settingAdvAutoOptimizeWasteThreshold');",
    "const settingAdvAutoOptimizeMinIntervalHours = document.getElementById('settingAdvAutoOptimizeMinIntervalHours');",
    "const settingAdvContradictionPolicy = document.getElementById('settingAdvContradictionPolicy');",
    "const settingAdvContextPruneStrategy = document.getElementById('settingAdvContextPruneStrategy');",
    "const settingAdvIncludeProfileMemory = document.getElementById('settingAdvIncludeProfileMemory');",
    "const settingAdvIncludeThreadMemory = document.getElementById('settingAdvIncludeThreadMemory');",
    "const settingAdvPinsOnly = document.getElementById('settingAdvPinsOnly');",
    "const settingAdvPinnedContext = document.getElementById('settingAdvPinnedContext');",
    "const settingAdvSessionTokenBudget = document.getElementById('settingAdvSessionTokenBudget');",
    "const settingAdvDailyTokenBudget = document.getElementById('settingAdvDailyTokenBudget');",
    "const settingAdvMaxRetries = document.getElementById('settingAdvMaxRetries');",
    "const settingAdvRetryBackoffMs = document.getElementById('settingAdvRetryBackoffMs');",
    "const settingAdvThrottleOnBudget = document.getElementById('settingAdvThrottleOnBudget');",
    "const settingAdvLowCostMode = document.getElementById('settingAdvLowCostMode');",
    "const settingAdvProviderFailoverChain = document.getElementById('settingAdvProviderFailoverChain');",
    "const settingAdvModelFailoverChain = document.getElementById('settingAdvModelFailoverChain');",
    "const settingAdvFailoverEnabled = document.getElementById('settingAdvFailoverEnabled');",
    "const settingAdvChatAutoFailover = document.getElementById('settingAdvChatAutoFailover');",
    "const settingAdvFallbackOnAuthError = document.getElementById('settingAdvFallbackOnAuthError');",
    "const settingAdvFailoverCooldownSeconds = document.getElementById('settingAdvFailoverCooldownSeconds');",
    "const settingAdvRetentionDays = document.getElementById('settingAdvRetentionDays');",
    "const settingAdvTelemetryEnabled = document.getElementById('settingAdvTelemetryEnabled');",
    "const settingAdvRedactSecretsInLogs = document.getElementById('settingAdvRedactSecretsInLogs');",
    "const settingAdvPiiGuardStrict = document.getElementById('settingAdvPiiGuardStrict');",
    "const settingAdvLocalOnlyMode = document.getElementById('settingAdvLocalOnlyMode');",
    "const settingAdvAuditLogEnabled = document.getElementById('settingAdvAuditLogEnabled');",
    "const settingAdvExportOnExit = document.getElementById('settingAdvExportOnExit');",
    "const settingAdvUiDensity = document.getElementById('settingAdvUiDensity');",
    "const settingAdvCodeTheme = document.getElementById('settingAdvCodeTheme');",
    "const settingAdvEventLogVerbosity = document.getElementById('settingAdvEventLogVerbosity');",
    "const settingAdvShowTimestamps = document.getElementById('settingAdvShowTimestamps');",
    "const settingAdvShowTokenMeter = document.getElementById('settingAdvShowTokenMeter');",
    "const settingAdvAnimationsEnabled = document.getElementById('settingAdvAnimationsEnabled');",
    "const settingAdvDebugPanelEnabled = document.getElementById('settingAdvDebugPanelEnabled');",
    "const settingAdvLabsFlags = document.getElementById('settingAdvLabsFlags');",
    "const sidebarUserAvatar = document.getElementById('sidebarUserAvatar');",
    "const sidebarChatPanel = document.getElementById('sidebarChatPanel');",
    "const searchOverlayBar = document.getElementById('searchOverlayBar');",
    "const sidebarChatList = document.getElementById('sidebarChatList');",
    "const sidebarSearchModeLabel = document.getElementById('sidebarSearchModeLabel');",
    "const sidebarChatHeaderLabel = document.getElementById('sidebarChatHeaderLabel');",
    "const taskContinuityPanel = document.getElementById('taskContinuityPanel');",
    "const taskContinuityStatusPill = document.getElementById('taskContinuityStatusPill');",
    "const taskContinuityGoal = document.getElementById('taskContinuityGoal');",
    "const taskContinuityBlockersWrap = document.getElementById('taskContinuityBlockersWrap');",
    "const taskContinuityBlockersList = document.getElementById('taskContinuityBlockersList');",
    "const taskContinuityProgress = document.getElementById('taskContinuityProgress');",
    "const taskContinuityEventsList = document.getElementById('taskContinuityEventsList');",
    "const taskContinuityUpdatedAt = document.getElementById('taskContinuityUpdatedAt');",
    "const taskContinuitySession = document.getElementById('taskContinuitySession');",
    "const taskContinuityRefreshBtn = document.getElementById('taskContinuityRefreshBtn');",
    "const debugDockToggleBtn = document.getElementById('debugDockToggleBtn');",
    "const debugDock = document.getElementById('debugDock');",
    "const debugDockCloseBtn = document.getElementById('debugDockCloseBtn');",
    "const debugDockRefreshBtn = document.getElementById('debugDockRefreshBtn');",
    "const debugDockTabs = document.getElementById('debugDockTabs');",
    "const debugTabRuntime = document.getElementById('debugTabRuntime');",
    "const debugTabSystem = document.getElementById('debugTabSystem');",
    "const debugTabModels = document.getElementById('debugTabModels');",
    "const debugTabTools = document.getElementById('debugTabTools');",
    "const debugTabMemory = document.getElementById('debugTabMemory');",
    "const debugTabRuns = document.getElementById('debugTabRuns');",
    "const debugTabEvents = document.getElementById('debugTabEvents');",
    "const debugTabConsole = document.getElementById('debugTabConsole');",
    "const debugTabNetwork = document.getElementById('debugTabNetwork');",
    "const debugPanelRuntime = document.getElementById('debugPanelRuntime');",
    "const debugPanelSystem = document.getElementById('debugPanelSystem');",
    "const debugPanelModels = document.getElementById('debugPanelModels');",
    "const debugPanelTools = document.getElementById('debugPanelTools');",
    "const debugPanelMemory = document.getElementById('debugPanelMemory');",
    "const debugPanelRuns = document.getElementById('debugPanelRuns');",
    "const debugPanelEvents = document.getElementById('debugPanelEvents');",
    "const debugPanelConsole = document.getElementById('debugPanelConsole');",
    "const debugPanelNetwork = document.getElementById('debugPanelNetwork');",
    "const debugCopySnapshotBtn = document.getElementById('debugCopySnapshotBtn');",
    "const debugClearEventsBtn = document.getElementById('debugClearEventsBtn');",
    "const debugClearConsoleBtn = document.getElementById('debugClearConsoleBtn');",
    "const debugClearNetworkBtn = document.getElementById('debugClearNetworkBtn');",
    "const debugEventLog = document.getElementById('debugEventLog');",
    "const debugConsoleLog = document.getElementById('debugConsoleLog');",
    "const debugNetworkLog = document.getElementById('debugNetworkLog');",
    "const debugSessionId = document.getElementById('debugSessionId');",
    "const debugModel = document.getElementById('debugModel');",
    "const debugMessageCount = document.getElementById('debugMessageCount');",
    "const debugGenerating = document.getElementById('debugGenerating');",
    "const debugSidebarState = document.getElementById('debugSidebarState');",
    "const debugSearchScope = document.getElementById('debugSearchScope');",
    "const debugThemeName = document.getElementById('debugThemeName');",
    "const debugViewport = document.getElementById('debugViewport');",
    "const debugEventCount = document.getElementById('debugEventCount');",
    "const debugConsoleCount = document.getElementById('debugConsoleCount');",
    "const debugNetworkCount = document.getElementById('debugNetworkCount');",
    "const debugNetworkTotal = document.getElementById('debugNetworkTotal');",
    "const debugNetworkErrors = document.getElementById('debugNetworkErrors');",
    "const debugNetworkAvgMs = document.getElementById('debugNetworkAvgMs');",
    "const debugSystemVersion = document.getElementById('debugSystemVersion');",
    "const debugSystemReady = document.getElementById('debugSystemReady');",
    "const debugSystemEngineCount = document.getElementById('debugSystemEngineCount');",
    "const debugSystemStatus = document.getElementById('debugSystemStatus');",
    "const debugSystemEngineList = document.getElementById('debugSystemEngineList');",
    "const debugOnboardingGateStatusPill = document.getElementById('debugOnboardingGateStatusPill');",
    "const debugOnboardingCompletionRate = document.getElementById('debugOnboardingCompletionRate');",
    "const debugOnboardingMedianReadySeconds = document.getElementById('debugOnboardingMedianReadySeconds');",
    "const debugOnboardingRepairBtn = document.getElementById('debugOnboardingRepairBtn');",
    "const debugOnboardingGateStatus = document.getElementById('debugOnboardingGateStatus');",
    "const debugOnboardingGateList = document.getElementById('debugOnboardingGateList');",
    "const debugModelsDefault = document.getElementById('debugModelsDefault');",
    "const debugModelsCount = document.getElementById('debugModelsCount');",
    "const debugModelsHealthy = document.getElementById('debugModelsHealthy');",
    "const debugModelHealthList = document.getElementById('debugModelHealthList');",
    "const debugToolsTotal = document.getElementById('debugToolsTotal');",
    "const debugToolsCategories = document.getElementById('debugToolsCategories');",
    "const debugToolCategoryList = document.getElementById('debugToolCategoryList');",
    "const debugToolRegistryList = document.getElementById('debugToolRegistryList');",
    "const debugMemoryEnabled = document.getElementById('debugMemoryEnabled');",
    "const debugMemoryPins = document.getElementById('debugMemoryPins');",
    "const debugMemoryContradictions = document.getElementById('debugMemoryContradictions');",
    "const debugMemoryList = document.getElementById('debugMemoryList');",
    "const debugRunsCount = document.getElementById('debugRunsCount');",
    "const debugRunsFailed = document.getElementById('debugRunsFailed');",
    "const debugRunsList = document.getElementById('debugRunsList');",
    "const robotAlertStage = document.getElementById('robotAlertStage');",
    "const robotAlertDoor = document.getElementById('robotAlertDoor');",
    "const robotAlertBot = document.getElementById('robotAlertBot');",
    "const robotAlertBubble = document.getElementById('robotAlertBubble');",
    "",
    "// New Phase 7 Elements",
    "const chatHistorySelector = document.getElementById('chatHistorySelector');",
    "const globalSearchInput = document.getElementById('globalSearchInput');",
    "",
    "// Phase 6 Model Setup Elements",
    "const modelSetupBtn = document.getElementById('modelSetupBtn');",
    "const modelSetupCurrentLabel = document.getElementById('modelSetupCurrentLabel');",
    "const modelSetupModal = document.getElementById('modelSetupModal');",
    "const closeModelSetupBtn = document.getElementById('closeModelSetupBtn');",
    "const applyModelSetupBtn = document.getElementById('applyModelSetupBtn');",
    "const setupProviderSelector = document.getElementById('setupProviderSelector');",
    "const setupPersonalitySelector = document.getElementById('setupPersonalitySelector');",
    "const customPersonalityGroup = document.getElementById('customPersonalityGroup');",
    "const setupCustomPrompt = document.getElementById('setupCustomPrompt');",
    "const setupAutonomyGroup = document.getElementById('setupAutonomyGroup');",
    "const setupEconomyGroup = document.getElementById('setupEconomyGroup');",
    "const setupMemoryToggle = document.getElementById('setupMemoryToggle');",
    "const setupModelSelector = document.getElementById('setupModelSelector');",
    "const restartServerBtn = document.getElementById('restartServerBtn');",
    "const restartOverlay = document.getElementById('restartOverlay');",
    "const rerunEasySetupBtn = document.getElementById('rerunEasySetupBtn');",
    "",
    "const easySetupModal = document.getElementById('easySetupModal');",
    "const easySetupBackdrop = document.getElementById('easySetupBackdrop');",
    "const easySetupCloseBtn = document.getElementById('easySetupCloseBtn');",
    "const easySetupProgressFill = document.getElementById('easySetupProgressFill');",
    "const easySetupProgressText = document.getElementById('easySetupProgressText');",
    "const easySetupStep1 = document.getElementById('easySetupStep1');",
    "const easySetupStep2 = document.getElementById('easySetupStep2');",
    "const easySetupStep3 = document.getElementById('easySetupStep3');",
    "const easySetupStep4 = document.getElementById('easySetupStep4');",
    "const easySetupPathGrid = document.getElementById('easySetupPathGrid');",
    "const easySetupRecommendedHint = document.getElementById('easySetupRecommendedHint');",
    "const easySetupConnectionMeta = document.getElementById('easySetupConnectionMeta');",
    "const easySetupCodexBlock = document.getElementById('easySetupCodexBlock');",
    "const easySetupManualBlock = document.getElementById('easySetupManualBlock');",
    "const easySetupLocalBlock = document.getElementById('easySetupLocalBlock');",
    "const easySetupCodexMeta = document.getElementById('easySetupCodexMeta');",
    "const easySetupManualProfile = document.getElementById('easySetupManualProfile');",
    "const easySetupManualApiKey = document.getElementById('easySetupManualApiKey');",
    "const easySetupManualPersist = document.getElementById('easySetupManualPersist');",
    "const easySetupLocalProfile = document.getElementById('easySetupLocalProfile');",
    "const easySetupTestConnectionBtn = document.getElementById('easySetupTestConnectionBtn');",
    "const easySetupAutoRepairBtn = document.getElementById('easySetupAutoRepairBtn');",
    "const easySetupConnectionStatus = document.getElementById('easySetupConnectionStatus');",
    "const easySetupDependencyList = document.getElementById('easySetupDependencyList');",
    "const easySetupDependencyTrustNote = document.getElementById('easySetupDependencyTrustNote');",
    "const easySetupApproveAllBtn = document.getElementById('easySetupApproveAllBtn');",
    "const easySetupReviewDownloadsBtn = document.getElementById('easySetupReviewDownloadsBtn');",
    "const easySetupReviewPanel = document.getElementById('easySetupReviewPanel');",
    "const easySetupDependencyStatus = document.getElementById('easySetupDependencyStatus');",
    "const easySetupReadyList = document.getElementById('easySetupReadyList');",
    "const easySetupBackBtn = document.getElementById('easySetupBackBtn');",
    "const easySetupDismissBtn = document.getElementById('easySetupDismissBtn');",
    "const easySetupNextBtn = document.getElementById('easySetupNextBtn');",
    "",
    "let activeAutonomyLevel = 3;",
    "let activeTokenEconomy = 'balanced';",
    "let activeReasoningEffort = '';",
    "let activeModelOverride = '';",
    "let activeChatMode = '';",
    "const KNOWN_MODEL_SUGGESTIONS = {",
    "    codex: ['gpt-5.3-codex', 'gpt-5.2-codex', 'gpt-5.1-codex-max', 'gpt-5.2', 'gpt-5.1-codex-mini'],",
    "};",
    "let currentPreferences = null;",
    "let currentCodexStatus = null;",
    "let pendingAvatarOverride = null;",
    "let availableModelProfiles = [];",
    "let settingsSectionEntries = [];",
    "let settingsNavBound = false;",
    "let settingsNavTicking = false;",
    "let sidebarSearchScope = 'chat';",
    "let sidebarNavMode = 'chat';",
    "let sidebarSessions = [];",
    "let chatPersistInFlight = false;",
    "let chatPersistQueued = false;",
    "let activeAgentName = 'Thomas';",
    "let taskContinuityAutoRefreshTimer = 0;",
    "let taskContinuityInFlight = false;",
    "let taskContinuityLatestState = null;",
    "let taskContinuityLatestEvents = [];",
    "let taskContinuityLatestSessionId = '';",
    "let debugEvents = [];",
    "let debugConsoleEntries = [];",
    "let debugNetworkEntries = [];",
    "let activeDebugTab = 'runtime';",
    "let debugConsoleCaptureEnabled = false;",
    "let debugNetworkCaptureEnabled = false;",
    "let debugLiveLoading = false;",
    "let debugOnboardingRepairInFlight = false;",
    "const debugLiveCache = {",
    "    loadedAt: 0,",
    "    system: null,",
    "    models: null,",
    "    tools: null,",
    "    memory: null,",
    "    runs: null,",
    "    errors: [],",
    "};",
    "let robotAlertQueue = [];",
    "let robotAlertShowing = false;",
    "let robotAlertLastMessage = '';",
    "let robotAlertLastAt = 0;",
    "let officeState = null;",
    "let missionState = null;",
    "let contentState = null;",
    "const spendState = { payload: null, lastFetchedAt: 0 };",
    "const goalsState = { payload: null, lastFetchedAt: 0 };",
    "let moduleState = null;",
    "let officeSpriteAtlasCache = null;",
    "let settingsReturnNavMode = 'chat';",
    "let chatListExpanded = true;",
    "let officeReducedMotionListenerBound = false;",
    "let officeLastHapticAt = 0;",
    "let sidebarAnimationTimer = 0;",
    "let debugDockAnimationTimer = 0;",
    "",
    "const SIDEBAR_ANIMATION_LOCK_MS = 280;",
    "const DEBUG_DOCK_ANIMATION_LOCK_MS = 300;",
    "const TASK_CONTINUITY_REFRESH_INTERVAL_MS = 9000;",
    "const DEBUG_EVENT_LIMIT = 80;",
    "const DEBUG_CONSOLE_LIMIT = 120;",
    "const DEBUG_NETWORK_LIMIT = 120;",
    "const DEBUG_LIVE_CACHE_TTL_MS = 20_000;",
    "const DEBUG_TAB_SEQUENCE = ['runtime', 'system', 'models', 'tools', 'memory', 'runs', 'events', 'console', 'network'];",
    "const UI_NAV_MODE_STORAGE_KEY = 'thomas.ui.nav_mode.v1';",
    "const UI_SIDEBAR_COLLAPSED_STORAGE_KEY = 'thomas.ui.sidebar_collapsed.v1';",
    "const UI_CHAT_LIST_EXPANDED_STORAGE_KEY = 'thomas.ui.chat_list_expanded.v1';",
    "const UI_ACTIVE_CHAT_STORAGE_KEY = 'thomas.ui.active_chat.v1';",
    "const OFFICE_CAMERA_STORAGE_KEY = 'thomas.ui.office.camera.v1';",
    "const OFFICE_LAYOUT_STORAGE_KEY = 'thomas.ui.office.layout.v1';",
    "const OFFICE_AGENT_PREFS_STORAGE_KEY = 'thomas.ui.office.agent_prefs.v1';",
    "const OFFICE_RUNTIME_STORAGE_KEY = 'thomas.ui.office.runtime.v1';",
    "const OFFICE_RUNTIME_SCHEMA_VERSION = 1;",
    "const DEFAULT_AGENT_NAME = 'Thomas';",
    "const MODULE_REFRESH_INTERVAL_MS = 15_000;",
    "const OFFICE_MAX_TASKS = 24;",
    "const OFFICE_MAX_CHAT_LINES = 48;",
    "const OFFICE_MAX_DYNAMIC_ROOMS = 40;",
    "const OFFICE_EVENT_SCHEMA_VERSION = 1;",
    "const OFFICE_EVENT_LOG_LIMIT = 120;",
    "const OFFICE_DEBUG_REFRESH_MS = 180;",
    "const OFFICE_RUNTIME_PERSIST_INTERVAL_MS = 1200;",
    "const OFFICE_BACKGROUND_TICK_MS = 1000;",
    "const OFFICE_STREAM_RETRY_MIN_MS = 1100;",
    "const OFFICE_STREAM_RETRY_MAX_MS = 12_000;",
    "const OFFICE_ZOOM_MIN = 0;",
    "const OFFICE_ZOOM_RENDER_FLOOR = 0.16;",
    "const OFFICE_ZOOM_MAX = 2.4;",
    "const OFFICE_ZOOM_STEP = 0.08;",
    "const OFFICE_WHEEL_ZOOM_SENSITIVITY = 0.00048;",
    "const OFFICE_AGENT_AVOID_RADIUS = 9.8;",
    "const OFFICE_AGENT_COLLISION_DISTANCE = 2.5;",
    "const OFFICE_CROWD_RELIEF_RADIUS = 6.4;",
    "const OFFICE_CROWD_RELIEF_NEIGHBORS = 3;",
    "const OFFICE_CROWD_RELIEF_COOLDOWN_MS = 900;",
    "const OFFICE_MAP_WIDTH = 2800;",
    "const OFFICE_MAP_HEIGHT = 1760;",
    "const OFFICE_VIEWPORT_MARGIN = 0;",
    "const OFFICE_MINIMAP_PAD_RATIO = 0.06;",
    "const OFFICE_COLLISION_PAIR_COOLDOWN_MIN = 1300;",
    "const OFFICE_COLLISION_PAIR_COOLDOWN_MAX = 2100;",
    "const OFFICE_COLLISION_PAIR_PURGE_MS = 2600;",
    "const OFFICE_RUNAWAY_DURATION_MS = 5600;",
    "const OFFICE_RUNAWAY_EXIT_MARGIN = 6.2;",
    "const OFFICE_HAPTIC_COOLDOWN_MS = 120;",
    "const OFFICE_RUNTIME_TIMER_FIELDS = [",
    "    'workUntil',",
    "    'breakUntil',",
    "    'idleUntil',",
    "    'nextAmbientAt',",
    "    'nextWorkLineAt',",
    "    'nextSocialAt',",
    "    'nextBreakAt',",
    "    'bumpUntil',",
    "    'jumpUntil',",
    "    'collisionCooldownUntil',",
    "    'crowdReliefUntil',",
    "    'yieldUntil',",
    "    'stuckSince',",
    "    'returnAfterRunAt',",
    "];",
    "const MISSION_POLL_INTERVAL_MS = 6500;",
    "const MISSION_PRIORITY_LIMIT = 16;",
    "const MISSION_TIMELINE_LIMIT = 10;",
    "const MISSION_JOBS_LIMIT = 180;",
    "const MISSION_TIMELINE_RECENT_MS = 1000 * 60 * 60 * 36;",
    "const MISSION_RECURRING_SCHEDULE_TYPES = new Set(['interval', 'daily', 'weekly']);",
    "const CONTENT_HUB_STALE_MS = 45_000;",
    "const OFFICE_TASK_KEYWORDS = /\\b(build|create|design|fix|update|refactor|research|compare|analy(?:z|s)e|write|draft|plan|test|deploy|ship|record|edit|summarize|review|debug|optimi(?:s|z)e|benchmark|publish|support|investigate|script|automation|website|landing|video|content)\\b/i;",
    "const OFFICE_STATIC_ROOMS = [",
    "    { id: 'room-engineering', label: 'Software Lab', meta: 'Code + automation', x: 27, y: 8, w: 30, h: 20, kind: 'work', theme: 'engineering', doorX: 50, doorY: 28, hallId: 'hall-top-mid' },",
    "    { id: 'room-content', label: 'Content Studio', meta: 'Video + social', x: 27, y: 30, w: 30, h: 18, kind: 'work', theme: 'content', doorX: 50, doorY: 52, hallId: 'hall-mid-mid' },",
    "    { id: 'room-research', label: 'Research Bay', meta: 'Comparisons + docs', x: 60, y: 8, w: 17, h: 20, kind: 'work', theme: 'research', doorX: 66, doorY: 28, hallId: 'hall-top-mid-right' },",
    "    { id: 'room-ops', label: 'Ops Command', meta: 'Deploy + reliability', x: 79, y: 8, w: 17, h: 20, kind: 'work', theme: 'ops', doorX: 82, doorY: 28, hallId: 'hall-top-right' },",
    "    { id: 'room-planning', label: 'Strategy Room', meta: 'Planning + roadmaps', x: 4, y: 8, w: 20, h: 18, kind: 'work', theme: 'planning', doorX: 18, doorY: 28, hallId: 'hall-top-left' },",
    "    { id: 'room-support', label: 'Support Desk', meta: 'Tickets + feedback', x: 4, y: 30, w: 20, h: 18, kind: 'work', theme: 'support', doorX: 18, doorY: 52, hallId: 'hall-mid-left' },",
    "    { id: 'room-design', label: 'Design Loft', meta: 'UI + product polish', x: 27, y: 52, w: 14, h: 18, kind: 'work', theme: 'design', doorX: 34, doorY: 70, hallId: 'hall-low-mid-left' },",
    "    { id: 'room-break', label: 'Lunch Room', meta: 'Breaks + team chat', x: 60, y: 30, w: 36, h: 18, kind: 'break', theme: 'break', doorX: 82, doorY: 52, hallId: 'hall-mid-right' },",
    "    { id: 'room-coffee', label: 'Coffee Bar', meta: 'Quick recharge', x: 4, y: 52, w: 20, h: 18, kind: 'break', theme: 'coffee', doorX: 18, doorY: 70, hallId: 'hall-low-left' },",
    "    { id: 'room-pods', label: 'Focus Pods', meta: 'Task swarms + deep work', x: 43, y: 52, w: 10, h: 18, kind: 'work', theme: 'pods', doorX: 50, doorY: 70, hallId: 'hall-low-mid' },",
    "    { id: 'room-lobby', label: 'Main Lobby', meta: 'Free roaming + dispatch', x: 55, y: 52, w: 41, h: 36, kind: 'lobby', theme: 'lobby', doorX: 82, doorY: 70, hallId: 'hall-low-right' },",
    "];",
    "const OFFICE_HALL_NODES = [",
    "    { id: 'hall-top-left', x: 18, y: 30 },",
    "    { id: 'hall-top-mid-left', x: 34, y: 30 },",
    "    { id: 'hall-top-mid', x: 50, y: 30 },",
    "    { id: 'hall-top-mid-right', x: 66, y: 30 },",
    "    { id: 'hall-top-right', x: 82, y: 30 },",
    "    { id: 'hall-mid-left', x: 18, y: 53 },",
    "    { id: 'hall-mid-mid-left', x: 34, y: 53 },",
    "    { id: 'hall-mid-mid', x: 50, y: 53 },",
    "    { id: 'hall-mid-mid-right', x: 66, y: 53 },",
    "    { id: 'hall-mid-right', x: 82, y: 53 },",
    "    { id: 'hall-low-left', x: 18, y: 72 },",
    "    { id: 'hall-low-mid-left', x: 34, y: 72 },",
    "    { id: 'hall-low-mid', x: 50, y: 72 },",
    "    { id: 'hall-low-mid-right', x: 66, y: 72 },",
    "    { id: 'hall-low-right', x: 82, y: 72 },",
    "];",
    "const OFFICE_HALL_EDGES = [",
    "    ['hall-top-left', 'hall-top-mid-left'],",
    "    ['hall-top-mid-left', 'hall-top-mid'],",
    "    ['hall-top-mid', 'hall-top-mid-right'],",
    "    ['hall-top-mid-right', 'hall-top-right'],",
    "    ['hall-mid-left', 'hall-mid-mid-left'],",
    "    ['hall-mid-mid-left', 'hall-mid-mid'],",
    "    ['hall-mid-mid', 'hall-mid-mid-right'],",
    "    ['hall-mid-mid-right', 'hall-mid-right'],",
    "    ['hall-low-left', 'hall-low-mid-left'],",
    "    ['hall-low-mid-left', 'hall-low-mid'],",
    "    ['hall-low-mid', 'hall-low-mid-right'],",
    "    ['hall-low-mid-right', 'hall-low-right'],",
    "    ['hall-top-left', 'hall-mid-left'],",
    "    ['hall-mid-left', 'hall-low-left'],",
    "    ['hall-top-mid-left', 'hall-mid-mid-left'],",
    "    ['hall-mid-mid-left', 'hall-low-mid-left'],",
    "    ['hall-top-mid', 'hall-mid-mid'],",
    "    ['hall-mid-mid', 'hall-low-mid'],",
    "    ['hall-top-mid-right', 'hall-mid-mid-right'],",
    "    ['hall-mid-mid-right', 'hall-low-mid-right'],",
    "    ['hall-top-right', 'hall-mid-right'],",
    "    ['hall-mid-right', 'hall-low-right'],",
    "];",
    "const OFFICE_CORRIDORS = [",
    "    { x: 3.4, y: 27.6, w: 93.2, h: 4.8, orientation: 'h' },",
    "    { x: 3.4, y: 50.6, w: 93.2, h: 4.8, orientation: 'h' },",
    "    { x: 3.4, y: 69.6, w: 93.2, h: 4.8, orientation: 'h' },",
    "    { x: 15.6, y: 27.6, w: 4.8, h: 46.8, orientation: 'v' },",
    "    { x: 31.6, y: 27.6, w: 4.8, h: 46.8, orientation: 'v' },",
    "    { x: 47.6, y: 27.6, w: 4.8, h: 46.8, orientation: 'v' },",
    "    { x: 63.6, y: 27.6, w: 4.8, h: 46.8, orientation: 'v' },",
    "    { x: 79.6, y: 27.6, w: 4.8, h: 46.8, orientation: 'v' },",
    "];",
    "const OFFICE_AMBIENT_DECOR = [",
    "    { type: 'tree', x: 2.4, y: 14, w: 4.8, h: 7.6 },",
    "    { type: 'tree', x: 2.4, y: 84, w: 4.8, h: 7.6 },",
    "    { type: 'tree', x: 97.6, y: 14, w: 4.8, h: 7.6 },",
    "    { type: 'tree', x: 97.6, y: 84, w: 4.8, h: 7.6 },",
    "    { type: 'windowstrip', x: 41, y: 5.6, w: 20, h: 2.6 },",
    "    { type: 'windowstrip', x: 70, y: 5.6, w: 24, h: 2.6 },",
    "    { type: 'whiteboard', x: 14, y: 18, w: 8.2, h: 2.8 },",
    "    { type: 'whiteboard', x: 42, y: 40, w: 8.6, h: 2.8 },",
    "    { type: 'whiteboard', x: 68, y: 18, w: 7.4, h: 2.8 },",
    "    { type: 'bookshelf', x: 9.5, y: 61, w: 7.6, h: 3.2 },",
    "    { type: 'bookshelf', x: 83.6, y: 18, w: 7.2, h: 3.2 },",
    "    { type: 'meetingtable', x: 14, y: 39, w: 8.4, h: 3.4 },",
    "    { type: 'kiosk', x: 74, y: 60, w: 3.4, h: 4.2 },",
    "    { type: 'watercooler', x: 62, y: 74, w: 3.4, h: 5 },",
    "    { type: 'watercooler', x: 18, y: 74, w: 3.2, h: 5 },",
    "    { type: 'sofa', x: 67, y: 82, w: 8.8, h: 3.2 },",
    "    { type: 'bench', x: 80, y: 82, w: 7.8, h: 2.9 },",
    "    { type: 'table', x: 48, y: 62, w: 4.4, h: 3.4 },",
    "    { type: 'lamp', x: 57, y: 71, w: 2.2, h: 4.5 },",
    "    { type: 'lamp', x: 79, y: 71, w: 2.2, h: 4.5 },",
    "    { type: 'arcade', x: 88.5, y: 80, w: 3.6, h: 5.2 },",
    "    { type: 'pingpong', x: 72, y: 64, w: 7.4, h: 3.6 },",
    "    { type: 'planterrow', x: 50, y: 6.8, w: 18, h: 3.2 },",
    "    { type: 'planterrow', x: 50, y: 89.2, w: 18, h: 3.2 },",
    "    { type: 'vending', x: 9.8, y: 44, w: 3.2, h: 5.6 },",
    "    { type: 'vending', x: 93, y: 44, w: 3.2, h: 5.6 },",
    "    { type: 'lounge-rug', x: 73.5, y: 69.5, w: 17, h: 11.2 },",
    "    { type: 'floor-art', x: 39, y: 44, w: 6.6, h: 3.4 },",
    "    { type: 'floor-art', x: 28, y: 63, w: 6.2, h: 3.2 },",
    "];",
    "const OFFICE_DYNAMIC_ROOM_SLOTS = [",
    "    { x: 58, y: 58, w: 8, h: 8 },",
    "    { x: 68, y: 58, w: 8, h: 8 },",
    "    { x: 78, y: 58, w: 8, h: 8 },",
    "    { x: 88, y: 58, w: 8, h: 8 },",
    "    { x: 58, y: 68, w: 8, h: 8 },",
    "    { x: 68, y: 68, w: 8, h: 8 },",
    "    { x: 78, y: 68, w: 8, h: 8 },",
    "    { x: 88, y: 68, w: 8, h: 8 },",
    "    { x: 58, y: 78, w: 8, h: 8 },",
    "    { x: 68, y: 78, w: 8, h: 8 },",
    "    { x: 78, y: 78, w: 8, h: 8 },",
    "    { x: 88, y: 78, w: 8, h: 8 },",
    "];",
    "const OFFICE_TASK_ROOM_RULES = [",
    "    { pattern: /\\b(code|coding|bug|fix|refactor|script|api|backend|frontend|test|suite|engineer(?:ing)?)\\b/i, roomId: 'room-engineering' },",
    "    { pattern: /\\b(content|video|youtube|social|post|edit|thumbnail|brand|marketing)\\b/i, roomId: 'room-content' },",
    "    { pattern: /\\b(research|compare|competitor|benchmark|analysis|document|docs|investigate)\\b/i, roomId: 'room-research' },",
    "    { pattern: /\\b(deploy|infra|infrastructure|ops|monitor|reliability|performance|server|hosting)\\b/i, roomId: 'room-ops' },",
    "    { pattern: /\\b(plan|roadmap|strategy|scope|milestone|timeline)\\b/i, roomId: 'room-planning' },",
    "    { pattern: /\\b(support|ticket|customer|feedback|help)\\b/i, roomId: 'room-support' },",
    "    { pattern: /\\b(design|ui|ux|landing|website|visual|brand)\\b/i, roomId: 'room-design' },",
    "    { pattern: /\\b(focus|deep work|pod|quiet)\\b/i, roomId: 'room-pods' },",
    "];",
    "const OFFICE_AGENT_SEEDS = [",
    "    { name: 'Brandon', color: '#9ad8ff', costume: 'visor', tint: 'blue' },",
    "    { name: 'Trey', color: '#9becc9', costume: 'headset', tint: 'green' },",
    "    { name: 'Zach', color: '#ffd49f', costume: 'cap', tint: 'orange' },",
    "    { name: 'Matt', color: '#ffc7eb', costume: 'bowtie', tint: 'pink' },",
    "    { name: 'Taylor', color: '#d7c8ff', costume: 'none', tint: 'purple' },",
    "    { name: 'John', color: '#ffeaa9', costume: 'visor', tint: 'yellow' },",
    "    { name: 'Nova', color: '#9ad8ff', costume: 'cap', tint: 'blue' },",
    "    { name: 'Pixel', color: '#9becc9', costume: 'headset', tint: 'green' },",
    "    { name: 'Byte', color: '#f4c4ff', costume: 'bowtie', tint: 'purple' },",
    "    { name: 'Orbit', color: '#9fd9ff', costume: 'none', tint: 'blue' },",
    "    { name: 'Echo', color: '#b2ffc8', costume: 'visor', tint: 'green' },",
    "    { name: 'Glitch', color: '#ffd0a8', costume: 'cap', tint: 'orange' },",
    "];",
    "const OFFICE_AGENT_STYLE_COLOR_POOL = [",
    "    '#9ad8ff',",
    "    '#9becc9',",
    "    '#ffd49f',",
    "    '#ffc7eb',",
    "    '#d7c8ff',",
    "    '#ffeaa9',",
    "    '#9fd9ff',",
    "    '#b2ffc8',",
    "    '#f4c4ff',",
    "    '#ffd0a8',",
    "    '#a7ffe3',",
    "    '#b7d6ff',",
    "    '#ffd8c2',",
    "    '#e4ceff',",
    "    '#c6f4ff',",
    "];",
    "const OFFICE_AGENT_COSTUME_POOL = ['none', 'cap', 'visor', 'headset', 'bowtie'];",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  VIRTUAL OFFICE DATA                                                    ║",
    "// ║  Agent dialogue trees, robot status sayings, UI notification helpers    ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "const OFFICE_DIALOGUE = {",
    "    startup: [",
    "        'Office simulation online. Local-only mode: no API tokens burned.',",
    "        'Virtual office booted. Agents are clocking in.',",
    "    ],",
    "    queued: [",
    "        'Task queued in {room}: {task}.',",
    "        'Logged new work for {room}.',",
    "        '{task} just hit the board.',",
    "    ],",
    "    pickup: [",
    "        'On it. Heading to {room}.',",
    "        'Routing to {room} now.',",
    "        'Copy that, moving to {room}.',",
    "    ],",
    "    working: [",
    "        'Compiling ideas and caffeine.',",
    "        'Low-key cooking in this room.',",
    "        'Focused mode: do not boop.',",
    "        'If this works first try, everyone acts normal.',",
    "        'Brandon said banana pro is unfair. Noted.',",
    "    ],",
    "    complete: [",
    "        'Task wrapped. Sending result vibes.',",
    "        'Done and documented.',",
    "        'Shipping this one.',",
    "    ],",
    "    break: [",
    "        'Coffee break acquired.',",
    "        'Lunch room debrief in progress.',",
    "        'Quick reset, then back to work.',",
    "    ],",
    "    collision: [",
    "        'Oops, my bad.',",
    "        'Watch out!',",
    "        'Sorry, rerouting.',",
    "        'Friendly traffic jam.',",
    "        'Hallway merge conflict.',",
    "        'My lane, your lane, our lane.',",
    "        'Sorry, boot-skid.',",
    "        'Desk side road rage avoided.',",
    "    ],",
    "    clicked: [",
    "        'Booped! Retreating!',",
    "        'You tapped me. Tactical sprint!',",
    "        'Zoom mode engaged.',",
    "    ],",
    "    mention: [",
    "        'Heard you loud and clear.',",
    "        'Copy that. I can reroute now.',",
    "        'Good call. I will handle it.',",
    "        'Roger. Updating my queue.',",
    "    ],",
    "    mentionStatus: [",
    "        'I have {count} active tasks right now.',",
    "        'Current load: {count} tasks and holding.',",
    "    ],",
    "};",
    "const OFFICE_PERSONA_LIBRARY = {",
    "    blue: {",
    "        working: [",
    "            'Latency low, momentum high.',",
    "            'Code path stabilized and cooking.',",
    "            'Shipping energy confirmed.',",
    "        ],",
    "        break: [",
    "            'Hydration checkpoint.',",
    "            'Coffee patch applied.',",
    "        ],",
    "        socialLead: [",
    "            'Quick sync before we ship this?',",
    "            'Any blockers before next sprint hop?',",
    "        ],",
    "        socialReply: [",
    "            'All clear on my side.',",
    "            'Looks clean. Let us run it.',",
    "        ],",
    "        collision: [",
    "            'Sorry, lane correction.',",
    "            'My pathing glitched for a sec.',",
    "        ],",
    "    },",
    "    green: {",
    "        working: [",
    "            'Research stack is humming.',",
    "            'Scanning options and ranking outcomes.',",
    "            'Signal over noise mode.',",
    "        ],",
    "        break: [",
    "            'Tea protocol engaged.',",
    "            'Recharging social battery for 60 seconds.',",
    "        ],",
    "        socialLead: [",
    "            'Want a quick quality pass?',",
    "            'Can we validate assumptions together?',",
    "        ],",
    "        socialReply: [",
    "            'Yep, that is a solid call.',",
    "            'I can sanity check the edge cases.',",
    "        ],",
    "        collision: [",
    "            'Oops, watch your lane.',"
].join("\n");
