/* app.js lines 3001-4000 */
export default [
    "    if (!Boolean(res.data?.ok)) {",
    "        const errorMsg = safeString(res.data?.error) || `Repair exited with code ${res.data?.exit_code}.`;",
    "        const stderrTail = safeString(res.data?.stderr_tail);",
    "        const finalMsg = stderrTail ? `${errorMsg}\\n${stderrTail}` : errorMsg;",
    "        setEasySetupStatus(easySetupDependencyStatus, `${finalMsg} Remediation: approve prompts and retry.`, 'error');",
    "        emitOnboardingTelemetry('wizard.download_approval_failed', {",
    "            trigger,",
    "            error: errorMsg,",
    "        });",
    "        return false;",
    "    }",
    "",
    "    const reportPath = safeString(res.data?.report_path);",
    "    setEasySetupStatus(",
    "        easySetupDependencyStatus,",
    "        reportPath",
    "            ? `Repair completed. Report: ${reportPath}`",
    "            : 'Repair completed successfully.',",
    "        'ok'",
    "    );",
    "    emitOnboardingTelemetry('wizard.download_approved', {",
    "        trigger,",
    "        report_path: reportPath,",
    "    });",
    "    return true;",
    "}",
    "",
    "async function handleEasySetupApproveAll() {",
    "    const ok = await runEasySetupRepair('approve_all');",
    "    if (!ok) return;",
    "    try {",
    "        await loadEasySetupBootstrap();",
    "    } catch {",
    "        // Ignore refresh failures; keep existing plan.",
    "    }",
    "    easySetupState.dependencyPlan = buildEasySetupDependencyPlan(easySetupState.bootstrap, easySetupState.selectedPath);",
    "    easySetupState.dependenciesAction = 'approved';",
    "    renderEasySetupDependencies();",
    "    renderEasySetupReviewPanel();",
    "    updateEasySetupNavigation();",
    "    await persistOnboardingPrefs({",
    "        current_step: 'downloads',",
    "        answers: { dependency_action: 'approved' },",
    "    });",
    "}",
    "",
    "function handleEasySetupReviewDownloads() {",
    "    if (!easySetupReviewPanel) return;",
    "    renderEasySetupReviewPanel();",
    "    easySetupReviewPanel.classList.toggle('hidden');",
    "}",
    "",
    "async function handleEasySetupNext() {",
    "    if (easySetupState.step === 1) {",
    "        if (!safeString(easySetupState.selectedPath)) {",
    "            setEasySetupStatus(easySetupConnectionStatus, 'Select a connection path first.', 'error');",
    "            return;",
    "        }",
    "        setEasySetupStep(2);",
    "        await persistOnboardingPrefs({ current_step: 'connect', dismissed_at: null });",
    "        emitOnboardingTelemetry('wizard.step_advanced', { step: 'connect', path: easySetupState.selectedPath });",
    "        return;",
    "    }",
    "",
    "    if (easySetupState.step === 2) {",
    "        if (!easySetupState.verified) {",
    "            setEasySetupStatus(",
    "                easySetupConnectionStatus,",
    "                'Connection must verify before continuing. Use \"Connect and Test\".',",
    "                'error'",
    "            );",
    "            return;",
    "        }",
    "        easySetupState.dependencyPlan = buildEasySetupDependencyPlan(easySetupState.bootstrap, easySetupState.selectedPath);",
    "        setEasySetupStep(3);",
    "        await persistOnboardingPrefs({ current_step: 'downloads' });",
    "        emitOnboardingTelemetry('wizard.step_advanced', { step: 'downloads', path: easySetupState.selectedPath });",
    "        return;",
    "    }",
    "",
    "    if (easySetupState.step === 3) {",
    "        const missing = missingRequiredDependencies(easySetupState.dependencyPlan).length;",
    "        if (missing > 0 && safeString(easySetupState.dependenciesAction) === 'pending') {",
    "            setEasySetupStatus(",
    "                easySetupDependencyStatus,",
    "                'Approve required downloads before continuing.',",
    "                'error'",
    "            );",
    "            return;",
    "        }",
    "        setEasySetupStep(4);",
    "        await persistOnboardingPrefs({ current_step: 'brain_ready' });",
    "        emitOnboardingTelemetry('wizard.step_advanced', { step: 'brain_ready', path: easySetupState.selectedPath });",
    "        return;",
    "    }",
    "",
    "    closeEasySetup();",
    "    ensureChatVisible();",
    "    beginOnboardingInterview();",
    "}",
    "",
    "async function handleEasySetupBack() {",
    "    if (easySetupState.step <= 1) return;",
    "    setEasySetupStep(easySetupState.step - 1);",
    "    await persistOnboardingPrefs({ current_step: easySetupStepName(easySetupState.step) });",
    "}",
    "",
"function initEasySetup() {",
"    if (!easySetupModal) return;",
"    if (easySetupDismissBtn) {",
"        easySetupDismissBtn.textContent = 'Skip for now';",
"        easySetupDismissBtn.classList.remove('hidden');",
"    }",
"    if (easySetupCloseBtn) {",
"        easySetupCloseBtn.classList.add('hidden');",
"    }",
"",
"    if (easySetupPathGrid) {",
"        easySetupPathGrid.querySelectorAll('[data-path]').forEach((btn) => {",
    "            btn.addEventListener('click', () => {",
    "                handleEasySetupPathSelect(btn.getAttribute('data-path'));",
    "            });",
    "        });",
    "    }",
    "",
    "    if (easySetupCloseBtn) easySetupCloseBtn.addEventListener('click', () => requestEasySetupClose('close_button'));",
    "    if (easySetupBackdrop) easySetupBackdrop.addEventListener('click', () => requestEasySetupClose('backdrop'));",
    "    if (easySetupDismissBtn) easySetupDismissBtn.addEventListener('click', () => requestEasySetupClose('footer_skip'));",
    "    if (easySetupBackBtn) {",
    "        easySetupBackBtn.addEventListener('click', () => {",
    "            handleEasySetupBack();",
    "        });",
    "    }",
    "    if (easySetupNextBtn) {",
    "        easySetupNextBtn.addEventListener('click', () => {",
    "            handleEasySetupNext();",
    "        });",
    "    }",
    "    if (easySetupTestConnectionBtn) {",
    "        easySetupTestConnectionBtn.addEventListener('click', () => {",
    "            handleEasySetupConnectionTest();",
    "        });",
    "    }",
    "    if (easySetupAutoRepairBtn) {",
    "        easySetupAutoRepairBtn.addEventListener('click', async () => {",
    "            const ok = await runEasySetupRepair('connect_step');",
    "            if (ok) {",
    "                try {",
    "                    await loadEasySetupBootstrap();",
    "                } catch {",
    "                    // Best effort only.",
    "                }",
    "                easySetupState.dependencyPlan = buildEasySetupDependencyPlan(easySetupState.bootstrap, easySetupState.selectedPath);",
    "                renderEasySetupDependencies();",
    "                updateEasySetupNavigation();",
    "            }",
    "        });",
    "    }",
    "    if (easySetupApproveAllBtn) {",
    "        easySetupApproveAllBtn.addEventListener('click', () => {",
    "            handleEasySetupApproveAll();",
    "        });",
    "    }",
    "    if (easySetupReviewDownloadsBtn) easySetupReviewDownloadsBtn.addEventListener('click', handleEasySetupReviewDownloads);",
    "    if (rerunEasySetupBtn) {",
    "        rerunEasySetupBtn.addEventListener('click', async () => {",
    "            if (isSettingsScreenOpen()) closeSettingsModal();",
    "            await openEasySetup({ source: 'settings', force: true, restart: true });",
    "        });",
    "    }",
    "",
    "    syncEasySetupConnectionBlocks();",
    "    setEasySetupStatus(easySetupConnectionStatus, 'Choose a path and run connection test.');",
    "    setEasySetupDependencyDefaultStatus();",
    "    setEasySetupStep(1);",
    "}",
    "",
    "function renderOnboardingChoiceBubble(prompt, options, onChoose) {",
    "    if (safeString(prompt)) {",
    "        renderMessage({ role: 'assistant', content: prompt });",
    "    }",
    "    setAssistantSuggestions({",
    "        title: 'Onboarding choices',",
    "        context: 'onboarding',",
    "        dismissible: false,",
    "        options: (options || []).map((option) => ({",
    "            ...option,",
    "            keep_after_choose: false,",
    "            onChoose: async () => {",
    "                if (typeof onChoose === 'function') {",
    "                    await onChoose(option);",
    "                }",
    "            },",
    "        })),",
    "    });",
    "}",
    "",
    "function deriveOnboardingDefaults(answers) {",
    "    const experience = safeString(answers?.experience) || 'builder';",
    "    const autonomyPref = safeString(answers?.autonomy) || 'balanced';",
    "    const costPref = safeString(answers?.cost_quality) || 'balanced';",
    "    const memoryPref = safeString(answers?.memory) || 'remember';",
    "    const personalityPref = safeString(answers?.personality) || 'balanced';",
    "    const workflowPref = safeString(answers?.workflow) || 'build_features';",
    "    const togglesPref = safeString(answers?.default_toggles) || 'safe_defaults';",
    "",
    "    let autonomyLevel = 2;",
    "    if (experience === 'new') autonomyLevel = 1;",
    "    if (experience === 'expert') autonomyLevel = 4;",
    "    if (autonomyPref === 'guided') autonomyLevel -= 1;",
    "    if (autonomyPref === 'aggressive') autonomyLevel += 1;",
    "    autonomyLevel = Math.max(1, Math.min(4, autonomyLevel));",
    "",
    "    let tokenEconomy = 'optimal';",
    "    if (costPref === 'low_cost') tokenEconomy = 'cheap';",
    "    if (costPref === 'max_quality') tokenEconomy = 'max';",
    "",
    "    const memoryEnabled = memoryPref === 'remember';",
    "    const sessionOnlyMemory = memoryPref === 'session_only';",
    "    const requireCommandApproval = togglesPref === 'safe_defaults' || workflowPref === 'ops_reliability';",
    "    const allowNetwork = togglesPref !== 'safe_defaults';",
    "    const showTokenMeter = togglesPref === 'power_mode';",
    "    const debugPanelEnabled = togglesPref === 'power_mode';",
    "    const desktopNotifications = togglesPref !== 'quiet_mode';",
    "    const showTimestamps = personalityPref === 'direct_technical' || workflowPref === 'ops_reliability';",
    "    const uiDensity = togglesPref === 'power_mode' ? 'compact' : 'comfortable';",
    "    const defaultMode = workflowPref === 'research' ? 'thinking' : 'auto';",
    "    let profileType = 'adaptive';",
    "    if (experience === 'new' || personalityPref === 'calm_guide') profileType = 'non_coder';",
    "    if (experience === 'expert' || personalityPref === 'direct_technical') profileType = 'coder';",
    "",
    "    return {",
    "        autonomyLevel,",
    "        tokenEconomy,",
    "        memoryEnabled,",
    "        sessionOnlyMemory,",
    "        requireCommandApproval,",
    "        allowNetwork,",
    "        showTokenMeter,",
    "        debugPanelEnabled,",
    "        desktopNotifications,",
    "        showTimestamps,",
    "        uiDensity,",
    "        defaultMode,",
    "        profileType,",
    "    };",
    "}",
    "",
    "async function applyOnboardingCompletion({ skippedInterview = false } = {}) {",
    "    const onboardingAnswers = {",
    "        ...(getOnboardingFromPrefs()?.answers || {}),",
    "        ...(easySetupState.interviewAnswers || {}),",
    "        interview_skipped: Boolean(skippedInterview),",
    "        connection_path: safeString(easySetupState.selectedPath),",
    "        dependency_action: safeString(easySetupState.dependenciesAction) || 'pending',",
    "    };",
    "    const derived = deriveOnboardingDefaults(onboardingAnswers);",
    "    const completedAt = onboardingNowIso();",
    "",
    "    const patch = {",
    "        autonomy: { default_level: `L${derived.autonomyLevel}` },",
    "        memory: { enabled_global: derived.memoryEnabled },",
    "        notifications: { desktop: derived.desktopNotifications },",
    "        profile: { profile_type: derived.profileType },",
    "        advanced: {",
    "            runtime: {",
    "                default_mode: derived.defaultMode,",
    "                default_token_economy: derived.tokenEconomy,",
    "            },",
    "            tools: {",
    "                require_command_approval: derived.requireCommandApproval,",
    "                allow_network: derived.allowNetwork,",
    "            },",
    "            interface: {",
    "                show_timestamps: derived.showTimestamps,",
    "                show_token_meter: derived.showTokenMeter,",
    "                debug_panel_enabled: derived.debugPanelEnabled,",
    "                ui_density: derived.uiDensity,",
    "            },",
    "        },",
    "        onboarding: {",
    "            setup_completed: true,",
    "            version: ONBOARDING_VERSION,",
    "            completed_at: completedAt,",
    "            dismissed_at: null,",
    "            current_step: 'completed',",
    "            connection_method: safeString(easySetupState.selectedPath) || null,",
    "            dependency_plan: {",
    "                path: safeString(easySetupState.selectedPath),",
    "                items: Array.isArray(easySetupState.dependencyPlan) ? easySetupState.dependencyPlan : [],",
    "            },",
    "            answers: onboardingAnswers,",
    "        },",
    "    };",
    "",
    "    const res = await fetch('/api/preferences', {",
    "        method: 'PATCH',",
    "        headers: { 'Content-Type': 'application/json' },",
    "        body: JSON.stringify(patch),",
    "    });",
    "    if (!res.ok) {",
    "        const reason = await res.text();",
    "        throw new Error(reason || `Failed to finalize onboarding (${res.status})`);",
    "    }",
    "    currentPreferences = await res.json();",
    "",
    "    if (derived.sessionOnlyMemory && sessionId) {",
    "        await fetch(`/api/preferences?thread_id=${encodeURIComponent(sessionId)}`, {",
    "            method: 'PATCH',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({ memory: { thread_enabled: true } }),",
    "        }).catch(() => { });",
    "    }",
    "",
    "    activeAutonomyLevel = derived.autonomyLevel;",
    "    activeTokenEconomy = derived.tokenEconomy === 'optimal' ? 'balanced' : derived.tokenEconomy;",
    "    activeChatMode = normalizeChatMode(derived.defaultMode) || 'auto';",
    "    setSegmentedControlSelection('setupAutonomyGroup', String(activeAutonomyLevel));",
    "    setSegmentedControlSelection('setupEconomyGroup', activeTokenEconomy);",
    "    if (settingAdvDefaultMode) settingAdvDefaultMode.value = activeChatMode;",
    "    if (setupMemoryToggle) setupMemoryToggle.checked = Boolean(currentPreferences?.memory?.enabled_global);",
    "    if (settingMemoryEnabled) settingMemoryEnabled.checked = Boolean(currentPreferences?.memory?.enabled_global);",
    "    updateSidebarIdentity();",
    "    easySetupState.interviewStarted = false;",
    "    easySetupState.interviewStage = 'idle';",
    "    easySetupState.interviewIndex = -1;",
    "    hideAssistantSuggestions({ force: true });",
    "    showStarterSuggestionRail({ force: true });",
    "",
    "    emitOnboardingTelemetry('completed', {",
    "        skipped_interview: Boolean(skippedInterview),",
    "        connection_method: safeString(easySetupState.selectedPath),",
    "        autonomy_level: derived.autonomyLevel,",
    "        token_economy: derived.tokenEconomy,",
    "    });",
    "}",
    "",
    "function includesAny(text, terms = []) {",
    "    return (terms || []).some((term) => text.includes(term));",
    "}",
    "",
    "function isSecurityTrustConcern(textRaw) {",
    "    const text = safeString(textRaw).toLowerCase();",
    "    if (!text) return false;",
    "    return includesAny(text, [",
    "        'security',",
    "        'secure',",
    "        'unsafe',",
    "        'cyber',",
    "        'risk',",
    "        'risky',",
    "        'trust',",
    "        'dependency',",
    "        'dependencies',",
    "        'dependency tree',",
    "        'dependency trees',",
    "        'install',",
    "        'installer',",
    "        'download',",
    "        'permission',",
    "        'permissions',",
    "        'malware',",
    "        'virus',",
    "        'supply chain',",
    "    ]);",
    "}",
    "",
    "function buildSetupSafetyMessage() {",
    "    return [",
    "        'Fair concern. Setup is designed to be explicit and user-controlled:',",
    "        withAgentName('- No silent installs: {{agent}} only runs dependency installs after your approval.'),",
    "        '- Dependency step shows why each tool is needed and where it comes from.',",
    "        '- You can choose the lowest-download path: Manual API Key.',",
    "        '- Safe defaults keep command approval on so actions stay supervised.',",
    "    ].join('\\n');",
    "}",
    "",
    "function showSetupSafetySuggestions() {",
    "    setAssistantSuggestions({",
    "        title: 'Setup safety',",
    "        context: 'setup_safety',",
    "        dismissible: false,",
    "        options: [",
    "            {",
    "                label: 'Run Easy Setup',",
    "                kind: 'action',",
    "                tone: 'primary',",
    "                onChoose: async () => {",
    "                    ensureChatVisible();",
    "                    await openEasySetup({ source: 'safety_suggestion', force: false, restart: false });",
    "                },",
    "            },",
    "            {",
    "                label: 'Use lowest-download setup',",
    "                kind: 'action',",
    "                onChoose: async () => {",
    "                    ensureChatVisible();",
    "                    await openEasySetup({ source: 'safety_suggestion', force: false, restart: true });",
    "                    handleEasySetupPathSelect('manual');",
    "                },",
    "            },",
    "            {",
    "                label: 'Show exact downloads',",
    "                kind: 'option',",
    "                send_prompt: withAgentName('Show exactly what {{agent}} installs in each setup path and why each dependency is required.'),",
    "            },",
    "        ],",
    "    });",
    "}",
    "",
    "function resolveOnboardingOptionLabel(question, value) {",
    "    const options = Array.isArray(question?.options) ? question.options : [];",
    "    const found = options.find((option) => safeString(option?.value) === safeString(value));",
    "    return safeString(found?.label) || safeString(value);",
    "}",
    "",
    "function formatOnboardingQuestionOptionList(question) {",
    "    const options = Array.isArray(question?.options) ? question.options : [];",
    "    return options.map((option) => `\"${safeString(option?.label)}\"`).filter(Boolean).join(', ');",
    "}",
    "",
    "function parseOnboardingQuestionAnswer(question, textRaw) {",
    "    const text = safeString(textRaw).toLowerCase();",
    "    if (!text) return '';",
    "    if (text === 'skip' || includesAny(text, ['skip interview', 'skip questions', 'skip setup', 'skip this'])) {",
    "        return '__skip_interview__';",
    "    }",
    "",
    "    const options = Array.isArray(question?.options) ? question.options : [];",
    "    for (const option of options) {",
    "        const valueToken = safeString(option?.value).toLowerCase().replace(/_/g, ' ');",
    "        const labelToken = safeString(option?.label).toLowerCase();",
    "        if ((valueToken && text.includes(valueToken)) || (labelToken && text.includes(labelToken))) {",
    "            return safeString(option?.value);",
    "        }",
    "    }",
    "",
    "    const questionId = safeString(question?.id);",
    "    if (questionId === 'experience') {",
    "        if (includesAny(text, ['new', 'beginner', 'novice', 'first time', 'first-time', 'non technical', 'non-technical', 'just starting'])) return 'new';",
    "        if (includesAny(text, ['expert', 'advanced', 'senior', 'professional', 'pro'])) return 'expert';",
    "        if (includesAny(text, ['builder', 'intermediate', 'some experience', 'comfortable'])) return 'builder';",
    "    }",
    "    if (questionId === 'personality') {",
    "        if (includesAny(text, ['direct', 'technical', 'blunt', 'straight', 'no fluff', 'concise'])) return 'direct_technical';",
    "        if (includesAny(text, ['calm', 'friendly', 'gentle', 'coach', 'guide', 'supportive'])) return 'calm_guide';",
    "        if (includesAny(text, ['balanced', 'normal', 'neutral', 'mix'])) return 'balanced';",
    "    }",
    "    if (questionId === 'autonomy') {",
    "        if (includesAny(text, ['guided', 'careful', 'safe', 'step by step', 'step-by-step', 'confirm', 'approval', 'ask first'])) return 'guided';",
    "        if (includesAny(text, ['aggressive', 'autonomous', 'fully auto', 'take over', 'run with it', 'do it all', 'max autonomy'])) return 'aggressive';",
    "        if (includesAny(text, ['balanced', 'normal', 'middle'])) return 'balanced';",
    "    }",
    "    if (questionId === 'cost_quality') {",
    "        if (includesAny(text, ['low cost', 'cheap', 'budget', 'save money', 'cost first', 'economy'])) return 'low_cost';",
    "        if (includesAny(text, ['max quality', 'highest quality', 'best quality', 'quality first', 'accuracy', 'premium'])) return 'max_quality';",
    "        if (includesAny(text, ['balanced', 'middle'])) return 'balanced';",
    "    }",
    "    if (questionId === 'memory') {",
    "        if (includesAny(text, ['disable memory', 'no memory', 'dont remember', 'do not remember', 'forget', 'private'])) return 'disabled';",
    "        if (includesAny(text, ['session only', 'this session', 'temporary', 'temp memory'])) return 'session_only';",
    "        if (includesAny(text, ['remember', 'across sessions', 'persistent', 'save context'])) return 'remember';",
    "    }",
    "    if (questionId === 'workflow') {",
    "        if (includesAny(text, ['build', 'ship', 'feature', 'features', 'product', 'app', 'coding', 'code'])) return 'build_features';",
    "        if (includesAny(text, ['research', 'investigate', 'analyze', 'compare', 'study'])) return 'research';",
    "        if (includesAny(text, ['ops', 'reliability', 'incident', 'monitoring', 'infra', 'infrastructure', 'production', 'stability'])) return 'ops_reliability';",
    "    }",
    "    if (questionId === 'default_toggles') {",
    "        if (includesAny(text, ['safe', 'conservative', 'cautious', 'guardrails', 'approval'])) return 'safe_defaults';",
    "        if (includesAny(text, ['power', 'advanced', 'fast', 'max control', 'pro mode'])) return 'power_mode';",
    "        if (includesAny(text, ['quiet', 'minimal', 'silent', 'fewer notifications', 'no notifications'])) return 'quiet_mode';",
    "    }",
    "",
    "    return '';",
    "}",
    "",
    "function parseOnboardingSkipConfirmAction(textRaw) {",
    "    const text = safeString(textRaw).toLowerCase();",
    "    if (!text) return '';",
    "    if (includesAny(text, ['finish', 'defaults', 'default settings', 'skip it', 'yes'])) return 'finish_defaults';",
    "    if (includesAny(text, ['resume', 'continue', 'questions', 'go back', 'no'])) return 'resume';",
    "    return '';",
    "}",
    "",
    "function parseOnboardingReviewAction(textRaw) {",
    "    const text = safeString(textRaw).toLowerCase();",
    "    if (!text) return '';",
    "    if (includesAny(text, ['open settings', 'settings', 'tweak settings'])) return 'settings';",
    "    if (includesAny(text, ['defaults', 'skip interview', 'finish with defaults', 'use defaults'])) return 'skip';",
    "    if (includesAny(text, ['finish', 'apply', 'done', 'complete', 'looks good', 'yes'])) return 'apply';",
    "    return '';",
    "}",
    "",
    "async function submitOnboardingInterviewAnswer(question, value, { source = 'bubble' } = {}) {",
    "    const index = Number(easySetupState.interviewIndex);",
    "    easySetupState.interviewAnswers[question.id] = value;",
    "    easySetupState.interviewIndex = index + 1;",
    "    easySetupState.interviewStage = 'question';",
    "    await persistOnboardingPrefs({",
    "        current_step: 'interview',",
    "        answers: { [question.id]: value },",
    "    });",
    "    emitOnboardingTelemetry('interview.answer', {",
    "        question_id: question.id,",
    "        value,",
    "        source: safeString(source) || 'bubble',",
    "    });",
    "    if (safeString(source) === 'text') {",
    "        const answerLabel = resolveOnboardingOptionLabel(question, value);",
    "        renderMessage({",
    "            role: 'assistant',",
    "            content: `Got it. **${answerLabel}** works for that.`,",
    "        });",
    "    }",
    "    promptOnboardingQuestion();",
    "}",
    "",
    "async function promptInterviewSkipConfirm() {",
    "    easySetupState.interviewStage = 'skip_confirm';",
    "    renderOnboardingChoiceBubble(",
    "        'You can skip the intake and finish with safe defaults. Want me to do that?',",
    "        [",
    "            { value: 'finish_defaults', label: 'Finish setup with defaults', kind: 'action', tone: 'primary' },",
    "            { value: 'resume', label: 'Resume questions', kind: 'action' },",
    "        ],",
    "        async (choice) => {",
    "            renderMessage({ role: 'user', content: safeString(choice?.label) });",
    "            const action = safeString(choice?.value);",
    "            if (action === 'finish_defaults') {",
    "                try {",
    "                    await applyOnboardingCompletion({ skippedInterview: true });",
    "                    renderMessage({",
    "                        role: 'assistant',",
    "                        content: withAgentName('Setup complete. {{agent}} is ready with safe defaults. You can tune anything in Settings later.'),",
    "                    });",
    "                } catch (err) {",
    "                    renderMessage({",
    "                        role: 'assistant',",
    "                        content: `Could not finalize setup: ${safeString(err?.message) || 'unknown error'}`,",
    "                    });",
    "                }",
    "                return;",
    "            }",
    "            easySetupState.interviewSkipChosen = false;",
    "            promptOnboardingQuestion();",
    "        }",
    "    );",
    "}",
    "",
    "function promptOnboardingQuestion() {",
    "    const index = Number(easySetupState.interviewIndex);",
    "    if (index >= onboardingInterviewQuestions.length) {",
    "        easySetupState.interviewStage = 'review';",
    "        const answers = easySetupState.interviewAnswers || {};",
    "        const summary = [",
    "            `Experience: ${safeString(answers.experience) || 'builder'}`,",
    "            `Autonomy: ${safeString(answers.autonomy) || 'balanced'}`,",
    "            `Cost/quality: ${safeString(answers.cost_quality) || 'balanced'}`,",
    "            `Memory: ${safeString(answers.memory) || 'remember'}`,",
    "            `Workflow: ${safeString(answers.workflow) || 'build_features'}`,",
    "        ];",
    "        renderMessage({",
    "            role: 'assistant',",
    "            content: `### Review profile\\n${summary.map((line) => `- ${line}`).join('\\n')}\\n\\nSay \"finish setup\", \"use defaults\", or \"open settings\".`,",
    "        });",
    "        renderOnboardingChoiceBubble(",
    "            'Final step',",
    "            [",
    "                { value: 'apply', label: 'Finish setup', kind: 'action', tone: 'primary' },",
    "                { value: 'skip', label: 'Finish with defaults', kind: 'action' },",
    "                { value: 'settings', label: 'Open Settings first', kind: 'action' },",
    "            ],",
    "            async (choice) => {",
    "                renderMessage({ role: 'user', content: safeString(choice?.label) });",
    "                const action = safeString(choice?.value);",
    "                if (action === 'settings') {",
    "                    openSettingsModal();",
    "                    renderMessage({",
    "                        role: 'assistant',",
    "                        content: 'Settings opened. Return and tell me to finish setup when you are ready.',",
    "                    });",
    "                    return;",
    "                }",
    "                try {",
    "                    await applyOnboardingCompletion({ skippedInterview: action === 'skip' });",
    "                    renderMessage({",
    "                        role: 'assistant',",
    "                        content: withAgentName('Onboarding complete. {{agent}} is connected and ready.'),",
    "                    });",
    "                } catch (err) {",
    "                    renderMessage({",
    "                        role: 'assistant',",
    "                        content: `Could not finalize setup: ${safeString(err?.message) || 'unknown error'}`,",
    "                    });",
    "                }",
    "            }",
    "        );",
    "        return;",
    "    }",
    "",
    "    easySetupState.interviewStage = 'question';",
    "    const question = onboardingInterviewQuestions[index];",
    "    const questionPrompt = withAgentName(question.prompt);",
    "    renderOnboardingChoiceBubble(",
    "        `### ${escapeHtml(questionPrompt)}\\nReply naturally or tap an option.`,",
    "        [",
    "            ...question.options.map((option) => ({ ...option, kind: 'option' })),",
    "            { value: '__skip_interview__', label: 'Skip intake', kind: 'action' },",
    "        ],",
    "        async (choice) => {",
    "            renderMessage({ role: 'user', content: safeString(choice?.label) });",
    "            const value = safeString(choice?.value);",
    "            if (value === '__skip_interview__') {",
    "                easySetupState.interviewSkipChosen = true;",
    "                await promptInterviewSkipConfirm();",
    "                return;",
    "            }",
    "            await submitOnboardingInterviewAnswer(question, value, { source: 'bubble' });",
    "        }",
    "    );",
    "}",
    "",
    "async function handleOnboardingChatInput(textRaw, { docsCount = 0, imagesCount = 0 } = {}) {",
    "    const text = safeString(textRaw);",
    "    if (docsCount > 0 || imagesCount > 0) {",
    "        renderMessage({",
    "            role: 'assistant',",
    "            content: 'For onboarding, plain text replies work best. I ignored attachments for this step.',",
    "        });",
    "    }",
    "    if (!text) {",
    "        renderMessage({",
    "            role: 'assistant',",
    "            content: 'Reply with your preference in plain language, or use a suggestion bubble.',",
    "        });",
    "        return;",
    "    }",
    "",
    "    const stage = safeString(easySetupState.interviewStage) || 'question';",
    "    if (stage === 'skip_confirm') {",
    "        const action = parseOnboardingSkipConfirmAction(text);",
    "        if (!action) {",
    "            if (isSecurityTrustConcern(text)) {",
    "                renderMessage({",
    "                    role: 'assistant',",
    "                    content: `${buildSetupSafetyMessage()}\\n\\nWhen ready, say \"finish with defaults\" or \"resume questions\".`,",
    "                });",
    "                return;",
    "            }",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: 'Say \"finish with defaults\" or \"resume questions\".',",
    "            });",
    "            return;",
    "        }",
    "        if (action === 'finish_defaults') {",
    "            try {",
    "                await applyOnboardingCompletion({ skippedInterview: true });",
    "                renderMessage({",
    "                    role: 'assistant',",
    "                    content: withAgentName('Setup complete. {{agent}} is ready with safe defaults.'),",
    "                });",
    "            } catch (err) {",
    "                renderMessage({",
    "                    role: 'assistant',",
    "                    content: `Could not finalize setup: ${safeString(err?.message) || 'unknown error'}`,",
    "                });",
    "            }",
    "            return;",
    "        }",
    "        easySetupState.interviewSkipChosen = false;",
    "        promptOnboardingQuestion();",
    "        return;",
    "    }",
    "",
    "    if (stage === 'review') {",
    "        const action = parseOnboardingReviewAction(text);",
    "        if (!action) {",
    "            if (isSecurityTrustConcern(text)) {",
    "                renderMessage({",
    "                    role: 'assistant',",
    "                    content: `${buildSetupSafetyMessage()}\\n\\nWhen ready, say \"finish setup\", \"use defaults\", or \"open settings\".`,",
    "                });",
    "                return;",
    "            }",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: 'Say \"finish setup\", \"use defaults\", or \"open settings\".',",
    "            });",
    "            return;",
    "        }",
    "        if (action === 'settings') {",
    "            openSettingsModal();",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: 'Settings opened. Return when you want me to finish onboarding.',",
    "            });",
    "            return;",
    "        }",
    "        try {",
    "            await applyOnboardingCompletion({ skippedInterview: action === 'skip' });",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: withAgentName('Onboarding complete. {{agent}} is connected and ready.'),",
    "            });",
    "        } catch (err) {",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: `Could not finalize setup: ${safeString(err?.message) || 'unknown error'}`,",
    "            });",
    "        }",
    "        return;",
    "    }",
    "",
    "    const question = onboardingInterviewQuestions[Number(easySetupState.interviewIndex)];",
    "    if (!question) {",
    "        promptOnboardingQuestion();",
    "        return;",
    "    }",
    "",
    "    const parsedValue = parseOnboardingQuestionAnswer(question, text);",
    "    if (parsedValue === '__skip_interview__') {",
    "        easySetupState.interviewSkipChosen = true;",
    "        await promptInterviewSkipConfirm();",
    "        return;",
    "    }",
    "    if (!parsedValue) {",
    "        if (isSecurityTrustConcern(text)) {",
    "            const optionHints = formatOnboardingQuestionOptionList(question);",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: `${buildSetupSafetyMessage()}\\n\\nWhen you are ready, answer this step: ${withAgentName(question.prompt)}\\nI can map replies like: ${optionHints}.`,",
    "            });",
    "            return;",
    "        }",
    "        const optionHints = formatOnboardingQuestionOptionList(question);",
    "        renderMessage({",
    "            role: 'assistant',",
    "            content: `I can map that, but I am not fully sure yet. Try phrasing it closer to one of: ${optionHints}.`,",
    "        });",
    "        return;",
    "    }",
    "",
    "    await submitOnboardingInterviewAnswer(question, parsedValue, { source: 'text' });",
    "}",
    "",
    "async function beginOnboardingInterview() {",
    "    easySetupState.interviewStarted = true;",
    "    easySetupState.interviewStage = 'question';",
    "    easySetupState.interviewIndex = 0;",
    "    ensureChatVisible();",
    "    await persistOnboardingPrefs({ current_step: 'interview', dismissed_at: null });",
    "    renderMessage({",
    "        role: 'assistant',",
    "        content: 'Brain handshake complete. I am caffeinated and morally obligated to make this easy. Tell me your preferences in plain English and I will translate them into setup defaults.',",
    "    });",
    "    promptOnboardingQuestion();",
    "    emitOnboardingTelemetry('interview.started', {",
    "        path: safeString(easySetupState.selectedPath),",
    "    });",
    "}",
    "",
    "// â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—",
    "// â•‘  INITIALIZATION & COMPOSER                                              â•‘",
    "// â•‘  Main init(), composer setup, slash palette, message building           â•‘",
    "// â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•",
].join("\n");
