/* split from part-030.js */
export default [
    "",
    "    const payload = {",
    "        profile: {",
    "            display_name: nextName,",
    "            avatar_url: safeString(currentPreferences?.profile?.avatar_url),",
    "        },",
    "    };",
    "",
    "    try {",
    "        const res = await fetch('/api/preferences', {",
    "            method: 'PATCH',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify(payload),",
    "        });",
    "        if (!res.ok) {",
    "            const details = await res.text();",
    "            throw new Error(details || `HTTP ${res.status}`);",
    "        }",
    "        currentPreferences = await res.json();",
    "        if (settingsDisplayName) settingsDisplayName.value = resolveAgentName(currentPreferences);",
    "        refreshSettingsAvatarPreview();",
    "        updateSidebarIdentity();",
    "        notifyUser(`Agent renamed to ${getAgentName()}.`, {",
    "            tone: 'success',",
    "            durationMs: 2200,",
    "            debugKind: 'settings',",
    "        });",
    "        emitOnboardingTelemetry('agent.renamed', {",
    "            source: safeString(source) || 'rename',",
    "            name: getAgentName(),",
    "        });",
    "        return true;",
    "    } catch (error) {",
    "        notifyUser(`Could not rename agent: ${safeString(error?.message) || 'unknown error'}`, {",
    "            tone: 'error',",
    "            durationMs: 3000,",
    "            debugKind: 'error',",
    "        });",
    "        return false;",
    "    }",
    "}",
    "",
    "async function promptRenameAgentIdentity() {",
    "    const currentName = getAgentName();",
    "    const prompted = window.prompt('Rename your assistant', currentName);",
    "    if (prompted === null) return;",
    "    const nextName = sanitizeAgentNameInput(prompted);",
    "    if (!nextName) {",
    "        notifyUser('Agent name cannot be blank.', {",
    "            tone: 'warning',",
    "            durationMs: 2400,",
    "            debugKind: 'settings',",
    "        });",
    "        return;",
    "    }",
    "    await saveAgentIdentityName(nextName, { source: 'sidebar_pencil' });",
    "}",
    "",
    "async function loadSessionFromHistory(sid) {",
    "    activeChatId = sid;",
    "    saveStoredActiveChatId(activeChatId);",
    "    rebuildChatHistorySelector();",
    "    try {",
    "        let sessionData = sidebarSessions.find((row) => safeString(row?.id) === safeString(sid)) || null;",
    "        if (!sessionData) {",
    "            await fetchChatHistory();",
    "            sessionData = sidebarSessions.find((row) => safeString(row?.id) === safeString(sid)) || null;",
    "        }",
    "        if (!sessionData) {",
    "            throw new Error(`Chat ${sid} not found.`);",
    "        }",
    "",
    "        const loadedHistory = normalizeConversationHistory(sessionData.messages);",
    "        chatHistory = loadedHistory;",
    "        chatMessagesInner.innerHTML = '';",
    "        if (chatHistory.length > 0) {",
    "            welcomeScreen.classList.add('hidden');",
    "            chatScrollArea.classList.remove('hidden');",
    "            let lastAssistantMessage = '';",
    "            let lastUserMessage = '';",
    "            chatHistory.forEach((msg) => {",
    "                renderMessage(msg);",
    "                if (safeString(msg?.role) === 'user') {",
    "                    lastUserMessage = safeString(msg?.content);",
    "                }",
    "                if (safeString(msg?.role) === 'assistant') {",
    "                    lastAssistantMessage = safeString(msg?.content);",
    "                }",
    "            });",
    "            if (lastAssistantMessage) {",
    "                maybeShowAssistantFollowups({",
    "                    assistantText: lastAssistantMessage,",
    "                    userText: lastUserMessage,",
    "                });",
    "            } else {",
    "                showStarterSuggestionRail({ force: true });",
    "            }",
    "        } else {",
    "            welcomeScreen.classList.remove('hidden');",
    "            chatScrollArea.classList.add('hidden');",
    "            maybeRenderSessionIntro();",
    "            showStarterSuggestionRail({ force: true });",
    "        }",
    "",
    "        // Bind runtime to the persisted chat id so multiple tabs/windows",
    "        // stay on one canonical session state for the same chat.",
    "        sessionId = safeString(sid);",
    "    } catch (e) { console.error(\"Error loading past session\", e); }",
    "    syncActiveChatSidebarEntry();",
    "    renderSidebarChatList();",
    "    pushDebugEvent('chat', `Loaded session ${safeString(sid)}`);",
    "    await refreshTaskContinuity({ sessionOverride: sessionId || sid, force: true });",
    "    _positionRobotDock();",
    "    if (!document.querySelector('.chat-robot-landed')) {",
    "        _landRobotAtComposerDock();",
    "    }",
    "}",
    "",
    "async function fetchModels() {",
    "    try {",
    "        const res = await fetchJsonSafe('/api/models', { timeoutMs: 8000 });",
    "        if (res.ok) {",
    "            const data = res.data || {};",
    "            availableModelProfiles = Array.isArray(data.profiles) ? data.profiles : [];",
    "            modelSelector.innerHTML = '';",
    "            setupProviderSelector.innerHTML = '';",
    "",
    "            // Partition into active (has_api_key) and inactive",
    "            const active = availableModelProfiles.filter(m => m.has_api_key);",
    "            const inactive = availableModelProfiles.filter(m => !m.has_api_key);",
    "",
    "            // Only show active providers initially",
    "            for (const m of active) {",
    "                const opt = document.createElement('option');",
    "                opt.value = m.name;",
    "                opt.textContent = m.name;",
    "                setupProviderSelector.appendChild(opt);",
    "            }",
    "",
    "            // \"Show all providers\" toggle reveals inactive ones",
    "            const showAllLink = document.getElementById('setupShowAllProviders');",
    "            if (showAllLink) {",
    "                if (inactive.length > 0) {",
    "                    showAllLink.style.display = '';",
    "                    showAllLink.onclick = (e) => {",
    "                        e.preventDefault();",
    "                        for (const m of inactive) {",
    "                            const opt = document.createElement('option');",
    "                            opt.value = m.name;",
    "                            opt.textContent = m.name;",
    "                            setupProviderSelector.appendChild(opt);",
    "                        }",
    "                        showAllLink.style.display = 'none';",
    "                    };",
    "                } else {",
    "                    showAllLink.style.display = 'none';",
    "                }",
    "            }",
    "",
    "            // Also populate hidden legacy selector",
    "            for (const m of availableModelProfiles) {",
    "                const opt = document.createElement('option');",
    "                opt.value = m.name;",
    "                opt.textContent = m.name;",
    "                modelSelector.appendChild(opt);",
    "            }",
    "",
    "            // Determine target profile: saved preference > localStorage backup > server default > first active",
    "            const savedProfile = safeString(currentPreferences?.advanced?.model?.active_profile)",
    "                || safeString(window.localStorage.getItem('thomas_active_profile'));",
    "            const savedModelId = safeString(currentPreferences?.advanced?.model?.model_id)",
    "                || safeString(window.localStorage.getItem('thomas_active_model_id'));",
    "            const targetProfile = (savedProfile && availableModelProfiles.find(m => m.name === savedProfile))",
    "                ? savedProfile",
    "                : (data.default || (active[0] && active[0].name) || (availableModelProfiles[0] && availableModelProfiles[0].name) || '');",
    "",
    "            // If target profile is inactive, ensure it's in the select",
    "            if (targetProfile && !active.find(m => m.name === targetProfile)) {",
    "                const inactiveMatch = inactive.find(m => m.name === targetProfile);",
    "                if (inactiveMatch) {",
    "                    const opt = document.createElement('option');",
    "                    opt.value = inactiveMatch.name;",
    "                    opt.textContent = inactiveMatch.name;",
    "                    setupProviderSelector.appendChild(opt);",
    "                }",
    "            }",
    "            setupProviderSelector.value = targetProfile;",
    "            modelSelector.value = targetProfile;",
    "",
    "            // Persist to localStorage as backup for next reload",
    "            if (targetProfile) {",
    "                try { window.localStorage.setItem('thomas_active_profile', targetProfile); } catch (_) {}",
    "            }",
    "",
    "            // Seed state from target profile",
    "            const tp = availableModelProfiles.find(m => m.name === targetProfile);",
    "            activeModelOverride = savedModelId || (tp ? safeString(tp.model).split('/').pop() : '');",
    "            if (activeModelOverride) {",
    "                try { window.localStorage.setItem('thomas_active_model_id', activeModelOverride); } catch (_) {}",
    "            }",
    "            if (tp && tp.reasoning_effort) activeReasoningEffort = tp.reasoning_effort;",
    "            modelSetupCurrentLabel.textContent = _profileHeaderLabel(targetProfile);",
    "",
    "            refreshEasySetupProfileOptions();",
    "            updateDebugDockSnapshot();",
    "        }",
    "    } catch (e) { console.error(\"Failed to fetch models\", e); }",
    "}",
    "",
    "function initFeatures() {",
    "    initOfficeWorkspace();",
    "    initMissionWorkspace();",
    "    initContentWorkspace();",
    "    initModuleWorkspace();",
    "    setDebugDockOpen(false, { recordEvent: false });",
    "    const restoredMode = loadStoredNavMode();",
    "    const sidebarCollapsed = loadStoredSidebarCollapsed();",
    "    chatListExpanded = loadStoredChatListExpanded();",
    "    if (sidebar) sidebar.classList.toggle('collapsed', sidebarCollapsed);",
    "    setChatListExpanded(chatListExpanded, { persist: false });",
    "    setSidebarNavMode(restoredMode, { persist: false });",
    "    if (taskContinuityRefreshBtn) {",
    "        taskContinuityRefreshBtn.addEventListener('click', () => {"
].join("\n");
