/* split from part-010.js */
export default [
    "",
    "function deriveChatTitleFromMessages(messagesRaw) {",
    "    const preview = deriveChatPreviewFromMessages(messagesRaw);",
    "    if (preview) return preview.slice(0, 72);",
    "    return 'New Chat';",
    "}",
    "",
    "function formatSidebarTimestamp(epochMs) {",
    "    const ts = Number(epochMs);",
    "    if (!Number.isFinite(ts) || ts <= 0) return '';",
    "    try {",
    "        return new Date(ts).toLocaleString([], {",
    "            month: 'short',",
    "            day: 'numeric',",
    "            hour: 'numeric',",
    "            minute: '2-digit',",
    "        });",
    "    } catch (error) {",
    "        return '';",
    "    }",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  SESSION & CHAT PERSISTENCE                                             ║",
    "// ║  Chat save/load, sidebar sessions, persistence helpers, animation locks ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function mapPersistedChatToSidebarSession(chatRaw) {",
    "    if (!chatRaw || typeof chatRaw !== 'object') return null;",
    "    const id = safeString(chatRaw.id);",
    "    if (!id) return null;",
    "",
    "    const messages = normalizeConversationHistory(chatRaw.messages);",
    "    const createdAt = Number(chatRaw.createdAt);",
    "    const updatedAt = Number(chatRaw.updatedAt);",
    "    const createdAtSafe = Number.isFinite(createdAt) && createdAt > 0 ? Math.floor(createdAt) : Date.now();",
    "    const updatedAtSafe = Number.isFinite(updatedAt) && updatedAt > 0 ? Math.floor(updatedAt) : createdAtSafe;",
    "",
    "    const title = safeString(chatRaw.title) || deriveChatTitleFromMessages(messages);",
    "    const preview = deriveChatPreviewFromMessages(messages) || title;",
    "    const model = safeString(chatRaw.model);",
    "    const timestamp = formatSidebarTimestamp(updatedAtSafe);",
    "",
    "    return {",
    "        id,",
    "        title,",
    "        preview,",
    "        model,",
    "        timestamp,",
    "        createdAt: createdAtSafe,",
    "        updatedAt: updatedAtSafe,",
    "        pinned: Boolean(chatRaw.pinned),",
    "        sessionId: safeString(chatRaw.sessionId),",
    "        messages,",
    "    };",
    "}",
    "",
    "function mapLegacySidebarSession(sessionRaw) {",
    "    if (!sessionRaw || typeof sessionRaw !== 'object') return null;",
    "    const id = safeString(sessionRaw.id);",
    "    if (!id) return null;",
    "    const preview = safeString(sessionRaw.preview);",
    "    const title = preview || `Chat ${id.slice(0, 8)}`;",
    "    return {",
    "        id,",
    "        title,",
    "        preview: preview || title,",
    "        model: safeString(sessionRaw.model),",
    "        timestamp: safeString(sessionRaw.timestamp),",
    "        createdAt: Date.now(),",
    "        updatedAt: Date.now(),",
    "        pinned: false,",
    "        sessionId: id,",
    "        messages: normalizeConversationHistory(sessionRaw.conversation),",
    "    };",
    "}",
    "",
    "function activeProfileNameForPersistence() {",
    "    return (",
    "        safeString(setupProviderSelector?.value)",
    "        || safeString(modelSelector?.value)",
    "        || safeString(availableModelProfiles.find((p) => safeString(p?.name) === safeString(modelSelector?.value))?.name)",
    "        || ''",
    "    );",
    "}",
    "",
    "function formatSidebarSessionTitle(session) {",
    "    const title = safeString(session?.title);",
    "    if (title) return title;",
    "    const preview = safeString(session?.preview);",
    "    if (preview) return preview;",
    "    const sid = safeString(session?.id);",
    "    return sid ? `Chat ${sid.slice(0, 8)}` : 'Untitled chat';",
    "}",
    "",
    "function formatSidebarSessionMeta(session) {",
    "    const model = safeString(session?.model) || activeProfileNameForPersistence();",
    "    const timestamp = safeString(session?.timestamp);",
    "    if (model && timestamp) return `${model} | ${timestamp}`;",
    "    if (model) return model;",
    "    if (timestamp) return timestamp;",
    "    return 'Chat';",
    "}",
    "",
    "function rebuildChatHistorySelector() {",
    "    if (!chatHistorySelector) return;",
    "    const activeId = safeString(activeChatId) || safeString(sessionId);",
    "    chatHistorySelector.innerHTML = '<option value=\"new\">New Chat</option>';",
    "    sidebarSessions.forEach((session) => {",
    "        const sid = safeString(session?.id);",
    "        if (!sid) return;",
    "        const opt = document.createElement('option');",
    "        opt.value = sid;",
    "        const title = formatSidebarSessionTitle(session);",
    "        opt.textContent = title.length > 36 ? `${title.slice(0, 33)}...` : title;",
    "        if (sid === activeId) opt.selected = true;",
    "        chatHistorySelector.appendChild(opt);",
    "    });",
    "}",
    "",
    "function upsertSidebarSession(sessionRaw) {",
    "    const session = mapPersistedChatToSidebarSession(sessionRaw) || mapLegacySidebarSession(sessionRaw);",
    "    if (!session) return;",
    "    const sid = safeString(session.id);",
    "    sidebarSessions = [",
    "        session,",
    "        ...sidebarSessions.filter((row) => safeString(row?.id) !== sid),",
    "    ];",
    "    sidebarSessions.sort((a, b) => Number(b?.updatedAt || 0) - Number(a?.updatedAt || 0));",
    "}",
    "",
    "function syncActiveChatSidebarEntry() {",
    "    const chatId = safeString(activeChatId) || safeString(sessionId);",
    "    if (!chatId) return;",
    "    saveStoredActiveChatId(chatId);",
    "    const normalizedMessages = normalizeConversationHistory(chatHistory);",
    "    const now = Date.now();",
    "    const existing = sidebarSessions.find((s) => safeString(s?.id) === chatId) || null;",
    "    const payload = {",
    "        id: chatId,",
    "        title: deriveChatTitleFromMessages(normalizedMessages),",
    "        messages: normalizedMessages,",
    "        createdAt: Number(existing?.createdAt || now),",
    "        updatedAt: now,",
    "        pinned: Boolean(existing?.pinned),",
    "        sessionId: safeString(sessionId) || null,",
    "        model: activeProfileNameForPersistence(),",
    "    };",
    "    upsertSidebarSession(payload);",
    "    rebuildChatHistorySelector();",
    "    renderSidebarChatList();",
    "}",
    "",
    "function buildPersistedChatPayload() {",
    "    const chatId = safeString(activeChatId) || safeString(sessionId);",
    "    if (!chatId) return null;",
    "    const normalizedMessages = normalizeConversationHistory(chatHistory);",
    "    const now = Date.now();",
    "    const existing = sidebarSessions.find((s) => safeString(s?.id) === chatId) || null;",
    "    return {",
    "        id: chatId,",
    "        title: deriveChatTitleFromMessages(normalizedMessages),",
    "        messages: normalizedMessages,",
    "        createdAt: Number(existing?.createdAt || now),",
    "        updatedAt: now,",
    "        pinned: Boolean(existing?.pinned),",
    "        sessionId: safeString(sessionId) || null,",
    "        model: activeProfileNameForPersistence(),",
    "    };",
    "}",
    "",
    "async function persistActiveChat({ quiet = true } = {}) {",
    "    const payload = buildPersistedChatPayload();",
    "    if (!payload) return false;",
    "    activeChatId = safeString(payload.id);",
    "    chatPersistQueued = true;",
    "    if (chatPersistInFlight) return true;",
    "    chatPersistInFlight = true;",
    "",
    "    let ok = true;",
    "    try {",
    "        while (chatPersistQueued) {",
    "            chatPersistQueued = false;",
    "            const nextPayload = buildPersistedChatPayload();",
    "            if (!nextPayload) continue;",
    "            try {",
    "                const res = await fetch(`/api/chats/${encodeURIComponent(nextPayload.id)}`, {",
    "                    method: 'PUT',",
    "                    headers: { 'Content-Type': 'application/json' },",
    "                    body: JSON.stringify(nextPayload),",
    "                });",
    "                if (!res.ok) {",
    "                    const details = safeString(await res.text()) || `HTTP ${res.status}`;",
    "                    throw new Error(details);",
    "                }",
    "                const body = await res.json();",
    "                const persisted = mapPersistedChatToSidebarSession(body?.chat) || mapPersistedChatToSidebarSession(nextPayload);",
    "                if (persisted) {",
    "                    upsertSidebarSession(persisted);",
    "                    rebuildChatHistorySelector();",
    "                    renderSidebarChatList();",
    "                    updateDebugDockSnapshot();",
    "                }",
    "            } catch (error) {",
    "                ok = false;",
    "                console.error('Failed to persist chat', error);",
    "                if (!quiet) {",
    "                    notifyUser(`Could not save chat: ${safeString(error?.message) || 'unknown error'}`, {",
    "                        tone: 'warning',",
    "                        durationMs: 2600,",
    "                        debugKind: 'error',",
    "                    });",
    "                }",
    "            }",
    "        }",
    "    } finally {",
    "        chatPersistInFlight = false;",
    "    }",
    "    return ok;",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  VIRTUAL OFFICE                                                         ║",
    "// ║  Office sim, agent movement, room rendering, minimap, sprite painting   ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function officeClamp(value, min, max) {",
    "    return Math.max(min, Math.min(max, value));",
    "}",
    "",
    "function officeRandomRange(min, max) {",
    "    return min + (Math.random() * (max - min));",
    "}",
    "",
    "function officeStableHash(valueRaw) {",
    "    const input = safeString(valueRaw);",
    "    let hash = 2166136261;",
    "    for (let i = 0; i < input.length; i += 1) {",
    "        hash ^= input.charCodeAt(i);",
    "        hash = Math.imul(hash, 16777619);"
].join("\n");
