/* app.js lines 17001-18000 */
export default [
    "function contentEnsureState() {",
    "    if (!contentWorkspace) return null;",
    "    if (!contentState) {",
    "        contentState = {",
    "            controlsBound: false,",
    "            loading: false,",
    "            lastFetchedAt: 0,",
    "            error: '',",
    "            payload: null,",
    "        };",
    "    }",
    "    return contentState;",
    "}",
    "",
    "function contentToCount(value, fallback = 0) {",
    "    const num = Number(value);",
    "    if (!Number.isFinite(num)) return fallback;",
    "    return Math.max(0, Math.round(num));",
    "}",
    "",
    "function contentEmptyPayload() {",
    "    return {",
    "        generatedAt: '',",
    "        summary: {",
    "            connected_platforms: 0,",
    "            known_platforms: 0,",
    "            total_jobs: 0,",
    "            active_jobs: 0,",
    "            queued_posts: 0,",
    "            workflows: 0,",
    "            scheduled_posts: 0,",
    "            approvals_pending: 0,",
    "            sessions_active: 0,",
    "            sessions_recent_total: 0,",
    "            cron_jobs: 0,",
    "            skills_installed: 0,",
    "            api_keys_configured: 0,",
    "            logs_last_24h: 0,",
    "        },",
    "        platforms: [],",
    "        workflows: [],",
    "        scheduler: [],",
    "        tools: [],",
    "        control_surface: {",
    "            chat_first: { enabled: true, detail: '' },",
    "            cards: [],",
    "            health_status: 'attention',",
    "            health_checks: [],",
    "        },",
    "        navigation: [],",
    "        organization_axes: [],",
    "        checklist: [],",
    "    };",
    "}",
    "",
    "function contentNormalizePayload(payloadRaw) {",
    "    const payload = payloadRaw && typeof payloadRaw === 'object' ? payloadRaw : {};",
    "    const summaryRaw = payload.summary && typeof payload.summary === 'object' ? payload.summary : {};",
    "    const controlRaw = payload.control_surface && typeof payload.control_surface === 'object'",
    "        ? payload.control_surface",
    "        : {};",
    "    return {",
    "        generatedAt: safeString(payload.generated_at),",
    "        summary: {",
    "            connected_platforms: contentToCount(summaryRaw.connected_platforms),",
    "            known_platforms: contentToCount(summaryRaw.known_platforms),",
    "            total_jobs: contentToCount(summaryRaw.total_jobs),",
    "            active_jobs: contentToCount(summaryRaw.active_jobs),",
    "            queued_posts: contentToCount(summaryRaw.queued_posts),",
    "            workflows: contentToCount(summaryRaw.workflows),",
    "            scheduled_posts: contentToCount(summaryRaw.scheduled_posts),",
    "            approvals_pending: contentToCount(summaryRaw.approvals_pending),",
    "            sessions_active: contentToCount(summaryRaw.sessions_active),",
    "            sessions_recent_total: contentToCount(summaryRaw.sessions_recent_total),",
    "            cron_jobs: contentToCount(summaryRaw.cron_jobs),",
    "            skills_installed: contentToCount(summaryRaw.skills_installed),",
    "            api_keys_configured: contentToCount(summaryRaw.api_keys_configured),",
    "            logs_last_24h: contentToCount(summaryRaw.logs_last_24h),",
    "        },",
    "        platforms: Array.isArray(payload.platforms) ? payload.platforms : [],",
    "        workflows: Array.isArray(payload.workflows) ? payload.workflows : [],",
    "        scheduler: Array.isArray(payload.scheduler) ? payload.scheduler : [],",
    "        tools: Array.isArray(payload.tools) ? payload.tools : [],",
    "        control_surface: {",
    "            chat_first: controlRaw.chat_first && typeof controlRaw.chat_first === 'object'",
    "                ? controlRaw.chat_first",
    "                : { enabled: true, detail: '' },",
    "            cards: Array.isArray(controlRaw.cards) ? controlRaw.cards : [],",
    "            health_status: safeString(controlRaw.health_status) || 'attention',",
    "            health_checks: Array.isArray(controlRaw.health_checks) ? controlRaw.health_checks : [],",
    "        },",
    "        navigation: Array.isArray(payload.navigation) ? payload.navigation : [],",
    "        organization_axes: Array.isArray(payload.organization_axes) ? payload.organization_axes : [],",
    "        checklist: Array.isArray(payload.checklist) ? payload.checklist : [],",
    "    };",
    "}",
    "",
    "function contentFormatNumber(value) {",
    "    const num = Number(value || 0);",
    "    if (!Number.isFinite(num)) return '0';",
    "    return num.toLocaleString();",
    "}",
    "",
    "function contentParseDate(valueRaw) {",
    "    const raw = safeString(valueRaw);",
    "    if (!raw) return null;",
    "    const dt = new Date(raw);",
    "    if (Number.isNaN(dt.getTime())) return null;",
    "    return dt;",
    "}",
    "",
    "function contentFormatScheduleDay(valueRaw) {",
    "    const dt = contentParseDate(valueRaw);",
    "    if (!dt) return '--';",
    "    return dt.toLocaleDateString(undefined, { weekday: 'long' });",
    "}",
    "",
    "function contentFormatScheduleTime(valueRaw) {",
    "    const dt = contentParseDate(valueRaw);",
    "    if (!dt) return '--';",
    "    return dt.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });",
    "}",
    "",
    "function contentPlatformConnected(platform) {",
    "    if (typeof platform?.connected === 'boolean') return platform.connected;",
    "    return Number(platform?.total_jobs || 0) > 0;",
    "}",
    "",
    "function contentStatusClass(statusRaw) {",
    "    const slug = safeString(statusRaw)",
    "        .toLowerCase()",
    "        .replace(/[^a-z0-9]+/g, '-')",
    "        .replace(/^-+|-+$/g, '');",
    "    return slug ? ` status-${slug}` : '';",
    "}",
    "",
    "function contentRenderPlatforms(platforms = []) {",
    "    if (!contentPlatformGrid) return;",
    "    contentPlatformGrid.innerHTML = '';",
    "    if (!platforms.length) {",
    "        const empty = document.createElement('div');",
    "        empty.className = 'content-item-empty';",
    "        empty.textContent = 'No platforms connected yet.';",
    "        contentPlatformGrid.appendChild(empty);",
    "        return;",
    "    }",
    "",
    "    const frag = document.createDocumentFragment();",
    "    platforms.forEach((platform) => {",
    "        const connected = contentPlatformConnected(platform);",
    "        const row = document.createElement('article');",
    "        row.className = 'content-platform-card';",
    "        row.innerHTML = `",
    "            <div class=\"content-platform-head\">",
    "                <h4>${escapeHtml(platform?.name || 'Platform')}</h4>",
    "                <span class=\"content-pill ${connected ? 'connected' : 'offline'}\">${connected ? 'Connected' : 'Not Connected'}</span>",
    "            </div>",
    "            <div class=\"content-platform-metrics\">",
    "                <span>Total Jobs <strong>${contentFormatNumber(platform?.total_jobs)}</strong></span>",
    "                <span>Queued <strong>${contentFormatNumber(platform?.queued)}</strong></span>",
    "                <span>Running <strong>${contentFormatNumber(platform?.running)}</strong></span>",
    "                <span>Needs Approval <strong>${contentFormatNumber(platform?.awaiting_approval)}</strong></span>",
    "                <span>Published <strong>${contentFormatNumber(platform?.published)}</strong></span>",
    "                <span>Failed <strong>${contentFormatNumber(platform?.failed)}</strong></span>",
    "            </div>",
    "        `;",
    "        frag.appendChild(row);",
    "    });",
    "    contentPlatformGrid.appendChild(frag);",
    "}",
    "",
    "function contentRenderWorkflows(workflows = []) {",
    "    if (!contentWorkflowGrid) return;",
    "    contentWorkflowGrid.innerHTML = '';",
    "    if (!workflows.length) {",
    "        const empty = document.createElement('div');",
    "        empty.className = 'content-item-empty';",
    "        empty.textContent = 'No workflows configured yet.';",
    "        contentWorkflowGrid.appendChild(empty);",
    "        return;",
    "    }",
    "",
    "    const frag = document.createDocumentFragment();",
    "    workflows.forEach((workflow) => {",
    "        const activeJobs = contentToCount(workflow?.active_jobs);",
    "        const totalJobs = contentToCount(workflow?.total_jobs);",
    "        const row = document.createElement('article');",
    "        row.className = 'content-workflow-card';",
    "        row.innerHTML = `",
    "            <h4>${escapeHtml(workflow?.name || 'Workflow')}</h4>",
    "            <p><span>Trigger:</span> ${escapeHtml(safeString(workflow?.trigger))}</p>",
    "            <p><span>Automation:</span> ${escapeHtml(safeString(workflow?.automation))}</p>",
    "            <p><span>Approval:</span> ${escapeHtml(safeString(workflow?.approval))}</p>",
    "            <p><span>Load:</span> ${contentFormatNumber(activeJobs)} active / ${contentFormatNumber(totalJobs)} total</p>",
    "        `;",
    "        frag.appendChild(row);",
    "    });",
    "    contentWorkflowGrid.appendChild(frag);",
    "}",
    "",
    "function contentRenderScheduler(schedule = []) {",
    "    if (!contentSchedulerRows) return;",
    "    contentSchedulerRows.innerHTML = '';",
    "    if (!schedule.length) {",
    "        const row = document.createElement('tr');",
    "        row.innerHTML = '<td colspan=\"5\">No scheduled content yet.</td>';",
    "        contentSchedulerRows.appendChild(row);",
    "        return;",
    "    }",
    "",
    "    const frag = document.createDocumentFragment();",
    "    schedule.forEach((item) => {",
    "        const runAt = safeString(item?.run_at);",
    "        const day = safeString(item?.day) || contentFormatScheduleDay(runAt);",
    "        const time = safeString(item?.time) || contentFormatScheduleTime(runAt);",
    "        const platform = safeString(item?.platform || item?.channel) || 'All Channels';",
    "        const type = safeString(item?.type || item?.workflow) || 'Scheduled content';",
    "        const status = safeString(item?.status) || 'Queued';",
    "        const row = document.createElement('tr');",
    "        row.innerHTML = `",
    "            <td>${escapeHtml(day)}</td>",
    "            <td>${escapeHtml(time)}</td>",
    "            <td>${escapeHtml(platform)}</td>",
    "            <td>${escapeHtml(type)}</td>",
    "            <td><span class=\"content-status-pill${contentStatusClass(status)}\">${escapeHtml(status)}</span></td>",
    "        `;",
    "        frag.appendChild(row);",
    "    });",
    "    contentSchedulerRows.appendChild(frag);",
    "}",
    "",
    "function contentRenderTools(tools = []) {",
    "    if (!contentToolsGrid) return;",
    "    contentToolsGrid.innerHTML = '';",
    "    if (!tools.length) {",
    "        const empty = document.createElement('div');",
    "        empty.className = 'content-item-empty';",
    "        empty.textContent = 'No manager tools configured yet.';",
    "        contentToolsGrid.appendChild(empty);",
    "        return;",
    "    }",
    "",
    "    const frag = document.createDocumentFragment();",
    "    tools.forEach((tool) => {",
    "        const status = safeString(tool?.status);",
    "        const row = document.createElement('article');",
    "        row.className = 'content-tool-card';",
    "        row.innerHTML = `",
    "            <h4>${escapeHtml(tool?.title || 'Capability')}</h4>",
    "            ${status ? `<p class=\"content-tool-status\">Status: ${escapeHtml(status)}</p>` : ''}",
    "            <p>${escapeHtml(safeString(tool?.detail))}</p>",
    "        `;",
    "        frag.appendChild(row);",
    "    });",
    "    contentToolsGrid.appendChild(frag);",
    "}",
    "",
    "function contentToneClass(statusRaw, prefix = 'tone-') {",
    "    const slug = safeString(statusRaw)",
    "        .toLowerCase()",
    "        .replace(/[^a-z0-9]+/g, '-')",
    "        .replace(/^-+|-+$/g, '');",
    "    return slug ? `${prefix}${slug}` : `${prefix}neutral`;",
    "}",
    "",
    "function contentRenderControl(control = null) {",
    "    if (!contentControlGrid) return;",
    "    contentControlGrid.innerHTML = '';",
    "    const cards = Array.isArray(control?.cards) ? control.cards : [];",
    "    if (!cards.length) {",
    "        const empty = document.createElement('div');",
    "        empty.className = 'content-item-empty';",
    "        empty.textContent = 'Control surface data will appear after the first sync.';",
    "        contentControlGrid.appendChild(empty);",
    "        return;",
    "    }",
    "",
    "    const frag = document.createDocumentFragment();",
    "    cards.forEach((card) => {",
    "        const row = document.createElement('article');",
    "        row.className = `content-control-card ${contentToneClass(card?.status, 'tone-')}`.trim();",
    "        row.innerHTML = `",
    "            <span class=\"content-control-label\">${escapeHtml(safeString(card?.label) || 'Control')}</span>",
    "            <strong class=\"content-control-value\">${escapeHtml(safeString(card?.value) || '--')}</strong>",
    "            <span class=\"content-control-status\">${escapeHtml(safeString(card?.status) || 'idle')}</span>",
    "            <p>${escapeHtml(safeString(card?.detail))}</p>",
    "        `;",
    "        frag.appendChild(row);",
    "    });",
    "",
    "    const checks = Array.isArray(control?.health_checks) ? control.health_checks : [];",
    "    if (checks.length) {",
    "        const checksCard = document.createElement('article');",
    "        checksCard.className = 'content-control-card content-control-health';",
    "        const lines = checks",
    "            .slice(0, 8)",
    "            .map((check) => {",
    "                const name = escapeHtml(safeString(check?.name) || 'check');",
    "                const status = escapeHtml(safeString(check?.status) || 'unknown');",
    "                const detail = escapeHtml(safeString(check?.detail));",
    "                return `<li><span>${name}</span><strong>${status}</strong><em>${detail}</em></li>`;",
    "            })",
    "            .join('');",
    "        checksCard.innerHTML = `",
    "            <span class=\"content-control-label\">Health Checks</span>",
    "            <ul class=\"content-health-list\">${lines}</ul>",
    "        `;",
    "        frag.appendChild(checksCard);",
    "    }",
    "    contentControlGrid.appendChild(frag);",
    "}",
    "",
    "function contentRenderTrackList(container, rows = [], emptyText = 'No entries yet.') {",
    "    if (!container) return;",
    "    container.innerHTML = '';",
    "    if (!rows.length) {",
    "        const empty = document.createElement('div');",
    "        empty.className = 'content-item-empty';",
    "        empty.textContent = emptyText;",
    "        container.appendChild(empty);",
    "        return;",
    "    }",
    "    const frag = document.createDocumentFragment();",
    "    rows.forEach((row) => {",
    "        const item = document.createElement('article');",
    "        item.className = 'content-track-card';",
    "        item.innerHTML = `",
    "            <h4>${escapeHtml(safeString(row?.label) || 'Item')}</h4>",
    "            <p>${escapeHtml(safeString(row?.description))}</p>",
    "        `;",
    "        frag.appendChild(item);",
    "    });",
    "    container.appendChild(frag);",
    "}",
    "",
    "function contentRenderChecklist(groups = []) {",
    "    if (!contentChecklistGrid) return;",
    "    contentChecklistGrid.innerHTML = '';",
    "    if (!groups.length) {",
    "        const empty = document.createElement('div');",
    "        empty.className = 'content-item-empty';",
    "        empty.textContent = 'Checklist categories are loading.';",
    "        contentChecklistGrid.appendChild(empty);",
    "        return;",
    "    }",
    "    const frag = document.createDocumentFragment();",
    "    groups.forEach((group) => {",
    "        const status = safeString(group?.status) || 'planned';",
    "        const items = Array.isArray(group?.items) ? group.items : [];",
    "        const itemLines = items",
    "            .slice(0, 8)",
    "            .map((line) => `<li>${escapeHtml(safeString(line))}</li>`)",
    "            .join('');",
    "        const card = document.createElement('article');",
    "        card.className = 'content-checklist-card';",
    "        card.innerHTML = `",
    "            <div class=\"content-checklist-head\">",
    "                <h4>${escapeHtml(safeString(group?.title) || 'Checklist Group')}</h4>",
    "                <span class=\"content-plan-pill ${contentToneClass(status, 'status-')}\">${escapeHtml(status)}</span>",
    "            </div>",
    "            <p>${escapeHtml(safeString(group?.summary))}</p>",
    "            <ul>${itemLines}</ul>",
    "        `;",
    "        frag.appendChild(card);",
    "    });",
    "    contentChecklistGrid.appendChild(frag);",
    "}",
    "",
    "async function contentRefresh({ silent = false } = {}) {",
    "    const state = contentEnsureState();",
    "    if (!state || state.loading) return false;",
    "    state.loading = true;",
    "    if (!silent && contentPlatformMeta) {",
    "        contentPlatformMeta.textContent = 'Loading live mission data...';",
    "    }",
    "    contentRender();",
    "    try {",
    "        const res = await fetchJsonSafe('/api/mission/content-hub');",
    "        if (!res.ok || !res.data || typeof res.data !== 'object') {",
    "            const reason = safeString(res?.data?.error) || safeString(res?.text) || `HTTP ${res.status}`;",
    "            throw new Error(reason || 'request failed');",
    "        }",
    "        state.payload = contentNormalizePayload(res.data);",
    "        state.error = '';",
    "        state.lastFetchedAt = Date.now();",
    "        return true;",
    "    } catch (error) {",
    "        state.error = safeString(error?.message) || 'Unable to load live content data.';",
    "        if (!state.payload) state.payload = contentEmptyPayload();",
    "        return false;",
    "    } finally {",
    "        state.loading = false;",
    "        contentRender();",
    "    }",
    "}",
    "",
    "async function spendRefresh({ force = false } = {}) {",
    "    if (!force && spendState.lastFetchedAt && (Date.now() - spendState.lastFetchedAt < 30000)) return;",
    "    try {",
    "        const res = await fetchJsonSafe('/api/spend/today');",
    "        if (res.ok && res.data && typeof res.data === 'object') {",
    "            spendState.payload = res.data;",
    "            spendState.lastFetchedAt = Date.now();",
    "        }",
    "    } catch (_) { /* silent */ }",
    "}",
    "",
    "async function goalsRefresh({ force = false } = {}) {",
    "    if (!force && goalsState.lastFetchedAt && (Date.now() - goalsState.lastFetchedAt < 30000)) return;",
    "    try {",
    "        const res = await fetchJsonSafe('/api/goals/stats');",
    "        if (res.ok && res.data && typeof res.data === 'object') {",
    "            goalsState.payload = res.data;",
    "            goalsState.lastFetchedAt = Date.now();",
    "        }",
    "    } catch (_) { /* silent */ }",
    "}",
    "",
    "function contentRender() {",
    "    const state = contentEnsureState();",
    "    if (!state) return;",
    "    const payload = state.payload || contentEmptyPayload();",
    "    const summary = payload.summary || {};",
    "    const platforms = Array.isArray(payload.platforms) ? payload.platforms : [];",
    "    const workflows = Array.isArray(payload.workflows) ? payload.workflows : [];",
    "    const schedule = Array.isArray(payload.scheduler) ? payload.scheduler : [];",
    "    const tools = Array.isArray(payload.tools) ? payload.tools : [];",
    "    const control = payload.control_surface && typeof payload.control_surface === 'object'",
    "        ? payload.control_surface",
    "        : {};",
    "    const navItems = Array.isArray(payload.navigation) ? payload.navigation : [];",
    "    const axes = Array.isArray(payload.organization_axes) ? payload.organization_axes : [];",
    "    const checklist = Array.isArray(payload.checklist) ? payload.checklist : [];",
    "    const connectedFromRows = platforms.filter((platform) => contentPlatformConnected(platform)).length;",
    "    const connected = contentToCount(summary.connected_platforms, connectedFromRows);",
    "    const knownPlatforms = contentToCount(summary.known_platforms, platforms.length);",
    "    const activeJobs = contentToCount(summary.active_jobs);",
    "    const queuedPosts = contentToCount(summary.queued_posts);",
    "    const workflowCount = contentToCount(summary.workflows, workflows.length);",
    "    const scheduledPosts = contentToCount(summary.scheduled_posts, schedule.length);",
    "    const approvalsPending = contentToCount(summary.approvals_pending);",
    "    const sessionsActive = contentToCount(summary.sessions_active);",
    "    const cronJobs = contentToCount(summary.cron_jobs);",
    "    const skillsInstalled = contentToCount(summary.skills_installed);",
    "    const apiKeysConfigured = contentToCount(summary.api_keys_configured);",
    "    const logs24h = contentToCount(summary.logs_last_24h);",
    "    const generatedLabel = payload.generatedAt ? missionRelativeTime(payload.generatedAt) : '--';",
    "",
    "    if (contentConnectedCount) contentConnectedCount.textContent = contentFormatNumber(connected);",
    "    if (contentConnectedMeta) contentConnectedMeta.textContent = `${connected} of ${knownPlatforms} channels active`;",
    "    if (contentAudienceCount) contentAudienceCount.textContent = contentFormatNumber(activeJobs);",
    "    if (contentAudienceMeta) contentAudienceMeta.textContent = 'jobs currently queued, running, or awaiting approval';",
    "    if (contentQueuedCount) contentQueuedCount.textContent = contentFormatNumber(queuedPosts);",
    "    if (contentQueuedMeta) contentQueuedMeta.textContent = `${scheduledPosts} scheduled publish jobs`;",
    "    if (contentWorkflowCount) contentWorkflowCount.textContent = contentFormatNumber(workflowCount);",
    "    if (contentWorkflowMetaSummary) {",
    "        contentWorkflowMetaSummary.textContent = approvalsPending > 0",
    "            ? `${approvalsPending} approvals pending`",
    "            : `updated ${generatedLabel}`;",
    "    }",
    "",
    "    if (contentPlatformMeta) {",
    "        contentPlatformMeta.textContent = state.loading",
    "            ? 'Loading live mission data...'",
    "            : `${connected} connected platform streams`;",
    "    }",
    "    if (contentWorkflowMeta) contentWorkflowMeta.textContent = `${workflowCount} workflow groups from real jobs`;",
    "    if (contentSchedulerMeta) contentSchedulerMeta.textContent = `${schedule.length} scheduler rows`;",
    "    if (contentToolsMeta) {",
    "        const errorLine = state.error ? `Sync issue: ${state.error}` : '';",
    "        contentToolsMeta.textContent = errorLine || `${tools.length} management capabilities`;",
    "    }",
    "    if (contentControlMeta) {",
    "        const health = safeString(control?.health_status) || 'attention';",
    "        const base = `Sessions ${sessionsActive} | Cron ${cronJobs} | Skills ${skillsInstalled} | Keys ${apiKeysConfigured} | Logs24h ${logs24h}`;",
    "        contentControlMeta.textContent = state.loading",
    "            ? 'Loading run-state telemetry...'",
    "            : `${base} | Health ${health}`;",
    "    }",
    "    if (contentNavMeta) contentNavMeta.textContent = `${navItems.length} core workspace sections`;",
    "    if (contentAxisMeta) contentAxisMeta.textContent = `${axes.length} organization lens${axes.length === 1 ? '' : 'es'} mapped`;",
    "    if (contentChecklistMeta) {",
    "        const partial = checklist.filter((item) => safeString(item?.status) === 'partial').length;",
    "        const live = checklist.filter((item) => safeString(item?.status) === 'live').length;",
    "        contentChecklistMeta.textContent = `${checklist.length} categories tracked | ${partial} partial | ${live} live`;",
    "    }",
    "",
    "    contentRenderPlatforms(platforms);",
    "    contentRenderWorkflows(workflows);",
    "    contentRenderScheduler(schedule);",
    "    contentRenderTools(tools);",
    "    contentRenderControl(control);",
    "    contentRenderTrackList(contentNavList, navItems, 'Navigation map unavailable.');",
    "    contentRenderTrackList(contentAxisList, axes, 'Organization axes unavailable.');",
    "    contentRenderChecklist(checklist);",
    "}",
    "",
    "function contentEnterMode() {",
    "    const state = contentEnsureState();",
    "    if (!state) return;",
    "    contentRender();",
    "    if (!state.lastFetchedAt || (Date.now() - state.lastFetchedAt) > CONTENT_HUB_STALE_MS) {",
    "        void contentRefresh({ silent: true });",
    "    }",
    "}",
    "",
    "function contentLeaveMode() {}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  MODULE SYSTEM (COMMAND CENTER)                                         ║",
    "// ║  19 nav modes, seeds, surfaces, workbench config, module state machine  ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "const MODULE_NAV_MODES = Object.freeze([",
    "    'dashboard',",
    "    'operations',",
    "    'inbox',",
    "    'notifications',",
    "    'automations',",
    "    'agents',",
    "    'studio',",
    "    'dev_studio',",
    "    'app_builder',",
    "    'game_studio',",
    "    'lab_3d',",
    "    'research_lab',",
    "    'people',",
    "    'finance',",
    "    'integrations',",
    "    'marketplace',",
    "    'vault',",
    "    'timeline',",
    "    'infinite',",
    "]);",
    "const MODULE_NAV_MODE_SET = new Set(MODULE_NAV_MODES);",
    "const MODULE_ITEM_DISMISS_ACTIONS = new Set(['done', 'archive', 'dismiss', 'ack', 'resolve', 'snooze', 'complete']);",
    "",
    "const MODULE_MODE_SEEDS = Object.freeze({",
    "    dashboard: {",
    "        title: 'Dashboard',",
    "        subtitle: 'What matters right now.',",
    "        pill: 'Live',",
    "        kpis: [",
    "            { label: 'Task Jobs', key: 'task_jobs', meta: 'deterministic workflows' },",
    "            { label: 'Cron Jobs', key: 'cron_jobs', meta: 'scheduled automation' },",
    "            { label: 'Approvals', key: 'approvals_pending', meta: 'manual decisions' },",
    "            { label: 'Connected', key: 'integrations_connected', meta: 'live integrations' },",
    "        ],",
    "        actions: [",
    "            { id: 'start_focus', label: 'Start Focus', meta: '90-minute deep work block.' },",
    "            { id: 'draft_reply', label: 'Draft Reply', meta: 'Prepare top inbox replies.' },",
    "            { id: 'run_workflow', label: 'Run Workflow', meta: 'Execute selected flow now.' },",
    "            { id: 'create_asset', label: 'Create Asset', meta: 'Open production action.' },",
    "        ],",
    "    },",
    "    operations: {",
    "        title: 'Operations',",
    "        subtitle: 'Business control room for customers, orders, inventory, and schedule.',",
    "        pill: 'Ops',",
    "        kpis: [",
    "            { label: 'Open Orders', key: 'task_jobs', meta: 'active operational tasks' },",
    "            { label: 'Exceptions', key: 'flow_failures', meta: 'failed or blocked flows' },",
    "            { label: 'Approvals', key: 'approvals_pending', meta: 'human decisions pending' },",
    "            { label: 'Connected', key: 'integrations_connected', meta: 'live business integrations' },",
    "        ],",
    "        actions: [",
    "            { id: 'open_today_queue', label: 'Open Today Queue', meta: 'Show highest-priority operations.' },",
    "            { id: 'draft_customer_followup', label: 'Draft Customer Follow-up', meta: 'Prepare outreach for blocked orders.' },",
    "            { id: 'run_reorder', label: 'Run Reorder Check', meta: 'Find low-stock items and supplier actions.' },",
    "            { id: 'open_disputes', label: 'Open Disputes', meta: 'Review cases that need negotiation.' },",
    "        ],",
    "    },",
    "    inbox: {",
    "        title: 'Inbox',",
    "        subtitle: 'Unified email, DMs, and SMS with triage.',",
    "        pill: 'Triage',",
    "        kpis: [",
    "            { label: 'Unread', key: 'inbox_unread', meta: 'across channels' },",
    "            { label: 'Urgent', key: 'inbox_urgent', meta: 'priority queue' },",
    "            { label: 'Needs Reply', key: 'inbox_needs_reply', meta: 'open commitments' },",
    "            { label: 'Newsletters', key: 'inbox_newsletters', meta: 'batch later' },",
    "        ],",
    "        actions: [",
    "            { id: 'summarize_thread', label: 'Summarize Thread', meta: 'Create quick thread summary.' },",
    "            { id: 'draft_reply', label: 'Draft Reply', meta: 'Generate response draft.' },",
    "            { id: 'schedule_followup', label: 'Schedule Follow-up', meta: 'Create reminder with context.' },",
    "            { id: 'create_rule', label: 'Create Rule', meta: 'Auto-label and route messages.' },",
    "        ],",
    "    },",
    "    notifications: {",
    "        title: 'Notifications Center',",
    "        subtitle: 'Robot board: severity, bundling, and escalation.',",
    "        pill: 'Rules',",
    "        kpis: [",
    "            { label: 'Rules', key: 'notif_rules', meta: 'active policies' },",
    "            { label: 'Bundled', key: 'notif_bundled', meta: 'batched alerts' },",
    "            { label: 'Escalations', key: 'notif_escalations', meta: 'second pings' },",
    "            { label: 'Muted', key: 'notif_muted', meta: 'quiet-hour suppressions' },",
    "        ],",
    "        actions: [",
    "            { id: 'ack_critical', label: 'Acknowledge Critical', meta: 'Mark critical queue reviewed.' },",
    "            { id: 'snooze_all_30', label: 'Snooze 30m', meta: 'Pause non-critical notifications.' },",
    "            { id: 'open_personalities', label: 'Robot Personalities', meta: 'Tune category robot behavior.' },",
    "            { id: 'open_history', label: 'Open History', meta: 'Inspect fired alerts and reasons.' },",
    "        ],",
    "    },",
    "    automations: {",
    "        title: 'Automations',",
    "        subtitle: 'Thomas orchestration board for triggers, logic, actions, and approvals.',",
    "        pill: 'Flows',",
    "        kpis: [",
    "            { label: 'Active Flows', key: 'flow_active', meta: 'enabled workflows' },",
    "            { label: 'Failing Runs', key: 'flow_failures', meta: 'needs debug' },",
    "            { label: 'Approvals', key: 'flow_approvals', meta: 'manual gates' },",
    "            { label: 'Webhook Rate', key: 'webhook_rate', meta: 'events per minute' },",
    "        ],",
    "        actions: [",
    "            { id: 'new_flow', label: 'New Flow', meta: 'Create trigger -> logic -> action.' },",
    "            { id: 'import_template', label: 'Import Template', meta: 'Use a prebuilt flow.' },",
    "            { id: 'run_smoke', label: 'Run Smoke Test', meta: 'Validate flow execution path.' },",
    "            { id: 'rollback', label: 'Rollback', meta: 'Return to prior flow version.' },",
    "        ],",
    "    },",
    "    agents: {",
    "        title: 'Agents',",
    "        subtitle: 'Specialized agent team, permissions, and boundaries.',",
    "        pill: 'Crew',",
    "        kpis: [",
    "            { label: 'Active Agents', key: 'agent_active', meta: 'currently running' },",
    "            { label: 'Delegated', key: 'agent_delegated', meta: 'assigned tasks' },",
    "            { label: 'Approval Only', key: 'agent_approval_only', meta: 'cannot act directly' },",
    "            { label: 'Escalations', key: 'agent_escalations', meta: 'asked for review' },",
    "        ],",
    "        actions: [",
    "            { id: 'create_agent', label: 'Create Agent', meta: 'Define role and goals.' },",
    "            { id: 'assign_sources', label: 'Assign Sources', meta: 'Attach inboxes/docs/feeds.' },",
    "            { id: 'set_approval_rule', label: 'Set Approval Rule', meta: 'Require human approval gates.' },",
    "            { id: 'tune_behavior', label: 'Tune Behavior', meta: 'Adjust tone and escalation style.' },",
    "        ],",
    "    },",
    "    studio: {",
    "        title: 'Asset Studio',",
    "        subtitle: 'Thomas-managed asset jobs, tool connectors, and output review.',",
    "        pill: 'Asset Ops',",
    "        kpis: [",
    "            { label: 'Render Queue', key: 'render_queue', meta: 'queued jobs' },",
    "            { label: 'Exports Today', key: 'exports_today', meta: 'completed outputs' },",
    "            { label: 'Pipelines', key: 'brand_kits', meta: 'active presets' },",
    "            { label: 'Library', key: 'assets_total', meta: 'managed assets' },",
    "        ],",
    "        actions: [",
    "            { id: 'ingest_assets', label: 'Ingest Assets', meta: 'Import and classify media in the library.' },",
    "            { id: 'configure_audio_chain', label: 'Audio Chain', meta: 'Prepare denoise, normalize, and loudness passes.' },",
    "            { id: 'generate_concepts', label: 'Generate Concepts', meta: 'Produce visual concepts from local tools.' },",
    "            { id: 'queue_render', label: 'Queue Master Export', meta: 'Send timeline to production presets.' },",
    "        ],",
    "    },",
    "    dev_studio: {",
    "        title: 'Dev Studio',",
    "        subtitle: 'Thomas-run engineering tasks, CI checks, and deploy controls.',",
    "        pill: 'Build',",
    "        kpis: [",
    "            { label: 'Open PRs', key: 'dev_pr_open', meta: 'awaiting review' },",
    "            { label: 'Failing Tests', key: 'dev_failures', meta: 'CI failures' },",
    "            { label: 'Deploys Today', key: 'deploys_today', meta: 'staging + prod' },",
    "            { label: 'Hotfixes', key: 'hotfixes_open', meta: 'urgent patches' },",
    "        ],",
    "        actions: [",
    "            { id: 'triage_issues', label: 'Triage Issues', meta: 'Sort by severity and owner.' },",
    "            { id: 'ask_thomas_implement', label: 'Ask {{agent}} to Implement', meta: 'Launch coding run.' },",
    "            { id: 'run_tests', label: 'Run Tests', meta: 'Execute smoke/regression checks.' },",
    "            { id: 'deploy_staging', label: 'Deploy Staging', meta: 'Promote current candidate.' },",
    "        ],",
    "    },",
    "    app_builder: {",
    "        title: 'App Builder',",
    "        subtitle: 'Describe apps and let Thomas generate, wire, and publish them.',",
    "        pill: 'Builder',",
    "        kpis: [",
    "            { label: 'Published Apps', key: 'apps_published', meta: 'live tools' },",
    "            { label: 'Draft Apps', key: 'apps_draft', meta: 'in progress' },",
    "            { label: 'Connectors', key: 'connectors_total', meta: 'data links' },",
    "            { label: 'Roles', key: 'roles_total', meta: 'permission groups' },",
    "        ],",
    "        actions: [",
    "            { id: 'new_app', label: 'New App', meta: 'Start blank or template app.' },",
    "            { id: 'add_connector', label: 'Add Connector', meta: 'Link API, DB, or sheet.' },",
    "            { id: 'preview', label: 'Preview Runtime', meta: 'Open test runtime environment.' },",
    "            { id: 'publish', label: 'Publish', meta: 'Release app to selected users.' },",
    "        ],",
    "    },",
    "    game_studio: {",
    "        title: 'Game Studio',",
    "        subtitle: 'Thomas-managed game pipelines, builds, and playtest operations.',",
    "        pill: 'Play',",
    "        kpis: [",
    "            { label: 'Projects', key: 'game_projects', meta: 'active game projects' },",
    "            { label: 'Playtests', key: 'game_playtests', meta: 'sessions this week' },",
    "            { label: 'Open Bugs', key: 'game_bugs', meta: 'triage backlog' },",
    "            { label: 'Gen Jobs', key: 'game_gen_jobs', meta: 'content generation' },",
    "        ],",
    "        actions: [",
    "            { id: 'launch_engine', label: 'Launch Engine', meta: 'Open active game project.' },",
    "            { id: 'run_build', label: 'Run Build', meta: 'Compile/package branch.' },",
    "            { id: 'capture_playtest', label: 'Capture Playtest', meta: 'Record and annotate session.' },",
    "            { id: 'generate_content', label: 'Generate Content', meta: 'Create quests/dialogue/items.' },",
    "        ],",
    "    },",
    "    lab_3d: {",
    "        title: '3D Lab',",
    "        subtitle: 'Thomas-managed modeling and fabrication pipelines with operator oversight.',",
    "        pill: 'Fabrication',",
    "        kpis: [",
    "            { label: 'Print Queue', key: 'print_queue', meta: 'jobs waiting' },",
    "            { label: 'Revisions', key: 'model_revisions', meta: 'design iterations' },",
    "            { label: 'Materials', key: 'materials_total', meta: 'loaded profiles' },",
    "            { label: 'Uptime', key: 'printer_uptime', meta: '7-day health' },",
    "        ],",
    "        actions: [",
    "            { id: 'import_stl', label: 'Import STL/OBJ', meta: 'Bring model into pipeline.' },",
    "            { id: 'run_cleanup', label: 'Mesh Cleanup', meta: 'Repair manifold/normals.' },",
    "            { id: 'slice_print', label: 'Slice Print', meta: 'Generate printer profile output.' },",
    "            { id: 'start_print', label: 'Start Print Queue', meta: 'Dispatch queued print jobs.' },",
    "        ],",
    "    },",
    "    research_lab: {",
    "        title: 'Research Lab',",
    "        subtitle: 'Thomas-run research operations with citations and tracked findings.',",
    "        pill: 'Citations',",
    "        kpis: [",
    "            { label: 'Open Briefs', key: 'research_briefs', meta: 'active deep dives' },",
    "            { label: 'Citations', key: 'research_citations', meta: 'saved sources' },",
    "            { label: 'Competitors', key: 'research_competitors', meta: 'watchlist set' },",
    "            { label: 'Indexed Docs', key: 'research_docs', meta: 'searchable corpus' },",
    "        ],",
    "        actions: [",
    "            { id: 'deep_research', label: 'Start Deep Research', meta: 'Run source-backed research flow.' },",
    "            { id: 'ingest_docs', label: 'Ingest Documents', meta: 'Parse and index new material.' },",
    "            { id: 'compare_competitors', label: 'Compare Competitors', meta: 'Produce side-by-side report.' },",
    "            { id: 'export_brief', label: 'Export Brief', meta: 'Publish answer with receipts.' },",
    "        ],",
    "    },",
    "    people: {",
    "        title: 'People',",
    "        subtitle: 'Relationship context, follow-ups, and commitment tracking.',",
    "        pill: 'CRM',",
    "        kpis: [",
    "            { label: 'Contacts', key: 'people_contacts', meta: 'tracked profiles' },",
    "            { label: 'Follow-ups', key: 'people_followups', meta: 'due reminders' },",
    "            { label: 'At Risk', key: 'people_at_risk', meta: 'stale relationships' },",
    "            { label: 'Commitments', key: 'people_commitments', meta: 'open promises' },",
    "        ],",
    "        actions: [",
    "            { id: 'log_interaction', label: 'Log Interaction', meta: 'Capture notes and commitments.' },",
    "            { id: 'draft_checkin', label: 'Draft Check-in', meta: 'Generate personalized outreach.' },",
    "            { id: 'create_followup', label: 'Create Follow-up', meta: 'Schedule reminder with context.' },",
    "            { id: 'open_contact_context', label: 'Open Contact Context', meta: 'View history and files.' },",
    "        ],",
    "    },",
    "    finance: {",
    "        title: 'Finance',",
    "        subtitle: 'Transactions, anomalies, forecasting, receipts, and approvals.',",
    "        pill: 'Money',",
    "        kpis: [",
    "            { label: 'Monthly Burn', key: 'finance_burn', meta: 'rolling 30 days' },",
    "            { label: 'Subscriptions', key: 'finance_subscriptions', meta: 'active recurring' },",
    "            { label: 'Anomalies', key: 'finance_anomalies', meta: 'spend outliers' },",
    "            { label: 'Approvals', key: 'finance_approvals', meta: 'pending decisions' },",
    "        ],",
    "        actions: [",
    "            { id: 'categorize', label: 'Categorize Expenses', meta: 'Auto-label transactions.' },",
    "            { id: 'create_invoice', label: 'Create Invoice', meta: 'Generate invoice draft.' },",
    "            { id: 'run_forecast', label: 'Run Forecast', meta: 'Project next spend window.' },",
    "            { id: 'request_approval', label: 'Request Approval', meta: 'Route high-risk spend.' },",
    "        ],",
    "    },",
    "    integrations: {",
    "        title: 'Integrations',",
    "        subtitle: 'Connector scopes, tokens, webhooks, and plugin health.',",
    "        pill: 'Connectors',",
    "        kpis: [",
    "            { label: 'Connected', key: 'integrations_connected', meta: 'active links' },",
    "            { label: 'Degraded', key: 'integrations_degraded', meta: 'needs fix' },",
    "            { label: 'Reconnects', key: 'integrations_reconnects', meta: 'pending' },",
    "            { label: 'Webhooks', key: 'webhooks_live', meta: 'live listeners' },",
    "        ],",
    "        actions: [",
    "            { id: 'connect_app', label: 'Connect App', meta: 'Authorize new integration.' },",
    "            { id: 'rotate_key', label: 'Rotate API Key', meta: 'Replace compromised/old key.' },",
    "            { id: 'run_health_check', label: 'Run Health Check', meta: 'Validate connector status.' },",
    "            { id: 'create_webhook', label: 'Create Webhook', meta: 'Register event callback.' },",
    "        ],",
    "    },",
    "    marketplace: {",
    "        title: 'Marketplace',",
    "        subtitle: 'Workflow/agent/template packs and team presets.',",
    "        pill: 'Packs',",
    "        kpis: [",
    "            { label: 'Installed', key: 'market_installed', meta: 'active packs' },",
    "            { label: 'Updates', key: 'market_updates', meta: 'available now' },",
    "            { label: 'Private', key: 'market_private', meta: 'team packs' },",
    "            { label: 'Saves', key: 'market_saves', meta: 'bookmarked templates' },",
    "        ],",
    "        actions: [",
    "            { id: 'browse_templates', label: 'Browse Templates', meta: 'Explore installable packs.' },",
    "            { id: 'publish_pack', label: 'Publish Pack', meta: 'Share a custom template pack.' },",
    "            { id: 'clone_pack', label: 'Clone Pack', meta: 'Copy pack into private workspace.' },",
    "            { id: 'update_all', label: 'Update All', meta: 'Apply all compatible updates.' },",
    "        ],",
    "    },",
    "    vault: {",
    "        title: 'Vault',",
    "        subtitle: 'Secrets, memory boundaries, retention, and backup controls.',",
    "        pill: 'Secure',",
    "        kpis: [",
    "            { label: 'Secrets', key: 'vault_secrets', meta: 'stored credentials' },",
    "            { label: 'Expiring', key: 'vault_expiring', meta: 'rotate soon' },",
    "            { label: 'Sources', key: 'vault_sources', meta: 'knowledge inputs' },",
    "            { label: 'Retention', key: 'vault_retention', meta: 'active policies' },",
    "        ],",
    "        actions: [",
    "            { id: 'add_secret', label: 'Add Secret', meta: 'Store credential with scope.' },",
    "            { id: 'revoke_token', label: 'Revoke Token', meta: 'Immediately disable access.' },",
    "            { id: 'export_backup', label: 'Export Backup', meta: 'Create encrypted data export.' },",
    "            { id: 'run_scan', label: 'Run Compliance Scan', meta: 'Audit access and policy drift.' },",
    "        ],",
    "    },",
    "    timeline: {",
    "        title: 'Timeline',",
    "        subtitle: 'Action receipts, approvals, retries, and rollbacks.',",
    "        pill: 'Audit',",
    "        kpis: [",
    "            { label: 'Events 24h', key: 'timeline_events', meta: 'logged actions' },",
    "            { label: 'Automated', key: 'timeline_automated', meta: 'workflow/agent actions' },",
    "            { label: 'Approvals', key: 'timeline_approvals', meta: 'manual sign-offs' },",
    "            { label: 'Retries', key: 'timeline_retries', meta: 'recovery attempts' },",
    "        ],",
    "        actions: [",
    "            { id: 'filter_errors', label: 'Filter Errors', meta: 'Show failed/retried actions.' },",
    "            { id: 'export_receipts', label: 'Export Receipts', meta: 'Download action timeline.' },",
    "            { id: 'rollback', label: 'Rollback Run', meta: 'Revert selected workflow version.' },",
    "            { id: 'open_diff', label: 'Open Before/After', meta: 'Inspect state transitions.' },",
    "        ],",
    "    },",
    "    infinite: {",
    "        title: 'Infinite',",
    "        subtitle: 'Companion HQ: pairing, handoff, push, and offline capture.',",
    "        pill: 'Companion',",
    "        kpis: [",
    "            { label: 'Devices', key: 'devices_paired', meta: 'paired devices' },",
    "            { label: 'Handoffs', key: 'handoffs_pending', meta: 'waiting handoff' },",
    "            { label: 'Offline Captures', key: 'offline_captures', meta: 'awaiting sync' },",
    "            { label: 'Push Routes', key: 'push_routes', meta: 'configured paths' },",
    "        ],",
    "        actions: [",
    "            { id: 'pair_device', label: 'Pair Device', meta: 'Register trusted companion device.' },",
    "            { id: 'send_handoff', label: 'Send Handoff', meta: 'Continue context on another device.' },",
    "            { id: 'sync_offline', label: 'Sync Offline Captures', meta: 'Upload queued captures.' },",
    "            { id: 'open_voice', label: 'Open Voice Mode', meta: 'Configure voice controls.' },",
    "        ],",
    "    },",
    "});",
    "",
    "const MODULE_MODE_SURFACES = Object.freeze({",
    "    dashboard: { layout: 'hub', sections: ['Now', 'Timeline', 'Robot Feed', 'Projects'] },",
    "    operations: { layout: 'ops', sections: ['Overview', 'Customers', 'Inventory', 'Disputes'] },",
    "    inbox: { layout: 'tri_pane', sections: ['Urgent', 'Needs Reply', 'FYI', 'Receipts'] },",
    "    notifications: { layout: 'board', sections: ['Rules', 'Channels', 'Robots', 'History'] },",
    "    automations: { layout: 'canvas', sections: ['Triggers', 'Logic', 'Actions', 'Run Logs'] },",
    "    agents: { layout: 'crew', sections: ['Roster', 'Assignments', 'Permissions', 'Memory'] },",
    "    studio: { layout: 'editor_media', sections: ['Library', 'Creation', 'Audio', 'Delivery'] },",
    "    dev_studio: { layout: 'editor_code', sections: ['Repo', 'Issues', 'PRs', 'Builds'] },",
    "    app_builder: { layout: 'canvas', sections: ['UI', 'Data', 'Logic', 'Publish'] },",
    "    game_studio: { layout: 'editor_game', sections: ['Projects', 'Assets', 'Builds', 'Playtests'] },",
    "    lab_3d: { layout: 'editor_3d', sections: ['Models', 'Materials', 'Repairs', 'Print Queue'] },",
    "    research_lab: { layout: 'research', sections: ['Collections', 'Sources', 'Notes', 'Citations'] },",
    "    people: { layout: 'tri_pane', sections: ['Segments', 'Timeline', 'Commitments', 'Follow-ups'] },",
    "    finance: { layout: 'tri_pane', sections: ['Accounts', 'Transactions', 'Approvals', 'Forecast'] },",
    "    integrations: { layout: 'tri_pane', sections: ['Installed', 'Available', 'Permissions', 'Logs'] },",
    "    marketplace: { layout: 'catalog', sections: ['Featured', 'Templates', 'Agents', 'Apps'] },",
    "    vault: { layout: 'admin', sections: ['Secrets', 'Permissions', 'Memory', 'Retention'] },",
    "    timeline: { layout: 'audit', sections: ['Events', 'Approvals', 'Retries', 'Rollbacks'] },",
    "    infinite: { layout: 'device', sections: ['Devices', 'Routing', 'Capture', 'Offline'] },",
    "});",
    "",
    "const MODULE_SECTION_ICONS = Object.freeze({",
    "    now: 'ph-lightning',",
    "    timeline: 'ph-timeline',",
    "    robot_feed: 'ph-robot',",
    "    projects: 'ph-kanban',",
    "    overview: 'ph-gauge',",
    "    customers: 'ph-users-three',",
    "    inventory: 'ph-package',",
    "    disputes: 'ph-scales',",
    "    urgent: 'ph-warning-circle',",
    "    needs_reply: 'ph-chat-centered-text',",
    "    fyi: 'ph-info',",
    "    receipts: 'ph-receipt',",
    "    rules: 'ph-sliders',",
    "    channels: 'ph-broadcast',",
    "    robots: 'ph-robot',",
    "    history: 'ph-clock-counter-clockwise',",
    "    triggers: 'ph-bell-ringing',",
    "    logic: 'ph-git-branch',",
    "    actions: 'ph-play-circle',",
    "    run_logs: 'ph-file-text',",
    "    roster: 'ph-user-list',",
    "    assignments: 'ph-check-square',",
    "    permissions: 'ph-shield-check',",
    "    memory: 'ph-brain',",
    "    video: 'ph-film-strip',",
    "    audio: 'ph-speaker-high',",
    "    design: 'ph-pencil-ruler',",
    "    render_queue: 'ph-hourglass',",
    "    repo: 'ph-folder-simple',",
    "    issues: 'ph-bug',",
    "    prs: 'ph-git-pull-request',",
    "    builds: 'ph-hammer',",
    "    ui: 'ph-app-window',",
    "    data: 'ph-database',",
    "    publish: 'ph-paper-plane-tilt',",
    "    assets: 'ph-image-square',",
    "    playtests: 'ph-game-controller',",
    "    models: 'ph-cube',",
    "    materials: 'ph-squares-four',",
    "    repairs: 'ph-wrench',",
    "    print_queue: 'ph-printer',",
    "    collections: 'ph-stack',",
    "    sources: 'ph-book-open',",
    "    notes: 'ph-note',",
    "    citations: 'ph-quotes',",
    "    segments: 'ph-funnel',",
    "    commitments: 'ph-handshake',",
    "    follow_ups: 'ph-arrow-bend-up-right',",
    "    accounts: 'ph-wallet',",
    "    transactions: 'ph-arrows-left-right',",
    "    approvals: 'ph-stamp',",
    "    forecast: 'ph-chart-line-up',",
    "    installed: 'ph-plugs-connected',",
    "    available: 'ph-plug',",
    "    logs: 'ph-file-search',",
    "    featured: 'ph-star',",
    "    templates: 'ph-copy',",
    "    agents: 'ph-robot',",
    "    apps: 'ph-grid-four',",
    "    secrets: 'ph-key',",
    "    retention: 'ph-clock-countdown',",
    "    events: 'ph-lightning',",
    "    retries: 'ph-arrow-clockwise',",
    "    rollbacks: 'ph-arrow-counter-clockwise',",
    "    devices: 'ph-device-mobile-camera',",
    "    routing: 'ph-signpost',",
    "    capture: 'ph-camera',",
    "    offline: 'ph-cloud-slash',",
    "});",
    "",
    "const MODULE_WORKBENCH_MODES = new Set([",
    "    'automations',",
    "    'app_builder',",
    "    'studio',",
    "    'dev_studio',",
    "    'game_studio',",
    "    'lab_3d',",
    "    'research_lab',",
    "]);",
    "",
    "function normalizeNavMode(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    if (mode === 'search' || mode === 'office' || mode === 'mission' || mode === 'content') return mode;",
    "    if (MODULE_NAV_MODE_SET.has(mode)) return mode;",
    "    return 'chat';",
    "}",
    "",
    "function moduleSeed(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    if (MODULE_MODE_SEEDS[mode]) return MODULE_MODE_SEEDS[mode];",
    "    return MODULE_MODE_SEEDS.dashboard;",
    "}",
    "",
    "function moduleModeSurface(modeRaw) {",
    "    const mode = safeString(modeRaw).toLowerCase();",
    "    if (MODULE_MODE_SURFACES[mode]) return MODULE_MODE_SURFACES[mode];",
    "    return MODULE_MODE_SURFACES.dashboard;",
    "}",
    "",
    "function moduleSectionIcon(sectionLabelRaw) {",
    "    const key = safeString(sectionLabelRaw).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');",
    "    if (MODULE_SECTION_ICONS[key]) return MODULE_SECTION_ICONS[key];",
    "    return 'ph-dot-outline';",
    "}",
    "",
    "function moduleEnsureRuntime() {",
    "    if (!moduleWorkspace) return null;",
    "    if (!moduleState) {",
    "        moduleState = {",
    "            controlsBound: false,",
    "            timerId: 0,",
    "            activeMode: 'dashboard',",
    "            lastRenderedMode: '',",
    "            modeEnterTimer: 0,"
].join("\n");
