/* app.js lines 7001-8000 */
export default [
    "    setGeneratingState(true);",
    "    pushDebugEvent('chat', 'Started chat request');",
    "",
    "    let finalPrompt = setupPersonalitySelector.value;",
    "    if (finalPrompt === 'custom') {",
    "        finalPrompt = setupCustomPrompt.value.trim();",
    "    }",
    "",
    "    const modelMessage = composerBuildMessageForModel(text);",
    "    const selectedProfile = setupProviderSelector.value || modelSelector.value;",
    "    const payload = {",
    "        message: modelMessage || text,",
    "        docs: docsToSend,",
    "        images: imagesToSend,",
    "        session_id: sessionId,",
    "        profile: selectedProfile,",
    "        model: selectedProfile,",
    "        model_id: activeModelOverride || undefined,",
    "        mode: activeChatMode || undefined,",
    "        autonomy_level: activeAutonomyLevel,",
    "        token_economy: activeTokenEconomy,",
    "        reasoning_effort: activeReasoningEffort || undefined,",
    "        system_prompt: finalPrompt || undefined,",
    "    };",
    "",
    "    await streamChatResponse(payload, { userContext: suggestionUserContext });",
    "}",
    "",
    "async function handleSend() {",
    "    composerCloseActionsMenu();",
    "    const text = composerTextarea.value.trim();",
    "    if (!text && pendingDocs.length === 0 && pendingImages.length === 0) return;",
    "    composerInputLockUntil = Date.now() + 1600;",
    "",
    "    if (isOnboardingSlashCommand(text) && pendingDocs.length === 0 && pendingImages.length === 0) {",
    "        composerTextarea.value = '';",
    "        composerTextarea.dispatchEvent(new Event('input'));",
    "        ensureChatVisible();",
    "        renderMessage({ role: 'user', content: text });",
    "        renderMessage({ role: 'assistant', content: 'Opening Easy Setup. We will verify your connection before setup continues.' });",
    "        openEasySetup({ source: 'slash', force: true });",
    "        return;",
    "    }",
    "",
    "    if (!isOnboardingComplete()) {",
    "        if (easySetupState.interviewStarted) {",
    "            const docsToSend = [...pendingDocs];",
    "            const imagesToSend = [...pendingImages];",
    "            composerTextarea.value = '';",
    "            composerTextarea.dispatchEvent(new Event('input'));",
    "            pendingDocs = [];",
    "            pendingImages = [];",
    "            renderAttachmentsPreview();",
    "            ensureChatVisible();",
    "",
    "            let uiText = text;",
    "            if (docsToSend.length > 0) uiText += `\\n\\n*(Attached ${docsToSend.length} document(s))*`;",
    "            if (imagesToSend.length > 0) uiText += `\\n\\n*(Attached ${imagesToSend.length} image(s))*`;",
    "            if (safeString(uiText)) {",
    "                renderMessage({ role: 'user', content: uiText });",
    "            }",
    "",
    "            await handleOnboardingChatInput(text, {",
    "                docsCount: docsToSend.length,",
    "                imagesCount: imagesToSend.length,",
    "            });",
    "            return;",
    "        }",
    "",
    "        composerTextarea.value = '';",
    "        composerTextarea.dispatchEvent(new Event('input'));",
    "        pendingDocs = [];",
    "        pendingImages = [];",
    "        renderAttachmentsPreview();",
    "        ensureChatVisible();",
    "        if (safeString(text)) {",
    "            renderMessage({ role: 'user', content: text });",
    "        }",
    "        if (isSecurityTrustConcern(text)) {",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: `${buildSetupSafetyMessage()}\\n\\nFinish Easy Setup first, then I can run normal chat tasks.`,",
    "            });",
    "            showSetupSafetySuggestions();",
    "        } else {",
    "            renderMessage({",
    "                role: 'assistant',",
    "                content: withAgentName('Finish Easy Setup first. {{agent}} requires setup before chat can run.'),",
    "            });",
    "        }",
    "        openEasySetup({ source: 'mandatory', force: false, restart: false });",
    "        return;",
    "    }",
    "",
    "    const sendJob = buildSendJobFromComposer(text);",
    "    if (!sendJob) return;",
    "    if (isGenerating) {",
    "        pendingSendQueue.push(sendJob);",
    "        notifyUser(`Queued message (${pendingSendQueue.length} waiting).`, {",
    "            tone: 'info',",
    "            durationMs: 1800,",
    "            debugKind: 'chat',",
    "        });",
    "        composerSyncSendButtonState();",
    "        return;",
    "    }",
    "",
    "    await runChatSendJob(sendJob);",
    "}",
    "",
    "/**",
    " * Stream an assistant response from the /api/chat endpoint.",
    " *",
    " * Extracted from handleSend() so that edit-message, regenerate, and retry",
    " * flows can reuse the same streaming + rendering logic without duplication.",
    " *",
    " * @param {Object} payload - The chat API payload (message, session_id, profile, etc.)",
    " * @param {Object} opts",
    " * @param {string} [opts.userContext] - User context string for follow-up suggestions",
    " * @param {string} [opts.existingBubbleId] - Reuse an existing assistant bubble instead of creating one",
    " */",
    "async function streamChatResponse(payload, { userContext = '', existingBubbleId = '' } = {}) {",
    "    try {",
    "        const landedRobotExit = _portalOutLandedRobot();",
    "",
    "        // Wire AbortController for stop generation",
    "        currentAbortController = new AbortController();",
    "        const res = await fetch('/api/chat', {",
    "            method: 'POST',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify(payload),",
    "            signal: currentAbortController.signal,",
    "        });",
    "",
    "        if (!res.ok) {",
    "            const errText = await res.text();",
    "            throw new Error(`API Error ${res.status}: ${errText}`);",
    "        }",
    "        void refreshTaskContinuity({",
    "            sessionOverride: safeString(payload?.session_id) || sessionId,",
    "        });",
    "",
    "        const bubbleId = existingBubbleId || ('msg-' + Date.now());",
    "",
    "        // Render an empty assistant bubble with typing indicator (or reuse existing)",
    "        if (!existingBubbleId) {",
    "            renderMessage({ role: 'assistant', content: '', id: bubbleId });",
    "        }",
    "        const bubbleRow = document.getElementById(bubbleId);",
    "        const bubbleMsgContent = bubbleRow ? bubbleRow.querySelector('.message-content') : null;",
    "        if (bubbleMsgContent) {",
    "            bubbleMsgContent.innerHTML = '';",
    "        }",
    "",
    "        const reader = res.body.getReader();",
    "        const decoder = new TextDecoder();",
    "        let buffer = '';",
    "        let fullText = '';",
    "        let hasRenderableText = false;",
    "        let streamDone = false;",
    "        let robotSayingInterval = null;",
    "        let robotTimerInterval = null;",
    "        let robotAnimInterval = null;",
    "        let robotStartTime = Date.now();",
    "        let currentRobotCategory = 'thinking';",
    "        let thinkingText = '';  // accumulates real thinking/reasoning content from stream",
    "        let robotLandedForThisResponse = false;",
    "        let robotStatusQueued = false;",
    "        let robotStatusCanStartAt = Date.now();",
    "        landedRobotExit.finally(() => {",
    "            robotStatusCanStartAt = Date.now() + 90;",
    "            if (!robotStatusQueued) return;",
    "            const delay = Math.max(0, robotStatusCanStartAt - Date.now());",
    "            setTimeout(() => {",
    "                if (!hasRenderableText) _startRobotStatus();",
    "            }, delay);",
    "        });",
    "",
    "        function _startRobotStatus() {",
    "            if (robotSayingInterval || !bubbleMsgContent) return;",
    "            const waitMs = Math.max(0, robotStatusCanStartAt - Date.now());",
    "            if (waitMs > 0) {",
    "                robotStatusQueued = true;",
    "                setTimeout(() => {",
    "                    robotStatusQueued = false;",
    "                    if (!hasRenderableText) _startRobotStatus();",
    "                }, waitMs);",
    "                return;",
    "            }",
    "            robotStatusQueued = false;",
    "            currentRobotCategory = 'thinking';",
    "            robotStartTime = Date.now();",
    "            bubbleMsgContent.innerHTML = '';",
    "            bubbleMsgContent.appendChild(_createRobotStatus('thinking'));",
    "",
    "            // Rotate sayings every 2.5s",
    "            robotSayingInterval = setInterval(() => {",
    "                const sayingEl = bubbleMsgContent.querySelector('.chat-robot-saying');",
    "                if (sayingEl) {",
    "                    sayingEl.classList.add('saying-fade');",
    "                    setTimeout(() => {",
    "                        sayingEl.textContent = pickChatSaying(currentRobotCategory);",
    "                        sayingEl.classList.remove('saying-fade');",
    "                    }, 200);",
    "                }",
    "            }, 2500);",
    "",
    "            // Update elapsed timer every 100ms",
    "            robotTimerInterval = setInterval(() => {",
    "                const timerEl = bubbleMsgContent.querySelector('.chat-robot-timer');",
    "                if (timerEl) {",
    "                    timerEl.textContent = ((Date.now() - robotStartTime) / 1000).toFixed(1) + 's';",
    "                }",
    "            }, 100);",
    "",
    "            // Swap animation every 8s — use rAF for clean transition",
    "            robotAnimInterval = setInterval(() => {",
    "                const agentEl = bubbleMsgContent.querySelector('.chat-robot-agent');",
    "                if (agentEl) {",
    "                    const newAnim = _pickRobotAnimation();",
    "                    // Remove old, pause for one frame, then apply new",
    "                    CHAT_ROBOT_ANIMATIONS.forEach(a => agentEl.classList.remove('chat-robot-anim-' + a));",
    "                    agentEl.style.animation = 'none';",
    "                    requestAnimationFrame(() => {",
    "                        agentEl.style.animation = '';",
    "                        agentEl.classList.add('chat-robot-anim-' + newAnim);",
    "                    });",
    "                }",
    "            }, 8000);",
    "",
    "            // No more task-ledger polling — thinking text arrives via NDJSON stream events",
    "        }",
    "        _startRobotStatus();",
    "",
    "        function _setRobotSaying(text) {",
    "            const sayingEl = bubbleMsgContent?.querySelector('.chat-robot-saying');",
    "            if (sayingEl) {",
    "                sayingEl.classList.add('saying-fade');",
    "                setTimeout(() => {",
    "                    sayingEl.textContent = text;",
    "                    sayingEl.classList.remove('saying-fade');",
    "                }, 200);",
    "            }",
    "        }",
    "",
    "        function _clearRobotStatus() {",
    "            if (robotSayingInterval) { clearInterval(robotSayingInterval); robotSayingInterval = null; }",
    "            if (robotTimerInterval) { clearInterval(robotTimerInterval); robotTimerInterval = null; }",
    "            if (robotAnimInterval) { clearInterval(robotAnimInterval); robotAnimInterval = null; }",
    "            const robotEl = bubbleMsgContent?.querySelector('.chat-robot-status');",
    "            if (robotEl) robotEl.remove();",
    "        }",
    "",
    "        function _robotExitRun() {",
    "            // Stop all intervals",
    "            if (robotSayingInterval) { clearInterval(robotSayingInterval); robotSayingInterval = null; }",
    "            if (robotTimerInterval) { clearInterval(robotTimerInterval); robotTimerInterval = null; }",
    "            if (robotAnimInterval) { clearInterval(robotAnimInterval); robotAnimInterval = null; }",
    "",
    "            // Capture elapsed time, accumulated thinking text, and tool cards for the summary",
    "            const elapsedMs = Date.now() - robotStartTime;",
    "            const capturedThinkingText = thinkingText;",
    "            const capturedToolCards = _liveToolCards.slice();",
    "            let scheduledLandingFromClone = false;",
    "",
    "            // Clone the robot agent and put it on the message-row for the exit animation",
    "            const agentEl = bubbleMsgContent?.querySelector('.chat-robot-agent');",
    "            if (agentEl && bubbleRow) {",
    "                const clone = agentEl.cloneNode(true);",
    "                // Strip all activity + entrance animation classes + inline styles",
    "                CHAT_ROBOT_ANIMATIONS.forEach(a => clone.classList.remove('chat-robot-anim-' + a));",
    "                clone.classList.remove('chat-robot-enter');",
    "                clone.style.filter = 'none';",
    "                clone.style.animation = '';",
    "                clone.removeAttribute('data-idle-anim');",
    "                // Position the clone absolutely on the message-row",
    "                clone.style.position = 'absolute';",
    "                clone.style.top = '6px';",
    "                clone.style.left = '38px';",
    "                clone.style.zIndex = '10';",
    "                clone.classList.add('robot-exit-run');",
    "                bubbleRow.appendChild(clone);",
    "                // Two chained animations (jump + fall) — remove after the fall ends",
    "                let exitAnimCount = 0;",
    "                let landedFromClone = false;",
    "                const landClone = () => {",
    "                    if (landedFromClone) return;",
    "                    landedFromClone = true;",
    "                    _landRobotAtComposerDock(clone);",
    "                    robotLandedForThisResponse = true;",
    "                };",
    "                clone.addEventListener('animationend', (e) => {",
    "                    // Ignore leg scurry animationend events",
    "                    if (e.target !== clone) return;",
    "                    exitAnimCount++;",
    "                    if (exitAnimCount >= 2) landClone();",
    "                });",
    "                setTimeout(() => landClone(), 2000);",
    "                scheduledLandingFromClone = true;",
    "            }",
    "            if (!scheduledLandingFromClone) {",
    "                setTimeout(() => {",
    "                    _landRobotAtComposerDock();",
    "                    robotLandedForThisResponse = true;",
    "                }, CHAT_ROBOT_EXIT_FALL_MS);",
    "            }",
    "            // Remove the status element so text can flow in",
    "            const robotEl = bubbleMsgContent?.querySelector('.chat-robot-status');",
    "            if (robotEl) robotEl.remove();",
    "",
    "            // Insert \"Thought for X.Xs\" collapsed summary at top of message content",
    "            if (bubbleMsgContent && elapsedMs > 500) {",
    "                const summaryEl = _createThinkingSummary(elapsedMs, capturedThinkingText, capturedToolCards);",
    "                if (summaryEl) {",
    "                    bubbleMsgContent.insertBefore(summaryEl, bubbleMsgContent.firstChild);",
    "                }",
    "            }",
    "        }",
    "",
    "        // ── rAF-batched streaming render ──",
    "        let _rafScheduled = false;",
    "        function _scheduleStreamRender() {",
    "            if (_rafScheduled) return;",
    "            _rafScheduled = true;",
    "            requestAnimationFrame(() => {",
    "                _rafScheduled = false;",
    "                updateMessage(bubbleId, fullText);",
    "            });",
    "        }",
    "",
    "        // Collected tool calls for this response",
    "        const collectedToolCalls = [];",
    "        // Live tool card instances for rendering",
    "        const _liveToolCards = [];",
    "        // Container for tool cards — lives inside the thinking dropdown",
    "        function _getToolCardsContainer() {",
    "            // Look for the thinking-tool-cards container inside the robot status",
    "            const existing = bubbleMsgContent?.querySelector('.thinking-tool-cards');",
    "            if (existing) return existing;",
    "            // Fallback: create one in the thinking details if present",
    "            const detailsEl = bubbleMsgContent?.querySelector('.chat-robot-thinking-details');",
    "            if (detailsEl) {",
    "                const container = document.createElement('div');",
    "                container.className = 'thinking-tool-cards';",
    "                detailsEl.appendChild(container);",
    "                return container;",
    "            }",
    "            // Last resort: append to message content (shouldn't happen normally)",
    "            const container = document.createElement('div');",
    "            container.className = 'thinking-tool-cards';",
    "            if (bubbleMsgContent) bubbleMsgContent.appendChild(container);",
    "            return container;",
    "        }",
    "",
    "        try {",
    "            while (true) {",
    "                const { done, value } = await reader.read();",
    "                if (done) break;",
    "",
    "                buffer += decoder.decode(value, { stream: true });",
    "                const lines = buffer.split('\\n');",
    "                buffer = lines.pop();",
    "",
    "                for (const line of lines) {",
    "                    if (!line.trim()) continue;",
    "                    try {",
    "                        const evt = JSON.parse(line);",
    "                        if (evt.type === 'timing') {",
    "                            console.log(`[timing] ${evt.label}: ${evt.elapsed_ms}ms`);",
    "                        } else if (evt.type === 'ui_state_patch') {",
    "                            applyUiStatePatchEvent(evt);",
    "                        } else if (evt.type === 'model_switch') {",
    "                            applyProfileSelection(evt.profile);",
    "                        } else if (evt.type === 'text' && evt.text) {",
    "                            if (!hasRenderableText) {",
    "                                _robotExitRun();",
    "                                if (bubbleMsgContent) bubbleMsgContent.classList.add('streaming-active');",
    "                            }",
    "                            fullText += evt.text;",
    "                            hasRenderableText = true;",
    "                            _scheduleStreamRender();",
    "                        } else if (evt.type === 'error') {",
    "                            if (!hasRenderableText) _clearRobotStatus();",
    "                            const errorText = safeString(evt.error) || 'Unknown stream error.';",
    "                            fullText += `\\n\\n**Error:** ${errorText}`;",
    "                            hasRenderableText = true;",
    "                            updateMessage(bubbleId, fullText);",
    "                        } else if (evt.type === 'tool_start') {",
    "                            collectedToolCalls.push({ name: safeString(evt.name), args: null, result: null });",
    "                            // Render a collapsible tool card",
    "                            const tc = createToolCallCard(safeString(evt.name));",
    "                            _liveToolCards.push(tc);",
    "                            _getToolCardsContainer().appendChild(tc.card);",
    "                            // Show descriptive tool saying immediately",
    "                            const toolDesc = describeToolName(safeString(evt.name));",
    "                            if (!hasRenderableText) {",
    "                                if (!robotSayingInterval) _startRobotStatus();",
    "                                currentRobotCategory = 'working';",
    "                                if (toolDesc) _setRobotSaying(toolDesc);",
    "                            }",
    "                        } else if (evt.type === 'tool_args' && collectedToolCalls.length > 0) {",
    "                            const last = collectedToolCalls[collectedToolCalls.length - 1];",
    "                            last.args = evt.args || evt.data || null;",
    "                            // Update the latest tool card with args",
    "                            if (_liveToolCards.length > 0) {",
    "                                _liveToolCards[_liveToolCards.length - 1].setArgs(last.args);",
    "                            }",
    "                        } else if (evt.type === 'tool_result') {",
    "                            if (collectedToolCalls.length > 0) {",
    "                                const last = collectedToolCalls[collectedToolCalls.length - 1];",
    "                                last.result = evt.result || evt.data || safeString(evt.text) || null;",
    "                            }",
    "                            // Update the latest tool card with result",
    "                            if (_liveToolCards.length > 0) {",
    "                                const lastCard = _liveToolCards[_liveToolCards.length - 1];",
    "                                const resultData = evt.result || evt.data || safeString(evt.text) || '';",
    "                                lastCard.setResult(resultData);",
    "                            }",
    "                            // Tool finished — back to generic working sayings",
    "                            currentRobotCategory = 'working';",
    "                        } else if (evt.type === 'thinking') {",
    "                            // Accumulate real thinking/reasoning text (from LLM or synthetic)",
    "                            const chunk = safeString(evt.text);",
    "                            if (chunk) {",
    "                                thinkingText += chunk;",
    "                                // Update the live thinking display inside the robot status",
    "                                const detailsEl = bubbleMsgContent?.querySelector('.chat-robot-thinking-details');",
    "                                if (detailsEl) _updateThinkingDisplay(detailsEl, thinkingText);",
    "                            }",
    "                        } else if (evt.type === 'route') {",
    "                            if (!hasRenderableText) _startRobotStatus();",
    "                        } else if (evt.type === 'iteration') {",
    "                            if (!hasRenderableText && !robotSayingInterval) _startRobotStatus();",
    "                        } else if (evt.type === 'done') {",
    "                            streamDone = true;",
    "                        }",
    "                    } catch (e) {",
    "                        console.warn(\"Failed to parse stream line:\", line);",
    "                    }",
    "                }",
    "            }",
    "        } catch (abortErr) {",
    "            if (abortErr.name === 'AbortError') {",
    "                _clearRobotStatus();",
    "                fullText += '\\n\\n*\\\\[Generation stopped\\\\]*';",
    "                updateMessage(bubbleId, fullText, false);",
    "            } else {",
    "                throw abortErr;",
    "            }",
    "        }",
    "",
    "        // Clean up robot status if still running",
    "        _clearRobotStatus();",
    "        currentAbortController = null;",
    "",
    "        if (buffer.trim()) {",
    "            try {",
    "                const evt = JSON.parse(buffer);",
    "                if (evt.type === 'ui_state_patch') {",
    "                    applyUiStatePatchEvent(evt);",
    "                } else if (evt.type === 'model_switch') {",
    "                    applyProfileSelection(evt.profile);",
    "                } else if (evt.type === 'text' && evt.text) {",
    "                    if (!hasRenderableText) _robotExitRun();",
    "                    fullText += evt.text;",
    "                    hasRenderableText = true;",
    "                } else if (evt.type === 'done') {",
    "                    streamDone = true;",
    "                }",
    "            } catch (ignore) { }",
    "        }",
    "",
    "        // Final render — remove streaming cursor",
    "        if (bubbleMsgContent) bubbleMsgContent.classList.remove('streaming-active');",
    "",
    "        if (hasRenderableText) {",
    "            updateMessage(bubbleId, fullText, false);",
    "            if (!robotLandedForThisResponse) _landRobotAtComposerDock();",
    "        }",
    "",
    "        let assistantFinalText = fullText;",
    "        if (!fullText.trim()) {",
    "            assistantFinalText = streamDone",
    "                ? '_Finished with no text response._'",
    "                : '_No text response yet. Still waiting on model output..._';",
    "            updateMessage(bubbleId, assistantFinalText, false);",
    "            showStarterSuggestionRail({ force: true });",
    "            pushDebugEvent('chat', 'Completed chat request with empty response');",
    "        } else {",
    "            maybeShowAssistantFollowups({",
    "                assistantText: fullText,",
    "                userText: userContext,",
    "            });",
    "            pushDebugEvent('chat', `Completed chat request (${fullText.length} chars)`);",
    "        }",
    "        chatHistory.push({",
    "            id: bubbleId,",
    "            role: 'assistant',",
    "            content: assistantFinalText,",
    "            createdAt: Date.now(),",
    "            status: 'complete',",
    "            toolCalls: collectedToolCalls,",
    "        });",
    "        syncActiveChatSidebarEntry();",
    "        void persistActiveChat({ quiet: true });",
    "",
    "    } catch (err) {",
    "        if (err.name === 'AbortError') {",
    "            // Already handled in the inner catch",
    "        } else {",
    "            console.error(err);",
    "        }",
    "        currentAbortController = null;",
    "        let errorMsg = err.name === 'AbortError' ? '' : (err.message || '');",
    "        if (!errorMsg) {",
    "            // Abort was handled inline — skip error rendering",
    "        } else if (errorMsg.includes('SyntaxError')) {",
    "            errorMsg = \"Invalid JSON returned from server.\";",
    "        }",
    "        if (errorMsg) {",
    "            const renderedError = `**Error connecting to ${escapeHtml(getAgentName())} backend.**\\n\\n\\`${escapeHtml(errorMsg)}\\``;",
    "            renderMessage({ role: 'assistant', content: renderedError });",
    "            chatHistory.push({",
    "                id: `err-${Date.now()}`,",
    "                role: 'assistant',",
    "                content: renderedError,",
    "                createdAt: Date.now(),",
    "                status: 'complete',",
    "                toolCalls: [],",
    "            });",
    "            syncActiveChatSidebarEntry();",
    "            void persistActiveChat({ quiet: true });",
    "            const trimmedError = safeString(errorMsg).replace(/^API Error \\d+:\\s*/i, '').slice(0, 220);",
    "            notifyUser(trimmedError ? `Chat failed: ${trimmedError}` : 'Chat request failed.', {",
    "                tone: 'error',",
    "                durationMs: 3600,",
    "            });",
    "            pushDebugEvent('error', `Chat request failed: ${errorMsg}`);",
    "            setAssistantSuggestions({",
    "                title: 'Quick recovery',",
    "                context: 'recovery',",
    "                dismissible: true,",
    "                options: [",
    "                    {",
    "                        label: 'Retry the request',",
    "                        kind: 'action',",
    "                        tone: 'primary',",
    "                        send_prompt: 'Retry my previous request and explain what changed if it still fails.',",
    "                    },",
    "                    {",
    "                        label: 'Diagnose backend issue',",
    "                        kind: 'option',",
    "                        send_prompt: 'Diagnose likely backend connectivity issues and give me concrete checks to run now.',",
    "                    },",
    "                    {",
    "                        label: 'Open Easy Setup',",
    "                        kind: 'option',",
    "                        onChoose: async () => {",
    "                            ensureChatVisible();",
    "                            await openEasySetup({ source: 'error_recovery', force: true, restart: false });",
    "                        },",
    "                    },",
    "                ],",
    "            });",
    "        }",
    "    } finally {",
    "        setGeneratingState(false);",
    "        void refreshTaskContinuity({",
    "            sessionOverride: safeString(payload?.session_id) || sessionId,",
    "            force: true,",
    "        });",
    "        void drainQueuedSends();",
    "    }",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Message editing + regeneration",
    "// ---------------------------------------------------------------------------",
    "",
    "/**",
    " * Enter edit mode on a user message row.",
    " * Replaces message content with a textarea + save/cancel buttons.",
    " */",
    "function beginEditMessage(row) {",
    "    if (isGenerating) return;",
    "    if (row.classList.contains('message-editing')) return; // already editing",
    "",
    "    const contentDiv = row.querySelector('.message-content');",
    "    if (!contentDiv) return;",
    "",
    "    // Find this message in chatHistory by row id",
    "    const msgId = row.id;",
    "    const historyEntry = chatHistory.find(m => m.id === msgId);",
    "    const originalText = historyEntry ? historyEntry.content : (contentDiv.innerText || contentDiv.textContent || '');",
    "    // Strip the attachment annotation for editing",
    "    const editText = originalText.replace(/\\n\\n\\*\\(Attached \\d+ (?:document|image)\\(s\\)\\)\\*/g, '').trim();",
    "",
    "    row.classList.add('message-editing');",
    "    row.dataset.originalContent = contentDiv.innerHTML;",
    "    row.dataset.originalText = originalText;",
    "",
    "    const textarea = document.createElement('textarea');",
    "    textarea.className = 'msg-edit-textarea';",
    "    textarea.value = editText;",
    "    textarea.rows = Math.max(2, Math.min(12, editText.split('\\n').length + 1));",
    "",
    "    const btnBar = document.createElement('div');",
    "    btnBar.className = 'msg-edit-actions';",
    "    btnBar.innerHTML = `",
    "        <button class=\"msg-edit-save\" title=\"Save & resend\">Save & Send</button>",
    "        <button class=\"msg-edit-cancel\" title=\"Cancel editing\">Cancel</button>",
    "    `;",
    "",
    "    contentDiv.innerHTML = '';",
    "    contentDiv.appendChild(textarea);",
    "    contentDiv.appendChild(btnBar);",
    "    textarea.focus();",
    "    textarea.setSelectionRange(textarea.value.length, textarea.value.length);",
    "",
    "    // Allow Escape to cancel, Ctrl+Enter to save",
    "    textarea.addEventListener('keydown', (e) => {",
    "        if (e.key === 'Escape') {",
    "            e.preventDefault();",
    "            cancelEditMessage(row);",
    "        } else if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {",
    "            e.preventDefault();",
    "            commitEditMessage(row);",
    "        }",
    "    });",
    "}",
    "",
    "/**",
    " * Cancel editing and restore original content.",
    " */",
    "function cancelEditMessage(row) {",
    "    if (!row.classList.contains('message-editing')) return;",
    "    const contentDiv = row.querySelector('.message-content');",
    "    if (contentDiv && row.dataset.originalContent) {",
    "        contentDiv.innerHTML = row.dataset.originalContent;",
    "        contentDiv.querySelectorAll('pre code').forEach(el => hljs.highlightElement(el));",
    "        addCodeBlockControls(contentDiv);",
    "    }",
    "    row.classList.remove('message-editing');",
    "    delete row.dataset.originalContent;",
    "    delete row.dataset.originalText;",
    "}",
    "",
    "/**",
    " * Commit an edited user message: truncate history after this message,",
    " * remove all subsequent DOM rows, and re-stream with edited text.",
    " */",
    "async function commitEditMessage(row) {",
    "    if (!row.classList.contains('message-editing')) return;",
    "    const contentDiv = row.querySelector('.message-content');",
    "    const textarea = contentDiv ? contentDiv.querySelector('.msg-edit-textarea') : null;",
    "    if (!textarea) return;",
    "",
    "    const newText = textarea.value.trim();",
    "    if (!newText) {",
    "        cancelEditMessage(row);",
    "        return;",
    "    }",
    "",
    "    const msgId = row.id;",
    "",
    "    // 1. Find position in chatHistory",
    "    const histIdx = chatHistory.findIndex(m => m.id === msgId);",
    "",
    "    // 2. Truncate chatHistory after this message",
    "    if (histIdx >= 0) {",
    "        chatHistory.length = histIdx; // remove this message and all after",
    "    }",
    "",
    "    // 3. Remove all DOM rows from this message onward (including this one)",
    "    let sibling = row;",
    "    while (sibling) {",
    "        const next = sibling.nextElementSibling;",
    "        // Don't remove non-message elements (like the landed robot)",
    "        if (sibling.classList.contains('message-row') || sibling.classList.contains('chat-robot-landed')) {",
    "            sibling.remove();",
    "        }",
    "        sibling = next;",
    "    }",
    "",
    "    // 4. Re-render the edited user message",
    "    const userContent = newText;",
    "    renderMessage({ role: 'user', content: userContent, id: msgId });",
    "    chatHistory.push({",
    "        id: msgId,",
    "        role: 'user',",
    "        content: userContent,",
    "        createdAt: Date.now(),",
    "        status: 'complete',",
    "        toolCalls: [],",
    "    });",
    "    syncActiveChatSidebarEntry();",
    "    void persistActiveChat({ quiet: true });",
    "",
    "    // 5. Build payload and stream new response",
    "    setGeneratingState(true);",
    "    pushDebugEvent('chat', 'Edited message — re-streaming response');",
    "",
    "    let finalPrompt = setupPersonalitySelector.value;",
    "    if (finalPrompt === 'custom') {",
    "        finalPrompt = setupCustomPrompt.value.trim();",
    "    }",
    "    const selectedProfile = setupProviderSelector.value || modelSelector.value;",
    "    const payload = {",
    "        message: newText,",
    "        docs: [],",
    "        images: [],",
    "        session_id: sessionId,",
    "        profile: selectedProfile,",
    "        model: selectedProfile,",
    "        model_id: activeModelOverride || undefined,",
    "        mode: activeChatMode || undefined,",
    "        autonomy_level: activeAutonomyLevel,",
    "        token_economy: activeTokenEconomy,",
    "        reasoning_effort: activeReasoningEffort || undefined,",
    "        system_prompt: finalPrompt || undefined,",
    "    };",
    "",
    "    await streamChatResponse(payload, { userContext: newText });",
    "}",
    "",
    "/**",
    " * Regenerate an assistant response: remove it and re-stream from the",
    " * preceding user message.",
    " */",
    "async function regenerateResponse(row) {",
    "    if (isGenerating) return;",
    "",
    "    const msgId = row.id;",
    "    const histIdx = chatHistory.findIndex(m => m.id === msgId);",
    "    if (histIdx < 0) return;",
    "",
    "    // Find the preceding user message",
    "    let userIdx = -1;",
    "    for (let i = histIdx - 1; i >= 0; i--) {",
    "        if (chatHistory[i].role === 'user') {",
    "            userIdx = i;",
    "            break;",
    "        }",
    "    }",
    "    if (userIdx < 0) return; // No user message to regenerate from",
    "",
    "    const userMsg = chatHistory[userIdx];",
    "",
    "    // Truncate everything after (and including) the assistant message",
    "    chatHistory.length = histIdx;",
    "",
    "    // Remove DOM rows from the assistant message onward",
    "    let sibling = row;",
    "    while (sibling) {",
    "        const next = sibling.nextElementSibling;",
    "        if (sibling.classList.contains('message-row') || sibling.classList.contains('chat-robot-landed')) {",
    "            sibling.remove();",
    "        }",
    "        sibling = next;",
    "    }",
    "",
    "    syncActiveChatSidebarEntry();",
    "    void persistActiveChat({ quiet: true });",
    "",
    "    // Build payload and stream new response",
    "    setGeneratingState(true);",
    "    pushDebugEvent('chat', 'Regenerating assistant response');",
    "",
    "    let finalPrompt = setupPersonalitySelector.value;",
    "    if (finalPrompt === 'custom') {",
    "        finalPrompt = setupCustomPrompt.value.trim();",
    "    }",
    "    const selectedProfile = setupProviderSelector.value || modelSelector.value;",
    "    const payload = {",
    "        message: userMsg.content,",
    "        docs: [],",
    "        images: [],",
    "        session_id: sessionId,",
    "        profile: selectedProfile,",
    "        model: selectedProfile,",
    "        model_id: activeModelOverride || undefined,",
    "        mode: activeChatMode || undefined,",
    "        autonomy_level: activeAutonomyLevel,",
    "        token_economy: activeTokenEconomy,",
    "        reasoning_effort: activeReasoningEffort || undefined,",
    "        system_prompt: finalPrompt || undefined,",
    "    };",
    "",
    "    await streamChatResponse(payload, { userContext: userMsg.content });",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Conversation management: export, search, pin",
    "// ---------------------------------------------------------------------------",
    "",
    "/**",
    " * Export the current chat conversation as a downloadable file.",
    " * @param {'markdown'|'json'} [format='markdown']",
    " */",
    "function exportChatConversation(format = 'markdown') {",
    "    if (chatHistory.length === 0) {",
    "        showToast('Nothing to export — conversation is empty.');",
    "        return;",
    "    }",
    "",
    "    let content, filename, mimeType;",
    "    const ts = new Date().toISOString().slice(0, 10);",
    "",
    "    if (format === 'json') {",
    "        content = JSON.stringify(chatHistory, null, 2);",
    "        filename = `thomas-chat-${ts}.json`;",
    "        mimeType = 'application/json';",
    "    } else {",
    "        // Markdown format",
    "        const lines = [`# Thomas Chat Export — ${ts}\\n`];",
    "        for (const msg of chatHistory) {",
    "            const role = msg.role === 'user' ? '**You**' : '**Thomas**';",
    "            lines.push(`### ${role}`);",
    "            lines.push(msg.content || '_(empty)_');",
    "            lines.push('');",
    "        }",
    "        content = lines.join('\\n');",
    "        filename = `thomas-chat-${ts}.md`;",
    "        mimeType = 'text/markdown';",
    "    }",
    "",
    "    const blob = new Blob([content], { type: mimeType });",
    "    const url = URL.createObjectURL(blob);",
    "    const a = document.createElement('a');",
    "    a.href = url;",
    "    a.download = filename;",
    "    document.body.appendChild(a);",
    "    a.click();",
    "    setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);",
    "    showToast(`Exported as ${filename}`);",
    "}",
    "",
    "/**",
    " * In-conversation search: find messages matching a query.",
    " */",
    "let _chatSearchState = { visible: false, query: '', matches: [], current: -1 };",
    "",
    "function toggleChatSearch() {",
    "    const bar = document.getElementById('chatSearchBar');",
    "    if (!bar) return;",
    "    _chatSearchState.visible = !_chatSearchState.visible;",
    "    bar.classList.toggle('visible', _chatSearchState.visible);",
    "    if (_chatSearchState.visible) {",
    "        const input = bar.querySelector('input');",
    "        if (input) input.focus();",
    "    } else {",
    "        _clearSearchHighlights();",
    "    }",
    "}",
    "",
    "function _performChatSearch(query) {",
    "    _clearSearchHighlights();",
    "    _chatSearchState.query = query;",
    "    _chatSearchState.matches = [];",
    "    _chatSearchState.current = -1;",
    "",
    "    if (!query.trim()) {",
    "        _updateSearchCount();",
    "        return;",
    "    }",
    "",
    "    const lowerQ = query.toLowerCase();",
    "    const rows = chatMessagesInner ? chatMessagesInner.querySelectorAll('.message-row') : [];",
    "    rows.forEach(row => {",
    "        const content = row.querySelector('.message-content');",
    "        if (content && (content.textContent || '').toLowerCase().includes(lowerQ)) {",
    "            _chatSearchState.matches.push(row);",
    "        }",
    "    });",
    "",
    "    if (_chatSearchState.matches.length > 0) {",
    "        _chatSearchState.current = 0;",
    "        _highlightSearchMatch();",
    "    }",
    "    _updateSearchCount();",
    "}",
    "",
    "function _navigateSearch(dir) {",
    "    if (_chatSearchState.matches.length === 0) return;",
    "    _chatSearchState.matches[_chatSearchState.current]?.classList.remove('search-highlight');",
    "    _chatSearchState.current = (_chatSearchState.current + dir + _chatSearchState.matches.length) % _chatSearchState.matches.length;",
    "    _highlightSearchMatch();",
    "    _updateSearchCount();",
    "}",
    "",
    "function _highlightSearchMatch() {",
    "    const row = _chatSearchState.matches[_chatSearchState.current];",
    "    if (!row) return;",
    "    row.classList.add('search-highlight');",
    "    row.scrollIntoView({ behavior: 'smooth', block: 'center' });",
    "}",
    "",
    "function _clearSearchHighlights() {",
    "    if (!chatMessagesInner) return;",
    "    chatMessagesInner.querySelectorAll('.search-highlight').forEach(r => r.classList.remove('search-highlight'));",
    "}",
    "",
    "function _updateSearchCount() {",
    "    const countEl = document.querySelector('#chatSearchBar .search-count');",
    "    if (!countEl) return;",
    "    if (_chatSearchState.matches.length === 0) {",
    "        countEl.textContent = _chatSearchState.query ? 'No matches' : '';",
    "    } else {",
    "        countEl.textContent = `${_chatSearchState.current + 1} / ${_chatSearchState.matches.length}`;",
    "    }",
    "}",
    "",
    "/**",
    " * Toggle pin on a message.",
    " */",
    "function togglePinMessage(row) {",
    "    if (!row) return;",
    "    const msgId = row.id;",
    "    const entry = chatHistory.find(m => m.id === msgId);",
    "    const isPinned = row.classList.toggle('pinned');",
    "    if (entry) entry.pinned = isPinned;",
    "    void persistActiveChat({ quiet: true });",
    "    showToast(isPinned ? 'Message pinned' : 'Message unpinned');",
    "}",
    "",
    "function initChatSearch() {",
    "    const searchInput = document.getElementById('chatSearchInput');",
    "    const prevBtn = document.getElementById('chatSearchPrev');",
    "    const nextBtn = document.getElementById('chatSearchNext');",
    "    const closeBtn = document.getElementById('chatSearchClose');",
    "    if (!searchInput) return;",
    "",
    "    let _debounce = null;",
    "    searchInput.addEventListener('input', () => {",
    "        clearTimeout(_debounce);",
    "        _debounce = setTimeout(() => _performChatSearch(searchInput.value), 200);",
    "    });",
    "    searchInput.addEventListener('keydown', (e) => {",
    "        if (e.key === 'Enter') { e.preventDefault(); _navigateSearch(e.shiftKey ? -1 : 1); }",
    "        if (e.key === 'Escape') { e.preventDefault(); toggleChatSearch(); }",
    "    });",
    "    if (prevBtn) prevBtn.addEventListener('click', () => _navigateSearch(-1));",
    "    if (nextBtn) nextBtn.addEventListener('click', () => _navigateSearch(1));",
    "    if (closeBtn) closeBtn.addEventListener('click', () => toggleChatSearch());",
    "}",
    "",
    "function stopGeneration() {",
    "    if (currentAbortController) {",
    "        currentAbortController.abort();",
    "        currentAbortController = null;",
    "    }",
    "    setGeneratingState(false);",
    "}",
    "",
    "function setGeneratingState(generating) {",
    "    isGenerating = generating;",
    "    if (generating) {",
    "        sendBtn.classList.add('stop-state');",
    "        sendBtn.innerHTML = '<i class=\"ph ph-stop\"></i>';",
    "        sendBtn.disabled = false;",
    "        // Hide suggestions while generating — they're distracting",
    "        _stopSuggestionAutoScroll();",
    "        if (assistantSuggestionRail) assistantSuggestionRail.classList.add('hidden');",
    "    } else {",
    "        sendBtn.classList.remove('stop-state');",
    "        sendBtn.innerHTML = '<i class=\"ph ph-arrow-up\"></i>';",
    "        sendBtn.disabled = (composerTextarea.value.trim().length === 0 && pendingDocs.length === 0 && pendingImages.length === 0);",
    "    }",
    "    updateDebugDockSnapshot();",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  CHAT & MESSAGE RENDERING                                               ║",
    "// ║  Attachments, message bubbles, markdown, code blocks, robot alerts      ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function renderAttachmentsPreview() {",
    "    attachmentsPreview.replaceChildren();",
    "    const all = [...pendingDocs.map(d => ({ ...d, type: 'doc' })), ...pendingImages.map(i => ({ ...i, type: 'img' }))];",
    "",
    "    all.forEach((item, index) => {",
    "        const chip = document.createElement('div');",
    "        chip.className = 'attachment-chip';",
    "        const icon = document.createElement('i');",
    "        icon.className = `ph ${item.type === 'img' ? 'ph-image' : 'ph-file-text'}`;",
    "",
    "        const label = document.createElement('span');",
    "        label.textContent = String(item.name || '');",
    "",
    "        const remove = document.createElement('i');",
    "        remove.className = 'ph ph-x remove-btn';",
    "        remove.dataset.index = String(index);",
    "        remove.dataset.type = item.type;",
    "",
    "        chip.appendChild(icon);",
    "        chip.appendChild(label);",
    "        chip.appendChild(remove);",
    "        attachmentsPreview.appendChild(chip);",
    "    });",
    ""
].join("\n");
