/* app.js lines 15001-16000 */
export default [
    "    }",
    "    if (action.startsWith('focus:')) {",
    "        const roomId = safeString(action.split(':')[1]) || 'room-pods';",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            officeRouteAgentToRoom(agent, roomId, {",
    "                intent: 'wander',",
    "                speed: officeRandomRange(3.2, 4.3),",
    "            });",
    "        });",
    "        const roomLabel = officeRoomById(roomId)?.label || roomId;",
    "        officePushChatLine(`System: Focus wave sent to ${roomLabel}.`);",
    "        officeBusEmit('quick_action.run', { ...eventPayload, roomId }, now);",
    "    }",
    "}",
    "",
    "function officeTouchActivePointers() {",
    "    if (!officeState?.touchGesture?.pointerById) return [];",
    "    return [...officeState.touchGesture.pointerById.values()];",
    "}",
    "",
    "function officeTouchGestureDown(event) {",
    "    if (!officeState?.touchGesture) return;",
    "    const gesture = officeState.touchGesture;",
    "    gesture.pointerById.set(event.pointerId, {",
    "        x: event.clientX,",
    "        y: event.clientY,",
    "    });",
    "    const pointers = officeTouchActivePointers();",
    "    if (pointers.length < 2) {",
    "        gesture.active = true;",
    "        gesture.baseDistance = 0;",
    "        gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "        gesture.lastCenterX = event.clientX;",
    "        gesture.lastCenterY = event.clientY;",
    "        return;",
    "    }",
    "    const a = pointers[0];",
    "    const b = pointers[1];",
    "    gesture.active = true;",
    "    gesture.baseDistance = Math.max(0.001, Math.hypot(b.x - a.x, b.y - a.y));",
    "    gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "    gesture.lastCenterX = (a.x + b.x) / 2;",
    "    gesture.lastCenterY = (a.y + b.y) / 2;",
    "}",
    "",
    "function officeTouchGestureMove(event) {",
    "    if (!officeState?.touchGesture) return false;",
    "    const gesture = officeState.touchGesture;",
    "    if (!gesture.pointerById.has(event.pointerId)) return false;",
    "    gesture.pointerById.set(event.pointerId, {",
    "        x: event.clientX,",
    "        y: event.clientY,",
    "    });",
    "    const pointers = officeTouchActivePointers();",
    "    if (pointers.length >= 2) {",
    "        const a = pointers[0];",
    "        const b = pointers[1];",
    "        const centerX = (a.x + b.x) / 2;",
    "        const centerY = (a.y + b.y) / 2;",
    "        const distance = Math.max(0.001, Math.hypot(b.x - a.x, b.y - a.y));",
    "        if (!gesture.active) {",
    "            gesture.active = true;",
    "            gesture.baseDistance = distance;",
    "            gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "            gesture.lastCenterX = centerX;",
    "            gesture.lastCenterY = centerY;",
    "            return true;",
    "        }",
    "        const ratio = distance / Math.max(0.001, gesture.baseDistance || distance);",
    "        const nextZoom = (gesture.baseZoom || officeState.zoomLevel) * ratio;",
    "        officeSetZoom(nextZoom, {",
    "            anchorClientX: centerX,",
    "            anchorClientY: centerY,",
    "        });",
    "        const deltaX = centerX - (gesture.lastCenterX || centerX);",
    "        const deltaY = centerY - (gesture.lastCenterY || centerY);",
    "        if (Math.abs(deltaX) > 0.2 || Math.abs(deltaY) > 0.2) {",
    "            officePanBy(deltaX, deltaY);",
    "        }",
    "        gesture.lastCenterX = centerX;",
    "        gesture.lastCenterY = centerY;",
    "        return true;",
    "    }",
    "    if (pointers.length === 1 && gesture.active) {",
    "        const pointer = pointers[0];",
    "        const deltaX = pointer.x - (gesture.lastCenterX || pointer.x);",
    "        const deltaY = pointer.y - (gesture.lastCenterY || pointer.y);",
    "        if (Math.abs(deltaX) > 0.1 || Math.abs(deltaY) > 0.1) {",
    "            officePanBy(deltaX, deltaY);",
    "        }",
    "        gesture.lastCenterX = pointer.x;",
    "        gesture.lastCenterY = pointer.y;",
    "        return true;",
    "    }",
    "    return false;",
    "}",
    "",
    "function officeTouchGestureEnd(event) {",
    "    if (!officeState?.touchGesture) return;",
    "    const gesture = officeState.touchGesture;",
    "    gesture.pointerById.delete(event.pointerId);",
    "    const pointers = officeTouchActivePointers();",
    "    if (pointers.length >= 2) {",
    "        const a = pointers[0];",
    "        const b = pointers[1];",
    "        gesture.baseDistance = Math.max(0.001, Math.hypot(b.x - a.x, b.y - a.y));",
    "        gesture.baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "        gesture.lastCenterX = (a.x + b.x) / 2;",
    "        gesture.lastCenterY = (a.y + b.y) / 2;",
    "        gesture.active = true;",
    "        return;",
    "    }",
    "    if (pointers.length === 1) {",
    "        const pointer = pointers[0];",
    "        gesture.lastCenterX = pointer.x;",
    "        gesture.lastCenterY = pointer.y;",
    "        gesture.baseDistance = 0;",
    "        gesture.active = true;",
    "        return;",
    "    }",
    "    gesture.active = false;",
    "    gesture.baseDistance = 0;",
    "}",
    "",
    "function officeClampResizeValue(value, min, max) {",
    "    const minBound = Number.isFinite(min) ? min : 80;",
    "    const maxBound = Number.isFinite(max) ? Math.max(minBound, max) : Number.POSITIVE_INFINITY;",
    "    if (!Number.isFinite(value)) return minBound;",
    "    return Math.max(minBound, Math.min(maxBound, value));",
    "}",
    "",
    "function officePanelResizeMetrics(panel) {",
    "    if (!(panel instanceof HTMLElement)) {",
    "        return { minWidth: 120, minHeight: 80, maxWidth: window.innerWidth, maxHeight: window.innerHeight };",
    "    }",
    "    const computed = window.getComputedStyle(panel);",
    "    const minWidth = Math.max(120, Number.parseFloat(computed.minWidth) || 0);",
    "    const minHeight = Math.max(80, Number.parseFloat(computed.minHeight) || 0);",
    "    const parentRect = panel.parentElement instanceof Element",
    "        ? panel.parentElement.getBoundingClientRect()",
    "        : null;",
    "    const maxWidth = Math.max(minWidth, Number(parentRect?.width) || window.innerWidth);",
    "    const maxHeight = Math.max(minHeight, Number(parentRect?.height) || window.innerHeight);",
    "    return { minWidth, minHeight, maxWidth, maxHeight };",
    "}",
    "",
    "function officePanelResizeBegin(event) {",
    "    if (!officeState || !(event.currentTarget instanceof Element)) return;",
    "    if (window.matchMedia && window.matchMedia('(max-width: 760px)').matches) return;",
    "    const handle = event.currentTarget;",
    "    const panel = handle.closest('.office-resizable');",
    "    if (!(panel instanceof HTMLElement)) return;",
    "    event.preventDefault();",
    "    event.stopPropagation();",
    "",
    "    const rect = panel.getBoundingClientRect();",
    "    const { minWidth, minHeight, maxWidth, maxHeight } = officePanelResizeMetrics(panel);",
    "    officeState.panelResize = {",
    "        active: true,",
    "        pointerId: event.pointerId,",
    "        dir: safeString(handle.getAttribute('data-dir')).toLowerCase(),",
    "        panel,",
    "        startX: event.clientX,",
    "        startY: event.clientY,",
    "        startWidth: rect.width,",
    "        startHeight: rect.height,",
    "        minWidth,",
    "        minHeight,",
    "        maxWidth,",
    "        maxHeight,",
    "    };",
    "    panel.classList.add('is-resizing');",
    "    if (typeof handle.setPointerCapture === 'function') {",
    "        handle.setPointerCapture(event.pointerId);",
    "    }",
    "}",
    "",
    "function officePanelResizeMove(event) {",
    "    const resize = officeState?.panelResize;",
    "    if (!resize?.active || !(resize.panel instanceof HTMLElement)) return;",
    "    if (event.pointerId !== resize.pointerId) return;",
    "    event.preventDefault();",
    "",
    "    const deltaX = event.clientX - resize.startX;",
    "    const deltaY = event.clientY - resize.startY;",
    "    const dir = safeString(resize.dir);",
    "    const horizontal = dir.includes('e') || dir.includes('w');",
    "    const vertical = dir.includes('n') || dir.includes('s');",
    "",
    "    if (horizontal) {",
    "        let nextWidth = resize.startWidth;",
    "        if (dir.includes('e')) nextWidth += deltaX;",
    "        if (dir.includes('w')) nextWidth -= deltaX;",
    "        const clampedWidth = officeClampResizeValue(nextWidth, resize.minWidth, resize.maxWidth);",
    "        resize.panel.style.width = String(Math.round(clampedWidth)) + 'px';",
    "    }",
    "",
    "    if (vertical) {",
    "        let nextHeight = resize.startHeight;",
    "        if (dir.includes('s')) nextHeight += deltaY;",
    "        if (dir.includes('n')) nextHeight -= deltaY;",
    "        const clampedHeight = officeClampResizeValue(nextHeight, resize.minHeight, resize.maxHeight);",
    "        resize.panel.style.height = String(Math.round(clampedHeight)) + 'px';",
    "    }",
    "}",
    "",
    "function officePanelResizeEnd(event) {",
    "    const resize = officeState?.panelResize;",
    "    if (!resize?.active) return;",
    "    if (event && Number.isFinite(event.pointerId) && event.pointerId !== resize.pointerId) return;",
    "",
    "    const resizedPanel = resize.panel;",
    "    if (resizedPanel instanceof HTMLElement) {",
    "        resizedPanel.classList.remove('is-resizing');",
    "    }",
    "    officeState.panelResize = {",
    "        active: false,",
    "        pointerId: -1,",
    "        dir: '',",
    "        panel: null,",
    "        startX: 0,",
    "        startY: 0,",
    "        startWidth: 0,",
    "        startHeight: 0,",
    "        minWidth: 0,",
    "        minHeight: 0,",
    "        maxWidth: 0,",
    "        maxHeight: 0,",
    "    };",
    "    if (resizedPanel === officeSceneWrap && officeState) {",
    "        officeResetViewport({ preserveZoom: true });",
    "    }",
    "    officeRenderMinimap();",
    "}",
    "",
    "function officeEnablePanelResizing() {",
    "    if (!officeState || !officeWorkspace) return;",
    "    if (!officeState.panelResize || typeof officeState.panelResize !== 'object') {",
    "        officeState.panelResize = {",
    "            active: false,",
    "            pointerId: -1,",
    "            dir: '',",
    "            panel: null,",
    "            startX: 0,",
    "            startY: 0,",
    "            startWidth: 0,",
    "            startHeight: 0,",
    "            minWidth: 0,",
    "            minHeight: 0,",
    "            maxWidth: 0,",
    "            maxHeight: 0,",
    "        };",
    "    }",
    "    if (!officeState.panelResizeWindowBound) {",
    "        officeState.panelResizeWindowBound = true;",
    "        window.addEventListener('pointermove', officePanelResizeMove, { passive: false });",
    "        window.addEventListener('pointerup', officePanelResizeEnd);",
    "        window.addEventListener('pointercancel', officePanelResizeEnd);",
    "    }",
    "",
    "    if (officeMinimap instanceof HTMLElement) {",
    "        officeMinimap.classList.remove('office-resizable', 'is-resizing');",
    "        officeMinimap.querySelectorAll('.office-resize-handle').forEach((handle) => handle.remove());",
    "        officeMinimap.style.removeProperty('width');",
    "        officeMinimap.style.removeProperty('height');",
    "    }",
    "",
    "    const panels = [",
    "        officeWorkspace.querySelector('.office-toolbar'),",
    "        officeSceneWrap,",
    "        officeWorkspace.querySelector('.office-live-panel'),",
    "        officeWorkspace.querySelector('.office-chatbar'),",
    "        officeWorkspace.querySelector('.office-task-list'),",
    "        officeWorkspace.querySelector('.office-chat-log'),",
    "    ];",
    "    const handleDirs = ['n', 'e', 's', 'w', 'ne', 'nw', 'se', 'sw'];",
    "",
    "    panels.forEach((panelRaw) => {",
    "        if (!(panelRaw instanceof HTMLElement)) return;",
    "        panelRaw.classList.add('office-resizable');",
    "        panelRaw.querySelectorAll('.office-resize-handle').forEach((handle) => handle.remove());",
    "        handleDirs.forEach((dir) => {",
    "            const handle = document.createElement('button');",
    "            handle.type = 'button';",
    "            handle.className = `office-resize-handle office-resize-handle-${dir}`;",
    "            handle.setAttribute('data-dir', dir);",
    "            handle.setAttribute('aria-label', `Resize panel ${dir}`);",
    "            handle.addEventListener('pointerdown', officePanelResizeBegin);",
    "            panelRaw.appendChild(handle);",
    "        });",
    "    });",
    "}",
    "",
    "function officeBindControls() {",
    "    if (!officeState || officeState.controlsBound) return;",
    "    officeState.controlsBound = true;",
    "",
    "    if (officeEditorToggleBtn) {",
    "        officeEditorToggleBtn.addEventListener('click', () => {",
    "            officeSetEditorOpen(true);",
    "        });",
    "    }",
    "    if (officeEditorDockBtn) {",
    "        officeEditorDockBtn.addEventListener('click', () => {",
    "            officeSetEditorOpen(true);",
    "        });",
    "    }",
    "    if (officeEditorCloseBtn) {",
    "        officeEditorCloseBtn.addEventListener('click', () => {",
    "            officeSetEditorOpen(false);",
    "        });",
    "    }",
    "    if (officeEditorModal) {",
    "        officeEditorModal.addEventListener('pointerdown', (event) => {",
    "            if (!(event.target instanceof Element)) return;",
    "            if (event.target.closest('.office-editor-card')) return;",
    "            officeSetEditorOpen(false);",
    "        });",
    "        officeEditorModal.addEventListener('keydown', (event) => {",
    "            if (event.key !== 'Tab') return;",
    "            const focusables = [...officeEditorModal.querySelectorAll(",
    "                'button, input, select, textarea, [tabindex]:not([tabindex=\"-1\"])',",
    "            )].filter((node) => !node.hasAttribute('disabled') && !node.classList.contains('hidden'));",
    "            if (!focusables.length) return;",
    "            const first = focusables[0];",
    "            const last = focusables[focusables.length - 1];",
    "            if (event.shiftKey && document.activeElement === first) {",
    "                event.preventDefault();",
    "                last.focus();",
    "                return;",
    "            }",
    "            if (!event.shiftKey && document.activeElement === last) {",
    "                event.preventDefault();",
    "                first.focus();",
    "            }",
    "        });",
    "    }",
    "    document.addEventListener('keydown', (event) => {",
    "        if (event.key === 'Escape') {",
    "            officeSetEditorOpen(false);",
    "        }",
    "    });",
    "",
    "    if (officeChatSendBtn) {",
    "        officeChatSendBtn.addEventListener('click', officeHandleChatSend);",
    "    }",
    "    if (officeChatInput) {",
    "        officeChatInput.addEventListener('keydown', (event) => {",
    "            if (event.key === 'Enter' && !event.shiftKey) {",
    "                event.preventDefault();",
    "                officeHandleChatSend();",
    "            }",
    "        });",
    "    }",
    "",
    "    if (officeAgentSelect) {",
    "        officeAgentSelect.addEventListener('change', () => {",
    "            officeState.selectedAgentId = safeString(officeAgentSelect.value);",
    "            officeSyncCustomizerFields();",
    "            if (safeString(officeState.followAgentId)) {",
    "                officeSetFollowMode(true, officeState.selectedAgentId);",
    "            }",
    "        });",
    "    }",
    "",
    "    if (officeFollowToggleBtn) {",
    "        officeFollowToggleBtn.addEventListener('click', () => {",
    "            const enable = !safeString(officeState?.followAgentId);",
    "            officeSetFollowMode(enable, officeState?.selectedAgentId || '');",
    "        });",
    "    }",
    "",
    "    if (officeMinimapCanvas) {",
    "        const minimapPan = (event) => {",
    "            if (!officeState) return;",
    "            event.preventDefault();",
    "            officePanToMinimapEvent(event);",
    "        };",
    "        const minimapEnd = (event) => {",
    "            if (!officeState?.minimapDrag?.active) return;",
    "            if (event.pointerId !== officeState.minimapDrag.pointerId) return;",
    "            officeState.minimapDrag.active = false;",
    "            officeState.minimapDrag.pointerId = -1;",
    "            if (officeMinimap && officeMinimap.classList) {",
    "                officeMinimap.classList.remove('dragging');",
    "            }",
    "            if (officeMinimapCanvas.hasPointerCapture(event.pointerId)) {",
    "                officeMinimapCanvas.releasePointerCapture(event.pointerId);",
    "            }",
    "        };",
    "        officeMinimapCanvas.addEventListener('pointerdown', (event) => {",
    "            if (!officeState) return;",
    "            if (safeString(officeState.followAgentId)) {",
    "                officeSetFollowMode(false);",
    "            }",
    "            officeState.minimapDrag.active = true;",
    "            officeState.minimapDrag.pointerId = event.pointerId;",
    "            officeMinimapCanvas.setPointerCapture(event.pointerId);",
    "            if (officeMinimap && officeMinimap.classList) {",
    "                officeMinimap.classList.add('dragging');",
    "            }",
    "            minimapPan(event);",
    "        });",
    "        officeMinimapCanvas.addEventListener('pointermove', (event) => {",
    "            if (!officeState?.minimapDrag?.active) return;",
    "            if (event.pointerId !== officeState.minimapDrag.pointerId) return;",
    "            minimapPan(event);",
    "        });",
    "        officeMinimapCanvas.addEventListener('pointerup', minimapEnd);",
    "        officeMinimapCanvas.addEventListener('pointercancel', minimapEnd);",
    "    }",
    "",
    "    if (officeAgentNameInput) {",
    "        officeAgentNameInput.addEventListener('input', () => {",
    "            const agent = officeGetAgentById(officeState.selectedAgentId);",
    "            if (!agent) return;",
    "            const proposed = safeString(officeAgentNameInput.value).slice(0, 24);",
    "            if (!proposed) return;",
    "            const normalized = officeAgentHandle(proposed);",
    "            const duplicate = officeState.agents.find((entry) => (",
    "                entry.id !== agent.id && officeAgentHandle(entry.name) === normalized",
    "            ));",
    "            if (duplicate) {",
    "                const suffix = Math.floor(officeRandomRange(2, 99));",
    "                agent.name = `${proposed.slice(0, 20)} ${suffix}`;",
    "            } else {",
    "                agent.name = proposed;",
    "            }",
    "            officeRenderAgentSelector(agent.id);",
    "            officePersistAgentPrefs();",
    "            officeBusEmit('agent.customized', {",
    "                agentId: agent.id,",
    "                field: 'name',",
    "                value: agent.name,",
    "            });",
    "        });",
    "    }",
    "",
    "    if (officeAgentColorInput) {",
    "        officeAgentColorInput.addEventListener('input', () => {",
    "            const agent = officeGetAgentById(officeState.selectedAgentId);",
    "            if (!agent) return;",
    "            const color = safeString(officeAgentColorInput.value);",
    "            if (!/^#[0-9a-f]{6}$/i.test(color)) return;",
    "            agent.color = color;",
    "            agent.tint = officeAgentTintFromColor(color);",
    "            officeRenderAgents();",
    "            officePersistAgentPrefs();",
    "            officeBusEmit('agent.customized', {",
    "                agentId: agent.id,",
    "                field: 'color',",
    "                value: color,",
    "            });",
    "        });",
    "    }",
    "",
    "    if (officeAgentCostumeSelect) {",
    "        officeAgentCostumeSelect.addEventListener('change', () => {",
    "            const agent = officeGetAgentById(officeState.selectedAgentId);",
    "            if (!agent) return;",
    "            const costume = safeString(officeAgentCostumeSelect.value).toLowerCase();",
    "            if (!['none', 'cap', 'visor', 'headset', 'bowtie'].includes(costume)) return;",
    "            agent.costume = costume;",
    "            officeRenderAgents();",
    "            officePersistAgentPrefs();",
    "            officeBusEmit('agent.customized', {",
    "                agentId: agent.id,",
    "                field: 'costume',",
    "                value: costume,",
    "            });",
    "        });",
    "    }",
    "",
    "    if (officeActionSummonBtn) {",
    "        officeActionSummonBtn.addEventListener('click', () => {",
    "            officeRunQuickAction('summon');",
    "        });",
    "    }",
    "    if (officeActionBreakBtn) {",
    "        officeActionBreakBtn.addEventListener('click', () => {",
    "            officeRunQuickAction('break');",
    "        });",
    "    }",
    "    if (officeActionResumeBtn) {",
    "        officeActionResumeBtn.addEventListener('click', () => {",
    "            officeRunQuickAction('resume');",
    "        });",
    "    }",
    "",
    "    if (officeZoomOutBtn) {",
    "        officeZoomOutBtn.addEventListener('click', () => {",
    "            const baseZoom = Number.isFinite(officeState?.targetZoomLevel) ? officeState.targetZoomLevel : (officeState?.zoomLevel || 1);",
    "            officeSetZoom(baseZoom - OFFICE_ZOOM_STEP);",
    "        });",
    "    }",
    "    if (officeZoomInBtn) {",
    "        officeZoomInBtn.addEventListener('click', () => {",
    "            const baseZoom = Number.isFinite(officeState?.targetZoomLevel) ? officeState.targetZoomLevel : (officeState?.zoomLevel || 1);",
    "            officeSetZoom(baseZoom + OFFICE_ZOOM_STEP);",
    "        });",
    "    }",
    "    if (officeZoomResetBtn) {",
    "        officeZoomResetBtn.addEventListener('click', () => {",
    "            officeResetViewport();",
    "        });",
    "    }",
    "    if (officeDebugToggleBtn) {",
    "        officeDebugToggleBtn.addEventListener('click', () => {",
    "            if (!officeState) return;",
    "            officeState.debugOverlayOpen = !officeState.debugOverlayOpen;",
    "            officeDebugToggleBtn.classList.toggle('active', officeState.debugOverlayOpen);",
    "            officeDebugToggleBtn.setAttribute('aria-pressed', officeState.debugOverlayOpen ? 'true' : 'false');",
    "            officeRenderDebugOverlay();",
    "        });",
    "    }",
    "    if (officeSceneWrap) {",
    "        officeSceneWrap.addEventListener('pointerdown', (event) => {",
    "            if (!officeState) return;",
    "            if (!(event.target instanceof Element)) return;",
    "            if (event.target.closest('.office-agent-hitbox')) return;",
    "            if (event.target.closest('.office-map-controls')) return;",
    "            if (event.target.closest('.office-minimap')) return;",
    "            if (event.target.closest('.office-editor-card')) return;",
    "            if (safeString(officeState.followAgentId)) {",
    "                officeSetFollowMode(false);",
    "            }",
    "",
    "            if (event.pointerType === 'touch') {",
    "                event.preventDefault();",
    "                officeTouchGestureDown(event);",
    "                officeSceneWrap.setPointerCapture(event.pointerId);",
    "                return;",
    "            }",
    "            if (event.button !== 0) return;",
    "",
    "            officeState.dragging = {",
    "                active: true,",
    "                pointerId: event.pointerId,",
    "                lastX: event.clientX,",
    "                lastY: event.clientY,",
    "            };",
    "            officeSceneWrap.classList.add('is-panning');",
    "            officeSceneWrap.setPointerCapture(event.pointerId);",
    "        });",
    "        officeSceneWrap.addEventListener('pointermove', (event) => {",
    "            if (event.pointerType === 'touch') {",
    "                const consumed = officeTouchGestureMove(event);",
    "                if (consumed) {",
    "                    event.preventDefault();",
    "                    return;",
    "                }",
    "            }",
    "            if (!officeState?.dragging?.active) return;",
    "            if (event.pointerId !== officeState.dragging.pointerId) return;",
    "            const deltaX = event.clientX - officeState.dragging.lastX;",
    "            const deltaY = event.clientY - officeState.dragging.lastY;",
    "            officeState.dragging.lastX = event.clientX;",
    "            officeState.dragging.lastY = event.clientY;",
    "            officePanBy(deltaX, deltaY);",
    "        });",
    "        const endDrag = (event) => {",
    "            if (event.pointerType === 'touch') {",
    "                officeTouchGestureEnd(event);",
    "                if (officeSceneWrap.hasPointerCapture(event.pointerId)) {",
    "                    officeSceneWrap.releasePointerCapture(event.pointerId);",
    "                }",
    "            }",
    "            if (!officeState?.dragging?.active) return;",
    "            if (event.pointerId !== officeState.dragging.pointerId) return;",
    "            officeState.dragging.active = false;",
    "            officeSceneWrap.classList.remove('is-panning');",
    "            if (officeSceneWrap.hasPointerCapture(event.pointerId)) {",
    "                officeSceneWrap.releasePointerCapture(event.pointerId);",
    "            }",
    "        };",
    "        officeSceneWrap.addEventListener('pointerup', endDrag);",
    "        officeSceneWrap.addEventListener('pointercancel', endDrag);",
    "        officeSceneWrap.addEventListener('wheel', (event) => {",
    "            if (!officeState) return;",
    "            event.preventDefault();",
    "            const deltaUnit = event.deltaMode === 1 ? 14 : (event.deltaMode === 2 ? 120 : 1);",
    "            const normalizedDelta = officeClamp(event.deltaY * deltaUnit, -220, 220);",
    "            const baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "            const factor = Math.exp(-normalizedDelta * OFFICE_WHEEL_ZOOM_SENSITIVITY);",
    "            officeSetZoom(",
    "                baseZoom * factor,",
    "                { anchorClientX: event.clientX, anchorClientY: event.clientY },",
    "            );",
    "        }, { passive: false });",
    "        officeSceneWrap.addEventListener('keydown', (event) => {",
    "            if (!officeState) return;",
    "            const panStep = event.shiftKey ? 88 : 46;",
    "            if (event.key === 'ArrowLeft') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(panStep, 0);",
    "                return;",
    "            }",
    "            if (event.key === 'ArrowRight') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(-panStep, 0);",
    "                return;",
    "            }",
    "            if (event.key === 'ArrowUp') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(0, panStep);",
    "                return;",
    "            }",
    "            if (event.key === 'ArrowDown') {",
    "                event.preventDefault();",
    "                if (safeString(officeState.followAgentId)) officeSetFollowMode(false);",
    "                officePanBy(0, -panStep);",
    "                return;",
    "            }",
    "            if (event.key === '+' || event.key === '=' || event.key === 'Add') {",
    "                event.preventDefault();",
    "                const baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "                officeSetZoom(baseZoom + OFFICE_ZOOM_STEP);",
    "                return;",
    "            }",
    "            if (event.key === '-' || event.key === '_' || event.key === 'Subtract') {",
    "                event.preventDefault();",
    "                const baseZoom = Number.isFinite(officeState.targetZoomLevel) ? officeState.targetZoomLevel : officeState.zoomLevel;",
    "                officeSetZoom(baseZoom - OFFICE_ZOOM_STEP);",
    "                return;",
    "            }",
    "            if (event.key === '0' || event.key === 'Home') {",
    "                event.preventDefault();",
    "                officeResetViewport();",
    "                return;",
    "            }",
    "            if (event.key === '`' || event.key === 'd' || event.key === 'D') {",
    "                event.preventDefault();",
    "                if (officeDebugToggleBtn) {",
    "                    officeDebugToggleBtn.click();",
    "                }",
    "            }",
    "        });",
    "    }",
    "    officeEnablePanelResizing();",
    "    window.addEventListener('resize', () => {",
    "        if (!officeState) return;",
    "        officeResetViewport({ preserveZoom: true });",
    "    });",
    "    document.addEventListener('visibilitychange', () => {",
    "        if (!officeState) return;",
    "        if (document.hidden) {",
    "            officeState.hiddenAtEpoch = Date.now();",
    "            officePersistRuntimeState(performance.now(), { force: true });",
    "            return;",
    "        }",
    "        officeState.hiddenAtEpoch = 0;",
    "        officeState.lastWallClockTickAt = Date.now();",
    "        officeRenderAgents();",
    "        if (officeState.tasksDirty) {",
    "            officeState.tasksDirty = false;",
    "            officeRenderTaskList();",
    "        }",
    "        officeUpdateRoomMeta();",
    "        officeRenderMinimap();",
    "        officePersistRuntimeState(performance.now(), { force: true });",
    "    });",
    "    window.addEventListener('beforeunload', () => {",
    "        if (!officeState) return;",
    "        officeStopMissionStream();",
    "        officeStopBackgroundTickTimer();",
    "        officePersistCameraState(Number.POSITIVE_INFINITY);",
    "        officePersistLayoutState();",
    "        officePersistAgentPrefs();",
    "        officePersistRuntimeState(performance.now(), { force: true });",
    "    });",
    "}",
    "",
    "function officeEnsureState() {",
    "    if (officeState) {",
    "        return true;",
    "    }",
    "    if (!officeScene || !officeWorkspace) {",
    "        return false;",
    "    }",
    "",
    "    const now = performance.now();",
    "    const storedLayout = loadStoredOfficeLayoutState();",
    "    const storedRuntime = loadStoredOfficeRuntimeState();",
    "    const dynamicRoomBySlug = new Map();",
    "    let dynamicIndex = 0;",
    "    const rooms = OFFICE_STATIC_ROOMS.map((room) => ({ ...room, dynamic: false }));",
    "    if (Array.isArray(storedLayout?.dynamicRooms)) {",
    "        storedLayout.dynamicRooms.forEach((roomRaw, idx) => {",
    "            const room = officeSanitizeDynamicRoomSnapshot(roomRaw, idx);",
    "            if (!room) return;",
    "            rooms.push(room);",
    "            const idMatch = safeString(room.id).match(/^room-dynamic-(\\d+)$/i);",
    "            const numericIndex = Number(idMatch?.[1]);",
    "            if (Number.isFinite(numericIndex) && numericIndex > dynamicIndex) {",
    "                dynamicIndex = numericIndex;",
    "            }",
    "        });",
    "    }",
    "    if (storedLayout?.dynamicRoomBySlug && typeof storedLayout.dynamicRoomBySlug === 'object') {",
    "        Object.entries(storedLayout.dynamicRoomBySlug).forEach(([slug, roomId]) => {",
    "            const key = safeString(slug);",
    "            const id = safeString(roomId);",
    "            if (!key || !id) return;",
    "            if (!rooms.some((room) => room.id === id)) return;",
    "            dynamicRoomBySlug.set(key, id);",
    "        });",
    "    }",
    "    const roomById = new Map();",
    "    rooms.forEach((room) => {",
    "        roomById.set(room.id, room);",
    "    });",
    "    const { navMap, roomNav } = officeBuildNavGraph(rooms);",
    "    const lobbyCenterId = roomNav.get('room-lobby')?.centerNodeId || '';",
    "    const lobbyCenter = lobbyCenterId ? navMap.get(lobbyCenterId) : null;",
    "    const spawnRoomSequence = [",
    "        'room-engineering',",
    "        'room-content',",
    "        'room-research',",
    "        'room-ops',",
    "        'room-planning',",
    "        'room-support',",
    "        'room-design',",
    "        'room-pods',",
    "        'room-break',",
    "        'room-coffee',",
    "        'room-lobby',",
    "    ].filter((roomId) => roomById.has(roomId));",
    "",
    "    const pickSpawnNodeForAgent = (seed, index) => {",
    "        const preferredRoomId = spawnRoomSequence[index % Math.max(1, spawnRoomSequence.length)] || 'room-lobby';",
    "        const nav = roomNav.get(preferredRoomId);",
    "        const slotNodeIds = Array.isArray(nav?.slotNodeIds) ? nav.slotNodeIds : [];",
    "        if (slotNodeIds.length) {",
    "            const slotIndex = officeStableHash(`${safeString(seed?.name)}|${index}`) % slotNodeIds.length;",
    "            const nodeId = slotNodeIds[slotIndex];",
    "            const node = navMap.get(nodeId);",
    "            if (node) return node;",
    "        }",
    "        const centerNode = navMap.get(nav?.centerNodeId || '');",
    "        if (centerNode) return centerNode;",
    "        return lobbyCenter || null;",
    "    };",
    "",
    "    const agents = OFFICE_AGENT_SEEDS.map((seed, index) => {",
    "        const spawnNode = pickSpawnNodeForAgent(seed, index);",
    "        return ({",
    "        id: `agent-${index + 1}`,",
    "        name: seed.name,",
    "        color: seed.color,",
    "        costume: seed.costume,",
    "        tint: seed.tint || 'blue',",
    "        x: spawnNode ? officeClamp(spawnNode.x + officeRandomRange(-0.18, 0.18), 3, 97) : officeRandomRange(35, 92),",
    "        y: spawnNode ? officeClamp(spawnNode.y + officeRandomRange(-0.18, 0.18), 5, 96) : officeRandomRange(64, 90),",
    "        targetX: 0,",
    "        targetY: 0,",
    "        speed: officeRandomRange(2.35, 3.75),",
    "        facing: officeChance(0.5) ? 1 : -1,",
    "        laneBias: officeRandomRange(-0.65, 0.65),",
    "        state: 'idle',",
    "        intent: 'wander',",
    "        taskId: '',",
    "        workStreak: 0,",
    "        workUntil: 0,",
    "        breakUntil: 0,",
    "        idleUntil: now + (index * 180) + officeRandomRange(450, 1700),",
    "        nextAmbientAt: now + officeRandomRange(3500, 9000),",
    "        nextWorkLineAt: now + officeRandomRange(2400, 6200),",
    "        nextSocialAt: now + officeRandomRange(5000, 14000),",
    "        nextBreakAt: now + officeRandomRange(34_000, 82_000),",
    "        speech: null,",
    "        bumpUntil: 0,",
    "        jumpUntil: 0,",
    "        collisionCooldownUntil: 0,",
    "        crowdReliefUntil: 0,",
    "        yieldUntil: 0,",
    "        yieldResumeIntent: '',",
    "        stuckSince: 0,",
    "        lastMoveX: 0,",
    "        lastMoveY: 0,",
    "        returnAfterRunAt: 0,",
    "        runawayPhase: '',",
    "        runawayExitX: 0,",
    "        runawayExitY: 0,",
    "        currentNodeId: '',",
    "        routeWaypoints: [],",
    "        routeDestinationNodeId: '',",
    "        reservedLaneEdgeKey: '',",
    "    });",
    "    });",
    "    const storedAgentPrefs = loadStoredOfficeAgentPrefs();",
    "    officeApplyDefaultAgentStyleDiversification(agents, storedAgentPrefs);",
    "    officeApplyStoredAgentPrefs(agents, storedAgentPrefs);",
    "    agents.forEach((agent) => {",
    "        agent.targetX = agent.x;",
    "        agent.targetY = agent.y;",
    "        agent.lastMoveX = agent.x;",
    "        agent.lastMoveY = agent.y;",
    "        agent.currentNodeId = officeFindNearestNode(navMap, agent.x, agent.y);",
    "    });",
    "    const initialMap = officeMapDimensionsForRoomCount(rooms.length);",
    "    const storedCamera = loadStoredOfficeCameraState();",
    "    const storedZoom = Number.isFinite(storedCamera?.zoom) ? officeClamp(storedCamera.zoom, OFFICE_ZOOM_MIN, OFFICE_ZOOM_MAX) : 0.9;",
    "",
    "    officeState = {",
    "        rooms,",
    "        roomById,",
    "        navMap,",
    "        roomNav,",
    "        corridors: [...OFFICE_CORRIDORS],",
    "        dynamicRoomBySlug,",
    "        dynamicIndex,",
    "        agents,",
    "        tasks: [],",
    "        taskCounter: 0,",
    "        chatLines: [],",
    "        officeEvents: [],",
    "        officeBusListeners: new Set(),",
    "        selectedAgentId: agents[0]?.id || '',",
    "        controlsBound: false,",
    "        roomLayerEl: null,",
    "        agentLayerEl: null,",
    "        agentElements: new Map(),",
    "        tasksDirty: true,",
    "        lastRoomMetaSyncAt: 0,",
    "        lastCameraPersistAt: 0,",
    "        lastCameraPersistSignature: '',",
    "        lastRuntimePersistAt: 0,",
    "        lastWallClockTickAt: Date.now(),",
    "        hiddenAtEpoch: 0,",
    "        lastCollisionCooldownPurgeAt: 0,",
    "        nextGlobalSpeechAt: 0,",
    "        collisionSpeechCooldownUntil: 0,",
    "        collisionPairCooldowns: new Map(),",
    "        laneReservations: new Map(),",
    "        lastSocialTickAt: 0,",
    "        nextSocialWindowAt: now + officeRandomRange(1800, 4000),",
    "        debugOverlayOpen: false,",
    "        lastDebugRenderAt: 0,",
    "        debugFrameRate: 0,",
    "        followAgentId: safeString(storedCamera?.followAgentId),",
    "        rafId: 0,",
    "        lastFrameAt: 0,",
    "        active: false,",
    "        backgroundTickTimerId: 0,",
    "        mapWidth: initialMap.width,",
    "        mapHeight: initialMap.height,",
    "        zoomLevel: storedZoom,",
    "        targetZoomLevel: storedZoom,",
    "        panX: Number(storedCamera?.panX) || 0,",
    "        panY: Number(storedCamera?.panY) || 0,",
    "        targetPanX: Number(storedCamera?.panX) || 0,",
    "        targetPanY: Number(storedCamera?.panY) || 0,",
    "        dragging: {",
    "            active: false,",
    "            pointerId: -1,",
    "            lastX: 0,",
    "            lastY: 0,",
    "        },",
    "        minimapDrag: {",
    "            active: false,",
    "            pointerId: -1,",
    "        },",
    "        touchGesture: {",
    "            pointerById: new Map(),",
    "            active: false,",
    "            baseDistance: 0,",
    "            baseZoom: 1,",
    "            lastCenterX: 0,",
    "            lastCenterY: 0,",
    "        },",
    "        stream: {",
    "            connected: false,",
    "            connecting: false,",
    "            retryMs: OFFICE_STREAM_RETRY_MIN_MS,",
    "            reconnectTimer: 0,",
    "            controller: null,",
    "            lastSeq: 0,",
    "            lastMessageAt: 0,",
    "        },",
    "    };",
    "",
    "    officeApplyRuntimeSnapshot(storedRuntime, now);",
    "",
    "    officeRenderScene();",
    "    officeRenderTaskList();",
    "    officeRenderAgentSelector();",
    "    officeBindControls();",
    "    officeResetViewport();",
    "    if (storedCamera) {",
    "        officeState.zoomLevel = storedZoom;",
    "        officeState.targetZoomLevel = storedZoom;",
    "        const clampedPan = officeClampPan(",
    "            Number(storedCamera.panX) || 0,",
    "            Number(storedCamera.panY) || 0,",
    "            storedZoom,",
    "        );",
    "        officeState.panX = clampedPan.panX;",
    "        officeState.panY = clampedPan.panY;",
    "        officeState.targetPanX = clampedPan.panX;",
    "        officeState.targetPanY = clampedPan.panY;",
    "        officeApplyZoom();",
    "    }",
    "    if (safeString(storedCamera?.followAgentId)) {",
    "        officeSetFollowMode(true, storedCamera.followAgentId);",
    "    }",
    "    officeUpdateFollowUi();",
    "    officeSetEditorOpen(false);",
    "    officePushChatLine(officePick(OFFICE_DIALOGUE.startup));",
    "    officePersistCameraState();",
    "    officePersistLayoutState();",
    "    officePersistAgentPrefs();",
    "    officePersistRuntimeState(now, { force: true });",
    "    officeBusEmit('office.booted', {",
    "        rooms: officeState.rooms.length,",
    "        dynamicRooms: officeState.rooms.filter((room) => room.dynamic).length,",
    "        agents: officeState.agents.length,",
    "    });",
    "    officeStartLoop();",
    "    return true;",
    "}",
    "",
    "function officeSyncReducedMotionPreference() {",
    "    if (!officeWorkspace) return;",
    "    const prefersReduced = Boolean(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);",
    "    const prefersHighContrast = Boolean(window.matchMedia && window.matchMedia('(prefers-contrast: more)').matches);",
    "    officeWorkspace.classList.toggle('reduced-motion', prefersReduced);",
    "    officeWorkspace.classList.toggle('high-contrast', prefersHighContrast);",
    "}",
    "",
    "function initOfficeWorkspace() {",
    "    if (!officeScene || !officeWorkspace) return;",
].join("\n");
