/* split from part-006.js */
export default [
    "            onGround: true,",
    "            ducking: false,",
    "            facing: 1,",
    "        },",
    "        obstacles: [],",
    "        scene: {",
    "            doorVisible: false,",
    "            doorOpen: 0,",
    "            light: 0,",
    "            botVisible: true,",
    "            botRunning: false,",
    "            botInside: false,",
    "            botDoorOffsetX: 0,",
    "            botX: portalAnchor.x,",
    "            botY: portalY,",
    "            botScale: 0.3,",
    "            botRotate: 0,",
    "            botJetpack: false,",
    "        },",
    "    };",
    "    state.player.y = state.groundY;",
    "    chatGameRuntime.dinoRun = state;",
    "    chatGameRuntime.lastFrameMs = 0;",
    "    chatGameUpdateHud(state);",
    "    chatGameSetStatusText('Portal spin-up...');",
    "    chatGameSyncScene(state);",
    "",
    "    const stabilizePortalAnchor = () => {",
    "        const live = chatGameRuntime.dinoRun;",
    "        if (!live || live.id !== DINO_GAME_ID || live.mode !== 'intro') return;",
    "        const nextAnchor = chatGameGetPortalAnchorInDino(live);",
    "        live.portal.x = nextAnchor.x;",
    "        live.portal.y = chatGameClamp(Math.min(nextAnchor.y - 18, live.groundY + 4), 18, live.height - 52);",
    "        if (live.introSeconds < 0.16) {",
    "            live.scene.botX = nextAnchor.x;",
    "            live.scene.botY = live.portal.y;",
    "        }",
    "        chatGameSyncScene(live);",
    "    };",
    "",
    "    window.requestAnimationFrame(() => {",
    "        stabilizePortalAnchor();",
    "        window.requestAnimationFrame(stabilizePortalAnchor);",
    "    });",
    "}",
    "",
    "function chatGameStartDinoRun(state = chatGameRuntime.dinoRun) {",
    "    if (!state || state.mode !== 'ready') return false;",
    "    state.mode = 'playing';",
    "    state.score = 0;",
    "    state.playFrames = 0;",
    "    state.speed = DINO_SCROLL_BASE;",
    "    state.spawnFrames = chatGameRandom(DINO_SPAWN_FRAMES_MIN, DINO_SPAWN_FRAMES_MAX);",
    "    state.obstacles = [];",
    "    state.player.vy = 0;",
    "    state.player.onGround = true;",
    "    state.player.ducking = false;",
    "    state.player.h = DINO_PLAYER_NORMAL_HEIGHT;",
    "    state.player.y = state.height - DINO_GROUND_PADDING - state.player.h;",
    "    state.portal.visible = false;",
    "    chatGameSetStatusText('Run active. Space to jump | Down to duck.');",
    "    chatGameSyncScene(state);",
    "    return true;",
    "}",
    "",
    "function chatGameDinoJump(state = chatGameRuntime.dinoRun) {",
    "    if (!state || state.mode !== 'playing') return false;",
    "    const player = state.player;",
    "    if (!player.onGround) return false;",
    "    player.vy = DINO_JUMP_VELOCITY;",
    "    player.onGround = false;",
    "    return true;",
    "}",
    "",
    "function chatGameSetDinoDuck(state, wantsDuck) {",
    "    const player = state?.player;",
    "    if (!player || !player.onGround) return;",
    "    if (wantsDuck && !player.ducking) {",
    "        const delta = DINO_PLAYER_NORMAL_HEIGHT - DINO_PLAYER_DUCK_HEIGHT;",
    "        player.ducking = true;",
    "        player.h = DINO_PLAYER_DUCK_HEIGHT;",
    "        player.y += delta;",
    "    } else if (!wantsDuck && player.ducking) {",
    "        const delta = DINO_PLAYER_NORMAL_HEIGHT - DINO_PLAYER_DUCK_HEIGHT;",
    "        player.ducking = false;",
    "        player.h = DINO_PLAYER_NORMAL_HEIGHT;",
    "        player.y -= delta;",
    "    }",
    "}",
    "",
    "function chatGameDinoCollision(state, obstacle) {",
    "    const player = state?.player;",
    "    if (!player || !obstacle) return false;",
    "    const padding = 4;",
    "    const px = player.x + padding;",
    "    const py = player.y + padding;",
    "    const pw = Math.max(1, player.w - (padding * 2));",
    "    const ph = Math.max(1, player.h - (padding * 2));",
    "    return (",
    "        px < obstacle.x + obstacle.w",
    "        && px + pw > obstacle.x",
    "        && py < obstacle.y + obstacle.h",
    "        && py + ph > obstacle.y",
    "    );",
    "}",
    "",
    "function chatGameStepDinoIntro(state, deltaFrames) {",
    "    state.tick += deltaFrames;",
    "    state.introSeconds += (deltaFrames / 60);",
    "    const scene = state.scene;",
    "    const player = state.player;",
    "    const portal = state.portal;",
    "    const progress = chatGameClamp(state.introSeconds / DINO_INTRO_DURATION_SECONDS, 0, 1);",
    "    const warmup = chatGameClamp(progress / 0.34, 0, 1);",
    "    const walkProgress = chatGameEaseOutCubic(chatGameClamp((progress - 0.34) / 0.62, 0, 1));",
    "",
    "    portal.visible = progress < 0.95;",
    "    portal.spin += (deltaFrames * chatGameLerp(33, 16, warmup));",
    "    portal.scale = chatGameLerp(0.24, 1.46, warmup) + (Math.sin(state.tick * 0.11) * (0.03 + (0.05 * warmup)));",
    "    portal.glow = 0.82 + (Math.sin(state.tick * 0.11) * 0.14);",
    "",
    "    scene.doorVisible = false;",
    "    scene.doorOpen = 0;",
    "    scene.light = 0;",
    "    scene.botInside = false;",
    "    scene.botDoorOffsetX = 0;",
    "    scene.botVisible = progress > 0.34;",
    "    scene.botRunning = walkProgress > 0.06 && walkProgress < 0.98;",
    "    scene.botJetpack = false;",
    "    scene.botScale = chatGameClamp(0.74 + (walkProgress * 0.26), 0.7, 1);",
    "    scene.botRotate = 0;",
    "    scene.botX = chatGameLerp(portal.x + 1, player.x, walkProgress);",
    "    scene.botY = state.groundY;",
    "    player.y = state.groundY;",
    "    player.vy = 0;",
    "    player.onGround = true;",
    "",
    "    if (progress >= 1) {",
    "        state.mode = 'ready';",
    "        scene.botVisible = true;",
    "        scene.botRunning = false;",
    "        scene.botScale = 1;",
    "        scene.botRotate = 0;",
    "        scene.botX = player.x;",
    "        scene.botY = player.y;",
    "        portal.visible = false;",
    "        chatGameSetStatusText('Press Space to start | Esc to exit');",
    "    }",
    "}",
    "",
    "function chatGameStepDinoReady(state, deltaFrames) {",
    "    state.tick += deltaFrames;",
    "    state.scrollX += (DINO_SCROLL_BASE * 0.38) * deltaFrames;",
    "    const scene = state.scene;",
    "    const player = state.player;",
    "    player.ducking = false;",
    "    player.h = DINO_PLAYER_NORMAL_HEIGHT;",
    "    player.y = state.height - DINO_GROUND_PADDING - player.h;",
    "    player.vy = 0;",
    "    player.onGround = true;",
    "",
    "    scene.doorVisible = false;",
    "    scene.doorOpen = 0;",
    "    scene.light = 0;",
    "    scene.botVisible = true;",
    "    scene.botRunning = false;",
    "    scene.botInside = false;",
    "    scene.botDoorOffsetX = 0;",
    "    scene.botScale = 1;",
    "    scene.botRotate = 0;",
    "    scene.botJetpack = false;",
    "    scene.botX = player.x;",
    "    scene.botY = player.y + (Math.sin(state.tick * 0.12) * 0.9);",
    "}",
    "",
    "function chatGameStepDinoPlaying(state, deltaFrames) {",
    "    state.tick += deltaFrames;",
    "    state.playFrames += deltaFrames;",
    "    const player = state.player;",
    "    const scene = state.scene;",
    "",
    "    chatGameSetDinoDuck(state, Boolean(chatGameRuntime.input.down));",
    "",
    "    player.vy += DINO_GRAVITY * deltaFrames;",
    "    player.vy = Math.min(player.vy, 16);",
    "    player.y += player.vy * deltaFrames;",
    "    const groundY = state.height - DINO_GROUND_PADDING - player.h;",
    "    if (player.y >= groundY) {",
    "        player.y = groundY;",
    "        player.vy = 0;",
    "        player.onGround = true;",
    "    } else {",
    "        player.onGround = false;",
    "    }",
    "",
    "    state.speed = DINO_SCROLL_BASE + Math.min(DINO_SCROLL_MAX_BONUS, (Math.floor(state.score) * 0.015));",
    "    state.spawnFrames -= deltaFrames;",
    "    if (state.spawnFrames <= 0) {",
    "        state.obstacles.push(chatGameCreateDinoObstacle(state));",
    "        const speedTighten = Math.min(24, Math.floor(state.score) * 0.02);",
    "        state.spawnFrames = chatGameRandom(",
    "            Math.max(30, DINO_SPAWN_FRAMES_MIN - speedTighten),",
    "            Math.max(46, DINO_SPAWN_FRAMES_MAX - speedTighten),",
    "        );",
    "    }",
    "",
    "    state.scrollX += state.speed * deltaFrames;",
    "    let crashed = false;",
    "    state.obstacles.forEach((obstacle) => {",
    "        obstacle.x -= state.speed * deltaFrames;",
    "        if (!obstacle.passed && (obstacle.x + obstacle.w) < player.x) {",
    "            obstacle.passed = true;",
    "            state.score += 1;",
    "        }",
    "        if (!crashed && chatGameDinoCollision(state, obstacle)) {",
    "            crashed = true;",
    "        }",
    "    });",
    "    state.obstacles = state.obstacles.filter((obstacle) => (obstacle.x + obstacle.w) >= -28);",
    "    state.score += state.speed * deltaFrames * 0.11;",
    "",
    "    scene.doorVisible = false;",
    "    scene.doorOpen = 0;",
    "    scene.light = 0;",
    "    scene.botVisible = true;",
    "    scene.botInside = false;",
    "    scene.botDoorOffsetX = 0;",
    "    scene.botRunning = player.onGround && !player.ducking;",
    "    scene.botScale = player.ducking ? 0.9 : 1;",
    "    scene.botRotate = player.onGround ? 0 : -8;",
    "    scene.botJetpack = false;",
    "    scene.botX = player.x;",
    "    scene.botY = player.y;",
    "",
    "    if (crashed) {",
    "        state.mode = 'game_over';",
    "        state.best = Math.max(state.best, Math.floor(state.score));",
    "        chatGameSetHighScore(state.best, DINO_GAME_ID);",
    "        player.vy = 0;",
    "        scene.botRunning = false;"
].join("\n");
