/* split from part-007.js */
export default [
    "            micBtn.style.color = 'var(--text-secondary)';",
    "            notifyUser('Unable to start microphone capture right now.', {",
    "                tone: 'warning',",
    "                debugKind: 'warning',",
    "                durationMs: 2800,",
    "            });",
    "        }",
    "    }",
    "    window.__thomasStopMicCapture = ({ send = false } = {}) => {",
    "        stopMicCapture({ send });",
    "        suppressMicTranscript(2200);",
    "        resetMicDraftState();",
    "    };",
    "",
    "    document.addEventListener('keydown', (event) => {",
    "        if (event.key === 'Escape') {",
    "            // Stop generation first if running",
    "            if (isGenerating) {",
    "                stopGeneration();",
    "                return;",
    "            }",
    "            composerCloseActionsMenu();",
    "        }",
    "        // Ctrl+Shift+N → new chat",
    "        if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key === 'N') {",
    "            event.preventDefault();",
    "            if (typeof startNewSession === 'function') startNewSession();",
    "        }",
    "        // Ctrl+F → in-chat search",
    "        if ((event.ctrlKey || event.metaKey) && !event.shiftKey && event.key === 'f') {",
    "            // Only override Ctrl+F when chat area is visible",
    "            const chatVisible = chatScrollArea && !chatScrollArea.classList.contains('hidden');",
    "            if (chatVisible) {",
    "                event.preventDefault();",
    "                toggleChatSearch();",
    "            }",
    "        }",
    "        // Ctrl+Shift+E → export conversation",
    "        if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key === 'E') {",
    "            event.preventDefault();",
    "            exportChatConversation();",
    "        }",
    "        if (",
    "            event.key === 'End'",
    "            && !event.ctrlKey",
    "            && !event.metaKey",
    "            && !event.altKey",
    "            && !event.shiftKey",
    "            && (micShouldListen || micIsListening)",
    "        ) {",
    "            event.preventDefault();",
    "            stopMicCapture({ send: true });",
    "        }",
    "    });",
    "",
    "    docFileInput.addEventListener('change', async (e) => {",
    "        composerCloseActionsMenu();",
    "        for (const file of e.target.files) {",
    "            if (file.type.startsWith('image/')) {",
    "                const reader = new FileReader();",
    "                reader.onload = (re) => {",
    "                    pendingImages.push({ data_url: re.target.result, name: file.name });",
    "                    renderAttachmentsPreview();",
    "                    composerSyncSendButtonState();",
    "                };",
    "                reader.readAsDataURL(file);",
    "            } else {",
    "                const text = await file.text();",
    "                pendingDocs.push({ name: file.name, text: text });",
    "                renderAttachmentsPreview();",
    "                composerSyncSendButtonState();",
    "            }",
    "        }",
    "        docFileInput.value = ''; // reset",
    "        composerSyncSendButtonState();",
    "    });",
    "",
    "    if ('SpeechRecognition' in window || 'webkitSpeechRecognition' in window) {",
    "        const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;",
    "        recognition = new SpeechRecognition();",
    "        recognition.continuous = true;",
    "        recognition.interimResults = true;",
    "",
    "        recognition.onstart = () => {",
    "            micIsListening = true;",
    "            micBtn.style.color = 'var(--danger-ink)';",
    "        };",
    "",
    "        recognition.onresult = (e) => {",
    "            let interimText = '';",
    "            for (let i = e.resultIndex; i < e.results.length; i += 1) {",
    "                const result = e.results[i];",
    "                const transcript = safeString(result?.[0]?.transcript).trim();",
    "                if (!transcript) continue;",
    "                if (result.isFinal) {",
    "                    micFinalText = joinSpeechText(micFinalText, transcript);",
    "                } else {",
    "                    interimText = joinSpeechText(interimText, transcript);",
    "                }",
    "            }",
    "            renderMicTranscript(interimText);",
    "        };",
    "",
    "        recognition.onend = () => {",
    "            micIsListening = false;",
    "            if (micShouldListen) {",
    "                try {",
    "                    recognition.start();",
    "                    return;",
    "                } catch {",
    "                    micShouldListen = false;",
    "                }",
    "            }",
    "            micBtn.style.color = 'var(--text-secondary)';",
    "            flushPendingMicSend();",
    "        };",
    "",
    "        recognition.onerror = (e) => {",
    "            micIsListening = false;",
    "            if (safeString(e?.error) === 'not-allowed' || safeString(e?.error) === 'service-not-allowed') {",
    "                micShouldListen = false;",
    "                micPendingSend = false;",
    "                notifyUser('Microphone permission was denied.', {",
    "                    tone: 'warning',",
    "                    debugKind: 'warning',",
    "                    durationMs: 2800,",
    "                });",
    "            }",
    "            micBtn.style.color = 'var(--text-secondary)';",
    "        };",
    "    }",
    "",
    "    micBtn.addEventListener('click', () => {",
    "        if (recognition) {",
    "            if (micShouldListen || micIsListening) {",
    "                stopMicCapture({ send: false });",
    "            } else {",
    "                startMicCapture();",
    "            }",
    "        } else {",
    "            notifyUser(\"Speech recognition isn't supported in this browser.\", {",
    "                tone: 'warning',",
    "                debugKind: 'warning',",
    "                durationMs: 2800,",
    "            });",
    "        }",
    "    });",
    "",
    "    // Suggestion chips",
    "    document.querySelectorAll('.suggestion-chip').forEach(btn => {",
    "        btn.addEventListener('click', (e) => {",
    "            composerTextarea.value = e.currentTarget.innerText.trim();",
    "            composerTextarea.dispatchEvent(new Event('input')); // trigger resize and enable button",
    "            composerTextarea.focus();",
    "        });",
    "    });",
    "",
    "    if (assistantSuggestionDismissBtn) {",
    "        assistantSuggestionDismissBtn.addEventListener('click', () => {",
    "            hideAssistantSuggestions();",
    "        });",
    "    }",
    "}",
    "",
    "/**",
    " * Execute the send flow",
    " */",
    "function buildSendJobFromComposer(textRaw = '') {",
    "    const text = safeString(textRaw).trim();",
    "    const docsToSend = [...pendingDocs];",
    "    const imagesToSend = [...pendingImages];",
    "    if (!text && docsToSend.length === 0 && imagesToSend.length === 0) return null;",
    "",
    "    composerTextarea.value = '';",
    "    composerTextarea.dispatchEvent(new Event('input'));",
    "    pendingDocs = [];",
    "    pendingImages = [];",
    "    renderAttachmentsPreview();",
    "",
    "    const suggestionUserContext = [",
    "        safeString(text),",
    "        docsToSend.length > 0 ? `Attached ${docsToSend.length} document(s)` : '',",
    "        imagesToSend.length > 0 ? `Attached ${imagesToSend.length} image(s)` : '',",
    "    ].filter(Boolean).join(' | ');",
    "    return { text, docsToSend, imagesToSend, suggestionUserContext };",
    "}",
    "",
    "async function drainQueuedSends() {",
    "    if (isGenerating || queuedSendDrainActive || pendingSendQueue.length === 0) return;",
    "    queuedSendDrainActive = true;",
    "    try {",
    "        while (!isGenerating && pendingSendQueue.length > 0) {",
    "            const next = pendingSendQueue.shift();",
    "            if (!next) continue;",
    "            await runChatSendJob(next);",
    "        }",
    "    } finally {",
    "        queuedSendDrainActive = false;",
    "        composerSyncSendButtonState();",
    "    }",
    "}",
    "",
    "async function runChatSendJob(sendJob) {",
    "    const text = safeString(sendJob?.text).trim();",
    "    const docsToSend = Array.isArray(sendJob?.docsToSend) ? sendJob.docsToSend : [];",
    "    const imagesToSend = Array.isArray(sendJob?.imagesToSend) ? sendJob.imagesToSend : [];",
    "    const suggestionUserContext = safeString(sendJob?.suggestionUserContext);",
    "    if (!text && docsToSend.length === 0 && imagesToSend.length === 0) return;",
    "",
    "    if (safeString(suggestionContext) !== 'onboarding') {",
    "        hideAssistantSuggestions({ force: true });",
    "    }",
    "    if (safeString(text)) {",
    "        officeMaybeQueueTaskFromPrompt(text, 'chat');",
    "    }",
    "",
    "    if (welcomeScreen && !welcomeScreen.classList.contains('hidden')) {",
    "        welcomeScreen.classList.add('hidden');",
    "        chatScrollArea.classList.remove('hidden');",
    "    }",
    "",
    "    let uiText = text;",
    "    if (docsToSend.length > 0) uiText += `\\n\\n*(Attached ${docsToSend.length} document(s))*`;",
    "    if (imagesToSend.length > 0) uiText += `\\n\\n*(Attached ${imagesToSend.length} image(s))*`;",
    "    const userContent = uiText || '(Sent Attachments)';",
    "    renderMessage({ role: 'user', content: userContent });",
    "    if (!safeString(activeChatId)) {",
    "        activeChatId = safeString(sessionId) || `chat-${Date.now()}`;",
    "    }",
    "    chatHistory.push({",
    "        id: `u-${Date.now()}`,",
    "        role: 'user',",
    "        content: userContent,",
    "        createdAt: Date.now(),",
    "        status: 'complete',",
    "        toolCalls: [],",
    "    });",
    "    syncActiveChatSidebarEntry();",
    "    void persistActiveChat({ quiet: true });",
    ""
].join("\n");
