/* app.js lines 21001-22000 */
export default [
    "                <button type=\"button\" class=\"module-item-btn\" data-lab-action=\"export\">Export</button>",
    "            </div>",
    "        </div>",
    "        <div class=\"module-wb-main-grid module-wb-main-grid-lab3d\">",
    "            <section class=\"module-wb-stage-card\">",
    "                <div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">CAD Surface</span><span class=\"module-wb-stage-meta\" data-lab-status></span></div>",
    "                <canvas class=\"module-wb-canvas-lab3d\" data-lab-canvas width=\"${escapeHtml(String(wb.canvasWidth))}\" height=\"${escapeHtml(String(wb.canvasHeight))}\"></canvas>",
    "                <p class=\"module-wb-hint\">Use Select to move. Other tools draw shapes.</p>",
    "            </section>",
    "            <aside class=\"module-wb-inspector-card\" data-lab-inspector></aside>",
    "        </div>",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const tools = [",
    "        { id: 'select', icon: 'ph-cursor-click', label: 'Select' },",
    "        { id: 'rect', icon: 'ph-rectangle', label: 'Rect' },",
    "        { id: 'circle', icon: 'ph-circle', label: 'Circle' },",
    "        { id: 'line', icon: 'ph-line-segment', label: 'Line' },",
    "    ];",
    "    const toolsEl = shell.querySelector('[data-lab-tools]');",
    "    const canvas = shell.querySelector('[data-lab-canvas]');",
    "    const inspector = shell.querySelector('[data-lab-inspector]');",
    "    const status = shell.querySelector('[data-lab-status]');",
    "    const gridInput = shell.querySelector('[data-lab-grid]');",
    "    const ctx = canvas instanceof HTMLCanvasElement ? canvas.getContext('2d') : null;",
    "",
    "    const selectedShape = () => moduleLab3dShapeById(wb, wb.selectedId);",
    "    const point = (event) => {",
    "        const raw = moduleWorkbenchPointFromEvent(canvas, event);",
    "        const grid = Math.max(4, Number(wb.grid) || 24);",
    "        const x = wb.snap ? Math.round(raw.x / grid) * grid : raw.x;",
    "        const y = wb.snap ? Math.round(raw.y / grid) * grid : raw.y;",
    "        return { x: moduleWorkbenchClamp(x, 0, canvas.width), y: moduleWorkbenchClamp(y, 0, canvas.height) };",
    "    };",
    "    const drawShape = (shape, selected = false, ghost = false) => {",
    "        if (!ctx || !shape) return;",
    "        const type = safeString(shape.type);",
    "        const color = /^#[0-9a-f]{6}$/i.test(safeString(shape.color)) ? safeString(shape.color) : moduleLab3dDefaultColor(type);",
    "        ctx.save();",
    "        ctx.strokeStyle = selected ? '#f7fbff' : color;",
    "        ctx.fillStyle = color;",
    "        ctx.globalAlpha = ghost ? 0.34 : 0.78;",
    "        ctx.lineWidth = selected ? 2.2 : 1.3;",
    "        if (type === 'line') {",
    "            ctx.beginPath();",
    "            ctx.moveTo(Number(shape.x) || 0, Number(shape.y) || 0);",
    "            ctx.lineTo(Number(shape.x2) || 0, Number(shape.y2) || 0);",
    "            ctx.stroke();",
    "        } else if (type === 'circle') {",
    "            const cx = (Number(shape.x) || 0) + ((Number(shape.w) || 0) / 2);",
    "            const cy = (Number(shape.y) || 0) + ((Number(shape.h) || 0) / 2);",
    "            const r = Math.max(3, Math.max(Number(shape.w) || 0, Number(shape.h) || 0) / 2);",
    "            ctx.beginPath();",
    "            ctx.arc(cx, cy, r, 0, Math.PI * 2);",
    "            ctx.fill();",
    "            ctx.stroke();",
    "        } else {",
    "            ctx.beginPath();",
    "            ctx.rect(Number(shape.x) || 0, Number(shape.y) || 0, Math.max(1, Number(shape.w) || 0), Math.max(1, Number(shape.h) || 0));",
    "            ctx.fill();",
    "            ctx.stroke();",
    "        }",
    "        ctx.restore();",
    "    };",
    "    const renderInspector = () => {",
    "        if (!inspector) return;",
    "        const shape = selectedShape();",
    "        if (!shape) {",
    "            const totals = wb.shapes.reduce((acc, item) => {",
    "                const m = moduleLab3dMetrics(item);",
    "                acc.area += m.area;",
    "                acc.volume += m.volume;",
    "                return acc;",
    "            }, { area: 0, volume: 0 });",
    "            inspector.innerHTML = `<h4>Inspector</h4><p class=\"module-wb-mini-note\">Select a shape to edit details.</p><div class=\"module-wb-metrics\"><div><span>Bodies</span><strong>${wb.shapes.length}</strong></div><div><span>Area</span><strong>${totals.area.toFixed(1)} ${escapeHtml(wb.units)}^2</strong></div><div><span>Volume</span><strong>${totals.volume.toFixed(1)} ${escapeHtml(wb.units)}^3</strong></div></div>`;",
    "            return;",
    "        }",
    "        const m = moduleLab3dMetrics(shape);",
    "        inspector.innerHTML = `<h4>${escapeHtml(safeString(shape.label) || 'Shape')}</h4><div class=\"module-wb-field-grid\"><label class=\"module-wb-field\">Label<input type=\"text\" data-shape-prop=\"label\" value=\"${escapeHtml(safeString(shape.label))}\" /></label><label class=\"module-wb-field\">Color<input type=\"color\" data-shape-prop=\"color\" value=\"${escapeHtml(/^#[0-9a-f]{6}$/i.test(safeString(shape.color)) ? safeString(shape.color) : moduleLab3dDefaultColor(shape.type))}\" /></label><label class=\"module-wb-field\">X<input type=\"number\" data-shape-prop=\"x\" value=\"${Math.round(Number(shape.x) || 0)}\" /></label><label class=\"module-wb-field\">Y<input type=\"number\" data-shape-prop=\"y\" value=\"${Math.round(Number(shape.y) || 0)}\" /></label>${safeString(shape.type) === 'line' ? `<label class=\"module-wb-field\">End X<input type=\"number\" data-shape-prop=\"x2\" value=\"${Math.round(Number(shape.x2) || 0)}\" /></label><label class=\"module-wb-field\">End Y<input type=\"number\" data-shape-prop=\"y2\" value=\"${Math.round(Number(shape.y2) || 0)}\" /></label>` : `<label class=\"module-wb-field\">Width<input type=\"number\" data-shape-prop=\"w\" value=\"${Math.round(Number(shape.w) || 0)}\" /></label><label class=\"module-wb-field\">Height<input type=\"number\" data-shape-prop=\"h\" value=\"${Math.round(Number(shape.h) || 0)}\" /></label>`}<label class=\"module-wb-field\">Depth<input type=\"number\" min=\"0\" max=\"200\" data-shape-prop=\"depth\" value=\"${Math.round(Number(shape.depth) || 0)}\" /></label></div><div class=\"module-wb-inspector-actions\"><button type=\"button\" class=\"module-item-btn\" data-shape-action=\"duplicate\">Duplicate</button><button type=\"button\" class=\"module-item-btn\" data-shape-action=\"delete\">Delete</button></div><div class=\"module-wb-metrics\"><div><span>Area</span><strong>${m.area.toFixed(1)}</strong></div><div><span>Perimeter</span><strong>${m.perimeter.toFixed(1)}</strong></div><div><span>Volume</span><strong>${m.volume.toFixed(1)}</strong></div></div>`;",
    "    };",
    "    const render = () => {",
    "        if (!ctx || !(canvas instanceof HTMLCanvasElement)) return;",
    "        toolsEl.innerHTML = tools.map((tool) => `<button type=\"button\" class=\"module-wb-tool-btn${safeString(wb.tool) === tool.id ? ' active' : ''}\" data-lab-tool=\"${tool.id}\"><i class=\"ph ${tool.icon}\"></i><span>${tool.label}</span></button>`).join('');",
    "        ctx.clearRect(0, 0, canvas.width, canvas.height);",
    "        ctx.strokeStyle = 'rgba(164, 198, 244, 0.12)';",
    "        for (let x = 0; x <= canvas.width; x += Number(wb.grid) || 24) { ctx.beginPath(); ctx.moveTo(x + 0.5, 0); ctx.lineTo(x + 0.5, canvas.height); ctx.stroke(); }",
    "        for (let y = 0; y <= canvas.height; y += Number(wb.grid) || 24) { ctx.beginPath(); ctx.moveTo(0, y + 0.5); ctx.lineTo(canvas.width, y + 0.5); ctx.stroke(); }",
    "        wb.shapes.forEach((shape) => drawShape(shape, safeString(shape.id) === safeString(wb.selectedId)));",
    "        if (wb.draft) drawShape(wb.draft, false, true);",
    "        renderInspector();",
    "        status.textContent = `${wb.shapes.length} shapes | ${wb.snap ? `snap ${wb.grid}px` : 'free'}${selectedShape() ? ` | selected ${safeString(selectedShape().label)}` : ''}`;",
    "    };",
    "",
    "    shell.addEventListener('click', (event) => {",
    "        const target = event.target instanceof Element ? event.target.closest('[data-lab-tool], [data-lab-action], [data-shape-action]') : null;",
    "        if (!target) return;",
    "        const tool = safeString(target.dataset.labTool);",
    "        const action = safeString(target.dataset.labAction || target.dataset.shapeAction).toLowerCase();",
    "        if (tool) wb.tool = tool;",
    "        if (action === 'snap') wb.snap = !wb.snap;",
    "        if (action === 'clear') { wb.shapes = []; wb.selectedId = ''; wb.draft = null; wb.dragStart = null; }",
    "        if (action === 'export') moduleWorkbenchCopyJson({ units: wb.units, grid: wb.grid, shapes: wb.shapes }, '3D Lab CAD JSON');",
    "        if (action === 'duplicate' && selectedShape()) { const copy = { ...selectedShape(), id: `shape-${wb.nextId++}`, label: `${safeString(selectedShape().label)} Copy`, x: (Number(selectedShape().x) || 0) + 18, y: (Number(selectedShape().y) || 0) + 18 }; if (safeString(copy.type) === 'line') { copy.x2 = (Number(copy.x2) || 0) + 18; copy.y2 = (Number(copy.y2) || 0) + 18; } wb.shapes.push(copy); wb.selectedId = copy.id; }",
    "        if (action === 'delete' && selectedShape()) { wb.shapes = wb.shapes.filter((shape) => safeString(shape.id) !== safeString(wb.selectedId)); wb.selectedId = ''; }",
    "        render();",
    "    });",
    "    if (gridInput) gridInput.addEventListener('input', () => { wb.grid = moduleWorkbenchClamp(Number(gridInput.value) || 24, 8, 64); render(); });",
    "    if (inspector) inspector.addEventListener('input', (event) => {",
    "        const target = event.target;",
    "        if (!(target instanceof HTMLInputElement)) return;",
    "        const shape = selectedShape();",
    "        if (!shape) return;",
    "        const prop = safeString(target.dataset.shapeProp);",
    "        if (!prop) return;",
    "        if (prop === 'label') shape.label = safeString(target.value).slice(0, 60);",
    "        else if (prop === 'color' && /^#[0-9a-f]{6}$/i.test(safeString(target.value))) shape.color = safeString(target.value);",
    "        else shape[prop] = Number.isFinite(Number(target.value)) ? Number(target.value) : shape[prop];",
    "        render();",
    "    });",
    "    if (canvas instanceof HTMLCanvasElement) {",
    "        canvas.addEventListener('pointerdown', (event) => {",
    "            const p = point(event);",
    "            if (safeString(wb.tool) === 'select') {",
    "                const hit = [...wb.shapes].reverse().find((shape) => moduleLab3dHitShape(shape, p)) || null;",
    "                wb.selectedId = safeString(hit?.id);",
    "                wb.dragStart = hit ? { x: p.x, y: p.y, origin: { ...hit } } : null;",
    "                render();",
    "                return;",
    "            }",
    "            wb.drawing = true;",
    "            wb.draft = {",
    "                id: 'draft',",
    "                type: wb.tool,",
    "                label: 'Draft',",
    "                color: moduleLab3dDefaultColor(wb.tool),",
    "                depth: 12,",
    "                startX: p.x,",
    "                startY: p.y,",
    "                x: p.x,",
    "                y: p.y,",
    "                w: 0,",
    "                h: 0,",
    "                x2: p.x,",
    "                y2: p.y,",
    "            };",
    "            wb.selectedId = '';",
    "            render();",
    "        });",
    "        canvas.addEventListener('pointermove', (event) => {",
    "            const p = point(event);",
    "            if (wb.drawing && wb.draft) {",
    "                if (safeString(wb.draft.type) === 'line') {",
    "                    wb.draft.x2 = p.x;",
    "                    wb.draft.y2 = p.y;",
    "                } else {",
    "                    const sx = Number(wb.draft.startX) || Number(wb.draft.x) || 0;",
    "                    const sy = Number(wb.draft.startY) || Number(wb.draft.y) || 0;",
    "                    wb.draft.x = Math.min(sx, p.x);",
    "                    wb.draft.y = Math.min(sy, p.y);",
    "                    wb.draft.w = Math.abs(p.x - sx);",
    "                    wb.draft.h = Math.abs(p.y - sy);",
    "                    wb.draft.x2 = p.x;",
    "                    wb.draft.y2 = p.y;",
    "                }",
    "                render();",
    "                return;",
    "            }",
    "            if (wb.dragStart && safeString(wb.tool) === 'select') { const shape = selectedShape(); if (!shape) return; const dx = p.x - wb.dragStart.x; const dy = p.y - wb.dragStart.y; shape.x = (Number(wb.dragStart.origin.x) || 0) + dx; shape.y = (Number(wb.dragStart.origin.y) || 0) + dy; if (safeString(shape.type) === 'line') { shape.x2 = (Number(wb.dragStart.origin.x2) || 0) + dx; shape.y2 = (Number(wb.dragStart.origin.y2) || 0) + dy; } render(); }",
    "        });",
    "        const finish = () => {",
    "            if (wb.drawing && wb.draft) {",
    "                const draft = wb.draft;",
    "                const lineLength = Math.hypot((Number(draft.x2) || 0) - (Number(draft.x) || 0), (Number(draft.y2) || 0) - (Number(draft.y) || 0));",
    "                const keep = safeString(draft.type) === 'line'",
    "                    ? lineLength > 6",
    "                    : (Math.max(Number(draft.w) || 0, Number(draft.h) || 0) > 6);",
    "                if (keep) {",
    "                    const shape = {",
    "                        ...draft,",
    "                        id: `shape-${wb.nextId++}`,",
    "                        label: `${safeString(draft.type)} ${wb.nextId - 1}`,",
    "                    };",
    "                    delete shape.startX;",
    "                    delete shape.startY;",
    "                    wb.shapes.push(shape);",
    "                    wb.selectedId = shape.id;",
    "                }",
    "            }",
    "            wb.drawing = false;",
    "            wb.draft = null;",
    "            wb.dragStart = null;",
    "            render();",
    "        };",
    "        canvas.addEventListener('pointerup', finish);",
    "        canvas.addEventListener('pointerleave', finish);",
    "    }",
    "    render();",
    "}",
    "",
    "function moduleWorkbenchPushLog(bucket, message, tone = 'ok', cap = 80, prefix = 'log') {",
    "    if (!Array.isArray(bucket)) return;",
    "    bucket.unshift({",
    "        id: moduleWorkbenchMakeId(prefix),",
    "        time: moduleWorkbenchTimeStamp(),",
    "        tone,",
    "        message: safeString(message),",
    "    });",
    "    if (bucket.length > cap) bucket.length = cap;",
    "}",
    "",
    "function moduleWorkbenchEnsureLiteGraphNodeType(LiteGraph) {",
    "    if (!LiteGraph?.registerNodeType) return;",
    "    if (LiteGraph.registered_node_types?.['thomas/flow_block']) return;",
    "    class ThomasFlowBlock extends LiteGraph.LGraphNode {",
    "        constructor() {",
    "            super();",
    "            this.title = 'Flow Block';",
    "            this.addInput('in', 'flow');",
    "            this.addOutput('out', 'flow');",
    "            this.properties = {",
    "                blockType: 'custom',",
    "                kind: 'action',",
    "                notes: '',",
    "                approval: false,",
    "            };",
    "            this.size = [210, 86];",
    "        }",
    "    }",
    "    LiteGraph.registerNodeType('thomas/flow_block', ThomasFlowBlock);",
    "}",
    "",
    "function moduleWorkbenchLiteGraphLinks(graphDataRaw) {",
    "    const graphData = graphDataRaw && typeof graphDataRaw === 'object' ? graphDataRaw : {};",
    "    const linksRaw = graphData.links;",
    "    if (!linksRaw || typeof linksRaw !== 'object') return [];",
    "    return Object.values(linksRaw)",
    "        .map((entry) => (Array.isArray(entry) ? entry : []))",
    "        .filter((entry) => entry.length >= 4)",
    "        .map((entry) => ({",
    "            originId: Number(entry[1]) || 0,",
    "            targetId: Number(entry[3]) || 0,",
    "        }))",
    "        .filter((entry) => entry.originId > 0 && entry.targetId > 0);",
    "}",
    "",
    "function moduleWorkbenchFlowToN8n(graphDataRaw) {",
    "    const graphData = graphDataRaw && typeof graphDataRaw === 'object' ? graphDataRaw : {};",
    "    const nodesRaw = Array.isArray(graphData.nodes) ? graphData.nodes : [];",
    "    const nodes = nodesRaw.map((nodeRaw, index) => {",
    "        const node = nodeRaw && typeof nodeRaw === 'object' ? nodeRaw : {};",
    "        const id = String(Number(node.id) || (index + 1));",
    "        const title = safeString(node.title) || `Flow ${index + 1}`;",
    "        const name = `${title} [${id}]`;",
    "        return {",
    "            _id: id,",
    "            id,",
    "            name,",
    "            type: 'n8n-nodes-base.noOp',",
    "            typeVersion: 1,",
    "            position: [",
    "                Number(node.pos?.[0]) || ((index + 1) * 180),",
    "                Number(node.pos?.[1]) || ((index + 1) * 80),",
    "            ],",
    "            parameters: {",
    "                kind: safeString(node.properties?.kind) || 'action',",
    "                blockType: safeString(node.properties?.blockType) || 'custom',",
    "                notes: safeString(node.properties?.notes),",
    "                approval: Boolean(node.properties?.approval),",
    "            },",
    "        };",
    "    });",
    "    const byId = new Map(nodes.map((node) => [node._id, node]));",
    "    const links = moduleWorkbenchLiteGraphLinks(graphData);",
    "    const connectionMap = new Map();",
    "    links.forEach((edge) => {",
    "        const from = byId.get(String(edge.originId));",
    "        const to = byId.get(String(edge.targetId));",
    "        if (!from || !to) return;",
    "        if (!connectionMap.has(from.name)) connectionMap.set(from.name, []);",
    "        connectionMap.get(from.name).push({",
    "            node: to.name,",
    "            type: 'main',",
    "            index: 0,",
    "        });",
    "    });",
    "    const connections = {};",
    "    nodes.forEach((node) => {",
    "        const outputs = connectionMap.get(node.name) || [];",
    "        if (!outputs.length) return;",
    "        connections[node.name] = {",
    "            main: [outputs],",
    "        };",
    "    });",
    "    return {",
    "        name: 'Thomas Flow Export',",
    "        active: false,",
    "        settings: {},",
    "        nodes: nodes.map((node) => ({",
    "            id: node.id,",
    "            name: node.name,",
    "            type: node.type,",
    "            typeVersion: node.typeVersion,",
    "            position: node.position,",
    "            parameters: node.parameters,",
    "        })),",
    "        connections,",
    "    };",
    "}",
    "",
    "function moduleWorkbenchFlowToNodeRed(graphDataRaw) {",
    "    const graphData = graphDataRaw && typeof graphDataRaw === 'object' ? graphDataRaw : {};",
    "    const nodesRaw = Array.isArray(graphData.nodes) ? graphData.nodes : [];",
    "    const tabId = `tab_${Date.now().toString(36)}`;",
    "    const nodes = nodesRaw.map((nodeRaw, index) => {",
    "        const node = nodeRaw && typeof nodeRaw === 'object' ? nodeRaw : {};",
    "        const id = `n_${String(Number(node.id) || (index + 1))}`;",
    "        return {",
    "            id,",
    "            type: 'function',",
    "            z: tabId,",
    "            name: safeString(node.title) || `Flow ${index + 1}`,",
    "            func: `// ${safeString(node.properties?.kind) || 'action'}\\nreturn msg;`,",
    "            outputs: 1,",
    "            noerr: 0,",
    "            initialize: '',",
    "            finalize: '',",
    "            libs: [],",
    "            x: Number(node.pos?.[0]) || ((index + 1) * 200),",
    "            y: Number(node.pos?.[1]) || ((index + 1) * 80),",
    "            wires: [[]],",
    "        };",
    "    });",
    "    const byId = new Map(nodes.map((node) => [node.id.replace(/^n_/, ''), node]));",
    "    moduleWorkbenchLiteGraphLinks(graphData).forEach((edge) => {",
    "        const from = byId.get(String(edge.originId));",
    "        const to = byId.get(String(edge.targetId));",
    "        if (!from || !to) return;",
    "        from.wires[0].push(to.id);",
    "    });",
    "    return [",
    "        { id: tabId, type: 'tab', label: 'Thomas Flow', disabled: false, info: '' },",
    "        ...nodes,",
    "    ];",
    "}",
    "",
    "function moduleAutomationCoerceValue(rawValue) {",
    "    const text = safeString(rawValue).trim();",
    "    if (!text) return '';",
    "    if (text === 'true') return true;",
    "    if (text === 'false') return false;",
    "    if (text === 'null') return null;",
    "    if (!Number.isNaN(Number(text)) && text !== '') return Number(text);",
    "    if ((text.startsWith('{') && text.endsWith('}')) || (text.startsWith('[') && text.endsWith(']'))) {",
    "        try {",
    "            return JSON.parse(text);",
    "        } catch (_error) {}",
    "    }",
    "    return text;",
    "}",
    "",
    "function moduleAutomationCompare(actual, opRaw, expectedRaw) {",
    "    const op = safeString(opRaw) || 'equals';",
    "    const expected = moduleAutomationCoerceValue(expectedRaw);",
    "    if (op === 'equals') return actual === expected;",
    "    if (op === 'not_equals') return actual !== expected;",
    "    if (op === 'contains') return safeString(actual).toLowerCase().includes(safeString(expected).toLowerCase());",
    "    if (op === 'not_contains') return !safeString(actual).toLowerCase().includes(safeString(expected).toLowerCase());",
    "    if (op === 'gt') return Number(actual) > Number(expected);",
    "    if (op === 'lt') return Number(actual) < Number(expected);",
    "    if (op === 'exists') return typeof actual !== 'undefined' && actual !== null && safeString(actual) !== '';",
    "    return actual === expected;",
    "}",
    "",
    "function moduleAutomationApplyTemplate(templateRaw, dataRaw) {",
    "    const template = safeString(templateRaw);",
    "    const data = dataRaw && typeof dataRaw === 'object' ? dataRaw : {};",
    "    if (!template) return '';",
    "    return template.replace(/\\{\\{\\s*([a-zA-Z0-9_.-]+)\\s*\\}\\}/g, (_match, path) => {",
    "        const value = moduleWorkbenchPathGet(data, safeString(path));",
    "        if (value === null || typeof value === 'undefined') return '';",
    "        if (typeof value === 'object') return JSON.stringify(value);",
    "        return safeString(value);",
    "    });",
    "}",
    "",
    "function moduleAutomationExecuteNode(nodeRaw, payloadRaw, outputsRaw) {",
    "    const node = nodeRaw && typeof nodeRaw === 'object' ? nodeRaw : {};",
    "    const outputs = Array.isArray(outputsRaw) ? outputsRaw : [];",
    "    const props = node.properties && typeof node.properties === 'object' ? node.properties : {};",
    "    const blockType = safeString(props.blockType);",
    "    const kind = safeString(props.kind);",
    "    const payload = moduleWorkbenchDeepClone(payloadRaw && typeof payloadRaw === 'object' ? payloadRaw : {});",
    "    const data = payload && typeof payload === 'object' ? payload : {};",
    "    const result = {",
    "        pass: true,",
    "        pendingApproval: false,",
    "        note: '',",
    "        payload: data,",
    "    };",
    "",
    "    if (blockType === 'if_else') {",
    "        const field = safeString(props.field) || 'priority';",
    "        const op = safeString(props.op) || 'equals';",
    "        const actual = moduleWorkbenchPathGet(data, field);",
    "        result.pass = moduleAutomationCompare(actual, op, props.value);",
    "        result.note = result.pass ? `Condition passed (${field} ${op}).` : `Condition failed (${field} ${op}).`;",
    "        return result;",
    "    }",
    "",
    "    if (blockType === 'approval_gate') {",
    "        const autoApprove = Boolean(props.autoApprove);",
    "        if (!autoApprove) {",
    "            result.pendingApproval = true;",
    "            result.pass = false;",
    "            result.note = 'Waiting for human approval.';",
    "            return result;",
    "        }",
    "        result.note = 'Auto-approved.';",
    "        return result;",
    "    }",
    "",
    "    if (blockType === 'run_script') {",
    "        const operation = safeString(props.operation) || 'set';",
    "        const field = safeString(props.field) || 'result.value';",
    "        if (operation === 'set') {",
    "            moduleWorkbenchPathSet(data, field, moduleAutomationCoerceValue(props.value));",
    "            result.note = `Set ${field}.`;",
    "        } else if (operation === 'inc') {",
    "            const current = Number(moduleWorkbenchPathGet(data, field) || 0);",
    "            const inc = Number(moduleAutomationCoerceValue(props.value) || 1);",
    "            moduleWorkbenchPathSet(data, field, current + inc);",
    "            result.note = `Incremented ${field} by ${inc}.`;",
    "        } else if (operation === 'append_tag') {",
    "            const current = moduleWorkbenchPathGet(data, field);",
    "            const next = Array.isArray(current) ? [...current, safeString(props.value)] : [safeString(props.value)];",
    "            moduleWorkbenchPathSet(data, field, next);",
    "            result.note = `Appended tag on ${field}.`;",
    "        } else if (operation === 'delete') {",
    "            moduleWorkbenchPathDelete(data, field);",
    "            result.note = `Deleted ${field}.`;",
    "        } else {",
    "            result.note = `No-op operation: ${operation}.`;",
    "        }",
    "        return result;",
    "    }",
    "",
    "    if (blockType === 'send_message') {",
    "        const template = safeString(props.template) || 'Workflow message: {{subject}}';",
    "        const text = moduleAutomationApplyTemplate(template, data);",
    "        outputs.push({",
    "            channel: safeString(props.channel) || 'inbox',",
    "            text,",
    "        });",
    "        result.note = 'Message action generated.';",
    "        return result;",
    "    }",
    "",
    "    if (kind === 'trigger') {",
    "        result.note = 'Trigger emitted payload.';",
    "        return result;",
    "    }",
    "    if (kind === 'logic') {",
    "        result.note = 'Logic gate passed.';",
    "        return result;",
    "    }",
    "    if (kind === 'action') {",
    "        result.note = 'Action executed.';",
    "        return result;",
    "    }",
    "    result.note = 'Node executed.';",
    "    return result;",
    "}",
    "",
    "function moduleAutomationRunGraphData(graphDataRaw, inputRaw) {",
    "    const graphData = graphDataRaw && typeof graphDataRaw === 'object' ? graphDataRaw : {};",
    "    const nodes = Array.isArray(graphData.nodes) ? graphData.nodes : [];",
    "    const edges = moduleWorkbenchLiteGraphLinks(graphData);",
    "    const nodeMap = new Map();",
    "    const adjacency = new Map();",
    "    const indegree = new Map();",
    "    nodes.forEach((node) => {",
    "        const id = Number(node?.id) || 0;",
    "        if (!id) return;",
    "        nodeMap.set(id, node);",
    "        adjacency.set(id, []);",
    "        indegree.set(id, 0);",
    "    });",
    "    edges.forEach((edge) => {",
    "        const from = Number(edge.originId) || 0;",
    "        const to = Number(edge.targetId) || 0;",
    "        if (!nodeMap.has(from) || !nodeMap.has(to)) return;",
    "        adjacency.get(from).push(to);",
    "        indegree.set(to, Number(indegree.get(to) || 0) + 1);",
    "    });",
    "",
    "    const starts = nodes",
    "        .map((node) => Number(node?.id) || 0)",
    "        .filter((id) => id && (",
    "            safeString(nodeMap.get(id)?.properties?.kind) === 'trigger'",
    "            || Number(indegree.get(id) || 0) === 0",
    "        ));",
    "    const queue = starts.map((id) => ({ id, payload: moduleWorkbenchDeepClone(inputRaw && typeof inputRaw === 'object' ? inputRaw : {}) }));",
    "    const outputs = [];",
    "    const steps = [];",
    "    const guard = new Map();",
    "    let iterations = 0;",
    "",
    "    while (queue.length && iterations < 500) {",
    "        iterations += 1;",
    "        const item = queue.shift();",
    "        if (!item) continue;",
    "        const id = Number(item.id) || 0;",
    "        const node = nodeMap.get(id);",
    "        if (!node) continue;",
    "        const key = String(id);",
    "        const seen = Number(guard.get(key) || 0) + 1;",
    "        guard.set(key, seen);",
    "        if (seen > 12) continue;",
    "",
    "        const run = moduleAutomationExecuteNode(node, item.payload, outputs);",
    "        steps.push({",
    "            id,",
    "            title: safeString(node.title) || `Node ${id}`,",
    "            pass: Boolean(run.pass),",
    "            pendingApproval: Boolean(run.pendingApproval),",
    "            note: safeString(run.note),",
    "            payload: moduleWorkbenchDeepClone(run.payload),",
    "        });",
    "        if (!run.pass) continue;",
    "        const children = adjacency.get(id) || [];",
    "        children.forEach((childId) => {",
    "            queue.push({ id: childId, payload: moduleWorkbenchDeepClone(run.payload) });",
    "        });",
    "    }",
    "",
    "    const lastPayload = steps.length ? moduleWorkbenchDeepClone(steps[steps.length - 1].payload) : moduleWorkbenchDeepClone(inputRaw && typeof inputRaw === 'object' ? inputRaw : {});",
    "    return {",
    "        steps,",
    "        outputs,",
    "        finalPayload: lastPayload,",
    "        nodeCount: nodes.length,",
    "        edgeCount: edges.length,",
    "    };",
    "}",
    "",
    "function moduleRenderWorkbenchAutomationsOss(container, wb) {",
    "    if (!container || !wb) return false;",
    "    if (wb.ossError) return false;",
    "    if (!wb.ossReady || !window.LiteGraph) {",
    "        moduleWorkbenchRenderEngineLoading(",
    "            container,",
    "            'Automation Graph Engine',",
    "            'LiteGraph drag/drop canvas with node links and run traces.',",
    "            'Loading LiteGraph...',",
    "            'If loading fails, fallback list mode will open automatically.',",
    "        );",
    "        if (!wb.ossLoading) {",
    "            wb.ossLoading = true;",
    "            void moduleWorkbenchLoadLiteGraph().then(() => {",
    "                wb.ossReady = true;",
    "                wb.ossLoading = false;",
    "                wb.ossError = '';",
    "                moduleWorkbenchRefreshMode('automations');",
    "            }).catch((error) => {",
    "                wb.ossLoading = false;",
    "                wb.ossReady = false;",
    "                wb.ossError = safeString(error?.message) || 'Failed to load LiteGraph.';",
    "                notifyUser('LiteGraph failed to load, using fallback flow list.', { tone: 'warn', durationMs: 2300, debugKind: 'automations' });",
    "                moduleWorkbenchRefreshMode('automations');",
    "            });",
    "        }",
    "        return true;",
    "    }",
    "",
    "    const LiteGraph = window.LiteGraph;",
    "    moduleWorkbenchEnsureLiteGraphNodeType(LiteGraph);",
    "    if (!Array.isArray(wb.logs)) wb.logs = [];",
    "    wb.runInput = safeString(wb.runInput) || '{\\n  \"subject\": \"Ops status\",\\n  \"priority\": \"high\"\\n}';",
    "    if (!wb.runReport || typeof wb.runReport !== 'object') wb.runReport = null;",
    "    wb.selectedProjectId = safeString(wb.selectedProjectId);",
    "    wb.selectedNodeId = safeString(wb.selectedNodeId);",
    "",
    "    moduleWorkbenchHeader(container, 'Automation Graph Engine', 'Define orchestration logic for Thomas to execute, then monitor run behavior and approvals.');",
    "    const shell = document.createElement('section');",
    "    shell.className = 'module-wb-shell module-wb-shell-flow-oss';",
    "    shell.innerHTML = `",
    "        <aside class=\"module-wb-side-card\">",
    "            <h4>Block Palette</h4>",
    "            <div class=\"module-wb-palette\" data-flow-palette></div>",
    "            ${moduleWorkbenchRenderProjectControls('automations', 'Flow Projects')}",
    "            <label class=\"module-wb-field module-wb-field-wide\">Run Input JSON<textarea rows=\"6\" data-flow-run-input>${escapeHtml(safeString(wb.runInput) || '{\\n  \"subject\": \"Ops status\",\\n  \"priority\": \"high\"\\n}')}</textarea></label>",
    "            <div class=\"module-wb-inspector-actions\">",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"run\">Test Run</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"run_dry\">Dry Run</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"export\">Export</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"export_n8n\">n8n JSON</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"export_nodered\">Node-RED JSON</button>",
    "                <button type=\"button\" class=\"module-item-btn\" data-flow-action=\"reset\">Reset</button>",
    "            </div>",
    "        </aside>",
    "        <section class=\"module-wb-stage-card\">",
    "            <div class=\"module-wb-stage-head\"><span class=\"module-wb-stage-title\">Visual Graph</span><span class=\"module-wb-stage-meta\" data-flow-status></span></div>",
    "            <canvas class=\"module-wb-flow-canvas\" data-flow-canvas></canvas>",
    "            <div class=\"module-wb-log-list\" data-flow-logs></div>",
    "            <div class=\"module-wb-run-report\" data-flow-report></div>",
    "        </section>",
    "        <aside class=\"module-wb-inspector-card\" data-flow-inspector></aside>",
    "        ${moduleWorkbenchRenderOssStack('automations')}",
    "    `;",
    "    container.appendChild(shell);",
    "",
    "    const palette = shell.querySelector('[data-flow-palette]');",
    "    const canvas = shell.querySelector('[data-flow-canvas]');",
    "    const logs = shell.querySelector('[data-flow-logs]');",
    "    const report = shell.querySelector('[data-flow-report]');",
    "    const inspector = shell.querySelector('[data-flow-inspector]');",
    "    const status = shell.querySelector('[data-flow-status]');",
    "    const runInputEl = shell.querySelector('[data-flow-run-input]');",
    "    if (!(palette instanceof HTMLElement) || !(canvas instanceof HTMLCanvasElement) || !(logs instanceof HTMLElement) || !(report instanceof HTMLElement) || !(inspector instanceof HTMLElement) || !(status instanceof HTMLElement)) {",
    "        return false;",
    "    }",
    "",
    "    if (wb.ossGraphCanvas?.setGraph) {",
    "        try {",
    "            wb.ossGraph?.stop?.();",
    "            wb.ossGraphCanvas.setGraph(null, true);",
    "        } catch (_error) {}",
    "    }",
    "",
    "    const graph = new LiteGraph.LGraph();",
    "    const graphCanvas = new LiteGraph.LGraphCanvas(canvas, graph);",
    "    graphCanvas.ds.scale = 0.92;",
    "    graphCanvas.onNodeSelected = (node) => {",
    "        wb.selectedNodeId = safeString(node?.id);",
    "        renderInspector();",
    "    };",
    "    graphCanvas.onNodeDeselected = () => {",
    "        wb.selectedNodeId = '';",
    "        renderInspector();",
    "    };",
    "    graph.start();",
    "",
    "    wb.ossGraph = graph;",
    "    wb.ossGraphCanvas = graphCanvas;",
    "",
    "    const blockDefs = [",
    "        { id: 'schedule_trigger', kind: 'trigger', label: 'Schedule Trigger' },",
    "        { id: 'email_trigger', kind: 'trigger', label: 'New Email Trigger' },",
    "        { id: 'if_else', kind: 'logic', label: 'If / Else' },",
    "        { id: 'approval_gate', kind: 'logic', label: 'Human Approval' },",
    "        { id: 'send_message', kind: 'action', label: 'Send Message' },",
    "        { id: 'run_script', kind: 'action', label: 'Run Script' },",
    "    ];",
    "",
    "    const createNode = (def, pos = [120, 120]) => {",
    "        const node = LiteGraph.createNode('thomas/flow_block');",
    "        if (!node) return null;",
    "        node.title = def.label;",
    "        node.properties.blockType = def.id;",
    "        node.properties.kind = def.kind;",
    "        node.properties.notes = node.properties.notes || '';",
    "        node.properties.approval = Boolean(node.properties.approval);",
    "        node.properties.field = safeString(node.properties.field) || 'priority';",
    "        node.properties.op = safeString(node.properties.op) || 'equals';",
    "        node.properties.value = safeString(node.properties.value) || 'high';",
    "        node.properties.template = safeString(node.properties.template) || 'Workflow alert: {{subject}}';",
    "        node.properties.operation = safeString(node.properties.operation) || 'set';",
    "        node.properties.channel = safeString(node.properties.channel) || 'inbox';",
    "        node.properties.autoApprove = Boolean(node.properties.autoApprove);",
    "        node.pos = [...pos];",
    "        return node;",
    "    };",
    "    const graphNodes = () => Array.isArray(graph?._nodes) ? graph._nodes : [];",
    "    const selectedNode = () => graphNodes().find((node) => safeString(node?.id) === safeString(wb.selectedNodeId)) || null;",
    "    const remember = () => {",
    "        try {",
    "            wb.graphData = graph.serialize();",
    "        } catch (_error) {}",
    "    };",
    "    const parseRunInput = () => {",
    "        const raw = safeString(runInputEl instanceof HTMLTextAreaElement ? runInputEl.value : wb.runInput);",
    "        wb.runInput = raw;",
    "        if (!raw.trim()) return {};",
    "        try {",
    "            const parsed = JSON.parse(raw);",
    "            if (parsed && typeof parsed === 'object') return parsed;",
    "            return { value: parsed };",
    "        } catch (_error) {",
    "            return { _raw: raw };",
    "        }",
    "    };",
    "    const renderProjectSelect = () => {",
    "        const select = shell.querySelector('select[data-wb-project-select=\"automations\"]');",
    "        if (!(select instanceof HTMLSelectElement)) return;",
    "        const rows = moduleWorkbenchProjectList('automations');",
    "        const current = safeString(wb.selectedProjectId);",
    "        select.innerHTML = `<option value=\"\">Select project</option>${rows.map((row) => `<option value=\"${escapeHtml(safeString(row.id))}\">${escapeHtml(`${safeString(row.name)} (${new Date(Number(row.updatedAt) || Date.now()).toLocaleString()})`)}</option>`).join('')}`;",
    "        select.value = rows.some((row) => safeString(row.id) === current) ? current : '';",
    "    };",
    "    const renderLogs = () => {",
    "        logs.innerHTML = wb.logs.length",
    "            ? wb.logs.slice(0, 14).map((entry) => `<article class=\"module-wb-log-item ${moduleToneClass(entry.tone) || 'ok'}\"><span>${escapeHtml(safeString(entry.time))}</span><p>${escapeHtml(safeString(entry.message))}</p></article>`).join('')",
    "            : '<div class=\"module-wb-ghost\">No run logs yet.</div>';",
    "    };",
    "    const renderReport = () => {",
    "        const run = wb.runReport && typeof wb.runReport === 'object' ? wb.runReport : null;",
    "        if (!run) {",
    "            report.innerHTML = '<div class=\"module-wb-ghost\">Run report appears here after Test Run.</div>';",
    "            return;",
    "        }",
    "        const pending = run.steps.filter((step) => Boolean(step.pendingApproval)).length;",
    "        report.innerHTML = `",
    "            <div class=\"module-wb-metrics\">",
    "                <div><span>Nodes</span><strong>${Number(run.nodeCount) || 0}</strong></div>",
    "                <div><span>Edges</span><strong>${Number(run.edgeCount) || 0}</strong></div>",
    "                <div><span>Pending</span><strong>${pending}</strong></div>",
    "            </div>",
    "            <div class=\"module-wb-log-list\">",
    "                ${run.steps.slice(0, 20).map((step) => `<article class=\"module-wb-log-item ${step.pendingApproval ? 'warn' : (step.pass ? 'ok' : 'error')}\"><span>${escapeHtml(safeString(step.title))}</span><p>${escapeHtml(safeString(step.note))}</p></article>`).join('')}",
    "            </div>",
    "            <div class=\"module-wb-field module-wb-field-wide\">",
    "                <label>Final Payload</label>",
    "                <textarea rows=\"7\" readonly>${escapeHtml(JSON.stringify(run.finalPayload || {}, null, 2))}</textarea>",
    "            </div>",
    "            <div class=\"module-wb-field module-wb-field-wide\">",
    "                <label>Generated Outputs</label>",
    "                <textarea rows=\"6\" readonly>${escapeHtml(JSON.stringify(run.outputs || [], null, 2))}</textarea>",
    "            </div>",
    "        `;",
    "    };",
    "    const renderStatus = () => {",
    "        const links = graph?.links ? Object.keys(graph.links).length : 0;",
    "        status.textContent = `${graphNodes().length} nodes | ${links} links`;",
    "    };",
    "    const renderInspector = () => {",
    "        const node = selectedNode();",
    "        if (!node) {",
    "            inspector.innerHTML = `<h4>Inspector</h4><p class=\"module-wb-mini-note\">Select a node on the canvas to edit details.</p><div class=\"module-wb-metrics\"><div><span>Nodes</span><strong>${graphNodes().length}</strong></div><div><span>Links</span><strong>${graph?.links ? Object.keys(graph.links).length : 0}</strong></div><div><span>Approvals</span><strong>${graphNodes().filter((entry) => Boolean(entry?.properties?.approval)).length}</strong></div></div>`;",
    "            return;",
    "        }",
    "        inspector.innerHTML = `",
    "            <h4>${escapeHtml(safeString(node.title) || 'Flow Block')}</h4>",
    "            <div class=\"module-wb-field-grid\">",
    "                <label class=\"module-wb-field\">Label<input type=\"text\" data-flow-prop=\"title\" value=\"${escapeHtml(safeString(node.title))}\" /></label>",
    "                <label class=\"module-wb-field\">Kind<select data-flow-prop=\"kind\">${['trigger', 'logic', 'action'].map((kind) => `<option value=\"${kind}\"${safeString(node.properties?.kind) === kind ? ' selected' : ''}>${kind}</option>`).join('')}</select></label>",
    "                <label class=\"module-wb-field module-wb-field-check\"><input type=\"checkbox\" data-flow-prop=\"approval\" ${node.properties?.approval ? 'checked' : ''} />Require approval</label>",
    "                <label class=\"module-wb-field\">Field<input type=\"text\" data-flow-prop=\"field\" value=\"${escapeHtml(safeString(node.properties?.field) || 'priority')}\" /></label>",
    "                <label class=\"module-wb-field\">Operator<select data-flow-prop=\"op\">${[",
    "                    ['equals', 'Equals'],",
    "                    ['not_equals', 'Not equals'],",
    "                    ['contains', 'Contains'],",
    "                    ['not_contains', 'Not contains'],",
    "                    ['gt', 'Greater than'],",
    "                    ['lt', 'Less than'],",
    "                    ['exists', 'Exists'],",
    "                ].map(([value, label]) => `<option value=\"${value}\"${safeString(node.properties?.op) === value ? ' selected' : ''}>${label}</option>`).join('')}</select></label>",
    "                <label class=\"module-wb-field\">Value<input type=\"text\" data-flow-prop=\"value\" value=\"${escapeHtml(safeString(node.properties?.value))}\" /></label>",
    "                <label class=\"module-wb-field\">Operation<select data-flow-prop=\"operation\">${[",
    "                    ['set', 'Set'],",
].join("\n");
