/* split from part-005.js */
export default [
    "            chatGameBotWrap.style.left = `${CHAT_GAME_DOOR_BOT_MOUNT_LEFT}px`;",
    "            chatGameBotWrap.style.top = 'auto';",
    "            chatGameBotWrap.style.bottom = `${CHAT_GAME_DOOR_BOT_MOUNT_BOTTOM}px`;",
    "            chatGameBotWrap.style.transform = `translate3d(${doorOffsetX.toFixed(2)}px, 0px, 0px) rotate(${botRotate.toFixed(2)}deg) scale(${botScale.toFixed(3)})`;",
    "        } else {",
    "            if (botPlayfieldHost instanceof HTMLElement && chatGameBotWrap.parentElement !== botPlayfieldHost) {",
    "                botPlayfieldHost.appendChild(chatGameBotWrap);",
    "            }",
    "            chatGameBotWrap.style.left = '0px';",
    "            chatGameBotWrap.style.top = '0px';",
    "            chatGameBotWrap.style.bottom = 'auto';",
    "            chatGameBotWrap.style.transform = `translate3d(${botX.toFixed(2)}px, ${botY.toFixed(2)}px, 0px) rotate(${botRotate.toFixed(2)}deg) scale(${botScale.toFixed(3)})`;",
    "        }",
    "        chatGameBotWrap.classList.toggle('visible', Boolean(scene.botVisible));",
    "        chatGameBotWrap.classList.toggle('inside-door', Boolean(scene.botInside));",
    "        chatGameBotWrap.classList.toggle('jetpack-on', activeGame === JETPACK_GAME_ID && Boolean(scene.botJetpack));",
    "        chatGameBotWrap.classList.toggle('dino-ride', isDino);",
    "        if (isDino) {",
    "            chatGameBotWrap.classList.remove('jetpack-on');",
    "        }",
    "        const moving = Boolean(scene.botRunning) || (state.mode === 'playing' && Math.abs(state.player?.vx || 0) > 0.35);",
    "        chatGameBotWrap.classList.toggle('is-running', moving);",
    "        chatGameBotWrap.classList.toggle('dir-left', Number(state.player?.facing || -1) < 0);",
    "    }",
    "    if (chatGameBot) {",
    "        chatGameBot.classList.toggle('looking-user', state.mode === 'ready');",
    "    }",
    "}",
    "",
    "function chatGameResetCloudJump() {",
    "    if (!(chatGameCanvas instanceof HTMLCanvasElement)) return;",
    "    const surface = chatGameResizeCanvas();",
    "    const width = surface.width;",
    "    const height = surface.height;",
    "    const best = chatGameGetHighScore();",
    "    const selectedAgent = chatGamePickOfficeAgentForRun();",
    "    const state = {",
    "        mode: 'intro',",
    "        selectedAgent,",
    "        width,",
    "        height,",
    "        tick: 0,",
    "        introSeconds: 0,",
    "        readySeconds: 0,",
    "        score: 0,",
    "        best,",
    "        distance: 0,",
    "        playFrames: 0,",
    "        gravity: 0.41,",
    "        horizontalSpeed: 4.6,",
    "        jumpVelocity: -10.6,",
    "        baseFallSpeed: 1.16,",
    "        launchSeconds: 0,",
    "        scrollLine: height * 0.34,",
    "        startY: height - 140,",
    "        platformGuideX: (width * CHAT_GAME_START_X_RATIO),",
    "        pathTargetX: (width * CHAT_GAME_PLATFORM_CENTER_RATIO),",
    "        platformSeq: 1,",
    "        platforms: [],",
    "        player: {",
    "            x: (width * CHAT_GAME_START_X_RATIO) - 15,",
    "            y: height - 150,",
    "            w: 30,",
    "            h: 34,",
    "            vx: 0,",
    "            vy: 0,",
    "            facing: -1,",
    "        },",
    "        scene: {",
    "            doorVisible: false,",
    "            doorOpen: 0,",
    "            light: 0,",
    "            botVisible: false,",
    "            botRunning: false,",
    "            botInside: true,",
    "            botDoorOffsetX: CHAT_GAME_DOOR_BOT_ENTER_OFFSET_START,",
    "            botX: width - 50,",
    "            botY: height - 150,",
    "            botScale: 1,",
    "            botJetpack: false,",
    "        },",
    "    };",
    "",
    "    const doorAnchor = chatGameGetDoorAnchor(state);",
    "    const startY = Number(doorAnchor.y) || (height - 140);",
    "    state.player.x = chatGameClamp(state.player.x, 18, Math.max(18, width - state.player.w - 18));",
    "    state.startY = startY;",
    "    state.player.y = startY;",
    "    state.platformGuideX = state.player.x + (state.player.w * 0.5);",
    "    state.pathTargetX = state.platformGuideX;",
    "    state.scene.botX = Number(doorAnchor.doorLeft || 0) + CHAT_GAME_DOOR_BOT_MOUNT_LEFT + CHAT_GAME_DOOR_BOT_ENTER_OFFSET_START;",
    "    state.scene.botY = startY;",
    "    chatGameRuntime.cloudJump = state;",
    "    chatGameRuntime.lastFrameMs = 0;",
    "    chatGameUpdateHud(state);",
    "    chatGameSetStatusText('Door opening...');",
    "    chatGameSyncScene(state);",
    "}",
    "",
    "function chatGameStartRun(state = chatGameRuntime.cloudJump) {",
    "    if (!state || state.mode !== 'ready') return false;",
    "    state.mode = 'launch';",
    "    state.launchSeconds = 0;",
    "    state.playFrames = 0;",
    "    state.score = 0;",
    "    state.distance = 0;",
    "    chatGameCreateTopStartPlatforms(state);",
    "    state.player.y = Number(state.startY) || state.player.y;",
    "    state.player.vy = 0;",
    "    state.player.vx = 0;",
    "    chatGameSetStatusText('Platforms incoming. First landing starts the run.');",
    "    chatGameSyncScene(state);",
    "    return true;",
    "}",
    "",
    "function chatGameStepIntro(state, deltaFrames) {",
    "    const stepSeconds = deltaFrames / 60;",
    "    state.tick += deltaFrames;",
    "    state.introSeconds += stepSeconds;",
    "",
    "    const elapsed = state.introSeconds;",
    "    const scene = state.scene;",
    "    scene.botScale = 1;",
    "    scene.botJetpack = false;",
    "    scene.doorVisible = elapsed >= 0.08;",
    "    scene.doorOpen = chatGameClamp((elapsed - 0.32) / 0.46, 0, 1);",
    "    scene.light = chatGameClamp((elapsed - 0.42) / 0.4, 0, 1);",
    "",
    "    const doorMetrics = chatGameGetDoorAnchor(state);",
    "    const insideBaseY = doorMetrics.y;",
    "    const insideOffsetStart = CHAT_GAME_DOOR_BOT_ENTER_OFFSET_START;",
    "    const insideOffsetEnd = CHAT_GAME_DOOR_BOT_ENTER_OFFSET_END;",
    "    const worldXFromDoorOffset = (offsetX) => (",
    "        Number(doorMetrics.doorLeft || 0) + CHAT_GAME_DOOR_BOT_MOUNT_LEFT + offsetX",
    "    );",
    "    const holdInsideStart = 0.22;",
    "    const holdInsideEnd = 1.12;",
    "    const emergeEnd = 1.58;",
    "    const runEnd = 2.72;",
    "    const doorCloseStart = runEnd - 0.34;",
    "",
    "    if (elapsed < holdInsideStart) {",
    "        scene.botVisible = false;",
    "        scene.botRunning = false;",
    "        scene.botInside = true;",
    "        scene.botDoorOffsetX = insideOffsetStart;",
    "        scene.botX = worldXFromDoorOffset(scene.botDoorOffsetX);",
    "        scene.botY = insideBaseY;",
    "        state.player.y = insideBaseY;",
    "        state.player.facing = -1;",
    "    } else if (elapsed < holdInsideEnd) {",
    "        scene.botVisible = true;",
    "        scene.botRunning = false;",
    "        scene.botInside = true;",
    "        scene.botDoorOffsetX = insideOffsetStart;",
    "        scene.botX = worldXFromDoorOffset(scene.botDoorOffsetX);",
    "        scene.botY = insideBaseY;",
    "        state.player.y = insideBaseY;",
    "        state.player.facing = -1;",
    "    } else if (elapsed < emergeEnd) {",
    "        const emergeProgress = chatGameClamp((elapsed - holdInsideEnd) / Math.max(0.001, emergeEnd - holdInsideEnd), 0, 1);",
    "        const eased = chatGameEaseOutCubic(emergeProgress);",
    "        scene.botVisible = true;",
    "        scene.botRunning = emergeProgress > 0.08;",
    "        scene.botInside = true;",
    "        scene.botDoorOffsetX = insideOffsetStart + ((insideOffsetEnd - insideOffsetStart) * eased);",
    "        scene.botX = worldXFromDoorOffset(scene.botDoorOffsetX);",
    "        scene.botY = insideBaseY;",
    "        state.player.y = insideBaseY;",
    "        state.player.facing = -1;",
    "    } else {",
    "        const runProgress = chatGameClamp((elapsed - emergeEnd) / Math.max(0.001, runEnd - emergeEnd), 0, 1);",
    "        const eased = chatGameEaseOutCubic(runProgress);",
    "        const startX = worldXFromDoorOffset(insideOffsetEnd);",
    "        const endX = state.player.x;",
    "        const closeProgress = chatGameClamp((elapsed - doorCloseStart) / Math.max(0.001, runEnd - doorCloseStart), 0, 1);",
    "        scene.botVisible = true;",
    "        scene.botRunning = runProgress < 0.98;",
    "        scene.botInside = false;",
    "        scene.botDoorOffsetX = 0;",
    "        scene.botX = startX + ((endX - startX) * eased);",
    "        scene.botY = insideBaseY + (Math.sin(runProgress * Math.PI) * 1.4);",
    "        scene.doorOpen = 1 - closeProgress;",
    "        scene.light *= (1 - closeProgress);",
    "        scene.doorVisible = closeProgress < 0.98;",
    "        state.player.y = insideBaseY;",
    "        state.startY = insideBaseY;",
    "        state.player.facing = -1;",
    "    }",
    "",
    "    if (elapsed >= (runEnd + 0.16)) {",
    "        state.mode = 'ready';",
    "        state.readySeconds = 0;",
    "        scene.botVisible = true;",
    "        scene.botRunning = false;",
    "        scene.botInside = false;",
    "        scene.botDoorOffsetX = 0;",
    "        scene.doorVisible = false;",
    "        scene.doorOpen = 0;",
    "        scene.light = 0;",
    "        scene.botX = state.player.x;",
    "        scene.botY = state.startY;",
    "        state.player.y = state.startY;",
    "        chatGameSetStatusText('Press Space to start | Esc to exit');",
    "    }",
    "}",
    "",
    "function chatGameStepReady(state, deltaFrames) {",
    "    state.tick += deltaFrames;",
    "    state.readySeconds += (deltaFrames / 60);",
    "    const scene = state.scene;",
    "    scene.botScale = 1;",
    "    scene.botJetpack = false;",
    "    scene.doorVisible = false;",
    "    scene.doorOpen = 0;",
    "    scene.light = 0;",
    "    scene.botVisible = true;",
    "    scene.botRunning = false;",
    "    scene.botInside = false;",
    "    scene.botDoorOffsetX = 0;",
    "    state.player.vx = 0;",
    "    state.player.vy = 0;",
    "    state.player.y = state.startY;",
    "    scene.botX = state.player.x;",
    "    scene.botY = state.player.y + (Math.sin(state.tick * 0.11) * 0.8);",
    "}",
    "",
    "function chatGameStepLaunch(state, deltaFrames) {",
    "    state.tick += deltaFrames;",
    "    state.launchSeconds += (deltaFrames / 60);",
    "",
    "    const player = state.player;",
    "    const horizontal = (chatGameRuntime.input.right ? 1 : 0) - (chatGameRuntime.input.left ? 1 : 0);",
    "    player.vx = horizontal * (state.horizontalSpeed * 0.92);",
    "    player.x += player.vx * deltaFrames;",
    "    if (player.vx > 0.12) {",
    "        player.facing = 1;",
    "    } else if (player.vx < -0.12) {",
    "        player.facing = -1;",
    "    }"
].join("\n");
