/* app.js lines 2001-3000 */
export default [
    "",
    "    // Cap at 6 suggestions max",
    "    const capped = validOptions.slice(0, 6);",
    "",
    "    suggestionRailVersion += 1;",
    "    const renderVersion = suggestionRailVersion;",
    "    suggestionContext = safeString(context) || 'general';",
    "    suggestionDismissible = Boolean(dismissible);",
    "    const heading = safeString(title) || 'Suggestions';",
    "",
    "    assistantSuggestionRail.classList.remove('hidden');",
    "    assistantSuggestionRail.dataset.context = suggestionContext;",
    "    if (assistantSuggestionTitle) {",
    "        assistantSuggestionTitle.textContent = heading;",
    "    }",
    "    if (assistantSuggestionDismissBtn) {",
    "        assistantSuggestionDismissBtn.classList.toggle('hidden', !suggestionDismissible);",
    "    }",
    "",
    "    assistantSuggestionBubbles.innerHTML = '';",
    "",
    "    // Build a marquee track that duplicates chips for seamless CSS looping",
    "    const track = document.createElement('div');",
    "    track.className = 'assistant-suggestion-track';",
    "",
    "    function createChipButton(option) {",
    "        const button = document.createElement('button');",
    "        const isAction = safeString(option?.kind) === 'action';",
    "        button.className = isAction",
    "            ? 'onboarding-action-chip assistant-suggestion-chip'",
    "            : 'onboarding-option-chip assistant-suggestion-chip';",
    "        if (safeString(option?.tone) === 'primary') button.classList.add('primary');",
    "        if (safeString(option?.tone) === 'danger') button.classList.add('danger');",
    "        button.type = 'button';",
    "        button.textContent = safeString(option?.label) || safeString(option?.value);",
    "",
    "        button.addEventListener('click', async () => {",
    "            if (!assistantSuggestionBubbles) return;",
    "            const buttons = Array.from(assistantSuggestionBubbles.querySelectorAll('button'));",
    "            buttons.forEach((b) => { b.disabled = true; });",
    "            button.classList.add('selected');",
    "",
    "            try {",
    "                if (typeof option?.onChoose === 'function') {",
    "                    await option.onChoose(option);",
    "                } else {",
    "                    const sendPrompt = safeString(option?.send_prompt || option?.sendPrompt);",
    "                    const insertPrompt = safeString(option?.insert_prompt || option?.insertPrompt);",
    "                    if (sendPrompt) {",
    "                        composerTextarea.value = sendPrompt;",
    "                        composerTextarea.dispatchEvent(new Event('input'));",
    "                        await handleSend();",
    "                    } else if (insertPrompt) {",
    "                        composerTextarea.value = insertPrompt;",
    "                        composerTextarea.dispatchEvent(new Event('input'));",
    "                        composerTextarea.focus();",
    "                    }",
    "                }",
    "            } catch (err) {",
    "                console.error('Suggestion action failed', err);",
    "            } finally {",
    "                if (renderVersion !== suggestionRailVersion) return;",
    "                if (Boolean(option?.keep_after_choose)) {",
    "                    buttons.forEach((b) => { b.disabled = false; });",
    "                    button.classList.remove('selected');",
    "                } else {",
    "                    hideAssistantSuggestions({ force: true });",
    "                }",
    "            }",
    "        });",
    "        return button;",
    "    }",
    "",
    "    // First set of chips (original)",
    "    capped.forEach((option) => {",
    "        track.appendChild(createChipButton(option));",
    "    });",
    "    // Duplicate set for seamless marquee loop",
    "    capped.forEach((option) => {",
    "        track.appendChild(createChipButton(option));",
    "    });",
    "",
    "    assistantSuggestionBubbles.appendChild(track);",
    "}",
    "",
    "function withSuggestionContext(prompt, { userText = '', assistantText = '' } = {}) {",
    "    const base = safeString(prompt);",
    "    const user = safeString(userText).slice(0, 260);",
    "    const assistant = safeString(assistantText).slice(0, 260);",
    "    const contextParts = [];",
    "    if (user) contextParts.push(`User context: ${user}`);",
    "    if (assistant) contextParts.push(`Latest response: ${assistant}`);",
    "    if (contextParts.length === 0) return base;",
    "    return `${base}\\n\\nContext:\\n- ${contextParts.join('\\n- ')}`;",
    "}",
    "",
    "function classifySuggestionIntent({ userText = '', assistantText = '' } = {}) {",
    "    const user = safeString(userText).toLowerCase();",
    "    const assistant = safeString(assistantText).toLowerCase();",
    "    const combined = `${user} ${assistant}`.trim();",
    "    const hasAny = (tokens = []) => tokens.some((token) => combined.includes(token));",
    "",
    "    if (hasAny(['error', 'failed', 'exception', 'stack trace', 'traceback', 'not working', \"can't\", 'cannot', 'bug'])) {",
    "        return 'troubleshooting';",
    "    }",
    "    if (hasAny(['meeting', 'agenda', 'minutes', 'follow-up', 'follow up', 'standup', 'retro'])) {",
    "        return 'meeting';",
    "    }",
    "    if (hasAny(['email', 'message', 'post', 'resume', 'cover letter', 'proposal', 'announcement', 'copy', 'blog'])) {",
    "        return 'writing';",
    "    }",
    "    if (hasAny(['plan', 'roadmap', 'milestone', 'timeline', 'project', 'launch', 'rollout', 'trip', 'event', 'strategy'])) {",
    "        return 'planning';",
    "    }",
    "    if (hasAny(['compare', 'comparison', 'pros and cons', 'which', 'best option', 'tradeoff', 'trade-off', 'decide', 'decision', 'choose'])) {",
    "        return 'decision';",
    "    }",
    "    if (hasAny(['budget', 'cost', 'pricing', 'price', 'expense', 'financial', 'roi'])) {",
    "        return 'finance';",
    "    }",
    "    if (hasAny(['research', 'analyze', 'analysis', 'investigate', 'summarize', 'summary', 'source', 'evidence'])) {",
    "        return 'research';",
    "    }",
    "    if (hasAny(['learn', 'teach', 'tutorial', 'explain', 'understand', 'study'])) {",
    "        return 'learning';",
    "    }",
    "    if (hasAny(['schedule', 'calendar', 'todo', 'to-do', 'task list', 'prioritize', 'weekly'])) {",
    "        return 'productivity';",
    "    }",
    "    if (hasAny(['brainstorm', 'ideas', 'creative', 'name', 'tagline', 'concept', 'campaign', 'story'])) {",
    "        return 'creative';",
    "    }",
    "    if (hasAny(['code', 'coding', 'script', 'api', 'function', 'class', 'repo', 'pull request', 'test case'])) {",
    "        return 'code';",
    "    }",
    "    return 'general';",
    "}",
    "",
    "function normalizeSuggestionOptions(options = []) {",
    "    const unique = [];",
    "    const seen = new Set();",
    "    (Array.isArray(options) ? options : []).forEach((option) => {",
    "        const label = safeString(option?.label || option?.value);",
    "        if (!label) return;",
    "        const key = label.toLowerCase();",
    "        if (seen.has(key)) return;",
    "        seen.add(key);",
    "        unique.push(option);",
    "    });",
    "    return unique.slice(0, 9);",
    "}",
    "",
    "function withUniversalSuggestionOptions(baseOptions = [], context = {}) {",
    "    const universal = [",
    "        {",
    "            label: 'Summarize where we are',",
    "            kind: 'option',",
    "            send_prompt: withSuggestionContext('Give a quick summary of where we are and what matters most next.', context),",
    "        },",
    "        {",
    "            label: 'Ask clarifying questions',",
    "            kind: 'option',",
    "            send_prompt: withSuggestionContext('Ask the minimum clarifying questions needed to improve the result.', context),",
    "        },",
    "        {",
    "            label: 'Give me 3 alternatives',",
    "            kind: 'option',",
    "            send_prompt: withSuggestionContext('Offer 3 viable alternatives with tradeoffs.', context),",
    "        },",
    "    ];",
    "    return normalizeSuggestionOptions([...(Array.isArray(baseOptions) ? baseOptions : []), ...universal]);",
    "}",
    "",
    "function buildIntentSuggestionOptions(intent, context = {}) {",
    "    const keepMoving = {",
    "        label: 'Keep this moving',",
    "        kind: 'action',",
    "        tone: 'primary',",
    "        send_prompt: withSuggestionContext(",
    "            'Continue this exact task. Give me the best next step and execute it directly where possible.',",
    "            context",
    "        ),",
    "    };",
    "",
    "    if (intent === 'planning') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Turn into checklist', kind: 'option', send_prompt: withSuggestionContext('Turn this into a concrete checklist with sequence and owners.', context) },",
    "            { label: 'Estimate timeline', kind: 'option', send_prompt: withSuggestionContext('Estimate a realistic timeline with dependencies and risk notes.', context) },",
    "            { label: 'Surface blockers', kind: 'option', send_prompt: withSuggestionContext('Identify likely blockers early and propose mitigations.', context) },",
    "            { label: 'Define success criteria', kind: 'option', send_prompt: withSuggestionContext('Define clear success criteria and measurable outcomes.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'writing') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Draft version 1', kind: 'option', send_prompt: withSuggestionContext('Write a strong first draft using the current context.', context) },",
    "            { label: 'Make it tighter', kind: 'option', send_prompt: withSuggestionContext('Rewrite this to be shorter, clearer, and more persuasive.', context) },",
    "            { label: 'Adjust tone', kind: 'option', send_prompt: withSuggestionContext('Give 3 tone variants: formal, friendly, and direct.', context) },",
    "            { label: 'Audience rewrite', kind: 'option', send_prompt: withSuggestionContext('Rewrite this for the target audience and goal.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'decision') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Pros/cons table', kind: 'option', send_prompt: withSuggestionContext('Create a pros and cons table for the main options.', context) },",
    "            { label: 'Recommend one', kind: 'option', send_prompt: withSuggestionContext('Recommend one option decisively and explain why.', context) },",
    "            { label: 'Missing inputs', kind: 'option', send_prompt: withSuggestionContext('List the missing information needed for a confident decision.', context) },",
    "            { label: 'Decision matrix', kind: 'option', send_prompt: withSuggestionContext('Build a weighted decision matrix for the leading options.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'research') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Plain-language summary', kind: 'option', send_prompt: withSuggestionContext('Summarize the key findings in plain language.', context) },",
    "            { label: 'Compare options', kind: 'option', send_prompt: withSuggestionContext('Compare top options with tradeoffs and recommendations.', context) },",
    "            { label: 'Sources + caveats', kind: 'option', send_prompt: withSuggestionContext('Give source-style reasoning and call out uncertainty clearly.', context) },",
    "            { label: 'What changed recently?', kind: 'option', send_prompt: withSuggestionContext('Highlight recent changes or updates relevant to this topic.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'learning') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Teach step-by-step', kind: 'option', send_prompt: withSuggestionContext('Teach this step-by-step with examples and no jargon.', context) },",
    "            { label: 'Quick practice', kind: 'option', send_prompt: withSuggestionContext('Give a short practice exercise to lock this in.', context) },",
    "            { label: \"Explain like I'm new\", kind: 'option', send_prompt: withSuggestionContext('Explain this for a beginner with analogies.', context) },",
    "            { label: 'Cheat sheet', kind: 'option', send_prompt: withSuggestionContext('Create a concise cheat sheet I can reference later.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'meeting') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Draft agenda', kind: 'option', send_prompt: withSuggestionContext('Create a sharp meeting agenda with goals and timing.', context) },",
    "            { label: 'Action items', kind: 'option', send_prompt: withSuggestionContext('Convert this into action items with owners and deadlines.', context) },",
    "            { label: 'Follow-up message', kind: 'option', send_prompt: withSuggestionContext('Draft a concise follow-up message for stakeholders.', context) },",
    "            { label: 'Talking points', kind: 'option', send_prompt: withSuggestionContext('Create concise talking points for the meeting.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'productivity') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Prioritize next 3', kind: 'option', send_prompt: withSuggestionContext('Prioritize the next 3 highest-impact tasks.', context) },",
    "            { label: 'Time-block plan', kind: 'option', send_prompt: withSuggestionContext('Create a realistic time-blocked schedule for today/this week.', context) },",
    "            { label: 'Simple checklist', kind: 'option', send_prompt: withSuggestionContext('Turn this into an actionable checklist.', context) },",
    "            { label: 'What can I drop?', kind: 'option', send_prompt: withSuggestionContext('Identify what can be deferred or dropped with low risk.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'creative') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Generate ideas', kind: 'option', send_prompt: withSuggestionContext('Generate 12 original ideas and rank the top 3.', context) },",
    "            { label: 'Pick strongest concept', kind: 'option', send_prompt: withSuggestionContext('Pick the strongest concept and justify the choice.', context) },",
    "            { label: 'Create variations', kind: 'option', send_prompt: withSuggestionContext('Create multiple variations with different styles and audiences.', context) },",
    "            { label: 'Name + tagline options', kind: 'option', send_prompt: withSuggestionContext('Generate strong name and tagline options with rationale.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'finance') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Build budget', kind: 'option', send_prompt: withSuggestionContext('Build a practical budget with best/target/worst cases.', context) },",
    "            { label: 'Compare spend options', kind: 'option', send_prompt: withSuggestionContext('Compare spending options and show tradeoffs.', context) },",
    "            { label: 'Find cost cuts', kind: 'option', send_prompt: withSuggestionContext('Identify safe places to reduce cost without hurting outcomes.', context) },",
    "            { label: 'ROI snapshot', kind: 'option', send_prompt: withSuggestionContext('Give a simple ROI snapshot for each option.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'troubleshooting') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Find root cause', kind: 'option', send_prompt: withSuggestionContext('Diagnose the most likely root cause with evidence.', context) },",
    "            { label: 'Fastest safe fix', kind: 'option', send_prompt: withSuggestionContext('Give the fastest safe fix and verification steps.', context) },",
    "            { label: 'Prevent repeat', kind: 'option', send_prompt: withSuggestionContext('Give a prevention checklist to avoid this recurring.', context) },",
    "            { label: 'Rollback plan', kind: 'option', send_prompt: withSuggestionContext('Provide a rollback/safety plan before risky changes.', context) },",
    "        ], context);",
    "    }",
    "    if (intent === 'code') {",
    "        return withUniversalSuggestionOptions([",
    "            keepMoving,",
    "            { label: 'Implement next step', kind: 'option', send_prompt: withSuggestionContext('Implement the next concrete step and show changes.', context) },",
    "            { label: 'Add tests', kind: 'option', send_prompt: withSuggestionContext('Add targeted tests covering risky paths and edge cases.', context) },",
    "            { label: 'Risk review', kind: 'option', send_prompt: withSuggestionContext('Review this implementation for bugs and regressions.', context) },",
    "            { label: 'Write docs for this', kind: 'option', send_prompt: withSuggestionContext('Document what this does and how to use it.', context) },",
    "        ], context);",
    "    }",
    "",
    "    return withUniversalSuggestionOptions([",
    "        keepMoving,",
    "        { label: 'Next 3 actions', kind: 'option', send_prompt: withSuggestionContext('Give the next 3 highest-impact actions from here.', context) },",
    "        { label: 'Alternative approach', kind: 'option', send_prompt: withSuggestionContext('Offer an alternative approach with clear tradeoffs.', context) },",
    "        { label: 'Make it concrete', kind: 'option', send_prompt: withSuggestionContext('Make this more concrete with specific examples and outputs.', context) },",
    "        { label: 'Clarify assumptions', kind: 'option', send_prompt: withSuggestionContext('List assumptions and what to validate first.', context) },",
    "    ], context);",
    "}",
    "",
    "function buildStarterSuggestionOptions() {",
    "    if (!isOnboardingComplete()) {",
    "        return [",
    "            {",
    "                label: 'Run Easy Setup',",
    "                kind: 'action',",
    "                tone: 'primary',",
    "                onChoose: async () => {",
    "                    ensureChatVisible();",
    "                    await openEasySetup({ source: 'suggestion', force: false, restart: false });",
    "                },",
    "            },",
    "            {",
    "                label: withAgentName('Is {{agent}} safe?'),",
    "                kind: 'option',",
    "                send_prompt: withAgentName('Is {{agent}} safe to run? Explain approvals, downloads, and security controls in plain language.'),",
    "            },",
    "            {",
    "                label: 'What does setup do?',",
    "                kind: 'option',",
    "                send_prompt: 'Explain Easy Setup in plain English and what each step unlocks.',",
    "            },",
    "            {",
    "                label: 'Minimal setup',",
    "                kind: 'action',",
    "                onChoose: async () => {",
    "                    ensureChatVisible();",
    "                    await openEasySetup({ source: 'suggestion', force: false, restart: true });",
    "                    handleEasySetupPathSelect('manual');",
    "                },",
    "            },",
    "        ];",
    "    }",
    "",
    "    return [",
    "        {",
    "            label: 'Plan something',",
    "            kind: 'action',",
    "            tone: 'primary',",
    "            send_prompt: 'Help me plan something important with milestones, priorities, and a practical first step.',",
    "        },",
    "        {",
    "            label: 'Draft a message',",
    "            kind: 'option',",
    "            send_prompt: 'Help me draft a clear, effective message/email. Ask 2-3 clarifying questions first.',",
    "        },",
    "        {",
    "            label: 'Research a topic',",
    "            kind: 'option',",
    "            send_prompt: 'Research this topic and compare the best options with tradeoffs and a recommendation.',",
    "        },",
    "        {",
    "            label: 'Brainstorm ideas',",
    "            kind: 'option',",
    "            send_prompt: 'Brainstorm a wide range of ideas, then shortlist the strongest 3 with reasoning.',",
    "        },",
    "        {",
    "            label: 'Organize tasks',",
    "            kind: 'option',",
    "            send_prompt: 'Turn my current priorities into a focused, realistic task plan.',",
    "        },",
    "        {",
    "            label: 'Help me decide',",
    "            kind: 'option',",
    "            send_prompt: 'Help me decide between options with a clear recommendation and tradeoffs.',",
    "        },",
    "    ];",
    "}",
    "",
    "function showStarterSuggestionRail({ force = false, title = '' } = {}) {",
    "    if (!force && safeString(suggestionContext) === 'onboarding') return;",
    "    if (easySetupState.interviewStarted) return;",
    "    const onboardingDone = isOnboardingComplete();",
    "    const heading = safeString(title) || 'Suggestions';",
    "    setAssistantSuggestions({",
    "        title: heading,",
    "        context: onboardingDone ? 'starter' : 'setup',",
    "        dismissible: onboardingDone,",
    "        options: buildStarterSuggestionOptions(),",
    "    });",
    "}",
    "",
    "function maybeRenderSessionIntro() {",
    "    if (!chatMessagesInner) return;",
    "    const sid = safeString(sessionId);",
    "    if (!sid || introShownSessionIds.has(sid)) return;",
    "    if (chatMessagesInner.children.length > 0) return;",
    "",
    "    const intro = isOnboardingComplete()",
    "        ? withAgentName('{{agent}} online. Give me the objective, constraints, and deadline. I will execute.')",
    "        : withAgentName('{{agent}} boot sequence complete. Brain not fully connected yet. Easy Setup is required, and every download/install needs your explicit approval.');",
    "    renderMessage({ role: 'assistant', content: intro });",
    "    introShownSessionIds.add(sid);",
    "}",
    "",
    "function maybeShowAssistantFollowups({ assistantText = '', userText = '' } = {}) {",
    "    if (!isOnboardingComplete()) return;",
    "    if (easySetupState.interviewStarted) return;",
    "    if (safeString(suggestionContext) === 'onboarding') return;",
    "    const context = {",
    "        userText: safeString(userText),",
    "        assistantText: safeString(assistantText),",
    "    };",
    "    const intent = classifySuggestionIntent(context);",
    "    setAssistantSuggestions({",
    "        title: 'Suggestions',",
    "        context: `followup_${intent}`,",
    "        dismissible: true,",
    "        options: buildIntentSuggestionOptions(intent, context),",
    "    });",
    "}",
    "",
    "function refreshEasySetupProfileOptions() {",
    "    const profiles = Array.isArray(availableModelProfiles) ? availableModelProfiles : [];",
    "    const manualProfiles = profiles.filter((p) => {",
    "        const provider = safeString(p?.provider).toLowerCase();",
    "        return provider !== 'codex' && provider !== 'ollama' && provider !== 'local';",
    "    });",
    "    const localProfiles = profiles.filter((p) => {",
    "        const provider = safeString(p?.provider).toLowerCase();",
    "        return provider === 'ollama' || provider === 'local';",
    "    });",
    "",
    "    if (easySetupManualProfile) {",
    "        easySetupManualProfile.innerHTML = '';",
    "        const source = manualProfiles.length > 0 ? manualProfiles : profiles.filter((p) => safeString(p?.name).toLowerCase() !== 'codex');",
    "        source.forEach((profile) => {",
    "            const option = document.createElement('option');",
    "            option.value = safeString(profile?.name);",
    "            option.textContent = `${safeString(profile?.name)} (${safeString(profile?.provider) || 'provider'})`;",
    "            easySetupManualProfile.appendChild(option);",
    "        });",
    "        if (easySetupManualProfile.options.length === 0) {",
    "            const fallback = document.createElement('option');",
    "            fallback.value = '';",
    "            fallback.textContent = 'No cloud profile configured';",
    "            easySetupManualProfile.appendChild(fallback);",
    "        }",
    "    }",
    "",
    "    if (easySetupLocalProfile) {",
    "        easySetupLocalProfile.innerHTML = '';",
    "        const source = localProfiles.length > 0 ? localProfiles : [{ name: 'local', provider: 'ollama' }];",
    "        source.forEach((profile) => {",
    "            const option = document.createElement('option');",
    "            option.value = safeString(profile?.name) || 'local';",
    "            option.textContent = `${safeString(profile?.name) || 'local'} (${safeString(profile?.provider) || 'ollama'})`;",
    "            easySetupLocalProfile.appendChild(option);",
    "        });",
    "    }",
    "}",
    "",
    "function renderEasySetupPathCards() {",
    "    if (!easySetupPathGrid) return;",
    "    easySetupPathGrid.querySelectorAll('[data-path]').forEach((btn) => {",
    "        const selected = safeString(btn.getAttribute('data-path')) === safeString(easySetupState.selectedPath);",
    "        btn.classList.toggle('selected', selected);",
    "    });",
    "}",
    "",
    "function syncEasySetupConnectionBlocks() {",
    "    if (easySetupCodexBlock) easySetupCodexBlock.classList.toggle('hidden', easySetupState.selectedPath !== 'codex');",
    "    if (easySetupManualBlock) easySetupManualBlock.classList.toggle('hidden', easySetupState.selectedPath !== 'manual');",
    "    if (easySetupLocalBlock) easySetupLocalBlock.classList.toggle('hidden', easySetupState.selectedPath !== 'local');",
    "",
    "    if (easySetupConnectionMeta) {",
    "        if (easySetupState.selectedPath === 'codex') {",
    "            easySetupConnectionMeta.textContent = 'ChatGPT OAuth path. Sign in, confirm account status, and validate a Codex profile.';",
    "        } else if (easySetupState.selectedPath === 'manual') {",
    "            easySetupConnectionMeta.textContent = 'Manual key path. Save API key to chosen profile and run live connectivity validation.';",
    "        } else if (easySetupState.selectedPath === 'local') {",
    "            easySetupConnectionMeta.textContent = 'Local path. Validate Ollama endpoint and profile readiness on this machine.';",
    "        } else {",
    "            easySetupConnectionMeta.textContent = 'Select a path first, then run a real verification.';",
    "        }",
    "    }",
    "}",
    "",
    "function buildEasySetupDependencyPlan(bootstrap, selectedPath) {",
    "    const tools = bootstrap?.tools || {};",
    "    const plan = [];",
    "",
    "    const addDep = (id, title, ready, required, note, installUrl = '') => {",
    "        plan.push({",
    "            id,",
    "            title,",
    "            ready: Boolean(ready),",
    "            required: Boolean(required),",
    "            note: safeString(note),",
    "            install_url: safeString(installUrl),",
    "        });",
    "    };",
    "",
    "    if (selectedPath === 'codex') {",
    "        addDep('node', 'Node.js runtime', tools?.node?.installed, true, 'Runs the Codex CLI runtime (official Node.js installer).', tools?.node?.install_url || 'https://nodejs.org/en/download');",
    "        addDep('npm', 'npm package manager', tools?.npm?.installed, true, 'Installs and updates Codex CLI packages.', tools?.npm?.install_url || 'https://nodejs.org/en/download');",
    "        addDep('codex', 'Codex CLI', tools?.codex?.installed, true, 'Handles ChatGPT/Codex sign-in and bridge execution.', tools?.codex?.install_url || 'https://developers.openai.com/codex');",
    "    } else if (selectedPath === 'local') {",
    "        addDep('ollama_installed', 'Ollama installed', tools?.ollama?.installed, true, 'Local runtime for on-device model execution.', tools?.ollama?.install_url || 'https://ollama.com/download');",
    "        addDep('ollama_running', 'Ollama service running', tools?.ollama?.running, true, 'Verifies local Ollama service is reachable.', tools?.ollama?.install_url || 'https://ollama.com/download');",
    "    } else if (selectedPath === 'manual') {",
    "        addDep('manual_key', 'Provider key connected', easySetupState.verified, false, 'Manual key flow does not require local runtime downloads.', '');",
    "        addDep('codex_optional', 'Codex CLI (optional)', tools?.codex?.installed, false, 'Optional only if you want ChatGPT OAuth later.', tools?.codex?.install_url || 'https://developers.openai.com/codex');",
    "    }",
    "",
    "    return plan;",
    "}",
    "",
    "function missingRequiredDependencies(plan) {",
    "    return (plan || []).filter((item) => Boolean(item.required) && !Boolean(item.ready));",
    "}",
    "",
    "function buildEasySetupDependencyTrustNote(selectedPath, plan) {",
    "    const path = safeString(selectedPath);",
    "    const items = Array.isArray(plan) ? plan : [];",
    "    const required = items.filter((item) => Boolean(item?.required));",
    "    const missingRequired = required.filter((item) => !Boolean(item?.ready)).length;",
    "    const requiredCount = required.length;",
    "    const requiredText = requiredCount === 0",
    "        ? 'This path does not require extra local runtime downloads.'",
    "        : `This path uses ${requiredCount} required core tool${requiredCount === 1 ? '' : 's'}.`;",
    "    const missingText = missingRequired > 0",
    "        ? `${missingRequired} required item${missingRequired === 1 ? '' : 's'} still need approval.`",
    "        : 'Required items are already available or not needed.';",
    "    let pathGuidance = '';",
    "    if (path === 'manual') {",
    "        pathGuidance = 'Manual API Key is the lowest-download path.';",
    "    } else if (path === 'codex') {",
    "        pathGuidance = 'Codex path requires official Node.js, npm, and Codex CLI tooling.';",
    "    } else if (path === 'local') {",
    "        pathGuidance = 'Local path requires Ollama running on this machine.';",
    "    }",
    "    return `Security check: nothing installs until you approve it. ${requiredText} ${missingText} ${pathGuidance}`.trim();",
    "}",
    "",
    "function renderEasySetupDependencies() {",
    "    if (!easySetupDependencyList) return;",
    "    easySetupDependencyList.innerHTML = '';",
    "    const plan = Array.isArray(easySetupState.dependencyPlan) ? easySetupState.dependencyPlan : [];",
    "    if (plan.length === 0) {",
    "        easySetupDependencyList.innerHTML = '<div class=\"easy-setup-note\">No dependency checks were generated for this path.</div>';",
    "        if (easySetupDependencyTrustNote) {",
    "            easySetupDependencyTrustNote.textContent = 'Security check: this path currently has no dependency checks.';",
    "        }",
    "        return;",
    "    }",
    "    plan.forEach((dep) => {",
    "        const row = document.createElement('div');",
    "        row.className = 'easy-setup-dep-item';",
    "        const stateClass = dep.ready ? 'ready' : (dep.required ? 'missing' : '');",
    "        const stateText = dep.ready ? 'Ready' : (dep.required ? 'Required' : 'Optional');",
    "        row.innerHTML = `",
    "            <div>",
    "                <strong>${escapeHtml(dep.title)}</strong>",
    "                <span>${escapeHtml(dep.note)}</span>",
    "            </div>",
    "            <span class=\"easy-setup-dep-pill ${stateClass}\">${stateText}</span>",
    "        `;",
    "        easySetupDependencyList.appendChild(row);",
    "    });",
    "    if (easySetupDependencyTrustNote) {",
    "        easySetupDependencyTrustNote.textContent = buildEasySetupDependencyTrustNote(easySetupState.selectedPath, plan);",
    "    }",
    "}",
    "",
    "function setEasySetupDependencyDefaultStatus() {",
    "    const missing = missingRequiredDependencies(easySetupState.dependencyPlan).length;",
    "    if (missing > 0) {",
    "        setEasySetupStatus(easySetupDependencyStatus, 'Approve required downloads to continue.');",
    "    } else {",
    "        setEasySetupStatus(easySetupDependencyStatus, 'No required downloads pending for this path. Continue when ready.', 'ok');",
    "    }",
    "}",
    "",
    "function renderEasySetupReviewPanel() {",
    "    if (!easySetupReviewPanel) return;",
    "    easySetupReviewPanel.innerHTML = '';",
    "    const plan = Array.isArray(easySetupState.dependencyPlan) ? easySetupState.dependencyPlan : [];",
    "    if (plan.length === 0) {",
    "        easySetupReviewPanel.classList.add('hidden');",
    "        return;",
    "    }",
    "    plan.forEach((dep) => {",
    "        const item = document.createElement('div');",
    "        item.className = 'easy-setup-review-item';",
    "        const state = dep.ready ? 'ready' : (dep.required ? 'missing' : 'optional');",
    "        const installUrl = safeString(dep.install_url);",
    "        item.innerHTML = `<strong>${escapeHtml(dep.title)}</strong> - ${escapeHtml(dep.note)} (status: ${escapeHtml(state)})`;",
    "        if (installUrl) {",
    "            const link = document.createElement('a');",
    "            link.href = installUrl;",
    "            link.target = '_blank';",
    "            link.rel = 'noreferrer';",
    "            link.textContent = 'Install link';",
    "            item.appendChild(document.createTextNode(' '));",
    "            item.appendChild(link);",
    "        }",
    "        easySetupReviewPanel.appendChild(item);",
    "    });",
    "}",
    "",
    "function updateEasySetupReadyList() {",
    "    if (!easySetupReadyList) return;",
    "    const verifiedProfile = safeString(easySetupState.verifiedProfile) || 'n/a';",
    "    const codexModelCount = Array.isArray(easySetupState.codexModels) ? easySetupState.codexModels.length : 0;",
    "    const depPlan = Array.isArray(easySetupState.dependencyPlan) ? easySetupState.dependencyPlan : [];",
    "    const depMissing = missingRequiredDependencies(depPlan).length;",
    "",
    "    const rows = [",
    "        `Connection path: ${safeString(easySetupState.selectedPath) || 'not selected'}`,",
    "        `Verification: ${easySetupState.verified ? 'passed' : 'not verified'}`,",
    "        `Validated profile: ${verifiedProfile}`,",
    "        `Codex models detected: ${codexModelCount}`,",
    "        depMissing > 0",
    "            ? `Required downloads still missing: ${depMissing}`",
    "            : 'Required downloads: complete or not needed for selected path.',",
    "    ];",
    "",
    "    easySetupReadyList.innerHTML = '';",
    "    rows.forEach((rowText) => {",
    "        const row = document.createElement('div');",
    "        row.className = 'easy-setup-ready-item';",
    "        row.innerHTML = `<i class=\"ph ph-check-circle\"></i><span>${escapeHtml(rowText)}</span>`;",
    "        easySetupReadyList.appendChild(row);",
    "    });",
    "}",
    "",
    "function updateEasySetupNavigation() {",
    "    if (!easySetupBackBtn || !easySetupNextBtn) return;",
    "    easySetupBackBtn.style.visibility = easySetupState.step <= 1 ? 'hidden' : 'visible';",
    "    easySetupNextBtn.textContent = easySetupState.step >= 4 ? 'Continue in chat' : 'Continue';",
    "",
    "    let disableNext = false;",
    "    if (easySetupState.step === 1) {",
    "        disableNext = !safeString(easySetupState.selectedPath);",
    "    } else if (easySetupState.step === 2) {",
    "        disableNext = !easySetupState.verified;",
    "    } else if (easySetupState.step === 3) {",
    "        const missing = missingRequiredDependencies(easySetupState.dependencyPlan).length;",
    "        disableNext = missing > 0 && safeString(easySetupState.dependenciesAction) === 'pending';",
    "    }",
    "    easySetupNextBtn.disabled = disableNext;",
    "",
"    const dismissAllowed = !easySetupState.required;",
"    if (easySetupDismissBtn) {",
"        easySetupDismissBtn.textContent = easySetupState.required ? 'Skip for now' : 'Close';",
"        easySetupDismissBtn.classList.toggle('hidden', false);",
"    }",
"    if (easySetupCloseBtn) {",
"        easySetupCloseBtn.classList.toggle('hidden', !dismissAllowed);",
"    }",
    "    if (easySetupBackdrop) {",
    "        easySetupBackdrop.classList.toggle('easy-setup-backdrop-locked', !dismissAllowed);",
    "    }",
    "}",
    "",
    "function setEasySetupStep(step) {",
    "    easySetupState.step = Math.max(1, Math.min(4, Number(step) || 1));",
    "    if (easySetupStep1) easySetupStep1.classList.toggle('hidden', easySetupState.step !== 1);",
    "    if (easySetupStep2) easySetupStep2.classList.toggle('hidden', easySetupState.step !== 2);",
    "    if (easySetupStep3) easySetupStep3.classList.toggle('hidden', easySetupState.step !== 3);",
    "    if (easySetupStep4) easySetupStep4.classList.toggle('hidden', easySetupState.step !== 4);",
    "",
    "    if (easySetupProgressFill) {",
    "        easySetupProgressFill.style.width = `${(easySetupState.step / 4) * 100}%`;",
    "    }",
    "    if (easySetupProgressText) {",
    "        easySetupProgressText.textContent = `Step ${easySetupState.step} of 4`;",
    "    }",
    "",
    "    renderEasySetupPathCards();",
    "    syncEasySetupConnectionBlocks();",
    "    if (easySetupState.step === 3) {",
    "        renderEasySetupDependencies();",
    "    }",
    "    if (easySetupState.step === 4) {",
    "        updateEasySetupReadyList();",
    "    }",
    "    updateEasySetupNavigation();",
    "}",
    "",
    "async function loadEasySetupBootstrap() {",
    "    const res = await fetchJsonSafe('/api/setup/bootstrap');",
    "    if (!res.ok || !res.data) {",
    "        throw new Error(res.text || `Setup bootstrap failed (${res.status})`);",
    "    }",
    "    easySetupState.bootstrap = res.data;",
    "    return res.data;",
    "}",
    "",
    "function recommendedLocalModelIdsFromPlan(localPlan) {",
    "    const rows = Array.isArray(localPlan?.recommended_models) ? localPlan.recommended_models : [];",
    "    const ids = [];",
    "    rows.forEach((row) => {",
    "        const id = safeString(row?.id);",
    "        if (!id) return;",
    "        if (!ids.includes(id)) ids.push(id);",
    "    });",
    "    return ids;",
    "}",
    "",
    "async function runEasySetupLocalModelSync(profile = 'local') {",
    "    let modelIds = recommendedLocalModelIdsFromPlan(easySetupState.bootstrap?.local_plan);",
    "    if (modelIds.length === 0) {",
    "        const recRes = await fetchJsonSafe(`/api/local/recommendations?profile=${encodeURIComponent(profile)}`);",
    "        if (recRes.ok && recRes.data) {",
    "            const nextPlan = recRes.data?.local_plan;",
    "            modelIds = recommendedLocalModelIdsFromPlan(nextPlan);",
    "            if (nextPlan && easySetupState.bootstrap && typeof easySetupState.bootstrap === 'object') {",
    "                easySetupState.bootstrap.local_plan = nextPlan;",
    "            }",
    "        }",
    "    }",
    "",
    "    if (modelIds.length === 0) {",
    "        return {",
    "            skipped: true,",
    "            summary: 'No hardware-recommended local models for this device tier. Continuing with local profile only.',",
    "        };",
    "    }",
    "",
    "    const syncRes = await fetchJsonSafe('/api/local/sync', {",
    "        method: 'POST',",
    "        headers: { 'Content-Type': 'application/json' },",
    "        body: JSON.stringify({",
    "            profile,",
    "            model_ids: modelIds,",
    "            use_recommended: false,",
    "            pull_missing_only: true,",
    "            verify_only: false,",
    "        }),",
    "        timeoutMs: 1800000,",
    "    });",
    "    if (!syncRes.ok || !syncRes.data) {",
    "        const reason = safeString(syncRes.text) || `Local model sync failed (${syncRes.status})`;",
    "        throw new Error(`${reason} Remediation: ensure Ollama is running and retry.`);",
    "    }",
    "",
    "    const rows = Array.isArray(syncRes.data?.results) ? syncRes.data.results : [];",
    "    const failedRows = rows.filter((row) => !Boolean(row?.ok));",
    "    if (failedRows.length > 0) {",
    "        const failed = failedRows.map((row) => safeString(row?.model_id)).filter(Boolean).join(', ');",
    "        const detail = failed ? ` Failed: ${failed}.` : '';",
    "        throw new Error(`Local model sync completed with failures.${detail} Remediation: run Auto Repair and retry.`);",
    "    }",
    "",
    "    const pulledCount = rows.filter((row) => Boolean(row?.pulled)).length;",
    "    const reusedCount = rows.filter((row) => Boolean(row?.already_installed)).length;",
    "    const verifiedCount = rows.filter((row) => Boolean(row?.verified)).length;",
    "    let summary = `Verified ${verifiedCount}/${rows.length} local model${rows.length === 1 ? '' : 's'}.`;",
    "    if (pulledCount > 0) summary += ` Pulled ${pulledCount} missing.`;",
    "    if (reusedCount > 0) summary += ` Reused ${reusedCount} already installed.`;",
    "    return {",
    "        skipped: false,",
    "        summary,",
    "    };",
    "}",
    "",
    "async function persistOnboardingPrefs(overrides = {}) {",
    "    const existing = getOnboardingFromPrefs();",
    "    const mergedAnswers = {",
    "        ...(existing.answers || {}),",
    "        ...(easySetupState.interviewAnswers || {}),",
    "        ...(overrides.answers || {}),",
    "        connection_path: safeString(easySetupState.selectedPath),",
    "        dependency_action: safeString(easySetupState.dependenciesAction) || 'pending',",
    "    };",
].join("\n");
