/* split from part-015.js */
export default [
    "    if (command === 'status' || command === 'where' || command === 'load') return { command: 'status', args };",
    "    if (command === 'break' || command === 'coffee' || command === 'lunch') return { command: 'break', args };",
    "    if (command === 'resume' || command === 'work') return { command: 'resume', args };",
    "    if (command === 'summon' || command === 'lobby') return { command: 'summon', args };",
    "    if (command === 'focus') return { command: 'focus', args };",
    "    if (command === 'task') return { command: 'task', args };",
    "    return { command: 'message', args: message };",
    "}",
    "",
    "function officeHandleMention(agent, messageRaw) {",
    "    if (!officeState || !agent) return;",
    "    const message = safeString(messageRaw);",
    "    const lower = message.toLowerCase();",
    "    const parsed = officeParseMentionCommand(message);",
    "    let reply = '';",
    "",
    "    if (parsed.command === 'status') {",
    "        const activeCount = officeState.tasks.filter((task) => task.status === 'active').length;",
    "        const room = officeCurrentRoomForAgent(agent);",
    "        const status = officePick(OFFICE_DIALOGUE.mentionStatus).replace('{count}', String(activeCount));",
    "        reply = `${status} I am in ${room?.label || 'the hallway'} right now.`;",
    "    } else if (parsed.command === 'break') {",
    "        const breakTarget = officeChance(0.5) ? 'room-coffee' : 'room-break';",
    "        officeRouteAgentToRoom(agent, breakTarget, {",
    "            intent: 'break',",
    "            speed: officeRandomRange(2.8, 3.9),",
    "        });",
    "        agent.nextBreakAt = performance.now() + officeRandomRange(40_000, 88_000);",
    "        reply = 'Copy. Taking a short break loop and returning to queue.';",
    "    } else if (parsed.command === 'resume') {",
    "        agent.state = 'idle';",
    "        agent.intent = 'wander';",
    "        agent.idleUntil = performance.now() + officeRandomRange(320, 1200);",
    "        const routed = officeRouteAgentToRoom(agent, 'room-lobby', {",
    "            intent: 'wander',",
    "            speed: officeRandomRange(2.8, 3.8),",
    "        });",
    "        reply = routed ? 'Resuming active route from lobby.' : 'Resuming in place.';",
    "    } else if (parsed.command === 'summon') {",
    "        officeRouteAgentToRoom(agent, 'room-lobby', {",
    "            intent: 'wander',",
    "            speed: officeRandomRange(3.2, 4.1),",
    "        });",
    "        reply = 'On my way to Main Lobby.';",
    "    } else if (parsed.command === 'focus') {",
    "        const target = safeString(parsed.args).toLowerCase();",
    "        const matched = OFFICE_TASK_ROOM_RULES.find((rule) => rule.pattern.test(target));",
    "        const roomId = matched?.roomId || 'room-pods';",
    "        const room = officeRoomById(roomId);",
    "        officeRouteAgentToRoom(agent, roomId, {",
    "            intent: 'wander',",
    "            speed: officeRandomRange(3.1, 4.1),",
    "        });",
    "        reply = `Switching to focus in ${room?.label || 'Focus Pods'}.`;",
    "    } else if (parsed.command === 'task' || OFFICE_TASK_KEYWORDS.test(message) || lower.includes('build') || lower.includes('ship')) {",
    "        const taskText = parsed.command === 'task' ? (parsed.args || 'new task') : message;",
    "        const task = officeQueueTask(taskText, {",
    "            source: `mention:${agent.id}`,",
    "            announce: false,",
    "            preferredAgentId: agent.id,",
    "        });",
    "        if (task && task.assignedAgentId === agent.id) {",
    "            reply = `Picked it up. I am moving to ${task.roomLabel}.`;",
    "        } else if (task) {",
    "            reply = `Queued it in ${task.roomLabel}. I will grab it after my current task.`;",
    "        } else {",
    "            reply = officePick(OFFICE_DIALOGUE.mention);",
    "        }",
    "    } else {",
    "        reply = officePick(OFFICE_DIALOGUE.mention);",
    "    }",
    "",
    "    if (officeSpeak(agent, reply, { priority: true, durationMs: 1700 })) {",
    "        officePushChatLine(`@${agent.name}: ${reply}`);",
    "        officeBusEmit('agent.mention', {",
    "            agentId: agent.id,",
    "            agentName: agent.name,",
    "            command: parsed.command,",
    "            args: safeString(parsed.args).slice(0, 160),",
    "        });",
    "    }",
    "}",
    "",
    "function officeHandleAgentTap(agentId) {",
    "    if (!officeState) return;",
    "    const agent = officeGetAgentById(agentId);",
    "    if (!agent) return;",
    "    officeState.selectedAgentId = agent.id;",
    "    officeSyncCustomizerFields();",
    "    if (safeString(officeState.followAgentId)) {",
    "        officeSetFollowMode(true, agent.id);",
    "    }",
    "    const now = performance.now();",
    "    const exit = officePlanRunawayExit(agent);",
    "    agent.jumpUntil = now + 460;",
    "    agent.bumpUntil = now + 460;",
    "    agent.state = 'runaway';",
    "    agent.intent = 'runaway';",
    "    agent.returnAfterRunAt = now + officeClamp(OFFICE_RUNAWAY_DURATION_MS * 0.46, 2000, 3200);",
    "    agent.taskId = '';",
    "    agent.facing = exit.x >= agent.x ? 1 : -1;",
    "    agent.runawayExitX = exit.x;",
    "    agent.runawayExitY = exit.y;",
    "    agent.runawayPhase = 'to-hall';",
    "    agent.routeWaypoints = [];",
    "    agent.routeDestinationNodeId = '';",
    "    const routed = officeRouteAgentToNode(agent, exit.hallId, {",
    "        intent: 'runaway',",
    "        speed: officeRandomRange(5.2, 6.8),",
    "    });",
    "    if (!routed) {",
    "        agent.runawayPhase = 'exiting';",
    "        officeSetAgentTarget(agent, exit.x, exit.y, {",
    "            intent: 'runaway',",
    "            speed: officeRandomRange(6.1, 7.8),",
    "        });",
    "    }",
    "    agent.state = 'runaway';",
    "    agent.intent = 'runaway';",
    "    const line = officePick(OFFICE_DIALOGUE.clicked);",
    "    officeSpeak(agent, line, { priority: true, durationMs: 1200 });",
    "    officePushChatLine(`${agent.name}: ${line}`);",
    "    officePulseHaptic([14, 24, 10]);",
    "    officeBusEmit('agent.tapped', {",
    "        agentId: agent.id,",
    "        agentName: agent.name,",
    "        runawayPhase: agent.runawayPhase,",
    "    });",
    "    officeState.tasks.forEach((task) => {",
    "        if (task.assignedAgentId === agent.id && task.status === 'active') {",
    "            task.status = 'queued';",
    "            task.assignedAgentId = '';",
    "            task.startedAt = 0;",
    "            officeState.tasksDirty = true;",
    "        }",
    "    });",
    "}",
    "",
    "function officeHandleChatSend() {",
    "    if (!officeState || !officeChatInput) return;",
    "    const input = safeString(officeChatInput.value);",
    "    if (!input) return;",
    "    officeChatInput.value = '';",
    "",
    "    const slashMatch = input.match(/^\\/([a-z_-]+)\\s*(.*)$/i);",
    "    if (slashMatch) {",
    "        const command = safeString(slashMatch[1]).toLowerCase();",
    "        const args = safeString(slashMatch[2]).trim();",
    "        if (command === 'summon' || command === 'break' || command === 'resume') {",
    "            officeRunQuickAction(command);",
    "            return;",
    "        }",
    "        if (command === 'focus') {",
    "            const mapped = OFFICE_TASK_ROOM_RULES.find((rule) => rule.pattern.test(args));",
    "            const roomId = mapped?.roomId || 'room-pods';",
    "            officeRunQuickAction(`focus:${roomId}`);",
    "            return;",
    "        }",
    "    }",
    "",
    "    const mentionMatch = input.match(/^@([a-z0-9._-]+)\\s*(.*)$/i);",
    "    if (mentionMatch) {",
    "        const handle = mentionMatch[1];",
    "        const message = safeString(mentionMatch[2]);",
    "        const agent = officeFindAgentByHandle(handle);",
    "        if (!agent) {",
    "            const handles = officeState.agents.map((entry) => `@${officeAgentHandle(entry.name)}`).join(', ');",
    "            officePushChatLine(`No agent found for @${handle}. Available: ${handles}`);",
    "            return;",
    "        }",
    "        officePushChatLine(`You -> @${agent.name}: ${message || 'status?'}`, 'user');",
    "        officeHandleMention(agent, message || 'status');",
    "        return;",
    "    }",
    "",
    "    officeQueueTask(input, { source: 'office-chat', announce: true });",
    "}",
    "",
    "function officeRunQuickAction(actionRaw) {",
    "    if (!officeState) return;",
    "    const action = safeString(actionRaw).toLowerCase();",
    "    const now = performance.now();",
    "    const eventPayload = {",
    "        action,",
    "        at: Date.now(),",
    "    };",
    "    if (action === 'summon') {",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            officeRouteAgentToRoom(agent, 'room-lobby', {",
    "                intent: 'wander',",
    "                speed: officeRandomRange(3.1, 4.2),",
    "            });",
    "        });",
    "        officePushChatLine('System: All agents summoned to the Main Lobby.');",
    "        officePulseHaptic([12, 18, 12]);",
    "        officeBusEmit('quick_action.run', eventPayload, now);",
    "        return;",
    "    }",
    "    if (action === 'break') {",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            const breakRoomId = officeChance(0.5) ? 'room-coffee' : 'room-break';",
    "            officeRouteAgentToRoom(agent, breakRoomId, {",
    "                intent: 'break',",
    "                speed: officeRandomRange(2.9, 3.8),",
    "            });",
    "            agent.nextBreakAt = now + officeRandomRange(42_000, 94_000);",
    "            if (officeChance(0.42)) {",
    "                officeSpeak(agent, officeBanterForAgent(agent, 'break', {",
    "                    roomTheme: officeRoomById(breakRoomId)?.theme || '',",
    "                }), { priority: true, durationMs: 1200 });",
    "            }",
    "        });",
    "        officePushChatLine('System: Break wave sent. Agents are rotating to coffee/lunch rooms.');",
    "        officePulseHaptic([10, 20, 10]);",
    "        officeBusEmit('quick_action.run', eventPayload, now);",
    "        return;",
    "    }",
    "    if (action === 'resume') {",
    "        officeState.agents.forEach((agent) => {",
    "            if (!agent || agent.state === 'runaway') return;",
    "            const assignedTask = agent.taskId",
    "                ? officeState.tasks.find((task) => task.id === agent.taskId && task.status !== 'done')",
    "                : null;",
    "            if (assignedTask) {",
    "                officeRouteAgentToRoom(agent, assignedTask.roomId, {",
    "                    intent: 'task',",
    "                    speed: officeRandomRange(3.2, 4.2),",
    "                });",
    "                return;",
    "            }",
    "            agent.state = 'idle';",
    "            agent.intent = 'wander';",
    "            agent.idleUntil = now + officeRandomRange(400, 1200);",
    "        });",
    "        officePushChatLine('System: Resume signal sent. Agents are returning to active work routing.');",
    "        officePulseHaptic(14);",
    "        officeBusEmit('quick_action.run', eventPayload, now);",
    "        return;"
].join("\n");
