/* app.js lines 6001-7000 */
export default [
    "        scene.botScale = 1;",
    "        scene.botRotate = 0;",
    "        chatGameSetStatusText('Run ended. Space to run again | Esc to exit');",
    "    }",
    "}",
    "",
    "function chatGameStepDinoGameOver(state, deltaFrames) {",
    "    state.tick += deltaFrames;",
    "    const scene = state.scene;",
    "    const player = state.player;",
    "    scene.doorVisible = false;",
    "    scene.doorOpen = 0;",
    "    scene.light = 0;",
    "    scene.botVisible = true;",
    "    scene.botRunning = false;",
    "    scene.botInside = false;",
    "    scene.botDoorOffsetX = 0;",
    "    scene.botScale = 1;",
    "    scene.botRotate = 0;",
    "    scene.botJetpack = false;",
    "    scene.botX = player.x;",
    "    scene.botY = player.y + (Math.sin(state.tick * 0.08) * 0.5);",
    "}",
    "",
    "function chatGameStepDino(deltaFrames) {",
    "    const state = chatGameRuntime.dinoRun;",
    "    if (!state) return;",
    "    const frames = Number.isFinite(deltaFrames) ? Math.max(0, deltaFrames) : 1;",
    "",
    "    if (state.mode === 'intro') {",
    "        chatGameStepDinoIntro(state, frames);",
    "    } else if (state.mode === 'ready') {",
    "        chatGameStepDinoReady(state, frames);",
    "    } else if (state.mode === 'playing') {",
    "        chatGameStepDinoPlaying(state, frames);",
    "    } else if (state.mode === 'game_over') {",
    "        chatGameStepDinoGameOver(state, frames);",
    "    }",
    "    chatGameUpdateHud(state);",
    "    chatGameSyncScene(state);",
    "}",
    "",
    "function chatGameRenderDino() {",
    "    if (!(composerDinoCanvas instanceof HTMLCanvasElement)) return;",
    "    const ctx = composerDinoCanvas.getContext('2d');",
    "    const state = chatGameRuntime.dinoRun;",
    "    if (!ctx || !state) return;",
    "    const width = state.width;",
    "    const height = state.height;",
    "    const groundY = state.height - DINO_GROUND_PADDING;",
    "",
    "    ctx.clearRect(0, 0, width, height);",
    "",
    "    ctx.strokeStyle = 'rgba(98, 188, 255, 0.9)';",
    "    ctx.lineWidth = 3;",
    "    ctx.beginPath();",
    "    ctx.moveTo(0, groundY);",
    "    ctx.lineTo(width, groundY);",
    "    ctx.stroke();",
    "",
    "    const stripeStep = 24;",
    "    const stripeOffset = (state.scrollX % stripeStep);",
    "    ctx.fillStyle = 'rgba(193, 232, 255, 0.84)';",
    "    for (let x = -stripeStep; x < width + stripeStep; x += stripeStep) {",
    "        const drawX = Math.round(x - stripeOffset);",
    "        ctx.fillRect(drawX, groundY + 4, 10, 2);",
    "    }",
    "",
    "    state.obstacles.forEach((obstacle) => {",
    "        if (obstacle.type === 'drone') {",
    "            ctx.fillStyle = 'rgba(83, 179, 248, 0.92)';",
    "            ctx.fillRect(obstacle.x, obstacle.y + 3, obstacle.w, obstacle.h - 6);",
    "            ctx.fillStyle = 'rgba(232, 247, 255, 0.94)';",
    "            ctx.fillRect(obstacle.x + 4, obstacle.y + 5, Math.max(8, obstacle.w - 8), 4);",
    "            ctx.fillStyle = 'rgba(255, 173, 104, 0.88)';",
    "            ctx.fillRect(obstacle.x - 3, obstacle.y + (obstacle.h * 0.5) - 2, 3, 4);",
    "            return;",
    "        }",
    "        ctx.fillStyle = 'rgba(66, 176, 246, 0.96)';",
    "        ctx.fillRect(obstacle.x, obstacle.y, obstacle.w, obstacle.h);",
    "        ctx.fillStyle = 'rgba(228, 246, 255, 0.92)';",
    "        ctx.fillRect(obstacle.x + 2, obstacle.y + 2, Math.max(4, obstacle.w - 4), 3);",
    "    });",
    "",
    "    if (state.mode === 'game_over') {",
    "        ctx.fillStyle = 'rgba(236, 246, 255, 0.88)';",
    "        ctx.font = '700 14px \"Segoe UI\", sans-serif';",
    "        ctx.textAlign = 'center';",
    "        ctx.fillText('Run Ended', width * 0.5, Math.max(28, height * 0.24));",
    "    }",
    "    chatGameSyncScene(state);",
    "}",
    "",
    "function chatGameStep(deltaFrames = 1) {",
    "    const frames = Number.isFinite(deltaFrames) ? Math.max(0, deltaFrames) : 1;",
    "    if (chatGameRuntime.activeGameId === 'cloud_jump') {",
    "        chatGameStepCloudJump(frames);",
    "    } else if (chatGameRuntime.activeGameId === JETPACK_GAME_ID) {",
    "        chatGameStepJetpack(frames);",
    "    } else if (chatGameRuntime.activeGameId === DINO_GAME_ID) {",
    "        chatGameStepDino(frames);",
    "    }",
    "}",
    "",
    "function chatGameRender() {",
    "    if (chatGameRuntime.activeGameId === 'cloud_jump') {",
    "        chatGameRenderCloudJump();",
    "    } else if (chatGameRuntime.activeGameId === JETPACK_GAME_ID) {",
    "        chatGameRenderJetpack();",
    "    } else if (chatGameRuntime.activeGameId === DINO_GAME_ID) {",
    "        chatGameRenderDino();",
    "    }",
    "}",
    "",
    "function chatGameStartLoop() {",
    "    chatGameStopLoop();",
    "    const runFrame = (timestampMs) => {",
    "        if (!chatGameRuntime.activeGameId) return;",
    "        if (!chatGameRuntime.lastFrameMs) {",
    "            chatGameRuntime.lastFrameMs = timestampMs;",
    "        }",
    "        const elapsedMs = Math.max(0, timestampMs - chatGameRuntime.lastFrameMs);",
    "        chatGameRuntime.lastFrameMs = timestampMs;",
    "        const deltaFrames = Math.min(2.8, Math.max(0.6, elapsedMs / (1000 / 60)));",
    "        chatGameStep(deltaFrames);",
    "        chatGameRender();",
    "        chatGameRuntime.rafId = window.requestAnimationFrame(runFrame);",
    "    };",
    "    chatGameRuntime.rafId = window.requestAnimationFrame(runFrame);",
    "}",
    "",
    "function chatGameStopLoop() {",
    "    if (chatGameRuntime.rafId) {",
    "        window.cancelAnimationFrame(chatGameRuntime.rafId);",
    "    }",
    "    chatGameRuntime.rafId = 0;",
    "    chatGameRuntime.lastFrameMs = 0;",
    "}",
    "",
    "function chatGameOpen(gameId = 'cloud_jump') {",
    "    const gameKey = String(gameId || '').trim().toLowerCase();",
    "    if (gameKey !== 'cloud_jump' && gameKey !== JETPACK_GAME_ID && gameKey !== DINO_GAME_ID) return;",
    "    if (gameKey === DINO_GAME_ID && !(composerDinoCanvas instanceof HTMLCanvasElement)) return;",
    "    if (gameKey !== DINO_GAME_ID && !(chatGameCanvas instanceof HTMLCanvasElement)) return;",
    "    chatGameToggleHiddenCanvasPriority(true);",
    "    chatGameRuntime.activeGameId = gameKey;",
    "    chatGameRuntime.input.left = false;",
    "    chatGameRuntime.input.right = false;",
    "    chatGameRuntime.input.up = false;",
    "    chatGameRuntime.input.down = false;",
    "    chatGameRuntime.input.thrust = false;",
    "    chatGameRuntime.cloudJump = null;",
    "    chatGameRuntime.jetpackJoyride = null;",
    "    chatGameRuntime.dinoRun = null;",
    "    const isDino = gameKey === DINO_GAME_ID;",
    "    chatGameSetPanelOpen(!isDino);",
    "    chatGameSetDinoSurfaceOpen(isDino);",
    "    if (chatGamePanel) {",
    "        chatGamePanel.classList.toggle('jetpack-mode', gameKey === JETPACK_GAME_ID);",
    "    }",
    "    chatGameSetCenterMuted(gameKey === JETPACK_GAME_ID);",
    "    if (gameKey === 'cloud_jump') {",
    "        chatGameResetCloudJump();",
    "    } else if (gameKey === JETPACK_GAME_ID) {",
    "        chatGameResetJetpackJoyride();",
    "    } else {",
    "        chatGameResetDinoRun();",
    "    }",
    "    chatGameRender();",
    "    chatGameStartLoop();",
    "}",
    "",
    "function chatGameClose({ clearMode = false } = {}) {",
    "    chatGameStopLoop();",
    "    chatGameToggleHiddenCanvasPriority(false);",
    "    const closingGameId = chatGameRuntime.activeGameId || 'cloud_jump';",
    "    chatGameRuntime.activeGameId = '';",
    "    chatGameRuntime.cloudJump = null;",
    "    chatGameRuntime.jetpackJoyride = null;",
    "    chatGameRuntime.dinoRun = null;",
    "    chatGameRuntime.input.left = false;",
    "    chatGameRuntime.input.right = false;",
    "    chatGameRuntime.input.up = false;",
    "    chatGameRuntime.input.down = false;",
    "    chatGameRuntime.input.thrust = false;",
    "    chatGameSetPanelOpen(false);",
    "    chatGameSetDinoSurfaceOpen(false);",
    "    chatGameSetCenterMuted(false);",
    "    chatGameSetPhaseClass('');",
    "    if (chatGamePanel) {",
    "        chatGamePanel.classList.remove('door-visible');",
    "        chatGamePanel.classList.remove('jetpack-mode');",
    "    }",
    "    if (chatGameDoor) {",
    "        chatGameDoor.style.removeProperty('--door-open');",
    "        chatGameDoor.style.removeProperty('--door-light');",
    "    }",
    "    if (chatGameBotWrap) {",
    "        chatGameBotWrap.classList.remove('visible', 'inside-door', 'is-running', 'dir-left', 'jetpack-on', 'dino-ride');",
    "        delete chatGameBotWrap.dataset.agentId;",
    "        delete chatGameBotWrap.dataset.agentName;",
    "        if (chatGameLane instanceof HTMLElement && chatGameBotWrap.parentElement !== chatGameLane) {",
    "            chatGameLane.appendChild(chatGameBotWrap);",
    "        }",
    "        chatGameBotWrap.style.left = '0px';",
    "        chatGameBotWrap.style.top = '0px';",
    "        chatGameBotWrap.style.bottom = 'auto';",
    "        chatGameBotWrap.style.transform = 'translate3d(0px, 0px, 0px) rotate(0deg) scale(1)';",
    "        chatGameBotWrap.style.removeProperty('--bot-rotate');",
    "    }",
    "    if (chatGameBot) {",
    "        chatGameBot.classList.remove('looking-user');",
    "        chatGameBot.classList.remove('costume-cap', 'costume-visor', 'costume-headset', 'costume-bowtie');",
    "        chatGameBot.style.removeProperty('--agent-primary');",
    "        chatGameBot.style.removeProperty('--agent-secondary');",
    "        chatGameBot.style.removeProperty('--agent-glow');",
    "        chatGameBot.style.removeProperty('--agent-trim');",
    "    }",
    "    if (chatGameBotName) {",
    "        chatGameBotName.textContent = 'Office Bot';",
    "        chatGameBotName.title = 'Office Bot';",
    "    }",
    "    const best = chatGameGetHighScore(closingGameId);",
    "    if (chatGameScore) chatGameScore.textContent = '0';",
    "    if (chatGameHighScore) chatGameHighScore.textContent = String(best);",
    "    if (composerDinoScore) composerDinoScore.textContent = '0';",
    "    if (composerDinoHighScore) composerDinoHighScore.textContent = String(chatGameGetHighScore(DINO_GAME_ID));",
    "    chatGameSetStatusText('Press Space to start | Esc to exit');",
    "    if (clearMode && safeString(composerModeSelection?.kind) === 'game') {",
    "        composerClearMode({ closeGame: false });",
    "    }",
    "}",
    "",
    "function chatGameRestartActive() {",
    "    if (chatGameRuntime.activeGameId === 'cloud_jump') {",
    "        chatGameResetCloudJump();",
    "    } else if (chatGameRuntime.activeGameId === JETPACK_GAME_ID) {",
    "        chatGameResetJetpackJoyride();",
    "    } else if (chatGameRuntime.activeGameId === DINO_GAME_ID) {",
    "        chatGameResetDinoRun();",
    "    } else {",
    "        return;",
    "    }",
    "    chatGameRender();",
    "    chatGameStartLoop();",
    "}",
    "",
    "function chatGameRenderToTextPayload() {",
    "    const panelOpen = Boolean(",
    "        (chatGamePanel && !chatGamePanel.classList.contains('hidden'))",
    "        || (composerDinoShell && !composerDinoShell.classList.contains('hidden')),",
    "    );",
    "    const activeGame = chatGameRuntime.activeGameId || 'none';",
    "    const base = {",
    "        coordinate_system: 'origin top-left; +x right; +y down',",
    "        panel_open: panelOpen,",
    "        active_game: activeGame,",
    "    };",
    "    if (activeGame === 'cloud_jump' && chatGameRuntime.cloudJump) {",
    "        const state = chatGameRuntime.cloudJump;",
    "        return JSON.stringify({",
    "            ...base,",
    "            mode: state.mode,",
    "            score: Math.floor(state.score),",
    "            high_score: Math.floor(state.best),",
    "            door: {",
    "                visible: Boolean(state.scene?.doorVisible),",
    "                open: Number((state.scene?.doorOpen || 0).toFixed(3)),",
    "                light: Number((state.scene?.light || 0).toFixed(3)),",
    "            },",
    "            selected_agent: {",
    "                id: safeString(state.selectedAgent?.id),",
    "                name: safeString(state.selectedAgent?.name),",
    "                costume: safeString(state.selectedAgent?.costume),",
    "                color: safeString(state.selectedAgent?.color),",
    "            },",
    "            bot: {",
    "                visible: Boolean(state.scene?.botVisible),",
    "                x: Number((state.scene?.botX || 0).toFixed(2)),",
    "                y: Number((state.scene?.botY || 0).toFixed(2)),",
    "                running: Boolean(state.scene?.botRunning),",
    "            },",
    "            player: {",
    "                x: Number(state.player.x.toFixed(2)),",
    "                y: Number(state.player.y.toFixed(2)),",
    "                vx: Number(state.player.vx.toFixed(2)),",
    "                vy: Number(state.player.vy.toFixed(2)),",
    "                w: state.player.w,",
    "                h: state.player.h,",
    "            },",
    "            platforms: state.platforms.slice(0, 14).map((platform) => ({",
    "                x: Number(platform.x.toFixed(2)),",
    "                y: Number(platform.y.toFixed(2)),",
    "                w: platform.w,",
    "                h: platform.h,",
    "            })),",
    "        });",
    "    }",
    "    if (activeGame === JETPACK_GAME_ID && chatGameRuntime.jetpackJoyride) {",
    "        const state = chatGameRuntime.jetpackJoyride;",
    "        return JSON.stringify({",
    "            ...base,",
    "            mode: state.mode,",
    "            score: Math.floor(state.score),",
    "            high_score: Math.floor(state.best),",
    "            door: {",
    "                visible: Boolean(state.scene?.doorVisible),",
    "                open: Number((state.scene?.doorOpen || 0).toFixed(3)),",
    "                light: Number((state.scene?.light || 0).toFixed(3)),",
    "            },",
    "            selected_agent: {",
    "                id: safeString(state.selectedAgent?.id),",
    "                name: safeString(state.selectedAgent?.name),",
    "                costume: safeString(state.selectedAgent?.costume),",
    "                color: safeString(state.selectedAgent?.color),",
    "            },",
    "            bot: {",
    "                visible: Boolean(state.scene?.botVisible),",
    "                x: Number((state.scene?.botX || 0).toFixed(2)),",
    "                y: Number((state.scene?.botY || 0).toFixed(2)),",
    "                running: Boolean(state.scene?.botRunning),",
    "            },",
    "            player: {",
    "                x: Number(state.player.x.toFixed(2)),",
    "                y: Number(state.player.y.toFixed(2)),",
    "                vx: Number(state.player.vx.toFixed(2)),",
    "                vy: Number(state.player.vy.toFixed(2)),",
    "                w: state.player.w,",
    "                h: state.player.h,",
    "            },",
    "            obstacles: state.obstacles.slice(0, 12).map((obstacle) => {",
    "                if (obstacle.type === 'zapper') {",
    "                    return {",
    "                        type: 'zapper',",
    "                        cx: Number((obstacle.cx || 0).toFixed(2)),",
    "                        cy: Number((obstacle.cy || 0).toFixed(2)),",
    "                        length: obstacle.length,",
    "                        angle: Number((obstacle.angle || 0).toFixed(3)),",
    "                    };",
    "                }",
    "                return {",
    "                    type: obstacle.type,",
    "                    x: Number((obstacle.x || 0).toFixed(2)),",
    "                    y: Number((obstacle.y || 0).toFixed(2)),",
    "                    w: obstacle.w,",
    "                    h: obstacle.h,",
    "                };",
    "            }),",
    "        });",
    "    }",
    "    if (activeGame === DINO_GAME_ID && chatGameRuntime.dinoRun) {",
    "        const state = chatGameRuntime.dinoRun;",
    "        return JSON.stringify({",
    "            ...base,",
    "            mode: state.mode,",
    "            score: Math.floor(state.score),",
    "            high_score: Math.floor(state.best),",
    "            portal: {",
    "                visible: Boolean(state.portal?.visible),",
    "                x: Number((state.portal?.x || 0).toFixed(2)),",
    "                y: Number((state.portal?.y || 0).toFixed(2)),",
    "            },",
    "            selected_agent: {",
    "                id: safeString(state.selectedAgent?.id),",
    "                name: safeString(state.selectedAgent?.name),",
    "                costume: safeString(state.selectedAgent?.costume),",
    "                color: safeString(state.selectedAgent?.color),",
    "            },",
    "            bot: {",
    "                visible: Boolean(state.scene?.botVisible),",
    "                x: Number((state.scene?.botX || 0).toFixed(2)),",
    "                y: Number((state.scene?.botY || 0).toFixed(2)),",
    "                running: Boolean(state.scene?.botRunning),",
    "            },",
    "            player: {",
    "                x: Number(state.player.x.toFixed(2)),",
    "                y: Number(state.player.y.toFixed(2)),",
    "                vx: Number((state.player.vx || 0).toFixed(2)),",
    "                vy: Number((state.player.vy || 0).toFixed(2)),",
    "                w: state.player.w,",
    "                h: state.player.h,",
    "                ducking: Boolean(state.player.ducking),",
    "            },",
    "            obstacles: state.obstacles.slice(0, 12).map((obstacle) => ({",
    "                type: obstacle.type,",
    "                x: Number((obstacle.x || 0).toFixed(2)),",
    "                y: Number((obstacle.y || 0).toFixed(2)),",
    "                w: obstacle.w,",
    "                h: obstacle.h,",
    "            })),",
    "        });",
    "    }",
    "    if (!chatGameRuntime.cloudJump && !chatGameRuntime.jetpackJoyride && !chatGameRuntime.dinoRun) {",
    "        return JSON.stringify(base);",
    "    }",
    "    return JSON.stringify(base);",
    "}",
    "",
    "function chatGameAdvanceTime(ms = 16) {",
    "    if (!chatGameRuntime.activeGameId) return;",
    "    const totalMs = Number.isFinite(ms) ? Math.max(1, Number(ms)) : 16;",
    "    const steps = Math.max(1, Math.round(totalMs / (1000 / 60)));",
    "    for (let i = 0; i < steps; i += 1) {",
    "        chatGameStep(1);",
    "    }",
    "    chatGameRender();",
    "}",
    "",
    "window.render_game_to_text = chatGameRenderToTextPayload;",
    "window.advanceTime = chatGameAdvanceTime;",
    "",
    "function chatGameHandleKeyInput(event, pressed) {",
    "    if (!chatGameRuntime.activeGameId) return;",
    "    const target = event.target;",
    "    const targetIsInput = (",
    "        target instanceof HTMLInputElement",
    "        || target instanceof HTMLTextAreaElement",
    "        || (target instanceof HTMLElement && target.isContentEditable)",
    "    );",
    "    if (targetIsInput) return;",
    "",
    "    const key = String(event.key || '').toLowerCase();",
    "    const activeGame = chatGameRuntime.activeGameId;",
    "",
    "    if (activeGame === 'cloud_jump') {",
    "        if (key === 'arrowleft' || key === 'a') {",
    "            chatGameRuntime.input.left = pressed;",
    "            event.preventDefault();",
    "            return;",
    "        }",
    "        if (key === 'arrowright' || key === 'd') {",
    "            chatGameRuntime.input.right = pressed;",
    "            event.preventDefault();",
    "            return;",
    "        }",
    "        if (key === ' ' || key === 'spacebar') {",
    "            if (!pressed) return;",
    "            event.preventDefault();",
    "            const state = chatGameRuntime.cloudJump;",
    "            if (state?.mode === 'ready') {",
    "                chatGameStartRun(state);",
    "                return;",
    "            }",
    "            if (state?.mode === 'game_over') {",
    "                chatGameRestartActive();",
    "            }",
    "            return;",
    "        }",
    "    } else if (activeGame === JETPACK_GAME_ID) {",
    "        if (key === 'arrowup' || key === 'w') {",
    "            chatGameRuntime.input.up = pressed;",
    "            event.preventDefault();",
    "            return;",
    "        }",
    "        if (key === 'arrowdown' || key === 's') {",
    "            chatGameRuntime.input.down = pressed;",
    "            event.preventDefault();",
    "            return;",
    "        }",
    "        if (key === ' ' || key === 'spacebar') {",
    "            if (!pressed) return;",
    "            event.preventDefault();",
    "            const state = chatGameRuntime.jetpackJoyride;",
    "            if (state?.mode === 'ready') {",
    "                chatGameStartJetpackRun(state);",
    "                return;",
    "            }",
    "            if (state?.mode === 'game_over') {",
    "                chatGameRestartActive();",
    "            }",
    "            return;",
    "        }",
    "    } else if (activeGame === DINO_GAME_ID) {",
    "        const dinoState = chatGameRuntime.dinoRun;",
    "        const triggerDinoPrimary = () => {",
    "            if (!dinoState) return;",
    "            if (dinoState.mode === 'ready') {",
    "                chatGameStartDinoRun(dinoState);",
    "                return;",
    "            }",
    "            if (dinoState.mode === 'playing') {",
    "                chatGameDinoJump(dinoState);",
    "                return;",
    "            }",
    "            if (dinoState.mode === 'game_over') {",
    "                chatGameRestartActive();",
    "            }",
    "        };",
    "",
    "        if (key === 'arrowdown' || key === 's') {",
    "            chatGameRuntime.input.down = pressed;",
    "            event.preventDefault();",
    "            return;",
    "        }",
    "        if (key === 'arrowup' || key === 'w') {",
    "            chatGameRuntime.input.up = pressed;",
    "            if (!pressed) return;",
    "            event.preventDefault();",
    "            triggerDinoPrimary();",
    "            return;",
    "        }",
    "        if (key === ' ' || key === 'spacebar') {",
    "            if (!pressed) return;",
    "            event.preventDefault();",
    "            triggerDinoPrimary();",
    "            return;",
    "        }",
    "    }",
    "",
    "    if (!pressed) return;",
    "    if (key === 'r') {",
    "        chatGameRestartActive();",
    "        return;",
    "    }",
    "    if (key === 'escape') {",
    "        chatGameClose({ clearMode: true });",
    "    }",
    "}",
    "",
    "function initChatGame() {",
    "    const best = chatGameGetHighScore();",
    "    if (chatGameScore) chatGameScore.textContent = '0';",
    "    if (chatGameHighScore) chatGameHighScore.textContent = String(best);",
    "    if (composerDinoScore) composerDinoScore.textContent = '0';",
    "    if (composerDinoHighScore) composerDinoHighScore.textContent = String(chatGameGetHighScore(DINO_GAME_ID));",
    "    chatGameSetStatusText('Press Space to start | Esc to exit');",
    "    chatGameSetPanelOpen(false);",
    "    chatGameSetDinoSurfaceOpen(false);",
    "    chatGameSetCenterMuted(false);",
    "    chatGameSetPhaseClass('');",
    "    if (chatGamePanel) {",
    "        chatGamePanel.classList.remove('door-visible');",
    "        chatGamePanel.classList.remove('jetpack-mode');",
    "    }",
    "",
    "    if (chatGameCloseBtn) {",
    "        chatGameCloseBtn.addEventListener('click', () => {",
    "            chatGameClose({ clearMode: true });",
    "        });",
    "    }",
    "    if (chatGameRestartBtn) {",
    "        chatGameRestartBtn.addEventListener('click', () => {",
    "            chatGameRestartActive();",
    "        });",
    "    }",
    "",
    "    document.addEventListener('keydown', (event) => {",
    "        chatGameHandleKeyInput(event, true);",
    "    });",
    "    document.addEventListener('keyup', (event) => {",
    "        chatGameHandleKeyInput(event, false);",
    "    });",
    "}",
    "",
    "// ╔═══════════════════════════════════════════════════════════════════════════╗",
    "// ║  ACTIONS & INTERACTIONS                                                 ║",
    "// ║  Send/stop, file attach, chat search, keyboard shortcuts, streaming     ║",
    "// ╚═══════════════════════════════════════════════════════════════════════════╝",
    "",
    "function initActions() {",
    "    function prepareManualSendFromComposer() {",
    "        if (typeof window.__thomasStopMicCapture === 'function') {",
    "            window.__thomasStopMicCapture({ send: false });",
    "        }",
    "    }",
    "",
    "    sendBtn.addEventListener('click', () => {",
    "        if (isGenerating) {",
    "            const hasQueuedInput = composerTextarea.value.trim().length > 0 || pendingDocs.length > 0 || pendingImages.length > 0;",
    "            if (hasQueuedInput) {",
    "                prepareManualSendFromComposer();",
    "                void handleSend();",
    "            } else {",
    "                // It's a stop button right now",
    "                stopGeneration();",
    "            }",
    "        } else {",
    "            prepareManualSendFromComposer();",
    "            void handleSend();",
    "        }",
    "    });",
    "",
    "    // Delegated click handlers for chat area (code copy + message copy)",
    "    chatMessagesInner.addEventListener('click', (e) => {",
    "        // Code block copy button",
    "        const copyCodeBtn = e.target.closest('.code-block-copy');",
    "        if (copyCodeBtn) {",
    "            const wrapper = copyCodeBtn.closest('.code-block-wrapper');",
    "            const code = wrapper ? wrapper.querySelector('code') : null;",
    "            if (code) {",
    "                navigator.clipboard.writeText(code.textContent).then(() => {",
    "                    copyCodeBtn.innerHTML = '<i class=\"ph ph-check\"></i> Copied';",
    "                    showToast('Copied to clipboard');",
    "                    setTimeout(() => { copyCodeBtn.innerHTML = '<i class=\"ph ph-copy\"></i> Copy'; }, 2000);",
    "                });",
    "            }",
    "            return;",
    "        }",
    "        // Message copy button",
    "        const msgCopyBtn = e.target.closest('.msg-action-btn[data-action=\"copy\"]');",
    "        if (msgCopyBtn) {",
    "            const row = msgCopyBtn.closest('.message-row');",
    "            const content = row ? row.querySelector('.message-content') : null;",
    "            if (content) {",
    "                navigator.clipboard.writeText(content.innerText || content.textContent).then(() => {",
    "                    showToast('Copied to clipboard');",
    "                });",
    "            }",
    "            return;",
    "        }",
    "        // Edit user message button",
    "        const msgEditBtn = e.target.closest('.msg-action-btn[data-action=\"edit\"]');",
    "        if (msgEditBtn) {",
    "            const row = msgEditBtn.closest('.message-row');",
    "            if (row) beginEditMessage(row);",
    "            return;",
    "        }",
    "        // Regenerate assistant response button",
    "        const msgRegenBtn = e.target.closest('.msg-action-btn[data-action=\"regenerate\"]');",
    "        if (msgRegenBtn) {",
    "            const row = msgRegenBtn.closest('.message-row');",
    "            if (row) regenerateResponse(row);",
    "            return;",
    "        }",
    "        // Save edited message button",
    "        const msgSaveBtn = e.target.closest('.msg-edit-save');",
    "        if (msgSaveBtn) {",
    "            const row = msgSaveBtn.closest('.message-row');",
    "            if (row) commitEditMessage(row);",
    "            return;",
    "        }",
    "        // Cancel edit button",
    "        const msgCancelBtn = e.target.closest('.msg-edit-cancel');",
    "        if (msgCancelBtn) {",
    "            const row = msgCancelBtn.closest('.message-row');",
    "            if (row) cancelEditMessage(row);",
    "            return;",
    "        }",
    "        // Pin message button",
    "        const msgPinBtn = e.target.closest('.msg-action-btn[data-action=\"pin\"]');",
    "        if (msgPinBtn) {",
    "            const row = msgPinBtn.closest('.message-row');",
    "            if (row) togglePinMessage(row);",
    "            return;",
    "        }",
    "    });",
    "",
    "    // Attachments",
    "    attachBtn.addEventListener('click', (event) => {",
    "        event.preventDefault();",
    "        event.stopPropagation();",
    "        composerToggleActionsMenu();",
    "    });",
    "",
    "    if (composerModeChipCloseBtn) {",
    "        composerModeChipCloseBtn.addEventListener('click', (event) => {",
    "            event.preventDefault();",
    "            event.stopPropagation();",
    "            composerClearMode();",
    "            if (composerTextarea) {",
    "                composerTextarea.focus();",
    "            }",
    "        });",
    "    }",
    "",
    "    if (composerActionList) {",
    "        composerActionList.addEventListener('click', (event) => {",
    "            if (!(event.target instanceof Element)) return;",
    "            const button = event.target.closest('[data-action]');",
    "            if (!(button instanceof HTMLButtonElement)) return;",
    "            composerHandleQuickAction(button.dataset.action);",
    "        });",
    "    }",
    "    if (composerGamesColumn) {",
    "        composerGamesColumn.addEventListener('click', (event) => {",
    "            if (!(event.target instanceof Element)) return;",
    "            const button = event.target.closest('[data-game]');",
    "            if (!(button instanceof HTMLButtonElement)) return;",
    "            composerHandleGameChoice(button.dataset.game);",
    "        });",
    "    }",
    "    document.addEventListener('click', (event) => {",
    "        if (!composerActionsOpen) return;",
    "        if (!(event.target instanceof Element)) return;",
    "        if (event.target.closest('#attachBtn')) return;",
    "        if (event.target.closest('#composerActionPopover')) return;",
    "        composerCloseActionsMenu();",
    "    });",
    "    // Microphone",
    "    let recognition = null;",
    "    let micShouldListen = false;",
    "    let micIsListening = false;",
    "    let micPendingSend = false;",
    "    let micSuppressTranscriptUntil = 0;",
    "    let micBaseText = '';",
    "    let micFinalText = '';",
    "",
    "    function suppressMicTranscript(ms = 1200) {",
    "        micSuppressTranscriptUntil = Date.now() + Math.max(0, Number(ms) || 0);",
    "    }",
    "",
    "    function joinSpeechText(leftRaw, rightRaw) {",
    "        const left = safeString(leftRaw).trim();",
    "        const right = safeString(rightRaw).trim();",
    "        if (!right) return left;",
    "        if (!left) return right;",
    "        const needsSpace = !/\\s$/.test(left) && !/^[,.;:!?)]/.test(right);",
    "        return needsSpace ? `${left} ${right}` : `${left}${right}`;",
    "    }",
    "",
    "    function renderMicTranscript(interimRaw = '') {",
    "        if (!micShouldListen && !micIsListening) return;",
    "        if (Date.now() < micSuppressTranscriptUntil || Date.now() < composerInputLockUntil) return;",
    "        const spokenText = joinSpeechText(micFinalText, interimRaw);",
    "        composerTextarea.value = joinSpeechText(micBaseText, spokenText);",
    "        composerTextarea.dispatchEvent(new Event('input'));",
    "    }",
    "",
    "    function resetMicDraftState() {",
    "        micBaseText = '';",
    "        micFinalText = '';",
    "    }",
    "",
    "    function flushPendingMicSend() {",
    "        if (!micPendingSend) return;",
    "        micPendingSend = false;",
    "        suppressMicTranscript();",
    "        resetMicDraftState();",
    "        void handleSend();",
    "    }",
    "",
    "    function stopMicCapture({ send = false } = {}) {",
    "        if (!recognition) return;",
    "        micShouldListen = false;",
    "        micPendingSend = Boolean(send);",
    "        if (!micIsListening) {",
    "            micBtn.style.color = 'var(--text-secondary)';",
    "            flushPendingMicSend();",
    "            return;",
    "        }",
    "        try {",
    "            recognition.stop();",
    "        } catch {",
    "            micIsListening = false;",
    "            micBtn.style.color = 'var(--text-secondary)';",
    "            flushPendingMicSend();",
    "        }",
    "    }",
    "",
    "    function startMicCapture() {",
    "        if (!recognition || micShouldListen || micIsListening) return;",
    "        resetMicDraftState();",
    "        micBaseText = safeString(composerTextarea.value);",
    "        micPendingSend = false;",
    "        micShouldListen = true;",
    "        try {",
    "            recognition.start();",
    "        } catch {",
    "            micShouldListen = false;",
    "            micIsListening = false;",
].join("\n");
