"""DSL Framework - Domain-Specific Language toolkit."""

from ._exceptions import (
    ArityError,
    DSLException,
    LexerError,
    ParseError,
    RecursionError,
    RuntimeError,
    SourceLocation,
    TimeoutError,
    TypeError,
    UndefinedFunction,
    UndefinedVariable,
    UnificationError,
)
from ._types import (
    Assignment,
    ASTNode,
    BinaryOp,
    Block,
    BreakExpr,
    ContinueExpr,
    DictExpr,
    DSLConfig,
    DSLType,
    Environment,
    ForLoop,
    FunctionCall,
    FunctionDef,
    FunctionType,
    Identifier,
    IfExpr,
    IndexExpr,
    LambdaExpr,
    LetBinding,
    ListExpr,
    ListType,
    Literal,
    MatchExpr,
    ReturnExpr,
    SimpleType,
    Token,
    TokenType,
    TypeVariable,
    UnaryOp,
    WhileLoop,
)
from .compiler import CodeObject, Compiler, OpCode
from .interpreter import Closure, Interpreter
from .lexer import Lexer, TokenDef
from .optimizer import Optimizer
from .parser import Parser, Precedence
from .repl import REPL, REPLConfig
from .stdlib import DSLStdlib
from .type_system import TypeEnvironment, TypeInference, Unifier
from .vm import VM, CallFrame

__version__ = "1.0.0"
__all__ = [
    # Types
    "Token",
    "TokenType",
    "ASTNode",
    "Literal",
    "Identifier",
    "BinaryOp",
    "UnaryOp",
    "FunctionCall",
    "Assignment",
    "IfExpr",
    "WhileLoop",
    "ForLoop",
    "Block",
    "LetBinding",
    "LambdaExpr",
    "FunctionDef",
    "MatchExpr",
    "IndexExpr",
    "ListExpr",
    "DictExpr",
    "ReturnExpr",
    "BreakExpr",
    "ContinueExpr",
    "Environment",
    "DSLConfig",
    "SimpleType",
    "FunctionType",
    "TypeVariable",
    "ListType",
    "DSLType",
    # Exceptions
    "DSLException",
    "LexerError",
    "ParseError",
    "TypeError",
    "RuntimeError",
    "UndefinedVariable",
    "UndefinedFunction",
    "UnificationError",
    "ArityError",
    "RecursionError",
    "TimeoutError",
    "SourceLocation",
    # Components
    "Lexer",
    "TokenDef",
    "Parser",
    "Precedence",
    "TypeInference",
    "TypeEnvironment",
    "Unifier",
    "Interpreter",
    "Closure",
    "Compiler",
    "CodeObject",
    "OpCode",
    "VM",
    "CallFrame",
    "Optimizer",
    "REPL",
    "REPLConfig",
    "DSLStdlib",
]
