"""
Thomas Statistics Module

A comprehensive statistics library built from scratch with no numpy/scipy dependencies.
Includes descriptive statistics, distributions, hypothesis testing, regression, correlation,
Bayesian methods, nonparametric statistics, time series, and sampling techniques.
"""

# Exceptions
# Descriptive statistics
# Distributions
# Hypothesis testing
# Correlation
# Regression
# Bayesian
# Nonparametric
# Time series
# Sampling
from . import (
    bayesian,
    correlation,
    descriptive,
    distributions,
    hypothesis,
    nonparametric,
    regression,
    sampling,
    timeseries,
)
from ._exceptions import ConvergenceError, InsufficientDataError, StatsError

# Types
from ._types import (
    ConfidenceInterval,
    CorrelationResult,
    DescriptiveStats,
    DistributionParams,
    RegressionResult,
    SampleStats,
    TestResult,
)
from .bayesian import (
    bayes_theorem,
    bayesian_ab_test,
    beta_binomial_credible_interval,
    beta_binomial_posterior,
    credible_interval_proportion,
    highest_posterior_density,
    normal_normal_posterior,
    posterior_predictive,
)
from .correlation import (
    acf,
    autocorrelation,
    correlation_matrix,
    cross_correlation,
    kendall_tau,
    partial_correlation,
    pearson_correlation,
    point_biserial_correlation,
    spearman_correlation,
)
from .descriptive import (
    coefficient_of_variation,
    describe,
    five_number_summary,
    geometric_mean,
    harmonic_mean,
    iqr,
    kurtosis,
    mean,
    median,
    mode,
    percentile,
    quantile,
    range_val,
    skewness,
    std,
    trimmed_mean,
    variance,
    weighted_mean,
    winsorized_mean,
    z_score,
)
from .distributions import (
    beta_pdf,
    binomial_cdf,
    binomial_pmf,
    chi2_cdf,
    chi2_pdf,
    estimate_binomial_params,
    estimate_exponential_params,
    estimate_normal_params,
    estimate_poisson_params,
    exponential_cdf,
    exponential_pdf,
    f_cdf,
    f_pdf,
    gamma_pdf,
    normal_cdf,
    normal_icdf,
    normal_pdf,
    normal_sample,
    poisson_cdf,
    poisson_pmf,
    t_cdf,
    t_pdf,
    uniform_cdf,
    uniform_pdf,
)
from .hypothesis import (
    chi2_contingency,
    chi2_goodness_of_fit,
    f_test_equal_variance,
    kolmogorov_smirnov,
    mann_whitney_u,
    one_sample_t_test,
    one_way_anova,
    paired_t_test,
    two_sample_t_test,
    wilcoxon_signed_rank,
)
from .nonparametric import (
    bca_confidence_interval,
    bootstrap_confidence_interval,
    empirical_cdf,
    jackknife_resampling,
    kernel_density_estimation,
    permutation_test,
    qq_plot_values,
    silverman_bandwidth,
)
from .regression import (
    logistic_regression,
    multiple_linear_regression,
    polynomial_regression,
    prediction_interval,
    ridge_regression,
    simple_linear_regression,
    standardized_residuals,
)
from .sampling import (
    bootstrap_sample,
    finite_population_correction,
    jackknife_sample,
    power_analysis,
    reservoir_sample,
    sample_size_mean,
    sample_size_proportion,
    simple_random_sample,
    stratified_sample,
    systematic_sample,
)
from .timeseries import (
    adf_test_simplified,
    differencing,
    exponential_smoothing,
    forecast_holt,
    forecast_simple_exponential,
    holt_linear_trend,
    holt_winters,
    moving_average,
    partial_autocorrelation,
    seasonal_decomposition,
    weighted_moving_average,
)

__all__ = [
    # Exceptions
    "StatsError",
    "InsufficientDataError",
    "ConvergenceError",
    # Types
    "DescriptiveStats",
    "DistributionParams",
    "TestResult",
    "ConfidenceInterval",
    "CorrelationResult",
    "RegressionResult",
    "SampleStats",
    # Modules
    "descriptive",
    "distributions",
    "hypothesis",
    "correlation",
    "regression",
    "bayesian",
    "nonparametric",
    "timeseries",
    "sampling",
    # Descriptive
    "mean",
    "weighted_mean",
    "geometric_mean",
    "harmonic_mean",
    "median",
    "mode",
    "variance",
    "std",
    "z_score",
    "coefficient_of_variation",
    "trimmed_mean",
    "winsorized_mean",
    "percentile",
    "quantile",
    "range_val",
    "iqr",
    "skewness",
    "kurtosis",
    "five_number_summary",
    "describe",
    # Distributions
    "normal_pdf",
    "normal_cdf",
    "normal_icdf",
    "normal_sample",
    "t_pdf",
    "t_cdf",
    "chi2_pdf",
    "chi2_cdf",
    "f_pdf",
    "f_cdf",
    "binomial_pmf",
    "binomial_cdf",
    "poisson_pmf",
    "poisson_cdf",
    "exponential_pdf",
    "exponential_cdf",
    "uniform_pdf",
    "uniform_cdf",
    "beta_pdf",
    "gamma_pdf",
    "estimate_normal_params",
    "estimate_exponential_params",
    "estimate_poisson_params",
    "estimate_binomial_params",
    # Hypothesis
    "one_sample_t_test",
    "two_sample_t_test",
    "paired_t_test",
    "chi2_goodness_of_fit",
    "chi2_contingency",
    "mann_whitney_u",
    "wilcoxon_signed_rank",
    "f_test_equal_variance",
    "kolmogorov_smirnov",
    "one_way_anova",
    # Correlation
    "pearson_correlation",
    "spearman_correlation",
    "kendall_tau",
    "point_biserial_correlation",
    "partial_correlation",
    "correlation_matrix",
    "autocorrelation",
    "acf",
    "cross_correlation",
    # Regression
    "simple_linear_regression",
    "multiple_linear_regression",
    "polynomial_regression",
    "ridge_regression",
    "logistic_regression",
    "standardized_residuals",
    "prediction_interval",
    # Bayesian
    "bayes_theorem",
    "beta_binomial_posterior",
    "beta_binomial_credible_interval",
    "normal_normal_posterior",
    "bayesian_ab_test",
    "posterior_predictive",
    "highest_posterior_density",
    "credible_interval_proportion",
    # Nonparametric
    "kernel_density_estimation",
    "silverman_bandwidth",
    "bootstrap_confidence_interval",
    "bca_confidence_interval",
    "permutation_test",
    "empirical_cdf",
    "qq_plot_values",
    "jackknife_resampling",
    # Time series
    "moving_average",
    "weighted_moving_average",
    "exponential_smoothing",
    "holt_linear_trend",
    "holt_winters",
    "differencing",
    "partial_autocorrelation",
    "seasonal_decomposition",
    "adf_test_simplified",
    "forecast_simple_exponential",
    "forecast_holt",
    # Sampling
    "simple_random_sample",
    "stratified_sample",
    "systematic_sample",
    "reservoir_sample",
    "bootstrap_sample",
    "jackknife_sample",
    "sample_size_mean",
    "sample_size_proportion",
    "power_analysis",
    "finite_population_correction",
]
