"""Social platform module - A complete social media platform engine.

This module provides a full-featured social media platform with user management,
content creation, feed generation, messaging, moderation, analytics, and more.
"""

from ._exceptions import (
    AccountDeactivatedError,
    AccountSuspendedError,
    AuthenticationError,
    AuthorizationError,
    BlockedUserError,
    CommentNotFoundError,
    ContentTooLongError,
    ConversationNotFoundError,
    DuplicateActionError,
    InvalidEmailError,
    InvalidMediaError,
    InvalidOperationError,
    InvalidPasswordError,
    InvalidReactionError,
    InvalidUsernameError,
    MaxRetryError,
    MessageNotFoundError,
    ModerationError,
    NotificationNotFoundError,
    PostNotFoundError,
    PrivacyViolationError,
    RateLimitExceededError,
    SocialPlatformException,
    SpamDetectedError,
    ToxicContentError,
    UserAlreadyExistsError,
    UserNotFoundError,
)
from ._types import (
    AccountStatus,
    Block,
    Comment,
    ContentPolicy,
    ContentType,
    Conversation,
    DirectMessage,
    FeedItem,
    Follow,
    Hashtag,
    HashtagStats,
    Media,
    Mention,
    ModerationAction,
    ModerationLog,
    Notification,
    NotificationType,
    Post,
    PostStats,
    PrivacySetting,
    Reaction,
    ReactionType,
    Report,
    User,
    UserRole,
    UserStats,
)
from .analytics import AnalyticsEngine
from .content import ContentManager
from .feed import FeedEngine
from .graph import SocialGraphAnalyzer
from .messaging import MessagingManager
from .moderation import ModerationEngine
from .notifications import NotificationManager
from .privacy import PrivacyManager
from .users import UserManager

__version__ = "1.0.0"

__all__ = [
    # Types
    "User",
    "Post",
    "Comment",
    "Reaction",
    "Follow",
    "Block",
    "Report",
    "Media",
    "Hashtag",
    "Mention",
    "DirectMessage",
    "Conversation",
    "Notification",
    "FeedItem",
    "ContentPolicy",
    "UserRole",
    "PrivacySetting",
    "AccountStatus",
    "ModerationAction",
    "NotificationType",
    "ContentType",
    "ReactionType",
    "UserStats",
    "PostStats",
    "HashtagStats",
    "ModerationLog",
    # Exceptions
    "SocialPlatformException",
    "UserNotFoundError",
    "UserAlreadyExistsError",
    "InvalidUsernameError",
    "InvalidEmailError",
    "InvalidPasswordError",
    "AuthenticationError",
    "AuthorizationError",
    "PostNotFoundError",
    "CommentNotFoundError",
    "ConversationNotFoundError",
    "MessageNotFoundError",
    "NotificationNotFoundError",
    "InvalidOperationError",
    "BlockedUserError",
    "PrivacyViolationError",
    "AccountDeactivatedError",
    "AccountSuspendedError",
    "RateLimitExceededError",
    "ContentTooLongError",
    "InvalidMediaError",
    "ModerationError",
    "SpamDetectedError",
    "ToxicContentError",
    "DuplicateActionError",
    "InvalidReactionError",
    "MaxRetryError",
    # Managers
    "UserManager",
    "FeedEngine",
    "ContentManager",
    "ModerationEngine",
    "MessagingManager",
    "NotificationManager",
    "AnalyticsEngine",
    "SocialGraphAnalyzer",
    "PrivacyManager",
]
