# Alembic Configuration
# =====================
# This file is the config file for Alembic and contains settings for
# revision file generation, database and logging configuration.

[alembic]
# path to migration scripts
script_location = thomas/migrations

# template file to generate new migration scripts
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to logging.config.fileConfig.
# Leave blank for migrating without timestamps
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
