"""Agriculture module for precision farming and farm management.

A comprehensive platform for crop and livestock management, precision agriculture,
soil science, irrigation scheduling, nutrient management, and farm economics.
"""

from thomas.agriculture._exceptions import (
    AgriculturalError,
    CropError,
    EconomicsError,
    IrrigationError,
    LivestockError,
    NutrientError,
    PestError,
    PrecisionError,
    SoilError,
    WeatherError,
)
from thomas.agriculture._types import (
    Crop,
    CropVariety,
    Equipment,
    Farm,
    Fertilizer,
    Field,
    GrowthStage,
    Harvest,
    Irrigation,
    LivestockAnimal,
    MarketPrice,
    Pesticide,
    SatelliteImage,
    SensorReading,
    Soil,
    Weather,
    YieldPrediction,
)

__all__ = [
    "Farm",
    "Field",
    "Crop",
    "CropVariety",
    "Soil",
    "Weather",
    "GrowthStage",
    "Irrigation",
    "Fertilizer",
    "Pesticide",
    "Harvest",
    "Equipment",
    "SensorReading",
    "SatelliteImage",
    "YieldPrediction",
    "MarketPrice",
    "LivestockAnimal",
    "AgriculturalError",
    "CropError",
    "SoilError",
    "IrrigationError",
    "NutrientError",
    "PestError",
    "WeatherError",
    "PrecisionError",
    "LivestockError",
    "EconomicsError",
]
