/** Office asset catalog plus DOM bindings required by direct preamble contract tests. */
const navEvolutionBtn = document.getElementById('navEvolutionBtn');
const evolutionWorkspace = document.getElementById('evolutionWorkspace');

const OFFICE_DRAFT_ASSET_LIBRARY = Object.freeze({
    couch: {
        label: 'Couch',
        width: 336,
        height: 188,
        defaultColorVariant: 'caramel',
        category: 'Lounge',
        interaction: 'sit',
        description: 'Three-seat couch for breaks, waiting, and team chat.',
    },
    desk: {
        label: 'Desk',
        width: 260,
        height: 152,
        defaultColorVariant: 'walnut',
        category: 'Work',
        interaction: 'work',
        description: 'Task desk for writing, coding, planning, and review work.',
    },
    chair: {
        label: 'Chair',
        width: 116,
        height: 132,
        defaultColorVariant: 'ink',
        category: 'Work',
        interaction: 'sit',
        description: 'Movable chair that pairs with desks and tables.',
    },
    workstation: {
        label: 'Workstation',
        width: 300,
        height: 190,
        defaultColorVariant: 'neon',
        category: 'Engineering',
        interaction: 'work',
        description: 'Monitor station for code, game builds, tests, and tooling.',
    },
    whiteboard: {
        label: 'Whiteboard',
        width: 310,
        height: 174,
        defaultColorVariant: 'clean',
        category: 'Planning',
        interaction: 'present',
        description: 'Planning board for research maps, recipes, designs, and strategy.',
    },
    vending_machine: {
        label: 'Vending Machine',
        width: 150,
        height: 260,
        defaultColorVariant: 'cola',
        category: 'Break',
        interaction: 'vend',
        description: 'Break-room vending machine that lets robots grab a Coke.',
    },
    coffee_bar: {
        label: 'Coffee Bar',
        width: 310,
        height: 176,
        defaultColorVariant: 'copper',
        category: 'Break',
        interaction: 'drink',
        description: 'Coffee and drink counter for recharge animations.',
    },
    round_table: {
        label: 'Round Table',
        width: 210,
        height: 210,
        defaultColorVariant: 'oak',
        category: 'Meeting',
        interaction: 'meet',
        description: 'Small meeting table for syncs, recipe planning, and reviews.',
    },
    plant: {
        label: 'Plant',
        width: 116,
        height: 184,
        defaultColorVariant: 'fern',
        category: 'Decor',
        interaction: 'decor',
        description: 'Office plant for softening rooms without changing task logic.',
    },
    bookshelf: {
        label: 'Bookshelf',
        width: 250,
        height: 200,
        defaultColorVariant: 'archive',
        category: 'Research',
        interaction: 'research',
        description: 'Reference shelf for research, docs, writing, and content rooms.',
    },
    server_rack: {
        label: 'Server Rack',
        width: 150,
        height: 246,
        defaultColorVariant: 'datacenter',
        category: 'Ops',
        interaction: 'monitor',
        description: 'Ops rack for deploy, monitoring, and reliability work.',
    },
    focus_pod: {
        label: 'Focus Pod',
        width: 220,
        height: 250,
        defaultColorVariant: 'quiet',
        category: 'Focus',
        interaction: 'focus',
        description: 'Private pod for deep work and long-running agent tasks.',
    },
    reception_counter: {
        label: 'Reception Counter',
        width: 360,
        height: 154,
        defaultColorVariant: 'walnut',
        colorGroup: 'wood',
        shape: 'counter',
        category: 'Lobby',
        interaction: 'dispatch',
        description: 'Front desk for intake, dispatch, and office check-ins.',
    },
    conference_table: {
        label: 'Conference Table',
        width: 430,
        height: 190,
        defaultColorVariant: 'oak',
        colorGroup: 'wood',
        shape: 'table',
        category: 'Meeting',
        interaction: 'meet',
        description: 'Long meeting table for planning, reviews, and team work.',
    },
    kitchen_island: {
        label: 'Kitchen Island',
        width: 350,
        height: 176,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'counter',
        category: 'Break',
        interaction: 'food',
        description: 'Cafeteria prep island for recipes, snacks, and break traffic.',
    },
    fridge: {
        label: 'Fridge',
        width: 130,
        height: 236,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'cabinet',
        category: 'Break',
        interaction: 'food',
        description: 'Break-room fridge for food and drink interactions.',
    },
    microwave: {
        label: 'Microwave',
        width: 156,
        height: 104,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'appliance',
        category: 'Break',
        interaction: 'food',
        description: 'Countertop microwave for cafeteria detail.',
    },
    water_cooler: {
        label: 'Water Cooler',
        width: 104,
        height: 190,
        defaultColorVariant: 'glass',
        colorGroup: 'clean',
        shape: 'tower',
        category: 'Break',
        interaction: 'drink',
        description: 'Water cooler for quick recharge stops.',
    },
    snack_shelf: {
        label: 'Snack Shelf',
        width: 216,
        height: 178,
        defaultColorVariant: 'market',
        colorGroup: 'warm',
        shape: 'shelf',
        category: 'Break',
        interaction: 'food',
        description: 'Snack shelf for break-room and recipe spaces.',
    },
    printer: {
        label: 'Printer',
        width: 192,
        height: 136,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'machine',
        category: 'Office',
        interaction: 'print',
        description: 'Shared printer for support, docs, and office workflows.',
    },
    filing_cabinet: {
        label: 'Filing Cabinet',
        width: 142,
        height: 184,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'cabinet',
        category: 'Office',
        interaction: 'archive',
        description: 'File cabinet for admin, support, and research rooms.',
    },
    archive_box: {
        label: 'Archive Box',
        width: 124,
        height: 94,
        defaultColorVariant: 'cardboard',
        colorGroup: 'warm',
        shape: 'box',
        category: 'Office',
        interaction: 'archive',
        description: 'Movable archive box for storage corners and mail areas.',
    },
    floor_lamp: {
        label: 'Floor Lamp',
        width: 92,
        height: 220,
        defaultColorVariant: 'amber',
        colorGroup: 'light',
        shape: 'lamp',
        category: 'Decor',
        interaction: 'decor',
        description: 'Floor lamp for lounge, focus, and design spaces.',
    },
    wall_monitor: {
        label: 'Wall Monitor',
        width: 250,
        height: 145,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'screen',
        category: 'Engineering',
        interaction: 'monitor',
        description: 'Wall display for dashboards, game builds, and ops status.',
    },
    kanban_board: {
        label: 'Kanban Board',
        width: 270,
        height: 168,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'board',
        category: 'Planning',
        interaction: 'present',
        description: 'Task board for planning rooms and work queues.',
    },
    blueprint_table: {
        label: 'Blueprint Table',
        width: 320,
        height: 176,
        defaultColorVariant: 'blueprint',
        colorGroup: 'tech',
        shape: 'table',
        category: 'Planning',
        interaction: 'plan',
        description: 'Wide table for layouts, recipes, and build plans.',
    },
    lab_bench: {
        label: 'Lab Bench',
        width: 340,
        height: 162,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'bench',
        category: 'Engineering',
        interaction: 'work',
        description: 'Bench for testing, debugging, and build work.',
    },
    tool_cart: {
        label: 'Tool Cart',
        width: 162,
        height: 138,
        defaultColorVariant: 'warning',
        colorGroup: 'warm',
        shape: 'cart',
        category: 'Engineering',
        interaction: 'tools',
        description: 'Rolling cart for engineering and repair rooms.',
    },
    charging_dock: {
        label: 'Charging Dock',
        width: 236,
        height: 128,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'dock',
        category: 'Robots',
        interaction: 'charge',
        description: 'Robot charging dock for idle and lobby areas.',
    },
    router_node: {
        label: 'Router Node',
        width: 168,
        height: 118,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'node',
        category: 'Ops',
        interaction: 'network',
        description: 'Network node for ops, integrations, and automation rooms.',
    },
    security_console: {
        label: 'Security Console',
        width: 310,
        height: 168,
        defaultColorVariant: 'warning',
        colorGroup: 'tech',
        shape: 'console',
        category: 'Ops',
        interaction: 'monitor',
        description: 'Monitoring console for incidents and reliability work.',
    },
    standing_desk: {
        label: 'Standing Desk',
        width: 238,
        height: 168,
        defaultColorVariant: 'steel',
        colorGroup: 'wood',
        shape: 'desk',
        category: 'Work',
        interaction: 'work',
        description: 'Compact standing desk for active work rooms.',
    },
    drafting_table: {
        label: 'Drafting Table',
        width: 282,
        height: 172,
        defaultColorVariant: 'oak',
        colorGroup: 'wood',
        shape: 'tilt_table',
        category: 'Design',
        interaction: 'design',
        description: 'Angled table for visual design and product sketches.',
    },
    camera_tripod: {
        label: 'Camera Tripod',
        width: 120,
        height: 205,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'tripod',
        category: 'Content',
        interaction: 'record',
        description: 'Tripod camera for content, video, and product demos.',
    },
    light_panel: {
        label: 'Light Panel',
        width: 142,
        height: 214,
        defaultColorVariant: 'clean',
        colorGroup: 'light',
        shape: 'light',
        category: 'Content',
        interaction: 'record',
        description: 'Studio light panel for content and design rooms.',
    },
    acoustic_panel: {
        label: 'Acoustic Panel',
        width: 184,
        height: 116,
        defaultColorVariant: 'berry',
        colorGroup: 'soft',
        shape: 'panel',
        category: 'Content',
        interaction: 'decor',
        description: 'Sound panel for recording and focus areas.',
    },
    rug: {
        label: 'Rug',
        width: 360,
        height: 220,
        defaultColorVariant: 'moss',
        colorGroup: 'soft',
        shape: 'rug',
        category: 'Decor',
        interaction: 'decor',
        description: 'Soft rug that defines sitting and meeting zones.',
    },
    divider: {
        label: 'Divider',
        width: 220,
        height: 156,
        defaultColorVariant: 'slate',
        colorGroup: 'soft',
        shape: 'divider',
        category: 'Decor',
        interaction: 'decor',
        description: 'Low divider for shaping room flow without blocking editing.',
    },
    bean_bag: {
        label: 'Bean Bag',
        width: 150,
        height: 120,
        defaultColorVariant: 'berry',
        colorGroup: 'soft',
        shape: 'soft_seat',
        category: 'Lounge',
        interaction: 'sit',
        description: 'Small casual seat for lounges and brainstorm rooms.',
    },
    arcade_cabinet: {
        label: 'Arcade Cabinet',
        width: 128,
        height: 230,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'cabinet',
        category: 'Lounge',
        interaction: 'play',
        description: 'Break-room arcade cabinet for personality and game tasks.',
    },
    trophy_shelf: {
        label: 'Trophy Shelf',
        width: 210,
        height: 168,
        defaultColorVariant: 'amber',
        colorGroup: 'light',
        shape: 'shelf',
        category: 'Decor',
        interaction: 'decor',
        description: 'Shelf for shipped wins, badges, and team trophies.',
    },
    package_station: {
        label: 'Package Station',
        width: 300,
        height: 170,
        defaultColorVariant: 'cardboard',
        colorGroup: 'warm',
        shape: 'counter',
        category: 'Ops',
        interaction: 'sort',
        description: 'Ops station for packages, files, and dispatch workflows.',
    },
    mail_sorter: {
        label: 'Mail Sorter',
        width: 220,
        height: 170,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'shelf',
        category: 'Support',
        interaction: 'sort',
        description: 'Inbox sorter for support tickets and admin flows.',
    },
    recipe_counter: {
        label: 'Recipe Counter',
        width: 318,
        height: 168,
        defaultColorVariant: 'mint',
        colorGroup: 'clean',
        shape: 'counter',
        category: 'Break',
        interaction: 'food',
        description: 'Kitchen counter for recipe tasks and food planning.',
    },
    floor_sign: {
        label: 'Floor Sign',
        width: 94,
        height: 142,
        defaultColorVariant: 'warning',
        colorGroup: 'warm',
        shape: 'sign',
        category: 'Decor',
        interaction: 'decor',
        description: 'Small wayfinding sign for corridors and room doors.',
    },
    bench: {
        label: 'Bench',
        width: 260,
        height: 112,
        defaultColorVariant: 'oak',
        colorGroup: 'wood',
        shape: 'bench',
        category: 'Lounge',
        interaction: 'sit',
        description: 'Low bench for waiting areas, hall edges, and break rooms.',
    },
    side_table: {
        label: 'Side Table',
        width: 150,
        height: 118,
        defaultColorVariant: 'oak',
        colorGroup: 'wood',
        shape: 'table',
        category: 'Lounge',
        interaction: 'decor',
        description: 'Small table for seating clusters and coffee corners.',
    },
    task_lamp: {
        label: 'Task Lamp',
        width: 82,
        height: 156,
        defaultColorVariant: 'clean',
        colorGroup: 'light',
        shape: 'lamp',
        category: 'Decor',
        interaction: 'decor',
        description: 'Desk-style lamp for workstations and reading corners.',
    },
    ottoman: {
        label: 'Ottoman',
        width: 142,
        height: 104,
        defaultColorVariant: 'moss',
        colorGroup: 'soft',
        shape: 'soft_seat',
        category: 'Lounge',
        interaction: 'sit',
        description: 'Soft movable seat for lounges and team rooms.',
    },
    lounge_chair: {
        label: 'Lounge Chair',
        width: 160,
        height: 146,
        defaultColorVariant: 'berry',
        colorGroup: 'soft',
        shape: 'soft_seat',
        category: 'Lounge',
        interaction: 'sit',
        description: 'Single-seat chair that fits beside couches and small tables.',
    },
    loveseat: {
        label: 'Loveseat',
        width: 238,
        height: 154,
        defaultColorVariant: 'moss',
        colorGroup: 'soft',
        shape: 'soft_seat',
        category: 'Lounge',
        interaction: 'sit',
        description: 'Compact couch for smaller rooms and focus corners.',
    },
    meeting_chair: {
        label: 'Meeting Chair',
        width: 104,
        height: 116,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'soft_seat',
        category: 'Meeting',
        interaction: 'sit',
        description: 'Slim meeting chair for conference and planning tables.',
    },
    stool: {
        label: 'Stool',
        width: 84,
        height: 102,
        defaultColorVariant: 'walnut',
        colorGroup: 'wood',
        shape: 'soft_seat',
        category: 'Break',
        interaction: 'sit',
        description: 'Small stool for kitchen counters and quick work stops.',
    },
    monitor_stand: {
        label: 'Monitor Stand',
        width: 180,
        height: 108,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'screen',
        category: 'Engineering',
        interaction: 'monitor',
        description: 'Raised monitor stand for desk setups and review stations.',
    },
    laptop: {
        label: 'Laptop',
        width: 150,
        height: 96,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'screen',
        category: 'Work',
        interaction: 'work',
        description: 'Portable computer prop for flexible agent work spots.',
    },
    tablet_stand: {
        label: 'Tablet Stand',
        width: 104,
        height: 126,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'screen',
        category: 'Work',
        interaction: 'work',
        description: 'Small tablet station for checklists and quick prompts.',
    },
    keyboard_tray: {
        label: 'Keyboard Tray',
        width: 170,
        height: 72,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'panel',
        category: 'Engineering',
        interaction: 'work',
        description: 'Low tray for computer desks and coding stations.',
    },
    dual_monitor: {
        label: 'Dual Monitor',
        width: 238,
        height: 130,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'screen',
        category: 'Engineering',
        interaction: 'monitor',
        description: 'Dual screen setup for code, tests, and dashboards.',
    },
    code_terminal: {
        label: 'Code Terminal',
        width: 214,
        height: 142,
        defaultColorVariant: 'blueprint',
        colorGroup: 'tech',
        shape: 'console',
        category: 'Engineering',
        interaction: 'work',
        description: 'Terminal console for build and debugging rooms.',
    },
    testing_rig: {
        label: 'Testing Rig',
        width: 250,
        height: 150,
        defaultColorVariant: 'warning',
        colorGroup: 'tech',
        shape: 'machine',
        category: 'Engineering',
        interaction: 'tools',
        description: 'QA rig for running checks, devices, and build validation.',
    },
    game_console: {
        label: 'Game Console',
        width: 168,
        height: 108,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'machine',
        category: 'Lounge',
        interaction: 'play',
        description: 'Small game console for breaks and game-task flavor.',
    },
    vr_headset: {
        label: 'VR Headset',
        width: 120,
        height: 92,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'machine',
        category: 'Design',
        interaction: 'design',
        description: 'VR headset prop for visual and prototype work.',
    },
    sound_mixer: {
        label: 'Sound Mixer',
        width: 210,
        height: 126,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'console',
        category: 'Content',
        interaction: 'record',
        description: 'Audio mixer for video, music, and podcast rooms.',
    },
    microphone: {
        label: 'Microphone',
        width: 86,
        height: 176,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'tower',
        category: 'Content',
        interaction: 'record',
        description: 'Standing microphone for content and voice work.',
    },
    podcast_desk: {
        label: 'Podcast Desk',
        width: 310,
        height: 160,
        defaultColorVariant: 'walnut',
        colorGroup: 'wood',
        shape: 'desk',
        category: 'Content',
        interaction: 'record',
        description: 'Content desk with enough room for audio and notes.',
    },
    camera_case: {
        label: 'Camera Case',
        width: 130,
        height: 92,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'box',
        category: 'Content',
        interaction: 'record',
        description: 'Equipment case for studio corners and production spaces.',
    },
    green_screen: {
        label: 'Green Screen',
        width: 300,
        height: 178,
        defaultColorVariant: 'moss',
        colorGroup: 'soft',
        shape: 'panel',
        category: 'Content',
        interaction: 'record',
        description: 'Backdrop panel for recording and image generation spaces.',
    },
    prop_shelf: {
        label: 'Prop Shelf',
        width: 220,
        height: 166,
        defaultColorVariant: 'walnut',
        colorGroup: 'wood',
        shape: 'shelf',
        category: 'Content',
        interaction: 'archive',
        description: 'Shelf for video props, thumbnails, and creative assets.',
    },
    pinboard: {
        label: 'Pinboard',
        width: 240,
        height: 142,
        defaultColorVariant: 'cardboard',
        colorGroup: 'warm',
        shape: 'board',
        category: 'Planning',
        interaction: 'present',
        description: 'Pinned notes board for design, research, and planning.',
    },
    sticky_note_wall: {
        label: 'Sticky Note Wall',
        width: 270,
        height: 152,
        defaultColorVariant: 'warning',
        colorGroup: 'warm',
        shape: 'board',
        category: 'Planning',
        interaction: 'plan',
        description: 'Wall of notes for strategy, recipes, and task breakdowns.',
    },
    map_table: {
        label: 'Map Table',
        width: 300,
        height: 164,
        defaultColorVariant: 'blueprint',
        colorGroup: 'tech',
        shape: 'table',
        category: 'Research',
        interaction: 'research',
        description: 'Wide table for source maps, routes, and investigation plans.',
    },
    research_terminal: {
        label: 'Research Terminal',
        width: 232,
        height: 148,
        defaultColorVariant: 'blueprint',
        colorGroup: 'tech',
        shape: 'console',
        category: 'Research',
        interaction: 'research',
        description: 'Terminal for lookup-heavy research and analysis tasks.',
    },
    microscope: {
        label: 'Microscope',
        width: 108,
        height: 154,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'machine',
        category: 'Research',
        interaction: 'research',
        description: 'Detail prop for careful investigation rooms.',
    },
    sample_tray: {
        label: 'Sample Tray',
        width: 150,
        height: 86,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'box',
        category: 'Research',
        interaction: 'research',
        description: 'Small tray for grouped findings and reference items.',
    },
    data_wall: {
        label: 'Data Wall',
        width: 330,
        height: 182,
        defaultColorVariant: 'blueprint',
        colorGroup: 'tech',
        shape: 'screen',
        category: 'Ops',
        interaction: 'monitor',
        description: 'Large dashboard wall for metrics, data, and monitoring.',
    },
    server_console: {
        label: 'Server Console',
        width: 260,
        height: 150,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'console',
        category: 'Ops',
        interaction: 'monitor',
        description: 'Control console for servers and deployment tasks.',
    },
    power_panel: {
        label: 'Power Panel',
        width: 150,
        height: 188,
        defaultColorVariant: 'warning',
        colorGroup: 'tech',
        shape: 'cabinet',
        category: 'Ops',
        interaction: 'monitor',
        description: 'Utility panel for infra and automation rooms.',
    },
    network_switch: {
        label: 'Network Switch',
        width: 196,
        height: 92,
        defaultColorVariant: 'neon',
        colorGroup: 'tech',
        shape: 'node',
        category: 'Ops',
        interaction: 'network',
        description: 'Network switch for integration and reliability spaces.',
    },
    firewall_box: {
        label: 'Firewall Box',
        width: 152,
        height: 124,
        defaultColorVariant: 'warning',
        colorGroup: 'tech',
        shape: 'box',
        category: 'Ops',
        interaction: 'network',
        description: 'Security appliance for ops and infrastructure rooms.',
    },
    dispatch_board: {
        label: 'Dispatch Board',
        width: 280,
        height: 156,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'board',
        category: 'Support',
        interaction: 'dispatch',
        description: 'Assignment board for tickets, agents, and handoffs.',
    },
    ticket_kiosk: {
        label: 'Ticket Kiosk',
        width: 148,
        height: 210,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'tower',
        category: 'Support',
        interaction: 'support',
        description: 'Self-serve ticket kiosk for support desks and lobbies.',
    },
    phone_booth: {
        label: 'Phone Booth',
        width: 168,
        height: 238,
        defaultColorVariant: 'slate',
        colorGroup: 'soft',
        shape: 'cabinet',
        category: 'Support',
        interaction: 'focus',
        description: 'Private booth for calls, support replies, and focus work.',
    },
    copier: {
        label: 'Copier',
        width: 186,
        height: 132,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'machine',
        category: 'Office',
        interaction: 'print',
        description: 'Shared copier for admin and document-heavy rooms.',
    },
    shredder: {
        label: 'Shredder',
        width: 98,
        height: 140,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'machine',
        category: 'Office',
        interaction: 'archive',
        description: 'Office shredder for support and admin corners.',
    },
    mail_cart: {
        label: 'Mail Cart',
        width: 158,
        height: 124,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'cart',
        category: 'Support',
        interaction: 'sort',
        description: 'Rolling mail cart for dispatch and support rooms.',
    },
    storage_locker: {
        label: 'Storage Locker',
        width: 158,
        height: 220,
        defaultColorVariant: 'steel',
        colorGroup: 'metal',
        shape: 'cabinet',
        category: 'Office',
        interaction: 'archive',
        description: 'Tall locker for equipment, tools, and office supplies.',
    },
    trash_bin: {
        label: 'Trash Bin',
        width: 84,
        height: 108,
        defaultColorVariant: 'graphite',
        colorGroup: 'metal',
        shape: 'box',
        category: 'Office',
        interaction: 'decor',
        description: 'Small bin for realistic office corners.',
    },
    coat_rack: {
        label: 'Coat Rack',
        width: 84,
        height: 190,
        defaultColorVariant: 'walnut',
        colorGroup: 'wood',
        shape: 'tower',
        category: 'Lobby',
        interaction: 'decor',
        description: 'Coat rack for lobbies and reception spaces.',
    },
    wall_clock: {
        label: 'Wall Clock',
        width: 86,
        height: 86,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'panel',
        category: 'Decor',
        interaction: 'decor',
        description: 'Small wall clock for rooms that need office detail.',
    },
    tall_plant: {
        label: 'Tall Plant',
        width: 106,
        height: 236,
        defaultColorVariant: 'moss',
        colorGroup: 'soft',
        shape: 'tower',
        category: 'Decor',
        interaction: 'decor',
        description: 'Tall plant for corners and hallway-adjacent spaces.',
    },
    planter_box: {
        label: 'Planter Box',
        width: 220,
        height: 96,
        defaultColorVariant: 'moss',
        colorGroup: 'soft',
        shape: 'box',
        category: 'Decor',
        interaction: 'decor',
        description: 'Low planter for shaping room edges without looking empty.',
    },
    room_sign: {
        label: 'Room Sign',
        width: 134,
        height: 82,
        defaultColorVariant: 'clean',
        colorGroup: 'clean',
        shape: 'sign',
        category: 'Decor',
        interaction: 'decor',
        description: 'Small room sign for labels, wayfinding, and door detail.',
    },
    snack_table: {
        label: 'Snack Table',
        width: 238,
        height: 126,
        defaultColorVariant: 'market',
        colorGroup: 'warm',
        shape: 'table',
        category: 'Break',
        interaction: 'food',
        description: 'Snack table for break rooms and recipe work.',
    },
    soda_crate: {
        label: 'Soda Crate',
        width: 126,
        height: 88,
        defaultColorVariant: 'market',
        colorGroup: 'warm',
        shape: 'box',
        category: 'Break',
        interaction: 'drink',
        description: 'Crate of sodas for vending and break-room detail.',
    },
    tea_station: {
        label: 'Tea Station',
        width: 196,
        height: 122,
        defaultColorVariant: 'mint',
        colorGroup: 'clean',
        shape: 'counter',
        category: 'Break',
        interaction: 'drink',
        description: 'Small drink station for coffee, tea, and recharge stops.',
    },
});
const OFFICE_DRAFT_ASSET_COLORWAYS = Object.freeze({
    couch: Object.freeze({
        caramel: {
            label: 'Caramel',
            back: 'linear-gradient(180deg, rgba(212, 160, 117, 0.98), rgba(162, 105, 69, 0.98))',
            seat: 'linear-gradient(180deg, rgba(223, 176, 132, 1), rgba(175, 117, 78, 0.98))',
            arm: 'linear-gradient(180deg, rgba(190, 132, 92, 0.98), rgba(141, 87, 56, 0.98))',
            seam: 'rgba(112, 63, 37, 0.34)',
            swatch: 'linear-gradient(180deg, #d4a075, #9f6844)',
        },
        moss: {
            label: 'Moss',
            back: 'linear-gradient(180deg, rgba(146, 172, 126, 0.98), rgba(92, 118, 76, 0.98))',
            seat: 'linear-gradient(180deg, rgba(170, 195, 147, 1), rgba(108, 138, 89, 0.98))',
            arm: 'linear-gradient(180deg, rgba(126, 150, 106, 0.98), rgba(83, 106, 66, 0.98))',
            seam: 'rgba(52, 74, 42, 0.34)',
            swatch: 'linear-gradient(180deg, #9cbc81, #63814f)',
        },
        harbor: {
            label: 'Harbor',
            back: 'linear-gradient(180deg, rgba(123, 158, 198, 0.98), rgba(73, 104, 145, 0.98))',
            seat: 'linear-gradient(180deg, rgba(153, 187, 224, 1), rgba(86, 122, 168, 0.98))',
            arm: 'linear-gradient(180deg, rgba(100, 134, 176, 0.98), rgba(65, 94, 131, 0.98))',
            seam: 'rgba(38, 62, 94, 0.34)',
            swatch: 'linear-gradient(180deg, #8bb0d7, #5678a7)',
        },
        graphite: {
            label: 'Graphite',
            back: 'linear-gradient(180deg, rgba(122, 130, 143, 0.98), rgba(76, 83, 97, 0.98))',
            seat: 'linear-gradient(180deg, rgba(153, 161, 175, 1), rgba(92, 100, 116, 0.98))',
            arm: 'linear-gradient(180deg, rgba(106, 113, 126, 0.98), rgba(67, 74, 86, 0.98))',
            seam: 'rgba(42, 48, 59, 0.34)',
            swatch: 'linear-gradient(180deg, #98a0ac, #5f6773)',
        },
    }),
    desk: Object.freeze({
        walnut: {
            label: 'Walnut',
            body: 'linear-gradient(180deg, rgba(157, 112, 72, 0.98), rgba(103, 67, 42, 0.98))',
            surface: 'linear-gradient(180deg, rgba(214, 164, 102, 0.98), rgba(145, 91, 52, 0.98))',
            accent: 'rgba(248, 206, 142, 0.86)',
            line: 'rgba(80, 45, 24, 0.38)',
            swatch: 'linear-gradient(180deg, #d2a066, #805532)',
        },
        steel: {
            label: 'Steel',
            body: 'linear-gradient(180deg, rgba(121, 142, 166, 0.98), rgba(70, 84, 103, 0.98))',
            surface: 'linear-gradient(180deg, rgba(177, 194, 211, 0.98), rgba(105, 124, 146, 0.98))',
            accent: 'rgba(178, 215, 255, 0.84)',
            line: 'rgba(44, 58, 78, 0.42)',
            swatch: 'linear-gradient(180deg, #aebfd1, #677b91)',
        },
    }),
    chair: Object.freeze({
        ink: {
            label: 'Ink',
            body: 'linear-gradient(180deg, rgba(74, 90, 118, 0.98), rgba(38, 49, 70, 0.98))',
            surface: 'linear-gradient(180deg, rgba(107, 128, 165, 0.98), rgba(54, 70, 101, 0.98))',
            accent: 'rgba(169, 204, 255, 0.78)',
            line: 'rgba(23, 31, 47, 0.42)',
            swatch: 'linear-gradient(180deg, #6b80a5, #364665)',
        },
        berry: {
            label: 'Berry',
            body: 'linear-gradient(180deg, rgba(160, 87, 129, 0.98), rgba(99, 48, 82, 0.98))',
            surface: 'linear-gradient(180deg, rgba(214, 132, 177, 0.98), rgba(136, 70, 114, 0.98))',
            accent: 'rgba(255, 199, 226, 0.8)',
            line: 'rgba(83, 33, 64, 0.4)',
            swatch: 'linear-gradient(180deg, #d684b1, #874671)',
        },
    }),
    workstation: Object.freeze({
        neon: {
            label: 'Neon',
            body: 'linear-gradient(180deg, rgba(58, 75, 105, 0.98), rgba(24, 34, 54, 0.98))',
            surface: 'linear-gradient(180deg, rgba(91, 115, 151, 0.98), rgba(44, 61, 91, 0.98))',
            accent: 'rgba(99, 232, 255, 0.9)',
            line: 'rgba(11, 23, 38, 0.46)',
            swatch: 'linear-gradient(180deg, #63e8ff, #324a7a)',
        },
        amber: {
            label: 'Amber',
            body: 'linear-gradient(180deg, rgba(87, 83, 70, 0.98), rgba(42, 43, 44, 0.98))',
            surface: 'linear-gradient(180deg, rgba(134, 121, 92, 0.98), rgba(70, 68, 62, 0.98))',
            accent: 'rgba(255, 204, 112, 0.92)',
            line: 'rgba(41, 33, 22, 0.44)',
            swatch: 'linear-gradient(180deg, #ffc96e, #535047)',
        },
    }),
    whiteboard: Object.freeze({
        clean: {
            label: 'Clean',
            body: 'linear-gradient(180deg, rgba(238, 246, 255, 0.98), rgba(198, 214, 232, 0.98))',
            surface: 'linear-gradient(180deg, rgba(255, 255, 255, 0.98), rgba(222, 234, 247, 0.98))',
            accent: 'rgba(77, 142, 234, 0.92)',
            line: 'rgba(94, 116, 145, 0.42)',
            swatch: 'linear-gradient(180deg, #f5fbff, #c9d8e8)',
        },
        lime: {
            label: 'Lime',
            body: 'linear-gradient(180deg, rgba(217, 245, 198, 0.98), rgba(164, 205, 134, 0.98))',
            surface: 'linear-gradient(180deg, rgba(242, 255, 230, 0.98), rgba(186, 226, 156, 0.98))',
            accent: 'rgba(65, 142, 83, 0.9)',
            line: 'rgba(68, 116, 60, 0.38)',
            swatch: 'linear-gradient(180deg, #efffde, #a7cc87)',
        },
    }),
    vending_machine: Object.freeze({
        cola: {
            label: 'Cola Red',
            body: 'linear-gradient(180deg, rgba(215, 68, 70, 0.98), rgba(122, 30, 41, 0.98))',
            surface: 'linear-gradient(180deg, rgba(255, 91, 88, 0.98), rgba(161, 41, 51, 0.98))',
            accent: 'rgba(255, 239, 214, 0.94)',
            line: 'rgba(93, 22, 31, 0.45)',
            swatch: 'linear-gradient(180deg, #ef5555, #8d2531)',
        },
        citrus: {
            label: 'Citrus',
            body: 'linear-gradient(180deg, rgba(110, 177, 92, 0.98), rgba(52, 101, 59, 0.98))',
            surface: 'linear-gradient(180deg, rgba(160, 222, 108, 0.98), rgba(77, 137, 71, 0.98))',
            accent: 'rgba(255, 244, 135, 0.95)',
            line: 'rgba(33, 72, 43, 0.42)',
            swatch: 'linear-gradient(180deg, #a2df6c, #4c8847)',
        },
    }),
    coffee_bar: Object.freeze({
        copper: {
            label: 'Copper',
            body: 'linear-gradient(180deg, rgba(171, 105, 61, 0.98), rgba(91, 56, 39, 0.98))',
            surface: 'linear-gradient(180deg, rgba(225, 158, 94, 0.98), rgba(133, 82, 50, 0.98))',
            accent: 'rgba(255, 219, 166, 0.86)',
            line: 'rgba(70, 41, 26, 0.43)',
            swatch: 'linear-gradient(180deg, #d9955a, #784a31)',
        },
        mint: {
            label: 'Mint',
            body: 'linear-gradient(180deg, rgba(92, 159, 145, 0.98), rgba(48, 92, 87, 0.98))',
            surface: 'linear-gradient(180deg, rgba(132, 213, 196, 0.98), rgba(73, 134, 125, 0.98))',
            accent: 'rgba(225, 255, 249, 0.86)',
            line: 'rgba(30, 72, 68, 0.42)',
            swatch: 'linear-gradient(180deg, #81d4c4, #49857c)',
        },
    }),
    round_table: Object.freeze({
        oak: {
            label: 'Oak',
            body: 'linear-gradient(180deg, rgba(194, 137, 79, 0.98), rgba(111, 73, 43, 0.98))',
            surface: 'linear-gradient(180deg, rgba(231, 180, 106, 0.98), rgba(153, 96, 54, 0.98))',
            accent: 'rgba(255, 222, 159, 0.82)',
            line: 'rgba(91, 52, 25, 0.42)',
            swatch: 'linear-gradient(180deg, #e2ae69, #935e38)',
        },
        glass: {
            label: 'Glass',
            body: 'linear-gradient(180deg, rgba(109, 149, 178, 0.56), rgba(58, 88, 117, 0.74))',
            surface: 'linear-gradient(180deg, rgba(186, 232, 255, 0.66), rgba(89, 142, 181, 0.74))',
            accent: 'rgba(228, 249, 255, 0.92)',
            line: 'rgba(60, 90, 119, 0.42)',
            swatch: 'linear-gradient(180deg, #c1eaff, #5d8db4)',
        },
    }),
    plant: Object.freeze({
        fern: {
            label: 'Fern',
            body: 'linear-gradient(180deg, rgba(68, 135, 76, 0.98), rgba(37, 82, 48, 0.98))',
            surface: 'linear-gradient(180deg, rgba(126, 193, 101, 0.98), rgba(54, 119, 65, 0.98))',
            accent: 'rgba(221, 176, 112, 0.9)',
            line: 'rgba(31, 67, 39, 0.4)',
            swatch: 'linear-gradient(180deg, #7bc166, #367842)',
        },
        blossom: {
            label: 'Blossom',
            body: 'linear-gradient(180deg, rgba(90, 151, 87, 0.98), rgba(51, 92, 54, 0.98))',
            surface: 'linear-gradient(180deg, rgba(148, 211, 118, 0.98), rgba(73, 135, 72, 0.98))',
            accent: 'rgba(255, 177, 210, 0.9)',
            line: 'rgba(42, 78, 43, 0.4)',
            swatch: 'linear-gradient(180deg, #93d276, #498648)',
        },
    }),
    bookshelf: Object.freeze({
        archive: {
            label: 'Archive',
            body: 'linear-gradient(180deg, rgba(139, 94, 61, 0.98), rgba(81, 55, 39, 0.98))',
            surface: 'linear-gradient(180deg, rgba(183, 125, 72, 0.98), rgba(103, 69, 43, 0.98))',
            accent: 'rgba(116, 178, 243, 0.9)',
            line: 'rgba(62, 39, 24, 0.42)',
            swatch: 'linear-gradient(180deg, #b47b49, #65442b)',
        },
        library: {
            label: 'Library',
            body: 'linear-gradient(180deg, rgba(86, 105, 119, 0.98), rgba(46, 59, 73, 0.98))',
            surface: 'linear-gradient(180deg, rgba(126, 145, 160, 0.98), rgba(68, 84, 101, 0.98))',
            accent: 'rgba(238, 206, 134, 0.92)',
            line: 'rgba(32, 42, 54, 0.45)',
            swatch: 'linear-gradient(180deg, #7f91a0, #465565)',
        },
    }),
    server_rack: Object.freeze({
        datacenter: {
            label: 'Datacenter',
            body: 'linear-gradient(180deg, rgba(57, 68, 83, 0.98), rgba(21, 29, 42, 0.98))',
            surface: 'linear-gradient(180deg, rgba(89, 104, 123, 0.98), rgba(36, 48, 66, 0.98))',
            accent: 'rgba(106, 255, 178, 0.92)',
            line: 'rgba(10, 18, 31, 0.5)',
            swatch: 'linear-gradient(180deg, #6affb2, #28364b)',
        },
        warning: {
            label: 'Warning',
            body: 'linear-gradient(180deg, rgba(78, 68, 53, 0.98), rgba(35, 33, 32, 0.98))',
            surface: 'linear-gradient(180deg, rgba(112, 95, 68, 0.98), rgba(55, 51, 47, 0.98))',
            accent: 'rgba(255, 197, 76, 0.94)',
            line: 'rgba(31, 25, 20, 0.46)',
            swatch: 'linear-gradient(180deg, #ffc54c, #37322f)',
        },
    }),
    focus_pod: Object.freeze({
        quiet: {
            label: 'Quiet',
            body: 'linear-gradient(180deg, rgba(93, 105, 135, 0.98), rgba(48, 57, 82, 0.98))',
            surface: 'linear-gradient(180deg, rgba(133, 151, 189, 0.98), rgba(72, 84, 119, 0.98))',
            accent: 'rgba(203, 225, 255, 0.88)',
            line: 'rgba(40, 49, 72, 0.43)',
            swatch: 'linear-gradient(180deg, #8797bc, #465476)',
        },
        sunrise: {
            label: 'Sunrise',
            body: 'linear-gradient(180deg, rgba(171, 112, 99, 0.98), rgba(96, 61, 65, 0.98))',
            surface: 'linear-gradient(180deg, rgba(223, 153, 125, 0.98), rgba(130, 80, 77, 0.98))',
            accent: 'rgba(255, 220, 152, 0.9)',
            line: 'rgba(75, 44, 45, 0.43)',
            swatch: 'linear-gradient(180deg, #de997d, #80514d)',
        },
    }),
    wood: Object.freeze({
        walnut: {
            label: 'Walnut',
            body: 'linear-gradient(180deg, rgba(151, 101, 62, 0.98), rgba(86, 55, 36, 0.98))',
            surface: 'linear-gradient(180deg, rgba(221, 164, 95, 0.98), rgba(138, 87, 48, 0.98))',
            accent: 'rgba(255, 213, 139, 0.9)',
            line: 'rgba(76, 43, 24, 0.45)',
            swatch: 'linear-gradient(180deg, #dba160, #80512d)',
        },
        oak: {
            label: 'Oak',
            body: 'linear-gradient(180deg, rgba(186, 143, 83, 0.98), rgba(111, 76, 39, 0.98))',
            surface: 'linear-gradient(180deg, rgba(232, 190, 116, 0.98), rgba(153, 102, 51, 0.98))',
            accent: 'rgba(255, 229, 158, 0.9)',
            line: 'rgba(88, 57, 28, 0.42)',
            swatch: 'linear-gradient(180deg, #e9bd75, #996633)',
        },
        steel: {
            label: 'Steel',
            body: 'linear-gradient(180deg, rgba(117, 135, 155, 0.98), rgba(63, 76, 95, 0.98))',
            surface: 'linear-gradient(180deg, rgba(180, 196, 211, 0.98), rgba(104, 121, 142, 0.98))',
            accent: 'rgba(190, 224, 255, 0.86)',
            line: 'rgba(47, 58, 75, 0.45)',
            swatch: 'linear-gradient(180deg, #b4c4d3, #667891)',
        },
    }),
    tech: Object.freeze({
        neon: {
            label: 'Neon',
            body: 'linear-gradient(180deg, rgba(49, 68, 103, 0.98), rgba(19, 29, 52, 0.98))',
            surface: 'linear-gradient(180deg, rgba(82, 105, 145, 0.98), rgba(38, 57, 91, 0.98))',
            accent: 'rgba(94, 232, 255, 0.94)',
            line: 'rgba(7, 16, 30, 0.5)',
            swatch: 'linear-gradient(180deg, #5ee8ff, #26395b)',
        },
        warning: {
            label: 'Warning',
            body: 'linear-gradient(180deg, rgba(82, 72, 54, 0.98), rgba(35, 34, 36, 0.98))',
            surface: 'linear-gradient(180deg, rgba(121, 102, 71, 0.98), rgba(58, 55, 51, 0.98))',
            accent: 'rgba(255, 203, 74, 0.96)',
            line: 'rgba(29, 24, 18, 0.5)',
            swatch: 'linear-gradient(180deg, #ffcb4a, #34312e)',
        },
        blueprint: {
            label: 'Blueprint',
            body: 'linear-gradient(180deg, rgba(59, 100, 146, 0.98), rgba(31, 56, 98, 0.98))',
            surface: 'linear-gradient(180deg, rgba(90, 146, 194, 0.98), rgba(45, 82, 136, 0.98))',
            accent: 'rgba(203, 238, 255, 0.95)',
            line: 'rgba(24, 49, 82, 0.45)',
            swatch: 'linear-gradient(180deg, #5b92c2, #2d5288)',
        },
    }),
    metal: Object.freeze({
        steel: {
            label: 'Steel',
            body: 'linear-gradient(180deg, rgba(135, 150, 166, 0.98), rgba(74, 87, 104, 0.98))',
            surface: 'linear-gradient(180deg, rgba(195, 207, 218, 0.98), rgba(112, 129, 148, 0.98))',
            accent: 'rgba(220, 239, 255, 0.9)',
            line: 'rgba(45, 56, 71, 0.46)',
            swatch: 'linear-gradient(180deg, #c2cfd9, #728295)',
        },
        graphite: {
            label: 'Graphite',
            body: 'linear-gradient(180deg, rgba(95, 103, 116, 0.98), rgba(43, 49, 61, 0.98))',
            surface: 'linear-gradient(180deg, rgba(136, 146, 160, 0.98), rgba(73, 82, 99, 0.98))',
            accent: 'rgba(178, 198, 226, 0.88)',
            line: 'rgba(30, 36, 47, 0.48)',
            swatch: 'linear-gradient(180deg, #87919f, #485263)',
        },
    }),
    clean: Object.freeze({
        clean: {
            label: 'Clean',
            body: 'linear-gradient(180deg, rgba(221, 232, 238, 0.98), rgba(159, 178, 190, 0.98))',
            surface: 'linear-gradient(180deg, rgba(250, 255, 255, 0.98), rgba(204, 222, 229, 0.98))',
            accent: 'rgba(94, 173, 220, 0.9)',
            line: 'rgba(94, 116, 130, 0.42)',
            swatch: 'linear-gradient(180deg, #f4fbff, #c9dde6)',
        },
        glass: {
            label: 'Glass',
            body: 'linear-gradient(180deg, rgba(121, 177, 207, 0.72), rgba(67, 112, 146, 0.82))',
            surface: 'linear-gradient(180deg, rgba(219, 248, 255, 0.88), rgba(141, 206, 228, 0.82))',
            accent: 'rgba(240, 255, 255, 0.96)',
            line: 'rgba(60, 101, 126, 0.42)',
            swatch: 'linear-gradient(180deg, #d7f8ff, #86cbdc)',
        },
        mint: {
            label: 'Mint',
            body: 'linear-gradient(180deg, rgba(90, 158, 143, 0.98), rgba(47, 91, 85, 0.98))',
            surface: 'linear-gradient(180deg, rgba(133, 214, 197, 0.98), rgba(72, 134, 124, 0.98))',
            accent: 'rgba(225, 255, 249, 0.9)',
            line: 'rgba(29, 70, 66, 0.44)',
            swatch: 'linear-gradient(180deg, #83d6c5, #48867c)',
        },
    }),
    warm: Object.freeze({
        cardboard: {
            label: 'Cardboard',
            body: 'linear-gradient(180deg, rgba(176, 128, 76, 0.98), rgba(116, 78, 43, 0.98))',
            surface: 'linear-gradient(180deg, rgba(214, 160, 93, 0.98), rgba(145, 94, 50, 0.98))',
            accent: 'rgba(255, 223, 159, 0.88)',
            line: 'rgba(91, 57, 29, 0.45)',
            swatch: 'linear-gradient(180deg, #d6a05d, #8f5e32)',
        },
        market: {
            label: 'Market',
            body: 'linear-gradient(180deg, rgba(166, 91, 72, 0.98), rgba(91, 58, 53, 0.98))',
            surface: 'linear-gradient(180deg, rgba(219, 139, 90, 0.98), rgba(130, 83, 63, 0.98))',
            accent: 'rgba(255, 211, 106, 0.94)',
            line: 'rgba(72, 40, 36, 0.45)',
            swatch: 'linear-gradient(180deg, #db8b5a, #80533f)',
        },
        warning: {
            label: 'Warning',
            body: 'linear-gradient(180deg, rgba(196, 132, 48, 0.98), rgba(107, 70, 38, 0.98))',
            surface: 'linear-gradient(180deg, rgba(240, 172, 67, 0.98), rgba(147, 94, 45, 0.98))',
            accent: 'rgba(255, 238, 148, 0.94)',
            line: 'rgba(89, 54, 24, 0.45)',
            swatch: 'linear-gradient(180deg, #f0ac43, #935e2d)',
        },
    }),
    soft: Object.freeze({
        berry: {
            label: 'Berry',
            body: 'linear-gradient(180deg, rgba(151, 88, 134, 0.98), rgba(88, 51, 93, 0.98))',
            surface: 'linear-gradient(180deg, rgba(207, 130, 178, 0.98), rgba(123, 74, 128, 0.98))',
            accent: 'rgba(255, 201, 230, 0.9)',
            line: 'rgba(68, 39, 75, 0.42)',
            swatch: 'linear-gradient(180deg, #cf82b2, #7b4a80)',
        },
        moss: {
            label: 'Moss',
            body: 'linear-gradient(180deg, rgba(120, 151, 99, 0.98), rgba(72, 99, 67, 0.98))',
            surface: 'linear-gradient(180deg, rgba(162, 194, 132, 0.98), rgba(94, 128, 83, 0.98))',
            accent: 'rgba(223, 255, 181, 0.86)',
            line: 'rgba(50, 73, 43, 0.42)',
            swatch: 'linear-gradient(180deg, #a1c183, #5d8052)',
        },
        slate: {
            label: 'Slate',
            body: 'linear-gradient(180deg, rgba(104, 119, 144, 0.98), rgba(58, 71, 93, 0.98))',
            surface: 'linear-gradient(180deg, rgba(145, 162, 192, 0.98), rgba(78, 95, 126, 0.98))',
            accent: 'rgba(208, 226, 255, 0.86)',
            line: 'rgba(39, 50, 72, 0.44)',
            swatch: 'linear-gradient(180deg, #91a2c0, #4e5f7e)',
        },
    }),
    light: Object.freeze({
        amber: {
            label: 'Amber',
            body: 'linear-gradient(180deg, rgba(117, 87, 54, 0.98), rgba(62, 51, 44, 0.98))',
            surface: 'linear-gradient(180deg, rgba(230, 179, 88, 0.98), rgba(139, 96, 48, 0.98))',
            accent: 'rgba(255, 225, 125, 0.98)',
            line: 'rgba(71, 52, 31, 0.45)',
            swatch: 'linear-gradient(180deg, #ffd86e, #895f31)',
        },
        clean: {
            label: 'Clean',
            body: 'linear-gradient(180deg, rgba(181, 199, 209, 0.98), rgba(91, 108, 123, 0.98))',
            surface: 'linear-gradient(180deg, rgba(244, 250, 255, 0.98), rgba(187, 211, 224, 0.98))',
            accent: 'rgba(238, 252, 255, 0.98)',
            line: 'rgba(75, 91, 107, 0.45)',
            swatch: 'linear-gradient(180deg, #f2fbff, #b8d1de)',
        },
    }),
});
