/** Settings and advanced-control DOM bindings. */

const settingAdvMaxParallelTools = document.getElementById('settingAdvMaxParallelTools');
const settingAdvRequireCommandApproval = document.getElementById('settingAdvRequireCommandApproval');
const settingAdvBreakglassWindowEnabled = document.getElementById('settingAdvBreakglassWindowEnabled');
const settingAdvBreakglassWindowHours = document.getElementById('settingAdvBreakglassWindowHours');
const settingAdvAllowShell = document.getElementById('settingAdvAllowShell');
const settingAdvAllowFileWrite = document.getElementById('settingAdvAllowFileWrite');
const settingAdvAllowNetwork = document.getElementById('settingAdvAllowNetwork');
const settingAdvAllowBrowser = document.getElementById('settingAdvAllowBrowser');
const settingAdvAllowChannels = document.getElementById('settingAdvAllowChannels');
const settingAdvAllowGit = document.getElementById('settingAdvAllowGit');
const settingAdvAllowedPaths = document.getElementById('settingAdvAllowedPaths');
const settingAdvBlockedCommands = document.getElementById('settingAdvBlockedCommands');
const settingAdvIncludeGlobalMemory = document.getElementById('settingAdvIncludeGlobalMemory');
const settingAdvRetrievalTopK = document.getElementById('settingAdvRetrievalTopK');
const settingAdvMaxPackTokens = document.getElementById('settingAdvMaxPackTokens');
const settingAdvDecayHalfLifeHours = document.getElementById('settingAdvDecayHalfLifeHours');
const settingAdvAutoSummarizeThreshold = document.getElementById('settingAdvAutoSummarizeThreshold');
const settingAdvMemoryDecayDays = document.getElementById('settingAdvMemoryDecayDays');
const settingAdvAutoCompactEnabled = document.getElementById('settingAdvAutoCompactEnabled');
const settingAdvAutoCompactEpisodeThreshold = document.getElementById('settingAdvAutoCompactEpisodeThreshold');
const settingAdvAutoCompactMinIntervalHours = document.getElementById('settingAdvAutoCompactMinIntervalHours');
const settingAdvAutoOptimizeEnabled = document.getElementById('settingAdvAutoOptimizeEnabled');
const settingAdvAutoOptimizeWasteThreshold = document.getElementById('settingAdvAutoOptimizeWasteThreshold');
const settingAdvAutoOptimizeMinIntervalHours = document.getElementById('settingAdvAutoOptimizeMinIntervalHours');
const settingAdvContradictionPolicy = document.getElementById('settingAdvContradictionPolicy');
const settingAdvContextPruneStrategy = document.getElementById('settingAdvContextPruneStrategy');
const settingAdvIncludeProfileMemory = document.getElementById('settingAdvIncludeProfileMemory');
const settingAdvIncludeThreadMemory = document.getElementById('settingAdvIncludeThreadMemory');
const settingAdvPinsOnly = document.getElementById('settingAdvPinsOnly');
const settingAdvPinnedContext = document.getElementById('settingAdvPinnedContext');
const settingAdvSessionTokenBudget = document.getElementById('settingAdvSessionTokenBudget');
const settingAdvDailyTokenBudget = document.getElementById('settingAdvDailyTokenBudget');
const settingAdvMaxRetries = document.getElementById('settingAdvMaxRetries');
const settingAdvRetryBackoffMs = document.getElementById('settingAdvRetryBackoffMs');
const settingAdvThrottleOnBudget = document.getElementById('settingAdvThrottleOnBudget');
const settingAdvLowCostMode = document.getElementById('settingAdvLowCostMode');
const settingAdvProviderFailoverChain = document.getElementById('settingAdvProviderFailoverChain');
const settingAdvModelFailoverChain = document.getElementById('settingAdvModelFailoverChain');
const settingAdvFailoverEnabled = document.getElementById('settingAdvFailoverEnabled');
const settingAdvChatAutoFailover = document.getElementById('settingAdvChatAutoFailover');
const settingAdvFallbackOnAuthError = document.getElementById('settingAdvFallbackOnAuthError');
const settingAdvFailoverCooldownSeconds = document.getElementById('settingAdvFailoverCooldownSeconds');
const settingAdvRetentionDays = document.getElementById('settingAdvRetentionDays');
const settingAdvTelemetryEnabled = document.getElementById('settingAdvTelemetryEnabled');
const settingAdvRedactSecretsInLogs = document.getElementById('settingAdvRedactSecretsInLogs');
const settingAdvPiiGuardStrict = document.getElementById('settingAdvPiiGuardStrict');
const settingAdvLocalOnlyMode = document.getElementById('settingAdvLocalOnlyMode');
const settingAdvAuditLogEnabled = document.getElementById('settingAdvAuditLogEnabled');
const settingAdvExportOnExit = document.getElementById('settingAdvExportOnExit');
const settingAdvUiDensity = document.getElementById('settingAdvUiDensity');
const settingAdvCodeTheme = document.getElementById('settingAdvCodeTheme');
const settingAdvEventLogVerbosity = document.getElementById('settingAdvEventLogVerbosity');
const settingAdvShowTimestamps = document.getElementById('settingAdvShowTimestamps');
const settingAdvShowTokenMeter = document.getElementById('settingAdvShowTokenMeter');
const settingAdvAnimationFidelity = document.getElementById('settingAdvAnimationFidelity');
const settingAdvAnimationsEnabled = document.getElementById('settingAdvAnimationsEnabled');
const settingAdvDebugPanelEnabled = document.getElementById('settingAdvDebugPanelEnabled');
const settingAdvLabsFlags = document.getElementById('settingAdvLabsFlags');
// ── New Settings: Workspaces ──
const settingWsMission = document.getElementById('settingWsMission');
const settingWsAppBuilder = document.getElementById('settingWsAppBuilder');
const settingWsMyStuff = document.getElementById('settingWsMyStuff');
const settingWsChannels = document.getElementById('settingWsChannels');
const settingWsTokenEconomy = document.getElementById('settingWsTokenEconomy');
const settingWsMarketplace = document.getElementById('settingWsMarketplace');
const settingWsOffice = document.getElementById('settingWsOffice');
// ── New Settings: Token Economy ──
const settingTeMonthlyBudget = document.getElementById('settingTeMonthlyBudget');
const settingTeBudgetAlertPct = document.getElementById('settingTeBudgetAlertPct');
const settingTeShowSidebarSpend = document.getElementById('settingTeShowSidebarSpend');
const settingTeAutoSummarize = document.getElementById('settingTeAutoSummarize');
// ── New Settings: Channels ──
const settingChDefaultChannel = document.getElementById('settingChDefaultChannel');
const settingChMaxMessageLength = document.getElementById('settingChMaxMessageLength');
const settingChAutoRoute = document.getElementById('settingChAutoRoute');
const settingChNotifications = document.getElementById('settingChNotifications');
const settingChAllowUploads = document.getElementById('settingChAllowUploads');
// ── New Settings: Marketplace & Plugins ──
const settingMpAutoUpdate = document.getElementById('settingMpAutoUpdate');
const settingMpShowDomainModules = document.getElementById('settingMpShowDomainModules');
const settingMpPluginNetworkAccess = document.getElementById('settingMpPluginNetworkAccess');
// ── New Settings: Data & Storage ──
const settingDataPersistHistory = document.getElementById('settingDataPersistHistory');
const settingDataAutoArchive = document.getElementById('settingDataAutoArchive');
const sidebarUserAvatar = document.getElementById('sidebarUserAvatar');
const sidebarChatPanel = document.getElementById('sidebarChatPanel');
const searchOverlayBar = document.getElementById('searchOverlayBar');
const sidebarChatList = document.getElementById('sidebarChatList');
const sidebarSearchModeLabel = document.getElementById('sidebarSearchModeLabel');
const sidebarChatHeaderLabel = document.getElementById('sidebarChatHeaderLabel');
const taskContinuityPanel = document.getElementById('taskContinuityPanel');
const taskContinuityStatusPill = document.getElementById('taskContinuityStatusPill');
const taskContinuityGoal = document.getElementById('taskContinuityGoal');
const taskContinuityBlockersWrap = document.getElementById('taskContinuityBlockersWrap');
const taskContinuityBlockersList = document.getElementById('taskContinuityBlockersList');
const taskContinuityProgress = document.getElementById('taskContinuityProgress');
const taskContinuityEventsList = document.getElementById('taskContinuityEventsList');
const taskContinuityUpdatedAt = document.getElementById('taskContinuityUpdatedAt');
const taskContinuitySession = document.getElementById('taskContinuitySession');
const taskContinuityRefreshBtn = document.getElementById('taskContinuityRefreshBtn');
const debugDockToggleBtn = document.getElementById('debugDockToggleBtn');
const debugDock = document.getElementById('debugDock');
const debugDockCloseBtn = document.getElementById('debugDockCloseBtn');
const debugDockRefreshBtn = document.getElementById('debugDockRefreshBtn');
const debugDockTabs = document.getElementById('debugDockTabs');
const debugTabRuntime = document.getElementById('debugTabRuntime');
const debugTabSystem = document.getElementById('debugTabSystem');
const debugTabModels = document.getElementById('debugTabModels');
const debugTabTools = document.getElementById('debugTabTools');
const debugTabMemory = document.getElementById('debugTabMemory');
const debugTabRuns = document.getElementById('debugTabRuns');
const debugTabEvents = document.getElementById('debugTabEvents');
const debugTabConsole = document.getElementById('debugTabConsole');
const debugTabNetwork = document.getElementById('debugTabNetwork');
const debugPanelRuntime = document.getElementById('debugPanelRuntime');
const debugPanelSystem = document.getElementById('debugPanelSystem');
const debugPanelModels = document.getElementById('debugPanelModels');
const debugPanelTools = document.getElementById('debugPanelTools');
const debugPanelMemory = document.getElementById('debugPanelMemory');
const debugPanelRuns = document.getElementById('debugPanelRuns');
const debugPanelEvents = document.getElementById('debugPanelEvents');
const debugPanelConsole = document.getElementById('debugPanelConsole');
const debugPanelNetwork = document.getElementById('debugPanelNetwork');
const debugCopySnapshotBtn = document.getElementById('debugCopySnapshotBtn');
const debugClearEventsBtn = document.getElementById('debugClearEventsBtn');
const debugClearConsoleBtn = document.getElementById('debugClearConsoleBtn');
const debugClearNetworkBtn = document.getElementById('debugClearNetworkBtn');
const debugEventLog = document.getElementById('debugEventLog');
const debugConsoleLog = document.getElementById('debugConsoleLog');
const debugNetworkLog = document.getElementById('debugNetworkLog');
const debugSessionId = document.getElementById('debugSessionId');
const debugModel = document.getElementById('debugModel');
const debugMessageCount = document.getElementById('debugMessageCount');
const debugGenerating = document.getElementById('debugGenerating');
const debugSidebarState = document.getElementById('debugSidebarState');
const debugSearchScope = document.getElementById('debugSearchScope');
const debugThemeName = document.getElementById('debugThemeName');
const debugViewport = document.getElementById('debugViewport');
const debugEventCount = document.getElementById('debugEventCount');
const debugConsoleCount = document.getElementById('debugConsoleCount');
const debugNetworkCount = document.getElementById('debugNetworkCount');
const debugNetworkTotal = document.getElementById('debugNetworkTotal');
const debugNetworkErrors = document.getElementById('debugNetworkErrors');
const debugNetworkAvgMs = document.getElementById('debugNetworkAvgMs');
const debugSystemVersion = document.getElementById('debugSystemVersion');
const debugSystemReady = document.getElementById('debugSystemReady');
const debugSystemEngineCount = document.getElementById('debugSystemEngineCount');
const debugSystemStatus = document.getElementById('debugSystemStatus');
const debugSystemEngineList = document.getElementById('debugSystemEngineList');
const debugOnboardingGateStatusPill = document.getElementById('debugOnboardingGateStatusPill');
const debugOnboardingCompletionRate = document.getElementById('debugOnboardingCompletionRate');
const debugOnboardingMedianReadySeconds = document.getElementById('debugOnboardingMedianReadySeconds');
const debugOnboardingRepairBtn = document.getElementById('debugOnboardingRepairBtn');
const debugOnboardingGateStatus = document.getElementById('debugOnboardingGateStatus');
const debugOnboardingGateList = document.getElementById('debugOnboardingGateList');
const debugModelsDefault = document.getElementById('debugModelsDefault');
const debugModelsCount = document.getElementById('debugModelsCount');
const debugModelsHealthy = document.getElementById('debugModelsHealthy');
const debugModelHealthList = document.getElementById('debugModelHealthList');
const debugToolsTotal = document.getElementById('debugToolsTotal');
const debugToolsCategories = document.getElementById('debugToolsCategories');
const debugToolCategoryList = document.getElementById('debugToolCategoryList');
const debugToolRegistryList = document.getElementById('debugToolRegistryList');
const debugWebhooksCount = document.getElementById('debugWebhooksCount');
const debugWebhooksWithSecret = document.getElementById('debugWebhooksWithSecret');
const debugWebhooksInboxCount = document.getElementById('debugWebhooksInboxCount');
const debugWebhooksList = document.getElementById('debugWebhooksList');
const debugWebhooksInboxList = document.getElementById('debugWebhooksInboxList');
const debugMemoryEnabled = document.getElementById('debugMemoryEnabled');
const debugMemoryPins = document.getElementById('debugMemoryPins');
const debugMemoryContradictions = document.getElementById('debugMemoryContradictions');
const debugMemoryList = document.getElementById('debugMemoryList');
const debugRunsCount = document.getElementById('debugRunsCount');
const debugRunsFailed = document.getElementById('debugRunsFailed');
const debugRunsList = document.getElementById('debugRunsList');
const robotAlertStage = document.getElementById('robotAlertStage');
const robotAlertDoor = document.getElementById('robotAlertDoor');
const robotAlertBot = document.getElementById('robotAlertBot');
const robotAlertBubble = document.getElementById('robotAlertBubble');

// New Phase 7 Elements
const chatHistorySelector = document.getElementById('chatHistorySelector');
const globalSearchInput = document.getElementById('globalSearchInput');

// Phase 6 Model Setup Elements
const modelSetupBtn = document.getElementById('modelSetupBtn');
const modelSetupCurrentLabel = document.getElementById('modelSetupCurrentLabel');
const modelSetupModal = document.getElementById('modelSetupModal');
const closeModelSetupBtn = document.getElementById('closeModelSetupBtn');
const applyModelSetupBtn = document.getElementById('applyModelSetupBtn');
const setupProviderSelector = document.getElementById('setupProviderSelector');
const setupProviderPicker = document.getElementById('setupProviderPicker');
const setupProviderPickerBtn = document.getElementById('setupProviderPickerBtn');
const setupProviderPickerLabel = document.getElementById('setupProviderPickerLabel');
const setupProviderPickerState = document.getElementById('setupProviderPickerState');
const setupProviderMenu = document.getElementById('setupProviderMenu');
const setupPersonalitySelector = document.getElementById('setupPersonalitySelector');
const customPersonalityGroup = document.getElementById('customPersonalityGroup');
const setupCustomPrompt = document.getElementById('setupCustomPrompt');
const setupAutonomyGroup = document.getElementById('setupAutonomyGroup');
const setupEconomyGroup = document.getElementById('setupEconomyGroup');
const setupMemoryToggle = document.getElementById('setupMemoryToggle');
const setupModelSelector = document.getElementById('setupModelSelector');
const setupSpecialtyRoleSelector = document.getElementById('setupSpecialtyRoleSelector');
const setupSpecialtyProviderSelector = document.getElementById('setupSpecialtyProviderSelector');
const setupSpecialtyModelSelector = document.getElementById('setupSpecialtyModelSelector');
const setupSpecialtyClearBtn = document.getElementById('setupSpecialtyClearBtn');
const setupSpecialtyStatus = document.getElementById('setupSpecialtyStatus');
const restartServerBtn = document.getElementById('restartServerBtn');
const restartOverlay = document.getElementById('restartOverlay');
const rerunEasySetupBtn = document.getElementById('rerunEasySetupBtn');

const easySetupModal = document.getElementById('easySetupModal');
const easySetupBackdrop = document.getElementById('easySetupBackdrop');
const easySetupCloseBtn = document.getElementById('easySetupCloseBtn');
const easySetupProgressFill = document.getElementById('easySetupProgressFill');
const easySetupProgressText = document.getElementById('easySetupProgressText');
const easySetupStep1 = document.getElementById('easySetupStep1');
const easySetupStep2 = document.getElementById('easySetupStep2');
const easySetupStep3 = document.getElementById('easySetupStep3');
const easySetupStep4 = document.getElementById('easySetupStep4');
const easySetupStep5 = document.getElementById('easySetupStep5');
const easySetupPathGrid = document.getElementById('easySetupPathGrid');
const easySetupRecommendedHint = document.getElementById('easySetupRecommendedHint');
const easySetupConnectionMeta = document.getElementById('easySetupConnectionMeta');
const easySetupCodexBlock = document.getElementById('easySetupCodexBlock');
const easySetupManualBlock = document.getElementById('easySetupManualBlock');
const easySetupLocalBlock = document.getElementById('easySetupLocalBlock');
const easySetupCodexMeta = document.getElementById('easySetupCodexMeta');
const easySetupManualProfile = document.getElementById('easySetupManualProfile');
const easySetupManualApiKey = document.getElementById('easySetupManualApiKey');
const easySetupManualPersist = document.getElementById('easySetupManualPersist');
const easySetupLocalProfile = document.getElementById('easySetupLocalProfile');
const easySetupTestConnectionBtn = document.getElementById('easySetupTestConnectionBtn');
const easySetupAutoRepairBtn = document.getElementById('easySetupAutoRepairBtn');
const easySetupConnectionStatus = document.getElementById('easySetupConnectionStatus');
const easySetupDependencyList = document.getElementById('easySetupDependencyList');
const easySetupDependencyTrustNote = document.getElementById('easySetupDependencyTrustNote');
const easySetupApproveAllBtn = document.getElementById('easySetupApproveAllBtn');
const easySetupReviewDownloadsBtn = document.getElementById('easySetupReviewDownloadsBtn');
const easySetupReviewPanel = document.getElementById('easySetupReviewPanel');
const easySetupDependencyStatus = document.getElementById('easySetupDependencyStatus');
const easySetupAnimationGrid = document.getElementById('easySetupAnimationGrid');
const easySetupAnimationHint = document.getElementById('easySetupAnimationHint');
const easySetupReadyList = document.getElementById('easySetupReadyList');
const easySetupBackBtn = document.getElementById('easySetupBackBtn');
const easySetupDismissBtn = document.getElementById('easySetupDismissBtn');
const easySetupNextBtn = document.getElementById('easySetupNextBtn');

function getSettingAdvChatPhysicsToggle() {
    return document.getElementById('settingAdvChatPhysicsEnabled');
}

function getEasySetupPhysicsToggle() {
    return document.getElementById('easySetupPhysicsToggle');
}

let activeAutonomyLevel = 1;
let activeTokenEconomy = 'balanced';
let activeReasoningEffort = '';
let activeGuardrails = (() => { try { return localStorage.getItem('thomasGuardrails') || 'guarded'; } catch (e) { return 'guarded'; } })();
// File-access permission ladder for the worker: read_only | workspace | project | pc | full.
// Default 'workspace' (sandbox-confined) — dial up to let Thomas write to your PC.
let activeFileAccess = (() => { try { return localStorage.getItem('thomasFileAccess') || 'workspace'; } catch (e) { return 'workspace'; } })();
let activeModelOverride = '';
let activeChatMode = '';
let autonomyLevelManuallySet = false;
const KNOWN_MODEL_SUGGESTIONS = {
    codex: ['gpt-5.3-codex', 'gpt-5.2-codex', 'gpt-5.1-codex-max', 'gpt-5.2', 'gpt-5.1-codex-mini'],
    openai_codex: ['gpt-5.5', 'gpt-5.4', 'gpt-5.3-codex', 'gpt-5.2-codex'],
};

