import type { Metadata } from "next";
import { RoadmapShell, type RoadmapChapter } from "@/components/roadmap-shell";

export const metadata: Metadata = {
  title: "Thomas Roadmap",
  description: "The current Thomas core, the Infinite phone layer, and the long-range Thomas OS plan.",
};

const repoSnapshot = {
  release: "v0.14.38 / pre-alpha",
  stamp: "Current repo state across the March 17-18, 2026 shipping streak.",
  signals: [
    "Startup router, guided vs expert modes, and approval-gated execution are already live.",
    "Agent presence monitoring, plugins, local-project launchers, and control-plane surfaces are already in the repo.",
    "Research and evolve loops are in flight, which means Thomas is already moving past one-shot prompt execution.",
  ],
};

const roadmapChapters: RoadmapChapter[] = [
  {
    id: "thomas-core",
    phase: "Phase 01",
    status: "Current build / Pre-Alpha",
    title: "Thomas Core",
    horizon: "Shipping now",
    intro: "Lock down the trust boundary, make local execution useful, and make the system feel dependable before the surface area gets bigger.",
    body: "This is the current repo story. Thomas already has approval-gated execution, release-linked evidence, plugin runtime surfaces, local project launchers, research and evolve loops, and agent coordination infrastructure. The next job is tightening that stack until it feels coherent instead of experimental.",
    outcome: "Thomas becomes a dependable local execution layer with enough trust, extensibility, and operator clarity to support everything that comes after it.",
    repoSignals: ["Startup router", "Agent presence monitor", "Desktop plugin runtime", "My Stuff launcher", "Research + Evolve"],
    checkpoints: [
      {
        id: "core-boundary",
        title: "Trust boundary and execution contracts",
        status: "Live in repo",
        horizon: "Now",
        summary: "Keep the AI useful without letting it slip past approvals, route rules, or release evidence.",
        detail: "Thomas already routes work through command families, explicit approvals, and release-linked signals. This checkpoint is about tightening that core until operator trust is the default feeling, not a best-effort promise.",
        signals: [
          "Approval-gated local execution path",
          "Command family contracts and policy checks",
          "Release-linked observability and artifact evidence",
        ],
        tone: "live",
        featured: true,
      },
      {
        id: "core-surfaces",
        title: "Programmable local surfaces",
        status: "Live in repo",
        horizon: "Now",
        summary: "Turn local workflows into clear launch surfaces instead of making users live in the terminal forever.",
        detail: "The current repo has linked local projects, the My Stuff launcher surface, and a web UI that is becoming more operational. That matters because the roadmap only works if Thomas can package capability into interfaces people can actually use.",
        signals: [
          "Local project registry and launcher API",
          "My Stuff one-click launcher surface",
          "Web and desktop surfaces converging on operator workflows",
        ],
        tone: "live",
      },
      {
        id: "core-plugins",
        title: "Desktop plugins and extension economy",
        status: "Live in repo",
        horizon: "Now",
        summary: "The plugin runtime is the first signal that Thomas can become a platform, not just one app.",
        detail: "Desktop plugins, hosted bundle plumbing, marketplace install flows, and the Life Manager plugin already exist. The next quality bar is making that system safer, cleaner, and easier to trust for real operator workflows.",
        signals: [
          "Desktop plugin runtime and hosted store contract",
          "Life Manager bundled plugin",
          "Marketplace install, enable, disable, and uninstall flows",
        ],
        tone: "live",
      },
      {
        id: "core-loops",
        title: "Research, evolve, and coordination loops",
        status: "Building now",
        horizon: "Current branch",
        summary: "Thomas is starting to manage longer-running improvement loops instead of acting like a one-request toy.",
        detail: "The research runtime, evolve workflow, startup router, and repo-scoped presence monitor all push Thomas toward a system that can coordinate effort, inspect itself, and keep making forward progress without losing operational clarity.",
        signals: ["Research programs with tracked artifacts", "Blue/green evolve workflow", "Repo-scoped agent presence plus startup router"],
        tone: "build",
        featured: true,
      },
    ],
  },
  {
    id: "thomas-infinite",
    phase: "Phase 02",
    status: "Next major milestone",
    title: "Thomas Infinite",
    horizon: "Private phone layer",
    intro: "Take Thomas off the desk and turn it into a private app network you can carry around without giving up the local core.",
    body: "Thomas Infinite is the phase where the system can generate headless web surfaces for specific jobs, move them over Tailscale, and present them on your phone without handing execution off to a public cloud. Thomas stays the policy engine. The phone becomes the private control surface.",
    outcome: "Thomas gains a private mobile layer where any workflow it can build locally can also become a focused app surface, approval queue, or live control panel in your pocket.",
    repoSignals: ["Control plane patterns already exist", "Phone layer is the next unlock", "Tailscale transport target", "Journey page placeholder exists"],
    checkpoints: [
      {
        id: "infinite-transport",
        title: "Private pairing and transport",
        status: "Next up",
        horizon: "Foundational",
        summary: "Use Tailscale as the private network layer so the phone app feels personal and direct instead of exposed and fragile.",
        detail: "This checkpoint is about secure pairing, clean session handoff, and making the phone feel like an extension of your Thomas machine rather than a second-class remote UI glued on afterward.",
        signals: ["Tailscale-based private network model", "Clean pairing and rekey story", "No public-cloud bypass around the Thomas core"],
        tone: "build",
        featured: true,
      },
      {
        id: "infinite-surfaces",
        title: "Headless app surfaces on demand",
        status: "Designing",
        horizon: "App factory layer",
        summary: "Thomas should be able to spin up job-specific interfaces instead of forcing every use case through one generic chat screen.",
        detail: "The vision is that Thomas can produce focused, headless web apps for a workflow, then deliver those surfaces privately to the phone app. That turns Thomas from one interface into a generator of interfaces.",
        signals: ["Workflow-specific mobile surfaces", "Headless website packaging over private transport", "Generated interfaces tied to Thomas runtime state"],
        tone: "build",
      },
      {
        id: "infinite-ops",
        title: "Approvals, queues, and live status",
        status: "Designing",
        horizon: "Operational layer",
        summary: "The phone experience should make Thomas more actionable, not just more visible.",
        detail: "This checkpoint turns the phone app into the best place to approve risky actions, review status, inspect results, and queue work while keeping execution grounded in the main Thomas runtime.",
        signals: ["Approval queue on mobile", "Live run state and result review", "Command handoff without breaking policy boundaries"],
        tone: "build",
      },
      {
        id: "infinite-handoff",
        title: "Deep-link handoff between web, desktop, and phone",
        status: "Vision in focus",
        horizon: "System glue",
        summary: "Infinite becomes powerful when every Thomas surface can hand work to the next surface without context loss.",
        detail: "That means mobile actions can wake the right local workflow, desktop surfaces can publish the right headless app, and Thomas keeps one coherent execution story across them all.",
        signals: ["Shared runtime identity across surfaces", "Cross-surface session handoff", "Phone app as a serious control surface"],
        tone: "vision",
      },
    ],
  },
  {
    id: "thomas-os",
    phase: "Phase 03",
    status: "Long-range bet",
    title: "Thomas OS",
    horizon: "AI-native Linux system",
    intro: "Stop treating AI as a layer above the computer and start building the computer around AI-native workflows from day one.",
    body: "Thomas OS is the idea that the shell, session model, app model, trust system, and operator controls should all be designed together. Not an assistant bolted onto Linux afterward, but a Linux-based system whose personality is already shaped around explicit intent, delegation, recoverability, and visibility.",
    outcome: "Thomas stops being only a product on top of an operating system and becomes the operating environment itself: AI-native, operator-controlled, and designed for real work instead of novelty demos.",
    repoSignals: ["Control-first philosophy", "Local-first runtime", "Recoverability obsession", "Operator-visible automation"],
    checkpoints: [
      {
        id: "os-session-model",
        title: "AI-native session and intent model",
        status: "Long bet",
        horizon: "Core systems layer",
        summary: "The operating system should understand tasks, intent, approvals, and delegated work as native concepts rather than ad hoc app logic.",
        detail: "This is where Thomas ideas like command families, approval gates, and persistent mission state would stop living inside one app and start shaping the entire computing environment.",
        signals: ["Intent-aware system shell", "Session memory as a native operating-system primitive", "Task routing built into the environment"],
        tone: "vision",
        featured: true,
      },
      {
        id: "os-surfaces",
        title: "Apps become generated operating surfaces",
        status: "Long bet",
        horizon: "UI model",
        summary: "Thomas-generated surfaces should feel like first-class apps because the operating system itself is designed for that behavior.",
        detail: "Instead of building every app conventionally, Thomas OS would let the system compose interfaces, automate flows, and expose specialized workspaces as part of normal operation.",
        signals: ["Generated interfaces as first-class citizens", "Delegated workflows reflected in system UI", "Less app-switching, more mission-switching"],
        tone: "vision",
      },
      {
        id: "os-trust",
        title: "Policy, recovery, and rollback at the operating-system layer",
        status: "Long bet",
        horizon: "Trust model",
        summary: "The whole point of Thomas survives only if the trust model scales with it.",
        detail: "Operator visibility, sandboxing, rollback, and auditability cannot disappear when the system gets bigger. Thomas OS only matters if the safety and recovery story gets stronger as the surface expands.",
        signals: ["Operating-system-level approval and rollback model", "Recoverability as a product feature", "Security posture built into the workflow engine"],
        tone: "vision",
      },
      {
        id: "os-environment",
        title: "Thomas as the operating environment",
        status: "Destination",
        horizon: "End state",
        summary: "This is where Thomas stops helping with the computer and starts being the way the computer works.",
        detail: "The long bet is a Linux-based operating environment where Thomas is not a sidecar. It is the shell, the app model, the workflow engine, the policy system, and the operator interface all at once.",
        signals: ["System-wide mission control", "AI-native operating surface", "Operator-visible automation as a default"],
        tone: "vision",
      },
    ],
  },
];

export default function RoadmapPage() {
  return <RoadmapShell chapters={roadmapChapters} repoSnapshot={repoSnapshot} />;
}